import * as _148 from "./abci/types";
import * as _149 from "./crypto/keys";
import * as _150 from "./crypto/proof";
import * as _151 from "./libs/bits/types";
import * as _152 from "./p2p/types";
import * as _153 from "./types/block";
import * as _154 from "./types/evidence";
import * as _155 from "./types/params";
import * as _156 from "./types/types";
import * as _157 from "./types/validator";
import * as _158 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _148.CheckTxType;
        checkTxTypeToJSON(object: _148.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _148.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _148.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _148.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _148.ResponseApplySnapshotChunk_Result): string;
        responseProcessProposal_ProposalStatusFromJSON(object: any): _148.ResponseProcessProposal_ProposalStatus;
        responseProcessProposal_ProposalStatusToJSON(object: _148.ResponseProcessProposal_ProposalStatus): string;
        misbehaviorTypeFromJSON(object: any): _148.MisbehaviorType;
        misbehaviorTypeToJSON(object: _148.MisbehaviorType): string;
        CheckTxType: typeof _148.CheckTxType;
        CheckTxTypeSDKType: typeof _148.CheckTxType;
        CheckTxTypeAmino: typeof _148.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _148.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _148.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _148.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _148.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _148.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _148.ResponseApplySnapshotChunk_Result;
        ResponseProcessProposal_ProposalStatus: typeof _148.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusSDKType: typeof _148.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusAmino: typeof _148.ResponseProcessProposal_ProposalStatus;
        MisbehaviorType: typeof _148.MisbehaviorType;
        MisbehaviorTypeSDKType: typeof _148.MisbehaviorType;
        MisbehaviorTypeAmino: typeof _148.MisbehaviorType;
        Request: {
            typeUrl: string;
            encode(message: _148.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.Request;
            fromPartial(object: Partial<_148.Request>): _148.Request;
            fromAmino(object: _148.RequestAmino): _148.Request;
            toAmino(message: _148.Request): _148.RequestAmino;
            fromAminoMsg(object: _148.RequestAminoMsg): _148.Request;
            fromProtoMsg(message: _148.RequestProtoMsg): _148.Request;
            toProto(message: _148.Request): Uint8Array;
            toProtoMsg(message: _148.Request): _148.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _148.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestEcho;
            fromPartial(object: Partial<_148.RequestEcho>): _148.RequestEcho;
            fromAmino(object: _148.RequestEchoAmino): _148.RequestEcho;
            toAmino(message: _148.RequestEcho): _148.RequestEchoAmino;
            fromAminoMsg(object: _148.RequestEchoAminoMsg): _148.RequestEcho;
            fromProtoMsg(message: _148.RequestEchoProtoMsg): _148.RequestEcho;
            toProto(message: _148.RequestEcho): Uint8Array;
            toProtoMsg(message: _148.RequestEcho): _148.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _148.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _148.RequestFlush;
            fromPartial(_: Partial<_148.RequestFlush>): _148.RequestFlush;
            fromAmino(_: _148.RequestFlushAmino): _148.RequestFlush;
            toAmino(_: _148.RequestFlush): _148.RequestFlushAmino;
            fromAminoMsg(object: _148.RequestFlushAminoMsg): _148.RequestFlush;
            fromProtoMsg(message: _148.RequestFlushProtoMsg): _148.RequestFlush;
            toProto(message: _148.RequestFlush): Uint8Array;
            toProtoMsg(message: _148.RequestFlush): _148.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _148.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestInfo;
            fromPartial(object: Partial<_148.RequestInfo>): _148.RequestInfo;
            fromAmino(object: _148.RequestInfoAmino): _148.RequestInfo;
            toAmino(message: _148.RequestInfo): _148.RequestInfoAmino;
            fromAminoMsg(object: _148.RequestInfoAminoMsg): _148.RequestInfo;
            fromProtoMsg(message: _148.RequestInfoProtoMsg): _148.RequestInfo;
            toProto(message: _148.RequestInfo): Uint8Array;
            toProtoMsg(message: _148.RequestInfo): _148.RequestInfoProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _148.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestInitChain;
            fromPartial(object: Partial<_148.RequestInitChain>): _148.RequestInitChain;
            fromAmino(object: _148.RequestInitChainAmino): _148.RequestInitChain;
            toAmino(message: _148.RequestInitChain): _148.RequestInitChainAmino;
            fromAminoMsg(object: _148.RequestInitChainAminoMsg): _148.RequestInitChain;
            fromProtoMsg(message: _148.RequestInitChainProtoMsg): _148.RequestInitChain;
            toProto(message: _148.RequestInitChain): Uint8Array;
            toProtoMsg(message: _148.RequestInitChain): _148.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _148.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestQuery;
            fromPartial(object: Partial<_148.RequestQuery>): _148.RequestQuery;
            fromAmino(object: _148.RequestQueryAmino): _148.RequestQuery;
            toAmino(message: _148.RequestQuery): _148.RequestQueryAmino;
            fromAminoMsg(object: _148.RequestQueryAminoMsg): _148.RequestQuery;
            fromProtoMsg(message: _148.RequestQueryProtoMsg): _148.RequestQuery;
            toProto(message: _148.RequestQuery): Uint8Array;
            toProtoMsg(message: _148.RequestQuery): _148.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _148.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestBeginBlock;
            fromPartial(object: Partial<_148.RequestBeginBlock>): _148.RequestBeginBlock;
            fromAmino(object: _148.RequestBeginBlockAmino): _148.RequestBeginBlock;
            toAmino(message: _148.RequestBeginBlock): _148.RequestBeginBlockAmino;
            fromAminoMsg(object: _148.RequestBeginBlockAminoMsg): _148.RequestBeginBlock;
            fromProtoMsg(message: _148.RequestBeginBlockProtoMsg): _148.RequestBeginBlock;
            toProto(message: _148.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _148.RequestBeginBlock): _148.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _148.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestCheckTx;
            fromPartial(object: Partial<_148.RequestCheckTx>): _148.RequestCheckTx;
            fromAmino(object: _148.RequestCheckTxAmino): _148.RequestCheckTx;
            toAmino(message: _148.RequestCheckTx): _148.RequestCheckTxAmino;
            fromAminoMsg(object: _148.RequestCheckTxAminoMsg): _148.RequestCheckTx;
            fromProtoMsg(message: _148.RequestCheckTxProtoMsg): _148.RequestCheckTx;
            toProto(message: _148.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _148.RequestCheckTx): _148.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _148.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestDeliverTx;
            fromPartial(object: Partial<_148.RequestDeliverTx>): _148.RequestDeliverTx;
            fromAmino(object: _148.RequestDeliverTxAmino): _148.RequestDeliverTx;
            toAmino(message: _148.RequestDeliverTx): _148.RequestDeliverTxAmino;
            fromAminoMsg(object: _148.RequestDeliverTxAminoMsg): _148.RequestDeliverTx;
            fromProtoMsg(message: _148.RequestDeliverTxProtoMsg): _148.RequestDeliverTx;
            toProto(message: _148.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _148.RequestDeliverTx): _148.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _148.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestEndBlock;
            fromPartial(object: Partial<_148.RequestEndBlock>): _148.RequestEndBlock;
            fromAmino(object: _148.RequestEndBlockAmino): _148.RequestEndBlock;
            toAmino(message: _148.RequestEndBlock): _148.RequestEndBlockAmino;
            fromAminoMsg(object: _148.RequestEndBlockAminoMsg): _148.RequestEndBlock;
            fromProtoMsg(message: _148.RequestEndBlockProtoMsg): _148.RequestEndBlock;
            toProto(message: _148.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _148.RequestEndBlock): _148.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _148.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _148.RequestCommit;
            fromPartial(_: Partial<_148.RequestCommit>): _148.RequestCommit;
            fromAmino(_: _148.RequestCommitAmino): _148.RequestCommit;
            toAmino(_: _148.RequestCommit): _148.RequestCommitAmino;
            fromAminoMsg(object: _148.RequestCommitAminoMsg): _148.RequestCommit;
            fromProtoMsg(message: _148.RequestCommitProtoMsg): _148.RequestCommit;
            toProto(message: _148.RequestCommit): Uint8Array;
            toProtoMsg(message: _148.RequestCommit): _148.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _148.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _148.RequestListSnapshots;
            fromPartial(_: Partial<_148.RequestListSnapshots>): _148.RequestListSnapshots;
            fromAmino(_: _148.RequestListSnapshotsAmino): _148.RequestListSnapshots;
            toAmino(_: _148.RequestListSnapshots): _148.RequestListSnapshotsAmino;
            fromAminoMsg(object: _148.RequestListSnapshotsAminoMsg): _148.RequestListSnapshots;
            fromProtoMsg(message: _148.RequestListSnapshotsProtoMsg): _148.RequestListSnapshots;
            toProto(message: _148.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _148.RequestListSnapshots): _148.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _148.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestOfferSnapshot;
            fromPartial(object: Partial<_148.RequestOfferSnapshot>): _148.RequestOfferSnapshot;
            fromAmino(object: _148.RequestOfferSnapshotAmino): _148.RequestOfferSnapshot;
            toAmino(message: _148.RequestOfferSnapshot): _148.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _148.RequestOfferSnapshotAminoMsg): _148.RequestOfferSnapshot;
            fromProtoMsg(message: _148.RequestOfferSnapshotProtoMsg): _148.RequestOfferSnapshot;
            toProto(message: _148.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _148.RequestOfferSnapshot): _148.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _148.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_148.RequestLoadSnapshotChunk>): _148.RequestLoadSnapshotChunk;
            fromAmino(object: _148.RequestLoadSnapshotChunkAmino): _148.RequestLoadSnapshotChunk;
            toAmino(message: _148.RequestLoadSnapshotChunk): _148.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _148.RequestLoadSnapshotChunkAminoMsg): _148.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _148.RequestLoadSnapshotChunkProtoMsg): _148.RequestLoadSnapshotChunk;
            toProto(message: _148.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _148.RequestLoadSnapshotChunk): _148.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _148.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_148.RequestApplySnapshotChunk>): _148.RequestApplySnapshotChunk;
            fromAmino(object: _148.RequestApplySnapshotChunkAmino): _148.RequestApplySnapshotChunk;
            toAmino(message: _148.RequestApplySnapshotChunk): _148.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _148.RequestApplySnapshotChunkAminoMsg): _148.RequestApplySnapshotChunk;
            fromProtoMsg(message: _148.RequestApplySnapshotChunkProtoMsg): _148.RequestApplySnapshotChunk;
            toProto(message: _148.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _148.RequestApplySnapshotChunk): _148.RequestApplySnapshotChunkProtoMsg;
        };
        RequestPrepareProposal: {
            typeUrl: string;
            encode(message: _148.RequestPrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestPrepareProposal;
            fromPartial(object: Partial<_148.RequestPrepareProposal>): _148.RequestPrepareProposal;
            fromAmino(object: _148.RequestPrepareProposalAmino): _148.RequestPrepareProposal;
            toAmino(message: _148.RequestPrepareProposal): _148.RequestPrepareProposalAmino;
            fromAminoMsg(object: _148.RequestPrepareProposalAminoMsg): _148.RequestPrepareProposal;
            fromProtoMsg(message: _148.RequestPrepareProposalProtoMsg): _148.RequestPrepareProposal;
            toProto(message: _148.RequestPrepareProposal): Uint8Array;
            toProtoMsg(message: _148.RequestPrepareProposal): _148.RequestPrepareProposalProtoMsg;
        };
        RequestProcessProposal: {
            typeUrl: string;
            encode(message: _148.RequestProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.RequestProcessProposal;
            fromPartial(object: Partial<_148.RequestProcessProposal>): _148.RequestProcessProposal;
            fromAmino(object: _148.RequestProcessProposalAmino): _148.RequestProcessProposal;
            toAmino(message: _148.RequestProcessProposal): _148.RequestProcessProposalAmino;
            fromAminoMsg(object: _148.RequestProcessProposalAminoMsg): _148.RequestProcessProposal;
            fromProtoMsg(message: _148.RequestProcessProposalProtoMsg): _148.RequestProcessProposal;
            toProto(message: _148.RequestProcessProposal): Uint8Array;
            toProtoMsg(message: _148.RequestProcessProposal): _148.RequestProcessProposalProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _148.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.Response;
            fromPartial(object: Partial<_148.Response>): _148.Response;
            fromAmino(object: _148.ResponseAmino): _148.Response;
            toAmino(message: _148.Response): _148.ResponseAmino;
            fromAminoMsg(object: _148.ResponseAminoMsg): _148.Response;
            fromProtoMsg(message: _148.ResponseProtoMsg): _148.Response;
            toProto(message: _148.Response): Uint8Array;
            toProtoMsg(message: _148.Response): _148.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _148.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseException;
            fromPartial(object: Partial<_148.ResponseException>): _148.ResponseException;
            fromAmino(object: _148.ResponseExceptionAmino): _148.ResponseException;
            toAmino(message: _148.ResponseException): _148.ResponseExceptionAmino;
            fromAminoMsg(object: _148.ResponseExceptionAminoMsg): _148.ResponseException;
            fromProtoMsg(message: _148.ResponseExceptionProtoMsg): _148.ResponseException;
            toProto(message: _148.ResponseException): Uint8Array;
            toProtoMsg(message: _148.ResponseException): _148.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _148.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseEcho;
            fromPartial(object: Partial<_148.ResponseEcho>): _148.ResponseEcho;
            fromAmino(object: _148.ResponseEchoAmino): _148.ResponseEcho;
            toAmino(message: _148.ResponseEcho): _148.ResponseEchoAmino;
            fromAminoMsg(object: _148.ResponseEchoAminoMsg): _148.ResponseEcho;
            fromProtoMsg(message: _148.ResponseEchoProtoMsg): _148.ResponseEcho;
            toProto(message: _148.ResponseEcho): Uint8Array;
            toProtoMsg(message: _148.ResponseEcho): _148.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _148.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _148.ResponseFlush;
            fromPartial(_: Partial<_148.ResponseFlush>): _148.ResponseFlush;
            fromAmino(_: _148.ResponseFlushAmino): _148.ResponseFlush;
            toAmino(_: _148.ResponseFlush): _148.ResponseFlushAmino;
            fromAminoMsg(object: _148.ResponseFlushAminoMsg): _148.ResponseFlush;
            fromProtoMsg(message: _148.ResponseFlushProtoMsg): _148.ResponseFlush;
            toProto(message: _148.ResponseFlush): Uint8Array;
            toProtoMsg(message: _148.ResponseFlush): _148.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _148.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseInfo;
            fromPartial(object: Partial<_148.ResponseInfo>): _148.ResponseInfo;
            fromAmino(object: _148.ResponseInfoAmino): _148.ResponseInfo;
            toAmino(message: _148.ResponseInfo): _148.ResponseInfoAmino;
            fromAminoMsg(object: _148.ResponseInfoAminoMsg): _148.ResponseInfo;
            fromProtoMsg(message: _148.ResponseInfoProtoMsg): _148.ResponseInfo;
            toProto(message: _148.ResponseInfo): Uint8Array;
            toProtoMsg(message: _148.ResponseInfo): _148.ResponseInfoProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _148.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseInitChain;
            fromPartial(object: Partial<_148.ResponseInitChain>): _148.ResponseInitChain;
            fromAmino(object: _148.ResponseInitChainAmino): _148.ResponseInitChain;
            toAmino(message: _148.ResponseInitChain): _148.ResponseInitChainAmino;
            fromAminoMsg(object: _148.ResponseInitChainAminoMsg): _148.ResponseInitChain;
            fromProtoMsg(message: _148.ResponseInitChainProtoMsg): _148.ResponseInitChain;
            toProto(message: _148.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _148.ResponseInitChain): _148.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _148.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseQuery;
            fromPartial(object: Partial<_148.ResponseQuery>): _148.ResponseQuery;
            fromAmino(object: _148.ResponseQueryAmino): _148.ResponseQuery;
            toAmino(message: _148.ResponseQuery): _148.ResponseQueryAmino;
            fromAminoMsg(object: _148.ResponseQueryAminoMsg): _148.ResponseQuery;
            fromProtoMsg(message: _148.ResponseQueryProtoMsg): _148.ResponseQuery;
            toProto(message: _148.ResponseQuery): Uint8Array;
            toProtoMsg(message: _148.ResponseQuery): _148.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _148.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseBeginBlock;
            fromPartial(object: Partial<_148.ResponseBeginBlock>): _148.ResponseBeginBlock;
            fromAmino(object: _148.ResponseBeginBlockAmino): _148.ResponseBeginBlock;
            toAmino(message: _148.ResponseBeginBlock): _148.ResponseBeginBlockAmino;
            fromAminoMsg(object: _148.ResponseBeginBlockAminoMsg): _148.ResponseBeginBlock;
            fromProtoMsg(message: _148.ResponseBeginBlockProtoMsg): _148.ResponseBeginBlock;
            toProto(message: _148.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _148.ResponseBeginBlock): _148.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _148.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseCheckTx;
            fromPartial(object: Partial<_148.ResponseCheckTx>): _148.ResponseCheckTx;
            fromAmino(object: _148.ResponseCheckTxAmino): _148.ResponseCheckTx;
            toAmino(message: _148.ResponseCheckTx): _148.ResponseCheckTxAmino;
            fromAminoMsg(object: _148.ResponseCheckTxAminoMsg): _148.ResponseCheckTx;
            fromProtoMsg(message: _148.ResponseCheckTxProtoMsg): _148.ResponseCheckTx;
            toProto(message: _148.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _148.ResponseCheckTx): _148.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _148.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseDeliverTx;
            fromPartial(object: Partial<_148.ResponseDeliverTx>): _148.ResponseDeliverTx;
            fromAmino(object: _148.ResponseDeliverTxAmino): _148.ResponseDeliverTx;
            toAmino(message: _148.ResponseDeliverTx): _148.ResponseDeliverTxAmino;
            fromAminoMsg(object: _148.ResponseDeliverTxAminoMsg): _148.ResponseDeliverTx;
            fromProtoMsg(message: _148.ResponseDeliverTxProtoMsg): _148.ResponseDeliverTx;
            toProto(message: _148.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _148.ResponseDeliverTx): _148.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _148.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseEndBlock;
            fromPartial(object: Partial<_148.ResponseEndBlock>): _148.ResponseEndBlock;
            fromAmino(object: _148.ResponseEndBlockAmino): _148.ResponseEndBlock;
            toAmino(message: _148.ResponseEndBlock): _148.ResponseEndBlockAmino;
            fromAminoMsg(object: _148.ResponseEndBlockAminoMsg): _148.ResponseEndBlock;
            fromProtoMsg(message: _148.ResponseEndBlockProtoMsg): _148.ResponseEndBlock;
            toProto(message: _148.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _148.ResponseEndBlock): _148.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _148.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseCommit;
            fromPartial(object: Partial<_148.ResponseCommit>): _148.ResponseCommit;
            fromAmino(object: _148.ResponseCommitAmino): _148.ResponseCommit;
            toAmino(message: _148.ResponseCommit): _148.ResponseCommitAmino;
            fromAminoMsg(object: _148.ResponseCommitAminoMsg): _148.ResponseCommit;
            fromProtoMsg(message: _148.ResponseCommitProtoMsg): _148.ResponseCommit;
            toProto(message: _148.ResponseCommit): Uint8Array;
            toProtoMsg(message: _148.ResponseCommit): _148.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _148.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseListSnapshots;
            fromPartial(object: Partial<_148.ResponseListSnapshots>): _148.ResponseListSnapshots;
            fromAmino(object: _148.ResponseListSnapshotsAmino): _148.ResponseListSnapshots;
            toAmino(message: _148.ResponseListSnapshots): _148.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _148.ResponseListSnapshotsAminoMsg): _148.ResponseListSnapshots;
            fromProtoMsg(message: _148.ResponseListSnapshotsProtoMsg): _148.ResponseListSnapshots;
            toProto(message: _148.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _148.ResponseListSnapshots): _148.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _148.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseOfferSnapshot;
            fromPartial(object: Partial<_148.ResponseOfferSnapshot>): _148.ResponseOfferSnapshot;
            fromAmino(object: _148.ResponseOfferSnapshotAmino): _148.ResponseOfferSnapshot;
            toAmino(message: _148.ResponseOfferSnapshot): _148.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _148.ResponseOfferSnapshotAminoMsg): _148.ResponseOfferSnapshot;
            fromProtoMsg(message: _148.ResponseOfferSnapshotProtoMsg): _148.ResponseOfferSnapshot;
            toProto(message: _148.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _148.ResponseOfferSnapshot): _148.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _148.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_148.ResponseLoadSnapshotChunk>): _148.ResponseLoadSnapshotChunk;
            fromAmino(object: _148.ResponseLoadSnapshotChunkAmino): _148.ResponseLoadSnapshotChunk;
            toAmino(message: _148.ResponseLoadSnapshotChunk): _148.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _148.ResponseLoadSnapshotChunkAminoMsg): _148.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _148.ResponseLoadSnapshotChunkProtoMsg): _148.ResponseLoadSnapshotChunk;
            toProto(message: _148.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _148.ResponseLoadSnapshotChunk): _148.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _148.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_148.ResponseApplySnapshotChunk>): _148.ResponseApplySnapshotChunk;
            fromAmino(object: _148.ResponseApplySnapshotChunkAmino): _148.ResponseApplySnapshotChunk;
            toAmino(message: _148.ResponseApplySnapshotChunk): _148.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _148.ResponseApplySnapshotChunkAminoMsg): _148.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _148.ResponseApplySnapshotChunkProtoMsg): _148.ResponseApplySnapshotChunk;
            toProto(message: _148.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _148.ResponseApplySnapshotChunk): _148.ResponseApplySnapshotChunkProtoMsg;
        };
        ResponsePrepareProposal: {
            typeUrl: string;
            encode(message: _148.ResponsePrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponsePrepareProposal;
            fromPartial(object: Partial<_148.ResponsePrepareProposal>): _148.ResponsePrepareProposal;
            fromAmino(object: _148.ResponsePrepareProposalAmino): _148.ResponsePrepareProposal;
            toAmino(message: _148.ResponsePrepareProposal): _148.ResponsePrepareProposalAmino;
            fromAminoMsg(object: _148.ResponsePrepareProposalAminoMsg): _148.ResponsePrepareProposal;
            fromProtoMsg(message: _148.ResponsePrepareProposalProtoMsg): _148.ResponsePrepareProposal;
            toProto(message: _148.ResponsePrepareProposal): Uint8Array;
            toProtoMsg(message: _148.ResponsePrepareProposal): _148.ResponsePrepareProposalProtoMsg;
        };
        ResponseProcessProposal: {
            typeUrl: string;
            encode(message: _148.ResponseProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ResponseProcessProposal;
            fromPartial(object: Partial<_148.ResponseProcessProposal>): _148.ResponseProcessProposal;
            fromAmino(object: _148.ResponseProcessProposalAmino): _148.ResponseProcessProposal;
            toAmino(message: _148.ResponseProcessProposal): _148.ResponseProcessProposalAmino;
            fromAminoMsg(object: _148.ResponseProcessProposalAminoMsg): _148.ResponseProcessProposal;
            fromProtoMsg(message: _148.ResponseProcessProposalProtoMsg): _148.ResponseProcessProposal;
            toProto(message: _148.ResponseProcessProposal): Uint8Array;
            toProtoMsg(message: _148.ResponseProcessProposal): _148.ResponseProcessProposalProtoMsg;
        };
        CommitInfo: {
            typeUrl: string;
            encode(message: _148.CommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.CommitInfo;
            fromPartial(object: Partial<_148.CommitInfo>): _148.CommitInfo;
            fromAmino(object: _148.CommitInfoAmino): _148.CommitInfo;
            toAmino(message: _148.CommitInfo): _148.CommitInfoAmino;
            fromAminoMsg(object: _148.CommitInfoAminoMsg): _148.CommitInfo;
            fromProtoMsg(message: _148.CommitInfoProtoMsg): _148.CommitInfo;
            toProto(message: _148.CommitInfo): Uint8Array;
            toProtoMsg(message: _148.CommitInfo): _148.CommitInfoProtoMsg;
        };
        ExtendedCommitInfo: {
            typeUrl: string;
            encode(message: _148.ExtendedCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ExtendedCommitInfo;
            fromPartial(object: Partial<_148.ExtendedCommitInfo>): _148.ExtendedCommitInfo;
            fromAmino(object: _148.ExtendedCommitInfoAmino): _148.ExtendedCommitInfo;
            toAmino(message: _148.ExtendedCommitInfo): _148.ExtendedCommitInfoAmino;
            fromAminoMsg(object: _148.ExtendedCommitInfoAminoMsg): _148.ExtendedCommitInfo;
            fromProtoMsg(message: _148.ExtendedCommitInfoProtoMsg): _148.ExtendedCommitInfo;
            toProto(message: _148.ExtendedCommitInfo): Uint8Array;
            toProtoMsg(message: _148.ExtendedCommitInfo): _148.ExtendedCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _148.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.Event;
            fromPartial(object: Partial<_148.Event>): _148.Event;
            fromAmino(object: _148.EventAmino): _148.Event;
            toAmino(message: _148.Event): _148.EventAmino;
            fromAminoMsg(object: _148.EventAminoMsg): _148.Event;
            fromProtoMsg(message: _148.EventProtoMsg): _148.Event;
            toProto(message: _148.Event): Uint8Array;
            toProtoMsg(message: _148.Event): _148.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _148.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.EventAttribute;
            fromPartial(object: Partial<_148.EventAttribute>): _148.EventAttribute;
            fromAmino(object: _148.EventAttributeAmino): _148.EventAttribute;
            toAmino(message: _148.EventAttribute): _148.EventAttributeAmino;
            fromAminoMsg(object: _148.EventAttributeAminoMsg): _148.EventAttribute;
            fromProtoMsg(message: _148.EventAttributeProtoMsg): _148.EventAttribute;
            toProto(message: _148.EventAttribute): Uint8Array;
            toProtoMsg(message: _148.EventAttribute): _148.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _148.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.TxResult;
            fromPartial(object: Partial<_148.TxResult>): _148.TxResult;
            fromAmino(object: _148.TxResultAmino): _148.TxResult;
            toAmino(message: _148.TxResult): _148.TxResultAmino;
            fromAminoMsg(object: _148.TxResultAminoMsg): _148.TxResult;
            fromProtoMsg(message: _148.TxResultProtoMsg): _148.TxResult;
            toProto(message: _148.TxResult): Uint8Array;
            toProtoMsg(message: _148.TxResult): _148.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _148.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.Validator;
            fromPartial(object: Partial<_148.Validator>): _148.Validator;
            fromAmino(object: _148.ValidatorAmino): _148.Validator;
            toAmino(message: _148.Validator): _148.ValidatorAmino;
            fromAminoMsg(object: _148.ValidatorAminoMsg): _148.Validator;
            fromProtoMsg(message: _148.ValidatorProtoMsg): _148.Validator;
            toProto(message: _148.Validator): Uint8Array;
            toProtoMsg(message: _148.Validator): _148.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _148.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ValidatorUpdate;
            fromPartial(object: Partial<_148.ValidatorUpdate>): _148.ValidatorUpdate;
            fromAmino(object: _148.ValidatorUpdateAmino): _148.ValidatorUpdate;
            toAmino(message: _148.ValidatorUpdate): _148.ValidatorUpdateAmino;
            fromAminoMsg(object: _148.ValidatorUpdateAminoMsg): _148.ValidatorUpdate;
            fromProtoMsg(message: _148.ValidatorUpdateProtoMsg): _148.ValidatorUpdate;
            toProto(message: _148.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _148.ValidatorUpdate): _148.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _148.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.VoteInfo;
            fromPartial(object: Partial<_148.VoteInfo>): _148.VoteInfo;
            fromAmino(object: _148.VoteInfoAmino): _148.VoteInfo;
            toAmino(message: _148.VoteInfo): _148.VoteInfoAmino;
            fromAminoMsg(object: _148.VoteInfoAminoMsg): _148.VoteInfo;
            fromProtoMsg(message: _148.VoteInfoProtoMsg): _148.VoteInfo;
            toProto(message: _148.VoteInfo): Uint8Array;
            toProtoMsg(message: _148.VoteInfo): _148.VoteInfoProtoMsg;
        };
        ExtendedVoteInfo: {
            typeUrl: string;
            encode(message: _148.ExtendedVoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.ExtendedVoteInfo;
            fromPartial(object: Partial<_148.ExtendedVoteInfo>): _148.ExtendedVoteInfo;
            fromAmino(object: _148.ExtendedVoteInfoAmino): _148.ExtendedVoteInfo;
            toAmino(message: _148.ExtendedVoteInfo): _148.ExtendedVoteInfoAmino;
            fromAminoMsg(object: _148.ExtendedVoteInfoAminoMsg): _148.ExtendedVoteInfo;
            fromProtoMsg(message: _148.ExtendedVoteInfoProtoMsg): _148.ExtendedVoteInfo;
            toProto(message: _148.ExtendedVoteInfo): Uint8Array;
            toProtoMsg(message: _148.ExtendedVoteInfo): _148.ExtendedVoteInfoProtoMsg;
        };
        Misbehavior: {
            typeUrl: string;
            encode(message: _148.Misbehavior, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.Misbehavior;
            fromPartial(object: Partial<_148.Misbehavior>): _148.Misbehavior;
            fromAmino(object: _148.MisbehaviorAmino): _148.Misbehavior;
            toAmino(message: _148.Misbehavior): _148.MisbehaviorAmino;
            fromAminoMsg(object: _148.MisbehaviorAminoMsg): _148.Misbehavior;
            fromProtoMsg(message: _148.MisbehaviorProtoMsg): _148.Misbehavior;
            toProto(message: _148.Misbehavior): Uint8Array;
            toProtoMsg(message: _148.Misbehavior): _148.MisbehaviorProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _148.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.Snapshot;
            fromPartial(object: Partial<_148.Snapshot>): _148.Snapshot;
            fromAmino(object: _148.SnapshotAmino): _148.Snapshot;
            toAmino(message: _148.Snapshot): _148.SnapshotAmino;
            fromAminoMsg(object: _148.SnapshotAminoMsg): _148.Snapshot;
            fromProtoMsg(message: _148.SnapshotProtoMsg): _148.Snapshot;
            toProto(message: _148.Snapshot): Uint8Array;
            toProtoMsg(message: _148.Snapshot): _148.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _150.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.Proof;
            fromPartial(object: Partial<_150.Proof>): _150.Proof;
            fromAmino(object: _150.ProofAmino): _150.Proof;
            toAmino(message: _150.Proof): _150.ProofAmino;
            fromAminoMsg(object: _150.ProofAminoMsg): _150.Proof;
            fromProtoMsg(message: _150.ProofProtoMsg): _150.Proof;
            toProto(message: _150.Proof): Uint8Array;
            toProtoMsg(message: _150.Proof): _150.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _150.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.ValueOp;
            fromPartial(object: Partial<_150.ValueOp>): _150.ValueOp;
            fromAmino(object: _150.ValueOpAmino): _150.ValueOp;
            toAmino(message: _150.ValueOp): _150.ValueOpAmino;
            fromAminoMsg(object: _150.ValueOpAminoMsg): _150.ValueOp;
            fromProtoMsg(message: _150.ValueOpProtoMsg): _150.ValueOp;
            toProto(message: _150.ValueOp): Uint8Array;
            toProtoMsg(message: _150.ValueOp): _150.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _150.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.DominoOp;
            fromPartial(object: Partial<_150.DominoOp>): _150.DominoOp;
            fromAmino(object: _150.DominoOpAmino): _150.DominoOp;
            toAmino(message: _150.DominoOp): _150.DominoOpAmino;
            fromAminoMsg(object: _150.DominoOpAminoMsg): _150.DominoOp;
            fromProtoMsg(message: _150.DominoOpProtoMsg): _150.DominoOp;
            toProto(message: _150.DominoOp): Uint8Array;
            toProtoMsg(message: _150.DominoOp): _150.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _150.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.ProofOp;
            fromPartial(object: Partial<_150.ProofOp>): _150.ProofOp;
            fromAmino(object: _150.ProofOpAmino): _150.ProofOp;
            toAmino(message: _150.ProofOp): _150.ProofOpAmino;
            fromAminoMsg(object: _150.ProofOpAminoMsg): _150.ProofOp;
            fromProtoMsg(message: _150.ProofOpProtoMsg): _150.ProofOp;
            toProto(message: _150.ProofOp): Uint8Array;
            toProtoMsg(message: _150.ProofOp): _150.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _150.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.ProofOps;
            fromPartial(object: Partial<_150.ProofOps>): _150.ProofOps;
            fromAmino(object: _150.ProofOpsAmino): _150.ProofOps;
            toAmino(message: _150.ProofOps): _150.ProofOpsAmino;
            fromAminoMsg(object: _150.ProofOpsAminoMsg): _150.ProofOps;
            fromProtoMsg(message: _150.ProofOpsProtoMsg): _150.ProofOps;
            toProto(message: _150.ProofOps): Uint8Array;
            toProtoMsg(message: _150.ProofOps): _150.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _149.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _149.PublicKey;
            fromPartial(object: Partial<_149.PublicKey>): _149.PublicKey;
            fromAmino(object: _149.PublicKeyAmino): _149.PublicKey;
            toAmino(message: _149.PublicKey): _149.PublicKeyAmino;
            fromAminoMsg(object: _149.PublicKeyAminoMsg): _149.PublicKey;
            fromProtoMsg(message: _149.PublicKeyProtoMsg): _149.PublicKey;
            toProto(message: _149.PublicKey): Uint8Array;
            toProtoMsg(message: _149.PublicKey): _149.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _151.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                fromJSON(object: any): _151.BitArray;
                fromPartial(object: Partial<_151.BitArray>): _151.BitArray;
                fromAmino(object: _151.BitArrayAmino): _151.BitArray;
                toAmino(message: _151.BitArray): _151.BitArrayAmino;
                fromAminoMsg(object: _151.BitArrayAminoMsg): _151.BitArray;
                fromProtoMsg(message: _151.BitArrayProtoMsg): _151.BitArray;
                toProto(message: _151.BitArray): Uint8Array;
                toProtoMsg(message: _151.BitArray): _151.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _152.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.NetAddress;
            fromPartial(object: Partial<_152.NetAddress>): _152.NetAddress;
            fromAmino(object: _152.NetAddressAmino): _152.NetAddress;
            toAmino(message: _152.NetAddress): _152.NetAddressAmino;
            fromAminoMsg(object: _152.NetAddressAminoMsg): _152.NetAddress;
            fromProtoMsg(message: _152.NetAddressProtoMsg): _152.NetAddress;
            toProto(message: _152.NetAddress): Uint8Array;
            toProtoMsg(message: _152.NetAddress): _152.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _152.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ProtocolVersion;
            fromPartial(object: Partial<_152.ProtocolVersion>): _152.ProtocolVersion;
            fromAmino(object: _152.ProtocolVersionAmino): _152.ProtocolVersion;
            toAmino(message: _152.ProtocolVersion): _152.ProtocolVersionAmino;
            fromAminoMsg(object: _152.ProtocolVersionAminoMsg): _152.ProtocolVersion;
            fromProtoMsg(message: _152.ProtocolVersionProtoMsg): _152.ProtocolVersion;
            toProto(message: _152.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _152.ProtocolVersion): _152.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _152.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.DefaultNodeInfo;
            fromPartial(object: Partial<_152.DefaultNodeInfo>): _152.DefaultNodeInfo;
            fromAmino(object: _152.DefaultNodeInfoAmino): _152.DefaultNodeInfo;
            toAmino(message: _152.DefaultNodeInfo): _152.DefaultNodeInfoAmino;
            fromAminoMsg(object: _152.DefaultNodeInfoAminoMsg): _152.DefaultNodeInfo;
            fromProtoMsg(message: _152.DefaultNodeInfoProtoMsg): _152.DefaultNodeInfo;
            toProto(message: _152.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _152.DefaultNodeInfo): _152.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _152.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.DefaultNodeInfoOther;
            fromPartial(object: Partial<_152.DefaultNodeInfoOther>): _152.DefaultNodeInfoOther;
            fromAmino(object: _152.DefaultNodeInfoOtherAmino): _152.DefaultNodeInfoOther;
            toAmino(message: _152.DefaultNodeInfoOther): _152.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _152.DefaultNodeInfoOtherAminoMsg): _152.DefaultNodeInfoOther;
            fromProtoMsg(message: _152.DefaultNodeInfoOtherProtoMsg): _152.DefaultNodeInfoOther;
            toProto(message: _152.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _152.DefaultNodeInfoOther): _152.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _157.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _157.ValidatorSet;
            fromPartial(object: Partial<_157.ValidatorSet>): _157.ValidatorSet;
            fromAmino(object: _157.ValidatorSetAmino): _157.ValidatorSet;
            toAmino(message: _157.ValidatorSet): _157.ValidatorSetAmino;
            fromAminoMsg(object: _157.ValidatorSetAminoMsg): _157.ValidatorSet;
            fromProtoMsg(message: _157.ValidatorSetProtoMsg): _157.ValidatorSet;
            toProto(message: _157.ValidatorSet): Uint8Array;
            toProtoMsg(message: _157.ValidatorSet): _157.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _157.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _157.Validator;
            fromPartial(object: Partial<_157.Validator>): _157.Validator;
            fromAmino(object: _157.ValidatorAmino): _157.Validator;
            toAmino(message: _157.Validator): _157.ValidatorAmino;
            fromAminoMsg(object: _157.ValidatorAminoMsg): _157.Validator;
            fromProtoMsg(message: _157.ValidatorProtoMsg): _157.Validator;
            toProto(message: _157.Validator): Uint8Array;
            toProtoMsg(message: _157.Validator): _157.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _157.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _157.SimpleValidator;
            fromPartial(object: Partial<_157.SimpleValidator>): _157.SimpleValidator;
            fromAmino(object: _157.SimpleValidatorAmino): _157.SimpleValidator;
            toAmino(message: _157.SimpleValidator): _157.SimpleValidatorAmino;
            fromAminoMsg(object: _157.SimpleValidatorAminoMsg): _157.SimpleValidator;
            fromProtoMsg(message: _157.SimpleValidatorProtoMsg): _157.SimpleValidator;
            toProto(message: _157.SimpleValidator): Uint8Array;
            toProtoMsg(message: _157.SimpleValidator): _157.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _156.BlockIDFlag;
        blockIDFlagToJSON(object: _156.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _156.SignedMsgType;
        signedMsgTypeToJSON(object: _156.SignedMsgType): string;
        BlockIDFlag: typeof _156.BlockIDFlag;
        BlockIDFlagSDKType: typeof _156.BlockIDFlag;
        BlockIDFlagAmino: typeof _156.BlockIDFlag;
        SignedMsgType: typeof _156.SignedMsgType;
        SignedMsgTypeSDKType: typeof _156.SignedMsgType;
        SignedMsgTypeAmino: typeof _156.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _156.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.PartSetHeader;
            fromPartial(object: Partial<_156.PartSetHeader>): _156.PartSetHeader;
            fromAmino(object: _156.PartSetHeaderAmino): _156.PartSetHeader;
            toAmino(message: _156.PartSetHeader): _156.PartSetHeaderAmino;
            fromAminoMsg(object: _156.PartSetHeaderAminoMsg): _156.PartSetHeader;
            fromProtoMsg(message: _156.PartSetHeaderProtoMsg): _156.PartSetHeader;
            toProto(message: _156.PartSetHeader): Uint8Array;
            toProtoMsg(message: _156.PartSetHeader): _156.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _156.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.Part;
            fromPartial(object: Partial<_156.Part>): _156.Part;
            fromAmino(object: _156.PartAmino): _156.Part;
            toAmino(message: _156.Part): _156.PartAmino;
            fromAminoMsg(object: _156.PartAminoMsg): _156.Part;
            fromProtoMsg(message: _156.PartProtoMsg): _156.Part;
            toProto(message: _156.Part): Uint8Array;
            toProtoMsg(message: _156.Part): _156.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _156.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.BlockID;
            fromPartial(object: Partial<_156.BlockID>): _156.BlockID;
            fromAmino(object: _156.BlockIDAmino): _156.BlockID;
            toAmino(message: _156.BlockID): _156.BlockIDAmino;
            fromAminoMsg(object: _156.BlockIDAminoMsg): _156.BlockID;
            fromProtoMsg(message: _156.BlockIDProtoMsg): _156.BlockID;
            toProto(message: _156.BlockID): Uint8Array;
            toProtoMsg(message: _156.BlockID): _156.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _156.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.Header;
            fromPartial(object: Partial<_156.Header>): _156.Header;
            fromAmino(object: _156.HeaderAmino): _156.Header;
            toAmino(message: _156.Header): _156.HeaderAmino;
            fromAminoMsg(object: _156.HeaderAminoMsg): _156.Header;
            fromProtoMsg(message: _156.HeaderProtoMsg): _156.Header;
            toProto(message: _156.Header): Uint8Array;
            toProtoMsg(message: _156.Header): _156.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _156.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.Data;
            fromPartial(object: Partial<_156.Data>): _156.Data;
            fromAmino(object: _156.DataAmino): _156.Data;
            toAmino(message: _156.Data): _156.DataAmino;
            fromAminoMsg(object: _156.DataAminoMsg): _156.Data;
            fromProtoMsg(message: _156.DataProtoMsg): _156.Data;
            toProto(message: _156.Data): Uint8Array;
            toProtoMsg(message: _156.Data): _156.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _156.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.Vote;
            fromPartial(object: Partial<_156.Vote>): _156.Vote;
            fromAmino(object: _156.VoteAmino): _156.Vote;
            toAmino(message: _156.Vote): _156.VoteAmino;
            fromAminoMsg(object: _156.VoteAminoMsg): _156.Vote;
            fromProtoMsg(message: _156.VoteProtoMsg): _156.Vote;
            toProto(message: _156.Vote): Uint8Array;
            toProtoMsg(message: _156.Vote): _156.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _156.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.Commit;
            fromPartial(object: Partial<_156.Commit>): _156.Commit;
            fromAmino(object: _156.CommitAmino): _156.Commit;
            toAmino(message: _156.Commit): _156.CommitAmino;
            fromAminoMsg(object: _156.CommitAminoMsg): _156.Commit;
            fromProtoMsg(message: _156.CommitProtoMsg): _156.Commit;
            toProto(message: _156.Commit): Uint8Array;
            toProtoMsg(message: _156.Commit): _156.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _156.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.CommitSig;
            fromPartial(object: Partial<_156.CommitSig>): _156.CommitSig;
            fromAmino(object: _156.CommitSigAmino): _156.CommitSig;
            toAmino(message: _156.CommitSig): _156.CommitSigAmino;
            fromAminoMsg(object: _156.CommitSigAminoMsg): _156.CommitSig;
            fromProtoMsg(message: _156.CommitSigProtoMsg): _156.CommitSig;
            toProto(message: _156.CommitSig): Uint8Array;
            toProtoMsg(message: _156.CommitSig): _156.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _156.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.Proposal;
            fromPartial(object: Partial<_156.Proposal>): _156.Proposal;
            fromAmino(object: _156.ProposalAmino): _156.Proposal;
            toAmino(message: _156.Proposal): _156.ProposalAmino;
            fromAminoMsg(object: _156.ProposalAminoMsg): _156.Proposal;
            fromProtoMsg(message: _156.ProposalProtoMsg): _156.Proposal;
            toProto(message: _156.Proposal): Uint8Array;
            toProtoMsg(message: _156.Proposal): _156.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _156.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.SignedHeader;
            fromPartial(object: Partial<_156.SignedHeader>): _156.SignedHeader;
            fromAmino(object: _156.SignedHeaderAmino): _156.SignedHeader;
            toAmino(message: _156.SignedHeader): _156.SignedHeaderAmino;
            fromAminoMsg(object: _156.SignedHeaderAminoMsg): _156.SignedHeader;
            fromProtoMsg(message: _156.SignedHeaderProtoMsg): _156.SignedHeader;
            toProto(message: _156.SignedHeader): Uint8Array;
            toProtoMsg(message: _156.SignedHeader): _156.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _156.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.LightBlock;
            fromPartial(object: Partial<_156.LightBlock>): _156.LightBlock;
            fromAmino(object: _156.LightBlockAmino): _156.LightBlock;
            toAmino(message: _156.LightBlock): _156.LightBlockAmino;
            fromAminoMsg(object: _156.LightBlockAminoMsg): _156.LightBlock;
            fromProtoMsg(message: _156.LightBlockProtoMsg): _156.LightBlock;
            toProto(message: _156.LightBlock): Uint8Array;
            toProtoMsg(message: _156.LightBlock): _156.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _156.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.BlockMeta;
            fromPartial(object: Partial<_156.BlockMeta>): _156.BlockMeta;
            fromAmino(object: _156.BlockMetaAmino): _156.BlockMeta;
            toAmino(message: _156.BlockMeta): _156.BlockMetaAmino;
            fromAminoMsg(object: _156.BlockMetaAminoMsg): _156.BlockMeta;
            fromProtoMsg(message: _156.BlockMetaProtoMsg): _156.BlockMeta;
            toProto(message: _156.BlockMeta): Uint8Array;
            toProtoMsg(message: _156.BlockMeta): _156.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _156.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.TxProof;
            fromPartial(object: Partial<_156.TxProof>): _156.TxProof;
            fromAmino(object: _156.TxProofAmino): _156.TxProof;
            toAmino(message: _156.TxProof): _156.TxProofAmino;
            fromAminoMsg(object: _156.TxProofAminoMsg): _156.TxProof;
            fromProtoMsg(message: _156.TxProofProtoMsg): _156.TxProof;
            toProto(message: _156.TxProof): Uint8Array;
            toProtoMsg(message: _156.TxProof): _156.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _155.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _155.ConsensusParams;
            fromPartial(object: Partial<_155.ConsensusParams>): _155.ConsensusParams;
            fromAmino(object: _155.ConsensusParamsAmino): _155.ConsensusParams;
            toAmino(message: _155.ConsensusParams): _155.ConsensusParamsAmino;
            fromAminoMsg(object: _155.ConsensusParamsAminoMsg): _155.ConsensusParams;
            fromProtoMsg(message: _155.ConsensusParamsProtoMsg): _155.ConsensusParams;
            toProto(message: _155.ConsensusParams): Uint8Array;
            toProtoMsg(message: _155.ConsensusParams): _155.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _155.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _155.BlockParams;
            fromPartial(object: Partial<_155.BlockParams>): _155.BlockParams;
            fromAmino(object: _155.BlockParamsAmino): _155.BlockParams;
            toAmino(message: _155.BlockParams): _155.BlockParamsAmino;
            fromAminoMsg(object: _155.BlockParamsAminoMsg): _155.BlockParams;
            fromProtoMsg(message: _155.BlockParamsProtoMsg): _155.BlockParams;
            toProto(message: _155.BlockParams): Uint8Array;
            toProtoMsg(message: _155.BlockParams): _155.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _155.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _155.EvidenceParams;
            fromPartial(object: Partial<_155.EvidenceParams>): _155.EvidenceParams;
            fromAmino(object: _155.EvidenceParamsAmino): _155.EvidenceParams;
            toAmino(message: _155.EvidenceParams): _155.EvidenceParamsAmino;
            fromAminoMsg(object: _155.EvidenceParamsAminoMsg): _155.EvidenceParams;
            fromProtoMsg(message: _155.EvidenceParamsProtoMsg): _155.EvidenceParams;
            toProto(message: _155.EvidenceParams): Uint8Array;
            toProtoMsg(message: _155.EvidenceParams): _155.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _155.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _155.ValidatorParams;
            fromPartial(object: Partial<_155.ValidatorParams>): _155.ValidatorParams;
            fromAmino(object: _155.ValidatorParamsAmino): _155.ValidatorParams;
            toAmino(message: _155.ValidatorParams): _155.ValidatorParamsAmino;
            fromAminoMsg(object: _155.ValidatorParamsAminoMsg): _155.ValidatorParams;
            fromProtoMsg(message: _155.ValidatorParamsProtoMsg): _155.ValidatorParams;
            toProto(message: _155.ValidatorParams): Uint8Array;
            toProtoMsg(message: _155.ValidatorParams): _155.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _155.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _155.VersionParams;
            fromPartial(object: Partial<_155.VersionParams>): _155.VersionParams;
            fromAmino(object: _155.VersionParamsAmino): _155.VersionParams;
            toAmino(message: _155.VersionParams): _155.VersionParamsAmino;
            fromAminoMsg(object: _155.VersionParamsAminoMsg): _155.VersionParams;
            fromProtoMsg(message: _155.VersionParamsProtoMsg): _155.VersionParams;
            toProto(message: _155.VersionParams): Uint8Array;
            toProtoMsg(message: _155.VersionParams): _155.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _155.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _155.HashedParams;
            fromPartial(object: Partial<_155.HashedParams>): _155.HashedParams;
            fromAmino(object: _155.HashedParamsAmino): _155.HashedParams;
            toAmino(message: _155.HashedParams): _155.HashedParamsAmino;
            fromAminoMsg(object: _155.HashedParamsAminoMsg): _155.HashedParams;
            fromProtoMsg(message: _155.HashedParamsProtoMsg): _155.HashedParams;
            toProto(message: _155.HashedParams): Uint8Array;
            toProtoMsg(message: _155.HashedParams): _155.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _154.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _154.Evidence;
            fromPartial(object: Partial<_154.Evidence>): _154.Evidence;
            fromAmino(object: _154.EvidenceAmino): _154.Evidence;
            toAmino(message: _154.Evidence): _154.EvidenceAmino;
            fromAminoMsg(object: _154.EvidenceAminoMsg): _154.Evidence;
            fromProtoMsg(message: _154.EvidenceProtoMsg): _154.Evidence;
            toProto(message: _154.Evidence): Uint8Array;
            toProtoMsg(message: _154.Evidence): _154.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _154.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _154.DuplicateVoteEvidence;
            fromPartial(object: Partial<_154.DuplicateVoteEvidence>): _154.DuplicateVoteEvidence;
            fromAmino(object: _154.DuplicateVoteEvidenceAmino): _154.DuplicateVoteEvidence;
            toAmino(message: _154.DuplicateVoteEvidence): _154.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _154.DuplicateVoteEvidenceAminoMsg): _154.DuplicateVoteEvidence;
            fromProtoMsg(message: _154.DuplicateVoteEvidenceProtoMsg): _154.DuplicateVoteEvidence;
            toProto(message: _154.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _154.DuplicateVoteEvidence): _154.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _154.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _154.LightClientAttackEvidence;
            fromPartial(object: Partial<_154.LightClientAttackEvidence>): _154.LightClientAttackEvidence;
            fromAmino(object: _154.LightClientAttackEvidenceAmino): _154.LightClientAttackEvidence;
            toAmino(message: _154.LightClientAttackEvidence): _154.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _154.LightClientAttackEvidenceAminoMsg): _154.LightClientAttackEvidence;
            fromProtoMsg(message: _154.LightClientAttackEvidenceProtoMsg): _154.LightClientAttackEvidence;
            toProto(message: _154.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _154.LightClientAttackEvidence): _154.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _154.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _154.EvidenceList;
            fromPartial(object: Partial<_154.EvidenceList>): _154.EvidenceList;
            fromAmino(object: _154.EvidenceListAmino): _154.EvidenceList;
            toAmino(message: _154.EvidenceList): _154.EvidenceListAmino;
            fromAminoMsg(object: _154.EvidenceListAminoMsg): _154.EvidenceList;
            fromProtoMsg(message: _154.EvidenceListProtoMsg): _154.EvidenceList;
            toProto(message: _154.EvidenceList): Uint8Array;
            toProtoMsg(message: _154.EvidenceList): _154.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _153.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.Block;
            fromPartial(object: Partial<_153.Block>): _153.Block;
            fromAmino(object: _153.BlockAmino): _153.Block;
            toAmino(message: _153.Block): _153.BlockAmino;
            fromAminoMsg(object: _153.BlockAminoMsg): _153.Block;
            fromProtoMsg(message: _153.BlockProtoMsg): _153.Block;
            toProto(message: _153.Block): Uint8Array;
            toProtoMsg(message: _153.Block): _153.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _158.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _158.App;
            fromPartial(object: Partial<_158.App>): _158.App;
            fromAmino(object: _158.AppAmino): _158.App;
            toAmino(message: _158.App): _158.AppAmino;
            fromAminoMsg(object: _158.AppAminoMsg): _158.App;
            fromProtoMsg(message: _158.AppProtoMsg): _158.App;
            toProto(message: _158.App): Uint8Array;
            toProtoMsg(message: _158.App): _158.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _158.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _158.Consensus;
            fromPartial(object: Partial<_158.Consensus>): _158.Consensus;
            fromAmino(object: _158.ConsensusAmino): _158.Consensus;
            toAmino(message: _158.Consensus): _158.ConsensusAmino;
            fromAminoMsg(object: _158.ConsensusAminoMsg): _158.Consensus;
            fromProtoMsg(message: _158.ConsensusProtoMsg): _158.Consensus;
            toProto(message: _158.Consensus): Uint8Array;
            toProtoMsg(message: _158.Consensus): _158.ConsensusProtoMsg;
        };
    };
}
