import * as _184 from "./api/http";
import * as _185 from "./protobuf/descriptor";
import * as _186 from "./protobuf/any";
import * as _187 from "./protobuf/timestamp";
import * as _188 from "./protobuf/duration";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _184.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _184.Http;
            fromPartial(object: Partial<_184.Http>): _184.Http;
            fromAmino(object: _184.HttpAmino): _184.Http;
            toAmino(message: _184.Http): _184.HttpAmino;
            fromAminoMsg(object: _184.HttpAminoMsg): _184.Http;
            fromProtoMsg(message: _184.HttpProtoMsg): _184.Http;
            toProto(message: _184.Http): Uint8Array;
            toProtoMsg(message: _184.Http): _184.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _184.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _184.HttpRule;
            fromPartial(object: Partial<_184.HttpRule>): _184.HttpRule;
            fromAmino(object: _184.HttpRuleAmino): _184.HttpRule;
            toAmino(message: _184.HttpRule): _184.HttpRuleAmino;
            fromAminoMsg(object: _184.HttpRuleAminoMsg): _184.HttpRule;
            fromProtoMsg(message: _184.HttpRuleProtoMsg): _184.HttpRule;
            toProto(message: _184.HttpRule): Uint8Array;
            toProtoMsg(message: _184.HttpRule): _184.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _184.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _184.CustomHttpPattern;
            fromPartial(object: Partial<_184.CustomHttpPattern>): _184.CustomHttpPattern;
            fromAmino(object: _184.CustomHttpPatternAmino): _184.CustomHttpPattern;
            toAmino(message: _184.CustomHttpPattern): _184.CustomHttpPatternAmino;
            fromAminoMsg(object: _184.CustomHttpPatternAminoMsg): _184.CustomHttpPattern;
            fromProtoMsg(message: _184.CustomHttpPatternProtoMsg): _184.CustomHttpPattern;
            toProto(message: _184.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _184.CustomHttpPattern): _184.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Duration: {
            typeUrl: string;
            encode(message: _188.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _188.Duration;
            fromPartial(object: Partial<_188.Duration>): _188.Duration;
            fromAmino(object: string): _188.Duration;
            toAmino(message: _188.Duration): string;
            fromAminoMsg(object: _188.DurationAminoMsg): _188.Duration;
            fromProtoMsg(message: _188.DurationProtoMsg): _188.Duration;
            toProto(message: _188.Duration): Uint8Array;
            toProtoMsg(message: _188.Duration): _188.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _187.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.Timestamp;
            fromPartial(object: Partial<_187.Timestamp>): _187.Timestamp;
            fromAmino(object: string): _187.Timestamp;
            toAmino(message: _187.Timestamp): string;
            fromAminoMsg(object: _187.TimestampAminoMsg): _187.Timestamp;
            fromProtoMsg(message: _187.TimestampProtoMsg): _187.Timestamp;
            toProto(message: _187.Timestamp): Uint8Array;
            toProtoMsg(message: _187.Timestamp): _187.TimestampProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _186.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _186.Any;
            fromPartial(object: Partial<_186.Any>): _186.Any;
            fromAmino(object: _186.AnyAmino): _186.Any;
            toAmino(message: _186.Any): _186.AnyAmino;
            fromAminoMsg(object: _186.AnyAminoMsg): _186.Any;
            fromProtoMsg(message: _186.AnyProtoMsg): _186.Any;
            toProto(message: _186.Any): Uint8Array;
            toProtoMsg(message: _186.Any): _186.AnyProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _185.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _185.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _185.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _185.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _185.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _185.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _185.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _185.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _185.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _185.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _185.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _185.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _185.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _185.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _185.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _185.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _185.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _185.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _185.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _185.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _185.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _185.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _185.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _185.FieldOptions_CType;
        FieldOptions_JSType: typeof _185.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _185.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _185.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _185.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _185.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _185.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _185.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.FileDescriptorSet;
            fromPartial(object: Partial<_185.FileDescriptorSet>): _185.FileDescriptorSet;
            fromAmino(object: _185.FileDescriptorSetAmino): _185.FileDescriptorSet;
            toAmino(message: _185.FileDescriptorSet): _185.FileDescriptorSetAmino;
            fromAminoMsg(object: _185.FileDescriptorSetAminoMsg): _185.FileDescriptorSet;
            fromProtoMsg(message: _185.FileDescriptorSetProtoMsg): _185.FileDescriptorSet;
            toProto(message: _185.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _185.FileDescriptorSet): _185.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _185.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.FileDescriptorProto;
            fromPartial(object: Partial<_185.FileDescriptorProto>): _185.FileDescriptorProto;
            fromAmino(object: _185.FileDescriptorProtoAmino): _185.FileDescriptorProto;
            toAmino(message: _185.FileDescriptorProto): _185.FileDescriptorProtoAmino;
            fromAminoMsg(object: _185.FileDescriptorProtoAminoMsg): _185.FileDescriptorProto;
            fromProtoMsg(message: _185.FileDescriptorProtoProtoMsg): _185.FileDescriptorProto;
            toProto(message: _185.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _185.FileDescriptorProto): _185.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _185.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.DescriptorProto;
            fromPartial(object: Partial<_185.DescriptorProto>): _185.DescriptorProto;
            fromAmino(object: _185.DescriptorProtoAmino): _185.DescriptorProto;
            toAmino(message: _185.DescriptorProto): _185.DescriptorProtoAmino;
            fromAminoMsg(object: _185.DescriptorProtoAminoMsg): _185.DescriptorProto;
            fromProtoMsg(message: _185.DescriptorProtoProtoMsg): _185.DescriptorProto;
            toProto(message: _185.DescriptorProto): Uint8Array;
            toProtoMsg(message: _185.DescriptorProto): _185.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _185.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_185.DescriptorProto_ExtensionRange>): _185.DescriptorProto_ExtensionRange;
            fromAmino(object: _185.DescriptorProto_ExtensionRangeAmino): _185.DescriptorProto_ExtensionRange;
            toAmino(message: _185.DescriptorProto_ExtensionRange): _185.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _185.DescriptorProto_ExtensionRangeAminoMsg): _185.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _185.DescriptorProto_ExtensionRangeProtoMsg): _185.DescriptorProto_ExtensionRange;
            toProto(message: _185.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _185.DescriptorProto_ExtensionRange): _185.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _185.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_185.DescriptorProto_ReservedRange>): _185.DescriptorProto_ReservedRange;
            fromAmino(object: _185.DescriptorProto_ReservedRangeAmino): _185.DescriptorProto_ReservedRange;
            toAmino(message: _185.DescriptorProto_ReservedRange): _185.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _185.DescriptorProto_ReservedRangeAminoMsg): _185.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _185.DescriptorProto_ReservedRangeProtoMsg): _185.DescriptorProto_ReservedRange;
            toProto(message: _185.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _185.DescriptorProto_ReservedRange): _185.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _185.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.ExtensionRangeOptions;
            fromPartial(object: Partial<_185.ExtensionRangeOptions>): _185.ExtensionRangeOptions;
            fromAmino(object: _185.ExtensionRangeOptionsAmino): _185.ExtensionRangeOptions;
            toAmino(message: _185.ExtensionRangeOptions): _185.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _185.ExtensionRangeOptionsAminoMsg): _185.ExtensionRangeOptions;
            fromProtoMsg(message: _185.ExtensionRangeOptionsProtoMsg): _185.ExtensionRangeOptions;
            toProto(message: _185.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _185.ExtensionRangeOptions): _185.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _185.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.FieldDescriptorProto;
            fromPartial(object: Partial<_185.FieldDescriptorProto>): _185.FieldDescriptorProto;
            fromAmino(object: _185.FieldDescriptorProtoAmino): _185.FieldDescriptorProto;
            toAmino(message: _185.FieldDescriptorProto): _185.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _185.FieldDescriptorProtoAminoMsg): _185.FieldDescriptorProto;
            fromProtoMsg(message: _185.FieldDescriptorProtoProtoMsg): _185.FieldDescriptorProto;
            toProto(message: _185.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _185.FieldDescriptorProto): _185.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _185.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.OneofDescriptorProto;
            fromPartial(object: Partial<_185.OneofDescriptorProto>): _185.OneofDescriptorProto;
            fromAmino(object: _185.OneofDescriptorProtoAmino): _185.OneofDescriptorProto;
            toAmino(message: _185.OneofDescriptorProto): _185.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _185.OneofDescriptorProtoAminoMsg): _185.OneofDescriptorProto;
            fromProtoMsg(message: _185.OneofDescriptorProtoProtoMsg): _185.OneofDescriptorProto;
            toProto(message: _185.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _185.OneofDescriptorProto): _185.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _185.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.EnumDescriptorProto;
            fromPartial(object: Partial<_185.EnumDescriptorProto>): _185.EnumDescriptorProto;
            fromAmino(object: _185.EnumDescriptorProtoAmino): _185.EnumDescriptorProto;
            toAmino(message: _185.EnumDescriptorProto): _185.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _185.EnumDescriptorProtoAminoMsg): _185.EnumDescriptorProto;
            fromProtoMsg(message: _185.EnumDescriptorProtoProtoMsg): _185.EnumDescriptorProto;
            toProto(message: _185.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _185.EnumDescriptorProto): _185.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _185.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_185.EnumDescriptorProto_EnumReservedRange>): _185.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _185.EnumDescriptorProto_EnumReservedRangeAmino): _185.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _185.EnumDescriptorProto_EnumReservedRange): _185.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _185.EnumDescriptorProto_EnumReservedRangeAminoMsg): _185.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _185.EnumDescriptorProto_EnumReservedRangeProtoMsg): _185.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _185.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _185.EnumDescriptorProto_EnumReservedRange): _185.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _185.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.EnumValueDescriptorProto;
            fromPartial(object: Partial<_185.EnumValueDescriptorProto>): _185.EnumValueDescriptorProto;
            fromAmino(object: _185.EnumValueDescriptorProtoAmino): _185.EnumValueDescriptorProto;
            toAmino(message: _185.EnumValueDescriptorProto): _185.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _185.EnumValueDescriptorProtoAminoMsg): _185.EnumValueDescriptorProto;
            fromProtoMsg(message: _185.EnumValueDescriptorProtoProtoMsg): _185.EnumValueDescriptorProto;
            toProto(message: _185.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _185.EnumValueDescriptorProto): _185.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _185.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.ServiceDescriptorProto;
            fromPartial(object: Partial<_185.ServiceDescriptorProto>): _185.ServiceDescriptorProto;
            fromAmino(object: _185.ServiceDescriptorProtoAmino): _185.ServiceDescriptorProto;
            toAmino(message: _185.ServiceDescriptorProto): _185.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _185.ServiceDescriptorProtoAminoMsg): _185.ServiceDescriptorProto;
            fromProtoMsg(message: _185.ServiceDescriptorProtoProtoMsg): _185.ServiceDescriptorProto;
            toProto(message: _185.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _185.ServiceDescriptorProto): _185.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _185.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.MethodDescriptorProto;
            fromPartial(object: Partial<_185.MethodDescriptorProto>): _185.MethodDescriptorProto;
            fromAmino(object: _185.MethodDescriptorProtoAmino): _185.MethodDescriptorProto;
            toAmino(message: _185.MethodDescriptorProto): _185.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _185.MethodDescriptorProtoAminoMsg): _185.MethodDescriptorProto;
            fromProtoMsg(message: _185.MethodDescriptorProtoProtoMsg): _185.MethodDescriptorProto;
            toProto(message: _185.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _185.MethodDescriptorProto): _185.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _185.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.FileOptions;
            fromPartial(object: Partial<_185.FileOptions>): _185.FileOptions;
            fromAmino(object: _185.FileOptionsAmino): _185.FileOptions;
            toAmino(message: _185.FileOptions): _185.FileOptionsAmino;
            fromAminoMsg(object: _185.FileOptionsAminoMsg): _185.FileOptions;
            fromProtoMsg(message: _185.FileOptionsProtoMsg): _185.FileOptions;
            toProto(message: _185.FileOptions): Uint8Array;
            toProtoMsg(message: _185.FileOptions): _185.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _185.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.MessageOptions;
            fromPartial(object: Partial<_185.MessageOptions>): _185.MessageOptions;
            fromAmino(object: _185.MessageOptionsAmino): _185.MessageOptions;
            toAmino(message: _185.MessageOptions): _185.MessageOptionsAmino;
            fromAminoMsg(object: _185.MessageOptionsAminoMsg): _185.MessageOptions;
            fromProtoMsg(message: _185.MessageOptionsProtoMsg): _185.MessageOptions;
            toProto(message: _185.MessageOptions): Uint8Array;
            toProtoMsg(message: _185.MessageOptions): _185.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _185.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.FieldOptions;
            fromPartial(object: Partial<_185.FieldOptions>): _185.FieldOptions;
            fromAmino(object: _185.FieldOptionsAmino): _185.FieldOptions;
            toAmino(message: _185.FieldOptions): _185.FieldOptionsAmino;
            fromAminoMsg(object: _185.FieldOptionsAminoMsg): _185.FieldOptions;
            fromProtoMsg(message: _185.FieldOptionsProtoMsg): _185.FieldOptions;
            toProto(message: _185.FieldOptions): Uint8Array;
            toProtoMsg(message: _185.FieldOptions): _185.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _185.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.OneofOptions;
            fromPartial(object: Partial<_185.OneofOptions>): _185.OneofOptions;
            fromAmino(object: _185.OneofOptionsAmino): _185.OneofOptions;
            toAmino(message: _185.OneofOptions): _185.OneofOptionsAmino;
            fromAminoMsg(object: _185.OneofOptionsAminoMsg): _185.OneofOptions;
            fromProtoMsg(message: _185.OneofOptionsProtoMsg): _185.OneofOptions;
            toProto(message: _185.OneofOptions): Uint8Array;
            toProtoMsg(message: _185.OneofOptions): _185.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _185.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.EnumOptions;
            fromPartial(object: Partial<_185.EnumOptions>): _185.EnumOptions;
            fromAmino(object: _185.EnumOptionsAmino): _185.EnumOptions;
            toAmino(message: _185.EnumOptions): _185.EnumOptionsAmino;
            fromAminoMsg(object: _185.EnumOptionsAminoMsg): _185.EnumOptions;
            fromProtoMsg(message: _185.EnumOptionsProtoMsg): _185.EnumOptions;
            toProto(message: _185.EnumOptions): Uint8Array;
            toProtoMsg(message: _185.EnumOptions): _185.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _185.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.EnumValueOptions;
            fromPartial(object: Partial<_185.EnumValueOptions>): _185.EnumValueOptions;
            fromAmino(object: _185.EnumValueOptionsAmino): _185.EnumValueOptions;
            toAmino(message: _185.EnumValueOptions): _185.EnumValueOptionsAmino;
            fromAminoMsg(object: _185.EnumValueOptionsAminoMsg): _185.EnumValueOptions;
            fromProtoMsg(message: _185.EnumValueOptionsProtoMsg): _185.EnumValueOptions;
            toProto(message: _185.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _185.EnumValueOptions): _185.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _185.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.ServiceOptions;
            fromPartial(object: Partial<_185.ServiceOptions>): _185.ServiceOptions;
            fromAmino(object: _185.ServiceOptionsAmino): _185.ServiceOptions;
            toAmino(message: _185.ServiceOptions): _185.ServiceOptionsAmino;
            fromAminoMsg(object: _185.ServiceOptionsAminoMsg): _185.ServiceOptions;
            fromProtoMsg(message: _185.ServiceOptionsProtoMsg): _185.ServiceOptions;
            toProto(message: _185.ServiceOptions): Uint8Array;
            toProtoMsg(message: _185.ServiceOptions): _185.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _185.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.MethodOptions;
            fromPartial(object: Partial<_185.MethodOptions>): _185.MethodOptions;
            fromAmino(object: _185.MethodOptionsAmino): _185.MethodOptions;
            toAmino(message: _185.MethodOptions): _185.MethodOptionsAmino;
            fromAminoMsg(object: _185.MethodOptionsAminoMsg): _185.MethodOptions;
            fromProtoMsg(message: _185.MethodOptionsProtoMsg): _185.MethodOptions;
            toProto(message: _185.MethodOptions): Uint8Array;
            toProtoMsg(message: _185.MethodOptions): _185.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _185.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.UninterpretedOption;
            fromPartial(object: Partial<_185.UninterpretedOption>): _185.UninterpretedOption;
            fromAmino(object: _185.UninterpretedOptionAmino): _185.UninterpretedOption;
            toAmino(message: _185.UninterpretedOption): _185.UninterpretedOptionAmino;
            fromAminoMsg(object: _185.UninterpretedOptionAminoMsg): _185.UninterpretedOption;
            fromProtoMsg(message: _185.UninterpretedOptionProtoMsg): _185.UninterpretedOption;
            toProto(message: _185.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _185.UninterpretedOption): _185.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _185.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_185.UninterpretedOption_NamePart>): _185.UninterpretedOption_NamePart;
            fromAmino(object: _185.UninterpretedOption_NamePartAmino): _185.UninterpretedOption_NamePart;
            toAmino(message: _185.UninterpretedOption_NamePart): _185.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _185.UninterpretedOption_NamePartAminoMsg): _185.UninterpretedOption_NamePart;
            fromProtoMsg(message: _185.UninterpretedOption_NamePartProtoMsg): _185.UninterpretedOption_NamePart;
            toProto(message: _185.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _185.UninterpretedOption_NamePart): _185.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _185.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.SourceCodeInfo;
            fromPartial(object: Partial<_185.SourceCodeInfo>): _185.SourceCodeInfo;
            fromAmino(object: _185.SourceCodeInfoAmino): _185.SourceCodeInfo;
            toAmino(message: _185.SourceCodeInfo): _185.SourceCodeInfoAmino;
            fromAminoMsg(object: _185.SourceCodeInfoAminoMsg): _185.SourceCodeInfo;
            fromProtoMsg(message: _185.SourceCodeInfoProtoMsg): _185.SourceCodeInfo;
            toProto(message: _185.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _185.SourceCodeInfo): _185.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _185.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.SourceCodeInfo_Location;
            fromPartial(object: Partial<_185.SourceCodeInfo_Location>): _185.SourceCodeInfo_Location;
            fromAmino(object: _185.SourceCodeInfo_LocationAmino): _185.SourceCodeInfo_Location;
            toAmino(message: _185.SourceCodeInfo_Location): _185.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _185.SourceCodeInfo_LocationAminoMsg): _185.SourceCodeInfo_Location;
            fromProtoMsg(message: _185.SourceCodeInfo_LocationProtoMsg): _185.SourceCodeInfo_Location;
            toProto(message: _185.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _185.SourceCodeInfo_Location): _185.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _185.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.GeneratedCodeInfo;
            fromPartial(object: Partial<_185.GeneratedCodeInfo>): _185.GeneratedCodeInfo;
            fromAmino(object: _185.GeneratedCodeInfoAmino): _185.GeneratedCodeInfo;
            toAmino(message: _185.GeneratedCodeInfo): _185.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _185.GeneratedCodeInfoAminoMsg): _185.GeneratedCodeInfo;
            fromProtoMsg(message: _185.GeneratedCodeInfoProtoMsg): _185.GeneratedCodeInfo;
            toProto(message: _185.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _185.GeneratedCodeInfo): _185.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _185.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_185.GeneratedCodeInfo_Annotation>): _185.GeneratedCodeInfo_Annotation;
            fromAmino(object: _185.GeneratedCodeInfo_AnnotationAmino): _185.GeneratedCodeInfo_Annotation;
            toAmino(message: _185.GeneratedCodeInfo_Annotation): _185.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _185.GeneratedCodeInfo_AnnotationAminoMsg): _185.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _185.GeneratedCodeInfo_AnnotationProtoMsg): _185.GeneratedCodeInfo_Annotation;
            toProto(message: _185.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _185.GeneratedCodeInfo_Annotation): _185.GeneratedCodeInfo_AnnotationProtoMsg;
        };
    };
}
