import * as _250 from "./api/http";
import * as _251 from "./protobuf/duration";
import * as _252 from "./protobuf/any";
import * as _253 from "./protobuf/timestamp";
import * as _254 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _250.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _250.Http;
            fromPartial(object: Partial<_250.Http>): _250.Http;
            fromAmino(object: _250.HttpAmino): _250.Http;
            toAmino(message: _250.Http): _250.HttpAmino;
            fromAminoMsg(object: _250.HttpAminoMsg): _250.Http;
            fromProtoMsg(message: _250.HttpProtoMsg): _250.Http;
            toProto(message: _250.Http): Uint8Array;
            toProtoMsg(message: _250.Http): _250.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _250.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _250.HttpRule;
            fromPartial(object: Partial<_250.HttpRule>): _250.HttpRule;
            fromAmino(object: _250.HttpRuleAmino): _250.HttpRule;
            toAmino(message: _250.HttpRule): _250.HttpRuleAmino;
            fromAminoMsg(object: _250.HttpRuleAminoMsg): _250.HttpRule;
            fromProtoMsg(message: _250.HttpRuleProtoMsg): _250.HttpRule;
            toProto(message: _250.HttpRule): Uint8Array;
            toProtoMsg(message: _250.HttpRule): _250.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _250.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _250.CustomHttpPattern;
            fromPartial(object: Partial<_250.CustomHttpPattern>): _250.CustomHttpPattern;
            fromAmino(object: _250.CustomHttpPatternAmino): _250.CustomHttpPattern;
            toAmino(message: _250.CustomHttpPattern): _250.CustomHttpPatternAmino;
            fromAminoMsg(object: _250.CustomHttpPatternAminoMsg): _250.CustomHttpPattern;
            fromProtoMsg(message: _250.CustomHttpPatternProtoMsg): _250.CustomHttpPattern;
            toProto(message: _250.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _250.CustomHttpPattern): _250.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _254.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _254.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _254.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _254.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _254.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _254.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _254.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _254.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _254.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _254.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _254.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _254.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _254.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _254.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _254.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _254.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _254.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _254.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _254.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _254.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _254.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _254.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _254.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _254.FieldOptions_CType;
        FieldOptions_JSType: typeof _254.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _254.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _254.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _254.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _254.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _254.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _254.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.FileDescriptorSet;
            fromPartial(object: Partial<_254.FileDescriptorSet>): _254.FileDescriptorSet;
            fromAmino(object: _254.FileDescriptorSetAmino): _254.FileDescriptorSet;
            toAmino(message: _254.FileDescriptorSet): _254.FileDescriptorSetAmino;
            fromAminoMsg(object: _254.FileDescriptorSetAminoMsg): _254.FileDescriptorSet;
            fromProtoMsg(message: _254.FileDescriptorSetProtoMsg): _254.FileDescriptorSet;
            toProto(message: _254.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _254.FileDescriptorSet): _254.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _254.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.FileDescriptorProto;
            fromPartial(object: Partial<_254.FileDescriptorProto>): _254.FileDescriptorProto;
            fromAmino(object: _254.FileDescriptorProtoAmino): _254.FileDescriptorProto;
            toAmino(message: _254.FileDescriptorProto): _254.FileDescriptorProtoAmino;
            fromAminoMsg(object: _254.FileDescriptorProtoAminoMsg): _254.FileDescriptorProto;
            fromProtoMsg(message: _254.FileDescriptorProtoProtoMsg): _254.FileDescriptorProto;
            toProto(message: _254.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _254.FileDescriptorProto): _254.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _254.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.DescriptorProto;
            fromPartial(object: Partial<_254.DescriptorProto>): _254.DescriptorProto;
            fromAmino(object: _254.DescriptorProtoAmino): _254.DescriptorProto;
            toAmino(message: _254.DescriptorProto): _254.DescriptorProtoAmino;
            fromAminoMsg(object: _254.DescriptorProtoAminoMsg): _254.DescriptorProto;
            fromProtoMsg(message: _254.DescriptorProtoProtoMsg): _254.DescriptorProto;
            toProto(message: _254.DescriptorProto): Uint8Array;
            toProtoMsg(message: _254.DescriptorProto): _254.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _254.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_254.DescriptorProto_ExtensionRange>): _254.DescriptorProto_ExtensionRange;
            fromAmino(object: _254.DescriptorProto_ExtensionRangeAmino): _254.DescriptorProto_ExtensionRange;
            toAmino(message: _254.DescriptorProto_ExtensionRange): _254.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _254.DescriptorProto_ExtensionRangeAminoMsg): _254.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _254.DescriptorProto_ExtensionRangeProtoMsg): _254.DescriptorProto_ExtensionRange;
            toProto(message: _254.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _254.DescriptorProto_ExtensionRange): _254.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _254.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_254.DescriptorProto_ReservedRange>): _254.DescriptorProto_ReservedRange;
            fromAmino(object: _254.DescriptorProto_ReservedRangeAmino): _254.DescriptorProto_ReservedRange;
            toAmino(message: _254.DescriptorProto_ReservedRange): _254.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _254.DescriptorProto_ReservedRangeAminoMsg): _254.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _254.DescriptorProto_ReservedRangeProtoMsg): _254.DescriptorProto_ReservedRange;
            toProto(message: _254.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _254.DescriptorProto_ReservedRange): _254.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _254.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.ExtensionRangeOptions;
            fromPartial(object: Partial<_254.ExtensionRangeOptions>): _254.ExtensionRangeOptions;
            fromAmino(object: _254.ExtensionRangeOptionsAmino): _254.ExtensionRangeOptions;
            toAmino(message: _254.ExtensionRangeOptions): _254.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _254.ExtensionRangeOptionsAminoMsg): _254.ExtensionRangeOptions;
            fromProtoMsg(message: _254.ExtensionRangeOptionsProtoMsg): _254.ExtensionRangeOptions;
            toProto(message: _254.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _254.ExtensionRangeOptions): _254.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _254.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.FieldDescriptorProto;
            fromPartial(object: Partial<_254.FieldDescriptorProto>): _254.FieldDescriptorProto;
            fromAmino(object: _254.FieldDescriptorProtoAmino): _254.FieldDescriptorProto;
            toAmino(message: _254.FieldDescriptorProto): _254.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _254.FieldDescriptorProtoAminoMsg): _254.FieldDescriptorProto;
            fromProtoMsg(message: _254.FieldDescriptorProtoProtoMsg): _254.FieldDescriptorProto;
            toProto(message: _254.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _254.FieldDescriptorProto): _254.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _254.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.OneofDescriptorProto;
            fromPartial(object: Partial<_254.OneofDescriptorProto>): _254.OneofDescriptorProto;
            fromAmino(object: _254.OneofDescriptorProtoAmino): _254.OneofDescriptorProto;
            toAmino(message: _254.OneofDescriptorProto): _254.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _254.OneofDescriptorProtoAminoMsg): _254.OneofDescriptorProto;
            fromProtoMsg(message: _254.OneofDescriptorProtoProtoMsg): _254.OneofDescriptorProto;
            toProto(message: _254.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _254.OneofDescriptorProto): _254.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _254.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.EnumDescriptorProto;
            fromPartial(object: Partial<_254.EnumDescriptorProto>): _254.EnumDescriptorProto;
            fromAmino(object: _254.EnumDescriptorProtoAmino): _254.EnumDescriptorProto;
            toAmino(message: _254.EnumDescriptorProto): _254.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _254.EnumDescriptorProtoAminoMsg): _254.EnumDescriptorProto;
            fromProtoMsg(message: _254.EnumDescriptorProtoProtoMsg): _254.EnumDescriptorProto;
            toProto(message: _254.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _254.EnumDescriptorProto): _254.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _254.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_254.EnumDescriptorProto_EnumReservedRange>): _254.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _254.EnumDescriptorProto_EnumReservedRangeAmino): _254.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _254.EnumDescriptorProto_EnumReservedRange): _254.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _254.EnumDescriptorProto_EnumReservedRangeAminoMsg): _254.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _254.EnumDescriptorProto_EnumReservedRangeProtoMsg): _254.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _254.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _254.EnumDescriptorProto_EnumReservedRange): _254.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _254.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.EnumValueDescriptorProto;
            fromPartial(object: Partial<_254.EnumValueDescriptorProto>): _254.EnumValueDescriptorProto;
            fromAmino(object: _254.EnumValueDescriptorProtoAmino): _254.EnumValueDescriptorProto;
            toAmino(message: _254.EnumValueDescriptorProto): _254.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _254.EnumValueDescriptorProtoAminoMsg): _254.EnumValueDescriptorProto;
            fromProtoMsg(message: _254.EnumValueDescriptorProtoProtoMsg): _254.EnumValueDescriptorProto;
            toProto(message: _254.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _254.EnumValueDescriptorProto): _254.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _254.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.ServiceDescriptorProto;
            fromPartial(object: Partial<_254.ServiceDescriptorProto>): _254.ServiceDescriptorProto;
            fromAmino(object: _254.ServiceDescriptorProtoAmino): _254.ServiceDescriptorProto;
            toAmino(message: _254.ServiceDescriptorProto): _254.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _254.ServiceDescriptorProtoAminoMsg): _254.ServiceDescriptorProto;
            fromProtoMsg(message: _254.ServiceDescriptorProtoProtoMsg): _254.ServiceDescriptorProto;
            toProto(message: _254.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _254.ServiceDescriptorProto): _254.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _254.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.MethodDescriptorProto;
            fromPartial(object: Partial<_254.MethodDescriptorProto>): _254.MethodDescriptorProto;
            fromAmino(object: _254.MethodDescriptorProtoAmino): _254.MethodDescriptorProto;
            toAmino(message: _254.MethodDescriptorProto): _254.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _254.MethodDescriptorProtoAminoMsg): _254.MethodDescriptorProto;
            fromProtoMsg(message: _254.MethodDescriptorProtoProtoMsg): _254.MethodDescriptorProto;
            toProto(message: _254.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _254.MethodDescriptorProto): _254.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _254.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.FileOptions;
            fromPartial(object: Partial<_254.FileOptions>): _254.FileOptions;
            fromAmino(object: _254.FileOptionsAmino): _254.FileOptions;
            toAmino(message: _254.FileOptions): _254.FileOptionsAmino;
            fromAminoMsg(object: _254.FileOptionsAminoMsg): _254.FileOptions;
            fromProtoMsg(message: _254.FileOptionsProtoMsg): _254.FileOptions;
            toProto(message: _254.FileOptions): Uint8Array;
            toProtoMsg(message: _254.FileOptions): _254.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _254.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.MessageOptions;
            fromPartial(object: Partial<_254.MessageOptions>): _254.MessageOptions;
            fromAmino(object: _254.MessageOptionsAmino): _254.MessageOptions;
            toAmino(message: _254.MessageOptions): _254.MessageOptionsAmino;
            fromAminoMsg(object: _254.MessageOptionsAminoMsg): _254.MessageOptions;
            fromProtoMsg(message: _254.MessageOptionsProtoMsg): _254.MessageOptions;
            toProto(message: _254.MessageOptions): Uint8Array;
            toProtoMsg(message: _254.MessageOptions): _254.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _254.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.FieldOptions;
            fromPartial(object: Partial<_254.FieldOptions>): _254.FieldOptions;
            fromAmino(object: _254.FieldOptionsAmino): _254.FieldOptions;
            toAmino(message: _254.FieldOptions): _254.FieldOptionsAmino;
            fromAminoMsg(object: _254.FieldOptionsAminoMsg): _254.FieldOptions;
            fromProtoMsg(message: _254.FieldOptionsProtoMsg): _254.FieldOptions;
            toProto(message: _254.FieldOptions): Uint8Array;
            toProtoMsg(message: _254.FieldOptions): _254.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _254.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.OneofOptions;
            fromPartial(object: Partial<_254.OneofOptions>): _254.OneofOptions;
            fromAmino(object: _254.OneofOptionsAmino): _254.OneofOptions;
            toAmino(message: _254.OneofOptions): _254.OneofOptionsAmino;
            fromAminoMsg(object: _254.OneofOptionsAminoMsg): _254.OneofOptions;
            fromProtoMsg(message: _254.OneofOptionsProtoMsg): _254.OneofOptions;
            toProto(message: _254.OneofOptions): Uint8Array;
            toProtoMsg(message: _254.OneofOptions): _254.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _254.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.EnumOptions;
            fromPartial(object: Partial<_254.EnumOptions>): _254.EnumOptions;
            fromAmino(object: _254.EnumOptionsAmino): _254.EnumOptions;
            toAmino(message: _254.EnumOptions): _254.EnumOptionsAmino;
            fromAminoMsg(object: _254.EnumOptionsAminoMsg): _254.EnumOptions;
            fromProtoMsg(message: _254.EnumOptionsProtoMsg): _254.EnumOptions;
            toProto(message: _254.EnumOptions): Uint8Array;
            toProtoMsg(message: _254.EnumOptions): _254.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _254.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.EnumValueOptions;
            fromPartial(object: Partial<_254.EnumValueOptions>): _254.EnumValueOptions;
            fromAmino(object: _254.EnumValueOptionsAmino): _254.EnumValueOptions;
            toAmino(message: _254.EnumValueOptions): _254.EnumValueOptionsAmino;
            fromAminoMsg(object: _254.EnumValueOptionsAminoMsg): _254.EnumValueOptions;
            fromProtoMsg(message: _254.EnumValueOptionsProtoMsg): _254.EnumValueOptions;
            toProto(message: _254.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _254.EnumValueOptions): _254.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _254.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.ServiceOptions;
            fromPartial(object: Partial<_254.ServiceOptions>): _254.ServiceOptions;
            fromAmino(object: _254.ServiceOptionsAmino): _254.ServiceOptions;
            toAmino(message: _254.ServiceOptions): _254.ServiceOptionsAmino;
            fromAminoMsg(object: _254.ServiceOptionsAminoMsg): _254.ServiceOptions;
            fromProtoMsg(message: _254.ServiceOptionsProtoMsg): _254.ServiceOptions;
            toProto(message: _254.ServiceOptions): Uint8Array;
            toProtoMsg(message: _254.ServiceOptions): _254.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _254.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.MethodOptions;
            fromPartial(object: Partial<_254.MethodOptions>): _254.MethodOptions;
            fromAmino(object: _254.MethodOptionsAmino): _254.MethodOptions;
            toAmino(message: _254.MethodOptions): _254.MethodOptionsAmino;
            fromAminoMsg(object: _254.MethodOptionsAminoMsg): _254.MethodOptions;
            fromProtoMsg(message: _254.MethodOptionsProtoMsg): _254.MethodOptions;
            toProto(message: _254.MethodOptions): Uint8Array;
            toProtoMsg(message: _254.MethodOptions): _254.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _254.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.UninterpretedOption;
            fromPartial(object: Partial<_254.UninterpretedOption>): _254.UninterpretedOption;
            fromAmino(object: _254.UninterpretedOptionAmino): _254.UninterpretedOption;
            toAmino(message: _254.UninterpretedOption): _254.UninterpretedOptionAmino;
            fromAminoMsg(object: _254.UninterpretedOptionAminoMsg): _254.UninterpretedOption;
            fromProtoMsg(message: _254.UninterpretedOptionProtoMsg): _254.UninterpretedOption;
            toProto(message: _254.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _254.UninterpretedOption): _254.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _254.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_254.UninterpretedOption_NamePart>): _254.UninterpretedOption_NamePart;
            fromAmino(object: _254.UninterpretedOption_NamePartAmino): _254.UninterpretedOption_NamePart;
            toAmino(message: _254.UninterpretedOption_NamePart): _254.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _254.UninterpretedOption_NamePartAminoMsg): _254.UninterpretedOption_NamePart;
            fromProtoMsg(message: _254.UninterpretedOption_NamePartProtoMsg): _254.UninterpretedOption_NamePart;
            toProto(message: _254.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _254.UninterpretedOption_NamePart): _254.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _254.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.SourceCodeInfo;
            fromPartial(object: Partial<_254.SourceCodeInfo>): _254.SourceCodeInfo;
            fromAmino(object: _254.SourceCodeInfoAmino): _254.SourceCodeInfo;
            toAmino(message: _254.SourceCodeInfo): _254.SourceCodeInfoAmino;
            fromAminoMsg(object: _254.SourceCodeInfoAminoMsg): _254.SourceCodeInfo;
            fromProtoMsg(message: _254.SourceCodeInfoProtoMsg): _254.SourceCodeInfo;
            toProto(message: _254.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _254.SourceCodeInfo): _254.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _254.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.SourceCodeInfo_Location;
            fromPartial(object: Partial<_254.SourceCodeInfo_Location>): _254.SourceCodeInfo_Location;
            fromAmino(object: _254.SourceCodeInfo_LocationAmino): _254.SourceCodeInfo_Location;
            toAmino(message: _254.SourceCodeInfo_Location): _254.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _254.SourceCodeInfo_LocationAminoMsg): _254.SourceCodeInfo_Location;
            fromProtoMsg(message: _254.SourceCodeInfo_LocationProtoMsg): _254.SourceCodeInfo_Location;
            toProto(message: _254.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _254.SourceCodeInfo_Location): _254.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _254.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.GeneratedCodeInfo;
            fromPartial(object: Partial<_254.GeneratedCodeInfo>): _254.GeneratedCodeInfo;
            fromAmino(object: _254.GeneratedCodeInfoAmino): _254.GeneratedCodeInfo;
            toAmino(message: _254.GeneratedCodeInfo): _254.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _254.GeneratedCodeInfoAminoMsg): _254.GeneratedCodeInfo;
            fromProtoMsg(message: _254.GeneratedCodeInfoProtoMsg): _254.GeneratedCodeInfo;
            toProto(message: _254.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _254.GeneratedCodeInfo): _254.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _254.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _254.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_254.GeneratedCodeInfo_Annotation>): _254.GeneratedCodeInfo_Annotation;
            fromAmino(object: _254.GeneratedCodeInfo_AnnotationAmino): _254.GeneratedCodeInfo_Annotation;
            toAmino(message: _254.GeneratedCodeInfo_Annotation): _254.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _254.GeneratedCodeInfo_AnnotationAminoMsg): _254.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _254.GeneratedCodeInfo_AnnotationProtoMsg): _254.GeneratedCodeInfo_Annotation;
            toProto(message: _254.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _254.GeneratedCodeInfo_Annotation): _254.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _253.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _253.Timestamp;
            fromPartial(object: Partial<_253.Timestamp>): _253.Timestamp;
            fromAmino(object: string): _253.Timestamp;
            toAmino(message: _253.Timestamp): string;
            fromAminoMsg(object: _253.TimestampAminoMsg): _253.Timestamp;
            fromProtoMsg(message: _253.TimestampProtoMsg): _253.Timestamp;
            toProto(message: _253.Timestamp): Uint8Array;
            toProtoMsg(message: _253.Timestamp): _253.TimestampProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _252.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _252.Any;
            fromPartial(object: Partial<_252.Any>): _252.Any;
            fromAmino(object: _252.AnyAmino): _252.Any;
            toAmino(message: _252.Any): _252.AnyAmino;
            fromAminoMsg(object: _252.AnyAminoMsg): _252.Any;
            fromProtoMsg(message: _252.AnyProtoMsg): _252.Any;
            toProto(message: _252.Any): Uint8Array;
            toProtoMsg(message: _252.Any): _252.AnyProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _251.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _251.Duration;
            fromPartial(object: Partial<_251.Duration>): _251.Duration;
            fromAmino(object: string): _251.Duration;
            toAmino(message: _251.Duration): string;
            fromAminoMsg(object: _251.DurationAminoMsg): _251.Duration;
            fromProtoMsg(message: _251.DurationProtoMsg): _251.Duration;
            toProto(message: _251.Duration): Uint8Array;
            toProtoMsg(message: _251.Duration): _251.DurationProtoMsg;
        };
    };
}
