import * as _133 from "./abci/types";
import * as _134 from "./crypto/keys";
import * as _135 from "./crypto/proof";
import * as _136 from "./libs/bits/types";
import * as _137 from "./p2p/types";
import * as _138 from "./types/block";
import * as _139 from "./types/evidence";
import * as _140 from "./types/params";
import * as _141 from "./types/types";
import * as _142 from "./types/validator";
import * as _143 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _133.CheckTxType;
        checkTxTypeToJSON(object: _133.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _133.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _133.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _133.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _133.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _133.EvidenceType;
        evidenceTypeToJSON(object: _133.EvidenceType): string;
        CheckTxType: typeof _133.CheckTxType;
        CheckTxTypeSDKType: typeof _133.CheckTxType;
        CheckTxTypeAmino: typeof _133.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _133.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _133.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _133.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _133.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _133.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _133.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _133.EvidenceType;
        EvidenceTypeSDKType: typeof _133.EvidenceType;
        EvidenceTypeAmino: typeof _133.EvidenceType;
        Request: {
            typeUrl: string;
            encode(message: _133.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.Request;
            fromPartial(object: Partial<_133.Request>): _133.Request;
            fromAmino(object: _133.RequestAmino): _133.Request;
            toAmino(message: _133.Request): _133.RequestAmino;
            fromAminoMsg(object: _133.RequestAminoMsg): _133.Request;
            fromProtoMsg(message: _133.RequestProtoMsg): _133.Request;
            toProto(message: _133.Request): Uint8Array;
            toProtoMsg(message: _133.Request): _133.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _133.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.RequestEcho;
            fromPartial(object: Partial<_133.RequestEcho>): _133.RequestEcho;
            fromAmino(object: _133.RequestEchoAmino): _133.RequestEcho;
            toAmino(message: _133.RequestEcho): _133.RequestEchoAmino;
            fromAminoMsg(object: _133.RequestEchoAminoMsg): _133.RequestEcho;
            fromProtoMsg(message: _133.RequestEchoProtoMsg): _133.RequestEcho;
            toProto(message: _133.RequestEcho): Uint8Array;
            toProtoMsg(message: _133.RequestEcho): _133.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _133.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _133.RequestFlush;
            fromPartial(_: Partial<_133.RequestFlush>): _133.RequestFlush;
            fromAmino(_: _133.RequestFlushAmino): _133.RequestFlush;
            toAmino(_: _133.RequestFlush): _133.RequestFlushAmino;
            fromAminoMsg(object: _133.RequestFlushAminoMsg): _133.RequestFlush;
            fromProtoMsg(message: _133.RequestFlushProtoMsg): _133.RequestFlush;
            toProto(message: _133.RequestFlush): Uint8Array;
            toProtoMsg(message: _133.RequestFlush): _133.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _133.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.RequestInfo;
            fromPartial(object: Partial<_133.RequestInfo>): _133.RequestInfo;
            fromAmino(object: _133.RequestInfoAmino): _133.RequestInfo;
            toAmino(message: _133.RequestInfo): _133.RequestInfoAmino;
            fromAminoMsg(object: _133.RequestInfoAminoMsg): _133.RequestInfo;
            fromProtoMsg(message: _133.RequestInfoProtoMsg): _133.RequestInfo;
            toProto(message: _133.RequestInfo): Uint8Array;
            toProtoMsg(message: _133.RequestInfo): _133.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            typeUrl: string;
            encode(message: _133.RequestSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.RequestSetOption;
            fromPartial(object: Partial<_133.RequestSetOption>): _133.RequestSetOption;
            fromAmino(object: _133.RequestSetOptionAmino): _133.RequestSetOption;
            toAmino(message: _133.RequestSetOption): _133.RequestSetOptionAmino;
            fromAminoMsg(object: _133.RequestSetOptionAminoMsg): _133.RequestSetOption;
            fromProtoMsg(message: _133.RequestSetOptionProtoMsg): _133.RequestSetOption;
            toProto(message: _133.RequestSetOption): Uint8Array;
            toProtoMsg(message: _133.RequestSetOption): _133.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _133.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.RequestInitChain;
            fromPartial(object: Partial<_133.RequestInitChain>): _133.RequestInitChain;
            fromAmino(object: _133.RequestInitChainAmino): _133.RequestInitChain;
            toAmino(message: _133.RequestInitChain): _133.RequestInitChainAmino;
            fromAminoMsg(object: _133.RequestInitChainAminoMsg): _133.RequestInitChain;
            fromProtoMsg(message: _133.RequestInitChainProtoMsg): _133.RequestInitChain;
            toProto(message: _133.RequestInitChain): Uint8Array;
            toProtoMsg(message: _133.RequestInitChain): _133.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _133.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.RequestQuery;
            fromPartial(object: Partial<_133.RequestQuery>): _133.RequestQuery;
            fromAmino(object: _133.RequestQueryAmino): _133.RequestQuery;
            toAmino(message: _133.RequestQuery): _133.RequestQueryAmino;
            fromAminoMsg(object: _133.RequestQueryAminoMsg): _133.RequestQuery;
            fromProtoMsg(message: _133.RequestQueryProtoMsg): _133.RequestQuery;
            toProto(message: _133.RequestQuery): Uint8Array;
            toProtoMsg(message: _133.RequestQuery): _133.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _133.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.RequestBeginBlock;
            fromPartial(object: Partial<_133.RequestBeginBlock>): _133.RequestBeginBlock;
            fromAmino(object: _133.RequestBeginBlockAmino): _133.RequestBeginBlock;
            toAmino(message: _133.RequestBeginBlock): _133.RequestBeginBlockAmino;
            fromAminoMsg(object: _133.RequestBeginBlockAminoMsg): _133.RequestBeginBlock;
            fromProtoMsg(message: _133.RequestBeginBlockProtoMsg): _133.RequestBeginBlock;
            toProto(message: _133.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _133.RequestBeginBlock): _133.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _133.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.RequestCheckTx;
            fromPartial(object: Partial<_133.RequestCheckTx>): _133.RequestCheckTx;
            fromAmino(object: _133.RequestCheckTxAmino): _133.RequestCheckTx;
            toAmino(message: _133.RequestCheckTx): _133.RequestCheckTxAmino;
            fromAminoMsg(object: _133.RequestCheckTxAminoMsg): _133.RequestCheckTx;
            fromProtoMsg(message: _133.RequestCheckTxProtoMsg): _133.RequestCheckTx;
            toProto(message: _133.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _133.RequestCheckTx): _133.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _133.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.RequestDeliverTx;
            fromPartial(object: Partial<_133.RequestDeliverTx>): _133.RequestDeliverTx;
            fromAmino(object: _133.RequestDeliverTxAmino): _133.RequestDeliverTx;
            toAmino(message: _133.RequestDeliverTx): _133.RequestDeliverTxAmino;
            fromAminoMsg(object: _133.RequestDeliverTxAminoMsg): _133.RequestDeliverTx;
            fromProtoMsg(message: _133.RequestDeliverTxProtoMsg): _133.RequestDeliverTx;
            toProto(message: _133.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _133.RequestDeliverTx): _133.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _133.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.RequestEndBlock;
            fromPartial(object: Partial<_133.RequestEndBlock>): _133.RequestEndBlock;
            fromAmino(object: _133.RequestEndBlockAmino): _133.RequestEndBlock;
            toAmino(message: _133.RequestEndBlock): _133.RequestEndBlockAmino;
            fromAminoMsg(object: _133.RequestEndBlockAminoMsg): _133.RequestEndBlock;
            fromProtoMsg(message: _133.RequestEndBlockProtoMsg): _133.RequestEndBlock;
            toProto(message: _133.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _133.RequestEndBlock): _133.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _133.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _133.RequestCommit;
            fromPartial(_: Partial<_133.RequestCommit>): _133.RequestCommit;
            fromAmino(_: _133.RequestCommitAmino): _133.RequestCommit;
            toAmino(_: _133.RequestCommit): _133.RequestCommitAmino;
            fromAminoMsg(object: _133.RequestCommitAminoMsg): _133.RequestCommit;
            fromProtoMsg(message: _133.RequestCommitProtoMsg): _133.RequestCommit;
            toProto(message: _133.RequestCommit): Uint8Array;
            toProtoMsg(message: _133.RequestCommit): _133.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _133.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _133.RequestListSnapshots;
            fromPartial(_: Partial<_133.RequestListSnapshots>): _133.RequestListSnapshots;
            fromAmino(_: _133.RequestListSnapshotsAmino): _133.RequestListSnapshots;
            toAmino(_: _133.RequestListSnapshots): _133.RequestListSnapshotsAmino;
            fromAminoMsg(object: _133.RequestListSnapshotsAminoMsg): _133.RequestListSnapshots;
            fromProtoMsg(message: _133.RequestListSnapshotsProtoMsg): _133.RequestListSnapshots;
            toProto(message: _133.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _133.RequestListSnapshots): _133.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _133.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.RequestOfferSnapshot;
            fromPartial(object: Partial<_133.RequestOfferSnapshot>): _133.RequestOfferSnapshot;
            fromAmino(object: _133.RequestOfferSnapshotAmino): _133.RequestOfferSnapshot;
            toAmino(message: _133.RequestOfferSnapshot): _133.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _133.RequestOfferSnapshotAminoMsg): _133.RequestOfferSnapshot;
            fromProtoMsg(message: _133.RequestOfferSnapshotProtoMsg): _133.RequestOfferSnapshot;
            toProto(message: _133.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _133.RequestOfferSnapshot): _133.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _133.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_133.RequestLoadSnapshotChunk>): _133.RequestLoadSnapshotChunk;
            fromAmino(object: _133.RequestLoadSnapshotChunkAmino): _133.RequestLoadSnapshotChunk;
            toAmino(message: _133.RequestLoadSnapshotChunk): _133.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _133.RequestLoadSnapshotChunkAminoMsg): _133.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _133.RequestLoadSnapshotChunkProtoMsg): _133.RequestLoadSnapshotChunk;
            toProto(message: _133.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _133.RequestLoadSnapshotChunk): _133.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _133.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_133.RequestApplySnapshotChunk>): _133.RequestApplySnapshotChunk;
            fromAmino(object: _133.RequestApplySnapshotChunkAmino): _133.RequestApplySnapshotChunk;
            toAmino(message: _133.RequestApplySnapshotChunk): _133.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _133.RequestApplySnapshotChunkAminoMsg): _133.RequestApplySnapshotChunk;
            fromProtoMsg(message: _133.RequestApplySnapshotChunkProtoMsg): _133.RequestApplySnapshotChunk;
            toProto(message: _133.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _133.RequestApplySnapshotChunk): _133.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _133.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.Response;
            fromPartial(object: Partial<_133.Response>): _133.Response;
            fromAmino(object: _133.ResponseAmino): _133.Response;
            toAmino(message: _133.Response): _133.ResponseAmino;
            fromAminoMsg(object: _133.ResponseAminoMsg): _133.Response;
            fromProtoMsg(message: _133.ResponseProtoMsg): _133.Response;
            toProto(message: _133.Response): Uint8Array;
            toProtoMsg(message: _133.Response): _133.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _133.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseException;
            fromPartial(object: Partial<_133.ResponseException>): _133.ResponseException;
            fromAmino(object: _133.ResponseExceptionAmino): _133.ResponseException;
            toAmino(message: _133.ResponseException): _133.ResponseExceptionAmino;
            fromAminoMsg(object: _133.ResponseExceptionAminoMsg): _133.ResponseException;
            fromProtoMsg(message: _133.ResponseExceptionProtoMsg): _133.ResponseException;
            toProto(message: _133.ResponseException): Uint8Array;
            toProtoMsg(message: _133.ResponseException): _133.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _133.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseEcho;
            fromPartial(object: Partial<_133.ResponseEcho>): _133.ResponseEcho;
            fromAmino(object: _133.ResponseEchoAmino): _133.ResponseEcho;
            toAmino(message: _133.ResponseEcho): _133.ResponseEchoAmino;
            fromAminoMsg(object: _133.ResponseEchoAminoMsg): _133.ResponseEcho;
            fromProtoMsg(message: _133.ResponseEchoProtoMsg): _133.ResponseEcho;
            toProto(message: _133.ResponseEcho): Uint8Array;
            toProtoMsg(message: _133.ResponseEcho): _133.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _133.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _133.ResponseFlush;
            fromPartial(_: Partial<_133.ResponseFlush>): _133.ResponseFlush;
            fromAmino(_: _133.ResponseFlushAmino): _133.ResponseFlush;
            toAmino(_: _133.ResponseFlush): _133.ResponseFlushAmino;
            fromAminoMsg(object: _133.ResponseFlushAminoMsg): _133.ResponseFlush;
            fromProtoMsg(message: _133.ResponseFlushProtoMsg): _133.ResponseFlush;
            toProto(message: _133.ResponseFlush): Uint8Array;
            toProtoMsg(message: _133.ResponseFlush): _133.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _133.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseInfo;
            fromPartial(object: Partial<_133.ResponseInfo>): _133.ResponseInfo;
            fromAmino(object: _133.ResponseInfoAmino): _133.ResponseInfo;
            toAmino(message: _133.ResponseInfo): _133.ResponseInfoAmino;
            fromAminoMsg(object: _133.ResponseInfoAminoMsg): _133.ResponseInfo;
            fromProtoMsg(message: _133.ResponseInfoProtoMsg): _133.ResponseInfo;
            toProto(message: _133.ResponseInfo): Uint8Array;
            toProtoMsg(message: _133.ResponseInfo): _133.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            typeUrl: string;
            encode(message: _133.ResponseSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseSetOption;
            fromPartial(object: Partial<_133.ResponseSetOption>): _133.ResponseSetOption;
            fromAmino(object: _133.ResponseSetOptionAmino): _133.ResponseSetOption;
            toAmino(message: _133.ResponseSetOption): _133.ResponseSetOptionAmino;
            fromAminoMsg(object: _133.ResponseSetOptionAminoMsg): _133.ResponseSetOption;
            fromProtoMsg(message: _133.ResponseSetOptionProtoMsg): _133.ResponseSetOption;
            toProto(message: _133.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _133.ResponseSetOption): _133.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _133.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseInitChain;
            fromPartial(object: Partial<_133.ResponseInitChain>): _133.ResponseInitChain;
            fromAmino(object: _133.ResponseInitChainAmino): _133.ResponseInitChain;
            toAmino(message: _133.ResponseInitChain): _133.ResponseInitChainAmino;
            fromAminoMsg(object: _133.ResponseInitChainAminoMsg): _133.ResponseInitChain;
            fromProtoMsg(message: _133.ResponseInitChainProtoMsg): _133.ResponseInitChain;
            toProto(message: _133.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _133.ResponseInitChain): _133.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _133.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseQuery;
            fromPartial(object: Partial<_133.ResponseQuery>): _133.ResponseQuery;
            fromAmino(object: _133.ResponseQueryAmino): _133.ResponseQuery;
            toAmino(message: _133.ResponseQuery): _133.ResponseQueryAmino;
            fromAminoMsg(object: _133.ResponseQueryAminoMsg): _133.ResponseQuery;
            fromProtoMsg(message: _133.ResponseQueryProtoMsg): _133.ResponseQuery;
            toProto(message: _133.ResponseQuery): Uint8Array;
            toProtoMsg(message: _133.ResponseQuery): _133.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _133.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseBeginBlock;
            fromPartial(object: Partial<_133.ResponseBeginBlock>): _133.ResponseBeginBlock;
            fromAmino(object: _133.ResponseBeginBlockAmino): _133.ResponseBeginBlock;
            toAmino(message: _133.ResponseBeginBlock): _133.ResponseBeginBlockAmino;
            fromAminoMsg(object: _133.ResponseBeginBlockAminoMsg): _133.ResponseBeginBlock;
            fromProtoMsg(message: _133.ResponseBeginBlockProtoMsg): _133.ResponseBeginBlock;
            toProto(message: _133.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _133.ResponseBeginBlock): _133.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _133.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseCheckTx;
            fromPartial(object: Partial<_133.ResponseCheckTx>): _133.ResponseCheckTx;
            fromAmino(object: _133.ResponseCheckTxAmino): _133.ResponseCheckTx;
            toAmino(message: _133.ResponseCheckTx): _133.ResponseCheckTxAmino;
            fromAminoMsg(object: _133.ResponseCheckTxAminoMsg): _133.ResponseCheckTx;
            fromProtoMsg(message: _133.ResponseCheckTxProtoMsg): _133.ResponseCheckTx;
            toProto(message: _133.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _133.ResponseCheckTx): _133.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _133.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseDeliverTx;
            fromPartial(object: Partial<_133.ResponseDeliverTx>): _133.ResponseDeliverTx;
            fromAmino(object: _133.ResponseDeliverTxAmino): _133.ResponseDeliverTx;
            toAmino(message: _133.ResponseDeliverTx): _133.ResponseDeliverTxAmino;
            fromAminoMsg(object: _133.ResponseDeliverTxAminoMsg): _133.ResponseDeliverTx;
            fromProtoMsg(message: _133.ResponseDeliverTxProtoMsg): _133.ResponseDeliverTx;
            toProto(message: _133.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _133.ResponseDeliverTx): _133.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _133.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseEndBlock;
            fromPartial(object: Partial<_133.ResponseEndBlock>): _133.ResponseEndBlock;
            fromAmino(object: _133.ResponseEndBlockAmino): _133.ResponseEndBlock;
            toAmino(message: _133.ResponseEndBlock): _133.ResponseEndBlockAmino;
            fromAminoMsg(object: _133.ResponseEndBlockAminoMsg): _133.ResponseEndBlock;
            fromProtoMsg(message: _133.ResponseEndBlockProtoMsg): _133.ResponseEndBlock;
            toProto(message: _133.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _133.ResponseEndBlock): _133.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _133.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseCommit;
            fromPartial(object: Partial<_133.ResponseCommit>): _133.ResponseCommit;
            fromAmino(object: _133.ResponseCommitAmino): _133.ResponseCommit;
            toAmino(message: _133.ResponseCommit): _133.ResponseCommitAmino;
            fromAminoMsg(object: _133.ResponseCommitAminoMsg): _133.ResponseCommit;
            fromProtoMsg(message: _133.ResponseCommitProtoMsg): _133.ResponseCommit;
            toProto(message: _133.ResponseCommit): Uint8Array;
            toProtoMsg(message: _133.ResponseCommit): _133.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _133.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseListSnapshots;
            fromPartial(object: Partial<_133.ResponseListSnapshots>): _133.ResponseListSnapshots;
            fromAmino(object: _133.ResponseListSnapshotsAmino): _133.ResponseListSnapshots;
            toAmino(message: _133.ResponseListSnapshots): _133.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _133.ResponseListSnapshotsAminoMsg): _133.ResponseListSnapshots;
            fromProtoMsg(message: _133.ResponseListSnapshotsProtoMsg): _133.ResponseListSnapshots;
            toProto(message: _133.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _133.ResponseListSnapshots): _133.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _133.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseOfferSnapshot;
            fromPartial(object: Partial<_133.ResponseOfferSnapshot>): _133.ResponseOfferSnapshot;
            fromAmino(object: _133.ResponseOfferSnapshotAmino): _133.ResponseOfferSnapshot;
            toAmino(message: _133.ResponseOfferSnapshot): _133.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _133.ResponseOfferSnapshotAminoMsg): _133.ResponseOfferSnapshot;
            fromProtoMsg(message: _133.ResponseOfferSnapshotProtoMsg): _133.ResponseOfferSnapshot;
            toProto(message: _133.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _133.ResponseOfferSnapshot): _133.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _133.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_133.ResponseLoadSnapshotChunk>): _133.ResponseLoadSnapshotChunk;
            fromAmino(object: _133.ResponseLoadSnapshotChunkAmino): _133.ResponseLoadSnapshotChunk;
            toAmino(message: _133.ResponseLoadSnapshotChunk): _133.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _133.ResponseLoadSnapshotChunkAminoMsg): _133.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _133.ResponseLoadSnapshotChunkProtoMsg): _133.ResponseLoadSnapshotChunk;
            toProto(message: _133.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _133.ResponseLoadSnapshotChunk): _133.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _133.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_133.ResponseApplySnapshotChunk>): _133.ResponseApplySnapshotChunk;
            fromAmino(object: _133.ResponseApplySnapshotChunkAmino): _133.ResponseApplySnapshotChunk;
            toAmino(message: _133.ResponseApplySnapshotChunk): _133.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _133.ResponseApplySnapshotChunkAminoMsg): _133.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _133.ResponseApplySnapshotChunkProtoMsg): _133.ResponseApplySnapshotChunk;
            toProto(message: _133.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _133.ResponseApplySnapshotChunk): _133.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _133.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ConsensusParams;
            fromPartial(object: Partial<_133.ConsensusParams>): _133.ConsensusParams;
            fromAmino(object: _133.ConsensusParamsAmino): _133.ConsensusParams;
            toAmino(message: _133.ConsensusParams): _133.ConsensusParamsAmino;
            fromAminoMsg(object: _133.ConsensusParamsAminoMsg): _133.ConsensusParams;
            fromProtoMsg(message: _133.ConsensusParamsProtoMsg): _133.ConsensusParams;
            toProto(message: _133.ConsensusParams): Uint8Array;
            toProtoMsg(message: _133.ConsensusParams): _133.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _133.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.BlockParams;
            fromPartial(object: Partial<_133.BlockParams>): _133.BlockParams;
            fromAmino(object: _133.BlockParamsAmino): _133.BlockParams;
            toAmino(message: _133.BlockParams): _133.BlockParamsAmino;
            fromAminoMsg(object: _133.BlockParamsAminoMsg): _133.BlockParams;
            fromProtoMsg(message: _133.BlockParamsProtoMsg): _133.BlockParams;
            toProto(message: _133.BlockParams): Uint8Array;
            toProtoMsg(message: _133.BlockParams): _133.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            typeUrl: string;
            encode(message: _133.LastCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.LastCommitInfo;
            fromPartial(object: Partial<_133.LastCommitInfo>): _133.LastCommitInfo;
            fromAmino(object: _133.LastCommitInfoAmino): _133.LastCommitInfo;
            toAmino(message: _133.LastCommitInfo): _133.LastCommitInfoAmino;
            fromAminoMsg(object: _133.LastCommitInfoAminoMsg): _133.LastCommitInfo;
            fromProtoMsg(message: _133.LastCommitInfoProtoMsg): _133.LastCommitInfo;
            toProto(message: _133.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _133.LastCommitInfo): _133.LastCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _133.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.Event;
            fromPartial(object: Partial<_133.Event>): _133.Event;
            fromAmino(object: _133.EventAmino): _133.Event;
            toAmino(message: _133.Event): _133.EventAmino;
            fromAminoMsg(object: _133.EventAminoMsg): _133.Event;
            fromProtoMsg(message: _133.EventProtoMsg): _133.Event;
            toProto(message: _133.Event): Uint8Array;
            toProtoMsg(message: _133.Event): _133.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _133.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.EventAttribute;
            fromPartial(object: Partial<_133.EventAttribute>): _133.EventAttribute;
            fromAmino(object: _133.EventAttributeAmino): _133.EventAttribute;
            toAmino(message: _133.EventAttribute): _133.EventAttributeAmino;
            fromAminoMsg(object: _133.EventAttributeAminoMsg): _133.EventAttribute;
            fromProtoMsg(message: _133.EventAttributeProtoMsg): _133.EventAttribute;
            toProto(message: _133.EventAttribute): Uint8Array;
            toProtoMsg(message: _133.EventAttribute): _133.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _133.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.TxResult;
            fromPartial(object: Partial<_133.TxResult>): _133.TxResult;
            fromAmino(object: _133.TxResultAmino): _133.TxResult;
            toAmino(message: _133.TxResult): _133.TxResultAmino;
            fromAminoMsg(object: _133.TxResultAminoMsg): _133.TxResult;
            fromProtoMsg(message: _133.TxResultProtoMsg): _133.TxResult;
            toProto(message: _133.TxResult): Uint8Array;
            toProtoMsg(message: _133.TxResult): _133.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _133.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.Validator;
            fromPartial(object: Partial<_133.Validator>): _133.Validator;
            fromAmino(object: _133.ValidatorAmino): _133.Validator;
            toAmino(message: _133.Validator): _133.ValidatorAmino;
            fromAminoMsg(object: _133.ValidatorAminoMsg): _133.Validator;
            fromProtoMsg(message: _133.ValidatorProtoMsg): _133.Validator;
            toProto(message: _133.Validator): Uint8Array;
            toProtoMsg(message: _133.Validator): _133.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _133.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ValidatorUpdate;
            fromPartial(object: Partial<_133.ValidatorUpdate>): _133.ValidatorUpdate;
            fromAmino(object: _133.ValidatorUpdateAmino): _133.ValidatorUpdate;
            toAmino(message: _133.ValidatorUpdate): _133.ValidatorUpdateAmino;
            fromAminoMsg(object: _133.ValidatorUpdateAminoMsg): _133.ValidatorUpdate;
            fromProtoMsg(message: _133.ValidatorUpdateProtoMsg): _133.ValidatorUpdate;
            toProto(message: _133.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _133.ValidatorUpdate): _133.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _133.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.VoteInfo;
            fromPartial(object: Partial<_133.VoteInfo>): _133.VoteInfo;
            fromAmino(object: _133.VoteInfoAmino): _133.VoteInfo;
            toAmino(message: _133.VoteInfo): _133.VoteInfoAmino;
            fromAminoMsg(object: _133.VoteInfoAminoMsg): _133.VoteInfo;
            fromProtoMsg(message: _133.VoteInfoProtoMsg): _133.VoteInfo;
            toProto(message: _133.VoteInfo): Uint8Array;
            toProtoMsg(message: _133.VoteInfo): _133.VoteInfoProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _133.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.Evidence;
            fromPartial(object: Partial<_133.Evidence>): _133.Evidence;
            fromAmino(object: _133.EvidenceAmino): _133.Evidence;
            toAmino(message: _133.Evidence): _133.EvidenceAmino;
            fromAminoMsg(object: _133.EvidenceAminoMsg): _133.Evidence;
            fromProtoMsg(message: _133.EvidenceProtoMsg): _133.Evidence;
            toProto(message: _133.Evidence): Uint8Array;
            toProtoMsg(message: _133.Evidence): _133.EvidenceProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _133.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.Snapshot;
            fromPartial(object: Partial<_133.Snapshot>): _133.Snapshot;
            fromAmino(object: _133.SnapshotAmino): _133.Snapshot;
            toAmino(message: _133.Snapshot): _133.SnapshotAmino;
            fromAminoMsg(object: _133.SnapshotAminoMsg): _133.Snapshot;
            fromProtoMsg(message: _133.SnapshotProtoMsg): _133.Snapshot;
            toProto(message: _133.Snapshot): Uint8Array;
            toProtoMsg(message: _133.Snapshot): _133.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _135.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _135.Proof;
            fromPartial(object: Partial<_135.Proof>): _135.Proof;
            fromAmino(object: _135.ProofAmino): _135.Proof;
            toAmino(message: _135.Proof): _135.ProofAmino;
            fromAminoMsg(object: _135.ProofAminoMsg): _135.Proof;
            fromProtoMsg(message: _135.ProofProtoMsg): _135.Proof;
            toProto(message: _135.Proof): Uint8Array;
            toProtoMsg(message: _135.Proof): _135.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _135.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _135.ValueOp;
            fromPartial(object: Partial<_135.ValueOp>): _135.ValueOp;
            fromAmino(object: _135.ValueOpAmino): _135.ValueOp;
            toAmino(message: _135.ValueOp): _135.ValueOpAmino;
            fromAminoMsg(object: _135.ValueOpAminoMsg): _135.ValueOp;
            fromProtoMsg(message: _135.ValueOpProtoMsg): _135.ValueOp;
            toProto(message: _135.ValueOp): Uint8Array;
            toProtoMsg(message: _135.ValueOp): _135.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _135.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _135.DominoOp;
            fromPartial(object: Partial<_135.DominoOp>): _135.DominoOp;
            fromAmino(object: _135.DominoOpAmino): _135.DominoOp;
            toAmino(message: _135.DominoOp): _135.DominoOpAmino;
            fromAminoMsg(object: _135.DominoOpAminoMsg): _135.DominoOp;
            fromProtoMsg(message: _135.DominoOpProtoMsg): _135.DominoOp;
            toProto(message: _135.DominoOp): Uint8Array;
            toProtoMsg(message: _135.DominoOp): _135.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _135.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _135.ProofOp;
            fromPartial(object: Partial<_135.ProofOp>): _135.ProofOp;
            fromAmino(object: _135.ProofOpAmino): _135.ProofOp;
            toAmino(message: _135.ProofOp): _135.ProofOpAmino;
            fromAminoMsg(object: _135.ProofOpAminoMsg): _135.ProofOp;
            fromProtoMsg(message: _135.ProofOpProtoMsg): _135.ProofOp;
            toProto(message: _135.ProofOp): Uint8Array;
            toProtoMsg(message: _135.ProofOp): _135.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _135.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _135.ProofOps;
            fromPartial(object: Partial<_135.ProofOps>): _135.ProofOps;
            fromAmino(object: _135.ProofOpsAmino): _135.ProofOps;
            toAmino(message: _135.ProofOps): _135.ProofOpsAmino;
            fromAminoMsg(object: _135.ProofOpsAminoMsg): _135.ProofOps;
            fromProtoMsg(message: _135.ProofOpsProtoMsg): _135.ProofOps;
            toProto(message: _135.ProofOps): Uint8Array;
            toProtoMsg(message: _135.ProofOps): _135.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _134.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.PublicKey;
            fromPartial(object: Partial<_134.PublicKey>): _134.PublicKey;
            fromAmino(object: _134.PublicKeyAmino): _134.PublicKey;
            toAmino(message: _134.PublicKey): _134.PublicKeyAmino;
            fromAminoMsg(object: _134.PublicKeyAminoMsg): _134.PublicKey;
            fromProtoMsg(message: _134.PublicKeyProtoMsg): _134.PublicKey;
            toProto(message: _134.PublicKey): Uint8Array;
            toProtoMsg(message: _134.PublicKey): _134.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _136.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                fromJSON(object: any): _136.BitArray;
                fromPartial(object: Partial<_136.BitArray>): _136.BitArray;
                fromAmino(object: _136.BitArrayAmino): _136.BitArray;
                toAmino(message: _136.BitArray): _136.BitArrayAmino;
                fromAminoMsg(object: _136.BitArrayAminoMsg): _136.BitArray;
                fromProtoMsg(message: _136.BitArrayProtoMsg): _136.BitArray;
                toProto(message: _136.BitArray): Uint8Array;
                toProtoMsg(message: _136.BitArray): _136.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _137.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.NetAddress;
            fromPartial(object: Partial<_137.NetAddress>): _137.NetAddress;
            fromAmino(object: _137.NetAddressAmino): _137.NetAddress;
            toAmino(message: _137.NetAddress): _137.NetAddressAmino;
            fromAminoMsg(object: _137.NetAddressAminoMsg): _137.NetAddress;
            fromProtoMsg(message: _137.NetAddressProtoMsg): _137.NetAddress;
            toProto(message: _137.NetAddress): Uint8Array;
            toProtoMsg(message: _137.NetAddress): _137.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _137.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ProtocolVersion;
            fromPartial(object: Partial<_137.ProtocolVersion>): _137.ProtocolVersion;
            fromAmino(object: _137.ProtocolVersionAmino): _137.ProtocolVersion;
            toAmino(message: _137.ProtocolVersion): _137.ProtocolVersionAmino;
            fromAminoMsg(object: _137.ProtocolVersionAminoMsg): _137.ProtocolVersion;
            fromProtoMsg(message: _137.ProtocolVersionProtoMsg): _137.ProtocolVersion;
            toProto(message: _137.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _137.ProtocolVersion): _137.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _137.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.DefaultNodeInfo;
            fromPartial(object: Partial<_137.DefaultNodeInfo>): _137.DefaultNodeInfo;
            fromAmino(object: _137.DefaultNodeInfoAmino): _137.DefaultNodeInfo;
            toAmino(message: _137.DefaultNodeInfo): _137.DefaultNodeInfoAmino;
            fromAminoMsg(object: _137.DefaultNodeInfoAminoMsg): _137.DefaultNodeInfo;
            fromProtoMsg(message: _137.DefaultNodeInfoProtoMsg): _137.DefaultNodeInfo;
            toProto(message: _137.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _137.DefaultNodeInfo): _137.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _137.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.DefaultNodeInfoOther;
            fromPartial(object: Partial<_137.DefaultNodeInfoOther>): _137.DefaultNodeInfoOther;
            fromAmino(object: _137.DefaultNodeInfoOtherAmino): _137.DefaultNodeInfoOther;
            toAmino(message: _137.DefaultNodeInfoOther): _137.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _137.DefaultNodeInfoOtherAminoMsg): _137.DefaultNodeInfoOther;
            fromProtoMsg(message: _137.DefaultNodeInfoOtherProtoMsg): _137.DefaultNodeInfoOther;
            toProto(message: _137.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _137.DefaultNodeInfoOther): _137.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _142.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _142.ValidatorSet;
            fromPartial(object: Partial<_142.ValidatorSet>): _142.ValidatorSet;
            fromAmino(object: _142.ValidatorSetAmino): _142.ValidatorSet;
            toAmino(message: _142.ValidatorSet): _142.ValidatorSetAmino;
            fromAminoMsg(object: _142.ValidatorSetAminoMsg): _142.ValidatorSet;
            fromProtoMsg(message: _142.ValidatorSetProtoMsg): _142.ValidatorSet;
            toProto(message: _142.ValidatorSet): Uint8Array;
            toProtoMsg(message: _142.ValidatorSet): _142.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _142.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _142.Validator;
            fromPartial(object: Partial<_142.Validator>): _142.Validator;
            fromAmino(object: _142.ValidatorAmino): _142.Validator;
            toAmino(message: _142.Validator): _142.ValidatorAmino;
            fromAminoMsg(object: _142.ValidatorAminoMsg): _142.Validator;
            fromProtoMsg(message: _142.ValidatorProtoMsg): _142.Validator;
            toProto(message: _142.Validator): Uint8Array;
            toProtoMsg(message: _142.Validator): _142.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _142.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _142.SimpleValidator;
            fromPartial(object: Partial<_142.SimpleValidator>): _142.SimpleValidator;
            fromAmino(object: _142.SimpleValidatorAmino): _142.SimpleValidator;
            toAmino(message: _142.SimpleValidator): _142.SimpleValidatorAmino;
            fromAminoMsg(object: _142.SimpleValidatorAminoMsg): _142.SimpleValidator;
            fromProtoMsg(message: _142.SimpleValidatorProtoMsg): _142.SimpleValidator;
            toProto(message: _142.SimpleValidator): Uint8Array;
            toProtoMsg(message: _142.SimpleValidator): _142.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _141.BlockIDFlag;
        blockIDFlagToJSON(object: _141.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _141.SignedMsgType;
        signedMsgTypeToJSON(object: _141.SignedMsgType): string;
        BlockIDFlag: typeof _141.BlockIDFlag;
        BlockIDFlagSDKType: typeof _141.BlockIDFlag;
        BlockIDFlagAmino: typeof _141.BlockIDFlag;
        SignedMsgType: typeof _141.SignedMsgType;
        SignedMsgTypeSDKType: typeof _141.SignedMsgType;
        SignedMsgTypeAmino: typeof _141.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _141.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.PartSetHeader;
            fromPartial(object: Partial<_141.PartSetHeader>): _141.PartSetHeader;
            fromAmino(object: _141.PartSetHeaderAmino): _141.PartSetHeader;
            toAmino(message: _141.PartSetHeader): _141.PartSetHeaderAmino;
            fromAminoMsg(object: _141.PartSetHeaderAminoMsg): _141.PartSetHeader;
            fromProtoMsg(message: _141.PartSetHeaderProtoMsg): _141.PartSetHeader;
            toProto(message: _141.PartSetHeader): Uint8Array;
            toProtoMsg(message: _141.PartSetHeader): _141.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _141.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.Part;
            fromPartial(object: Partial<_141.Part>): _141.Part;
            fromAmino(object: _141.PartAmino): _141.Part;
            toAmino(message: _141.Part): _141.PartAmino;
            fromAminoMsg(object: _141.PartAminoMsg): _141.Part;
            fromProtoMsg(message: _141.PartProtoMsg): _141.Part;
            toProto(message: _141.Part): Uint8Array;
            toProtoMsg(message: _141.Part): _141.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _141.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.BlockID;
            fromPartial(object: Partial<_141.BlockID>): _141.BlockID;
            fromAmino(object: _141.BlockIDAmino): _141.BlockID;
            toAmino(message: _141.BlockID): _141.BlockIDAmino;
            fromAminoMsg(object: _141.BlockIDAminoMsg): _141.BlockID;
            fromProtoMsg(message: _141.BlockIDProtoMsg): _141.BlockID;
            toProto(message: _141.BlockID): Uint8Array;
            toProtoMsg(message: _141.BlockID): _141.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _141.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.Header;
            fromPartial(object: Partial<_141.Header>): _141.Header;
            fromAmino(object: _141.HeaderAmino): _141.Header;
            toAmino(message: _141.Header): _141.HeaderAmino;
            fromAminoMsg(object: _141.HeaderAminoMsg): _141.Header;
            fromProtoMsg(message: _141.HeaderProtoMsg): _141.Header;
            toProto(message: _141.Header): Uint8Array;
            toProtoMsg(message: _141.Header): _141.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _141.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.Data;
            fromPartial(object: Partial<_141.Data>): _141.Data;
            fromAmino(object: _141.DataAmino): _141.Data;
            toAmino(message: _141.Data): _141.DataAmino;
            fromAminoMsg(object: _141.DataAminoMsg): _141.Data;
            fromProtoMsg(message: _141.DataProtoMsg): _141.Data;
            toProto(message: _141.Data): Uint8Array;
            toProtoMsg(message: _141.Data): _141.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _141.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.Vote;
            fromPartial(object: Partial<_141.Vote>): _141.Vote;
            fromAmino(object: _141.VoteAmino): _141.Vote;
            toAmino(message: _141.Vote): _141.VoteAmino;
            fromAminoMsg(object: _141.VoteAminoMsg): _141.Vote;
            fromProtoMsg(message: _141.VoteProtoMsg): _141.Vote;
            toProto(message: _141.Vote): Uint8Array;
            toProtoMsg(message: _141.Vote): _141.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _141.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.Commit;
            fromPartial(object: Partial<_141.Commit>): _141.Commit;
            fromAmino(object: _141.CommitAmino): _141.Commit;
            toAmino(message: _141.Commit): _141.CommitAmino;
            fromAminoMsg(object: _141.CommitAminoMsg): _141.Commit;
            fromProtoMsg(message: _141.CommitProtoMsg): _141.Commit;
            toProto(message: _141.Commit): Uint8Array;
            toProtoMsg(message: _141.Commit): _141.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _141.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.CommitSig;
            fromPartial(object: Partial<_141.CommitSig>): _141.CommitSig;
            fromAmino(object: _141.CommitSigAmino): _141.CommitSig;
            toAmino(message: _141.CommitSig): _141.CommitSigAmino;
            fromAminoMsg(object: _141.CommitSigAminoMsg): _141.CommitSig;
            fromProtoMsg(message: _141.CommitSigProtoMsg): _141.CommitSig;
            toProto(message: _141.CommitSig): Uint8Array;
            toProtoMsg(message: _141.CommitSig): _141.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _141.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.Proposal;
            fromPartial(object: Partial<_141.Proposal>): _141.Proposal;
            fromAmino(object: _141.ProposalAmino): _141.Proposal;
            toAmino(message: _141.Proposal): _141.ProposalAmino;
            fromAminoMsg(object: _141.ProposalAminoMsg): _141.Proposal;
            fromProtoMsg(message: _141.ProposalProtoMsg): _141.Proposal;
            toProto(message: _141.Proposal): Uint8Array;
            toProtoMsg(message: _141.Proposal): _141.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _141.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.SignedHeader;
            fromPartial(object: Partial<_141.SignedHeader>): _141.SignedHeader;
            fromAmino(object: _141.SignedHeaderAmino): _141.SignedHeader;
            toAmino(message: _141.SignedHeader): _141.SignedHeaderAmino;
            fromAminoMsg(object: _141.SignedHeaderAminoMsg): _141.SignedHeader;
            fromProtoMsg(message: _141.SignedHeaderProtoMsg): _141.SignedHeader;
            toProto(message: _141.SignedHeader): Uint8Array;
            toProtoMsg(message: _141.SignedHeader): _141.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _141.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.LightBlock;
            fromPartial(object: Partial<_141.LightBlock>): _141.LightBlock;
            fromAmino(object: _141.LightBlockAmino): _141.LightBlock;
            toAmino(message: _141.LightBlock): _141.LightBlockAmino;
            fromAminoMsg(object: _141.LightBlockAminoMsg): _141.LightBlock;
            fromProtoMsg(message: _141.LightBlockProtoMsg): _141.LightBlock;
            toProto(message: _141.LightBlock): Uint8Array;
            toProtoMsg(message: _141.LightBlock): _141.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _141.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.BlockMeta;
            fromPartial(object: Partial<_141.BlockMeta>): _141.BlockMeta;
            fromAmino(object: _141.BlockMetaAmino): _141.BlockMeta;
            toAmino(message: _141.BlockMeta): _141.BlockMetaAmino;
            fromAminoMsg(object: _141.BlockMetaAminoMsg): _141.BlockMeta;
            fromProtoMsg(message: _141.BlockMetaProtoMsg): _141.BlockMeta;
            toProto(message: _141.BlockMeta): Uint8Array;
            toProtoMsg(message: _141.BlockMeta): _141.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _141.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.TxProof;
            fromPartial(object: Partial<_141.TxProof>): _141.TxProof;
            fromAmino(object: _141.TxProofAmino): _141.TxProof;
            toAmino(message: _141.TxProof): _141.TxProofAmino;
            fromAminoMsg(object: _141.TxProofAminoMsg): _141.TxProof;
            fromProtoMsg(message: _141.TxProofProtoMsg): _141.TxProof;
            toProto(message: _141.TxProof): Uint8Array;
            toProtoMsg(message: _141.TxProof): _141.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _140.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _140.ConsensusParams;
            fromPartial(object: Partial<_140.ConsensusParams>): _140.ConsensusParams;
            fromAmino(object: _140.ConsensusParamsAmino): _140.ConsensusParams;
            toAmino(message: _140.ConsensusParams): _140.ConsensusParamsAmino;
            fromAminoMsg(object: _140.ConsensusParamsAminoMsg): _140.ConsensusParams;
            fromProtoMsg(message: _140.ConsensusParamsProtoMsg): _140.ConsensusParams;
            toProto(message: _140.ConsensusParams): Uint8Array;
            toProtoMsg(message: _140.ConsensusParams): _140.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _140.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _140.BlockParams;
            fromPartial(object: Partial<_140.BlockParams>): _140.BlockParams;
            fromAmino(object: _140.BlockParamsAmino): _140.BlockParams;
            toAmino(message: _140.BlockParams): _140.BlockParamsAmino;
            fromAminoMsg(object: _140.BlockParamsAminoMsg): _140.BlockParams;
            fromProtoMsg(message: _140.BlockParamsProtoMsg): _140.BlockParams;
            toProto(message: _140.BlockParams): Uint8Array;
            toProtoMsg(message: _140.BlockParams): _140.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _140.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _140.EvidenceParams;
            fromPartial(object: Partial<_140.EvidenceParams>): _140.EvidenceParams;
            fromAmino(object: _140.EvidenceParamsAmino): _140.EvidenceParams;
            toAmino(message: _140.EvidenceParams): _140.EvidenceParamsAmino;
            fromAminoMsg(object: _140.EvidenceParamsAminoMsg): _140.EvidenceParams;
            fromProtoMsg(message: _140.EvidenceParamsProtoMsg): _140.EvidenceParams;
            toProto(message: _140.EvidenceParams): Uint8Array;
            toProtoMsg(message: _140.EvidenceParams): _140.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _140.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _140.ValidatorParams;
            fromPartial(object: Partial<_140.ValidatorParams>): _140.ValidatorParams;
            fromAmino(object: _140.ValidatorParamsAmino): _140.ValidatorParams;
            toAmino(message: _140.ValidatorParams): _140.ValidatorParamsAmino;
            fromAminoMsg(object: _140.ValidatorParamsAminoMsg): _140.ValidatorParams;
            fromProtoMsg(message: _140.ValidatorParamsProtoMsg): _140.ValidatorParams;
            toProto(message: _140.ValidatorParams): Uint8Array;
            toProtoMsg(message: _140.ValidatorParams): _140.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _140.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _140.VersionParams;
            fromPartial(object: Partial<_140.VersionParams>): _140.VersionParams;
            fromAmino(object: _140.VersionParamsAmino): _140.VersionParams;
            toAmino(message: _140.VersionParams): _140.VersionParamsAmino;
            fromAminoMsg(object: _140.VersionParamsAminoMsg): _140.VersionParams;
            fromProtoMsg(message: _140.VersionParamsProtoMsg): _140.VersionParams;
            toProto(message: _140.VersionParams): Uint8Array;
            toProtoMsg(message: _140.VersionParams): _140.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _140.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _140.HashedParams;
            fromPartial(object: Partial<_140.HashedParams>): _140.HashedParams;
            fromAmino(object: _140.HashedParamsAmino): _140.HashedParams;
            toAmino(message: _140.HashedParams): _140.HashedParamsAmino;
            fromAminoMsg(object: _140.HashedParamsAminoMsg): _140.HashedParams;
            fromProtoMsg(message: _140.HashedParamsProtoMsg): _140.HashedParams;
            toProto(message: _140.HashedParams): Uint8Array;
            toProtoMsg(message: _140.HashedParams): _140.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _139.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _139.Evidence;
            fromPartial(object: Partial<_139.Evidence>): _139.Evidence;
            fromAmino(object: _139.EvidenceAmino): _139.Evidence;
            toAmino(message: _139.Evidence): _139.EvidenceAmino;
            fromAminoMsg(object: _139.EvidenceAminoMsg): _139.Evidence;
            fromProtoMsg(message: _139.EvidenceProtoMsg): _139.Evidence;
            toProto(message: _139.Evidence): Uint8Array;
            toProtoMsg(message: _139.Evidence): _139.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _139.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _139.DuplicateVoteEvidence;
            fromPartial(object: Partial<_139.DuplicateVoteEvidence>): _139.DuplicateVoteEvidence;
            fromAmino(object: _139.DuplicateVoteEvidenceAmino): _139.DuplicateVoteEvidence;
            toAmino(message: _139.DuplicateVoteEvidence): _139.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _139.DuplicateVoteEvidenceAminoMsg): _139.DuplicateVoteEvidence;
            fromProtoMsg(message: _139.DuplicateVoteEvidenceProtoMsg): _139.DuplicateVoteEvidence;
            toProto(message: _139.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _139.DuplicateVoteEvidence): _139.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _139.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _139.LightClientAttackEvidence;
            fromPartial(object: Partial<_139.LightClientAttackEvidence>): _139.LightClientAttackEvidence;
            fromAmino(object: _139.LightClientAttackEvidenceAmino): _139.LightClientAttackEvidence;
            toAmino(message: _139.LightClientAttackEvidence): _139.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _139.LightClientAttackEvidenceAminoMsg): _139.LightClientAttackEvidence;
            fromProtoMsg(message: _139.LightClientAttackEvidenceProtoMsg): _139.LightClientAttackEvidence;
            toProto(message: _139.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _139.LightClientAttackEvidence): _139.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _139.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _139.EvidenceList;
            fromPartial(object: Partial<_139.EvidenceList>): _139.EvidenceList;
            fromAmino(object: _139.EvidenceListAmino): _139.EvidenceList;
            toAmino(message: _139.EvidenceList): _139.EvidenceListAmino;
            fromAminoMsg(object: _139.EvidenceListAminoMsg): _139.EvidenceList;
            fromProtoMsg(message: _139.EvidenceListProtoMsg): _139.EvidenceList;
            toProto(message: _139.EvidenceList): Uint8Array;
            toProtoMsg(message: _139.EvidenceList): _139.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _138.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _138.Block;
            fromPartial(object: Partial<_138.Block>): _138.Block;
            fromAmino(object: _138.BlockAmino): _138.Block;
            toAmino(message: _138.Block): _138.BlockAmino;
            fromAminoMsg(object: _138.BlockAminoMsg): _138.Block;
            fromProtoMsg(message: _138.BlockProtoMsg): _138.Block;
            toProto(message: _138.Block): Uint8Array;
            toProtoMsg(message: _138.Block): _138.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _143.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.App;
            fromPartial(object: Partial<_143.App>): _143.App;
            fromAmino(object: _143.AppAmino): _143.App;
            toAmino(message: _143.App): _143.AppAmino;
            fromAminoMsg(object: _143.AppAminoMsg): _143.App;
            fromProtoMsg(message: _143.AppProtoMsg): _143.App;
            toProto(message: _143.App): Uint8Array;
            toProtoMsg(message: _143.App): _143.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _143.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.Consensus;
            fromPartial(object: Partial<_143.Consensus>): _143.Consensus;
            fromAmino(object: _143.ConsensusAmino): _143.Consensus;
            toAmino(message: _143.Consensus): _143.ConsensusAmino;
            fromAminoMsg(object: _143.ConsensusAminoMsg): _143.Consensus;
            fromProtoMsg(message: _143.ConsensusProtoMsg): _143.Consensus;
            toProto(message: _143.Consensus): Uint8Array;
            toProtoMsg(message: _143.Consensus): _143.ConsensusProtoMsg;
        };
    };
}
