import * as _126 from "./abci/types";
import * as _127 from "./crypto/keys";
import * as _128 from "./crypto/proof";
import * as _129 from "./libs/bits/types";
import * as _130 from "./p2p/types";
import * as _131 from "./types/block";
import * as _132 from "./types/evidence";
import * as _133 from "./types/params";
import * as _134 from "./types/types";
import * as _135 from "./types/validator";
import * as _136 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _126.CheckTxType;
        checkTxTypeToJSON(object: _126.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _126.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _126.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _126.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _126.ResponseApplySnapshotChunk_Result): string;
        responseProcessProposal_ProposalStatusFromJSON(object: any): _126.ResponseProcessProposal_ProposalStatus;
        responseProcessProposal_ProposalStatusToJSON(object: _126.ResponseProcessProposal_ProposalStatus): string;
        misbehaviorTypeFromJSON(object: any): _126.MisbehaviorType;
        misbehaviorTypeToJSON(object: _126.MisbehaviorType): string;
        CheckTxType: typeof _126.CheckTxType;
        CheckTxTypeSDKType: typeof _126.CheckTxType;
        CheckTxTypeAmino: typeof _126.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _126.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _126.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _126.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _126.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _126.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _126.ResponseApplySnapshotChunk_Result;
        ResponseProcessProposal_ProposalStatus: typeof _126.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusSDKType: typeof _126.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusAmino: typeof _126.ResponseProcessProposal_ProposalStatus;
        MisbehaviorType: typeof _126.MisbehaviorType;
        MisbehaviorTypeSDKType: typeof _126.MisbehaviorType;
        MisbehaviorTypeAmino: typeof _126.MisbehaviorType;
        Request: {
            typeUrl: string;
            encode(message: _126.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.Request;
            fromPartial(object: Partial<_126.Request>): _126.Request;
            fromAmino(object: _126.RequestAmino): _126.Request;
            toAmino(message: _126.Request): _126.RequestAmino;
            fromAminoMsg(object: _126.RequestAminoMsg): _126.Request;
            fromProtoMsg(message: _126.RequestProtoMsg): _126.Request;
            toProto(message: _126.Request): Uint8Array;
            toProtoMsg(message: _126.Request): _126.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _126.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestEcho;
            fromPartial(object: Partial<_126.RequestEcho>): _126.RequestEcho;
            fromAmino(object: _126.RequestEchoAmino): _126.RequestEcho;
            toAmino(message: _126.RequestEcho): _126.RequestEchoAmino;
            fromAminoMsg(object: _126.RequestEchoAminoMsg): _126.RequestEcho;
            fromProtoMsg(message: _126.RequestEchoProtoMsg): _126.RequestEcho;
            toProto(message: _126.RequestEcho): Uint8Array;
            toProtoMsg(message: _126.RequestEcho): _126.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _126.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _126.RequestFlush;
            fromPartial(_: Partial<_126.RequestFlush>): _126.RequestFlush;
            fromAmino(_: _126.RequestFlushAmino): _126.RequestFlush;
            toAmino(_: _126.RequestFlush): _126.RequestFlushAmino;
            fromAminoMsg(object: _126.RequestFlushAminoMsg): _126.RequestFlush;
            fromProtoMsg(message: _126.RequestFlushProtoMsg): _126.RequestFlush;
            toProto(message: _126.RequestFlush): Uint8Array;
            toProtoMsg(message: _126.RequestFlush): _126.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _126.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestInfo;
            fromPartial(object: Partial<_126.RequestInfo>): _126.RequestInfo;
            fromAmino(object: _126.RequestInfoAmino): _126.RequestInfo;
            toAmino(message: _126.RequestInfo): _126.RequestInfoAmino;
            fromAminoMsg(object: _126.RequestInfoAminoMsg): _126.RequestInfo;
            fromProtoMsg(message: _126.RequestInfoProtoMsg): _126.RequestInfo;
            toProto(message: _126.RequestInfo): Uint8Array;
            toProtoMsg(message: _126.RequestInfo): _126.RequestInfoProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _126.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestInitChain;
            fromPartial(object: Partial<_126.RequestInitChain>): _126.RequestInitChain;
            fromAmino(object: _126.RequestInitChainAmino): _126.RequestInitChain;
            toAmino(message: _126.RequestInitChain): _126.RequestInitChainAmino;
            fromAminoMsg(object: _126.RequestInitChainAminoMsg): _126.RequestInitChain;
            fromProtoMsg(message: _126.RequestInitChainProtoMsg): _126.RequestInitChain;
            toProto(message: _126.RequestInitChain): Uint8Array;
            toProtoMsg(message: _126.RequestInitChain): _126.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _126.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestQuery;
            fromPartial(object: Partial<_126.RequestQuery>): _126.RequestQuery;
            fromAmino(object: _126.RequestQueryAmino): _126.RequestQuery;
            toAmino(message: _126.RequestQuery): _126.RequestQueryAmino;
            fromAminoMsg(object: _126.RequestQueryAminoMsg): _126.RequestQuery;
            fromProtoMsg(message: _126.RequestQueryProtoMsg): _126.RequestQuery;
            toProto(message: _126.RequestQuery): Uint8Array;
            toProtoMsg(message: _126.RequestQuery): _126.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _126.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestBeginBlock;
            fromPartial(object: Partial<_126.RequestBeginBlock>): _126.RequestBeginBlock;
            fromAmino(object: _126.RequestBeginBlockAmino): _126.RequestBeginBlock;
            toAmino(message: _126.RequestBeginBlock): _126.RequestBeginBlockAmino;
            fromAminoMsg(object: _126.RequestBeginBlockAminoMsg): _126.RequestBeginBlock;
            fromProtoMsg(message: _126.RequestBeginBlockProtoMsg): _126.RequestBeginBlock;
            toProto(message: _126.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _126.RequestBeginBlock): _126.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _126.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestCheckTx;
            fromPartial(object: Partial<_126.RequestCheckTx>): _126.RequestCheckTx;
            fromAmino(object: _126.RequestCheckTxAmino): _126.RequestCheckTx;
            toAmino(message: _126.RequestCheckTx): _126.RequestCheckTxAmino;
            fromAminoMsg(object: _126.RequestCheckTxAminoMsg): _126.RequestCheckTx;
            fromProtoMsg(message: _126.RequestCheckTxProtoMsg): _126.RequestCheckTx;
            toProto(message: _126.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _126.RequestCheckTx): _126.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _126.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestDeliverTx;
            fromPartial(object: Partial<_126.RequestDeliverTx>): _126.RequestDeliverTx;
            fromAmino(object: _126.RequestDeliverTxAmino): _126.RequestDeliverTx;
            toAmino(message: _126.RequestDeliverTx): _126.RequestDeliverTxAmino;
            fromAminoMsg(object: _126.RequestDeliverTxAminoMsg): _126.RequestDeliverTx;
            fromProtoMsg(message: _126.RequestDeliverTxProtoMsg): _126.RequestDeliverTx;
            toProto(message: _126.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _126.RequestDeliverTx): _126.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _126.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestEndBlock;
            fromPartial(object: Partial<_126.RequestEndBlock>): _126.RequestEndBlock;
            fromAmino(object: _126.RequestEndBlockAmino): _126.RequestEndBlock;
            toAmino(message: _126.RequestEndBlock): _126.RequestEndBlockAmino;
            fromAminoMsg(object: _126.RequestEndBlockAminoMsg): _126.RequestEndBlock;
            fromProtoMsg(message: _126.RequestEndBlockProtoMsg): _126.RequestEndBlock;
            toProto(message: _126.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _126.RequestEndBlock): _126.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _126.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _126.RequestCommit;
            fromPartial(_: Partial<_126.RequestCommit>): _126.RequestCommit;
            fromAmino(_: _126.RequestCommitAmino): _126.RequestCommit;
            toAmino(_: _126.RequestCommit): _126.RequestCommitAmino;
            fromAminoMsg(object: _126.RequestCommitAminoMsg): _126.RequestCommit;
            fromProtoMsg(message: _126.RequestCommitProtoMsg): _126.RequestCommit;
            toProto(message: _126.RequestCommit): Uint8Array;
            toProtoMsg(message: _126.RequestCommit): _126.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _126.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _126.RequestListSnapshots;
            fromPartial(_: Partial<_126.RequestListSnapshots>): _126.RequestListSnapshots;
            fromAmino(_: _126.RequestListSnapshotsAmino): _126.RequestListSnapshots;
            toAmino(_: _126.RequestListSnapshots): _126.RequestListSnapshotsAmino;
            fromAminoMsg(object: _126.RequestListSnapshotsAminoMsg): _126.RequestListSnapshots;
            fromProtoMsg(message: _126.RequestListSnapshotsProtoMsg): _126.RequestListSnapshots;
            toProto(message: _126.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _126.RequestListSnapshots): _126.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _126.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestOfferSnapshot;
            fromPartial(object: Partial<_126.RequestOfferSnapshot>): _126.RequestOfferSnapshot;
            fromAmino(object: _126.RequestOfferSnapshotAmino): _126.RequestOfferSnapshot;
            toAmino(message: _126.RequestOfferSnapshot): _126.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _126.RequestOfferSnapshotAminoMsg): _126.RequestOfferSnapshot;
            fromProtoMsg(message: _126.RequestOfferSnapshotProtoMsg): _126.RequestOfferSnapshot;
            toProto(message: _126.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _126.RequestOfferSnapshot): _126.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _126.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_126.RequestLoadSnapshotChunk>): _126.RequestLoadSnapshotChunk;
            fromAmino(object: _126.RequestLoadSnapshotChunkAmino): _126.RequestLoadSnapshotChunk;
            toAmino(message: _126.RequestLoadSnapshotChunk): _126.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _126.RequestLoadSnapshotChunkAminoMsg): _126.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _126.RequestLoadSnapshotChunkProtoMsg): _126.RequestLoadSnapshotChunk;
            toProto(message: _126.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _126.RequestLoadSnapshotChunk): _126.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _126.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_126.RequestApplySnapshotChunk>): _126.RequestApplySnapshotChunk;
            fromAmino(object: _126.RequestApplySnapshotChunkAmino): _126.RequestApplySnapshotChunk;
            toAmino(message: _126.RequestApplySnapshotChunk): _126.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _126.RequestApplySnapshotChunkAminoMsg): _126.RequestApplySnapshotChunk;
            fromProtoMsg(message: _126.RequestApplySnapshotChunkProtoMsg): _126.RequestApplySnapshotChunk;
            toProto(message: _126.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _126.RequestApplySnapshotChunk): _126.RequestApplySnapshotChunkProtoMsg;
        };
        RequestPrepareProposal: {
            typeUrl: string;
            encode(message: _126.RequestPrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestPrepareProposal;
            fromPartial(object: Partial<_126.RequestPrepareProposal>): _126.RequestPrepareProposal;
            fromAmino(object: _126.RequestPrepareProposalAmino): _126.RequestPrepareProposal;
            toAmino(message: _126.RequestPrepareProposal): _126.RequestPrepareProposalAmino;
            fromAminoMsg(object: _126.RequestPrepareProposalAminoMsg): _126.RequestPrepareProposal;
            fromProtoMsg(message: _126.RequestPrepareProposalProtoMsg): _126.RequestPrepareProposal;
            toProto(message: _126.RequestPrepareProposal): Uint8Array;
            toProtoMsg(message: _126.RequestPrepareProposal): _126.RequestPrepareProposalProtoMsg;
        };
        RequestProcessProposal: {
            typeUrl: string;
            encode(message: _126.RequestProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.RequestProcessProposal;
            fromPartial(object: Partial<_126.RequestProcessProposal>): _126.RequestProcessProposal;
            fromAmino(object: _126.RequestProcessProposalAmino): _126.RequestProcessProposal;
            toAmino(message: _126.RequestProcessProposal): _126.RequestProcessProposalAmino;
            fromAminoMsg(object: _126.RequestProcessProposalAminoMsg): _126.RequestProcessProposal;
            fromProtoMsg(message: _126.RequestProcessProposalProtoMsg): _126.RequestProcessProposal;
            toProto(message: _126.RequestProcessProposal): Uint8Array;
            toProtoMsg(message: _126.RequestProcessProposal): _126.RequestProcessProposalProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _126.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.Response;
            fromPartial(object: Partial<_126.Response>): _126.Response;
            fromAmino(object: _126.ResponseAmino): _126.Response;
            toAmino(message: _126.Response): _126.ResponseAmino;
            fromAminoMsg(object: _126.ResponseAminoMsg): _126.Response;
            fromProtoMsg(message: _126.ResponseProtoMsg): _126.Response;
            toProto(message: _126.Response): Uint8Array;
            toProtoMsg(message: _126.Response): _126.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _126.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseException;
            fromPartial(object: Partial<_126.ResponseException>): _126.ResponseException;
            fromAmino(object: _126.ResponseExceptionAmino): _126.ResponseException;
            toAmino(message: _126.ResponseException): _126.ResponseExceptionAmino;
            fromAminoMsg(object: _126.ResponseExceptionAminoMsg): _126.ResponseException;
            fromProtoMsg(message: _126.ResponseExceptionProtoMsg): _126.ResponseException;
            toProto(message: _126.ResponseException): Uint8Array;
            toProtoMsg(message: _126.ResponseException): _126.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _126.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseEcho;
            fromPartial(object: Partial<_126.ResponseEcho>): _126.ResponseEcho;
            fromAmino(object: _126.ResponseEchoAmino): _126.ResponseEcho;
            toAmino(message: _126.ResponseEcho): _126.ResponseEchoAmino;
            fromAminoMsg(object: _126.ResponseEchoAminoMsg): _126.ResponseEcho;
            fromProtoMsg(message: _126.ResponseEchoProtoMsg): _126.ResponseEcho;
            toProto(message: _126.ResponseEcho): Uint8Array;
            toProtoMsg(message: _126.ResponseEcho): _126.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _126.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _126.ResponseFlush;
            fromPartial(_: Partial<_126.ResponseFlush>): _126.ResponseFlush;
            fromAmino(_: _126.ResponseFlushAmino): _126.ResponseFlush;
            toAmino(_: _126.ResponseFlush): _126.ResponseFlushAmino;
            fromAminoMsg(object: _126.ResponseFlushAminoMsg): _126.ResponseFlush;
            fromProtoMsg(message: _126.ResponseFlushProtoMsg): _126.ResponseFlush;
            toProto(message: _126.ResponseFlush): Uint8Array;
            toProtoMsg(message: _126.ResponseFlush): _126.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _126.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseInfo;
            fromPartial(object: Partial<_126.ResponseInfo>): _126.ResponseInfo;
            fromAmino(object: _126.ResponseInfoAmino): _126.ResponseInfo;
            toAmino(message: _126.ResponseInfo): _126.ResponseInfoAmino;
            fromAminoMsg(object: _126.ResponseInfoAminoMsg): _126.ResponseInfo;
            fromProtoMsg(message: _126.ResponseInfoProtoMsg): _126.ResponseInfo;
            toProto(message: _126.ResponseInfo): Uint8Array;
            toProtoMsg(message: _126.ResponseInfo): _126.ResponseInfoProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _126.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseInitChain;
            fromPartial(object: Partial<_126.ResponseInitChain>): _126.ResponseInitChain;
            fromAmino(object: _126.ResponseInitChainAmino): _126.ResponseInitChain;
            toAmino(message: _126.ResponseInitChain): _126.ResponseInitChainAmino;
            fromAminoMsg(object: _126.ResponseInitChainAminoMsg): _126.ResponseInitChain;
            fromProtoMsg(message: _126.ResponseInitChainProtoMsg): _126.ResponseInitChain;
            toProto(message: _126.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _126.ResponseInitChain): _126.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _126.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseQuery;
            fromPartial(object: Partial<_126.ResponseQuery>): _126.ResponseQuery;
            fromAmino(object: _126.ResponseQueryAmino): _126.ResponseQuery;
            toAmino(message: _126.ResponseQuery): _126.ResponseQueryAmino;
            fromAminoMsg(object: _126.ResponseQueryAminoMsg): _126.ResponseQuery;
            fromProtoMsg(message: _126.ResponseQueryProtoMsg): _126.ResponseQuery;
            toProto(message: _126.ResponseQuery): Uint8Array;
            toProtoMsg(message: _126.ResponseQuery): _126.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _126.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseBeginBlock;
            fromPartial(object: Partial<_126.ResponseBeginBlock>): _126.ResponseBeginBlock;
            fromAmino(object: _126.ResponseBeginBlockAmino): _126.ResponseBeginBlock;
            toAmino(message: _126.ResponseBeginBlock): _126.ResponseBeginBlockAmino;
            fromAminoMsg(object: _126.ResponseBeginBlockAminoMsg): _126.ResponseBeginBlock;
            fromProtoMsg(message: _126.ResponseBeginBlockProtoMsg): _126.ResponseBeginBlock;
            toProto(message: _126.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _126.ResponseBeginBlock): _126.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _126.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseCheckTx;
            fromPartial(object: Partial<_126.ResponseCheckTx>): _126.ResponseCheckTx;
            fromAmino(object: _126.ResponseCheckTxAmino): _126.ResponseCheckTx;
            toAmino(message: _126.ResponseCheckTx): _126.ResponseCheckTxAmino;
            fromAminoMsg(object: _126.ResponseCheckTxAminoMsg): _126.ResponseCheckTx;
            fromProtoMsg(message: _126.ResponseCheckTxProtoMsg): _126.ResponseCheckTx;
            toProto(message: _126.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _126.ResponseCheckTx): _126.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _126.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseDeliverTx;
            fromPartial(object: Partial<_126.ResponseDeliverTx>): _126.ResponseDeliverTx;
            fromAmino(object: _126.ResponseDeliverTxAmino): _126.ResponseDeliverTx;
            toAmino(message: _126.ResponseDeliverTx): _126.ResponseDeliverTxAmino;
            fromAminoMsg(object: _126.ResponseDeliverTxAminoMsg): _126.ResponseDeliverTx;
            fromProtoMsg(message: _126.ResponseDeliverTxProtoMsg): _126.ResponseDeliverTx;
            toProto(message: _126.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _126.ResponseDeliverTx): _126.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _126.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseEndBlock;
            fromPartial(object: Partial<_126.ResponseEndBlock>): _126.ResponseEndBlock;
            fromAmino(object: _126.ResponseEndBlockAmino): _126.ResponseEndBlock;
            toAmino(message: _126.ResponseEndBlock): _126.ResponseEndBlockAmino;
            fromAminoMsg(object: _126.ResponseEndBlockAminoMsg): _126.ResponseEndBlock;
            fromProtoMsg(message: _126.ResponseEndBlockProtoMsg): _126.ResponseEndBlock;
            toProto(message: _126.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _126.ResponseEndBlock): _126.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _126.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseCommit;
            fromPartial(object: Partial<_126.ResponseCommit>): _126.ResponseCommit;
            fromAmino(object: _126.ResponseCommitAmino): _126.ResponseCommit;
            toAmino(message: _126.ResponseCommit): _126.ResponseCommitAmino;
            fromAminoMsg(object: _126.ResponseCommitAminoMsg): _126.ResponseCommit;
            fromProtoMsg(message: _126.ResponseCommitProtoMsg): _126.ResponseCommit;
            toProto(message: _126.ResponseCommit): Uint8Array;
            toProtoMsg(message: _126.ResponseCommit): _126.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _126.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseListSnapshots;
            fromPartial(object: Partial<_126.ResponseListSnapshots>): _126.ResponseListSnapshots;
            fromAmino(object: _126.ResponseListSnapshotsAmino): _126.ResponseListSnapshots;
            toAmino(message: _126.ResponseListSnapshots): _126.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _126.ResponseListSnapshotsAminoMsg): _126.ResponseListSnapshots;
            fromProtoMsg(message: _126.ResponseListSnapshotsProtoMsg): _126.ResponseListSnapshots;
            toProto(message: _126.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _126.ResponseListSnapshots): _126.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _126.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseOfferSnapshot;
            fromPartial(object: Partial<_126.ResponseOfferSnapshot>): _126.ResponseOfferSnapshot;
            fromAmino(object: _126.ResponseOfferSnapshotAmino): _126.ResponseOfferSnapshot;
            toAmino(message: _126.ResponseOfferSnapshot): _126.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _126.ResponseOfferSnapshotAminoMsg): _126.ResponseOfferSnapshot;
            fromProtoMsg(message: _126.ResponseOfferSnapshotProtoMsg): _126.ResponseOfferSnapshot;
            toProto(message: _126.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _126.ResponseOfferSnapshot): _126.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _126.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_126.ResponseLoadSnapshotChunk>): _126.ResponseLoadSnapshotChunk;
            fromAmino(object: _126.ResponseLoadSnapshotChunkAmino): _126.ResponseLoadSnapshotChunk;
            toAmino(message: _126.ResponseLoadSnapshotChunk): _126.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _126.ResponseLoadSnapshotChunkAminoMsg): _126.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _126.ResponseLoadSnapshotChunkProtoMsg): _126.ResponseLoadSnapshotChunk;
            toProto(message: _126.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _126.ResponseLoadSnapshotChunk): _126.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _126.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_126.ResponseApplySnapshotChunk>): _126.ResponseApplySnapshotChunk;
            fromAmino(object: _126.ResponseApplySnapshotChunkAmino): _126.ResponseApplySnapshotChunk;
            toAmino(message: _126.ResponseApplySnapshotChunk): _126.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _126.ResponseApplySnapshotChunkAminoMsg): _126.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _126.ResponseApplySnapshotChunkProtoMsg): _126.ResponseApplySnapshotChunk;
            toProto(message: _126.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _126.ResponseApplySnapshotChunk): _126.ResponseApplySnapshotChunkProtoMsg;
        };
        ResponsePrepareProposal: {
            typeUrl: string;
            encode(message: _126.ResponsePrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponsePrepareProposal;
            fromPartial(object: Partial<_126.ResponsePrepareProposal>): _126.ResponsePrepareProposal;
            fromAmino(object: _126.ResponsePrepareProposalAmino): _126.ResponsePrepareProposal;
            toAmino(message: _126.ResponsePrepareProposal): _126.ResponsePrepareProposalAmino;
            fromAminoMsg(object: _126.ResponsePrepareProposalAminoMsg): _126.ResponsePrepareProposal;
            fromProtoMsg(message: _126.ResponsePrepareProposalProtoMsg): _126.ResponsePrepareProposal;
            toProto(message: _126.ResponsePrepareProposal): Uint8Array;
            toProtoMsg(message: _126.ResponsePrepareProposal): _126.ResponsePrepareProposalProtoMsg;
        };
        ResponseProcessProposal: {
            typeUrl: string;
            encode(message: _126.ResponseProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ResponseProcessProposal;
            fromPartial(object: Partial<_126.ResponseProcessProposal>): _126.ResponseProcessProposal;
            fromAmino(object: _126.ResponseProcessProposalAmino): _126.ResponseProcessProposal;
            toAmino(message: _126.ResponseProcessProposal): _126.ResponseProcessProposalAmino;
            fromAminoMsg(object: _126.ResponseProcessProposalAminoMsg): _126.ResponseProcessProposal;
            fromProtoMsg(message: _126.ResponseProcessProposalProtoMsg): _126.ResponseProcessProposal;
            toProto(message: _126.ResponseProcessProposal): Uint8Array;
            toProtoMsg(message: _126.ResponseProcessProposal): _126.ResponseProcessProposalProtoMsg;
        };
        CommitInfo: {
            typeUrl: string;
            encode(message: _126.CommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.CommitInfo;
            fromPartial(object: Partial<_126.CommitInfo>): _126.CommitInfo;
            fromAmino(object: _126.CommitInfoAmino): _126.CommitInfo;
            toAmino(message: _126.CommitInfo): _126.CommitInfoAmino;
            fromAminoMsg(object: _126.CommitInfoAminoMsg): _126.CommitInfo;
            fromProtoMsg(message: _126.CommitInfoProtoMsg): _126.CommitInfo;
            toProto(message: _126.CommitInfo): Uint8Array;
            toProtoMsg(message: _126.CommitInfo): _126.CommitInfoProtoMsg;
        };
        ExtendedCommitInfo: {
            typeUrl: string;
            encode(message: _126.ExtendedCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ExtendedCommitInfo;
            fromPartial(object: Partial<_126.ExtendedCommitInfo>): _126.ExtendedCommitInfo;
            fromAmino(object: _126.ExtendedCommitInfoAmino): _126.ExtendedCommitInfo;
            toAmino(message: _126.ExtendedCommitInfo): _126.ExtendedCommitInfoAmino;
            fromAminoMsg(object: _126.ExtendedCommitInfoAminoMsg): _126.ExtendedCommitInfo;
            fromProtoMsg(message: _126.ExtendedCommitInfoProtoMsg): _126.ExtendedCommitInfo;
            toProto(message: _126.ExtendedCommitInfo): Uint8Array;
            toProtoMsg(message: _126.ExtendedCommitInfo): _126.ExtendedCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _126.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.Event;
            fromPartial(object: Partial<_126.Event>): _126.Event;
            fromAmino(object: _126.EventAmino): _126.Event;
            toAmino(message: _126.Event): _126.EventAmino;
            fromAminoMsg(object: _126.EventAminoMsg): _126.Event;
            fromProtoMsg(message: _126.EventProtoMsg): _126.Event;
            toProto(message: _126.Event): Uint8Array;
            toProtoMsg(message: _126.Event): _126.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _126.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.EventAttribute;
            fromPartial(object: Partial<_126.EventAttribute>): _126.EventAttribute;
            fromAmino(object: _126.EventAttributeAmino): _126.EventAttribute;
            toAmino(message: _126.EventAttribute): _126.EventAttributeAmino;
            fromAminoMsg(object: _126.EventAttributeAminoMsg): _126.EventAttribute;
            fromProtoMsg(message: _126.EventAttributeProtoMsg): _126.EventAttribute;
            toProto(message: _126.EventAttribute): Uint8Array;
            toProtoMsg(message: _126.EventAttribute): _126.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _126.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.TxResult;
            fromPartial(object: Partial<_126.TxResult>): _126.TxResult;
            fromAmino(object: _126.TxResultAmino): _126.TxResult;
            toAmino(message: _126.TxResult): _126.TxResultAmino;
            fromAminoMsg(object: _126.TxResultAminoMsg): _126.TxResult;
            fromProtoMsg(message: _126.TxResultProtoMsg): _126.TxResult;
            toProto(message: _126.TxResult): Uint8Array;
            toProtoMsg(message: _126.TxResult): _126.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _126.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.Validator;
            fromPartial(object: Partial<_126.Validator>): _126.Validator;
            fromAmino(object: _126.ValidatorAmino): _126.Validator;
            toAmino(message: _126.Validator): _126.ValidatorAmino;
            fromAminoMsg(object: _126.ValidatorAminoMsg): _126.Validator;
            fromProtoMsg(message: _126.ValidatorProtoMsg): _126.Validator;
            toProto(message: _126.Validator): Uint8Array;
            toProtoMsg(message: _126.Validator): _126.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _126.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ValidatorUpdate;
            fromPartial(object: Partial<_126.ValidatorUpdate>): _126.ValidatorUpdate;
            fromAmino(object: _126.ValidatorUpdateAmino): _126.ValidatorUpdate;
            toAmino(message: _126.ValidatorUpdate): _126.ValidatorUpdateAmino;
            fromAminoMsg(object: _126.ValidatorUpdateAminoMsg): _126.ValidatorUpdate;
            fromProtoMsg(message: _126.ValidatorUpdateProtoMsg): _126.ValidatorUpdate;
            toProto(message: _126.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _126.ValidatorUpdate): _126.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _126.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.VoteInfo;
            fromPartial(object: Partial<_126.VoteInfo>): _126.VoteInfo;
            fromAmino(object: _126.VoteInfoAmino): _126.VoteInfo;
            toAmino(message: _126.VoteInfo): _126.VoteInfoAmino;
            fromAminoMsg(object: _126.VoteInfoAminoMsg): _126.VoteInfo;
            fromProtoMsg(message: _126.VoteInfoProtoMsg): _126.VoteInfo;
            toProto(message: _126.VoteInfo): Uint8Array;
            toProtoMsg(message: _126.VoteInfo): _126.VoteInfoProtoMsg;
        };
        ExtendedVoteInfo: {
            typeUrl: string;
            encode(message: _126.ExtendedVoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ExtendedVoteInfo;
            fromPartial(object: Partial<_126.ExtendedVoteInfo>): _126.ExtendedVoteInfo;
            fromAmino(object: _126.ExtendedVoteInfoAmino): _126.ExtendedVoteInfo;
            toAmino(message: _126.ExtendedVoteInfo): _126.ExtendedVoteInfoAmino;
            fromAminoMsg(object: _126.ExtendedVoteInfoAminoMsg): _126.ExtendedVoteInfo;
            fromProtoMsg(message: _126.ExtendedVoteInfoProtoMsg): _126.ExtendedVoteInfo;
            toProto(message: _126.ExtendedVoteInfo): Uint8Array;
            toProtoMsg(message: _126.ExtendedVoteInfo): _126.ExtendedVoteInfoProtoMsg;
        };
        Misbehavior: {
            typeUrl: string;
            encode(message: _126.Misbehavior, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.Misbehavior;
            fromPartial(object: Partial<_126.Misbehavior>): _126.Misbehavior;
            fromAmino(object: _126.MisbehaviorAmino): _126.Misbehavior;
            toAmino(message: _126.Misbehavior): _126.MisbehaviorAmino;
            fromAminoMsg(object: _126.MisbehaviorAminoMsg): _126.Misbehavior;
            fromProtoMsg(message: _126.MisbehaviorProtoMsg): _126.Misbehavior;
            toProto(message: _126.Misbehavior): Uint8Array;
            toProtoMsg(message: _126.Misbehavior): _126.MisbehaviorProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _126.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.Snapshot;
            fromPartial(object: Partial<_126.Snapshot>): _126.Snapshot;
            fromAmino(object: _126.SnapshotAmino): _126.Snapshot;
            toAmino(message: _126.Snapshot): _126.SnapshotAmino;
            fromAminoMsg(object: _126.SnapshotAminoMsg): _126.Snapshot;
            fromProtoMsg(message: _126.SnapshotProtoMsg): _126.Snapshot;
            toProto(message: _126.Snapshot): Uint8Array;
            toProtoMsg(message: _126.Snapshot): _126.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _128.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _128.Proof;
            fromPartial(object: Partial<_128.Proof>): _128.Proof;
            fromAmino(object: _128.ProofAmino): _128.Proof;
            toAmino(message: _128.Proof): _128.ProofAmino;
            fromAminoMsg(object: _128.ProofAminoMsg): _128.Proof;
            fromProtoMsg(message: _128.ProofProtoMsg): _128.Proof;
            toProto(message: _128.Proof): Uint8Array;
            toProtoMsg(message: _128.Proof): _128.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _128.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _128.ValueOp;
            fromPartial(object: Partial<_128.ValueOp>): _128.ValueOp;
            fromAmino(object: _128.ValueOpAmino): _128.ValueOp;
            toAmino(message: _128.ValueOp): _128.ValueOpAmino;
            fromAminoMsg(object: _128.ValueOpAminoMsg): _128.ValueOp;
            fromProtoMsg(message: _128.ValueOpProtoMsg): _128.ValueOp;
            toProto(message: _128.ValueOp): Uint8Array;
            toProtoMsg(message: _128.ValueOp): _128.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _128.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _128.DominoOp;
            fromPartial(object: Partial<_128.DominoOp>): _128.DominoOp;
            fromAmino(object: _128.DominoOpAmino): _128.DominoOp;
            toAmino(message: _128.DominoOp): _128.DominoOpAmino;
            fromAminoMsg(object: _128.DominoOpAminoMsg): _128.DominoOp;
            fromProtoMsg(message: _128.DominoOpProtoMsg): _128.DominoOp;
            toProto(message: _128.DominoOp): Uint8Array;
            toProtoMsg(message: _128.DominoOp): _128.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _128.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _128.ProofOp;
            fromPartial(object: Partial<_128.ProofOp>): _128.ProofOp;
            fromAmino(object: _128.ProofOpAmino): _128.ProofOp;
            toAmino(message: _128.ProofOp): _128.ProofOpAmino;
            fromAminoMsg(object: _128.ProofOpAminoMsg): _128.ProofOp;
            fromProtoMsg(message: _128.ProofOpProtoMsg): _128.ProofOp;
            toProto(message: _128.ProofOp): Uint8Array;
            toProtoMsg(message: _128.ProofOp): _128.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _128.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _128.ProofOps;
            fromPartial(object: Partial<_128.ProofOps>): _128.ProofOps;
            fromAmino(object: _128.ProofOpsAmino): _128.ProofOps;
            toAmino(message: _128.ProofOps): _128.ProofOpsAmino;
            fromAminoMsg(object: _128.ProofOpsAminoMsg): _128.ProofOps;
            fromProtoMsg(message: _128.ProofOpsProtoMsg): _128.ProofOps;
            toProto(message: _128.ProofOps): Uint8Array;
            toProtoMsg(message: _128.ProofOps): _128.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _127.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.PublicKey;
            fromPartial(object: Partial<_127.PublicKey>): _127.PublicKey;
            fromAmino(object: _127.PublicKeyAmino): _127.PublicKey;
            toAmino(message: _127.PublicKey): _127.PublicKeyAmino;
            fromAminoMsg(object: _127.PublicKeyAminoMsg): _127.PublicKey;
            fromProtoMsg(message: _127.PublicKeyProtoMsg): _127.PublicKey;
            toProto(message: _127.PublicKey): Uint8Array;
            toProtoMsg(message: _127.PublicKey): _127.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _129.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                fromJSON(object: any): _129.BitArray;
                fromPartial(object: Partial<_129.BitArray>): _129.BitArray;
                fromAmino(object: _129.BitArrayAmino): _129.BitArray;
                toAmino(message: _129.BitArray): _129.BitArrayAmino;
                fromAminoMsg(object: _129.BitArrayAminoMsg): _129.BitArray;
                fromProtoMsg(message: _129.BitArrayProtoMsg): _129.BitArray;
                toProto(message: _129.BitArray): Uint8Array;
                toProtoMsg(message: _129.BitArray): _129.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _130.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _130.NetAddress;
            fromPartial(object: Partial<_130.NetAddress>): _130.NetAddress;
            fromAmino(object: _130.NetAddressAmino): _130.NetAddress;
            toAmino(message: _130.NetAddress): _130.NetAddressAmino;
            fromAminoMsg(object: _130.NetAddressAminoMsg): _130.NetAddress;
            fromProtoMsg(message: _130.NetAddressProtoMsg): _130.NetAddress;
            toProto(message: _130.NetAddress): Uint8Array;
            toProtoMsg(message: _130.NetAddress): _130.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _130.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _130.ProtocolVersion;
            fromPartial(object: Partial<_130.ProtocolVersion>): _130.ProtocolVersion;
            fromAmino(object: _130.ProtocolVersionAmino): _130.ProtocolVersion;
            toAmino(message: _130.ProtocolVersion): _130.ProtocolVersionAmino;
            fromAminoMsg(object: _130.ProtocolVersionAminoMsg): _130.ProtocolVersion;
            fromProtoMsg(message: _130.ProtocolVersionProtoMsg): _130.ProtocolVersion;
            toProto(message: _130.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _130.ProtocolVersion): _130.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _130.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _130.DefaultNodeInfo;
            fromPartial(object: Partial<_130.DefaultNodeInfo>): _130.DefaultNodeInfo;
            fromAmino(object: _130.DefaultNodeInfoAmino): _130.DefaultNodeInfo;
            toAmino(message: _130.DefaultNodeInfo): _130.DefaultNodeInfoAmino;
            fromAminoMsg(object: _130.DefaultNodeInfoAminoMsg): _130.DefaultNodeInfo;
            fromProtoMsg(message: _130.DefaultNodeInfoProtoMsg): _130.DefaultNodeInfo;
            toProto(message: _130.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _130.DefaultNodeInfo): _130.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _130.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _130.DefaultNodeInfoOther;
            fromPartial(object: Partial<_130.DefaultNodeInfoOther>): _130.DefaultNodeInfoOther;
            fromAmino(object: _130.DefaultNodeInfoOtherAmino): _130.DefaultNodeInfoOther;
            toAmino(message: _130.DefaultNodeInfoOther): _130.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _130.DefaultNodeInfoOtherAminoMsg): _130.DefaultNodeInfoOther;
            fromProtoMsg(message: _130.DefaultNodeInfoOtherProtoMsg): _130.DefaultNodeInfoOther;
            toProto(message: _130.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _130.DefaultNodeInfoOther): _130.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _135.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _135.ValidatorSet;
            fromPartial(object: Partial<_135.ValidatorSet>): _135.ValidatorSet;
            fromAmino(object: _135.ValidatorSetAmino): _135.ValidatorSet;
            toAmino(message: _135.ValidatorSet): _135.ValidatorSetAmino;
            fromAminoMsg(object: _135.ValidatorSetAminoMsg): _135.ValidatorSet;
            fromProtoMsg(message: _135.ValidatorSetProtoMsg): _135.ValidatorSet;
            toProto(message: _135.ValidatorSet): Uint8Array;
            toProtoMsg(message: _135.ValidatorSet): _135.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _135.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _135.Validator;
            fromPartial(object: Partial<_135.Validator>): _135.Validator;
            fromAmino(object: _135.ValidatorAmino): _135.Validator;
            toAmino(message: _135.Validator): _135.ValidatorAmino;
            fromAminoMsg(object: _135.ValidatorAminoMsg): _135.Validator;
            fromProtoMsg(message: _135.ValidatorProtoMsg): _135.Validator;
            toProto(message: _135.Validator): Uint8Array;
            toProtoMsg(message: _135.Validator): _135.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _135.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _135.SimpleValidator;
            fromPartial(object: Partial<_135.SimpleValidator>): _135.SimpleValidator;
            fromAmino(object: _135.SimpleValidatorAmino): _135.SimpleValidator;
            toAmino(message: _135.SimpleValidator): _135.SimpleValidatorAmino;
            fromAminoMsg(object: _135.SimpleValidatorAminoMsg): _135.SimpleValidator;
            fromProtoMsg(message: _135.SimpleValidatorProtoMsg): _135.SimpleValidator;
            toProto(message: _135.SimpleValidator): Uint8Array;
            toProtoMsg(message: _135.SimpleValidator): _135.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _134.BlockIDFlag;
        blockIDFlagToJSON(object: _134.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _134.SignedMsgType;
        signedMsgTypeToJSON(object: _134.SignedMsgType): string;
        BlockIDFlag: typeof _134.BlockIDFlag;
        BlockIDFlagSDKType: typeof _134.BlockIDFlag;
        BlockIDFlagAmino: typeof _134.BlockIDFlag;
        SignedMsgType: typeof _134.SignedMsgType;
        SignedMsgTypeSDKType: typeof _134.SignedMsgType;
        SignedMsgTypeAmino: typeof _134.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _134.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.PartSetHeader;
            fromPartial(object: Partial<_134.PartSetHeader>): _134.PartSetHeader;
            fromAmino(object: _134.PartSetHeaderAmino): _134.PartSetHeader;
            toAmino(message: _134.PartSetHeader): _134.PartSetHeaderAmino;
            fromAminoMsg(object: _134.PartSetHeaderAminoMsg): _134.PartSetHeader;
            fromProtoMsg(message: _134.PartSetHeaderProtoMsg): _134.PartSetHeader;
            toProto(message: _134.PartSetHeader): Uint8Array;
            toProtoMsg(message: _134.PartSetHeader): _134.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _134.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.Part;
            fromPartial(object: Partial<_134.Part>): _134.Part;
            fromAmino(object: _134.PartAmino): _134.Part;
            toAmino(message: _134.Part): _134.PartAmino;
            fromAminoMsg(object: _134.PartAminoMsg): _134.Part;
            fromProtoMsg(message: _134.PartProtoMsg): _134.Part;
            toProto(message: _134.Part): Uint8Array;
            toProtoMsg(message: _134.Part): _134.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _134.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.BlockID;
            fromPartial(object: Partial<_134.BlockID>): _134.BlockID;
            fromAmino(object: _134.BlockIDAmino): _134.BlockID;
            toAmino(message: _134.BlockID): _134.BlockIDAmino;
            fromAminoMsg(object: _134.BlockIDAminoMsg): _134.BlockID;
            fromProtoMsg(message: _134.BlockIDProtoMsg): _134.BlockID;
            toProto(message: _134.BlockID): Uint8Array;
            toProtoMsg(message: _134.BlockID): _134.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _134.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.Header;
            fromPartial(object: Partial<_134.Header>): _134.Header;
            fromAmino(object: _134.HeaderAmino): _134.Header;
            toAmino(message: _134.Header): _134.HeaderAmino;
            fromAminoMsg(object: _134.HeaderAminoMsg): _134.Header;
            fromProtoMsg(message: _134.HeaderProtoMsg): _134.Header;
            toProto(message: _134.Header): Uint8Array;
            toProtoMsg(message: _134.Header): _134.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _134.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.Data;
            fromPartial(object: Partial<_134.Data>): _134.Data;
            fromAmino(object: _134.DataAmino): _134.Data;
            toAmino(message: _134.Data): _134.DataAmino;
            fromAminoMsg(object: _134.DataAminoMsg): _134.Data;
            fromProtoMsg(message: _134.DataProtoMsg): _134.Data;
            toProto(message: _134.Data): Uint8Array;
            toProtoMsg(message: _134.Data): _134.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _134.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.Vote;
            fromPartial(object: Partial<_134.Vote>): _134.Vote;
            fromAmino(object: _134.VoteAmino): _134.Vote;
            toAmino(message: _134.Vote): _134.VoteAmino;
            fromAminoMsg(object: _134.VoteAminoMsg): _134.Vote;
            fromProtoMsg(message: _134.VoteProtoMsg): _134.Vote;
            toProto(message: _134.Vote): Uint8Array;
            toProtoMsg(message: _134.Vote): _134.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _134.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.Commit;
            fromPartial(object: Partial<_134.Commit>): _134.Commit;
            fromAmino(object: _134.CommitAmino): _134.Commit;
            toAmino(message: _134.Commit): _134.CommitAmino;
            fromAminoMsg(object: _134.CommitAminoMsg): _134.Commit;
            fromProtoMsg(message: _134.CommitProtoMsg): _134.Commit;
            toProto(message: _134.Commit): Uint8Array;
            toProtoMsg(message: _134.Commit): _134.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _134.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.CommitSig;
            fromPartial(object: Partial<_134.CommitSig>): _134.CommitSig;
            fromAmino(object: _134.CommitSigAmino): _134.CommitSig;
            toAmino(message: _134.CommitSig): _134.CommitSigAmino;
            fromAminoMsg(object: _134.CommitSigAminoMsg): _134.CommitSig;
            fromProtoMsg(message: _134.CommitSigProtoMsg): _134.CommitSig;
            toProto(message: _134.CommitSig): Uint8Array;
            toProtoMsg(message: _134.CommitSig): _134.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _134.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.Proposal;
            fromPartial(object: Partial<_134.Proposal>): _134.Proposal;
            fromAmino(object: _134.ProposalAmino): _134.Proposal;
            toAmino(message: _134.Proposal): _134.ProposalAmino;
            fromAminoMsg(object: _134.ProposalAminoMsg): _134.Proposal;
            fromProtoMsg(message: _134.ProposalProtoMsg): _134.Proposal;
            toProto(message: _134.Proposal): Uint8Array;
            toProtoMsg(message: _134.Proposal): _134.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _134.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.SignedHeader;
            fromPartial(object: Partial<_134.SignedHeader>): _134.SignedHeader;
            fromAmino(object: _134.SignedHeaderAmino): _134.SignedHeader;
            toAmino(message: _134.SignedHeader): _134.SignedHeaderAmino;
            fromAminoMsg(object: _134.SignedHeaderAminoMsg): _134.SignedHeader;
            fromProtoMsg(message: _134.SignedHeaderProtoMsg): _134.SignedHeader;
            toProto(message: _134.SignedHeader): Uint8Array;
            toProtoMsg(message: _134.SignedHeader): _134.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _134.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.LightBlock;
            fromPartial(object: Partial<_134.LightBlock>): _134.LightBlock;
            fromAmino(object: _134.LightBlockAmino): _134.LightBlock;
            toAmino(message: _134.LightBlock): _134.LightBlockAmino;
            fromAminoMsg(object: _134.LightBlockAminoMsg): _134.LightBlock;
            fromProtoMsg(message: _134.LightBlockProtoMsg): _134.LightBlock;
            toProto(message: _134.LightBlock): Uint8Array;
            toProtoMsg(message: _134.LightBlock): _134.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _134.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.BlockMeta;
            fromPartial(object: Partial<_134.BlockMeta>): _134.BlockMeta;
            fromAmino(object: _134.BlockMetaAmino): _134.BlockMeta;
            toAmino(message: _134.BlockMeta): _134.BlockMetaAmino;
            fromAminoMsg(object: _134.BlockMetaAminoMsg): _134.BlockMeta;
            fromProtoMsg(message: _134.BlockMetaProtoMsg): _134.BlockMeta;
            toProto(message: _134.BlockMeta): Uint8Array;
            toProtoMsg(message: _134.BlockMeta): _134.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _134.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.TxProof;
            fromPartial(object: Partial<_134.TxProof>): _134.TxProof;
            fromAmino(object: _134.TxProofAmino): _134.TxProof;
            toAmino(message: _134.TxProof): _134.TxProofAmino;
            fromAminoMsg(object: _134.TxProofAminoMsg): _134.TxProof;
            fromProtoMsg(message: _134.TxProofProtoMsg): _134.TxProof;
            toProto(message: _134.TxProof): Uint8Array;
            toProtoMsg(message: _134.TxProof): _134.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _133.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ConsensusParams;
            fromPartial(object: Partial<_133.ConsensusParams>): _133.ConsensusParams;
            fromAmino(object: _133.ConsensusParamsAmino): _133.ConsensusParams;
            toAmino(message: _133.ConsensusParams): _133.ConsensusParamsAmino;
            fromAminoMsg(object: _133.ConsensusParamsAminoMsg): _133.ConsensusParams;
            fromProtoMsg(message: _133.ConsensusParamsProtoMsg): _133.ConsensusParams;
            toProto(message: _133.ConsensusParams): Uint8Array;
            toProtoMsg(message: _133.ConsensusParams): _133.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _133.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.BlockParams;
            fromPartial(object: Partial<_133.BlockParams>): _133.BlockParams;
            fromAmino(object: _133.BlockParamsAmino): _133.BlockParams;
            toAmino(message: _133.BlockParams): _133.BlockParamsAmino;
            fromAminoMsg(object: _133.BlockParamsAminoMsg): _133.BlockParams;
            fromProtoMsg(message: _133.BlockParamsProtoMsg): _133.BlockParams;
            toProto(message: _133.BlockParams): Uint8Array;
            toProtoMsg(message: _133.BlockParams): _133.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _133.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.EvidenceParams;
            fromPartial(object: Partial<_133.EvidenceParams>): _133.EvidenceParams;
            fromAmino(object: _133.EvidenceParamsAmino): _133.EvidenceParams;
            toAmino(message: _133.EvidenceParams): _133.EvidenceParamsAmino;
            fromAminoMsg(object: _133.EvidenceParamsAminoMsg): _133.EvidenceParams;
            fromProtoMsg(message: _133.EvidenceParamsProtoMsg): _133.EvidenceParams;
            toProto(message: _133.EvidenceParams): Uint8Array;
            toProtoMsg(message: _133.EvidenceParams): _133.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _133.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ValidatorParams;
            fromPartial(object: Partial<_133.ValidatorParams>): _133.ValidatorParams;
            fromAmino(object: _133.ValidatorParamsAmino): _133.ValidatorParams;
            toAmino(message: _133.ValidatorParams): _133.ValidatorParamsAmino;
            fromAminoMsg(object: _133.ValidatorParamsAminoMsg): _133.ValidatorParams;
            fromProtoMsg(message: _133.ValidatorParamsProtoMsg): _133.ValidatorParams;
            toProto(message: _133.ValidatorParams): Uint8Array;
            toProtoMsg(message: _133.ValidatorParams): _133.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _133.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.VersionParams;
            fromPartial(object: Partial<_133.VersionParams>): _133.VersionParams;
            fromAmino(object: _133.VersionParamsAmino): _133.VersionParams;
            toAmino(message: _133.VersionParams): _133.VersionParamsAmino;
            fromAminoMsg(object: _133.VersionParamsAminoMsg): _133.VersionParams;
            fromProtoMsg(message: _133.VersionParamsProtoMsg): _133.VersionParams;
            toProto(message: _133.VersionParams): Uint8Array;
            toProtoMsg(message: _133.VersionParams): _133.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _133.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.HashedParams;
            fromPartial(object: Partial<_133.HashedParams>): _133.HashedParams;
            fromAmino(object: _133.HashedParamsAmino): _133.HashedParams;
            toAmino(message: _133.HashedParams): _133.HashedParamsAmino;
            fromAminoMsg(object: _133.HashedParamsAminoMsg): _133.HashedParams;
            fromProtoMsg(message: _133.HashedParamsProtoMsg): _133.HashedParams;
            toProto(message: _133.HashedParams): Uint8Array;
            toProtoMsg(message: _133.HashedParams): _133.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _132.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _132.Evidence;
            fromPartial(object: Partial<_132.Evidence>): _132.Evidence;
            fromAmino(object: _132.EvidenceAmino): _132.Evidence;
            toAmino(message: _132.Evidence): _132.EvidenceAmino;
            fromAminoMsg(object: _132.EvidenceAminoMsg): _132.Evidence;
            fromProtoMsg(message: _132.EvidenceProtoMsg): _132.Evidence;
            toProto(message: _132.Evidence): Uint8Array;
            toProtoMsg(message: _132.Evidence): _132.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _132.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _132.DuplicateVoteEvidence;
            fromPartial(object: Partial<_132.DuplicateVoteEvidence>): _132.DuplicateVoteEvidence;
            fromAmino(object: _132.DuplicateVoteEvidenceAmino): _132.DuplicateVoteEvidence;
            toAmino(message: _132.DuplicateVoteEvidence): _132.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _132.DuplicateVoteEvidenceAminoMsg): _132.DuplicateVoteEvidence;
            fromProtoMsg(message: _132.DuplicateVoteEvidenceProtoMsg): _132.DuplicateVoteEvidence;
            toProto(message: _132.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _132.DuplicateVoteEvidence): _132.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _132.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _132.LightClientAttackEvidence;
            fromPartial(object: Partial<_132.LightClientAttackEvidence>): _132.LightClientAttackEvidence;
            fromAmino(object: _132.LightClientAttackEvidenceAmino): _132.LightClientAttackEvidence;
            toAmino(message: _132.LightClientAttackEvidence): _132.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _132.LightClientAttackEvidenceAminoMsg): _132.LightClientAttackEvidence;
            fromProtoMsg(message: _132.LightClientAttackEvidenceProtoMsg): _132.LightClientAttackEvidence;
            toProto(message: _132.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _132.LightClientAttackEvidence): _132.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _132.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _132.EvidenceList;
            fromPartial(object: Partial<_132.EvidenceList>): _132.EvidenceList;
            fromAmino(object: _132.EvidenceListAmino): _132.EvidenceList;
            toAmino(message: _132.EvidenceList): _132.EvidenceListAmino;
            fromAminoMsg(object: _132.EvidenceListAminoMsg): _132.EvidenceList;
            fromProtoMsg(message: _132.EvidenceListProtoMsg): _132.EvidenceList;
            toProto(message: _132.EvidenceList): Uint8Array;
            toProtoMsg(message: _132.EvidenceList): _132.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _131.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _131.Block;
            fromPartial(object: Partial<_131.Block>): _131.Block;
            fromAmino(object: _131.BlockAmino): _131.Block;
            toAmino(message: _131.Block): _131.BlockAmino;
            fromAminoMsg(object: _131.BlockAminoMsg): _131.Block;
            fromProtoMsg(message: _131.BlockProtoMsg): _131.Block;
            toProto(message: _131.Block): Uint8Array;
            toProtoMsg(message: _131.Block): _131.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _136.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _136.App;
            fromPartial(object: Partial<_136.App>): _136.App;
            fromAmino(object: _136.AppAmino): _136.App;
            toAmino(message: _136.App): _136.AppAmino;
            fromAminoMsg(object: _136.AppAminoMsg): _136.App;
            fromProtoMsg(message: _136.AppProtoMsg): _136.App;
            toProto(message: _136.App): Uint8Array;
            toProtoMsg(message: _136.App): _136.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _136.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _136.Consensus;
            fromPartial(object: Partial<_136.Consensus>): _136.Consensus;
            fromAmino(object: _136.ConsensusAmino): _136.Consensus;
            toAmino(message: _136.Consensus): _136.ConsensusAmino;
            fromAminoMsg(object: _136.ConsensusAminoMsg): _136.Consensus;
            fromProtoMsg(message: _136.ConsensusProtoMsg): _136.Consensus;
            toProto(message: _136.Consensus): Uint8Array;
            toProtoMsg(message: _136.Consensus): _136.ConsensusProtoMsg;
        };
    };
}
