import * as _83 from "./api/http";
import * as _84 from "./api/httpbody";
import * as _85 from "./protobuf/any";
import * as _86 from "./protobuf/duration";
import * as _87 from "./protobuf/timestamp";
import * as _88 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        HttpBody: {
            typeUrl: string;
            encode(message: _84.HttpBody, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.HttpBody;
            fromPartial(object: Partial<_84.HttpBody>): _84.HttpBody;
            fromAmino(object: _84.HttpBodyAmino): _84.HttpBody;
            toAmino(message: _84.HttpBody): _84.HttpBodyAmino;
            fromAminoMsg(object: _84.HttpBodyAminoMsg): _84.HttpBody;
            fromProtoMsg(message: _84.HttpBodyProtoMsg): _84.HttpBody;
            toProto(message: _84.HttpBody): Uint8Array;
            toProtoMsg(message: _84.HttpBody): _84.HttpBodyProtoMsg;
        };
        Http: {
            typeUrl: string;
            encode(message: _83.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _83.Http;
            fromPartial(object: Partial<_83.Http>): _83.Http;
            fromAmino(object: _83.HttpAmino): _83.Http;
            toAmino(message: _83.Http): _83.HttpAmino;
            fromAminoMsg(object: _83.HttpAminoMsg): _83.Http;
            fromProtoMsg(message: _83.HttpProtoMsg): _83.Http;
            toProto(message: _83.Http): Uint8Array;
            toProtoMsg(message: _83.Http): _83.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _83.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _83.HttpRule;
            fromPartial(object: Partial<_83.HttpRule>): _83.HttpRule;
            fromAmino(object: _83.HttpRuleAmino): _83.HttpRule;
            toAmino(message: _83.HttpRule): _83.HttpRuleAmino;
            fromAminoMsg(object: _83.HttpRuleAminoMsg): _83.HttpRule;
            fromProtoMsg(message: _83.HttpRuleProtoMsg): _83.HttpRule;
            toProto(message: _83.HttpRule): Uint8Array;
            toProtoMsg(message: _83.HttpRule): _83.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _83.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _83.CustomHttpPattern;
            fromPartial(object: Partial<_83.CustomHttpPattern>): _83.CustomHttpPattern;
            fromAmino(object: _83.CustomHttpPatternAmino): _83.CustomHttpPattern;
            toAmino(message: _83.CustomHttpPattern): _83.CustomHttpPatternAmino;
            fromAminoMsg(object: _83.CustomHttpPatternAminoMsg): _83.CustomHttpPattern;
            fromProtoMsg(message: _83.CustomHttpPatternProtoMsg): _83.CustomHttpPattern;
            toProto(message: _83.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _83.CustomHttpPattern): _83.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _88.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _88.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _88.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _88.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _88.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _88.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _88.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _88.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _88.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _88.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _88.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _88.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _88.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _88.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _88.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _88.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _88.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _88.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _88.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _88.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _88.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _88.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _88.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _88.FieldOptions_CType;
        FieldOptions_JSType: typeof _88.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _88.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _88.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _88.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _88.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _88.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _88.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.FileDescriptorSet;
            fromPartial(object: Partial<_88.FileDescriptorSet>): _88.FileDescriptorSet;
            fromAmino(object: _88.FileDescriptorSetAmino): _88.FileDescriptorSet;
            toAmino(message: _88.FileDescriptorSet): _88.FileDescriptorSetAmino;
            fromAminoMsg(object: _88.FileDescriptorSetAminoMsg): _88.FileDescriptorSet;
            fromProtoMsg(message: _88.FileDescriptorSetProtoMsg): _88.FileDescriptorSet;
            toProto(message: _88.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _88.FileDescriptorSet): _88.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _88.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.FileDescriptorProto;
            fromPartial(object: Partial<_88.FileDescriptorProto>): _88.FileDescriptorProto;
            fromAmino(object: _88.FileDescriptorProtoAmino): _88.FileDescriptorProto;
            toAmino(message: _88.FileDescriptorProto): _88.FileDescriptorProtoAmino;
            fromAminoMsg(object: _88.FileDescriptorProtoAminoMsg): _88.FileDescriptorProto;
            fromProtoMsg(message: _88.FileDescriptorProtoProtoMsg): _88.FileDescriptorProto;
            toProto(message: _88.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.FileDescriptorProto): _88.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _88.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.DescriptorProto;
            fromPartial(object: Partial<_88.DescriptorProto>): _88.DescriptorProto;
            fromAmino(object: _88.DescriptorProtoAmino): _88.DescriptorProto;
            toAmino(message: _88.DescriptorProto): _88.DescriptorProtoAmino;
            fromAminoMsg(object: _88.DescriptorProtoAminoMsg): _88.DescriptorProto;
            fromProtoMsg(message: _88.DescriptorProtoProtoMsg): _88.DescriptorProto;
            toProto(message: _88.DescriptorProto): Uint8Array;
            toProtoMsg(message: _88.DescriptorProto): _88.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _88.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_88.DescriptorProto_ExtensionRange>): _88.DescriptorProto_ExtensionRange;
            fromAmino(object: _88.DescriptorProto_ExtensionRangeAmino): _88.DescriptorProto_ExtensionRange;
            toAmino(message: _88.DescriptorProto_ExtensionRange): _88.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _88.DescriptorProto_ExtensionRangeAminoMsg): _88.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _88.DescriptorProto_ExtensionRangeProtoMsg): _88.DescriptorProto_ExtensionRange;
            toProto(message: _88.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _88.DescriptorProto_ExtensionRange): _88.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _88.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_88.DescriptorProto_ReservedRange>): _88.DescriptorProto_ReservedRange;
            fromAmino(object: _88.DescriptorProto_ReservedRangeAmino): _88.DescriptorProto_ReservedRange;
            toAmino(message: _88.DescriptorProto_ReservedRange): _88.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _88.DescriptorProto_ReservedRangeAminoMsg): _88.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _88.DescriptorProto_ReservedRangeProtoMsg): _88.DescriptorProto_ReservedRange;
            toProto(message: _88.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _88.DescriptorProto_ReservedRange): _88.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _88.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.ExtensionRangeOptions;
            fromPartial(object: Partial<_88.ExtensionRangeOptions>): _88.ExtensionRangeOptions;
            fromAmino(object: _88.ExtensionRangeOptionsAmino): _88.ExtensionRangeOptions;
            toAmino(message: _88.ExtensionRangeOptions): _88.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _88.ExtensionRangeOptionsAminoMsg): _88.ExtensionRangeOptions;
            fromProtoMsg(message: _88.ExtensionRangeOptionsProtoMsg): _88.ExtensionRangeOptions;
            toProto(message: _88.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _88.ExtensionRangeOptions): _88.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _88.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.FieldDescriptorProto;
            fromPartial(object: Partial<_88.FieldDescriptorProto>): _88.FieldDescriptorProto;
            fromAmino(object: _88.FieldDescriptorProtoAmino): _88.FieldDescriptorProto;
            toAmino(message: _88.FieldDescriptorProto): _88.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _88.FieldDescriptorProtoAminoMsg): _88.FieldDescriptorProto;
            fromProtoMsg(message: _88.FieldDescriptorProtoProtoMsg): _88.FieldDescriptorProto;
            toProto(message: _88.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.FieldDescriptorProto): _88.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _88.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.OneofDescriptorProto;
            fromPartial(object: Partial<_88.OneofDescriptorProto>): _88.OneofDescriptorProto;
            fromAmino(object: _88.OneofDescriptorProtoAmino): _88.OneofDescriptorProto;
            toAmino(message: _88.OneofDescriptorProto): _88.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _88.OneofDescriptorProtoAminoMsg): _88.OneofDescriptorProto;
            fromProtoMsg(message: _88.OneofDescriptorProtoProtoMsg): _88.OneofDescriptorProto;
            toProto(message: _88.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.OneofDescriptorProto): _88.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _88.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.EnumDescriptorProto;
            fromPartial(object: Partial<_88.EnumDescriptorProto>): _88.EnumDescriptorProto;
            fromAmino(object: _88.EnumDescriptorProtoAmino): _88.EnumDescriptorProto;
            toAmino(message: _88.EnumDescriptorProto): _88.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _88.EnumDescriptorProtoAminoMsg): _88.EnumDescriptorProto;
            fromProtoMsg(message: _88.EnumDescriptorProtoProtoMsg): _88.EnumDescriptorProto;
            toProto(message: _88.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.EnumDescriptorProto): _88.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _88.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_88.EnumDescriptorProto_EnumReservedRange>): _88.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _88.EnumDescriptorProto_EnumReservedRangeAmino): _88.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _88.EnumDescriptorProto_EnumReservedRange): _88.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _88.EnumDescriptorProto_EnumReservedRangeAminoMsg): _88.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _88.EnumDescriptorProto_EnumReservedRangeProtoMsg): _88.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _88.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _88.EnumDescriptorProto_EnumReservedRange): _88.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _88.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.EnumValueDescriptorProto;
            fromPartial(object: Partial<_88.EnumValueDescriptorProto>): _88.EnumValueDescriptorProto;
            fromAmino(object: _88.EnumValueDescriptorProtoAmino): _88.EnumValueDescriptorProto;
            toAmino(message: _88.EnumValueDescriptorProto): _88.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _88.EnumValueDescriptorProtoAminoMsg): _88.EnumValueDescriptorProto;
            fromProtoMsg(message: _88.EnumValueDescriptorProtoProtoMsg): _88.EnumValueDescriptorProto;
            toProto(message: _88.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.EnumValueDescriptorProto): _88.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _88.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.ServiceDescriptorProto;
            fromPartial(object: Partial<_88.ServiceDescriptorProto>): _88.ServiceDescriptorProto;
            fromAmino(object: _88.ServiceDescriptorProtoAmino): _88.ServiceDescriptorProto;
            toAmino(message: _88.ServiceDescriptorProto): _88.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _88.ServiceDescriptorProtoAminoMsg): _88.ServiceDescriptorProto;
            fromProtoMsg(message: _88.ServiceDescriptorProtoProtoMsg): _88.ServiceDescriptorProto;
            toProto(message: _88.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.ServiceDescriptorProto): _88.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _88.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.MethodDescriptorProto;
            fromPartial(object: Partial<_88.MethodDescriptorProto>): _88.MethodDescriptorProto;
            fromAmino(object: _88.MethodDescriptorProtoAmino): _88.MethodDescriptorProto;
            toAmino(message: _88.MethodDescriptorProto): _88.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _88.MethodDescriptorProtoAminoMsg): _88.MethodDescriptorProto;
            fromProtoMsg(message: _88.MethodDescriptorProtoProtoMsg): _88.MethodDescriptorProto;
            toProto(message: _88.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.MethodDescriptorProto): _88.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _88.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.FileOptions;
            fromPartial(object: Partial<_88.FileOptions>): _88.FileOptions;
            fromAmino(object: _88.FileOptionsAmino): _88.FileOptions;
            toAmino(message: _88.FileOptions): _88.FileOptionsAmino;
            fromAminoMsg(object: _88.FileOptionsAminoMsg): _88.FileOptions;
            fromProtoMsg(message: _88.FileOptionsProtoMsg): _88.FileOptions;
            toProto(message: _88.FileOptions): Uint8Array;
            toProtoMsg(message: _88.FileOptions): _88.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _88.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.MessageOptions;
            fromPartial(object: Partial<_88.MessageOptions>): _88.MessageOptions;
            fromAmino(object: _88.MessageOptionsAmino): _88.MessageOptions;
            toAmino(message: _88.MessageOptions): _88.MessageOptionsAmino;
            fromAminoMsg(object: _88.MessageOptionsAminoMsg): _88.MessageOptions;
            fromProtoMsg(message: _88.MessageOptionsProtoMsg): _88.MessageOptions;
            toProto(message: _88.MessageOptions): Uint8Array;
            toProtoMsg(message: _88.MessageOptions): _88.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _88.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.FieldOptions;
            fromPartial(object: Partial<_88.FieldOptions>): _88.FieldOptions;
            fromAmino(object: _88.FieldOptionsAmino): _88.FieldOptions;
            toAmino(message: _88.FieldOptions): _88.FieldOptionsAmino;
            fromAminoMsg(object: _88.FieldOptionsAminoMsg): _88.FieldOptions;
            fromProtoMsg(message: _88.FieldOptionsProtoMsg): _88.FieldOptions;
            toProto(message: _88.FieldOptions): Uint8Array;
            toProtoMsg(message: _88.FieldOptions): _88.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _88.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.OneofOptions;
            fromPartial(object: Partial<_88.OneofOptions>): _88.OneofOptions;
            fromAmino(object: _88.OneofOptionsAmino): _88.OneofOptions;
            toAmino(message: _88.OneofOptions): _88.OneofOptionsAmino;
            fromAminoMsg(object: _88.OneofOptionsAminoMsg): _88.OneofOptions;
            fromProtoMsg(message: _88.OneofOptionsProtoMsg): _88.OneofOptions;
            toProto(message: _88.OneofOptions): Uint8Array;
            toProtoMsg(message: _88.OneofOptions): _88.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _88.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.EnumOptions;
            fromPartial(object: Partial<_88.EnumOptions>): _88.EnumOptions;
            fromAmino(object: _88.EnumOptionsAmino): _88.EnumOptions;
            toAmino(message: _88.EnumOptions): _88.EnumOptionsAmino;
            fromAminoMsg(object: _88.EnumOptionsAminoMsg): _88.EnumOptions;
            fromProtoMsg(message: _88.EnumOptionsProtoMsg): _88.EnumOptions;
            toProto(message: _88.EnumOptions): Uint8Array;
            toProtoMsg(message: _88.EnumOptions): _88.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _88.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.EnumValueOptions;
            fromPartial(object: Partial<_88.EnumValueOptions>): _88.EnumValueOptions;
            fromAmino(object: _88.EnumValueOptionsAmino): _88.EnumValueOptions;
            toAmino(message: _88.EnumValueOptions): _88.EnumValueOptionsAmino;
            fromAminoMsg(object: _88.EnumValueOptionsAminoMsg): _88.EnumValueOptions;
            fromProtoMsg(message: _88.EnumValueOptionsProtoMsg): _88.EnumValueOptions;
            toProto(message: _88.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _88.EnumValueOptions): _88.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _88.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.ServiceOptions;
            fromPartial(object: Partial<_88.ServiceOptions>): _88.ServiceOptions;
            fromAmino(object: _88.ServiceOptionsAmino): _88.ServiceOptions;
            toAmino(message: _88.ServiceOptions): _88.ServiceOptionsAmino;
            fromAminoMsg(object: _88.ServiceOptionsAminoMsg): _88.ServiceOptions;
            fromProtoMsg(message: _88.ServiceOptionsProtoMsg): _88.ServiceOptions;
            toProto(message: _88.ServiceOptions): Uint8Array;
            toProtoMsg(message: _88.ServiceOptions): _88.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _88.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.MethodOptions;
            fromPartial(object: Partial<_88.MethodOptions>): _88.MethodOptions;
            fromAmino(object: _88.MethodOptionsAmino): _88.MethodOptions;
            toAmino(message: _88.MethodOptions): _88.MethodOptionsAmino;
            fromAminoMsg(object: _88.MethodOptionsAminoMsg): _88.MethodOptions;
            fromProtoMsg(message: _88.MethodOptionsProtoMsg): _88.MethodOptions;
            toProto(message: _88.MethodOptions): Uint8Array;
            toProtoMsg(message: _88.MethodOptions): _88.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _88.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.UninterpretedOption;
            fromPartial(object: Partial<_88.UninterpretedOption>): _88.UninterpretedOption;
            fromAmino(object: _88.UninterpretedOptionAmino): _88.UninterpretedOption;
            toAmino(message: _88.UninterpretedOption): _88.UninterpretedOptionAmino;
            fromAminoMsg(object: _88.UninterpretedOptionAminoMsg): _88.UninterpretedOption;
            fromProtoMsg(message: _88.UninterpretedOptionProtoMsg): _88.UninterpretedOption;
            toProto(message: _88.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _88.UninterpretedOption): _88.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _88.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_88.UninterpretedOption_NamePart>): _88.UninterpretedOption_NamePart;
            fromAmino(object: _88.UninterpretedOption_NamePartAmino): _88.UninterpretedOption_NamePart;
            toAmino(message: _88.UninterpretedOption_NamePart): _88.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _88.UninterpretedOption_NamePartAminoMsg): _88.UninterpretedOption_NamePart;
            fromProtoMsg(message: _88.UninterpretedOption_NamePartProtoMsg): _88.UninterpretedOption_NamePart;
            toProto(message: _88.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _88.UninterpretedOption_NamePart): _88.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _88.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.SourceCodeInfo;
            fromPartial(object: Partial<_88.SourceCodeInfo>): _88.SourceCodeInfo;
            fromAmino(object: _88.SourceCodeInfoAmino): _88.SourceCodeInfo;
            toAmino(message: _88.SourceCodeInfo): _88.SourceCodeInfoAmino;
            fromAminoMsg(object: _88.SourceCodeInfoAminoMsg): _88.SourceCodeInfo;
            fromProtoMsg(message: _88.SourceCodeInfoProtoMsg): _88.SourceCodeInfo;
            toProto(message: _88.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _88.SourceCodeInfo): _88.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _88.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.SourceCodeInfo_Location;
            fromPartial(object: Partial<_88.SourceCodeInfo_Location>): _88.SourceCodeInfo_Location;
            fromAmino(object: _88.SourceCodeInfo_LocationAmino): _88.SourceCodeInfo_Location;
            toAmino(message: _88.SourceCodeInfo_Location): _88.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _88.SourceCodeInfo_LocationAminoMsg): _88.SourceCodeInfo_Location;
            fromProtoMsg(message: _88.SourceCodeInfo_LocationProtoMsg): _88.SourceCodeInfo_Location;
            toProto(message: _88.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _88.SourceCodeInfo_Location): _88.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _88.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.GeneratedCodeInfo;
            fromPartial(object: Partial<_88.GeneratedCodeInfo>): _88.GeneratedCodeInfo;
            fromAmino(object: _88.GeneratedCodeInfoAmino): _88.GeneratedCodeInfo;
            toAmino(message: _88.GeneratedCodeInfo): _88.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _88.GeneratedCodeInfoAminoMsg): _88.GeneratedCodeInfo;
            fromProtoMsg(message: _88.GeneratedCodeInfoProtoMsg): _88.GeneratedCodeInfo;
            toProto(message: _88.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _88.GeneratedCodeInfo): _88.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _88.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_88.GeneratedCodeInfo_Annotation>): _88.GeneratedCodeInfo_Annotation;
            fromAmino(object: _88.GeneratedCodeInfo_AnnotationAmino): _88.GeneratedCodeInfo_Annotation;
            toAmino(message: _88.GeneratedCodeInfo_Annotation): _88.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _88.GeneratedCodeInfo_AnnotationAminoMsg): _88.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _88.GeneratedCodeInfo_AnnotationProtoMsg): _88.GeneratedCodeInfo_Annotation;
            toProto(message: _88.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _88.GeneratedCodeInfo_Annotation): _88.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _87.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _87.Timestamp;
            fromPartial(object: Partial<_87.Timestamp>): _87.Timestamp;
            fromAmino(object: string): _87.Timestamp;
            toAmino(message: _87.Timestamp): string;
            fromAminoMsg(object: _87.TimestampAminoMsg): _87.Timestamp;
            fromProtoMsg(message: _87.TimestampProtoMsg): _87.Timestamp;
            toProto(message: _87.Timestamp): Uint8Array;
            toProtoMsg(message: _87.Timestamp): _87.TimestampProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _86.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _86.Duration;
            fromPartial(object: Partial<_86.Duration>): _86.Duration;
            fromAmino(object: string): _86.Duration;
            toAmino(message: _86.Duration): string;
            fromAminoMsg(object: _86.DurationAminoMsg): _86.Duration;
            fromProtoMsg(message: _86.DurationProtoMsg): _86.Duration;
            toProto(message: _86.Duration): Uint8Array;
            toProtoMsg(message: _86.Duration): _86.DurationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _85.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.Any;
            fromPartial(object: Partial<_85.Any>): _85.Any;
            fromAmino(object: _85.AnyAmino): _85.Any;
            toAmino(message: _85.Any): _85.AnyAmino;
            fromAminoMsg(object: _85.AnyAminoMsg): _85.Any;
            fromProtoMsg(message: _85.AnyProtoMsg): _85.Any;
            toProto(message: _85.Any): Uint8Array;
            toProtoMsg(message: _85.Any): _85.AnyProtoMsg;
        };
    };
}
