import * as _161 from "./api/http";
import * as _162 from "./api/httpbody";
import * as _163 from "./protobuf/any";
import * as _164 from "./protobuf/duration";
import * as _165 from "./protobuf/timestamp";
import * as _166 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        HttpBody: {
            typeUrl: string;
            encode(message: _162.HttpBody, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _162.HttpBody;
            fromPartial(object: Partial<_162.HttpBody>): _162.HttpBody;
            fromAmino(object: _162.HttpBodyAmino): _162.HttpBody;
            toAmino(message: _162.HttpBody): _162.HttpBodyAmino;
            fromAminoMsg(object: _162.HttpBodyAminoMsg): _162.HttpBody;
            fromProtoMsg(message: _162.HttpBodyProtoMsg): _162.HttpBody;
            toProto(message: _162.HttpBody): Uint8Array;
            toProtoMsg(message: _162.HttpBody): _162.HttpBodyProtoMsg;
        };
        Http: {
            typeUrl: string;
            encode(message: _161.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.Http;
            fromPartial(object: Partial<_161.Http>): _161.Http;
            fromAmino(object: _161.HttpAmino): _161.Http;
            toAmino(message: _161.Http): _161.HttpAmino;
            fromAminoMsg(object: _161.HttpAminoMsg): _161.Http;
            fromProtoMsg(message: _161.HttpProtoMsg): _161.Http;
            toProto(message: _161.Http): Uint8Array;
            toProtoMsg(message: _161.Http): _161.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _161.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.HttpRule;
            fromPartial(object: Partial<_161.HttpRule>): _161.HttpRule;
            fromAmino(object: _161.HttpRuleAmino): _161.HttpRule;
            toAmino(message: _161.HttpRule): _161.HttpRuleAmino;
            fromAminoMsg(object: _161.HttpRuleAminoMsg): _161.HttpRule;
            fromProtoMsg(message: _161.HttpRuleProtoMsg): _161.HttpRule;
            toProto(message: _161.HttpRule): Uint8Array;
            toProtoMsg(message: _161.HttpRule): _161.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _161.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.CustomHttpPattern;
            fromPartial(object: Partial<_161.CustomHttpPattern>): _161.CustomHttpPattern;
            fromAmino(object: _161.CustomHttpPatternAmino): _161.CustomHttpPattern;
            toAmino(message: _161.CustomHttpPattern): _161.CustomHttpPatternAmino;
            fromAminoMsg(object: _161.CustomHttpPatternAminoMsg): _161.CustomHttpPattern;
            fromProtoMsg(message: _161.CustomHttpPatternProtoMsg): _161.CustomHttpPattern;
            toProto(message: _161.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _161.CustomHttpPattern): _161.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _166.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _166.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _166.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _166.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _166.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _166.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _166.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _166.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _166.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _166.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _166.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _166.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _166.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _166.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _166.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _166.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _166.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _166.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _166.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _166.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _166.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _166.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _166.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _166.FieldOptions_CType;
        FieldOptions_JSType: typeof _166.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _166.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _166.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _166.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _166.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _166.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _166.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.FileDescriptorSet;
            fromPartial(object: Partial<_166.FileDescriptorSet>): _166.FileDescriptorSet;
            fromAmino(object: _166.FileDescriptorSetAmino): _166.FileDescriptorSet;
            toAmino(message: _166.FileDescriptorSet): _166.FileDescriptorSetAmino;
            fromAminoMsg(object: _166.FileDescriptorSetAminoMsg): _166.FileDescriptorSet;
            fromProtoMsg(message: _166.FileDescriptorSetProtoMsg): _166.FileDescriptorSet;
            toProto(message: _166.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _166.FileDescriptorSet): _166.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _166.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.FileDescriptorProto;
            fromPartial(object: Partial<_166.FileDescriptorProto>): _166.FileDescriptorProto;
            fromAmino(object: _166.FileDescriptorProtoAmino): _166.FileDescriptorProto;
            toAmino(message: _166.FileDescriptorProto): _166.FileDescriptorProtoAmino;
            fromAminoMsg(object: _166.FileDescriptorProtoAminoMsg): _166.FileDescriptorProto;
            fromProtoMsg(message: _166.FileDescriptorProtoProtoMsg): _166.FileDescriptorProto;
            toProto(message: _166.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _166.FileDescriptorProto): _166.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _166.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.DescriptorProto;
            fromPartial(object: Partial<_166.DescriptorProto>): _166.DescriptorProto;
            fromAmino(object: _166.DescriptorProtoAmino): _166.DescriptorProto;
            toAmino(message: _166.DescriptorProto): _166.DescriptorProtoAmino;
            fromAminoMsg(object: _166.DescriptorProtoAminoMsg): _166.DescriptorProto;
            fromProtoMsg(message: _166.DescriptorProtoProtoMsg): _166.DescriptorProto;
            toProto(message: _166.DescriptorProto): Uint8Array;
            toProtoMsg(message: _166.DescriptorProto): _166.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _166.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_166.DescriptorProto_ExtensionRange>): _166.DescriptorProto_ExtensionRange;
            fromAmino(object: _166.DescriptorProto_ExtensionRangeAmino): _166.DescriptorProto_ExtensionRange;
            toAmino(message: _166.DescriptorProto_ExtensionRange): _166.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _166.DescriptorProto_ExtensionRangeAminoMsg): _166.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _166.DescriptorProto_ExtensionRangeProtoMsg): _166.DescriptorProto_ExtensionRange;
            toProto(message: _166.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _166.DescriptorProto_ExtensionRange): _166.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _166.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_166.DescriptorProto_ReservedRange>): _166.DescriptorProto_ReservedRange;
            fromAmino(object: _166.DescriptorProto_ReservedRangeAmino): _166.DescriptorProto_ReservedRange;
            toAmino(message: _166.DescriptorProto_ReservedRange): _166.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _166.DescriptorProto_ReservedRangeAminoMsg): _166.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _166.DescriptorProto_ReservedRangeProtoMsg): _166.DescriptorProto_ReservedRange;
            toProto(message: _166.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _166.DescriptorProto_ReservedRange): _166.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _166.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.ExtensionRangeOptions;
            fromPartial(object: Partial<_166.ExtensionRangeOptions>): _166.ExtensionRangeOptions;
            fromAmino(object: _166.ExtensionRangeOptionsAmino): _166.ExtensionRangeOptions;
            toAmino(message: _166.ExtensionRangeOptions): _166.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _166.ExtensionRangeOptionsAminoMsg): _166.ExtensionRangeOptions;
            fromProtoMsg(message: _166.ExtensionRangeOptionsProtoMsg): _166.ExtensionRangeOptions;
            toProto(message: _166.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _166.ExtensionRangeOptions): _166.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _166.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.FieldDescriptorProto;
            fromPartial(object: Partial<_166.FieldDescriptorProto>): _166.FieldDescriptorProto;
            fromAmino(object: _166.FieldDescriptorProtoAmino): _166.FieldDescriptorProto;
            toAmino(message: _166.FieldDescriptorProto): _166.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _166.FieldDescriptorProtoAminoMsg): _166.FieldDescriptorProto;
            fromProtoMsg(message: _166.FieldDescriptorProtoProtoMsg): _166.FieldDescriptorProto;
            toProto(message: _166.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _166.FieldDescriptorProto): _166.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _166.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.OneofDescriptorProto;
            fromPartial(object: Partial<_166.OneofDescriptorProto>): _166.OneofDescriptorProto;
            fromAmino(object: _166.OneofDescriptorProtoAmino): _166.OneofDescriptorProto;
            toAmino(message: _166.OneofDescriptorProto): _166.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _166.OneofDescriptorProtoAminoMsg): _166.OneofDescriptorProto;
            fromProtoMsg(message: _166.OneofDescriptorProtoProtoMsg): _166.OneofDescriptorProto;
            toProto(message: _166.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _166.OneofDescriptorProto): _166.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _166.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.EnumDescriptorProto;
            fromPartial(object: Partial<_166.EnumDescriptorProto>): _166.EnumDescriptorProto;
            fromAmino(object: _166.EnumDescriptorProtoAmino): _166.EnumDescriptorProto;
            toAmino(message: _166.EnumDescriptorProto): _166.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _166.EnumDescriptorProtoAminoMsg): _166.EnumDescriptorProto;
            fromProtoMsg(message: _166.EnumDescriptorProtoProtoMsg): _166.EnumDescriptorProto;
            toProto(message: _166.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _166.EnumDescriptorProto): _166.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _166.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_166.EnumDescriptorProto_EnumReservedRange>): _166.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _166.EnumDescriptorProto_EnumReservedRangeAmino): _166.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _166.EnumDescriptorProto_EnumReservedRange): _166.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _166.EnumDescriptorProto_EnumReservedRangeAminoMsg): _166.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _166.EnumDescriptorProto_EnumReservedRangeProtoMsg): _166.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _166.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _166.EnumDescriptorProto_EnumReservedRange): _166.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _166.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.EnumValueDescriptorProto;
            fromPartial(object: Partial<_166.EnumValueDescriptorProto>): _166.EnumValueDescriptorProto;
            fromAmino(object: _166.EnumValueDescriptorProtoAmino): _166.EnumValueDescriptorProto;
            toAmino(message: _166.EnumValueDescriptorProto): _166.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _166.EnumValueDescriptorProtoAminoMsg): _166.EnumValueDescriptorProto;
            fromProtoMsg(message: _166.EnumValueDescriptorProtoProtoMsg): _166.EnumValueDescriptorProto;
            toProto(message: _166.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _166.EnumValueDescriptorProto): _166.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _166.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.ServiceDescriptorProto;
            fromPartial(object: Partial<_166.ServiceDescriptorProto>): _166.ServiceDescriptorProto;
            fromAmino(object: _166.ServiceDescriptorProtoAmino): _166.ServiceDescriptorProto;
            toAmino(message: _166.ServiceDescriptorProto): _166.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _166.ServiceDescriptorProtoAminoMsg): _166.ServiceDescriptorProto;
            fromProtoMsg(message: _166.ServiceDescriptorProtoProtoMsg): _166.ServiceDescriptorProto;
            toProto(message: _166.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _166.ServiceDescriptorProto): _166.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _166.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.MethodDescriptorProto;
            fromPartial(object: Partial<_166.MethodDescriptorProto>): _166.MethodDescriptorProto;
            fromAmino(object: _166.MethodDescriptorProtoAmino): _166.MethodDescriptorProto;
            toAmino(message: _166.MethodDescriptorProto): _166.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _166.MethodDescriptorProtoAminoMsg): _166.MethodDescriptorProto;
            fromProtoMsg(message: _166.MethodDescriptorProtoProtoMsg): _166.MethodDescriptorProto;
            toProto(message: _166.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _166.MethodDescriptorProto): _166.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _166.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.FileOptions;
            fromPartial(object: Partial<_166.FileOptions>): _166.FileOptions;
            fromAmino(object: _166.FileOptionsAmino): _166.FileOptions;
            toAmino(message: _166.FileOptions): _166.FileOptionsAmino;
            fromAminoMsg(object: _166.FileOptionsAminoMsg): _166.FileOptions;
            fromProtoMsg(message: _166.FileOptionsProtoMsg): _166.FileOptions;
            toProto(message: _166.FileOptions): Uint8Array;
            toProtoMsg(message: _166.FileOptions): _166.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _166.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.MessageOptions;
            fromPartial(object: Partial<_166.MessageOptions>): _166.MessageOptions;
            fromAmino(object: _166.MessageOptionsAmino): _166.MessageOptions;
            toAmino(message: _166.MessageOptions): _166.MessageOptionsAmino;
            fromAminoMsg(object: _166.MessageOptionsAminoMsg): _166.MessageOptions;
            fromProtoMsg(message: _166.MessageOptionsProtoMsg): _166.MessageOptions;
            toProto(message: _166.MessageOptions): Uint8Array;
            toProtoMsg(message: _166.MessageOptions): _166.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _166.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.FieldOptions;
            fromPartial(object: Partial<_166.FieldOptions>): _166.FieldOptions;
            fromAmino(object: _166.FieldOptionsAmino): _166.FieldOptions;
            toAmino(message: _166.FieldOptions): _166.FieldOptionsAmino;
            fromAminoMsg(object: _166.FieldOptionsAminoMsg): _166.FieldOptions;
            fromProtoMsg(message: _166.FieldOptionsProtoMsg): _166.FieldOptions;
            toProto(message: _166.FieldOptions): Uint8Array;
            toProtoMsg(message: _166.FieldOptions): _166.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _166.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.OneofOptions;
            fromPartial(object: Partial<_166.OneofOptions>): _166.OneofOptions;
            fromAmino(object: _166.OneofOptionsAmino): _166.OneofOptions;
            toAmino(message: _166.OneofOptions): _166.OneofOptionsAmino;
            fromAminoMsg(object: _166.OneofOptionsAminoMsg): _166.OneofOptions;
            fromProtoMsg(message: _166.OneofOptionsProtoMsg): _166.OneofOptions;
            toProto(message: _166.OneofOptions): Uint8Array;
            toProtoMsg(message: _166.OneofOptions): _166.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _166.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.EnumOptions;
            fromPartial(object: Partial<_166.EnumOptions>): _166.EnumOptions;
            fromAmino(object: _166.EnumOptionsAmino): _166.EnumOptions;
            toAmino(message: _166.EnumOptions): _166.EnumOptionsAmino;
            fromAminoMsg(object: _166.EnumOptionsAminoMsg): _166.EnumOptions;
            fromProtoMsg(message: _166.EnumOptionsProtoMsg): _166.EnumOptions;
            toProto(message: _166.EnumOptions): Uint8Array;
            toProtoMsg(message: _166.EnumOptions): _166.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _166.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.EnumValueOptions;
            fromPartial(object: Partial<_166.EnumValueOptions>): _166.EnumValueOptions;
            fromAmino(object: _166.EnumValueOptionsAmino): _166.EnumValueOptions;
            toAmino(message: _166.EnumValueOptions): _166.EnumValueOptionsAmino;
            fromAminoMsg(object: _166.EnumValueOptionsAminoMsg): _166.EnumValueOptions;
            fromProtoMsg(message: _166.EnumValueOptionsProtoMsg): _166.EnumValueOptions;
            toProto(message: _166.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _166.EnumValueOptions): _166.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _166.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.ServiceOptions;
            fromPartial(object: Partial<_166.ServiceOptions>): _166.ServiceOptions;
            fromAmino(object: _166.ServiceOptionsAmino): _166.ServiceOptions;
            toAmino(message: _166.ServiceOptions): _166.ServiceOptionsAmino;
            fromAminoMsg(object: _166.ServiceOptionsAminoMsg): _166.ServiceOptions;
            fromProtoMsg(message: _166.ServiceOptionsProtoMsg): _166.ServiceOptions;
            toProto(message: _166.ServiceOptions): Uint8Array;
            toProtoMsg(message: _166.ServiceOptions): _166.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _166.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.MethodOptions;
            fromPartial(object: Partial<_166.MethodOptions>): _166.MethodOptions;
            fromAmino(object: _166.MethodOptionsAmino): _166.MethodOptions;
            toAmino(message: _166.MethodOptions): _166.MethodOptionsAmino;
            fromAminoMsg(object: _166.MethodOptionsAminoMsg): _166.MethodOptions;
            fromProtoMsg(message: _166.MethodOptionsProtoMsg): _166.MethodOptions;
            toProto(message: _166.MethodOptions): Uint8Array;
            toProtoMsg(message: _166.MethodOptions): _166.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _166.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.UninterpretedOption;
            fromPartial(object: Partial<_166.UninterpretedOption>): _166.UninterpretedOption;
            fromAmino(object: _166.UninterpretedOptionAmino): _166.UninterpretedOption;
            toAmino(message: _166.UninterpretedOption): _166.UninterpretedOptionAmino;
            fromAminoMsg(object: _166.UninterpretedOptionAminoMsg): _166.UninterpretedOption;
            fromProtoMsg(message: _166.UninterpretedOptionProtoMsg): _166.UninterpretedOption;
            toProto(message: _166.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _166.UninterpretedOption): _166.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _166.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_166.UninterpretedOption_NamePart>): _166.UninterpretedOption_NamePart;
            fromAmino(object: _166.UninterpretedOption_NamePartAmino): _166.UninterpretedOption_NamePart;
            toAmino(message: _166.UninterpretedOption_NamePart): _166.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _166.UninterpretedOption_NamePartAminoMsg): _166.UninterpretedOption_NamePart;
            fromProtoMsg(message: _166.UninterpretedOption_NamePartProtoMsg): _166.UninterpretedOption_NamePart;
            toProto(message: _166.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _166.UninterpretedOption_NamePart): _166.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _166.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.SourceCodeInfo;
            fromPartial(object: Partial<_166.SourceCodeInfo>): _166.SourceCodeInfo;
            fromAmino(object: _166.SourceCodeInfoAmino): _166.SourceCodeInfo;
            toAmino(message: _166.SourceCodeInfo): _166.SourceCodeInfoAmino;
            fromAminoMsg(object: _166.SourceCodeInfoAminoMsg): _166.SourceCodeInfo;
            fromProtoMsg(message: _166.SourceCodeInfoProtoMsg): _166.SourceCodeInfo;
            toProto(message: _166.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _166.SourceCodeInfo): _166.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _166.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.SourceCodeInfo_Location;
            fromPartial(object: Partial<_166.SourceCodeInfo_Location>): _166.SourceCodeInfo_Location;
            fromAmino(object: _166.SourceCodeInfo_LocationAmino): _166.SourceCodeInfo_Location;
            toAmino(message: _166.SourceCodeInfo_Location): _166.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _166.SourceCodeInfo_LocationAminoMsg): _166.SourceCodeInfo_Location;
            fromProtoMsg(message: _166.SourceCodeInfo_LocationProtoMsg): _166.SourceCodeInfo_Location;
            toProto(message: _166.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _166.SourceCodeInfo_Location): _166.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _166.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.GeneratedCodeInfo;
            fromPartial(object: Partial<_166.GeneratedCodeInfo>): _166.GeneratedCodeInfo;
            fromAmino(object: _166.GeneratedCodeInfoAmino): _166.GeneratedCodeInfo;
            toAmino(message: _166.GeneratedCodeInfo): _166.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _166.GeneratedCodeInfoAminoMsg): _166.GeneratedCodeInfo;
            fromProtoMsg(message: _166.GeneratedCodeInfoProtoMsg): _166.GeneratedCodeInfo;
            toProto(message: _166.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _166.GeneratedCodeInfo): _166.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _166.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _166.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_166.GeneratedCodeInfo_Annotation>): _166.GeneratedCodeInfo_Annotation;
            fromAmino(object: _166.GeneratedCodeInfo_AnnotationAmino): _166.GeneratedCodeInfo_Annotation;
            toAmino(message: _166.GeneratedCodeInfo_Annotation): _166.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _166.GeneratedCodeInfo_AnnotationAminoMsg): _166.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _166.GeneratedCodeInfo_AnnotationProtoMsg): _166.GeneratedCodeInfo_Annotation;
            toProto(message: _166.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _166.GeneratedCodeInfo_Annotation): _166.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _165.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _165.Timestamp;
            fromPartial(object: Partial<_165.Timestamp>): _165.Timestamp;
            fromAmino(object: string): _165.Timestamp;
            toAmino(message: _165.Timestamp): string;
            fromAminoMsg(object: _165.TimestampAminoMsg): _165.Timestamp;
            fromProtoMsg(message: _165.TimestampProtoMsg): _165.Timestamp;
            toProto(message: _165.Timestamp): Uint8Array;
            toProtoMsg(message: _165.Timestamp): _165.TimestampProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _164.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _164.Duration;
            fromPartial(object: Partial<_164.Duration>): _164.Duration;
            fromAmino(object: string): _164.Duration;
            toAmino(message: _164.Duration): string;
            fromAminoMsg(object: _164.DurationAminoMsg): _164.Duration;
            fromProtoMsg(message: _164.DurationProtoMsg): _164.Duration;
            toProto(message: _164.Duration): Uint8Array;
            toProtoMsg(message: _164.Duration): _164.DurationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _163.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _163.Any;
            fromPartial(object: Partial<_163.Any>): _163.Any;
            fromAmino(object: _163.AnyAmino): _163.Any;
            toAmino(message: _163.Any): _163.AnyAmino;
            fromAminoMsg(object: _163.AnyAminoMsg): _163.Any;
            fromProtoMsg(message: _163.AnyProtoMsg): _163.Any;
            toProto(message: _163.Any): Uint8Array;
            toProtoMsg(message: _163.Any): _163.AnyProtoMsg;
        };
    };
}
