import * as _104 from "./api/http";
import * as _105 from "./protobuf/descriptor";
import * as _106 from "./protobuf/timestamp";
import * as _107 from "./protobuf/duration";
import * as _108 from "./protobuf/any";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _104.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _104.Http;
            fromPartial(object: Partial<_104.Http>): _104.Http;
            fromAmino(object: _104.HttpAmino): _104.Http;
            toAmino(message: _104.Http): _104.HttpAmino;
            fromAminoMsg(object: _104.HttpAminoMsg): _104.Http;
            fromProtoMsg(message: _104.HttpProtoMsg): _104.Http;
            toProto(message: _104.Http): Uint8Array;
            toProtoMsg(message: _104.Http): _104.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _104.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _104.HttpRule;
            fromPartial(object: Partial<_104.HttpRule>): _104.HttpRule;
            fromAmino(object: _104.HttpRuleAmino): _104.HttpRule;
            toAmino(message: _104.HttpRule): _104.HttpRuleAmino;
            fromAminoMsg(object: _104.HttpRuleAminoMsg): _104.HttpRule;
            fromProtoMsg(message: _104.HttpRuleProtoMsg): _104.HttpRule;
            toProto(message: _104.HttpRule): Uint8Array;
            toProtoMsg(message: _104.HttpRule): _104.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _104.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _104.CustomHttpPattern;
            fromPartial(object: Partial<_104.CustomHttpPattern>): _104.CustomHttpPattern;
            fromAmino(object: _104.CustomHttpPatternAmino): _104.CustomHttpPattern;
            toAmino(message: _104.CustomHttpPattern): _104.CustomHttpPatternAmino;
            fromAminoMsg(object: _104.CustomHttpPatternAminoMsg): _104.CustomHttpPattern;
            fromProtoMsg(message: _104.CustomHttpPatternProtoMsg): _104.CustomHttpPattern;
            toProto(message: _104.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _104.CustomHttpPattern): _104.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Any: {
            typeUrl: string;
            encode(message: _108.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _108.Any;
            fromPartial(object: Partial<_108.Any>): _108.Any;
            fromAmino(object: _108.AnyAmino): _108.Any;
            toAmino(message: _108.Any): _108.AnyAmino;
            fromAminoMsg(object: _108.AnyAminoMsg): _108.Any;
            fromProtoMsg(message: _108.AnyProtoMsg): _108.Any;
            toProto(message: _108.Any): Uint8Array;
            toProtoMsg(message: _108.Any): _108.AnyProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _107.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.Duration;
            fromPartial(object: Partial<_107.Duration>): _107.Duration;
            fromAmino(object: string): _107.Duration;
            toAmino(message: _107.Duration): string;
            fromAminoMsg(object: _107.DurationAminoMsg): _107.Duration;
            fromProtoMsg(message: _107.DurationProtoMsg): _107.Duration;
            toProto(message: _107.Duration): Uint8Array;
            toProtoMsg(message: _107.Duration): _107.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _106.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.Timestamp;
            fromPartial(object: Partial<_106.Timestamp>): _106.Timestamp;
            fromAmino(object: string): _106.Timestamp;
            toAmino(message: _106.Timestamp): string;
            fromAminoMsg(object: _106.TimestampAminoMsg): _106.Timestamp;
            fromProtoMsg(message: _106.TimestampProtoMsg): _106.Timestamp;
            toProto(message: _106.Timestamp): Uint8Array;
            toProtoMsg(message: _106.Timestamp): _106.TimestampProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _105.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _105.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _105.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _105.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _105.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _105.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _105.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _105.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _105.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _105.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _105.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _105.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _105.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _105.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _105.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _105.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _105.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _105.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _105.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _105.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _105.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _105.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _105.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _105.FieldOptions_CType;
        FieldOptions_JSType: typeof _105.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _105.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _105.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _105.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _105.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _105.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _105.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.FileDescriptorSet;
            fromPartial(object: Partial<_105.FileDescriptorSet>): _105.FileDescriptorSet;
            fromAmino(object: _105.FileDescriptorSetAmino): _105.FileDescriptorSet;
            toAmino(message: _105.FileDescriptorSet): _105.FileDescriptorSetAmino;
            fromAminoMsg(object: _105.FileDescriptorSetAminoMsg): _105.FileDescriptorSet;
            fromProtoMsg(message: _105.FileDescriptorSetProtoMsg): _105.FileDescriptorSet;
            toProto(message: _105.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _105.FileDescriptorSet): _105.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _105.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.FileDescriptorProto;
            fromPartial(object: Partial<_105.FileDescriptorProto>): _105.FileDescriptorProto;
            fromAmino(object: _105.FileDescriptorProtoAmino): _105.FileDescriptorProto;
            toAmino(message: _105.FileDescriptorProto): _105.FileDescriptorProtoAmino;
            fromAminoMsg(object: _105.FileDescriptorProtoAminoMsg): _105.FileDescriptorProto;
            fromProtoMsg(message: _105.FileDescriptorProtoProtoMsg): _105.FileDescriptorProto;
            toProto(message: _105.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _105.FileDescriptorProto): _105.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _105.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.DescriptorProto;
            fromPartial(object: Partial<_105.DescriptorProto>): _105.DescriptorProto;
            fromAmino(object: _105.DescriptorProtoAmino): _105.DescriptorProto;
            toAmino(message: _105.DescriptorProto): _105.DescriptorProtoAmino;
            fromAminoMsg(object: _105.DescriptorProtoAminoMsg): _105.DescriptorProto;
            fromProtoMsg(message: _105.DescriptorProtoProtoMsg): _105.DescriptorProto;
            toProto(message: _105.DescriptorProto): Uint8Array;
            toProtoMsg(message: _105.DescriptorProto): _105.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _105.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_105.DescriptorProto_ExtensionRange>): _105.DescriptorProto_ExtensionRange;
            fromAmino(object: _105.DescriptorProto_ExtensionRangeAmino): _105.DescriptorProto_ExtensionRange;
            toAmino(message: _105.DescriptorProto_ExtensionRange): _105.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _105.DescriptorProto_ExtensionRangeAminoMsg): _105.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _105.DescriptorProto_ExtensionRangeProtoMsg): _105.DescriptorProto_ExtensionRange;
            toProto(message: _105.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _105.DescriptorProto_ExtensionRange): _105.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _105.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_105.DescriptorProto_ReservedRange>): _105.DescriptorProto_ReservedRange;
            fromAmino(object: _105.DescriptorProto_ReservedRangeAmino): _105.DescriptorProto_ReservedRange;
            toAmino(message: _105.DescriptorProto_ReservedRange): _105.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _105.DescriptorProto_ReservedRangeAminoMsg): _105.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _105.DescriptorProto_ReservedRangeProtoMsg): _105.DescriptorProto_ReservedRange;
            toProto(message: _105.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _105.DescriptorProto_ReservedRange): _105.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _105.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.ExtensionRangeOptions;
            fromPartial(object: Partial<_105.ExtensionRangeOptions>): _105.ExtensionRangeOptions;
            fromAmino(object: _105.ExtensionRangeOptionsAmino): _105.ExtensionRangeOptions;
            toAmino(message: _105.ExtensionRangeOptions): _105.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _105.ExtensionRangeOptionsAminoMsg): _105.ExtensionRangeOptions;
            fromProtoMsg(message: _105.ExtensionRangeOptionsProtoMsg): _105.ExtensionRangeOptions;
            toProto(message: _105.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _105.ExtensionRangeOptions): _105.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _105.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.FieldDescriptorProto;
            fromPartial(object: Partial<_105.FieldDescriptorProto>): _105.FieldDescriptorProto;
            fromAmino(object: _105.FieldDescriptorProtoAmino): _105.FieldDescriptorProto;
            toAmino(message: _105.FieldDescriptorProto): _105.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _105.FieldDescriptorProtoAminoMsg): _105.FieldDescriptorProto;
            fromProtoMsg(message: _105.FieldDescriptorProtoProtoMsg): _105.FieldDescriptorProto;
            toProto(message: _105.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _105.FieldDescriptorProto): _105.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _105.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.OneofDescriptorProto;
            fromPartial(object: Partial<_105.OneofDescriptorProto>): _105.OneofDescriptorProto;
            fromAmino(object: _105.OneofDescriptorProtoAmino): _105.OneofDescriptorProto;
            toAmino(message: _105.OneofDescriptorProto): _105.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _105.OneofDescriptorProtoAminoMsg): _105.OneofDescriptorProto;
            fromProtoMsg(message: _105.OneofDescriptorProtoProtoMsg): _105.OneofDescriptorProto;
            toProto(message: _105.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _105.OneofDescriptorProto): _105.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _105.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.EnumDescriptorProto;
            fromPartial(object: Partial<_105.EnumDescriptorProto>): _105.EnumDescriptorProto;
            fromAmino(object: _105.EnumDescriptorProtoAmino): _105.EnumDescriptorProto;
            toAmino(message: _105.EnumDescriptorProto): _105.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _105.EnumDescriptorProtoAminoMsg): _105.EnumDescriptorProto;
            fromProtoMsg(message: _105.EnumDescriptorProtoProtoMsg): _105.EnumDescriptorProto;
            toProto(message: _105.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _105.EnumDescriptorProto): _105.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _105.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_105.EnumDescriptorProto_EnumReservedRange>): _105.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _105.EnumDescriptorProto_EnumReservedRangeAmino): _105.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _105.EnumDescriptorProto_EnumReservedRange): _105.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _105.EnumDescriptorProto_EnumReservedRangeAminoMsg): _105.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _105.EnumDescriptorProto_EnumReservedRangeProtoMsg): _105.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _105.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _105.EnumDescriptorProto_EnumReservedRange): _105.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _105.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.EnumValueDescriptorProto;
            fromPartial(object: Partial<_105.EnumValueDescriptorProto>): _105.EnumValueDescriptorProto;
            fromAmino(object: _105.EnumValueDescriptorProtoAmino): _105.EnumValueDescriptorProto;
            toAmino(message: _105.EnumValueDescriptorProto): _105.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _105.EnumValueDescriptorProtoAminoMsg): _105.EnumValueDescriptorProto;
            fromProtoMsg(message: _105.EnumValueDescriptorProtoProtoMsg): _105.EnumValueDescriptorProto;
            toProto(message: _105.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _105.EnumValueDescriptorProto): _105.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _105.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.ServiceDescriptorProto;
            fromPartial(object: Partial<_105.ServiceDescriptorProto>): _105.ServiceDescriptorProto;
            fromAmino(object: _105.ServiceDescriptorProtoAmino): _105.ServiceDescriptorProto;
            toAmino(message: _105.ServiceDescriptorProto): _105.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _105.ServiceDescriptorProtoAminoMsg): _105.ServiceDescriptorProto;
            fromProtoMsg(message: _105.ServiceDescriptorProtoProtoMsg): _105.ServiceDescriptorProto;
            toProto(message: _105.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _105.ServiceDescriptorProto): _105.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _105.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.MethodDescriptorProto;
            fromPartial(object: Partial<_105.MethodDescriptorProto>): _105.MethodDescriptorProto;
            fromAmino(object: _105.MethodDescriptorProtoAmino): _105.MethodDescriptorProto;
            toAmino(message: _105.MethodDescriptorProto): _105.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _105.MethodDescriptorProtoAminoMsg): _105.MethodDescriptorProto;
            fromProtoMsg(message: _105.MethodDescriptorProtoProtoMsg): _105.MethodDescriptorProto;
            toProto(message: _105.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _105.MethodDescriptorProto): _105.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _105.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.FileOptions;
            fromPartial(object: Partial<_105.FileOptions>): _105.FileOptions;
            fromAmino(object: _105.FileOptionsAmino): _105.FileOptions;
            toAmino(message: _105.FileOptions): _105.FileOptionsAmino;
            fromAminoMsg(object: _105.FileOptionsAminoMsg): _105.FileOptions;
            fromProtoMsg(message: _105.FileOptionsProtoMsg): _105.FileOptions;
            toProto(message: _105.FileOptions): Uint8Array;
            toProtoMsg(message: _105.FileOptions): _105.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _105.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.MessageOptions;
            fromPartial(object: Partial<_105.MessageOptions>): _105.MessageOptions;
            fromAmino(object: _105.MessageOptionsAmino): _105.MessageOptions;
            toAmino(message: _105.MessageOptions): _105.MessageOptionsAmino;
            fromAminoMsg(object: _105.MessageOptionsAminoMsg): _105.MessageOptions;
            fromProtoMsg(message: _105.MessageOptionsProtoMsg): _105.MessageOptions;
            toProto(message: _105.MessageOptions): Uint8Array;
            toProtoMsg(message: _105.MessageOptions): _105.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _105.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.FieldOptions;
            fromPartial(object: Partial<_105.FieldOptions>): _105.FieldOptions;
            fromAmino(object: _105.FieldOptionsAmino): _105.FieldOptions;
            toAmino(message: _105.FieldOptions): _105.FieldOptionsAmino;
            fromAminoMsg(object: _105.FieldOptionsAminoMsg): _105.FieldOptions;
            fromProtoMsg(message: _105.FieldOptionsProtoMsg): _105.FieldOptions;
            toProto(message: _105.FieldOptions): Uint8Array;
            toProtoMsg(message: _105.FieldOptions): _105.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _105.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.OneofOptions;
            fromPartial(object: Partial<_105.OneofOptions>): _105.OneofOptions;
            fromAmino(object: _105.OneofOptionsAmino): _105.OneofOptions;
            toAmino(message: _105.OneofOptions): _105.OneofOptionsAmino;
            fromAminoMsg(object: _105.OneofOptionsAminoMsg): _105.OneofOptions;
            fromProtoMsg(message: _105.OneofOptionsProtoMsg): _105.OneofOptions;
            toProto(message: _105.OneofOptions): Uint8Array;
            toProtoMsg(message: _105.OneofOptions): _105.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _105.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.EnumOptions;
            fromPartial(object: Partial<_105.EnumOptions>): _105.EnumOptions;
            fromAmino(object: _105.EnumOptionsAmino): _105.EnumOptions;
            toAmino(message: _105.EnumOptions): _105.EnumOptionsAmino;
            fromAminoMsg(object: _105.EnumOptionsAminoMsg): _105.EnumOptions;
            fromProtoMsg(message: _105.EnumOptionsProtoMsg): _105.EnumOptions;
            toProto(message: _105.EnumOptions): Uint8Array;
            toProtoMsg(message: _105.EnumOptions): _105.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _105.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.EnumValueOptions;
            fromPartial(object: Partial<_105.EnumValueOptions>): _105.EnumValueOptions;
            fromAmino(object: _105.EnumValueOptionsAmino): _105.EnumValueOptions;
            toAmino(message: _105.EnumValueOptions): _105.EnumValueOptionsAmino;
            fromAminoMsg(object: _105.EnumValueOptionsAminoMsg): _105.EnumValueOptions;
            fromProtoMsg(message: _105.EnumValueOptionsProtoMsg): _105.EnumValueOptions;
            toProto(message: _105.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _105.EnumValueOptions): _105.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _105.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.ServiceOptions;
            fromPartial(object: Partial<_105.ServiceOptions>): _105.ServiceOptions;
            fromAmino(object: _105.ServiceOptionsAmino): _105.ServiceOptions;
            toAmino(message: _105.ServiceOptions): _105.ServiceOptionsAmino;
            fromAminoMsg(object: _105.ServiceOptionsAminoMsg): _105.ServiceOptions;
            fromProtoMsg(message: _105.ServiceOptionsProtoMsg): _105.ServiceOptions;
            toProto(message: _105.ServiceOptions): Uint8Array;
            toProtoMsg(message: _105.ServiceOptions): _105.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _105.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.MethodOptions;
            fromPartial(object: Partial<_105.MethodOptions>): _105.MethodOptions;
            fromAmino(object: _105.MethodOptionsAmino): _105.MethodOptions;
            toAmino(message: _105.MethodOptions): _105.MethodOptionsAmino;
            fromAminoMsg(object: _105.MethodOptionsAminoMsg): _105.MethodOptions;
            fromProtoMsg(message: _105.MethodOptionsProtoMsg): _105.MethodOptions;
            toProto(message: _105.MethodOptions): Uint8Array;
            toProtoMsg(message: _105.MethodOptions): _105.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _105.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.UninterpretedOption;
            fromPartial(object: Partial<_105.UninterpretedOption>): _105.UninterpretedOption;
            fromAmino(object: _105.UninterpretedOptionAmino): _105.UninterpretedOption;
            toAmino(message: _105.UninterpretedOption): _105.UninterpretedOptionAmino;
            fromAminoMsg(object: _105.UninterpretedOptionAminoMsg): _105.UninterpretedOption;
            fromProtoMsg(message: _105.UninterpretedOptionProtoMsg): _105.UninterpretedOption;
            toProto(message: _105.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _105.UninterpretedOption): _105.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _105.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_105.UninterpretedOption_NamePart>): _105.UninterpretedOption_NamePart;
            fromAmino(object: _105.UninterpretedOption_NamePartAmino): _105.UninterpretedOption_NamePart;
            toAmino(message: _105.UninterpretedOption_NamePart): _105.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _105.UninterpretedOption_NamePartAminoMsg): _105.UninterpretedOption_NamePart;
            fromProtoMsg(message: _105.UninterpretedOption_NamePartProtoMsg): _105.UninterpretedOption_NamePart;
            toProto(message: _105.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _105.UninterpretedOption_NamePart): _105.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _105.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.SourceCodeInfo;
            fromPartial(object: Partial<_105.SourceCodeInfo>): _105.SourceCodeInfo;
            fromAmino(object: _105.SourceCodeInfoAmino): _105.SourceCodeInfo;
            toAmino(message: _105.SourceCodeInfo): _105.SourceCodeInfoAmino;
            fromAminoMsg(object: _105.SourceCodeInfoAminoMsg): _105.SourceCodeInfo;
            fromProtoMsg(message: _105.SourceCodeInfoProtoMsg): _105.SourceCodeInfo;
            toProto(message: _105.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _105.SourceCodeInfo): _105.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _105.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.SourceCodeInfo_Location;
            fromPartial(object: Partial<_105.SourceCodeInfo_Location>): _105.SourceCodeInfo_Location;
            fromAmino(object: _105.SourceCodeInfo_LocationAmino): _105.SourceCodeInfo_Location;
            toAmino(message: _105.SourceCodeInfo_Location): _105.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _105.SourceCodeInfo_LocationAminoMsg): _105.SourceCodeInfo_Location;
            fromProtoMsg(message: _105.SourceCodeInfo_LocationProtoMsg): _105.SourceCodeInfo_Location;
            toProto(message: _105.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _105.SourceCodeInfo_Location): _105.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _105.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.GeneratedCodeInfo;
            fromPartial(object: Partial<_105.GeneratedCodeInfo>): _105.GeneratedCodeInfo;
            fromAmino(object: _105.GeneratedCodeInfoAmino): _105.GeneratedCodeInfo;
            toAmino(message: _105.GeneratedCodeInfo): _105.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _105.GeneratedCodeInfoAminoMsg): _105.GeneratedCodeInfo;
            fromProtoMsg(message: _105.GeneratedCodeInfoProtoMsg): _105.GeneratedCodeInfo;
            toProto(message: _105.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _105.GeneratedCodeInfo): _105.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _105.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_105.GeneratedCodeInfo_Annotation>): _105.GeneratedCodeInfo_Annotation;
            fromAmino(object: _105.GeneratedCodeInfo_AnnotationAmino): _105.GeneratedCodeInfo_Annotation;
            toAmino(message: _105.GeneratedCodeInfo_Annotation): _105.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _105.GeneratedCodeInfo_AnnotationAminoMsg): _105.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _105.GeneratedCodeInfo_AnnotationProtoMsg): _105.GeneratedCodeInfo_Annotation;
            toProto(message: _105.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _105.GeneratedCodeInfo_Annotation): _105.GeneratedCodeInfo_AnnotationProtoMsg;
        };
    };
}
