import * as _120 from "./api/http";
import * as _121 from "./protobuf/timestamp";
import * as _122 from "./protobuf/duration";
import * as _123 from "./protobuf/any";
import * as _124 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _120.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _120.Http;
            fromPartial(object: Partial<_120.Http>): _120.Http;
            fromAmino(object: _120.HttpAmino): _120.Http;
            toAmino(message: _120.Http): _120.HttpAmino;
            fromAminoMsg(object: _120.HttpAminoMsg): _120.Http;
            fromProtoMsg(message: _120.HttpProtoMsg): _120.Http;
            toProto(message: _120.Http): Uint8Array;
            toProtoMsg(message: _120.Http): _120.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _120.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _120.HttpRule;
            fromPartial(object: Partial<_120.HttpRule>): _120.HttpRule;
            fromAmino(object: _120.HttpRuleAmino): _120.HttpRule;
            toAmino(message: _120.HttpRule): _120.HttpRuleAmino;
            fromAminoMsg(object: _120.HttpRuleAminoMsg): _120.HttpRule;
            fromProtoMsg(message: _120.HttpRuleProtoMsg): _120.HttpRule;
            toProto(message: _120.HttpRule): Uint8Array;
            toProtoMsg(message: _120.HttpRule): _120.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _120.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _120.CustomHttpPattern;
            fromPartial(object: Partial<_120.CustomHttpPattern>): _120.CustomHttpPattern;
            fromAmino(object: _120.CustomHttpPatternAmino): _120.CustomHttpPattern;
            toAmino(message: _120.CustomHttpPattern): _120.CustomHttpPatternAmino;
            fromAminoMsg(object: _120.CustomHttpPatternAminoMsg): _120.CustomHttpPattern;
            fromProtoMsg(message: _120.CustomHttpPatternProtoMsg): _120.CustomHttpPattern;
            toProto(message: _120.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _120.CustomHttpPattern): _120.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _124.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _124.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _124.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _124.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _124.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _124.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _124.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _124.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _124.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _124.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _124.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _124.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _124.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _124.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _124.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _124.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _124.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _124.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _124.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _124.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _124.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _124.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _124.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _124.FieldOptions_CType;
        FieldOptions_JSType: typeof _124.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _124.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _124.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _124.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _124.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _124.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _124.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.FileDescriptorSet;
            fromPartial(object: Partial<_124.FileDescriptorSet>): _124.FileDescriptorSet;
            fromAmino(object: _124.FileDescriptorSetAmino): _124.FileDescriptorSet;
            toAmino(message: _124.FileDescriptorSet): _124.FileDescriptorSetAmino;
            fromAminoMsg(object: _124.FileDescriptorSetAminoMsg): _124.FileDescriptorSet;
            fromProtoMsg(message: _124.FileDescriptorSetProtoMsg): _124.FileDescriptorSet;
            toProto(message: _124.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _124.FileDescriptorSet): _124.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _124.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.FileDescriptorProto;
            fromPartial(object: Partial<_124.FileDescriptorProto>): _124.FileDescriptorProto;
            fromAmino(object: _124.FileDescriptorProtoAmino): _124.FileDescriptorProto;
            toAmino(message: _124.FileDescriptorProto): _124.FileDescriptorProtoAmino;
            fromAminoMsg(object: _124.FileDescriptorProtoAminoMsg): _124.FileDescriptorProto;
            fromProtoMsg(message: _124.FileDescriptorProtoProtoMsg): _124.FileDescriptorProto;
            toProto(message: _124.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _124.FileDescriptorProto): _124.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _124.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.DescriptorProto;
            fromPartial(object: Partial<_124.DescriptorProto>): _124.DescriptorProto;
            fromAmino(object: _124.DescriptorProtoAmino): _124.DescriptorProto;
            toAmino(message: _124.DescriptorProto): _124.DescriptorProtoAmino;
            fromAminoMsg(object: _124.DescriptorProtoAminoMsg): _124.DescriptorProto;
            fromProtoMsg(message: _124.DescriptorProtoProtoMsg): _124.DescriptorProto;
            toProto(message: _124.DescriptorProto): Uint8Array;
            toProtoMsg(message: _124.DescriptorProto): _124.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _124.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_124.DescriptorProto_ExtensionRange>): _124.DescriptorProto_ExtensionRange;
            fromAmino(object: _124.DescriptorProto_ExtensionRangeAmino): _124.DescriptorProto_ExtensionRange;
            toAmino(message: _124.DescriptorProto_ExtensionRange): _124.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _124.DescriptorProto_ExtensionRangeAminoMsg): _124.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _124.DescriptorProto_ExtensionRangeProtoMsg): _124.DescriptorProto_ExtensionRange;
            toProto(message: _124.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _124.DescriptorProto_ExtensionRange): _124.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _124.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_124.DescriptorProto_ReservedRange>): _124.DescriptorProto_ReservedRange;
            fromAmino(object: _124.DescriptorProto_ReservedRangeAmino): _124.DescriptorProto_ReservedRange;
            toAmino(message: _124.DescriptorProto_ReservedRange): _124.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _124.DescriptorProto_ReservedRangeAminoMsg): _124.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _124.DescriptorProto_ReservedRangeProtoMsg): _124.DescriptorProto_ReservedRange;
            toProto(message: _124.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _124.DescriptorProto_ReservedRange): _124.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _124.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.ExtensionRangeOptions;
            fromPartial(object: Partial<_124.ExtensionRangeOptions>): _124.ExtensionRangeOptions;
            fromAmino(object: _124.ExtensionRangeOptionsAmino): _124.ExtensionRangeOptions;
            toAmino(message: _124.ExtensionRangeOptions): _124.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _124.ExtensionRangeOptionsAminoMsg): _124.ExtensionRangeOptions;
            fromProtoMsg(message: _124.ExtensionRangeOptionsProtoMsg): _124.ExtensionRangeOptions;
            toProto(message: _124.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _124.ExtensionRangeOptions): _124.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _124.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.FieldDescriptorProto;
            fromPartial(object: Partial<_124.FieldDescriptorProto>): _124.FieldDescriptorProto;
            fromAmino(object: _124.FieldDescriptorProtoAmino): _124.FieldDescriptorProto;
            toAmino(message: _124.FieldDescriptorProto): _124.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _124.FieldDescriptorProtoAminoMsg): _124.FieldDescriptorProto;
            fromProtoMsg(message: _124.FieldDescriptorProtoProtoMsg): _124.FieldDescriptorProto;
            toProto(message: _124.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _124.FieldDescriptorProto): _124.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _124.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.OneofDescriptorProto;
            fromPartial(object: Partial<_124.OneofDescriptorProto>): _124.OneofDescriptorProto;
            fromAmino(object: _124.OneofDescriptorProtoAmino): _124.OneofDescriptorProto;
            toAmino(message: _124.OneofDescriptorProto): _124.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _124.OneofDescriptorProtoAminoMsg): _124.OneofDescriptorProto;
            fromProtoMsg(message: _124.OneofDescriptorProtoProtoMsg): _124.OneofDescriptorProto;
            toProto(message: _124.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _124.OneofDescriptorProto): _124.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _124.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.EnumDescriptorProto;
            fromPartial(object: Partial<_124.EnumDescriptorProto>): _124.EnumDescriptorProto;
            fromAmino(object: _124.EnumDescriptorProtoAmino): _124.EnumDescriptorProto;
            toAmino(message: _124.EnumDescriptorProto): _124.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _124.EnumDescriptorProtoAminoMsg): _124.EnumDescriptorProto;
            fromProtoMsg(message: _124.EnumDescriptorProtoProtoMsg): _124.EnumDescriptorProto;
            toProto(message: _124.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _124.EnumDescriptorProto): _124.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _124.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_124.EnumDescriptorProto_EnumReservedRange>): _124.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _124.EnumDescriptorProto_EnumReservedRangeAmino): _124.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _124.EnumDescriptorProto_EnumReservedRange): _124.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _124.EnumDescriptorProto_EnumReservedRangeAminoMsg): _124.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _124.EnumDescriptorProto_EnumReservedRangeProtoMsg): _124.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _124.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _124.EnumDescriptorProto_EnumReservedRange): _124.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _124.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.EnumValueDescriptorProto;
            fromPartial(object: Partial<_124.EnumValueDescriptorProto>): _124.EnumValueDescriptorProto;
            fromAmino(object: _124.EnumValueDescriptorProtoAmino): _124.EnumValueDescriptorProto;
            toAmino(message: _124.EnumValueDescriptorProto): _124.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _124.EnumValueDescriptorProtoAminoMsg): _124.EnumValueDescriptorProto;
            fromProtoMsg(message: _124.EnumValueDescriptorProtoProtoMsg): _124.EnumValueDescriptorProto;
            toProto(message: _124.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _124.EnumValueDescriptorProto): _124.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _124.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.ServiceDescriptorProto;
            fromPartial(object: Partial<_124.ServiceDescriptorProto>): _124.ServiceDescriptorProto;
            fromAmino(object: _124.ServiceDescriptorProtoAmino): _124.ServiceDescriptorProto;
            toAmino(message: _124.ServiceDescriptorProto): _124.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _124.ServiceDescriptorProtoAminoMsg): _124.ServiceDescriptorProto;
            fromProtoMsg(message: _124.ServiceDescriptorProtoProtoMsg): _124.ServiceDescriptorProto;
            toProto(message: _124.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _124.ServiceDescriptorProto): _124.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _124.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.MethodDescriptorProto;
            fromPartial(object: Partial<_124.MethodDescriptorProto>): _124.MethodDescriptorProto;
            fromAmino(object: _124.MethodDescriptorProtoAmino): _124.MethodDescriptorProto;
            toAmino(message: _124.MethodDescriptorProto): _124.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _124.MethodDescriptorProtoAminoMsg): _124.MethodDescriptorProto;
            fromProtoMsg(message: _124.MethodDescriptorProtoProtoMsg): _124.MethodDescriptorProto;
            toProto(message: _124.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _124.MethodDescriptorProto): _124.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _124.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.FileOptions;
            fromPartial(object: Partial<_124.FileOptions>): _124.FileOptions;
            fromAmino(object: _124.FileOptionsAmino): _124.FileOptions;
            toAmino(message: _124.FileOptions): _124.FileOptionsAmino;
            fromAminoMsg(object: _124.FileOptionsAminoMsg): _124.FileOptions;
            fromProtoMsg(message: _124.FileOptionsProtoMsg): _124.FileOptions;
            toProto(message: _124.FileOptions): Uint8Array;
            toProtoMsg(message: _124.FileOptions): _124.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _124.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.MessageOptions;
            fromPartial(object: Partial<_124.MessageOptions>): _124.MessageOptions;
            fromAmino(object: _124.MessageOptionsAmino): _124.MessageOptions;
            toAmino(message: _124.MessageOptions): _124.MessageOptionsAmino;
            fromAminoMsg(object: _124.MessageOptionsAminoMsg): _124.MessageOptions;
            fromProtoMsg(message: _124.MessageOptionsProtoMsg): _124.MessageOptions;
            toProto(message: _124.MessageOptions): Uint8Array;
            toProtoMsg(message: _124.MessageOptions): _124.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _124.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.FieldOptions;
            fromPartial(object: Partial<_124.FieldOptions>): _124.FieldOptions;
            fromAmino(object: _124.FieldOptionsAmino): _124.FieldOptions;
            toAmino(message: _124.FieldOptions): _124.FieldOptionsAmino;
            fromAminoMsg(object: _124.FieldOptionsAminoMsg): _124.FieldOptions;
            fromProtoMsg(message: _124.FieldOptionsProtoMsg): _124.FieldOptions;
            toProto(message: _124.FieldOptions): Uint8Array;
            toProtoMsg(message: _124.FieldOptions): _124.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _124.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.OneofOptions;
            fromPartial(object: Partial<_124.OneofOptions>): _124.OneofOptions;
            fromAmino(object: _124.OneofOptionsAmino): _124.OneofOptions;
            toAmino(message: _124.OneofOptions): _124.OneofOptionsAmino;
            fromAminoMsg(object: _124.OneofOptionsAminoMsg): _124.OneofOptions;
            fromProtoMsg(message: _124.OneofOptionsProtoMsg): _124.OneofOptions;
            toProto(message: _124.OneofOptions): Uint8Array;
            toProtoMsg(message: _124.OneofOptions): _124.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _124.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.EnumOptions;
            fromPartial(object: Partial<_124.EnumOptions>): _124.EnumOptions;
            fromAmino(object: _124.EnumOptionsAmino): _124.EnumOptions;
            toAmino(message: _124.EnumOptions): _124.EnumOptionsAmino;
            fromAminoMsg(object: _124.EnumOptionsAminoMsg): _124.EnumOptions;
            fromProtoMsg(message: _124.EnumOptionsProtoMsg): _124.EnumOptions;
            toProto(message: _124.EnumOptions): Uint8Array;
            toProtoMsg(message: _124.EnumOptions): _124.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _124.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.EnumValueOptions;
            fromPartial(object: Partial<_124.EnumValueOptions>): _124.EnumValueOptions;
            fromAmino(object: _124.EnumValueOptionsAmino): _124.EnumValueOptions;
            toAmino(message: _124.EnumValueOptions): _124.EnumValueOptionsAmino;
            fromAminoMsg(object: _124.EnumValueOptionsAminoMsg): _124.EnumValueOptions;
            fromProtoMsg(message: _124.EnumValueOptionsProtoMsg): _124.EnumValueOptions;
            toProto(message: _124.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _124.EnumValueOptions): _124.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _124.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.ServiceOptions;
            fromPartial(object: Partial<_124.ServiceOptions>): _124.ServiceOptions;
            fromAmino(object: _124.ServiceOptionsAmino): _124.ServiceOptions;
            toAmino(message: _124.ServiceOptions): _124.ServiceOptionsAmino;
            fromAminoMsg(object: _124.ServiceOptionsAminoMsg): _124.ServiceOptions;
            fromProtoMsg(message: _124.ServiceOptionsProtoMsg): _124.ServiceOptions;
            toProto(message: _124.ServiceOptions): Uint8Array;
            toProtoMsg(message: _124.ServiceOptions): _124.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _124.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.MethodOptions;
            fromPartial(object: Partial<_124.MethodOptions>): _124.MethodOptions;
            fromAmino(object: _124.MethodOptionsAmino): _124.MethodOptions;
            toAmino(message: _124.MethodOptions): _124.MethodOptionsAmino;
            fromAminoMsg(object: _124.MethodOptionsAminoMsg): _124.MethodOptions;
            fromProtoMsg(message: _124.MethodOptionsProtoMsg): _124.MethodOptions;
            toProto(message: _124.MethodOptions): Uint8Array;
            toProtoMsg(message: _124.MethodOptions): _124.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _124.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.UninterpretedOption;
            fromPartial(object: Partial<_124.UninterpretedOption>): _124.UninterpretedOption;
            fromAmino(object: _124.UninterpretedOptionAmino): _124.UninterpretedOption;
            toAmino(message: _124.UninterpretedOption): _124.UninterpretedOptionAmino;
            fromAminoMsg(object: _124.UninterpretedOptionAminoMsg): _124.UninterpretedOption;
            fromProtoMsg(message: _124.UninterpretedOptionProtoMsg): _124.UninterpretedOption;
            toProto(message: _124.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _124.UninterpretedOption): _124.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _124.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_124.UninterpretedOption_NamePart>): _124.UninterpretedOption_NamePart;
            fromAmino(object: _124.UninterpretedOption_NamePartAmino): _124.UninterpretedOption_NamePart;
            toAmino(message: _124.UninterpretedOption_NamePart): _124.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _124.UninterpretedOption_NamePartAminoMsg): _124.UninterpretedOption_NamePart;
            fromProtoMsg(message: _124.UninterpretedOption_NamePartProtoMsg): _124.UninterpretedOption_NamePart;
            toProto(message: _124.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _124.UninterpretedOption_NamePart): _124.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _124.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.SourceCodeInfo;
            fromPartial(object: Partial<_124.SourceCodeInfo>): _124.SourceCodeInfo;
            fromAmino(object: _124.SourceCodeInfoAmino): _124.SourceCodeInfo;
            toAmino(message: _124.SourceCodeInfo): _124.SourceCodeInfoAmino;
            fromAminoMsg(object: _124.SourceCodeInfoAminoMsg): _124.SourceCodeInfo;
            fromProtoMsg(message: _124.SourceCodeInfoProtoMsg): _124.SourceCodeInfo;
            toProto(message: _124.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _124.SourceCodeInfo): _124.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _124.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.SourceCodeInfo_Location;
            fromPartial(object: Partial<_124.SourceCodeInfo_Location>): _124.SourceCodeInfo_Location;
            fromAmino(object: _124.SourceCodeInfo_LocationAmino): _124.SourceCodeInfo_Location;
            toAmino(message: _124.SourceCodeInfo_Location): _124.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _124.SourceCodeInfo_LocationAminoMsg): _124.SourceCodeInfo_Location;
            fromProtoMsg(message: _124.SourceCodeInfo_LocationProtoMsg): _124.SourceCodeInfo_Location;
            toProto(message: _124.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _124.SourceCodeInfo_Location): _124.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _124.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.GeneratedCodeInfo;
            fromPartial(object: Partial<_124.GeneratedCodeInfo>): _124.GeneratedCodeInfo;
            fromAmino(object: _124.GeneratedCodeInfoAmino): _124.GeneratedCodeInfo;
            toAmino(message: _124.GeneratedCodeInfo): _124.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _124.GeneratedCodeInfoAminoMsg): _124.GeneratedCodeInfo;
            fromProtoMsg(message: _124.GeneratedCodeInfoProtoMsg): _124.GeneratedCodeInfo;
            toProto(message: _124.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _124.GeneratedCodeInfo): _124.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _124.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_124.GeneratedCodeInfo_Annotation>): _124.GeneratedCodeInfo_Annotation;
            fromAmino(object: _124.GeneratedCodeInfo_AnnotationAmino): _124.GeneratedCodeInfo_Annotation;
            toAmino(message: _124.GeneratedCodeInfo_Annotation): _124.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _124.GeneratedCodeInfo_AnnotationAminoMsg): _124.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _124.GeneratedCodeInfo_AnnotationProtoMsg): _124.GeneratedCodeInfo_Annotation;
            toProto(message: _124.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _124.GeneratedCodeInfo_Annotation): _124.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _123.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _123.Any;
            fromPartial(object: Partial<_123.Any>): _123.Any;
            fromAmino(object: _123.AnyAmino): _123.Any;
            toAmino(message: _123.Any): _123.AnyAmino;
            fromAminoMsg(object: _123.AnyAminoMsg): _123.Any;
            fromProtoMsg(message: _123.AnyProtoMsg): _123.Any;
            toProto(message: _123.Any): Uint8Array;
            toProtoMsg(message: _123.Any): _123.AnyProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _122.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _122.Duration;
            fromPartial(object: Partial<_122.Duration>): _122.Duration;
            fromAmino(object: string): _122.Duration;
            toAmino(message: _122.Duration): string;
            fromAminoMsg(object: _122.DurationAminoMsg): _122.Duration;
            fromProtoMsg(message: _122.DurationProtoMsg): _122.Duration;
            toProto(message: _122.Duration): Uint8Array;
            toProtoMsg(message: _122.Duration): _122.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _121.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _121.Timestamp;
            fromPartial(object: Partial<_121.Timestamp>): _121.Timestamp;
            fromAmino(object: string): _121.Timestamp;
            toAmino(message: _121.Timestamp): string;
            fromAminoMsg(object: _121.TimestampAminoMsg): _121.Timestamp;
            fromProtoMsg(message: _121.TimestampProtoMsg): _121.Timestamp;
            toProto(message: _121.Timestamp): Uint8Array;
            toProtoMsg(message: _121.Timestamp): _121.TimestampProtoMsg;
        };
    };
}
