import * as _89 from "./api/http";
import * as _90 from "./api/httpbody";
import * as _91 from "./protobuf/any";
import * as _92 from "./protobuf/duration";
import * as _93 from "./protobuf/empty";
import * as _94 from "./protobuf/timestamp";
import * as _95 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        HttpBody: {
            typeUrl: string;
            encode(message: _90.HttpBody, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.HttpBody;
            fromPartial(object: Partial<_90.HttpBody>): _90.HttpBody;
            fromAmino(object: _90.HttpBodyAmino): _90.HttpBody;
            toAmino(message: _90.HttpBody): _90.HttpBodyAmino;
            fromAminoMsg(object: _90.HttpBodyAminoMsg): _90.HttpBody;
            fromProtoMsg(message: _90.HttpBodyProtoMsg): _90.HttpBody;
            toProto(message: _90.HttpBody): Uint8Array;
            toProtoMsg(message: _90.HttpBody): _90.HttpBodyProtoMsg;
        };
        Http: {
            typeUrl: string;
            encode(message: _89.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.Http;
            fromPartial(object: Partial<_89.Http>): _89.Http;
            fromAmino(object: _89.HttpAmino): _89.Http;
            toAmino(message: _89.Http): _89.HttpAmino;
            fromAminoMsg(object: _89.HttpAminoMsg): _89.Http;
            fromProtoMsg(message: _89.HttpProtoMsg): _89.Http;
            toProto(message: _89.Http): Uint8Array;
            toProtoMsg(message: _89.Http): _89.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _89.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.HttpRule;
            fromPartial(object: Partial<_89.HttpRule>): _89.HttpRule;
            fromAmino(object: _89.HttpRuleAmino): _89.HttpRule;
            toAmino(message: _89.HttpRule): _89.HttpRuleAmino;
            fromAminoMsg(object: _89.HttpRuleAminoMsg): _89.HttpRule;
            fromProtoMsg(message: _89.HttpRuleProtoMsg): _89.HttpRule;
            toProto(message: _89.HttpRule): Uint8Array;
            toProtoMsg(message: _89.HttpRule): _89.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _89.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.CustomHttpPattern;
            fromPartial(object: Partial<_89.CustomHttpPattern>): _89.CustomHttpPattern;
            fromAmino(object: _89.CustomHttpPatternAmino): _89.CustomHttpPattern;
            toAmino(message: _89.CustomHttpPattern): _89.CustomHttpPatternAmino;
            fromAminoMsg(object: _89.CustomHttpPatternAminoMsg): _89.CustomHttpPattern;
            fromProtoMsg(message: _89.CustomHttpPatternProtoMsg): _89.CustomHttpPattern;
            toProto(message: _89.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _89.CustomHttpPattern): _89.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _95.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _95.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _95.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _95.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _95.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _95.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _95.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _95.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _95.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _95.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _95.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _95.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _95.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _95.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _95.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _95.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _95.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _95.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _95.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _95.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _95.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _95.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _95.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _95.FieldOptions_CType;
        FieldOptions_JSType: typeof _95.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _95.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _95.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _95.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _95.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _95.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _95.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.FileDescriptorSet;
            fromPartial(object: Partial<_95.FileDescriptorSet>): _95.FileDescriptorSet;
            fromAmino(object: _95.FileDescriptorSetAmino): _95.FileDescriptorSet;
            toAmino(message: _95.FileDescriptorSet): _95.FileDescriptorSetAmino;
            fromAminoMsg(object: _95.FileDescriptorSetAminoMsg): _95.FileDescriptorSet;
            fromProtoMsg(message: _95.FileDescriptorSetProtoMsg): _95.FileDescriptorSet;
            toProto(message: _95.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _95.FileDescriptorSet): _95.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _95.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.FileDescriptorProto;
            fromPartial(object: Partial<_95.FileDescriptorProto>): _95.FileDescriptorProto;
            fromAmino(object: _95.FileDescriptorProtoAmino): _95.FileDescriptorProto;
            toAmino(message: _95.FileDescriptorProto): _95.FileDescriptorProtoAmino;
            fromAminoMsg(object: _95.FileDescriptorProtoAminoMsg): _95.FileDescriptorProto;
            fromProtoMsg(message: _95.FileDescriptorProtoProtoMsg): _95.FileDescriptorProto;
            toProto(message: _95.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _95.FileDescriptorProto): _95.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _95.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.DescriptorProto;
            fromPartial(object: Partial<_95.DescriptorProto>): _95.DescriptorProto;
            fromAmino(object: _95.DescriptorProtoAmino): _95.DescriptorProto;
            toAmino(message: _95.DescriptorProto): _95.DescriptorProtoAmino;
            fromAminoMsg(object: _95.DescriptorProtoAminoMsg): _95.DescriptorProto;
            fromProtoMsg(message: _95.DescriptorProtoProtoMsg): _95.DescriptorProto;
            toProto(message: _95.DescriptorProto): Uint8Array;
            toProtoMsg(message: _95.DescriptorProto): _95.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _95.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_95.DescriptorProto_ExtensionRange>): _95.DescriptorProto_ExtensionRange;
            fromAmino(object: _95.DescriptorProto_ExtensionRangeAmino): _95.DescriptorProto_ExtensionRange;
            toAmino(message: _95.DescriptorProto_ExtensionRange): _95.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _95.DescriptorProto_ExtensionRangeAminoMsg): _95.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _95.DescriptorProto_ExtensionRangeProtoMsg): _95.DescriptorProto_ExtensionRange;
            toProto(message: _95.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _95.DescriptorProto_ExtensionRange): _95.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _95.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_95.DescriptorProto_ReservedRange>): _95.DescriptorProto_ReservedRange;
            fromAmino(object: _95.DescriptorProto_ReservedRangeAmino): _95.DescriptorProto_ReservedRange;
            toAmino(message: _95.DescriptorProto_ReservedRange): _95.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _95.DescriptorProto_ReservedRangeAminoMsg): _95.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _95.DescriptorProto_ReservedRangeProtoMsg): _95.DescriptorProto_ReservedRange;
            toProto(message: _95.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _95.DescriptorProto_ReservedRange): _95.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _95.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.ExtensionRangeOptions;
            fromPartial(object: Partial<_95.ExtensionRangeOptions>): _95.ExtensionRangeOptions;
            fromAmino(object: _95.ExtensionRangeOptionsAmino): _95.ExtensionRangeOptions;
            toAmino(message: _95.ExtensionRangeOptions): _95.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _95.ExtensionRangeOptionsAminoMsg): _95.ExtensionRangeOptions;
            fromProtoMsg(message: _95.ExtensionRangeOptionsProtoMsg): _95.ExtensionRangeOptions;
            toProto(message: _95.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _95.ExtensionRangeOptions): _95.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _95.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.FieldDescriptorProto;
            fromPartial(object: Partial<_95.FieldDescriptorProto>): _95.FieldDescriptorProto;
            fromAmino(object: _95.FieldDescriptorProtoAmino): _95.FieldDescriptorProto;
            toAmino(message: _95.FieldDescriptorProto): _95.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _95.FieldDescriptorProtoAminoMsg): _95.FieldDescriptorProto;
            fromProtoMsg(message: _95.FieldDescriptorProtoProtoMsg): _95.FieldDescriptorProto;
            toProto(message: _95.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _95.FieldDescriptorProto): _95.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _95.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.OneofDescriptorProto;
            fromPartial(object: Partial<_95.OneofDescriptorProto>): _95.OneofDescriptorProto;
            fromAmino(object: _95.OneofDescriptorProtoAmino): _95.OneofDescriptorProto;
            toAmino(message: _95.OneofDescriptorProto): _95.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _95.OneofDescriptorProtoAminoMsg): _95.OneofDescriptorProto;
            fromProtoMsg(message: _95.OneofDescriptorProtoProtoMsg): _95.OneofDescriptorProto;
            toProto(message: _95.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _95.OneofDescriptorProto): _95.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _95.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.EnumDescriptorProto;
            fromPartial(object: Partial<_95.EnumDescriptorProto>): _95.EnumDescriptorProto;
            fromAmino(object: _95.EnumDescriptorProtoAmino): _95.EnumDescriptorProto;
            toAmino(message: _95.EnumDescriptorProto): _95.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _95.EnumDescriptorProtoAminoMsg): _95.EnumDescriptorProto;
            fromProtoMsg(message: _95.EnumDescriptorProtoProtoMsg): _95.EnumDescriptorProto;
            toProto(message: _95.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _95.EnumDescriptorProto): _95.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _95.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_95.EnumDescriptorProto_EnumReservedRange>): _95.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _95.EnumDescriptorProto_EnumReservedRangeAmino): _95.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _95.EnumDescriptorProto_EnumReservedRange): _95.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _95.EnumDescriptorProto_EnumReservedRangeAminoMsg): _95.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _95.EnumDescriptorProto_EnumReservedRangeProtoMsg): _95.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _95.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _95.EnumDescriptorProto_EnumReservedRange): _95.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _95.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.EnumValueDescriptorProto;
            fromPartial(object: Partial<_95.EnumValueDescriptorProto>): _95.EnumValueDescriptorProto;
            fromAmino(object: _95.EnumValueDescriptorProtoAmino): _95.EnumValueDescriptorProto;
            toAmino(message: _95.EnumValueDescriptorProto): _95.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _95.EnumValueDescriptorProtoAminoMsg): _95.EnumValueDescriptorProto;
            fromProtoMsg(message: _95.EnumValueDescriptorProtoProtoMsg): _95.EnumValueDescriptorProto;
            toProto(message: _95.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _95.EnumValueDescriptorProto): _95.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _95.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.ServiceDescriptorProto;
            fromPartial(object: Partial<_95.ServiceDescriptorProto>): _95.ServiceDescriptorProto;
            fromAmino(object: _95.ServiceDescriptorProtoAmino): _95.ServiceDescriptorProto;
            toAmino(message: _95.ServiceDescriptorProto): _95.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _95.ServiceDescriptorProtoAminoMsg): _95.ServiceDescriptorProto;
            fromProtoMsg(message: _95.ServiceDescriptorProtoProtoMsg): _95.ServiceDescriptorProto;
            toProto(message: _95.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _95.ServiceDescriptorProto): _95.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _95.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.MethodDescriptorProto;
            fromPartial(object: Partial<_95.MethodDescriptorProto>): _95.MethodDescriptorProto;
            fromAmino(object: _95.MethodDescriptorProtoAmino): _95.MethodDescriptorProto;
            toAmino(message: _95.MethodDescriptorProto): _95.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _95.MethodDescriptorProtoAminoMsg): _95.MethodDescriptorProto;
            fromProtoMsg(message: _95.MethodDescriptorProtoProtoMsg): _95.MethodDescriptorProto;
            toProto(message: _95.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _95.MethodDescriptorProto): _95.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _95.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.FileOptions;
            fromPartial(object: Partial<_95.FileOptions>): _95.FileOptions;
            fromAmino(object: _95.FileOptionsAmino): _95.FileOptions;
            toAmino(message: _95.FileOptions): _95.FileOptionsAmino;
            fromAminoMsg(object: _95.FileOptionsAminoMsg): _95.FileOptions;
            fromProtoMsg(message: _95.FileOptionsProtoMsg): _95.FileOptions;
            toProto(message: _95.FileOptions): Uint8Array;
            toProtoMsg(message: _95.FileOptions): _95.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _95.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.MessageOptions;
            fromPartial(object: Partial<_95.MessageOptions>): _95.MessageOptions;
            fromAmino(object: _95.MessageOptionsAmino): _95.MessageOptions;
            toAmino(message: _95.MessageOptions): _95.MessageOptionsAmino;
            fromAminoMsg(object: _95.MessageOptionsAminoMsg): _95.MessageOptions;
            fromProtoMsg(message: _95.MessageOptionsProtoMsg): _95.MessageOptions;
            toProto(message: _95.MessageOptions): Uint8Array;
            toProtoMsg(message: _95.MessageOptions): _95.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _95.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.FieldOptions;
            fromPartial(object: Partial<_95.FieldOptions>): _95.FieldOptions;
            fromAmino(object: _95.FieldOptionsAmino): _95.FieldOptions;
            toAmino(message: _95.FieldOptions): _95.FieldOptionsAmino;
            fromAminoMsg(object: _95.FieldOptionsAminoMsg): _95.FieldOptions;
            fromProtoMsg(message: _95.FieldOptionsProtoMsg): _95.FieldOptions;
            toProto(message: _95.FieldOptions): Uint8Array;
            toProtoMsg(message: _95.FieldOptions): _95.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _95.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.OneofOptions;
            fromPartial(object: Partial<_95.OneofOptions>): _95.OneofOptions;
            fromAmino(object: _95.OneofOptionsAmino): _95.OneofOptions;
            toAmino(message: _95.OneofOptions): _95.OneofOptionsAmino;
            fromAminoMsg(object: _95.OneofOptionsAminoMsg): _95.OneofOptions;
            fromProtoMsg(message: _95.OneofOptionsProtoMsg): _95.OneofOptions;
            toProto(message: _95.OneofOptions): Uint8Array;
            toProtoMsg(message: _95.OneofOptions): _95.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _95.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.EnumOptions;
            fromPartial(object: Partial<_95.EnumOptions>): _95.EnumOptions;
            fromAmino(object: _95.EnumOptionsAmino): _95.EnumOptions;
            toAmino(message: _95.EnumOptions): _95.EnumOptionsAmino;
            fromAminoMsg(object: _95.EnumOptionsAminoMsg): _95.EnumOptions;
            fromProtoMsg(message: _95.EnumOptionsProtoMsg): _95.EnumOptions;
            toProto(message: _95.EnumOptions): Uint8Array;
            toProtoMsg(message: _95.EnumOptions): _95.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _95.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.EnumValueOptions;
            fromPartial(object: Partial<_95.EnumValueOptions>): _95.EnumValueOptions;
            fromAmino(object: _95.EnumValueOptionsAmino): _95.EnumValueOptions;
            toAmino(message: _95.EnumValueOptions): _95.EnumValueOptionsAmino;
            fromAminoMsg(object: _95.EnumValueOptionsAminoMsg): _95.EnumValueOptions;
            fromProtoMsg(message: _95.EnumValueOptionsProtoMsg): _95.EnumValueOptions;
            toProto(message: _95.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _95.EnumValueOptions): _95.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _95.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.ServiceOptions;
            fromPartial(object: Partial<_95.ServiceOptions>): _95.ServiceOptions;
            fromAmino(object: _95.ServiceOptionsAmino): _95.ServiceOptions;
            toAmino(message: _95.ServiceOptions): _95.ServiceOptionsAmino;
            fromAminoMsg(object: _95.ServiceOptionsAminoMsg): _95.ServiceOptions;
            fromProtoMsg(message: _95.ServiceOptionsProtoMsg): _95.ServiceOptions;
            toProto(message: _95.ServiceOptions): Uint8Array;
            toProtoMsg(message: _95.ServiceOptions): _95.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _95.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.MethodOptions;
            fromPartial(object: Partial<_95.MethodOptions>): _95.MethodOptions;
            fromAmino(object: _95.MethodOptionsAmino): _95.MethodOptions;
            toAmino(message: _95.MethodOptions): _95.MethodOptionsAmino;
            fromAminoMsg(object: _95.MethodOptionsAminoMsg): _95.MethodOptions;
            fromProtoMsg(message: _95.MethodOptionsProtoMsg): _95.MethodOptions;
            toProto(message: _95.MethodOptions): Uint8Array;
            toProtoMsg(message: _95.MethodOptions): _95.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _95.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.UninterpretedOption;
            fromPartial(object: Partial<_95.UninterpretedOption>): _95.UninterpretedOption;
            fromAmino(object: _95.UninterpretedOptionAmino): _95.UninterpretedOption;
            toAmino(message: _95.UninterpretedOption): _95.UninterpretedOptionAmino;
            fromAminoMsg(object: _95.UninterpretedOptionAminoMsg): _95.UninterpretedOption;
            fromProtoMsg(message: _95.UninterpretedOptionProtoMsg): _95.UninterpretedOption;
            toProto(message: _95.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _95.UninterpretedOption): _95.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _95.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_95.UninterpretedOption_NamePart>): _95.UninterpretedOption_NamePart;
            fromAmino(object: _95.UninterpretedOption_NamePartAmino): _95.UninterpretedOption_NamePart;
            toAmino(message: _95.UninterpretedOption_NamePart): _95.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _95.UninterpretedOption_NamePartAminoMsg): _95.UninterpretedOption_NamePart;
            fromProtoMsg(message: _95.UninterpretedOption_NamePartProtoMsg): _95.UninterpretedOption_NamePart;
            toProto(message: _95.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _95.UninterpretedOption_NamePart): _95.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _95.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.SourceCodeInfo;
            fromPartial(object: Partial<_95.SourceCodeInfo>): _95.SourceCodeInfo;
            fromAmino(object: _95.SourceCodeInfoAmino): _95.SourceCodeInfo;
            toAmino(message: _95.SourceCodeInfo): _95.SourceCodeInfoAmino;
            fromAminoMsg(object: _95.SourceCodeInfoAminoMsg): _95.SourceCodeInfo;
            fromProtoMsg(message: _95.SourceCodeInfoProtoMsg): _95.SourceCodeInfo;
            toProto(message: _95.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _95.SourceCodeInfo): _95.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _95.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.SourceCodeInfo_Location;
            fromPartial(object: Partial<_95.SourceCodeInfo_Location>): _95.SourceCodeInfo_Location;
            fromAmino(object: _95.SourceCodeInfo_LocationAmino): _95.SourceCodeInfo_Location;
            toAmino(message: _95.SourceCodeInfo_Location): _95.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _95.SourceCodeInfo_LocationAminoMsg): _95.SourceCodeInfo_Location;
            fromProtoMsg(message: _95.SourceCodeInfo_LocationProtoMsg): _95.SourceCodeInfo_Location;
            toProto(message: _95.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _95.SourceCodeInfo_Location): _95.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _95.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.GeneratedCodeInfo;
            fromPartial(object: Partial<_95.GeneratedCodeInfo>): _95.GeneratedCodeInfo;
            fromAmino(object: _95.GeneratedCodeInfoAmino): _95.GeneratedCodeInfo;
            toAmino(message: _95.GeneratedCodeInfo): _95.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _95.GeneratedCodeInfoAminoMsg): _95.GeneratedCodeInfo;
            fromProtoMsg(message: _95.GeneratedCodeInfoProtoMsg): _95.GeneratedCodeInfo;
            toProto(message: _95.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _95.GeneratedCodeInfo): _95.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _95.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_95.GeneratedCodeInfo_Annotation>): _95.GeneratedCodeInfo_Annotation;
            fromAmino(object: _95.GeneratedCodeInfo_AnnotationAmino): _95.GeneratedCodeInfo_Annotation;
            toAmino(message: _95.GeneratedCodeInfo_Annotation): _95.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _95.GeneratedCodeInfo_AnnotationAminoMsg): _95.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _95.GeneratedCodeInfo_AnnotationProtoMsg): _95.GeneratedCodeInfo_Annotation;
            toProto(message: _95.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _95.GeneratedCodeInfo_Annotation): _95.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _94.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _94.Timestamp;
            fromPartial(object: Partial<_94.Timestamp>): _94.Timestamp;
            fromAmino(object: string): _94.Timestamp;
            toAmino(message: _94.Timestamp): string;
            fromAminoMsg(object: _94.TimestampAminoMsg): _94.Timestamp;
            fromProtoMsg(message: _94.TimestampProtoMsg): _94.Timestamp;
            toProto(message: _94.Timestamp): Uint8Array;
            toProtoMsg(message: _94.Timestamp): _94.TimestampProtoMsg;
        };
        Empty: {
            typeUrl: string;
            encode(_: _93.Empty, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _93.Empty;
            fromPartial(_: Partial<_93.Empty>): _93.Empty;
            fromAmino(_: _93.EmptyAmino): _93.Empty;
            toAmino(_: _93.Empty): _93.EmptyAmino;
            fromAminoMsg(object: _93.EmptyAminoMsg): _93.Empty;
            fromProtoMsg(message: _93.EmptyProtoMsg): _93.Empty;
            toProto(message: _93.Empty): Uint8Array;
            toProtoMsg(message: _93.Empty): _93.EmptyProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _92.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _92.Duration;
            fromPartial(object: Partial<_92.Duration>): _92.Duration;
            fromAmino(object: string): _92.Duration;
            toAmino(message: _92.Duration): string;
            fromAminoMsg(object: _92.DurationAminoMsg): _92.Duration;
            fromProtoMsg(message: _92.DurationProtoMsg): _92.Duration;
            toProto(message: _92.Duration): Uint8Array;
            toProtoMsg(message: _92.Duration): _92.DurationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _91.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _91.Any;
            fromPartial(object: Partial<_91.Any>): _91.Any;
            fromAmino(object: _91.AnyAmino): _91.Any;
            toAmino(message: _91.Any): _91.AnyAmino;
            fromAminoMsg(object: _91.AnyAminoMsg): _91.Any;
            fromProtoMsg(message: _91.AnyProtoMsg): _91.Any;
            toProto(message: _91.Any): Uint8Array;
            toProtoMsg(message: _91.Any): _91.AnyProtoMsg;
        };
    };
}
