import * as _207 from "./api/http";
import * as _208 from "./protobuf/any";
import * as _209 from "./protobuf/timestamp";
import * as _210 from "./protobuf/duration";
import * as _211 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _207.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _207.Http;
            fromPartial(object: Partial<_207.Http>): _207.Http;
            fromAmino(object: _207.HttpAmino): _207.Http;
            toAmino(message: _207.Http): _207.HttpAmino;
            fromAminoMsg(object: _207.HttpAminoMsg): _207.Http;
            fromProtoMsg(message: _207.HttpProtoMsg): _207.Http;
            toProto(message: _207.Http): Uint8Array;
            toProtoMsg(message: _207.Http): _207.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _207.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _207.HttpRule;
            fromPartial(object: Partial<_207.HttpRule>): _207.HttpRule;
            fromAmino(object: _207.HttpRuleAmino): _207.HttpRule;
            toAmino(message: _207.HttpRule): _207.HttpRuleAmino;
            fromAminoMsg(object: _207.HttpRuleAminoMsg): _207.HttpRule;
            fromProtoMsg(message: _207.HttpRuleProtoMsg): _207.HttpRule;
            toProto(message: _207.HttpRule): Uint8Array;
            toProtoMsg(message: _207.HttpRule): _207.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _207.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _207.CustomHttpPattern;
            fromPartial(object: Partial<_207.CustomHttpPattern>): _207.CustomHttpPattern;
            fromAmino(object: _207.CustomHttpPatternAmino): _207.CustomHttpPattern;
            toAmino(message: _207.CustomHttpPattern): _207.CustomHttpPatternAmino;
            fromAminoMsg(object: _207.CustomHttpPatternAminoMsg): _207.CustomHttpPattern;
            fromProtoMsg(message: _207.CustomHttpPatternProtoMsg): _207.CustomHttpPattern;
            toProto(message: _207.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _207.CustomHttpPattern): _207.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _211.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _211.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _211.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _211.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _211.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _211.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _211.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _211.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _211.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _211.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _211.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _211.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _211.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _211.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _211.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _211.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _211.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _211.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _211.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _211.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _211.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _211.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _211.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _211.FieldOptions_CType;
        FieldOptions_JSType: typeof _211.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _211.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _211.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _211.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _211.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _211.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _211.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.FileDescriptorSet;
            fromPartial(object: Partial<_211.FileDescriptorSet>): _211.FileDescriptorSet;
            fromAmino(object: _211.FileDescriptorSetAmino): _211.FileDescriptorSet;
            toAmino(message: _211.FileDescriptorSet): _211.FileDescriptorSetAmino;
            fromAminoMsg(object: _211.FileDescriptorSetAminoMsg): _211.FileDescriptorSet;
            fromProtoMsg(message: _211.FileDescriptorSetProtoMsg): _211.FileDescriptorSet;
            toProto(message: _211.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _211.FileDescriptorSet): _211.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _211.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.FileDescriptorProto;
            fromPartial(object: Partial<_211.FileDescriptorProto>): _211.FileDescriptorProto;
            fromAmino(object: _211.FileDescriptorProtoAmino): _211.FileDescriptorProto;
            toAmino(message: _211.FileDescriptorProto): _211.FileDescriptorProtoAmino;
            fromAminoMsg(object: _211.FileDescriptorProtoAminoMsg): _211.FileDescriptorProto;
            fromProtoMsg(message: _211.FileDescriptorProtoProtoMsg): _211.FileDescriptorProto;
            toProto(message: _211.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _211.FileDescriptorProto): _211.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _211.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.DescriptorProto;
            fromPartial(object: Partial<_211.DescriptorProto>): _211.DescriptorProto;
            fromAmino(object: _211.DescriptorProtoAmino): _211.DescriptorProto;
            toAmino(message: _211.DescriptorProto): _211.DescriptorProtoAmino;
            fromAminoMsg(object: _211.DescriptorProtoAminoMsg): _211.DescriptorProto;
            fromProtoMsg(message: _211.DescriptorProtoProtoMsg): _211.DescriptorProto;
            toProto(message: _211.DescriptorProto): Uint8Array;
            toProtoMsg(message: _211.DescriptorProto): _211.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _211.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_211.DescriptorProto_ExtensionRange>): _211.DescriptorProto_ExtensionRange;
            fromAmino(object: _211.DescriptorProto_ExtensionRangeAmino): _211.DescriptorProto_ExtensionRange;
            toAmino(message: _211.DescriptorProto_ExtensionRange): _211.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _211.DescriptorProto_ExtensionRangeAminoMsg): _211.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _211.DescriptorProto_ExtensionRangeProtoMsg): _211.DescriptorProto_ExtensionRange;
            toProto(message: _211.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _211.DescriptorProto_ExtensionRange): _211.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _211.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_211.DescriptorProto_ReservedRange>): _211.DescriptorProto_ReservedRange;
            fromAmino(object: _211.DescriptorProto_ReservedRangeAmino): _211.DescriptorProto_ReservedRange;
            toAmino(message: _211.DescriptorProto_ReservedRange): _211.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _211.DescriptorProto_ReservedRangeAminoMsg): _211.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _211.DescriptorProto_ReservedRangeProtoMsg): _211.DescriptorProto_ReservedRange;
            toProto(message: _211.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _211.DescriptorProto_ReservedRange): _211.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _211.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.ExtensionRangeOptions;
            fromPartial(object: Partial<_211.ExtensionRangeOptions>): _211.ExtensionRangeOptions;
            fromAmino(object: _211.ExtensionRangeOptionsAmino): _211.ExtensionRangeOptions;
            toAmino(message: _211.ExtensionRangeOptions): _211.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _211.ExtensionRangeOptionsAminoMsg): _211.ExtensionRangeOptions;
            fromProtoMsg(message: _211.ExtensionRangeOptionsProtoMsg): _211.ExtensionRangeOptions;
            toProto(message: _211.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _211.ExtensionRangeOptions): _211.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _211.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.FieldDescriptorProto;
            fromPartial(object: Partial<_211.FieldDescriptorProto>): _211.FieldDescriptorProto;
            fromAmino(object: _211.FieldDescriptorProtoAmino): _211.FieldDescriptorProto;
            toAmino(message: _211.FieldDescriptorProto): _211.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _211.FieldDescriptorProtoAminoMsg): _211.FieldDescriptorProto;
            fromProtoMsg(message: _211.FieldDescriptorProtoProtoMsg): _211.FieldDescriptorProto;
            toProto(message: _211.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _211.FieldDescriptorProto): _211.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _211.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.OneofDescriptorProto;
            fromPartial(object: Partial<_211.OneofDescriptorProto>): _211.OneofDescriptorProto;
            fromAmino(object: _211.OneofDescriptorProtoAmino): _211.OneofDescriptorProto;
            toAmino(message: _211.OneofDescriptorProto): _211.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _211.OneofDescriptorProtoAminoMsg): _211.OneofDescriptorProto;
            fromProtoMsg(message: _211.OneofDescriptorProtoProtoMsg): _211.OneofDescriptorProto;
            toProto(message: _211.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _211.OneofDescriptorProto): _211.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _211.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.EnumDescriptorProto;
            fromPartial(object: Partial<_211.EnumDescriptorProto>): _211.EnumDescriptorProto;
            fromAmino(object: _211.EnumDescriptorProtoAmino): _211.EnumDescriptorProto;
            toAmino(message: _211.EnumDescriptorProto): _211.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _211.EnumDescriptorProtoAminoMsg): _211.EnumDescriptorProto;
            fromProtoMsg(message: _211.EnumDescriptorProtoProtoMsg): _211.EnumDescriptorProto;
            toProto(message: _211.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _211.EnumDescriptorProto): _211.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _211.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_211.EnumDescriptorProto_EnumReservedRange>): _211.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _211.EnumDescriptorProto_EnumReservedRangeAmino): _211.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _211.EnumDescriptorProto_EnumReservedRange): _211.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _211.EnumDescriptorProto_EnumReservedRangeAminoMsg): _211.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _211.EnumDescriptorProto_EnumReservedRangeProtoMsg): _211.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _211.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _211.EnumDescriptorProto_EnumReservedRange): _211.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _211.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.EnumValueDescriptorProto;
            fromPartial(object: Partial<_211.EnumValueDescriptorProto>): _211.EnumValueDescriptorProto;
            fromAmino(object: _211.EnumValueDescriptorProtoAmino): _211.EnumValueDescriptorProto;
            toAmino(message: _211.EnumValueDescriptorProto): _211.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _211.EnumValueDescriptorProtoAminoMsg): _211.EnumValueDescriptorProto;
            fromProtoMsg(message: _211.EnumValueDescriptorProtoProtoMsg): _211.EnumValueDescriptorProto;
            toProto(message: _211.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _211.EnumValueDescriptorProto): _211.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _211.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.ServiceDescriptorProto;
            fromPartial(object: Partial<_211.ServiceDescriptorProto>): _211.ServiceDescriptorProto;
            fromAmino(object: _211.ServiceDescriptorProtoAmino): _211.ServiceDescriptorProto;
            toAmino(message: _211.ServiceDescriptorProto): _211.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _211.ServiceDescriptorProtoAminoMsg): _211.ServiceDescriptorProto;
            fromProtoMsg(message: _211.ServiceDescriptorProtoProtoMsg): _211.ServiceDescriptorProto;
            toProto(message: _211.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _211.ServiceDescriptorProto): _211.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _211.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.MethodDescriptorProto;
            fromPartial(object: Partial<_211.MethodDescriptorProto>): _211.MethodDescriptorProto;
            fromAmino(object: _211.MethodDescriptorProtoAmino): _211.MethodDescriptorProto;
            toAmino(message: _211.MethodDescriptorProto): _211.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _211.MethodDescriptorProtoAminoMsg): _211.MethodDescriptorProto;
            fromProtoMsg(message: _211.MethodDescriptorProtoProtoMsg): _211.MethodDescriptorProto;
            toProto(message: _211.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _211.MethodDescriptorProto): _211.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _211.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.FileOptions;
            fromPartial(object: Partial<_211.FileOptions>): _211.FileOptions;
            fromAmino(object: _211.FileOptionsAmino): _211.FileOptions;
            toAmino(message: _211.FileOptions): _211.FileOptionsAmino;
            fromAminoMsg(object: _211.FileOptionsAminoMsg): _211.FileOptions;
            fromProtoMsg(message: _211.FileOptionsProtoMsg): _211.FileOptions;
            toProto(message: _211.FileOptions): Uint8Array;
            toProtoMsg(message: _211.FileOptions): _211.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _211.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.MessageOptions;
            fromPartial(object: Partial<_211.MessageOptions>): _211.MessageOptions;
            fromAmino(object: _211.MessageOptionsAmino): _211.MessageOptions;
            toAmino(message: _211.MessageOptions): _211.MessageOptionsAmino;
            fromAminoMsg(object: _211.MessageOptionsAminoMsg): _211.MessageOptions;
            fromProtoMsg(message: _211.MessageOptionsProtoMsg): _211.MessageOptions;
            toProto(message: _211.MessageOptions): Uint8Array;
            toProtoMsg(message: _211.MessageOptions): _211.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _211.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.FieldOptions;
            fromPartial(object: Partial<_211.FieldOptions>): _211.FieldOptions;
            fromAmino(object: _211.FieldOptionsAmino): _211.FieldOptions;
            toAmino(message: _211.FieldOptions): _211.FieldOptionsAmino;
            fromAminoMsg(object: _211.FieldOptionsAminoMsg): _211.FieldOptions;
            fromProtoMsg(message: _211.FieldOptionsProtoMsg): _211.FieldOptions;
            toProto(message: _211.FieldOptions): Uint8Array;
            toProtoMsg(message: _211.FieldOptions): _211.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _211.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.OneofOptions;
            fromPartial(object: Partial<_211.OneofOptions>): _211.OneofOptions;
            fromAmino(object: _211.OneofOptionsAmino): _211.OneofOptions;
            toAmino(message: _211.OneofOptions): _211.OneofOptionsAmino;
            fromAminoMsg(object: _211.OneofOptionsAminoMsg): _211.OneofOptions;
            fromProtoMsg(message: _211.OneofOptionsProtoMsg): _211.OneofOptions;
            toProto(message: _211.OneofOptions): Uint8Array;
            toProtoMsg(message: _211.OneofOptions): _211.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _211.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.EnumOptions;
            fromPartial(object: Partial<_211.EnumOptions>): _211.EnumOptions;
            fromAmino(object: _211.EnumOptionsAmino): _211.EnumOptions;
            toAmino(message: _211.EnumOptions): _211.EnumOptionsAmino;
            fromAminoMsg(object: _211.EnumOptionsAminoMsg): _211.EnumOptions;
            fromProtoMsg(message: _211.EnumOptionsProtoMsg): _211.EnumOptions;
            toProto(message: _211.EnumOptions): Uint8Array;
            toProtoMsg(message: _211.EnumOptions): _211.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _211.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.EnumValueOptions;
            fromPartial(object: Partial<_211.EnumValueOptions>): _211.EnumValueOptions;
            fromAmino(object: _211.EnumValueOptionsAmino): _211.EnumValueOptions;
            toAmino(message: _211.EnumValueOptions): _211.EnumValueOptionsAmino;
            fromAminoMsg(object: _211.EnumValueOptionsAminoMsg): _211.EnumValueOptions;
            fromProtoMsg(message: _211.EnumValueOptionsProtoMsg): _211.EnumValueOptions;
            toProto(message: _211.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _211.EnumValueOptions): _211.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _211.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.ServiceOptions;
            fromPartial(object: Partial<_211.ServiceOptions>): _211.ServiceOptions;
            fromAmino(object: _211.ServiceOptionsAmino): _211.ServiceOptions;
            toAmino(message: _211.ServiceOptions): _211.ServiceOptionsAmino;
            fromAminoMsg(object: _211.ServiceOptionsAminoMsg): _211.ServiceOptions;
            fromProtoMsg(message: _211.ServiceOptionsProtoMsg): _211.ServiceOptions;
            toProto(message: _211.ServiceOptions): Uint8Array;
            toProtoMsg(message: _211.ServiceOptions): _211.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _211.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.MethodOptions;
            fromPartial(object: Partial<_211.MethodOptions>): _211.MethodOptions;
            fromAmino(object: _211.MethodOptionsAmino): _211.MethodOptions;
            toAmino(message: _211.MethodOptions): _211.MethodOptionsAmino;
            fromAminoMsg(object: _211.MethodOptionsAminoMsg): _211.MethodOptions;
            fromProtoMsg(message: _211.MethodOptionsProtoMsg): _211.MethodOptions;
            toProto(message: _211.MethodOptions): Uint8Array;
            toProtoMsg(message: _211.MethodOptions): _211.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _211.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.UninterpretedOption;
            fromPartial(object: Partial<_211.UninterpretedOption>): _211.UninterpretedOption;
            fromAmino(object: _211.UninterpretedOptionAmino): _211.UninterpretedOption;
            toAmino(message: _211.UninterpretedOption): _211.UninterpretedOptionAmino;
            fromAminoMsg(object: _211.UninterpretedOptionAminoMsg): _211.UninterpretedOption;
            fromProtoMsg(message: _211.UninterpretedOptionProtoMsg): _211.UninterpretedOption;
            toProto(message: _211.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _211.UninterpretedOption): _211.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _211.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_211.UninterpretedOption_NamePart>): _211.UninterpretedOption_NamePart;
            fromAmino(object: _211.UninterpretedOption_NamePartAmino): _211.UninterpretedOption_NamePart;
            toAmino(message: _211.UninterpretedOption_NamePart): _211.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _211.UninterpretedOption_NamePartAminoMsg): _211.UninterpretedOption_NamePart;
            fromProtoMsg(message: _211.UninterpretedOption_NamePartProtoMsg): _211.UninterpretedOption_NamePart;
            toProto(message: _211.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _211.UninterpretedOption_NamePart): _211.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _211.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.SourceCodeInfo;
            fromPartial(object: Partial<_211.SourceCodeInfo>): _211.SourceCodeInfo;
            fromAmino(object: _211.SourceCodeInfoAmino): _211.SourceCodeInfo;
            toAmino(message: _211.SourceCodeInfo): _211.SourceCodeInfoAmino;
            fromAminoMsg(object: _211.SourceCodeInfoAminoMsg): _211.SourceCodeInfo;
            fromProtoMsg(message: _211.SourceCodeInfoProtoMsg): _211.SourceCodeInfo;
            toProto(message: _211.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _211.SourceCodeInfo): _211.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _211.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.SourceCodeInfo_Location;
            fromPartial(object: Partial<_211.SourceCodeInfo_Location>): _211.SourceCodeInfo_Location;
            fromAmino(object: _211.SourceCodeInfo_LocationAmino): _211.SourceCodeInfo_Location;
            toAmino(message: _211.SourceCodeInfo_Location): _211.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _211.SourceCodeInfo_LocationAminoMsg): _211.SourceCodeInfo_Location;
            fromProtoMsg(message: _211.SourceCodeInfo_LocationProtoMsg): _211.SourceCodeInfo_Location;
            toProto(message: _211.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _211.SourceCodeInfo_Location): _211.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _211.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.GeneratedCodeInfo;
            fromPartial(object: Partial<_211.GeneratedCodeInfo>): _211.GeneratedCodeInfo;
            fromAmino(object: _211.GeneratedCodeInfoAmino): _211.GeneratedCodeInfo;
            toAmino(message: _211.GeneratedCodeInfo): _211.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _211.GeneratedCodeInfoAminoMsg): _211.GeneratedCodeInfo;
            fromProtoMsg(message: _211.GeneratedCodeInfoProtoMsg): _211.GeneratedCodeInfo;
            toProto(message: _211.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _211.GeneratedCodeInfo): _211.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _211.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_211.GeneratedCodeInfo_Annotation>): _211.GeneratedCodeInfo_Annotation;
            fromAmino(object: _211.GeneratedCodeInfo_AnnotationAmino): _211.GeneratedCodeInfo_Annotation;
            toAmino(message: _211.GeneratedCodeInfo_Annotation): _211.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _211.GeneratedCodeInfo_AnnotationAminoMsg): _211.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _211.GeneratedCodeInfo_AnnotationProtoMsg): _211.GeneratedCodeInfo_Annotation;
            toProto(message: _211.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _211.GeneratedCodeInfo_Annotation): _211.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _210.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _210.Duration;
            fromPartial(object: Partial<_210.Duration>): _210.Duration;
            fromAmino(object: string): _210.Duration;
            toAmino(message: _210.Duration): string;
            fromAminoMsg(object: _210.DurationAminoMsg): _210.Duration;
            fromProtoMsg(message: _210.DurationProtoMsg): _210.Duration;
            toProto(message: _210.Duration): Uint8Array;
            toProtoMsg(message: _210.Duration): _210.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _209.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _209.Timestamp;
            fromPartial(object: Partial<_209.Timestamp>): _209.Timestamp;
            fromAmino(object: string): _209.Timestamp;
            toAmino(message: _209.Timestamp): string;
            fromAminoMsg(object: _209.TimestampAminoMsg): _209.Timestamp;
            fromProtoMsg(message: _209.TimestampProtoMsg): _209.Timestamp;
            toProto(message: _209.Timestamp): Uint8Array;
            toProtoMsg(message: _209.Timestamp): _209.TimestampProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _208.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _208.Any;
            fromPartial(object: Partial<_208.Any>): _208.Any;
            fromAmino(object: _208.AnyAmino): _208.Any;
            toAmino(message: _208.Any): _208.AnyAmino;
            fromAminoMsg(object: _208.AnyAminoMsg): _208.Any;
            fromProtoMsg(message: _208.AnyProtoMsg): _208.Any;
            toProto(message: _208.Any): Uint8Array;
            toProtoMsg(message: _208.Any): _208.AnyProtoMsg;
        };
    };
}
