import * as _149 from "./api/http";
import * as _150 from "./protobuf/any";
import * as _151 from "./protobuf/timestamp";
import * as _152 from "./protobuf/duration";
import * as _153 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _149.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _149.Http;
            fromPartial(object: Partial<_149.Http>): _149.Http;
            fromAmino(object: _149.HttpAmino): _149.Http;
            toAmino(message: _149.Http): _149.HttpAmino;
            fromAminoMsg(object: _149.HttpAminoMsg): _149.Http;
            fromProtoMsg(message: _149.HttpProtoMsg): _149.Http;
            toProto(message: _149.Http): Uint8Array;
            toProtoMsg(message: _149.Http): _149.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _149.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _149.HttpRule;
            fromPartial(object: Partial<_149.HttpRule>): _149.HttpRule;
            fromAmino(object: _149.HttpRuleAmino): _149.HttpRule;
            toAmino(message: _149.HttpRule): _149.HttpRuleAmino;
            fromAminoMsg(object: _149.HttpRuleAminoMsg): _149.HttpRule;
            fromProtoMsg(message: _149.HttpRuleProtoMsg): _149.HttpRule;
            toProto(message: _149.HttpRule): Uint8Array;
            toProtoMsg(message: _149.HttpRule): _149.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _149.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _149.CustomHttpPattern;
            fromPartial(object: Partial<_149.CustomHttpPattern>): _149.CustomHttpPattern;
            fromAmino(object: _149.CustomHttpPatternAmino): _149.CustomHttpPattern;
            toAmino(message: _149.CustomHttpPattern): _149.CustomHttpPatternAmino;
            fromAminoMsg(object: _149.CustomHttpPatternAminoMsg): _149.CustomHttpPattern;
            fromProtoMsg(message: _149.CustomHttpPatternProtoMsg): _149.CustomHttpPattern;
            toProto(message: _149.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _149.CustomHttpPattern): _149.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _153.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _153.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _153.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _153.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _153.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _153.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _153.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _153.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _153.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _153.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _153.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _153.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _153.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _153.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _153.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _153.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _153.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _153.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _153.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _153.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _153.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _153.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _153.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _153.FieldOptions_CType;
        FieldOptions_JSType: typeof _153.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _153.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _153.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _153.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _153.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _153.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _153.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.FileDescriptorSet;
            fromPartial(object: Partial<_153.FileDescriptorSet>): _153.FileDescriptorSet;
            fromAmino(object: _153.FileDescriptorSetAmino): _153.FileDescriptorSet;
            toAmino(message: _153.FileDescriptorSet): _153.FileDescriptorSetAmino;
            fromAminoMsg(object: _153.FileDescriptorSetAminoMsg): _153.FileDescriptorSet;
            fromProtoMsg(message: _153.FileDescriptorSetProtoMsg): _153.FileDescriptorSet;
            toProto(message: _153.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _153.FileDescriptorSet): _153.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _153.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.FileDescriptorProto;
            fromPartial(object: Partial<_153.FileDescriptorProto>): _153.FileDescriptorProto;
            fromAmino(object: _153.FileDescriptorProtoAmino): _153.FileDescriptorProto;
            toAmino(message: _153.FileDescriptorProto): _153.FileDescriptorProtoAmino;
            fromAminoMsg(object: _153.FileDescriptorProtoAminoMsg): _153.FileDescriptorProto;
            fromProtoMsg(message: _153.FileDescriptorProtoProtoMsg): _153.FileDescriptorProto;
            toProto(message: _153.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _153.FileDescriptorProto): _153.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _153.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.DescriptorProto;
            fromPartial(object: Partial<_153.DescriptorProto>): _153.DescriptorProto;
            fromAmino(object: _153.DescriptorProtoAmino): _153.DescriptorProto;
            toAmino(message: _153.DescriptorProto): _153.DescriptorProtoAmino;
            fromAminoMsg(object: _153.DescriptorProtoAminoMsg): _153.DescriptorProto;
            fromProtoMsg(message: _153.DescriptorProtoProtoMsg): _153.DescriptorProto;
            toProto(message: _153.DescriptorProto): Uint8Array;
            toProtoMsg(message: _153.DescriptorProto): _153.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _153.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_153.DescriptorProto_ExtensionRange>): _153.DescriptorProto_ExtensionRange;
            fromAmino(object: _153.DescriptorProto_ExtensionRangeAmino): _153.DescriptorProto_ExtensionRange;
            toAmino(message: _153.DescriptorProto_ExtensionRange): _153.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _153.DescriptorProto_ExtensionRangeAminoMsg): _153.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _153.DescriptorProto_ExtensionRangeProtoMsg): _153.DescriptorProto_ExtensionRange;
            toProto(message: _153.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _153.DescriptorProto_ExtensionRange): _153.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _153.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_153.DescriptorProto_ReservedRange>): _153.DescriptorProto_ReservedRange;
            fromAmino(object: _153.DescriptorProto_ReservedRangeAmino): _153.DescriptorProto_ReservedRange;
            toAmino(message: _153.DescriptorProto_ReservedRange): _153.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _153.DescriptorProto_ReservedRangeAminoMsg): _153.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _153.DescriptorProto_ReservedRangeProtoMsg): _153.DescriptorProto_ReservedRange;
            toProto(message: _153.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _153.DescriptorProto_ReservedRange): _153.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _153.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.ExtensionRangeOptions;
            fromPartial(object: Partial<_153.ExtensionRangeOptions>): _153.ExtensionRangeOptions;
            fromAmino(object: _153.ExtensionRangeOptionsAmino): _153.ExtensionRangeOptions;
            toAmino(message: _153.ExtensionRangeOptions): _153.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _153.ExtensionRangeOptionsAminoMsg): _153.ExtensionRangeOptions;
            fromProtoMsg(message: _153.ExtensionRangeOptionsProtoMsg): _153.ExtensionRangeOptions;
            toProto(message: _153.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _153.ExtensionRangeOptions): _153.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _153.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.FieldDescriptorProto;
            fromPartial(object: Partial<_153.FieldDescriptorProto>): _153.FieldDescriptorProto;
            fromAmino(object: _153.FieldDescriptorProtoAmino): _153.FieldDescriptorProto;
            toAmino(message: _153.FieldDescriptorProto): _153.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _153.FieldDescriptorProtoAminoMsg): _153.FieldDescriptorProto;
            fromProtoMsg(message: _153.FieldDescriptorProtoProtoMsg): _153.FieldDescriptorProto;
            toProto(message: _153.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _153.FieldDescriptorProto): _153.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _153.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.OneofDescriptorProto;
            fromPartial(object: Partial<_153.OneofDescriptorProto>): _153.OneofDescriptorProto;
            fromAmino(object: _153.OneofDescriptorProtoAmino): _153.OneofDescriptorProto;
            toAmino(message: _153.OneofDescriptorProto): _153.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _153.OneofDescriptorProtoAminoMsg): _153.OneofDescriptorProto;
            fromProtoMsg(message: _153.OneofDescriptorProtoProtoMsg): _153.OneofDescriptorProto;
            toProto(message: _153.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _153.OneofDescriptorProto): _153.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _153.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.EnumDescriptorProto;
            fromPartial(object: Partial<_153.EnumDescriptorProto>): _153.EnumDescriptorProto;
            fromAmino(object: _153.EnumDescriptorProtoAmino): _153.EnumDescriptorProto;
            toAmino(message: _153.EnumDescriptorProto): _153.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _153.EnumDescriptorProtoAminoMsg): _153.EnumDescriptorProto;
            fromProtoMsg(message: _153.EnumDescriptorProtoProtoMsg): _153.EnumDescriptorProto;
            toProto(message: _153.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _153.EnumDescriptorProto): _153.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _153.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_153.EnumDescriptorProto_EnumReservedRange>): _153.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _153.EnumDescriptorProto_EnumReservedRangeAmino): _153.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _153.EnumDescriptorProto_EnumReservedRange): _153.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _153.EnumDescriptorProto_EnumReservedRangeAminoMsg): _153.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _153.EnumDescriptorProto_EnumReservedRangeProtoMsg): _153.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _153.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _153.EnumDescriptorProto_EnumReservedRange): _153.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _153.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.EnumValueDescriptorProto;
            fromPartial(object: Partial<_153.EnumValueDescriptorProto>): _153.EnumValueDescriptorProto;
            fromAmino(object: _153.EnumValueDescriptorProtoAmino): _153.EnumValueDescriptorProto;
            toAmino(message: _153.EnumValueDescriptorProto): _153.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _153.EnumValueDescriptorProtoAminoMsg): _153.EnumValueDescriptorProto;
            fromProtoMsg(message: _153.EnumValueDescriptorProtoProtoMsg): _153.EnumValueDescriptorProto;
            toProto(message: _153.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _153.EnumValueDescriptorProto): _153.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _153.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.ServiceDescriptorProto;
            fromPartial(object: Partial<_153.ServiceDescriptorProto>): _153.ServiceDescriptorProto;
            fromAmino(object: _153.ServiceDescriptorProtoAmino): _153.ServiceDescriptorProto;
            toAmino(message: _153.ServiceDescriptorProto): _153.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _153.ServiceDescriptorProtoAminoMsg): _153.ServiceDescriptorProto;
            fromProtoMsg(message: _153.ServiceDescriptorProtoProtoMsg): _153.ServiceDescriptorProto;
            toProto(message: _153.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _153.ServiceDescriptorProto): _153.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _153.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.MethodDescriptorProto;
            fromPartial(object: Partial<_153.MethodDescriptorProto>): _153.MethodDescriptorProto;
            fromAmino(object: _153.MethodDescriptorProtoAmino): _153.MethodDescriptorProto;
            toAmino(message: _153.MethodDescriptorProto): _153.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _153.MethodDescriptorProtoAminoMsg): _153.MethodDescriptorProto;
            fromProtoMsg(message: _153.MethodDescriptorProtoProtoMsg): _153.MethodDescriptorProto;
            toProto(message: _153.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _153.MethodDescriptorProto): _153.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _153.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.FileOptions;
            fromPartial(object: Partial<_153.FileOptions>): _153.FileOptions;
            fromAmino(object: _153.FileOptionsAmino): _153.FileOptions;
            toAmino(message: _153.FileOptions): _153.FileOptionsAmino;
            fromAminoMsg(object: _153.FileOptionsAminoMsg): _153.FileOptions;
            fromProtoMsg(message: _153.FileOptionsProtoMsg): _153.FileOptions;
            toProto(message: _153.FileOptions): Uint8Array;
            toProtoMsg(message: _153.FileOptions): _153.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _153.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.MessageOptions;
            fromPartial(object: Partial<_153.MessageOptions>): _153.MessageOptions;
            fromAmino(object: _153.MessageOptionsAmino): _153.MessageOptions;
            toAmino(message: _153.MessageOptions): _153.MessageOptionsAmino;
            fromAminoMsg(object: _153.MessageOptionsAminoMsg): _153.MessageOptions;
            fromProtoMsg(message: _153.MessageOptionsProtoMsg): _153.MessageOptions;
            toProto(message: _153.MessageOptions): Uint8Array;
            toProtoMsg(message: _153.MessageOptions): _153.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _153.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.FieldOptions;
            fromPartial(object: Partial<_153.FieldOptions>): _153.FieldOptions;
            fromAmino(object: _153.FieldOptionsAmino): _153.FieldOptions;
            toAmino(message: _153.FieldOptions): _153.FieldOptionsAmino;
            fromAminoMsg(object: _153.FieldOptionsAminoMsg): _153.FieldOptions;
            fromProtoMsg(message: _153.FieldOptionsProtoMsg): _153.FieldOptions;
            toProto(message: _153.FieldOptions): Uint8Array;
            toProtoMsg(message: _153.FieldOptions): _153.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _153.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.OneofOptions;
            fromPartial(object: Partial<_153.OneofOptions>): _153.OneofOptions;
            fromAmino(object: _153.OneofOptionsAmino): _153.OneofOptions;
            toAmino(message: _153.OneofOptions): _153.OneofOptionsAmino;
            fromAminoMsg(object: _153.OneofOptionsAminoMsg): _153.OneofOptions;
            fromProtoMsg(message: _153.OneofOptionsProtoMsg): _153.OneofOptions;
            toProto(message: _153.OneofOptions): Uint8Array;
            toProtoMsg(message: _153.OneofOptions): _153.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _153.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.EnumOptions;
            fromPartial(object: Partial<_153.EnumOptions>): _153.EnumOptions;
            fromAmino(object: _153.EnumOptionsAmino): _153.EnumOptions;
            toAmino(message: _153.EnumOptions): _153.EnumOptionsAmino;
            fromAminoMsg(object: _153.EnumOptionsAminoMsg): _153.EnumOptions;
            fromProtoMsg(message: _153.EnumOptionsProtoMsg): _153.EnumOptions;
            toProto(message: _153.EnumOptions): Uint8Array;
            toProtoMsg(message: _153.EnumOptions): _153.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _153.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.EnumValueOptions;
            fromPartial(object: Partial<_153.EnumValueOptions>): _153.EnumValueOptions;
            fromAmino(object: _153.EnumValueOptionsAmino): _153.EnumValueOptions;
            toAmino(message: _153.EnumValueOptions): _153.EnumValueOptionsAmino;
            fromAminoMsg(object: _153.EnumValueOptionsAminoMsg): _153.EnumValueOptions;
            fromProtoMsg(message: _153.EnumValueOptionsProtoMsg): _153.EnumValueOptions;
            toProto(message: _153.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _153.EnumValueOptions): _153.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _153.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.ServiceOptions;
            fromPartial(object: Partial<_153.ServiceOptions>): _153.ServiceOptions;
            fromAmino(object: _153.ServiceOptionsAmino): _153.ServiceOptions;
            toAmino(message: _153.ServiceOptions): _153.ServiceOptionsAmino;
            fromAminoMsg(object: _153.ServiceOptionsAminoMsg): _153.ServiceOptions;
            fromProtoMsg(message: _153.ServiceOptionsProtoMsg): _153.ServiceOptions;
            toProto(message: _153.ServiceOptions): Uint8Array;
            toProtoMsg(message: _153.ServiceOptions): _153.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _153.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.MethodOptions;
            fromPartial(object: Partial<_153.MethodOptions>): _153.MethodOptions;
            fromAmino(object: _153.MethodOptionsAmino): _153.MethodOptions;
            toAmino(message: _153.MethodOptions): _153.MethodOptionsAmino;
            fromAminoMsg(object: _153.MethodOptionsAminoMsg): _153.MethodOptions;
            fromProtoMsg(message: _153.MethodOptionsProtoMsg): _153.MethodOptions;
            toProto(message: _153.MethodOptions): Uint8Array;
            toProtoMsg(message: _153.MethodOptions): _153.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _153.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.UninterpretedOption;
            fromPartial(object: Partial<_153.UninterpretedOption>): _153.UninterpretedOption;
            fromAmino(object: _153.UninterpretedOptionAmino): _153.UninterpretedOption;
            toAmino(message: _153.UninterpretedOption): _153.UninterpretedOptionAmino;
            fromAminoMsg(object: _153.UninterpretedOptionAminoMsg): _153.UninterpretedOption;
            fromProtoMsg(message: _153.UninterpretedOptionProtoMsg): _153.UninterpretedOption;
            toProto(message: _153.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _153.UninterpretedOption): _153.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _153.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_153.UninterpretedOption_NamePart>): _153.UninterpretedOption_NamePart;
            fromAmino(object: _153.UninterpretedOption_NamePartAmino): _153.UninterpretedOption_NamePart;
            toAmino(message: _153.UninterpretedOption_NamePart): _153.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _153.UninterpretedOption_NamePartAminoMsg): _153.UninterpretedOption_NamePart;
            fromProtoMsg(message: _153.UninterpretedOption_NamePartProtoMsg): _153.UninterpretedOption_NamePart;
            toProto(message: _153.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _153.UninterpretedOption_NamePart): _153.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _153.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.SourceCodeInfo;
            fromPartial(object: Partial<_153.SourceCodeInfo>): _153.SourceCodeInfo;
            fromAmino(object: _153.SourceCodeInfoAmino): _153.SourceCodeInfo;
            toAmino(message: _153.SourceCodeInfo): _153.SourceCodeInfoAmino;
            fromAminoMsg(object: _153.SourceCodeInfoAminoMsg): _153.SourceCodeInfo;
            fromProtoMsg(message: _153.SourceCodeInfoProtoMsg): _153.SourceCodeInfo;
            toProto(message: _153.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _153.SourceCodeInfo): _153.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _153.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.SourceCodeInfo_Location;
            fromPartial(object: Partial<_153.SourceCodeInfo_Location>): _153.SourceCodeInfo_Location;
            fromAmino(object: _153.SourceCodeInfo_LocationAmino): _153.SourceCodeInfo_Location;
            toAmino(message: _153.SourceCodeInfo_Location): _153.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _153.SourceCodeInfo_LocationAminoMsg): _153.SourceCodeInfo_Location;
            fromProtoMsg(message: _153.SourceCodeInfo_LocationProtoMsg): _153.SourceCodeInfo_Location;
            toProto(message: _153.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _153.SourceCodeInfo_Location): _153.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _153.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.GeneratedCodeInfo;
            fromPartial(object: Partial<_153.GeneratedCodeInfo>): _153.GeneratedCodeInfo;
            fromAmino(object: _153.GeneratedCodeInfoAmino): _153.GeneratedCodeInfo;
            toAmino(message: _153.GeneratedCodeInfo): _153.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _153.GeneratedCodeInfoAminoMsg): _153.GeneratedCodeInfo;
            fromProtoMsg(message: _153.GeneratedCodeInfoProtoMsg): _153.GeneratedCodeInfo;
            toProto(message: _153.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _153.GeneratedCodeInfo): _153.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _153.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_153.GeneratedCodeInfo_Annotation>): _153.GeneratedCodeInfo_Annotation;
            fromAmino(object: _153.GeneratedCodeInfo_AnnotationAmino): _153.GeneratedCodeInfo_Annotation;
            toAmino(message: _153.GeneratedCodeInfo_Annotation): _153.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _153.GeneratedCodeInfo_AnnotationAminoMsg): _153.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _153.GeneratedCodeInfo_AnnotationProtoMsg): _153.GeneratedCodeInfo_Annotation;
            toProto(message: _153.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _153.GeneratedCodeInfo_Annotation): _153.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _152.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.Duration;
            fromPartial(object: Partial<_152.Duration>): _152.Duration;
            fromAmino(object: string): _152.Duration;
            toAmino(message: _152.Duration): string;
            fromAminoMsg(object: _152.DurationAminoMsg): _152.Duration;
            fromProtoMsg(message: _152.DurationProtoMsg): _152.Duration;
            toProto(message: _152.Duration): Uint8Array;
            toProtoMsg(message: _152.Duration): _152.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _151.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _151.Timestamp;
            fromPartial(object: Partial<_151.Timestamp>): _151.Timestamp;
            fromAmino(object: string): _151.Timestamp;
            toAmino(message: _151.Timestamp): string;
            fromAminoMsg(object: _151.TimestampAminoMsg): _151.Timestamp;
            fromProtoMsg(message: _151.TimestampProtoMsg): _151.Timestamp;
            toProto(message: _151.Timestamp): Uint8Array;
            toProtoMsg(message: _151.Timestamp): _151.TimestampProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _150.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.Any;
            fromPartial(object: Partial<_150.Any>): _150.Any;
            fromAmino(object: _150.AnyAmino): _150.Any;
            toAmino(message: _150.Any): _150.AnyAmino;
            fromAminoMsg(object: _150.AnyAminoMsg): _150.Any;
            fromProtoMsg(message: _150.AnyProtoMsg): _150.Any;
            toProto(message: _150.Any): Uint8Array;
            toProtoMsg(message: _150.Any): _150.AnyProtoMsg;
        };
    };
}
