import * as _81 from "./api/http";
import * as _82 from "./api/httpbody";
import * as _83 from "./protobuf/any";
import * as _84 from "./protobuf/descriptor";
import * as _85 from "./protobuf/timestamp";
import * as _86 from "./protobuf/duration";
export declare namespace google {
    const api: {
        HttpBody: {
            typeUrl: string;
            encode(message: _82.HttpBody, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _82.HttpBody;
            fromPartial(object: Partial<_82.HttpBody>): _82.HttpBody;
            fromAmino(object: _82.HttpBodyAmino): _82.HttpBody;
            toAmino(message: _82.HttpBody): _82.HttpBodyAmino;
            fromAminoMsg(object: _82.HttpBodyAminoMsg): _82.HttpBody;
            fromProtoMsg(message: _82.HttpBodyProtoMsg): _82.HttpBody;
            toProto(message: _82.HttpBody): Uint8Array;
            toProtoMsg(message: _82.HttpBody): _82.HttpBodyProtoMsg;
        };
        Http: {
            typeUrl: string;
            encode(message: _81.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _81.Http;
            fromPartial(object: Partial<_81.Http>): _81.Http;
            fromAmino(object: _81.HttpAmino): _81.Http;
            toAmino(message: _81.Http): _81.HttpAmino;
            fromAminoMsg(object: _81.HttpAminoMsg): _81.Http;
            fromProtoMsg(message: _81.HttpProtoMsg): _81.Http;
            toProto(message: _81.Http): Uint8Array;
            toProtoMsg(message: _81.Http): _81.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _81.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _81.HttpRule;
            fromPartial(object: Partial<_81.HttpRule>): _81.HttpRule;
            fromAmino(object: _81.HttpRuleAmino): _81.HttpRule;
            toAmino(message: _81.HttpRule): _81.HttpRuleAmino;
            fromAminoMsg(object: _81.HttpRuleAminoMsg): _81.HttpRule;
            fromProtoMsg(message: _81.HttpRuleProtoMsg): _81.HttpRule;
            toProto(message: _81.HttpRule): Uint8Array;
            toProtoMsg(message: _81.HttpRule): _81.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _81.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _81.CustomHttpPattern;
            fromPartial(object: Partial<_81.CustomHttpPattern>): _81.CustomHttpPattern;
            fromAmino(object: _81.CustomHttpPatternAmino): _81.CustomHttpPattern;
            toAmino(message: _81.CustomHttpPattern): _81.CustomHttpPatternAmino;
            fromAminoMsg(object: _81.CustomHttpPatternAminoMsg): _81.CustomHttpPattern;
            fromProtoMsg(message: _81.CustomHttpPatternProtoMsg): _81.CustomHttpPattern;
            toProto(message: _81.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _81.CustomHttpPattern): _81.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Duration: {
            typeUrl: string;
            encode(message: _86.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _86.Duration;
            fromPartial(object: Partial<_86.Duration>): _86.Duration;
            fromAmino(object: string): _86.Duration;
            toAmino(message: _86.Duration): string;
            fromAminoMsg(object: _86.DurationAminoMsg): _86.Duration;
            fromProtoMsg(message: _86.DurationProtoMsg): _86.Duration;
            toProto(message: _86.Duration): Uint8Array;
            toProtoMsg(message: _86.Duration): _86.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _85.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.Timestamp;
            fromPartial(object: Partial<_85.Timestamp>): _85.Timestamp;
            fromAmino(object: string): _85.Timestamp;
            toAmino(message: _85.Timestamp): string;
            fromAminoMsg(object: _85.TimestampAminoMsg): _85.Timestamp;
            fromProtoMsg(message: _85.TimestampProtoMsg): _85.Timestamp;
            toProto(message: _85.Timestamp): Uint8Array;
            toProtoMsg(message: _85.Timestamp): _85.TimestampProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _84.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _84.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _84.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _84.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _84.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _84.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _84.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _84.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _84.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _84.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _84.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _84.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _84.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _84.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _84.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _84.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _84.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _84.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _84.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _84.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _84.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _84.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _84.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _84.FieldOptions_CType;
        FieldOptions_JSType: typeof _84.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _84.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _84.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _84.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _84.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _84.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _84.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.FileDescriptorSet;
            fromPartial(object: Partial<_84.FileDescriptorSet>): _84.FileDescriptorSet;
            fromAmino(object: _84.FileDescriptorSetAmino): _84.FileDescriptorSet;
            toAmino(message: _84.FileDescriptorSet): _84.FileDescriptorSetAmino;
            fromAminoMsg(object: _84.FileDescriptorSetAminoMsg): _84.FileDescriptorSet;
            fromProtoMsg(message: _84.FileDescriptorSetProtoMsg): _84.FileDescriptorSet;
            toProto(message: _84.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _84.FileDescriptorSet): _84.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _84.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.FileDescriptorProto;
            fromPartial(object: Partial<_84.FileDescriptorProto>): _84.FileDescriptorProto;
            fromAmino(object: _84.FileDescriptorProtoAmino): _84.FileDescriptorProto;
            toAmino(message: _84.FileDescriptorProto): _84.FileDescriptorProtoAmino;
            fromAminoMsg(object: _84.FileDescriptorProtoAminoMsg): _84.FileDescriptorProto;
            fromProtoMsg(message: _84.FileDescriptorProtoProtoMsg): _84.FileDescriptorProto;
            toProto(message: _84.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _84.FileDescriptorProto): _84.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _84.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.DescriptorProto;
            fromPartial(object: Partial<_84.DescriptorProto>): _84.DescriptorProto;
            fromAmino(object: _84.DescriptorProtoAmino): _84.DescriptorProto;
            toAmino(message: _84.DescriptorProto): _84.DescriptorProtoAmino;
            fromAminoMsg(object: _84.DescriptorProtoAminoMsg): _84.DescriptorProto;
            fromProtoMsg(message: _84.DescriptorProtoProtoMsg): _84.DescriptorProto;
            toProto(message: _84.DescriptorProto): Uint8Array;
            toProtoMsg(message: _84.DescriptorProto): _84.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _84.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_84.DescriptorProto_ExtensionRange>): _84.DescriptorProto_ExtensionRange;
            fromAmino(object: _84.DescriptorProto_ExtensionRangeAmino): _84.DescriptorProto_ExtensionRange;
            toAmino(message: _84.DescriptorProto_ExtensionRange): _84.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _84.DescriptorProto_ExtensionRangeAminoMsg): _84.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _84.DescriptorProto_ExtensionRangeProtoMsg): _84.DescriptorProto_ExtensionRange;
            toProto(message: _84.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _84.DescriptorProto_ExtensionRange): _84.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _84.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_84.DescriptorProto_ReservedRange>): _84.DescriptorProto_ReservedRange;
            fromAmino(object: _84.DescriptorProto_ReservedRangeAmino): _84.DescriptorProto_ReservedRange;
            toAmino(message: _84.DescriptorProto_ReservedRange): _84.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _84.DescriptorProto_ReservedRangeAminoMsg): _84.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _84.DescriptorProto_ReservedRangeProtoMsg): _84.DescriptorProto_ReservedRange;
            toProto(message: _84.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _84.DescriptorProto_ReservedRange): _84.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _84.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.ExtensionRangeOptions;
            fromPartial(object: Partial<_84.ExtensionRangeOptions>): _84.ExtensionRangeOptions;
            fromAmino(object: _84.ExtensionRangeOptionsAmino): _84.ExtensionRangeOptions;
            toAmino(message: _84.ExtensionRangeOptions): _84.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _84.ExtensionRangeOptionsAminoMsg): _84.ExtensionRangeOptions;
            fromProtoMsg(message: _84.ExtensionRangeOptionsProtoMsg): _84.ExtensionRangeOptions;
            toProto(message: _84.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _84.ExtensionRangeOptions): _84.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _84.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.FieldDescriptorProto;
            fromPartial(object: Partial<_84.FieldDescriptorProto>): _84.FieldDescriptorProto;
            fromAmino(object: _84.FieldDescriptorProtoAmino): _84.FieldDescriptorProto;
            toAmino(message: _84.FieldDescriptorProto): _84.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _84.FieldDescriptorProtoAminoMsg): _84.FieldDescriptorProto;
            fromProtoMsg(message: _84.FieldDescriptorProtoProtoMsg): _84.FieldDescriptorProto;
            toProto(message: _84.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _84.FieldDescriptorProto): _84.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _84.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.OneofDescriptorProto;
            fromPartial(object: Partial<_84.OneofDescriptorProto>): _84.OneofDescriptorProto;
            fromAmino(object: _84.OneofDescriptorProtoAmino): _84.OneofDescriptorProto;
            toAmino(message: _84.OneofDescriptorProto): _84.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _84.OneofDescriptorProtoAminoMsg): _84.OneofDescriptorProto;
            fromProtoMsg(message: _84.OneofDescriptorProtoProtoMsg): _84.OneofDescriptorProto;
            toProto(message: _84.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _84.OneofDescriptorProto): _84.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _84.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.EnumDescriptorProto;
            fromPartial(object: Partial<_84.EnumDescriptorProto>): _84.EnumDescriptorProto;
            fromAmino(object: _84.EnumDescriptorProtoAmino): _84.EnumDescriptorProto;
            toAmino(message: _84.EnumDescriptorProto): _84.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _84.EnumDescriptorProtoAminoMsg): _84.EnumDescriptorProto;
            fromProtoMsg(message: _84.EnumDescriptorProtoProtoMsg): _84.EnumDescriptorProto;
            toProto(message: _84.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _84.EnumDescriptorProto): _84.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _84.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_84.EnumDescriptorProto_EnumReservedRange>): _84.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _84.EnumDescriptorProto_EnumReservedRangeAmino): _84.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _84.EnumDescriptorProto_EnumReservedRange): _84.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _84.EnumDescriptorProto_EnumReservedRangeAminoMsg): _84.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _84.EnumDescriptorProto_EnumReservedRangeProtoMsg): _84.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _84.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _84.EnumDescriptorProto_EnumReservedRange): _84.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _84.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.EnumValueDescriptorProto;
            fromPartial(object: Partial<_84.EnumValueDescriptorProto>): _84.EnumValueDescriptorProto;
            fromAmino(object: _84.EnumValueDescriptorProtoAmino): _84.EnumValueDescriptorProto;
            toAmino(message: _84.EnumValueDescriptorProto): _84.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _84.EnumValueDescriptorProtoAminoMsg): _84.EnumValueDescriptorProto;
            fromProtoMsg(message: _84.EnumValueDescriptorProtoProtoMsg): _84.EnumValueDescriptorProto;
            toProto(message: _84.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _84.EnumValueDescriptorProto): _84.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _84.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.ServiceDescriptorProto;
            fromPartial(object: Partial<_84.ServiceDescriptorProto>): _84.ServiceDescriptorProto;
            fromAmino(object: _84.ServiceDescriptorProtoAmino): _84.ServiceDescriptorProto;
            toAmino(message: _84.ServiceDescriptorProto): _84.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _84.ServiceDescriptorProtoAminoMsg): _84.ServiceDescriptorProto;
            fromProtoMsg(message: _84.ServiceDescriptorProtoProtoMsg): _84.ServiceDescriptorProto;
            toProto(message: _84.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _84.ServiceDescriptorProto): _84.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _84.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.MethodDescriptorProto;
            fromPartial(object: Partial<_84.MethodDescriptorProto>): _84.MethodDescriptorProto;
            fromAmino(object: _84.MethodDescriptorProtoAmino): _84.MethodDescriptorProto;
            toAmino(message: _84.MethodDescriptorProto): _84.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _84.MethodDescriptorProtoAminoMsg): _84.MethodDescriptorProto;
            fromProtoMsg(message: _84.MethodDescriptorProtoProtoMsg): _84.MethodDescriptorProto;
            toProto(message: _84.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _84.MethodDescriptorProto): _84.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _84.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.FileOptions;
            fromPartial(object: Partial<_84.FileOptions>): _84.FileOptions;
            fromAmino(object: _84.FileOptionsAmino): _84.FileOptions;
            toAmino(message: _84.FileOptions): _84.FileOptionsAmino;
            fromAminoMsg(object: _84.FileOptionsAminoMsg): _84.FileOptions;
            fromProtoMsg(message: _84.FileOptionsProtoMsg): _84.FileOptions;
            toProto(message: _84.FileOptions): Uint8Array;
            toProtoMsg(message: _84.FileOptions): _84.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _84.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.MessageOptions;
            fromPartial(object: Partial<_84.MessageOptions>): _84.MessageOptions;
            fromAmino(object: _84.MessageOptionsAmino): _84.MessageOptions;
            toAmino(message: _84.MessageOptions): _84.MessageOptionsAmino;
            fromAminoMsg(object: _84.MessageOptionsAminoMsg): _84.MessageOptions;
            fromProtoMsg(message: _84.MessageOptionsProtoMsg): _84.MessageOptions;
            toProto(message: _84.MessageOptions): Uint8Array;
            toProtoMsg(message: _84.MessageOptions): _84.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _84.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.FieldOptions;
            fromPartial(object: Partial<_84.FieldOptions>): _84.FieldOptions;
            fromAmino(object: _84.FieldOptionsAmino): _84.FieldOptions;
            toAmino(message: _84.FieldOptions): _84.FieldOptionsAmino;
            fromAminoMsg(object: _84.FieldOptionsAminoMsg): _84.FieldOptions;
            fromProtoMsg(message: _84.FieldOptionsProtoMsg): _84.FieldOptions;
            toProto(message: _84.FieldOptions): Uint8Array;
            toProtoMsg(message: _84.FieldOptions): _84.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _84.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.OneofOptions;
            fromPartial(object: Partial<_84.OneofOptions>): _84.OneofOptions;
            fromAmino(object: _84.OneofOptionsAmino): _84.OneofOptions;
            toAmino(message: _84.OneofOptions): _84.OneofOptionsAmino;
            fromAminoMsg(object: _84.OneofOptionsAminoMsg): _84.OneofOptions;
            fromProtoMsg(message: _84.OneofOptionsProtoMsg): _84.OneofOptions;
            toProto(message: _84.OneofOptions): Uint8Array;
            toProtoMsg(message: _84.OneofOptions): _84.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _84.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.EnumOptions;
            fromPartial(object: Partial<_84.EnumOptions>): _84.EnumOptions;
            fromAmino(object: _84.EnumOptionsAmino): _84.EnumOptions;
            toAmino(message: _84.EnumOptions): _84.EnumOptionsAmino;
            fromAminoMsg(object: _84.EnumOptionsAminoMsg): _84.EnumOptions;
            fromProtoMsg(message: _84.EnumOptionsProtoMsg): _84.EnumOptions;
            toProto(message: _84.EnumOptions): Uint8Array;
            toProtoMsg(message: _84.EnumOptions): _84.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _84.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.EnumValueOptions;
            fromPartial(object: Partial<_84.EnumValueOptions>): _84.EnumValueOptions;
            fromAmino(object: _84.EnumValueOptionsAmino): _84.EnumValueOptions;
            toAmino(message: _84.EnumValueOptions): _84.EnumValueOptionsAmino;
            fromAminoMsg(object: _84.EnumValueOptionsAminoMsg): _84.EnumValueOptions;
            fromProtoMsg(message: _84.EnumValueOptionsProtoMsg): _84.EnumValueOptions;
            toProto(message: _84.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _84.EnumValueOptions): _84.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _84.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.ServiceOptions;
            fromPartial(object: Partial<_84.ServiceOptions>): _84.ServiceOptions;
            fromAmino(object: _84.ServiceOptionsAmino): _84.ServiceOptions;
            toAmino(message: _84.ServiceOptions): _84.ServiceOptionsAmino;
            fromAminoMsg(object: _84.ServiceOptionsAminoMsg): _84.ServiceOptions;
            fromProtoMsg(message: _84.ServiceOptionsProtoMsg): _84.ServiceOptions;
            toProto(message: _84.ServiceOptions): Uint8Array;
            toProtoMsg(message: _84.ServiceOptions): _84.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _84.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.MethodOptions;
            fromPartial(object: Partial<_84.MethodOptions>): _84.MethodOptions;
            fromAmino(object: _84.MethodOptionsAmino): _84.MethodOptions;
            toAmino(message: _84.MethodOptions): _84.MethodOptionsAmino;
            fromAminoMsg(object: _84.MethodOptionsAminoMsg): _84.MethodOptions;
            fromProtoMsg(message: _84.MethodOptionsProtoMsg): _84.MethodOptions;
            toProto(message: _84.MethodOptions): Uint8Array;
            toProtoMsg(message: _84.MethodOptions): _84.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _84.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.UninterpretedOption;
            fromPartial(object: Partial<_84.UninterpretedOption>): _84.UninterpretedOption;
            fromAmino(object: _84.UninterpretedOptionAmino): _84.UninterpretedOption;
            toAmino(message: _84.UninterpretedOption): _84.UninterpretedOptionAmino;
            fromAminoMsg(object: _84.UninterpretedOptionAminoMsg): _84.UninterpretedOption;
            fromProtoMsg(message: _84.UninterpretedOptionProtoMsg): _84.UninterpretedOption;
            toProto(message: _84.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _84.UninterpretedOption): _84.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _84.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_84.UninterpretedOption_NamePart>): _84.UninterpretedOption_NamePart;
            fromAmino(object: _84.UninterpretedOption_NamePartAmino): _84.UninterpretedOption_NamePart;
            toAmino(message: _84.UninterpretedOption_NamePart): _84.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _84.UninterpretedOption_NamePartAminoMsg): _84.UninterpretedOption_NamePart;
            fromProtoMsg(message: _84.UninterpretedOption_NamePartProtoMsg): _84.UninterpretedOption_NamePart;
            toProto(message: _84.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _84.UninterpretedOption_NamePart): _84.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _84.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.SourceCodeInfo;
            fromPartial(object: Partial<_84.SourceCodeInfo>): _84.SourceCodeInfo;
            fromAmino(object: _84.SourceCodeInfoAmino): _84.SourceCodeInfo;
            toAmino(message: _84.SourceCodeInfo): _84.SourceCodeInfoAmino;
            fromAminoMsg(object: _84.SourceCodeInfoAminoMsg): _84.SourceCodeInfo;
            fromProtoMsg(message: _84.SourceCodeInfoProtoMsg): _84.SourceCodeInfo;
            toProto(message: _84.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _84.SourceCodeInfo): _84.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _84.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.SourceCodeInfo_Location;
            fromPartial(object: Partial<_84.SourceCodeInfo_Location>): _84.SourceCodeInfo_Location;
            fromAmino(object: _84.SourceCodeInfo_LocationAmino): _84.SourceCodeInfo_Location;
            toAmino(message: _84.SourceCodeInfo_Location): _84.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _84.SourceCodeInfo_LocationAminoMsg): _84.SourceCodeInfo_Location;
            fromProtoMsg(message: _84.SourceCodeInfo_LocationProtoMsg): _84.SourceCodeInfo_Location;
            toProto(message: _84.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _84.SourceCodeInfo_Location): _84.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _84.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.GeneratedCodeInfo;
            fromPartial(object: Partial<_84.GeneratedCodeInfo>): _84.GeneratedCodeInfo;
            fromAmino(object: _84.GeneratedCodeInfoAmino): _84.GeneratedCodeInfo;
            toAmino(message: _84.GeneratedCodeInfo): _84.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _84.GeneratedCodeInfoAminoMsg): _84.GeneratedCodeInfo;
            fromProtoMsg(message: _84.GeneratedCodeInfoProtoMsg): _84.GeneratedCodeInfo;
            toProto(message: _84.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _84.GeneratedCodeInfo): _84.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _84.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_84.GeneratedCodeInfo_Annotation>): _84.GeneratedCodeInfo_Annotation;
            fromAmino(object: _84.GeneratedCodeInfo_AnnotationAmino): _84.GeneratedCodeInfo_Annotation;
            toAmino(message: _84.GeneratedCodeInfo_Annotation): _84.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _84.GeneratedCodeInfo_AnnotationAminoMsg): _84.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _84.GeneratedCodeInfo_AnnotationProtoMsg): _84.GeneratedCodeInfo_Annotation;
            toProto(message: _84.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _84.GeneratedCodeInfo_Annotation): _84.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _83.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _83.Any;
            fromPartial(object: Partial<_83.Any>): _83.Any;
            fromAmino(object: _83.AnyAmino): _83.Any;
            toAmino(message: _83.Any): _83.AnyAmino;
            fromAminoMsg(object: _83.AnyAminoMsg): _83.Any;
            fromProtoMsg(message: _83.AnyProtoMsg): _83.Any;
            toProto(message: _83.Any): Uint8Array;
            toProtoMsg(message: _83.Any): _83.AnyProtoMsg;
        };
    };
}
