import * as _98 from "./abci/types";
import * as _99 from "./crypto/keys";
import * as _100 from "./crypto/proof";
import * as _101 from "./libs/bits/types";
import * as _102 from "./p2p/types";
import * as _103 from "./types/block";
import * as _104 from "./types/evidence";
import * as _105 from "./types/params";
import * as _106 from "./types/types";
import * as _107 from "./types/validator";
import * as _108 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _98.CheckTxType;
        checkTxTypeToJSON(object: _98.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _98.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _98.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _98.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _98.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _98.EvidenceType;
        evidenceTypeToJSON(object: _98.EvidenceType): string;
        CheckTxType: typeof _98.CheckTxType;
        CheckTxTypeSDKType: typeof _98.CheckTxType;
        CheckTxTypeAmino: typeof _98.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _98.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _98.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _98.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _98.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _98.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _98.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _98.EvidenceType;
        EvidenceTypeSDKType: typeof _98.EvidenceType;
        EvidenceTypeAmino: typeof _98.EvidenceType;
        Request: {
            typeUrl: string;
            encode(message: _98.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.Request;
            fromPartial(object: Partial<_98.Request>): _98.Request;
            fromAmino(object: _98.RequestAmino): _98.Request;
            toAmino(message: _98.Request): _98.RequestAmino;
            fromAminoMsg(object: _98.RequestAminoMsg): _98.Request;
            fromProtoMsg(message: _98.RequestProtoMsg): _98.Request;
            toProto(message: _98.Request): Uint8Array;
            toProtoMsg(message: _98.Request): _98.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _98.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.RequestEcho;
            fromPartial(object: Partial<_98.RequestEcho>): _98.RequestEcho;
            fromAmino(object: _98.RequestEchoAmino): _98.RequestEcho;
            toAmino(message: _98.RequestEcho): _98.RequestEchoAmino;
            fromAminoMsg(object: _98.RequestEchoAminoMsg): _98.RequestEcho;
            fromProtoMsg(message: _98.RequestEchoProtoMsg): _98.RequestEcho;
            toProto(message: _98.RequestEcho): Uint8Array;
            toProtoMsg(message: _98.RequestEcho): _98.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _98.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _98.RequestFlush;
            fromPartial(_: Partial<_98.RequestFlush>): _98.RequestFlush;
            fromAmino(_: _98.RequestFlushAmino): _98.RequestFlush;
            toAmino(_: _98.RequestFlush): _98.RequestFlushAmino;
            fromAminoMsg(object: _98.RequestFlushAminoMsg): _98.RequestFlush;
            fromProtoMsg(message: _98.RequestFlushProtoMsg): _98.RequestFlush;
            toProto(message: _98.RequestFlush): Uint8Array;
            toProtoMsg(message: _98.RequestFlush): _98.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _98.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.RequestInfo;
            fromPartial(object: Partial<_98.RequestInfo>): _98.RequestInfo;
            fromAmino(object: _98.RequestInfoAmino): _98.RequestInfo;
            toAmino(message: _98.RequestInfo): _98.RequestInfoAmino;
            fromAminoMsg(object: _98.RequestInfoAminoMsg): _98.RequestInfo;
            fromProtoMsg(message: _98.RequestInfoProtoMsg): _98.RequestInfo;
            toProto(message: _98.RequestInfo): Uint8Array;
            toProtoMsg(message: _98.RequestInfo): _98.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            typeUrl: string;
            encode(message: _98.RequestSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.RequestSetOption;
            fromPartial(object: Partial<_98.RequestSetOption>): _98.RequestSetOption;
            fromAmino(object: _98.RequestSetOptionAmino): _98.RequestSetOption;
            toAmino(message: _98.RequestSetOption): _98.RequestSetOptionAmino;
            fromAminoMsg(object: _98.RequestSetOptionAminoMsg): _98.RequestSetOption;
            fromProtoMsg(message: _98.RequestSetOptionProtoMsg): _98.RequestSetOption;
            toProto(message: _98.RequestSetOption): Uint8Array;
            toProtoMsg(message: _98.RequestSetOption): _98.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _98.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.RequestInitChain;
            fromPartial(object: Partial<_98.RequestInitChain>): _98.RequestInitChain;
            fromAmino(object: _98.RequestInitChainAmino): _98.RequestInitChain;
            toAmino(message: _98.RequestInitChain): _98.RequestInitChainAmino;
            fromAminoMsg(object: _98.RequestInitChainAminoMsg): _98.RequestInitChain;
            fromProtoMsg(message: _98.RequestInitChainProtoMsg): _98.RequestInitChain;
            toProto(message: _98.RequestInitChain): Uint8Array;
            toProtoMsg(message: _98.RequestInitChain): _98.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _98.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.RequestQuery;
            fromPartial(object: Partial<_98.RequestQuery>): _98.RequestQuery;
            fromAmino(object: _98.RequestQueryAmino): _98.RequestQuery;
            toAmino(message: _98.RequestQuery): _98.RequestQueryAmino;
            fromAminoMsg(object: _98.RequestQueryAminoMsg): _98.RequestQuery;
            fromProtoMsg(message: _98.RequestQueryProtoMsg): _98.RequestQuery;
            toProto(message: _98.RequestQuery): Uint8Array;
            toProtoMsg(message: _98.RequestQuery): _98.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _98.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.RequestBeginBlock;
            fromPartial(object: Partial<_98.RequestBeginBlock>): _98.RequestBeginBlock;
            fromAmino(object: _98.RequestBeginBlockAmino): _98.RequestBeginBlock;
            toAmino(message: _98.RequestBeginBlock): _98.RequestBeginBlockAmino;
            fromAminoMsg(object: _98.RequestBeginBlockAminoMsg): _98.RequestBeginBlock;
            fromProtoMsg(message: _98.RequestBeginBlockProtoMsg): _98.RequestBeginBlock;
            toProto(message: _98.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _98.RequestBeginBlock): _98.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _98.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.RequestCheckTx;
            fromPartial(object: Partial<_98.RequestCheckTx>): _98.RequestCheckTx;
            fromAmino(object: _98.RequestCheckTxAmino): _98.RequestCheckTx;
            toAmino(message: _98.RequestCheckTx): _98.RequestCheckTxAmino;
            fromAminoMsg(object: _98.RequestCheckTxAminoMsg): _98.RequestCheckTx;
            fromProtoMsg(message: _98.RequestCheckTxProtoMsg): _98.RequestCheckTx;
            toProto(message: _98.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _98.RequestCheckTx): _98.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _98.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.RequestDeliverTx;
            fromPartial(object: Partial<_98.RequestDeliverTx>): _98.RequestDeliverTx;
            fromAmino(object: _98.RequestDeliverTxAmino): _98.RequestDeliverTx;
            toAmino(message: _98.RequestDeliverTx): _98.RequestDeliverTxAmino;
            fromAminoMsg(object: _98.RequestDeliverTxAminoMsg): _98.RequestDeliverTx;
            fromProtoMsg(message: _98.RequestDeliverTxProtoMsg): _98.RequestDeliverTx;
            toProto(message: _98.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _98.RequestDeliverTx): _98.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _98.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.RequestEndBlock;
            fromPartial(object: Partial<_98.RequestEndBlock>): _98.RequestEndBlock;
            fromAmino(object: _98.RequestEndBlockAmino): _98.RequestEndBlock;
            toAmino(message: _98.RequestEndBlock): _98.RequestEndBlockAmino;
            fromAminoMsg(object: _98.RequestEndBlockAminoMsg): _98.RequestEndBlock;
            fromProtoMsg(message: _98.RequestEndBlockProtoMsg): _98.RequestEndBlock;
            toProto(message: _98.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _98.RequestEndBlock): _98.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _98.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _98.RequestCommit;
            fromPartial(_: Partial<_98.RequestCommit>): _98.RequestCommit;
            fromAmino(_: _98.RequestCommitAmino): _98.RequestCommit;
            toAmino(_: _98.RequestCommit): _98.RequestCommitAmino;
            fromAminoMsg(object: _98.RequestCommitAminoMsg): _98.RequestCommit;
            fromProtoMsg(message: _98.RequestCommitProtoMsg): _98.RequestCommit;
            toProto(message: _98.RequestCommit): Uint8Array;
            toProtoMsg(message: _98.RequestCommit): _98.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _98.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _98.RequestListSnapshots;
            fromPartial(_: Partial<_98.RequestListSnapshots>): _98.RequestListSnapshots;
            fromAmino(_: _98.RequestListSnapshotsAmino): _98.RequestListSnapshots;
            toAmino(_: _98.RequestListSnapshots): _98.RequestListSnapshotsAmino;
            fromAminoMsg(object: _98.RequestListSnapshotsAminoMsg): _98.RequestListSnapshots;
            fromProtoMsg(message: _98.RequestListSnapshotsProtoMsg): _98.RequestListSnapshots;
            toProto(message: _98.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _98.RequestListSnapshots): _98.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _98.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.RequestOfferSnapshot;
            fromPartial(object: Partial<_98.RequestOfferSnapshot>): _98.RequestOfferSnapshot;
            fromAmino(object: _98.RequestOfferSnapshotAmino): _98.RequestOfferSnapshot;
            toAmino(message: _98.RequestOfferSnapshot): _98.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _98.RequestOfferSnapshotAminoMsg): _98.RequestOfferSnapshot;
            fromProtoMsg(message: _98.RequestOfferSnapshotProtoMsg): _98.RequestOfferSnapshot;
            toProto(message: _98.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _98.RequestOfferSnapshot): _98.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _98.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_98.RequestLoadSnapshotChunk>): _98.RequestLoadSnapshotChunk;
            fromAmino(object: _98.RequestLoadSnapshotChunkAmino): _98.RequestLoadSnapshotChunk;
            toAmino(message: _98.RequestLoadSnapshotChunk): _98.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _98.RequestLoadSnapshotChunkAminoMsg): _98.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _98.RequestLoadSnapshotChunkProtoMsg): _98.RequestLoadSnapshotChunk;
            toProto(message: _98.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _98.RequestLoadSnapshotChunk): _98.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _98.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_98.RequestApplySnapshotChunk>): _98.RequestApplySnapshotChunk;
            fromAmino(object: _98.RequestApplySnapshotChunkAmino): _98.RequestApplySnapshotChunk;
            toAmino(message: _98.RequestApplySnapshotChunk): _98.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _98.RequestApplySnapshotChunkAminoMsg): _98.RequestApplySnapshotChunk;
            fromProtoMsg(message: _98.RequestApplySnapshotChunkProtoMsg): _98.RequestApplySnapshotChunk;
            toProto(message: _98.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _98.RequestApplySnapshotChunk): _98.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _98.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.Response;
            fromPartial(object: Partial<_98.Response>): _98.Response;
            fromAmino(object: _98.ResponseAmino): _98.Response;
            toAmino(message: _98.Response): _98.ResponseAmino;
            fromAminoMsg(object: _98.ResponseAminoMsg): _98.Response;
            fromProtoMsg(message: _98.ResponseProtoMsg): _98.Response;
            toProto(message: _98.Response): Uint8Array;
            toProtoMsg(message: _98.Response): _98.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _98.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseException;
            fromPartial(object: Partial<_98.ResponseException>): _98.ResponseException;
            fromAmino(object: _98.ResponseExceptionAmino): _98.ResponseException;
            toAmino(message: _98.ResponseException): _98.ResponseExceptionAmino;
            fromAminoMsg(object: _98.ResponseExceptionAminoMsg): _98.ResponseException;
            fromProtoMsg(message: _98.ResponseExceptionProtoMsg): _98.ResponseException;
            toProto(message: _98.ResponseException): Uint8Array;
            toProtoMsg(message: _98.ResponseException): _98.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _98.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseEcho;
            fromPartial(object: Partial<_98.ResponseEcho>): _98.ResponseEcho;
            fromAmino(object: _98.ResponseEchoAmino): _98.ResponseEcho;
            toAmino(message: _98.ResponseEcho): _98.ResponseEchoAmino;
            fromAminoMsg(object: _98.ResponseEchoAminoMsg): _98.ResponseEcho;
            fromProtoMsg(message: _98.ResponseEchoProtoMsg): _98.ResponseEcho;
            toProto(message: _98.ResponseEcho): Uint8Array;
            toProtoMsg(message: _98.ResponseEcho): _98.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _98.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _98.ResponseFlush;
            fromPartial(_: Partial<_98.ResponseFlush>): _98.ResponseFlush;
            fromAmino(_: _98.ResponseFlushAmino): _98.ResponseFlush;
            toAmino(_: _98.ResponseFlush): _98.ResponseFlushAmino;
            fromAminoMsg(object: _98.ResponseFlushAminoMsg): _98.ResponseFlush;
            fromProtoMsg(message: _98.ResponseFlushProtoMsg): _98.ResponseFlush;
            toProto(message: _98.ResponseFlush): Uint8Array;
            toProtoMsg(message: _98.ResponseFlush): _98.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _98.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseInfo;
            fromPartial(object: Partial<_98.ResponseInfo>): _98.ResponseInfo;
            fromAmino(object: _98.ResponseInfoAmino): _98.ResponseInfo;
            toAmino(message: _98.ResponseInfo): _98.ResponseInfoAmino;
            fromAminoMsg(object: _98.ResponseInfoAminoMsg): _98.ResponseInfo;
            fromProtoMsg(message: _98.ResponseInfoProtoMsg): _98.ResponseInfo;
            toProto(message: _98.ResponseInfo): Uint8Array;
            toProtoMsg(message: _98.ResponseInfo): _98.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            typeUrl: string;
            encode(message: _98.ResponseSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseSetOption;
            fromPartial(object: Partial<_98.ResponseSetOption>): _98.ResponseSetOption;
            fromAmino(object: _98.ResponseSetOptionAmino): _98.ResponseSetOption;
            toAmino(message: _98.ResponseSetOption): _98.ResponseSetOptionAmino;
            fromAminoMsg(object: _98.ResponseSetOptionAminoMsg): _98.ResponseSetOption;
            fromProtoMsg(message: _98.ResponseSetOptionProtoMsg): _98.ResponseSetOption;
            toProto(message: _98.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _98.ResponseSetOption): _98.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _98.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseInitChain;
            fromPartial(object: Partial<_98.ResponseInitChain>): _98.ResponseInitChain;
            fromAmino(object: _98.ResponseInitChainAmino): _98.ResponseInitChain;
            toAmino(message: _98.ResponseInitChain): _98.ResponseInitChainAmino;
            fromAminoMsg(object: _98.ResponseInitChainAminoMsg): _98.ResponseInitChain;
            fromProtoMsg(message: _98.ResponseInitChainProtoMsg): _98.ResponseInitChain;
            toProto(message: _98.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _98.ResponseInitChain): _98.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _98.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseQuery;
            fromPartial(object: Partial<_98.ResponseQuery>): _98.ResponseQuery;
            fromAmino(object: _98.ResponseQueryAmino): _98.ResponseQuery;
            toAmino(message: _98.ResponseQuery): _98.ResponseQueryAmino;
            fromAminoMsg(object: _98.ResponseQueryAminoMsg): _98.ResponseQuery;
            fromProtoMsg(message: _98.ResponseQueryProtoMsg): _98.ResponseQuery;
            toProto(message: _98.ResponseQuery): Uint8Array;
            toProtoMsg(message: _98.ResponseQuery): _98.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _98.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseBeginBlock;
            fromPartial(object: Partial<_98.ResponseBeginBlock>): _98.ResponseBeginBlock;
            fromAmino(object: _98.ResponseBeginBlockAmino): _98.ResponseBeginBlock;
            toAmino(message: _98.ResponseBeginBlock): _98.ResponseBeginBlockAmino;
            fromAminoMsg(object: _98.ResponseBeginBlockAminoMsg): _98.ResponseBeginBlock;
            fromProtoMsg(message: _98.ResponseBeginBlockProtoMsg): _98.ResponseBeginBlock;
            toProto(message: _98.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _98.ResponseBeginBlock): _98.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _98.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseCheckTx;
            fromPartial(object: Partial<_98.ResponseCheckTx>): _98.ResponseCheckTx;
            fromAmino(object: _98.ResponseCheckTxAmino): _98.ResponseCheckTx;
            toAmino(message: _98.ResponseCheckTx): _98.ResponseCheckTxAmino;
            fromAminoMsg(object: _98.ResponseCheckTxAminoMsg): _98.ResponseCheckTx;
            fromProtoMsg(message: _98.ResponseCheckTxProtoMsg): _98.ResponseCheckTx;
            toProto(message: _98.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _98.ResponseCheckTx): _98.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _98.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseDeliverTx;
            fromPartial(object: Partial<_98.ResponseDeliverTx>): _98.ResponseDeliverTx;
            fromAmino(object: _98.ResponseDeliverTxAmino): _98.ResponseDeliverTx;
            toAmino(message: _98.ResponseDeliverTx): _98.ResponseDeliverTxAmino;
            fromAminoMsg(object: _98.ResponseDeliverTxAminoMsg): _98.ResponseDeliverTx;
            fromProtoMsg(message: _98.ResponseDeliverTxProtoMsg): _98.ResponseDeliverTx;
            toProto(message: _98.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _98.ResponseDeliverTx): _98.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _98.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseEndBlock;
            fromPartial(object: Partial<_98.ResponseEndBlock>): _98.ResponseEndBlock;
            fromAmino(object: _98.ResponseEndBlockAmino): _98.ResponseEndBlock;
            toAmino(message: _98.ResponseEndBlock): _98.ResponseEndBlockAmino;
            fromAminoMsg(object: _98.ResponseEndBlockAminoMsg): _98.ResponseEndBlock;
            fromProtoMsg(message: _98.ResponseEndBlockProtoMsg): _98.ResponseEndBlock;
            toProto(message: _98.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _98.ResponseEndBlock): _98.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _98.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseCommit;
            fromPartial(object: Partial<_98.ResponseCommit>): _98.ResponseCommit;
            fromAmino(object: _98.ResponseCommitAmino): _98.ResponseCommit;
            toAmino(message: _98.ResponseCommit): _98.ResponseCommitAmino;
            fromAminoMsg(object: _98.ResponseCommitAminoMsg): _98.ResponseCommit;
            fromProtoMsg(message: _98.ResponseCommitProtoMsg): _98.ResponseCommit;
            toProto(message: _98.ResponseCommit): Uint8Array;
            toProtoMsg(message: _98.ResponseCommit): _98.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _98.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseListSnapshots;
            fromPartial(object: Partial<_98.ResponseListSnapshots>): _98.ResponseListSnapshots;
            fromAmino(object: _98.ResponseListSnapshotsAmino): _98.ResponseListSnapshots;
            toAmino(message: _98.ResponseListSnapshots): _98.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _98.ResponseListSnapshotsAminoMsg): _98.ResponseListSnapshots;
            fromProtoMsg(message: _98.ResponseListSnapshotsProtoMsg): _98.ResponseListSnapshots;
            toProto(message: _98.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _98.ResponseListSnapshots): _98.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _98.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseOfferSnapshot;
            fromPartial(object: Partial<_98.ResponseOfferSnapshot>): _98.ResponseOfferSnapshot;
            fromAmino(object: _98.ResponseOfferSnapshotAmino): _98.ResponseOfferSnapshot;
            toAmino(message: _98.ResponseOfferSnapshot): _98.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _98.ResponseOfferSnapshotAminoMsg): _98.ResponseOfferSnapshot;
            fromProtoMsg(message: _98.ResponseOfferSnapshotProtoMsg): _98.ResponseOfferSnapshot;
            toProto(message: _98.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _98.ResponseOfferSnapshot): _98.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _98.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_98.ResponseLoadSnapshotChunk>): _98.ResponseLoadSnapshotChunk;
            fromAmino(object: _98.ResponseLoadSnapshotChunkAmino): _98.ResponseLoadSnapshotChunk;
            toAmino(message: _98.ResponseLoadSnapshotChunk): _98.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _98.ResponseLoadSnapshotChunkAminoMsg): _98.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _98.ResponseLoadSnapshotChunkProtoMsg): _98.ResponseLoadSnapshotChunk;
            toProto(message: _98.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _98.ResponseLoadSnapshotChunk): _98.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _98.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_98.ResponseApplySnapshotChunk>): _98.ResponseApplySnapshotChunk;
            fromAmino(object: _98.ResponseApplySnapshotChunkAmino): _98.ResponseApplySnapshotChunk;
            toAmino(message: _98.ResponseApplySnapshotChunk): _98.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _98.ResponseApplySnapshotChunkAminoMsg): _98.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _98.ResponseApplySnapshotChunkProtoMsg): _98.ResponseApplySnapshotChunk;
            toProto(message: _98.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _98.ResponseApplySnapshotChunk): _98.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _98.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ConsensusParams;
            fromPartial(object: Partial<_98.ConsensusParams>): _98.ConsensusParams;
            fromAmino(object: _98.ConsensusParamsAmino): _98.ConsensusParams;
            toAmino(message: _98.ConsensusParams): _98.ConsensusParamsAmino;
            fromAminoMsg(object: _98.ConsensusParamsAminoMsg): _98.ConsensusParams;
            fromProtoMsg(message: _98.ConsensusParamsProtoMsg): _98.ConsensusParams;
            toProto(message: _98.ConsensusParams): Uint8Array;
            toProtoMsg(message: _98.ConsensusParams): _98.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _98.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.BlockParams;
            fromPartial(object: Partial<_98.BlockParams>): _98.BlockParams;
            fromAmino(object: _98.BlockParamsAmino): _98.BlockParams;
            toAmino(message: _98.BlockParams): _98.BlockParamsAmino;
            fromAminoMsg(object: _98.BlockParamsAminoMsg): _98.BlockParams;
            fromProtoMsg(message: _98.BlockParamsProtoMsg): _98.BlockParams;
            toProto(message: _98.BlockParams): Uint8Array;
            toProtoMsg(message: _98.BlockParams): _98.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            typeUrl: string;
            encode(message: _98.LastCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.LastCommitInfo;
            fromPartial(object: Partial<_98.LastCommitInfo>): _98.LastCommitInfo;
            fromAmino(object: _98.LastCommitInfoAmino): _98.LastCommitInfo;
            toAmino(message: _98.LastCommitInfo): _98.LastCommitInfoAmino;
            fromAminoMsg(object: _98.LastCommitInfoAminoMsg): _98.LastCommitInfo;
            fromProtoMsg(message: _98.LastCommitInfoProtoMsg): _98.LastCommitInfo;
            toProto(message: _98.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _98.LastCommitInfo): _98.LastCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _98.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.Event;
            fromPartial(object: Partial<_98.Event>): _98.Event;
            fromAmino(object: _98.EventAmino): _98.Event;
            toAmino(message: _98.Event): _98.EventAmino;
            fromAminoMsg(object: _98.EventAminoMsg): _98.Event;
            fromProtoMsg(message: _98.EventProtoMsg): _98.Event;
            toProto(message: _98.Event): Uint8Array;
            toProtoMsg(message: _98.Event): _98.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _98.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.EventAttribute;
            fromPartial(object: Partial<_98.EventAttribute>): _98.EventAttribute;
            fromAmino(object: _98.EventAttributeAmino): _98.EventAttribute;
            toAmino(message: _98.EventAttribute): _98.EventAttributeAmino;
            fromAminoMsg(object: _98.EventAttributeAminoMsg): _98.EventAttribute;
            fromProtoMsg(message: _98.EventAttributeProtoMsg): _98.EventAttribute;
            toProto(message: _98.EventAttribute): Uint8Array;
            toProtoMsg(message: _98.EventAttribute): _98.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _98.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.TxResult;
            fromPartial(object: Partial<_98.TxResult>): _98.TxResult;
            fromAmino(object: _98.TxResultAmino): _98.TxResult;
            toAmino(message: _98.TxResult): _98.TxResultAmino;
            fromAminoMsg(object: _98.TxResultAminoMsg): _98.TxResult;
            fromProtoMsg(message: _98.TxResultProtoMsg): _98.TxResult;
            toProto(message: _98.TxResult): Uint8Array;
            toProtoMsg(message: _98.TxResult): _98.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _98.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.Validator;
            fromPartial(object: Partial<_98.Validator>): _98.Validator;
            fromAmino(object: _98.ValidatorAmino): _98.Validator;
            toAmino(message: _98.Validator): _98.ValidatorAmino;
            fromAminoMsg(object: _98.ValidatorAminoMsg): _98.Validator;
            fromProtoMsg(message: _98.ValidatorProtoMsg): _98.Validator;
            toProto(message: _98.Validator): Uint8Array;
            toProtoMsg(message: _98.Validator): _98.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _98.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.ValidatorUpdate;
            fromPartial(object: Partial<_98.ValidatorUpdate>): _98.ValidatorUpdate;
            fromAmino(object: _98.ValidatorUpdateAmino): _98.ValidatorUpdate;
            toAmino(message: _98.ValidatorUpdate): _98.ValidatorUpdateAmino;
            fromAminoMsg(object: _98.ValidatorUpdateAminoMsg): _98.ValidatorUpdate;
            fromProtoMsg(message: _98.ValidatorUpdateProtoMsg): _98.ValidatorUpdate;
            toProto(message: _98.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _98.ValidatorUpdate): _98.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _98.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.VoteInfo;
            fromPartial(object: Partial<_98.VoteInfo>): _98.VoteInfo;
            fromAmino(object: _98.VoteInfoAmino): _98.VoteInfo;
            toAmino(message: _98.VoteInfo): _98.VoteInfoAmino;
            fromAminoMsg(object: _98.VoteInfoAminoMsg): _98.VoteInfo;
            fromProtoMsg(message: _98.VoteInfoProtoMsg): _98.VoteInfo;
            toProto(message: _98.VoteInfo): Uint8Array;
            toProtoMsg(message: _98.VoteInfo): _98.VoteInfoProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _98.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.Evidence;
            fromPartial(object: Partial<_98.Evidence>): _98.Evidence;
            fromAmino(object: _98.EvidenceAmino): _98.Evidence;
            toAmino(message: _98.Evidence): _98.EvidenceAmino;
            fromAminoMsg(object: _98.EvidenceAminoMsg): _98.Evidence;
            fromProtoMsg(message: _98.EvidenceProtoMsg): _98.Evidence;
            toProto(message: _98.Evidence): Uint8Array;
            toProtoMsg(message: _98.Evidence): _98.EvidenceProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _98.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.Snapshot;
            fromPartial(object: Partial<_98.Snapshot>): _98.Snapshot;
            fromAmino(object: _98.SnapshotAmino): _98.Snapshot;
            toAmino(message: _98.Snapshot): _98.SnapshotAmino;
            fromAminoMsg(object: _98.SnapshotAminoMsg): _98.Snapshot;
            fromProtoMsg(message: _98.SnapshotProtoMsg): _98.Snapshot;
            toProto(message: _98.Snapshot): Uint8Array;
            toProtoMsg(message: _98.Snapshot): _98.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _100.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _100.Proof;
            fromPartial(object: Partial<_100.Proof>): _100.Proof;
            fromAmino(object: _100.ProofAmino): _100.Proof;
            toAmino(message: _100.Proof): _100.ProofAmino;
            fromAminoMsg(object: _100.ProofAminoMsg): _100.Proof;
            fromProtoMsg(message: _100.ProofProtoMsg): _100.Proof;
            toProto(message: _100.Proof): Uint8Array;
            toProtoMsg(message: _100.Proof): _100.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _100.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _100.ValueOp;
            fromPartial(object: Partial<_100.ValueOp>): _100.ValueOp;
            fromAmino(object: _100.ValueOpAmino): _100.ValueOp;
            toAmino(message: _100.ValueOp): _100.ValueOpAmino;
            fromAminoMsg(object: _100.ValueOpAminoMsg): _100.ValueOp;
            fromProtoMsg(message: _100.ValueOpProtoMsg): _100.ValueOp;
            toProto(message: _100.ValueOp): Uint8Array;
            toProtoMsg(message: _100.ValueOp): _100.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _100.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _100.DominoOp;
            fromPartial(object: Partial<_100.DominoOp>): _100.DominoOp;
            fromAmino(object: _100.DominoOpAmino): _100.DominoOp;
            toAmino(message: _100.DominoOp): _100.DominoOpAmino;
            fromAminoMsg(object: _100.DominoOpAminoMsg): _100.DominoOp;
            fromProtoMsg(message: _100.DominoOpProtoMsg): _100.DominoOp;
            toProto(message: _100.DominoOp): Uint8Array;
            toProtoMsg(message: _100.DominoOp): _100.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _100.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _100.ProofOp;
            fromPartial(object: Partial<_100.ProofOp>): _100.ProofOp;
            fromAmino(object: _100.ProofOpAmino): _100.ProofOp;
            toAmino(message: _100.ProofOp): _100.ProofOpAmino;
            fromAminoMsg(object: _100.ProofOpAminoMsg): _100.ProofOp;
            fromProtoMsg(message: _100.ProofOpProtoMsg): _100.ProofOp;
            toProto(message: _100.ProofOp): Uint8Array;
            toProtoMsg(message: _100.ProofOp): _100.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _100.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _100.ProofOps;
            fromPartial(object: Partial<_100.ProofOps>): _100.ProofOps;
            fromAmino(object: _100.ProofOpsAmino): _100.ProofOps;
            toAmino(message: _100.ProofOps): _100.ProofOpsAmino;
            fromAminoMsg(object: _100.ProofOpsAminoMsg): _100.ProofOps;
            fromProtoMsg(message: _100.ProofOpsProtoMsg): _100.ProofOps;
            toProto(message: _100.ProofOps): Uint8Array;
            toProtoMsg(message: _100.ProofOps): _100.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _99.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _99.PublicKey;
            fromPartial(object: Partial<_99.PublicKey>): _99.PublicKey;
            fromAmino(object: _99.PublicKeyAmino): _99.PublicKey;
            toAmino(message: _99.PublicKey): _99.PublicKeyAmino;
            fromAminoMsg(object: _99.PublicKeyAminoMsg): _99.PublicKey;
            fromProtoMsg(message: _99.PublicKeyProtoMsg): _99.PublicKey;
            toProto(message: _99.PublicKey): Uint8Array;
            toProtoMsg(message: _99.PublicKey): _99.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _101.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                fromJSON(object: any): _101.BitArray;
                fromPartial(object: Partial<_101.BitArray>): _101.BitArray;
                fromAmino(object: _101.BitArrayAmino): _101.BitArray;
                toAmino(message: _101.BitArray): _101.BitArrayAmino;
                fromAminoMsg(object: _101.BitArrayAminoMsg): _101.BitArray;
                fromProtoMsg(message: _101.BitArrayProtoMsg): _101.BitArray;
                toProto(message: _101.BitArray): Uint8Array;
                toProtoMsg(message: _101.BitArray): _101.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _102.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _102.NetAddress;
            fromPartial(object: Partial<_102.NetAddress>): _102.NetAddress;
            fromAmino(object: _102.NetAddressAmino): _102.NetAddress;
            toAmino(message: _102.NetAddress): _102.NetAddressAmino;
            fromAminoMsg(object: _102.NetAddressAminoMsg): _102.NetAddress;
            fromProtoMsg(message: _102.NetAddressProtoMsg): _102.NetAddress;
            toProto(message: _102.NetAddress): Uint8Array;
            toProtoMsg(message: _102.NetAddress): _102.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _102.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _102.ProtocolVersion;
            fromPartial(object: Partial<_102.ProtocolVersion>): _102.ProtocolVersion;
            fromAmino(object: _102.ProtocolVersionAmino): _102.ProtocolVersion;
            toAmino(message: _102.ProtocolVersion): _102.ProtocolVersionAmino;
            fromAminoMsg(object: _102.ProtocolVersionAminoMsg): _102.ProtocolVersion;
            fromProtoMsg(message: _102.ProtocolVersionProtoMsg): _102.ProtocolVersion;
            toProto(message: _102.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _102.ProtocolVersion): _102.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _102.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _102.DefaultNodeInfo;
            fromPartial(object: Partial<_102.DefaultNodeInfo>): _102.DefaultNodeInfo;
            fromAmino(object: _102.DefaultNodeInfoAmino): _102.DefaultNodeInfo;
            toAmino(message: _102.DefaultNodeInfo): _102.DefaultNodeInfoAmino;
            fromAminoMsg(object: _102.DefaultNodeInfoAminoMsg): _102.DefaultNodeInfo;
            fromProtoMsg(message: _102.DefaultNodeInfoProtoMsg): _102.DefaultNodeInfo;
            toProto(message: _102.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _102.DefaultNodeInfo): _102.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _102.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _102.DefaultNodeInfoOther;
            fromPartial(object: Partial<_102.DefaultNodeInfoOther>): _102.DefaultNodeInfoOther;
            fromAmino(object: _102.DefaultNodeInfoOtherAmino): _102.DefaultNodeInfoOther;
            toAmino(message: _102.DefaultNodeInfoOther): _102.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _102.DefaultNodeInfoOtherAminoMsg): _102.DefaultNodeInfoOther;
            fromProtoMsg(message: _102.DefaultNodeInfoOtherProtoMsg): _102.DefaultNodeInfoOther;
            toProto(message: _102.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _102.DefaultNodeInfoOther): _102.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _107.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ValidatorSet;
            fromPartial(object: Partial<_107.ValidatorSet>): _107.ValidatorSet;
            fromAmino(object: _107.ValidatorSetAmino): _107.ValidatorSet;
            toAmino(message: _107.ValidatorSet): _107.ValidatorSetAmino;
            fromAminoMsg(object: _107.ValidatorSetAminoMsg): _107.ValidatorSet;
            fromProtoMsg(message: _107.ValidatorSetProtoMsg): _107.ValidatorSet;
            toProto(message: _107.ValidatorSet): Uint8Array;
            toProtoMsg(message: _107.ValidatorSet): _107.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _107.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.Validator;
            fromPartial(object: Partial<_107.Validator>): _107.Validator;
            fromAmino(object: _107.ValidatorAmino): _107.Validator;
            toAmino(message: _107.Validator): _107.ValidatorAmino;
            fromAminoMsg(object: _107.ValidatorAminoMsg): _107.Validator;
            fromProtoMsg(message: _107.ValidatorProtoMsg): _107.Validator;
            toProto(message: _107.Validator): Uint8Array;
            toProtoMsg(message: _107.Validator): _107.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _107.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.SimpleValidator;
            fromPartial(object: Partial<_107.SimpleValidator>): _107.SimpleValidator;
            fromAmino(object: _107.SimpleValidatorAmino): _107.SimpleValidator;
            toAmino(message: _107.SimpleValidator): _107.SimpleValidatorAmino;
            fromAminoMsg(object: _107.SimpleValidatorAminoMsg): _107.SimpleValidator;
            fromProtoMsg(message: _107.SimpleValidatorProtoMsg): _107.SimpleValidator;
            toProto(message: _107.SimpleValidator): Uint8Array;
            toProtoMsg(message: _107.SimpleValidator): _107.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _106.BlockIDFlag;
        blockIDFlagToJSON(object: _106.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _106.SignedMsgType;
        signedMsgTypeToJSON(object: _106.SignedMsgType): string;
        BlockIDFlag: typeof _106.BlockIDFlag;
        BlockIDFlagSDKType: typeof _106.BlockIDFlag;
        BlockIDFlagAmino: typeof _106.BlockIDFlag;
        SignedMsgType: typeof _106.SignedMsgType;
        SignedMsgTypeSDKType: typeof _106.SignedMsgType;
        SignedMsgTypeAmino: typeof _106.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _106.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.PartSetHeader;
            fromPartial(object: Partial<_106.PartSetHeader>): _106.PartSetHeader;
            fromAmino(object: _106.PartSetHeaderAmino): _106.PartSetHeader;
            toAmino(message: _106.PartSetHeader): _106.PartSetHeaderAmino;
            fromAminoMsg(object: _106.PartSetHeaderAminoMsg): _106.PartSetHeader;
            fromProtoMsg(message: _106.PartSetHeaderProtoMsg): _106.PartSetHeader;
            toProto(message: _106.PartSetHeader): Uint8Array;
            toProtoMsg(message: _106.PartSetHeader): _106.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _106.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.Part;
            fromPartial(object: Partial<_106.Part>): _106.Part;
            fromAmino(object: _106.PartAmino): _106.Part;
            toAmino(message: _106.Part): _106.PartAmino;
            fromAminoMsg(object: _106.PartAminoMsg): _106.Part;
            fromProtoMsg(message: _106.PartProtoMsg): _106.Part;
            toProto(message: _106.Part): Uint8Array;
            toProtoMsg(message: _106.Part): _106.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _106.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.BlockID;
            fromPartial(object: Partial<_106.BlockID>): _106.BlockID;
            fromAmino(object: _106.BlockIDAmino): _106.BlockID;
            toAmino(message: _106.BlockID): _106.BlockIDAmino;
            fromAminoMsg(object: _106.BlockIDAminoMsg): _106.BlockID;
            fromProtoMsg(message: _106.BlockIDProtoMsg): _106.BlockID;
            toProto(message: _106.BlockID): Uint8Array;
            toProtoMsg(message: _106.BlockID): _106.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _106.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.Header;
            fromPartial(object: Partial<_106.Header>): _106.Header;
            fromAmino(object: _106.HeaderAmino): _106.Header;
            toAmino(message: _106.Header): _106.HeaderAmino;
            fromAminoMsg(object: _106.HeaderAminoMsg): _106.Header;
            fromProtoMsg(message: _106.HeaderProtoMsg): _106.Header;
            toProto(message: _106.Header): Uint8Array;
            toProtoMsg(message: _106.Header): _106.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _106.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.Data;
            fromPartial(object: Partial<_106.Data>): _106.Data;
            fromAmino(object: _106.DataAmino): _106.Data;
            toAmino(message: _106.Data): _106.DataAmino;
            fromAminoMsg(object: _106.DataAminoMsg): _106.Data;
            fromProtoMsg(message: _106.DataProtoMsg): _106.Data;
            toProto(message: _106.Data): Uint8Array;
            toProtoMsg(message: _106.Data): _106.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _106.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.Vote;
            fromPartial(object: Partial<_106.Vote>): _106.Vote;
            fromAmino(object: _106.VoteAmino): _106.Vote;
            toAmino(message: _106.Vote): _106.VoteAmino;
            fromAminoMsg(object: _106.VoteAminoMsg): _106.Vote;
            fromProtoMsg(message: _106.VoteProtoMsg): _106.Vote;
            toProto(message: _106.Vote): Uint8Array;
            toProtoMsg(message: _106.Vote): _106.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _106.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.Commit;
            fromPartial(object: Partial<_106.Commit>): _106.Commit;
            fromAmino(object: _106.CommitAmino): _106.Commit;
            toAmino(message: _106.Commit): _106.CommitAmino;
            fromAminoMsg(object: _106.CommitAminoMsg): _106.Commit;
            fromProtoMsg(message: _106.CommitProtoMsg): _106.Commit;
            toProto(message: _106.Commit): Uint8Array;
            toProtoMsg(message: _106.Commit): _106.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _106.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.CommitSig;
            fromPartial(object: Partial<_106.CommitSig>): _106.CommitSig;
            fromAmino(object: _106.CommitSigAmino): _106.CommitSig;
            toAmino(message: _106.CommitSig): _106.CommitSigAmino;
            fromAminoMsg(object: _106.CommitSigAminoMsg): _106.CommitSig;
            fromProtoMsg(message: _106.CommitSigProtoMsg): _106.CommitSig;
            toProto(message: _106.CommitSig): Uint8Array;
            toProtoMsg(message: _106.CommitSig): _106.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _106.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.Proposal;
            fromPartial(object: Partial<_106.Proposal>): _106.Proposal;
            fromAmino(object: _106.ProposalAmino): _106.Proposal;
            toAmino(message: _106.Proposal): _106.ProposalAmino;
            fromAminoMsg(object: _106.ProposalAminoMsg): _106.Proposal;
            fromProtoMsg(message: _106.ProposalProtoMsg): _106.Proposal;
            toProto(message: _106.Proposal): Uint8Array;
            toProtoMsg(message: _106.Proposal): _106.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _106.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.SignedHeader;
            fromPartial(object: Partial<_106.SignedHeader>): _106.SignedHeader;
            fromAmino(object: _106.SignedHeaderAmino): _106.SignedHeader;
            toAmino(message: _106.SignedHeader): _106.SignedHeaderAmino;
            fromAminoMsg(object: _106.SignedHeaderAminoMsg): _106.SignedHeader;
            fromProtoMsg(message: _106.SignedHeaderProtoMsg): _106.SignedHeader;
            toProto(message: _106.SignedHeader): Uint8Array;
            toProtoMsg(message: _106.SignedHeader): _106.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _106.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.LightBlock;
            fromPartial(object: Partial<_106.LightBlock>): _106.LightBlock;
            fromAmino(object: _106.LightBlockAmino): _106.LightBlock;
            toAmino(message: _106.LightBlock): _106.LightBlockAmino;
            fromAminoMsg(object: _106.LightBlockAminoMsg): _106.LightBlock;
            fromProtoMsg(message: _106.LightBlockProtoMsg): _106.LightBlock;
            toProto(message: _106.LightBlock): Uint8Array;
            toProtoMsg(message: _106.LightBlock): _106.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _106.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.BlockMeta;
            fromPartial(object: Partial<_106.BlockMeta>): _106.BlockMeta;
            fromAmino(object: _106.BlockMetaAmino): _106.BlockMeta;
            toAmino(message: _106.BlockMeta): _106.BlockMetaAmino;
            fromAminoMsg(object: _106.BlockMetaAminoMsg): _106.BlockMeta;
            fromProtoMsg(message: _106.BlockMetaProtoMsg): _106.BlockMeta;
            toProto(message: _106.BlockMeta): Uint8Array;
            toProtoMsg(message: _106.BlockMeta): _106.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _106.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _106.TxProof;
            fromPartial(object: Partial<_106.TxProof>): _106.TxProof;
            fromAmino(object: _106.TxProofAmino): _106.TxProof;
            toAmino(message: _106.TxProof): _106.TxProofAmino;
            fromAminoMsg(object: _106.TxProofAminoMsg): _106.TxProof;
            fromProtoMsg(message: _106.TxProofProtoMsg): _106.TxProof;
            toProto(message: _106.TxProof): Uint8Array;
            toProtoMsg(message: _106.TxProof): _106.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _105.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.ConsensusParams;
            fromPartial(object: Partial<_105.ConsensusParams>): _105.ConsensusParams;
            fromAmino(object: _105.ConsensusParamsAmino): _105.ConsensusParams;
            toAmino(message: _105.ConsensusParams): _105.ConsensusParamsAmino;
            fromAminoMsg(object: _105.ConsensusParamsAminoMsg): _105.ConsensusParams;
            fromProtoMsg(message: _105.ConsensusParamsProtoMsg): _105.ConsensusParams;
            toProto(message: _105.ConsensusParams): Uint8Array;
            toProtoMsg(message: _105.ConsensusParams): _105.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _105.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.BlockParams;
            fromPartial(object: Partial<_105.BlockParams>): _105.BlockParams;
            fromAmino(object: _105.BlockParamsAmino): _105.BlockParams;
            toAmino(message: _105.BlockParams): _105.BlockParamsAmino;
            fromAminoMsg(object: _105.BlockParamsAminoMsg): _105.BlockParams;
            fromProtoMsg(message: _105.BlockParamsProtoMsg): _105.BlockParams;
            toProto(message: _105.BlockParams): Uint8Array;
            toProtoMsg(message: _105.BlockParams): _105.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _105.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.EvidenceParams;
            fromPartial(object: Partial<_105.EvidenceParams>): _105.EvidenceParams;
            fromAmino(object: _105.EvidenceParamsAmino): _105.EvidenceParams;
            toAmino(message: _105.EvidenceParams): _105.EvidenceParamsAmino;
            fromAminoMsg(object: _105.EvidenceParamsAminoMsg): _105.EvidenceParams;
            fromProtoMsg(message: _105.EvidenceParamsProtoMsg): _105.EvidenceParams;
            toProto(message: _105.EvidenceParams): Uint8Array;
            toProtoMsg(message: _105.EvidenceParams): _105.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _105.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.ValidatorParams;
            fromPartial(object: Partial<_105.ValidatorParams>): _105.ValidatorParams;
            fromAmino(object: _105.ValidatorParamsAmino): _105.ValidatorParams;
            toAmino(message: _105.ValidatorParams): _105.ValidatorParamsAmino;
            fromAminoMsg(object: _105.ValidatorParamsAminoMsg): _105.ValidatorParams;
            fromProtoMsg(message: _105.ValidatorParamsProtoMsg): _105.ValidatorParams;
            toProto(message: _105.ValidatorParams): Uint8Array;
            toProtoMsg(message: _105.ValidatorParams): _105.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _105.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.VersionParams;
            fromPartial(object: Partial<_105.VersionParams>): _105.VersionParams;
            fromAmino(object: _105.VersionParamsAmino): _105.VersionParams;
            toAmino(message: _105.VersionParams): _105.VersionParamsAmino;
            fromAminoMsg(object: _105.VersionParamsAminoMsg): _105.VersionParams;
            fromProtoMsg(message: _105.VersionParamsProtoMsg): _105.VersionParams;
            toProto(message: _105.VersionParams): Uint8Array;
            toProtoMsg(message: _105.VersionParams): _105.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _105.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _105.HashedParams;
            fromPartial(object: Partial<_105.HashedParams>): _105.HashedParams;
            fromAmino(object: _105.HashedParamsAmino): _105.HashedParams;
            toAmino(message: _105.HashedParams): _105.HashedParamsAmino;
            fromAminoMsg(object: _105.HashedParamsAminoMsg): _105.HashedParams;
            fromProtoMsg(message: _105.HashedParamsProtoMsg): _105.HashedParams;
            toProto(message: _105.HashedParams): Uint8Array;
            toProtoMsg(message: _105.HashedParams): _105.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _104.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _104.Evidence;
            fromPartial(object: Partial<_104.Evidence>): _104.Evidence;
            fromAmino(object: _104.EvidenceAmino): _104.Evidence;
            toAmino(message: _104.Evidence): _104.EvidenceAmino;
            fromAminoMsg(object: _104.EvidenceAminoMsg): _104.Evidence;
            fromProtoMsg(message: _104.EvidenceProtoMsg): _104.Evidence;
            toProto(message: _104.Evidence): Uint8Array;
            toProtoMsg(message: _104.Evidence): _104.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _104.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _104.DuplicateVoteEvidence;
            fromPartial(object: Partial<_104.DuplicateVoteEvidence>): _104.DuplicateVoteEvidence;
            fromAmino(object: _104.DuplicateVoteEvidenceAmino): _104.DuplicateVoteEvidence;
            toAmino(message: _104.DuplicateVoteEvidence): _104.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _104.DuplicateVoteEvidenceAminoMsg): _104.DuplicateVoteEvidence;
            fromProtoMsg(message: _104.DuplicateVoteEvidenceProtoMsg): _104.DuplicateVoteEvidence;
            toProto(message: _104.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _104.DuplicateVoteEvidence): _104.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _104.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _104.LightClientAttackEvidence;
            fromPartial(object: Partial<_104.LightClientAttackEvidence>): _104.LightClientAttackEvidence;
            fromAmino(object: _104.LightClientAttackEvidenceAmino): _104.LightClientAttackEvidence;
            toAmino(message: _104.LightClientAttackEvidence): _104.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _104.LightClientAttackEvidenceAminoMsg): _104.LightClientAttackEvidence;
            fromProtoMsg(message: _104.LightClientAttackEvidenceProtoMsg): _104.LightClientAttackEvidence;
            toProto(message: _104.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _104.LightClientAttackEvidence): _104.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _104.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _104.EvidenceList;
            fromPartial(object: Partial<_104.EvidenceList>): _104.EvidenceList;
            fromAmino(object: _104.EvidenceListAmino): _104.EvidenceList;
            toAmino(message: _104.EvidenceList): _104.EvidenceListAmino;
            fromAminoMsg(object: _104.EvidenceListAminoMsg): _104.EvidenceList;
            fromProtoMsg(message: _104.EvidenceListProtoMsg): _104.EvidenceList;
            toProto(message: _104.EvidenceList): Uint8Array;
            toProtoMsg(message: _104.EvidenceList): _104.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _103.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _103.Block;
            fromPartial(object: Partial<_103.Block>): _103.Block;
            fromAmino(object: _103.BlockAmino): _103.Block;
            toAmino(message: _103.Block): _103.BlockAmino;
            fromAminoMsg(object: _103.BlockAminoMsg): _103.Block;
            fromProtoMsg(message: _103.BlockProtoMsg): _103.Block;
            toProto(message: _103.Block): Uint8Array;
            toProtoMsg(message: _103.Block): _103.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _108.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _108.App;
            fromPartial(object: Partial<_108.App>): _108.App;
            fromAmino(object: _108.AppAmino): _108.App;
            toAmino(message: _108.App): _108.AppAmino;
            fromAminoMsg(object: _108.AppAminoMsg): _108.App;
            fromProtoMsg(message: _108.AppProtoMsg): _108.App;
            toProto(message: _108.App): Uint8Array;
            toProtoMsg(message: _108.App): _108.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _108.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _108.Consensus;
            fromPartial(object: Partial<_108.Consensus>): _108.Consensus;
            fromAmino(object: _108.ConsensusAmino): _108.Consensus;
            toAmino(message: _108.Consensus): _108.ConsensusAmino;
            fromAminoMsg(object: _108.ConsensusAminoMsg): _108.Consensus;
            fromProtoMsg(message: _108.ConsensusProtoMsg): _108.Consensus;
            toProto(message: _108.Consensus): Uint8Array;
            toProtoMsg(message: _108.Consensus): _108.ConsensusProtoMsg;
        };
    };
}
