import * as _145 from "../proofs";
export declare const ics23: {
    hashOpFromJSON(object: any): _145.HashOp;
    hashOpToJSON(object: _145.HashOp): string;
    lengthOpFromJSON(object: any): _145.LengthOp;
    lengthOpToJSON(object: _145.LengthOp): string;
    HashOp: typeof _145.HashOp;
    HashOpSDKType: typeof _145.HashOp;
    HashOpAmino: typeof _145.HashOp;
    LengthOp: typeof _145.LengthOp;
    LengthOpSDKType: typeof _145.LengthOp;
    LengthOpAmino: typeof _145.LengthOp;
    ExistenceProof: {
        typeUrl: string;
        encode(message: _145.ExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.ExistenceProof;
        fromPartial(object: Partial<_145.ExistenceProof>): _145.ExistenceProof;
        fromAmino(object: _145.ExistenceProofAmino): _145.ExistenceProof;
        toAmino(message: _145.ExistenceProof): _145.ExistenceProofAmino;
        fromAminoMsg(object: _145.ExistenceProofAminoMsg): _145.ExistenceProof;
        fromProtoMsg(message: _145.ExistenceProofProtoMsg): _145.ExistenceProof;
        toProto(message: _145.ExistenceProof): Uint8Array;
        toProtoMsg(message: _145.ExistenceProof): _145.ExistenceProofProtoMsg;
    };
    NonExistenceProof: {
        typeUrl: string;
        encode(message: _145.NonExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.NonExistenceProof;
        fromPartial(object: Partial<_145.NonExistenceProof>): _145.NonExistenceProof;
        fromAmino(object: _145.NonExistenceProofAmino): _145.NonExistenceProof;
        toAmino(message: _145.NonExistenceProof): _145.NonExistenceProofAmino;
        fromAminoMsg(object: _145.NonExistenceProofAminoMsg): _145.NonExistenceProof;
        fromProtoMsg(message: _145.NonExistenceProofProtoMsg): _145.NonExistenceProof;
        toProto(message: _145.NonExistenceProof): Uint8Array;
        toProtoMsg(message: _145.NonExistenceProof): _145.NonExistenceProofProtoMsg;
    };
    CommitmentProof: {
        typeUrl: string;
        encode(message: _145.CommitmentProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.CommitmentProof;
        fromPartial(object: Partial<_145.CommitmentProof>): _145.CommitmentProof;
        fromAmino(object: _145.CommitmentProofAmino): _145.CommitmentProof;
        toAmino(message: _145.CommitmentProof): _145.CommitmentProofAmino;
        fromAminoMsg(object: _145.CommitmentProofAminoMsg): _145.CommitmentProof;
        fromProtoMsg(message: _145.CommitmentProofProtoMsg): _145.CommitmentProof;
        toProto(message: _145.CommitmentProof): Uint8Array;
        toProtoMsg(message: _145.CommitmentProof): _145.CommitmentProofProtoMsg;
    };
    LeafOp: {
        typeUrl: string;
        encode(message: _145.LeafOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.LeafOp;
        fromPartial(object: Partial<_145.LeafOp>): _145.LeafOp;
        fromAmino(object: _145.LeafOpAmino): _145.LeafOp;
        toAmino(message: _145.LeafOp): _145.LeafOpAmino;
        fromAminoMsg(object: _145.LeafOpAminoMsg): _145.LeafOp;
        fromProtoMsg(message: _145.LeafOpProtoMsg): _145.LeafOp;
        toProto(message: _145.LeafOp): Uint8Array;
        toProtoMsg(message: _145.LeafOp): _145.LeafOpProtoMsg;
    };
    InnerOp: {
        typeUrl: string;
        encode(message: _145.InnerOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.InnerOp;
        fromPartial(object: Partial<_145.InnerOp>): _145.InnerOp;
        fromAmino(object: _145.InnerOpAmino): _145.InnerOp;
        toAmino(message: _145.InnerOp): _145.InnerOpAmino;
        fromAminoMsg(object: _145.InnerOpAminoMsg): _145.InnerOp;
        fromProtoMsg(message: _145.InnerOpProtoMsg): _145.InnerOp;
        toProto(message: _145.InnerOp): Uint8Array;
        toProtoMsg(message: _145.InnerOp): _145.InnerOpProtoMsg;
    };
    ProofSpec: {
        typeUrl: string;
        encode(message: _145.ProofSpec, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.ProofSpec;
        fromPartial(object: Partial<_145.ProofSpec>): _145.ProofSpec;
        fromAmino(object: _145.ProofSpecAmino): _145.ProofSpec;
        toAmino(message: _145.ProofSpec): _145.ProofSpecAmino;
        fromAminoMsg(object: _145.ProofSpecAminoMsg): _145.ProofSpec;
        fromProtoMsg(message: _145.ProofSpecProtoMsg): _145.ProofSpec;
        toProto(message: _145.ProofSpec): Uint8Array;
        toProtoMsg(message: _145.ProofSpec): _145.ProofSpecProtoMsg;
    };
    InnerSpec: {
        typeUrl: string;
        encode(message: _145.InnerSpec, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.InnerSpec;
        fromPartial(object: Partial<_145.InnerSpec>): _145.InnerSpec;
        fromAmino(object: _145.InnerSpecAmino): _145.InnerSpec;
        toAmino(message: _145.InnerSpec): _145.InnerSpecAmino;
        fromAminoMsg(object: _145.InnerSpecAminoMsg): _145.InnerSpec;
        fromProtoMsg(message: _145.InnerSpecProtoMsg): _145.InnerSpec;
        toProto(message: _145.InnerSpec): Uint8Array;
        toProtoMsg(message: _145.InnerSpec): _145.InnerSpecProtoMsg;
    };
    BatchProof: {
        typeUrl: string;
        encode(message: _145.BatchProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.BatchProof;
        fromPartial(object: Partial<_145.BatchProof>): _145.BatchProof;
        fromAmino(object: _145.BatchProofAmino): _145.BatchProof;
        toAmino(message: _145.BatchProof): _145.BatchProofAmino;
        fromAminoMsg(object: _145.BatchProofAminoMsg): _145.BatchProof;
        fromProtoMsg(message: _145.BatchProofProtoMsg): _145.BatchProof;
        toProto(message: _145.BatchProof): Uint8Array;
        toProtoMsg(message: _145.BatchProof): _145.BatchProofProtoMsg;
    };
    BatchEntry: {
        typeUrl: string;
        encode(message: _145.BatchEntry, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.BatchEntry;
        fromPartial(object: Partial<_145.BatchEntry>): _145.BatchEntry;
        fromAmino(object: _145.BatchEntryAmino): _145.BatchEntry;
        toAmino(message: _145.BatchEntry): _145.BatchEntryAmino;
        fromAminoMsg(object: _145.BatchEntryAminoMsg): _145.BatchEntry;
        fromProtoMsg(message: _145.BatchEntryProtoMsg): _145.BatchEntry;
        toProto(message: _145.BatchEntry): Uint8Array;
        toProtoMsg(message: _145.BatchEntry): _145.BatchEntryProtoMsg;
    };
    CompressedBatchProof: {
        typeUrl: string;
        encode(message: _145.CompressedBatchProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.CompressedBatchProof;
        fromPartial(object: Partial<_145.CompressedBatchProof>): _145.CompressedBatchProof;
        fromAmino(object: _145.CompressedBatchProofAmino): _145.CompressedBatchProof;
        toAmino(message: _145.CompressedBatchProof): _145.CompressedBatchProofAmino;
        fromAminoMsg(object: _145.CompressedBatchProofAminoMsg): _145.CompressedBatchProof;
        fromProtoMsg(message: _145.CompressedBatchProofProtoMsg): _145.CompressedBatchProof;
        toProto(message: _145.CompressedBatchProof): Uint8Array;
        toProtoMsg(message: _145.CompressedBatchProof): _145.CompressedBatchProofProtoMsg;
    };
    CompressedBatchEntry: {
        typeUrl: string;
        encode(message: _145.CompressedBatchEntry, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.CompressedBatchEntry;
        fromPartial(object: Partial<_145.CompressedBatchEntry>): _145.CompressedBatchEntry;
        fromAmino(object: _145.CompressedBatchEntryAmino): _145.CompressedBatchEntry;
        toAmino(message: _145.CompressedBatchEntry): _145.CompressedBatchEntryAmino;
        fromAminoMsg(object: _145.CompressedBatchEntryAminoMsg): _145.CompressedBatchEntry;
        fromProtoMsg(message: _145.CompressedBatchEntryProtoMsg): _145.CompressedBatchEntry;
        toProto(message: _145.CompressedBatchEntry): Uint8Array;
        toProtoMsg(message: _145.CompressedBatchEntry): _145.CompressedBatchEntryProtoMsg;
    };
    CompressedExistenceProof: {
        typeUrl: string;
        encode(message: _145.CompressedExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.CompressedExistenceProof;
        fromPartial(object: Partial<_145.CompressedExistenceProof>): _145.CompressedExistenceProof;
        fromAmino(object: _145.CompressedExistenceProofAmino): _145.CompressedExistenceProof;
        toAmino(message: _145.CompressedExistenceProof): _145.CompressedExistenceProofAmino;
        fromAminoMsg(object: _145.CompressedExistenceProofAminoMsg): _145.CompressedExistenceProof;
        fromProtoMsg(message: _145.CompressedExistenceProofProtoMsg): _145.CompressedExistenceProof;
        toProto(message: _145.CompressedExistenceProof): Uint8Array;
        toProtoMsg(message: _145.CompressedExistenceProof): _145.CompressedExistenceProofProtoMsg;
    };
    CompressedNonExistenceProof: {
        typeUrl: string;
        encode(message: _145.CompressedNonExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _145.CompressedNonExistenceProof;
        fromPartial(object: Partial<_145.CompressedNonExistenceProof>): _145.CompressedNonExistenceProof;
        fromAmino(object: _145.CompressedNonExistenceProofAmino): _145.CompressedNonExistenceProof;
        toAmino(message: _145.CompressedNonExistenceProof): _145.CompressedNonExistenceProofAmino;
        fromAminoMsg(object: _145.CompressedNonExistenceProofAminoMsg): _145.CompressedNonExistenceProof;
        fromProtoMsg(message: _145.CompressedNonExistenceProofProtoMsg): _145.CompressedNonExistenceProof;
        toProto(message: _145.CompressedNonExistenceProof): Uint8Array;
        toProtoMsg(message: _145.CompressedNonExistenceProof): _145.CompressedNonExistenceProofProtoMsg;
    };
};
