import * as _90 from "./abci/types";
import * as _91 from "./crypto/keys";
import * as _92 from "./crypto/proof";
import * as _93 from "./libs/bits/types";
import * as _94 from "./p2p/types";
import * as _95 from "./types/block";
import * as _96 from "./types/evidence";
import * as _97 from "./types/params";
import * as _98 from "./types/types";
import * as _99 from "./types/validator";
import * as _100 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _90.CheckTxType;
        checkTxTypeToJSON(object: _90.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _90.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _90.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _90.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _90.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _90.EvidenceType;
        evidenceTypeToJSON(object: _90.EvidenceType): string;
        CheckTxType: typeof _90.CheckTxType;
        CheckTxTypeSDKType: typeof _90.CheckTxType;
        CheckTxTypeAmino: typeof _90.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _90.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _90.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _90.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _90.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _90.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _90.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _90.EvidenceType;
        EvidenceTypeSDKType: typeof _90.EvidenceType;
        EvidenceTypeAmino: typeof _90.EvidenceType;
        Request: {
            typeUrl: string;
            encode(message: _90.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.Request;
            fromPartial(object: Partial<_90.Request>): _90.Request;
            fromAmino(object: _90.RequestAmino): _90.Request;
            toAmino(message: _90.Request): _90.RequestAmino;
            fromAminoMsg(object: _90.RequestAminoMsg): _90.Request;
            fromProtoMsg(message: _90.RequestProtoMsg): _90.Request;
            toProto(message: _90.Request): Uint8Array;
            toProtoMsg(message: _90.Request): _90.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _90.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.RequestEcho;
            fromPartial(object: Partial<_90.RequestEcho>): _90.RequestEcho;
            fromAmino(object: _90.RequestEchoAmino): _90.RequestEcho;
            toAmino(message: _90.RequestEcho): _90.RequestEchoAmino;
            fromAminoMsg(object: _90.RequestEchoAminoMsg): _90.RequestEcho;
            fromProtoMsg(message: _90.RequestEchoProtoMsg): _90.RequestEcho;
            toProto(message: _90.RequestEcho): Uint8Array;
            toProtoMsg(message: _90.RequestEcho): _90.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _90.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _90.RequestFlush;
            fromPartial(_: Partial<_90.RequestFlush>): _90.RequestFlush;
            fromAmino(_: _90.RequestFlushAmino): _90.RequestFlush;
            toAmino(_: _90.RequestFlush): _90.RequestFlushAmino;
            fromAminoMsg(object: _90.RequestFlushAminoMsg): _90.RequestFlush;
            fromProtoMsg(message: _90.RequestFlushProtoMsg): _90.RequestFlush;
            toProto(message: _90.RequestFlush): Uint8Array;
            toProtoMsg(message: _90.RequestFlush): _90.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _90.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.RequestInfo;
            fromPartial(object: Partial<_90.RequestInfo>): _90.RequestInfo;
            fromAmino(object: _90.RequestInfoAmino): _90.RequestInfo;
            toAmino(message: _90.RequestInfo): _90.RequestInfoAmino;
            fromAminoMsg(object: _90.RequestInfoAminoMsg): _90.RequestInfo;
            fromProtoMsg(message: _90.RequestInfoProtoMsg): _90.RequestInfo;
            toProto(message: _90.RequestInfo): Uint8Array;
            toProtoMsg(message: _90.RequestInfo): _90.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            typeUrl: string;
            encode(message: _90.RequestSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.RequestSetOption;
            fromPartial(object: Partial<_90.RequestSetOption>): _90.RequestSetOption;
            fromAmino(object: _90.RequestSetOptionAmino): _90.RequestSetOption;
            toAmino(message: _90.RequestSetOption): _90.RequestSetOptionAmino;
            fromAminoMsg(object: _90.RequestSetOptionAminoMsg): _90.RequestSetOption;
            fromProtoMsg(message: _90.RequestSetOptionProtoMsg): _90.RequestSetOption;
            toProto(message: _90.RequestSetOption): Uint8Array;
            toProtoMsg(message: _90.RequestSetOption): _90.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _90.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.RequestInitChain;
            fromPartial(object: Partial<_90.RequestInitChain>): _90.RequestInitChain;
            fromAmino(object: _90.RequestInitChainAmino): _90.RequestInitChain;
            toAmino(message: _90.RequestInitChain): _90.RequestInitChainAmino;
            fromAminoMsg(object: _90.RequestInitChainAminoMsg): _90.RequestInitChain;
            fromProtoMsg(message: _90.RequestInitChainProtoMsg): _90.RequestInitChain;
            toProto(message: _90.RequestInitChain): Uint8Array;
            toProtoMsg(message: _90.RequestInitChain): _90.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _90.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.RequestQuery;
            fromPartial(object: Partial<_90.RequestQuery>): _90.RequestQuery;
            fromAmino(object: _90.RequestQueryAmino): _90.RequestQuery;
            toAmino(message: _90.RequestQuery): _90.RequestQueryAmino;
            fromAminoMsg(object: _90.RequestQueryAminoMsg): _90.RequestQuery;
            fromProtoMsg(message: _90.RequestQueryProtoMsg): _90.RequestQuery;
            toProto(message: _90.RequestQuery): Uint8Array;
            toProtoMsg(message: _90.RequestQuery): _90.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _90.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.RequestBeginBlock;
            fromPartial(object: Partial<_90.RequestBeginBlock>): _90.RequestBeginBlock;
            fromAmino(object: _90.RequestBeginBlockAmino): _90.RequestBeginBlock;
            toAmino(message: _90.RequestBeginBlock): _90.RequestBeginBlockAmino;
            fromAminoMsg(object: _90.RequestBeginBlockAminoMsg): _90.RequestBeginBlock;
            fromProtoMsg(message: _90.RequestBeginBlockProtoMsg): _90.RequestBeginBlock;
            toProto(message: _90.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _90.RequestBeginBlock): _90.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _90.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.RequestCheckTx;
            fromPartial(object: Partial<_90.RequestCheckTx>): _90.RequestCheckTx;
            fromAmino(object: _90.RequestCheckTxAmino): _90.RequestCheckTx;
            toAmino(message: _90.RequestCheckTx): _90.RequestCheckTxAmino;
            fromAminoMsg(object: _90.RequestCheckTxAminoMsg): _90.RequestCheckTx;
            fromProtoMsg(message: _90.RequestCheckTxProtoMsg): _90.RequestCheckTx;
            toProto(message: _90.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _90.RequestCheckTx): _90.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _90.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.RequestDeliverTx;
            fromPartial(object: Partial<_90.RequestDeliverTx>): _90.RequestDeliverTx;
            fromAmino(object: _90.RequestDeliverTxAmino): _90.RequestDeliverTx;
            toAmino(message: _90.RequestDeliverTx): _90.RequestDeliverTxAmino;
            fromAminoMsg(object: _90.RequestDeliverTxAminoMsg): _90.RequestDeliverTx;
            fromProtoMsg(message: _90.RequestDeliverTxProtoMsg): _90.RequestDeliverTx;
            toProto(message: _90.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _90.RequestDeliverTx): _90.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _90.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.RequestEndBlock;
            fromPartial(object: Partial<_90.RequestEndBlock>): _90.RequestEndBlock;
            fromAmino(object: _90.RequestEndBlockAmino): _90.RequestEndBlock;
            toAmino(message: _90.RequestEndBlock): _90.RequestEndBlockAmino;
            fromAminoMsg(object: _90.RequestEndBlockAminoMsg): _90.RequestEndBlock;
            fromProtoMsg(message: _90.RequestEndBlockProtoMsg): _90.RequestEndBlock;
            toProto(message: _90.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _90.RequestEndBlock): _90.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _90.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _90.RequestCommit;
            fromPartial(_: Partial<_90.RequestCommit>): _90.RequestCommit;
            fromAmino(_: _90.RequestCommitAmino): _90.RequestCommit;
            toAmino(_: _90.RequestCommit): _90.RequestCommitAmino;
            fromAminoMsg(object: _90.RequestCommitAminoMsg): _90.RequestCommit;
            fromProtoMsg(message: _90.RequestCommitProtoMsg): _90.RequestCommit;
            toProto(message: _90.RequestCommit): Uint8Array;
            toProtoMsg(message: _90.RequestCommit): _90.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _90.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _90.RequestListSnapshots;
            fromPartial(_: Partial<_90.RequestListSnapshots>): _90.RequestListSnapshots;
            fromAmino(_: _90.RequestListSnapshotsAmino): _90.RequestListSnapshots;
            toAmino(_: _90.RequestListSnapshots): _90.RequestListSnapshotsAmino;
            fromAminoMsg(object: _90.RequestListSnapshotsAminoMsg): _90.RequestListSnapshots;
            fromProtoMsg(message: _90.RequestListSnapshotsProtoMsg): _90.RequestListSnapshots;
            toProto(message: _90.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _90.RequestListSnapshots): _90.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _90.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.RequestOfferSnapshot;
            fromPartial(object: Partial<_90.RequestOfferSnapshot>): _90.RequestOfferSnapshot;
            fromAmino(object: _90.RequestOfferSnapshotAmino): _90.RequestOfferSnapshot;
            toAmino(message: _90.RequestOfferSnapshot): _90.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _90.RequestOfferSnapshotAminoMsg): _90.RequestOfferSnapshot;
            fromProtoMsg(message: _90.RequestOfferSnapshotProtoMsg): _90.RequestOfferSnapshot;
            toProto(message: _90.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _90.RequestOfferSnapshot): _90.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _90.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_90.RequestLoadSnapshotChunk>): _90.RequestLoadSnapshotChunk;
            fromAmino(object: _90.RequestLoadSnapshotChunkAmino): _90.RequestLoadSnapshotChunk;
            toAmino(message: _90.RequestLoadSnapshotChunk): _90.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _90.RequestLoadSnapshotChunkAminoMsg): _90.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _90.RequestLoadSnapshotChunkProtoMsg): _90.RequestLoadSnapshotChunk;
            toProto(message: _90.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _90.RequestLoadSnapshotChunk): _90.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _90.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_90.RequestApplySnapshotChunk>): _90.RequestApplySnapshotChunk;
            fromAmino(object: _90.RequestApplySnapshotChunkAmino): _90.RequestApplySnapshotChunk;
            toAmino(message: _90.RequestApplySnapshotChunk): _90.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _90.RequestApplySnapshotChunkAminoMsg): _90.RequestApplySnapshotChunk;
            fromProtoMsg(message: _90.RequestApplySnapshotChunkProtoMsg): _90.RequestApplySnapshotChunk;
            toProto(message: _90.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _90.RequestApplySnapshotChunk): _90.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _90.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.Response;
            fromPartial(object: Partial<_90.Response>): _90.Response;
            fromAmino(object: _90.ResponseAmino): _90.Response;
            toAmino(message: _90.Response): _90.ResponseAmino;
            fromAminoMsg(object: _90.ResponseAminoMsg): _90.Response;
            fromProtoMsg(message: _90.ResponseProtoMsg): _90.Response;
            toProto(message: _90.Response): Uint8Array;
            toProtoMsg(message: _90.Response): _90.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _90.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseException;
            fromPartial(object: Partial<_90.ResponseException>): _90.ResponseException;
            fromAmino(object: _90.ResponseExceptionAmino): _90.ResponseException;
            toAmino(message: _90.ResponseException): _90.ResponseExceptionAmino;
            fromAminoMsg(object: _90.ResponseExceptionAminoMsg): _90.ResponseException;
            fromProtoMsg(message: _90.ResponseExceptionProtoMsg): _90.ResponseException;
            toProto(message: _90.ResponseException): Uint8Array;
            toProtoMsg(message: _90.ResponseException): _90.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _90.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseEcho;
            fromPartial(object: Partial<_90.ResponseEcho>): _90.ResponseEcho;
            fromAmino(object: _90.ResponseEchoAmino): _90.ResponseEcho;
            toAmino(message: _90.ResponseEcho): _90.ResponseEchoAmino;
            fromAminoMsg(object: _90.ResponseEchoAminoMsg): _90.ResponseEcho;
            fromProtoMsg(message: _90.ResponseEchoProtoMsg): _90.ResponseEcho;
            toProto(message: _90.ResponseEcho): Uint8Array;
            toProtoMsg(message: _90.ResponseEcho): _90.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _90.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _90.ResponseFlush;
            fromPartial(_: Partial<_90.ResponseFlush>): _90.ResponseFlush;
            fromAmino(_: _90.ResponseFlushAmino): _90.ResponseFlush;
            toAmino(_: _90.ResponseFlush): _90.ResponseFlushAmino;
            fromAminoMsg(object: _90.ResponseFlushAminoMsg): _90.ResponseFlush;
            fromProtoMsg(message: _90.ResponseFlushProtoMsg): _90.ResponseFlush;
            toProto(message: _90.ResponseFlush): Uint8Array;
            toProtoMsg(message: _90.ResponseFlush): _90.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _90.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseInfo;
            fromPartial(object: Partial<_90.ResponseInfo>): _90.ResponseInfo;
            fromAmino(object: _90.ResponseInfoAmino): _90.ResponseInfo;
            toAmino(message: _90.ResponseInfo): _90.ResponseInfoAmino;
            fromAminoMsg(object: _90.ResponseInfoAminoMsg): _90.ResponseInfo;
            fromProtoMsg(message: _90.ResponseInfoProtoMsg): _90.ResponseInfo;
            toProto(message: _90.ResponseInfo): Uint8Array;
            toProtoMsg(message: _90.ResponseInfo): _90.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            typeUrl: string;
            encode(message: _90.ResponseSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseSetOption;
            fromPartial(object: Partial<_90.ResponseSetOption>): _90.ResponseSetOption;
            fromAmino(object: _90.ResponseSetOptionAmino): _90.ResponseSetOption;
            toAmino(message: _90.ResponseSetOption): _90.ResponseSetOptionAmino;
            fromAminoMsg(object: _90.ResponseSetOptionAminoMsg): _90.ResponseSetOption;
            fromProtoMsg(message: _90.ResponseSetOptionProtoMsg): _90.ResponseSetOption;
            toProto(message: _90.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _90.ResponseSetOption): _90.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _90.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseInitChain;
            fromPartial(object: Partial<_90.ResponseInitChain>): _90.ResponseInitChain;
            fromAmino(object: _90.ResponseInitChainAmino): _90.ResponseInitChain;
            toAmino(message: _90.ResponseInitChain): _90.ResponseInitChainAmino;
            fromAminoMsg(object: _90.ResponseInitChainAminoMsg): _90.ResponseInitChain;
            fromProtoMsg(message: _90.ResponseInitChainProtoMsg): _90.ResponseInitChain;
            toProto(message: _90.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _90.ResponseInitChain): _90.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _90.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseQuery;
            fromPartial(object: Partial<_90.ResponseQuery>): _90.ResponseQuery;
            fromAmino(object: _90.ResponseQueryAmino): _90.ResponseQuery;
            toAmino(message: _90.ResponseQuery): _90.ResponseQueryAmino;
            fromAminoMsg(object: _90.ResponseQueryAminoMsg): _90.ResponseQuery;
            fromProtoMsg(message: _90.ResponseQueryProtoMsg): _90.ResponseQuery;
            toProto(message: _90.ResponseQuery): Uint8Array;
            toProtoMsg(message: _90.ResponseQuery): _90.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _90.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseBeginBlock;
            fromPartial(object: Partial<_90.ResponseBeginBlock>): _90.ResponseBeginBlock;
            fromAmino(object: _90.ResponseBeginBlockAmino): _90.ResponseBeginBlock;
            toAmino(message: _90.ResponseBeginBlock): _90.ResponseBeginBlockAmino;
            fromAminoMsg(object: _90.ResponseBeginBlockAminoMsg): _90.ResponseBeginBlock;
            fromProtoMsg(message: _90.ResponseBeginBlockProtoMsg): _90.ResponseBeginBlock;
            toProto(message: _90.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _90.ResponseBeginBlock): _90.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _90.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseCheckTx;
            fromPartial(object: Partial<_90.ResponseCheckTx>): _90.ResponseCheckTx;
            fromAmino(object: _90.ResponseCheckTxAmino): _90.ResponseCheckTx;
            toAmino(message: _90.ResponseCheckTx): _90.ResponseCheckTxAmino;
            fromAminoMsg(object: _90.ResponseCheckTxAminoMsg): _90.ResponseCheckTx;
            fromProtoMsg(message: _90.ResponseCheckTxProtoMsg): _90.ResponseCheckTx;
            toProto(message: _90.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _90.ResponseCheckTx): _90.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _90.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseDeliverTx;
            fromPartial(object: Partial<_90.ResponseDeliverTx>): _90.ResponseDeliverTx;
            fromAmino(object: _90.ResponseDeliverTxAmino): _90.ResponseDeliverTx;
            toAmino(message: _90.ResponseDeliverTx): _90.ResponseDeliverTxAmino;
            fromAminoMsg(object: _90.ResponseDeliverTxAminoMsg): _90.ResponseDeliverTx;
            fromProtoMsg(message: _90.ResponseDeliverTxProtoMsg): _90.ResponseDeliverTx;
            toProto(message: _90.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _90.ResponseDeliverTx): _90.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _90.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseEndBlock;
            fromPartial(object: Partial<_90.ResponseEndBlock>): _90.ResponseEndBlock;
            fromAmino(object: _90.ResponseEndBlockAmino): _90.ResponseEndBlock;
            toAmino(message: _90.ResponseEndBlock): _90.ResponseEndBlockAmino;
            fromAminoMsg(object: _90.ResponseEndBlockAminoMsg): _90.ResponseEndBlock;
            fromProtoMsg(message: _90.ResponseEndBlockProtoMsg): _90.ResponseEndBlock;
            toProto(message: _90.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _90.ResponseEndBlock): _90.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _90.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseCommit;
            fromPartial(object: Partial<_90.ResponseCommit>): _90.ResponseCommit;
            fromAmino(object: _90.ResponseCommitAmino): _90.ResponseCommit;
            toAmino(message: _90.ResponseCommit): _90.ResponseCommitAmino;
            fromAminoMsg(object: _90.ResponseCommitAminoMsg): _90.ResponseCommit;
            fromProtoMsg(message: _90.ResponseCommitProtoMsg): _90.ResponseCommit;
            toProto(message: _90.ResponseCommit): Uint8Array;
            toProtoMsg(message: _90.ResponseCommit): _90.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _90.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseListSnapshots;
            fromPartial(object: Partial<_90.ResponseListSnapshots>): _90.ResponseListSnapshots;
            fromAmino(object: _90.ResponseListSnapshotsAmino): _90.ResponseListSnapshots;
            toAmino(message: _90.ResponseListSnapshots): _90.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _90.ResponseListSnapshotsAminoMsg): _90.ResponseListSnapshots;
            fromProtoMsg(message: _90.ResponseListSnapshotsProtoMsg): _90.ResponseListSnapshots;
            toProto(message: _90.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _90.ResponseListSnapshots): _90.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _90.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseOfferSnapshot;
            fromPartial(object: Partial<_90.ResponseOfferSnapshot>): _90.ResponseOfferSnapshot;
            fromAmino(object: _90.ResponseOfferSnapshotAmino): _90.ResponseOfferSnapshot;
            toAmino(message: _90.ResponseOfferSnapshot): _90.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _90.ResponseOfferSnapshotAminoMsg): _90.ResponseOfferSnapshot;
            fromProtoMsg(message: _90.ResponseOfferSnapshotProtoMsg): _90.ResponseOfferSnapshot;
            toProto(message: _90.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _90.ResponseOfferSnapshot): _90.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _90.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_90.ResponseLoadSnapshotChunk>): _90.ResponseLoadSnapshotChunk;
            fromAmino(object: _90.ResponseLoadSnapshotChunkAmino): _90.ResponseLoadSnapshotChunk;
            toAmino(message: _90.ResponseLoadSnapshotChunk): _90.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _90.ResponseLoadSnapshotChunkAminoMsg): _90.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _90.ResponseLoadSnapshotChunkProtoMsg): _90.ResponseLoadSnapshotChunk;
            toProto(message: _90.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _90.ResponseLoadSnapshotChunk): _90.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _90.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_90.ResponseApplySnapshotChunk>): _90.ResponseApplySnapshotChunk;
            fromAmino(object: _90.ResponseApplySnapshotChunkAmino): _90.ResponseApplySnapshotChunk;
            toAmino(message: _90.ResponseApplySnapshotChunk): _90.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _90.ResponseApplySnapshotChunkAminoMsg): _90.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _90.ResponseApplySnapshotChunkProtoMsg): _90.ResponseApplySnapshotChunk;
            toProto(message: _90.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _90.ResponseApplySnapshotChunk): _90.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _90.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ConsensusParams;
            fromPartial(object: Partial<_90.ConsensusParams>): _90.ConsensusParams;
            fromAmino(object: _90.ConsensusParamsAmino): _90.ConsensusParams;
            toAmino(message: _90.ConsensusParams): _90.ConsensusParamsAmino;
            fromAminoMsg(object: _90.ConsensusParamsAminoMsg): _90.ConsensusParams;
            fromProtoMsg(message: _90.ConsensusParamsProtoMsg): _90.ConsensusParams;
            toProto(message: _90.ConsensusParams): Uint8Array;
            toProtoMsg(message: _90.ConsensusParams): _90.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _90.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.BlockParams;
            fromPartial(object: Partial<_90.BlockParams>): _90.BlockParams;
            fromAmino(object: _90.BlockParamsAmino): _90.BlockParams;
            toAmino(message: _90.BlockParams): _90.BlockParamsAmino;
            fromAminoMsg(object: _90.BlockParamsAminoMsg): _90.BlockParams;
            fromProtoMsg(message: _90.BlockParamsProtoMsg): _90.BlockParams;
            toProto(message: _90.BlockParams): Uint8Array;
            toProtoMsg(message: _90.BlockParams): _90.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            typeUrl: string;
            encode(message: _90.LastCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.LastCommitInfo;
            fromPartial(object: Partial<_90.LastCommitInfo>): _90.LastCommitInfo;
            fromAmino(object: _90.LastCommitInfoAmino): _90.LastCommitInfo;
            toAmino(message: _90.LastCommitInfo): _90.LastCommitInfoAmino;
            fromAminoMsg(object: _90.LastCommitInfoAminoMsg): _90.LastCommitInfo;
            fromProtoMsg(message: _90.LastCommitInfoProtoMsg): _90.LastCommitInfo;
            toProto(message: _90.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _90.LastCommitInfo): _90.LastCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _90.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.Event;
            fromPartial(object: Partial<_90.Event>): _90.Event;
            fromAmino(object: _90.EventAmino): _90.Event;
            toAmino(message: _90.Event): _90.EventAmino;
            fromAminoMsg(object: _90.EventAminoMsg): _90.Event;
            fromProtoMsg(message: _90.EventProtoMsg): _90.Event;
            toProto(message: _90.Event): Uint8Array;
            toProtoMsg(message: _90.Event): _90.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _90.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.EventAttribute;
            fromPartial(object: Partial<_90.EventAttribute>): _90.EventAttribute;
            fromAmino(object: _90.EventAttributeAmino): _90.EventAttribute;
            toAmino(message: _90.EventAttribute): _90.EventAttributeAmino;
            fromAminoMsg(object: _90.EventAttributeAminoMsg): _90.EventAttribute;
            fromProtoMsg(message: _90.EventAttributeProtoMsg): _90.EventAttribute;
            toProto(message: _90.EventAttribute): Uint8Array;
            toProtoMsg(message: _90.EventAttribute): _90.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _90.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.TxResult;
            fromPartial(object: Partial<_90.TxResult>): _90.TxResult;
            fromAmino(object: _90.TxResultAmino): _90.TxResult;
            toAmino(message: _90.TxResult): _90.TxResultAmino;
            fromAminoMsg(object: _90.TxResultAminoMsg): _90.TxResult;
            fromProtoMsg(message: _90.TxResultProtoMsg): _90.TxResult;
            toProto(message: _90.TxResult): Uint8Array;
            toProtoMsg(message: _90.TxResult): _90.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _90.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.Validator;
            fromPartial(object: Partial<_90.Validator>): _90.Validator;
            fromAmino(object: _90.ValidatorAmino): _90.Validator;
            toAmino(message: _90.Validator): _90.ValidatorAmino;
            fromAminoMsg(object: _90.ValidatorAminoMsg): _90.Validator;
            fromProtoMsg(message: _90.ValidatorProtoMsg): _90.Validator;
            toProto(message: _90.Validator): Uint8Array;
            toProtoMsg(message: _90.Validator): _90.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _90.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.ValidatorUpdate;
            fromPartial(object: Partial<_90.ValidatorUpdate>): _90.ValidatorUpdate;
            fromAmino(object: _90.ValidatorUpdateAmino): _90.ValidatorUpdate;
            toAmino(message: _90.ValidatorUpdate): _90.ValidatorUpdateAmino;
            fromAminoMsg(object: _90.ValidatorUpdateAminoMsg): _90.ValidatorUpdate;
            fromProtoMsg(message: _90.ValidatorUpdateProtoMsg): _90.ValidatorUpdate;
            toProto(message: _90.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _90.ValidatorUpdate): _90.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _90.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.VoteInfo;
            fromPartial(object: Partial<_90.VoteInfo>): _90.VoteInfo;
            fromAmino(object: _90.VoteInfoAmino): _90.VoteInfo;
            toAmino(message: _90.VoteInfo): _90.VoteInfoAmino;
            fromAminoMsg(object: _90.VoteInfoAminoMsg): _90.VoteInfo;
            fromProtoMsg(message: _90.VoteInfoProtoMsg): _90.VoteInfo;
            toProto(message: _90.VoteInfo): Uint8Array;
            toProtoMsg(message: _90.VoteInfo): _90.VoteInfoProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _90.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.Evidence;
            fromPartial(object: Partial<_90.Evidence>): _90.Evidence;
            fromAmino(object: _90.EvidenceAmino): _90.Evidence;
            toAmino(message: _90.Evidence): _90.EvidenceAmino;
            fromAminoMsg(object: _90.EvidenceAminoMsg): _90.Evidence;
            fromProtoMsg(message: _90.EvidenceProtoMsg): _90.Evidence;
            toProto(message: _90.Evidence): Uint8Array;
            toProtoMsg(message: _90.Evidence): _90.EvidenceProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _90.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _90.Snapshot;
            fromPartial(object: Partial<_90.Snapshot>): _90.Snapshot;
            fromAmino(object: _90.SnapshotAmino): _90.Snapshot;
            toAmino(message: _90.Snapshot): _90.SnapshotAmino;
            fromAminoMsg(object: _90.SnapshotAminoMsg): _90.Snapshot;
            fromProtoMsg(message: _90.SnapshotProtoMsg): _90.Snapshot;
            toProto(message: _90.Snapshot): Uint8Array;
            toProtoMsg(message: _90.Snapshot): _90.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _92.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _92.Proof;
            fromPartial(object: Partial<_92.Proof>): _92.Proof;
            fromAmino(object: _92.ProofAmino): _92.Proof;
            toAmino(message: _92.Proof): _92.ProofAmino;
            fromAminoMsg(object: _92.ProofAminoMsg): _92.Proof;
            fromProtoMsg(message: _92.ProofProtoMsg): _92.Proof;
            toProto(message: _92.Proof): Uint8Array;
            toProtoMsg(message: _92.Proof): _92.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _92.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _92.ValueOp;
            fromPartial(object: Partial<_92.ValueOp>): _92.ValueOp;
            fromAmino(object: _92.ValueOpAmino): _92.ValueOp;
            toAmino(message: _92.ValueOp): _92.ValueOpAmino;
            fromAminoMsg(object: _92.ValueOpAminoMsg): _92.ValueOp;
            fromProtoMsg(message: _92.ValueOpProtoMsg): _92.ValueOp;
            toProto(message: _92.ValueOp): Uint8Array;
            toProtoMsg(message: _92.ValueOp): _92.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _92.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _92.DominoOp;
            fromPartial(object: Partial<_92.DominoOp>): _92.DominoOp;
            fromAmino(object: _92.DominoOpAmino): _92.DominoOp;
            toAmino(message: _92.DominoOp): _92.DominoOpAmino;
            fromAminoMsg(object: _92.DominoOpAminoMsg): _92.DominoOp;
            fromProtoMsg(message: _92.DominoOpProtoMsg): _92.DominoOp;
            toProto(message: _92.DominoOp): Uint8Array;
            toProtoMsg(message: _92.DominoOp): _92.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _92.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _92.ProofOp;
            fromPartial(object: Partial<_92.ProofOp>): _92.ProofOp;
            fromAmino(object: _92.ProofOpAmino): _92.ProofOp;
            toAmino(message: _92.ProofOp): _92.ProofOpAmino;
            fromAminoMsg(object: _92.ProofOpAminoMsg): _92.ProofOp;
            fromProtoMsg(message: _92.ProofOpProtoMsg): _92.ProofOp;
            toProto(message: _92.ProofOp): Uint8Array;
            toProtoMsg(message: _92.ProofOp): _92.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _92.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _92.ProofOps;
            fromPartial(object: Partial<_92.ProofOps>): _92.ProofOps;
            fromAmino(object: _92.ProofOpsAmino): _92.ProofOps;
            toAmino(message: _92.ProofOps): _92.ProofOpsAmino;
            fromAminoMsg(object: _92.ProofOpsAminoMsg): _92.ProofOps;
            fromProtoMsg(message: _92.ProofOpsProtoMsg): _92.ProofOps;
            toProto(message: _92.ProofOps): Uint8Array;
            toProtoMsg(message: _92.ProofOps): _92.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _91.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _91.PublicKey;
            fromPartial(object: Partial<_91.PublicKey>): _91.PublicKey;
            fromAmino(object: _91.PublicKeyAmino): _91.PublicKey;
            toAmino(message: _91.PublicKey): _91.PublicKeyAmino;
            fromAminoMsg(object: _91.PublicKeyAminoMsg): _91.PublicKey;
            fromProtoMsg(message: _91.PublicKeyProtoMsg): _91.PublicKey;
            toProto(message: _91.PublicKey): Uint8Array;
            toProtoMsg(message: _91.PublicKey): _91.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _93.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                fromJSON(object: any): _93.BitArray;
                fromPartial(object: Partial<_93.BitArray>): _93.BitArray;
                fromAmino(object: _93.BitArrayAmino): _93.BitArray;
                toAmino(message: _93.BitArray): _93.BitArrayAmino;
                fromAminoMsg(object: _93.BitArrayAminoMsg): _93.BitArray;
                fromProtoMsg(message: _93.BitArrayProtoMsg): _93.BitArray;
                toProto(message: _93.BitArray): Uint8Array;
                toProtoMsg(message: _93.BitArray): _93.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _94.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _94.NetAddress;
            fromPartial(object: Partial<_94.NetAddress>): _94.NetAddress;
            fromAmino(object: _94.NetAddressAmino): _94.NetAddress;
            toAmino(message: _94.NetAddress): _94.NetAddressAmino;
            fromAminoMsg(object: _94.NetAddressAminoMsg): _94.NetAddress;
            fromProtoMsg(message: _94.NetAddressProtoMsg): _94.NetAddress;
            toProto(message: _94.NetAddress): Uint8Array;
            toProtoMsg(message: _94.NetAddress): _94.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _94.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _94.ProtocolVersion;
            fromPartial(object: Partial<_94.ProtocolVersion>): _94.ProtocolVersion;
            fromAmino(object: _94.ProtocolVersionAmino): _94.ProtocolVersion;
            toAmino(message: _94.ProtocolVersion): _94.ProtocolVersionAmino;
            fromAminoMsg(object: _94.ProtocolVersionAminoMsg): _94.ProtocolVersion;
            fromProtoMsg(message: _94.ProtocolVersionProtoMsg): _94.ProtocolVersion;
            toProto(message: _94.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _94.ProtocolVersion): _94.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _94.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _94.DefaultNodeInfo;
            fromPartial(object: Partial<_94.DefaultNodeInfo>): _94.DefaultNodeInfo;
            fromAmino(object: _94.DefaultNodeInfoAmino): _94.DefaultNodeInfo;
            toAmino(message: _94.DefaultNodeInfo): _94.DefaultNodeInfoAmino;
            fromAminoMsg(object: _94.DefaultNodeInfoAminoMsg): _94.DefaultNodeInfo;
            fromProtoMsg(message: _94.DefaultNodeInfoProtoMsg): _94.DefaultNodeInfo;
            toProto(message: _94.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _94.DefaultNodeInfo): _94.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _94.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _94.DefaultNodeInfoOther;
            fromPartial(object: Partial<_94.DefaultNodeInfoOther>): _94.DefaultNodeInfoOther;
            fromAmino(object: _94.DefaultNodeInfoOtherAmino): _94.DefaultNodeInfoOther;
            toAmino(message: _94.DefaultNodeInfoOther): _94.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _94.DefaultNodeInfoOtherAminoMsg): _94.DefaultNodeInfoOther;
            fromProtoMsg(message: _94.DefaultNodeInfoOtherProtoMsg): _94.DefaultNodeInfoOther;
            toProto(message: _94.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _94.DefaultNodeInfoOther): _94.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _99.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _99.ValidatorSet;
            fromPartial(object: Partial<_99.ValidatorSet>): _99.ValidatorSet;
            fromAmino(object: _99.ValidatorSetAmino): _99.ValidatorSet;
            toAmino(message: _99.ValidatorSet): _99.ValidatorSetAmino;
            fromAminoMsg(object: _99.ValidatorSetAminoMsg): _99.ValidatorSet;
            fromProtoMsg(message: _99.ValidatorSetProtoMsg): _99.ValidatorSet;
            toProto(message: _99.ValidatorSet): Uint8Array;
            toProtoMsg(message: _99.ValidatorSet): _99.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _99.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _99.Validator;
            fromPartial(object: Partial<_99.Validator>): _99.Validator;
            fromAmino(object: _99.ValidatorAmino): _99.Validator;
            toAmino(message: _99.Validator): _99.ValidatorAmino;
            fromAminoMsg(object: _99.ValidatorAminoMsg): _99.Validator;
            fromProtoMsg(message: _99.ValidatorProtoMsg): _99.Validator;
            toProto(message: _99.Validator): Uint8Array;
            toProtoMsg(message: _99.Validator): _99.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _99.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _99.SimpleValidator;
            fromPartial(object: Partial<_99.SimpleValidator>): _99.SimpleValidator;
            fromAmino(object: _99.SimpleValidatorAmino): _99.SimpleValidator;
            toAmino(message: _99.SimpleValidator): _99.SimpleValidatorAmino;
            fromAminoMsg(object: _99.SimpleValidatorAminoMsg): _99.SimpleValidator;
            fromProtoMsg(message: _99.SimpleValidatorProtoMsg): _99.SimpleValidator;
            toProto(message: _99.SimpleValidator): Uint8Array;
            toProtoMsg(message: _99.SimpleValidator): _99.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _98.BlockIDFlag;
        blockIDFlagToJSON(object: _98.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _98.SignedMsgType;
        signedMsgTypeToJSON(object: _98.SignedMsgType): string;
        BlockIDFlag: typeof _98.BlockIDFlag;
        BlockIDFlagSDKType: typeof _98.BlockIDFlag;
        BlockIDFlagAmino: typeof _98.BlockIDFlag;
        SignedMsgType: typeof _98.SignedMsgType;
        SignedMsgTypeSDKType: typeof _98.SignedMsgType;
        SignedMsgTypeAmino: typeof _98.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _98.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.PartSetHeader;
            fromPartial(object: Partial<_98.PartSetHeader>): _98.PartSetHeader;
            fromAmino(object: _98.PartSetHeaderAmino): _98.PartSetHeader;
            toAmino(message: _98.PartSetHeader): _98.PartSetHeaderAmino;
            fromAminoMsg(object: _98.PartSetHeaderAminoMsg): _98.PartSetHeader;
            fromProtoMsg(message: _98.PartSetHeaderProtoMsg): _98.PartSetHeader;
            toProto(message: _98.PartSetHeader): Uint8Array;
            toProtoMsg(message: _98.PartSetHeader): _98.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _98.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.Part;
            fromPartial(object: Partial<_98.Part>): _98.Part;
            fromAmino(object: _98.PartAmino): _98.Part;
            toAmino(message: _98.Part): _98.PartAmino;
            fromAminoMsg(object: _98.PartAminoMsg): _98.Part;
            fromProtoMsg(message: _98.PartProtoMsg): _98.Part;
            toProto(message: _98.Part): Uint8Array;
            toProtoMsg(message: _98.Part): _98.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _98.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.BlockID;
            fromPartial(object: Partial<_98.BlockID>): _98.BlockID;
            fromAmino(object: _98.BlockIDAmino): _98.BlockID;
            toAmino(message: _98.BlockID): _98.BlockIDAmino;
            fromAminoMsg(object: _98.BlockIDAminoMsg): _98.BlockID;
            fromProtoMsg(message: _98.BlockIDProtoMsg): _98.BlockID;
            toProto(message: _98.BlockID): Uint8Array;
            toProtoMsg(message: _98.BlockID): _98.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _98.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.Header;
            fromPartial(object: Partial<_98.Header>): _98.Header;
            fromAmino(object: _98.HeaderAmino): _98.Header;
            toAmino(message: _98.Header): _98.HeaderAmino;
            fromAminoMsg(object: _98.HeaderAminoMsg): _98.Header;
            fromProtoMsg(message: _98.HeaderProtoMsg): _98.Header;
            toProto(message: _98.Header): Uint8Array;
            toProtoMsg(message: _98.Header): _98.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _98.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.Data;
            fromPartial(object: Partial<_98.Data>): _98.Data;
            fromAmino(object: _98.DataAmino): _98.Data;
            toAmino(message: _98.Data): _98.DataAmino;
            fromAminoMsg(object: _98.DataAminoMsg): _98.Data;
            fromProtoMsg(message: _98.DataProtoMsg): _98.Data;
            toProto(message: _98.Data): Uint8Array;
            toProtoMsg(message: _98.Data): _98.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _98.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.Vote;
            fromPartial(object: Partial<_98.Vote>): _98.Vote;
            fromAmino(object: _98.VoteAmino): _98.Vote;
            toAmino(message: _98.Vote): _98.VoteAmino;
            fromAminoMsg(object: _98.VoteAminoMsg): _98.Vote;
            fromProtoMsg(message: _98.VoteProtoMsg): _98.Vote;
            toProto(message: _98.Vote): Uint8Array;
            toProtoMsg(message: _98.Vote): _98.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _98.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.Commit;
            fromPartial(object: Partial<_98.Commit>): _98.Commit;
            fromAmino(object: _98.CommitAmino): _98.Commit;
            toAmino(message: _98.Commit): _98.CommitAmino;
            fromAminoMsg(object: _98.CommitAminoMsg): _98.Commit;
            fromProtoMsg(message: _98.CommitProtoMsg): _98.Commit;
            toProto(message: _98.Commit): Uint8Array;
            toProtoMsg(message: _98.Commit): _98.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _98.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.CommitSig;
            fromPartial(object: Partial<_98.CommitSig>): _98.CommitSig;
            fromAmino(object: _98.CommitSigAmino): _98.CommitSig;
            toAmino(message: _98.CommitSig): _98.CommitSigAmino;
            fromAminoMsg(object: _98.CommitSigAminoMsg): _98.CommitSig;
            fromProtoMsg(message: _98.CommitSigProtoMsg): _98.CommitSig;
            toProto(message: _98.CommitSig): Uint8Array;
            toProtoMsg(message: _98.CommitSig): _98.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _98.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.Proposal;
            fromPartial(object: Partial<_98.Proposal>): _98.Proposal;
            fromAmino(object: _98.ProposalAmino): _98.Proposal;
            toAmino(message: _98.Proposal): _98.ProposalAmino;
            fromAminoMsg(object: _98.ProposalAminoMsg): _98.Proposal;
            fromProtoMsg(message: _98.ProposalProtoMsg): _98.Proposal;
            toProto(message: _98.Proposal): Uint8Array;
            toProtoMsg(message: _98.Proposal): _98.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _98.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.SignedHeader;
            fromPartial(object: Partial<_98.SignedHeader>): _98.SignedHeader;
            fromAmino(object: _98.SignedHeaderAmino): _98.SignedHeader;
            toAmino(message: _98.SignedHeader): _98.SignedHeaderAmino;
            fromAminoMsg(object: _98.SignedHeaderAminoMsg): _98.SignedHeader;
            fromProtoMsg(message: _98.SignedHeaderProtoMsg): _98.SignedHeader;
            toProto(message: _98.SignedHeader): Uint8Array;
            toProtoMsg(message: _98.SignedHeader): _98.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _98.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.LightBlock;
            fromPartial(object: Partial<_98.LightBlock>): _98.LightBlock;
            fromAmino(object: _98.LightBlockAmino): _98.LightBlock;
            toAmino(message: _98.LightBlock): _98.LightBlockAmino;
            fromAminoMsg(object: _98.LightBlockAminoMsg): _98.LightBlock;
            fromProtoMsg(message: _98.LightBlockProtoMsg): _98.LightBlock;
            toProto(message: _98.LightBlock): Uint8Array;
            toProtoMsg(message: _98.LightBlock): _98.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _98.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.BlockMeta;
            fromPartial(object: Partial<_98.BlockMeta>): _98.BlockMeta;
            fromAmino(object: _98.BlockMetaAmino): _98.BlockMeta;
            toAmino(message: _98.BlockMeta): _98.BlockMetaAmino;
            fromAminoMsg(object: _98.BlockMetaAminoMsg): _98.BlockMeta;
            fromProtoMsg(message: _98.BlockMetaProtoMsg): _98.BlockMeta;
            toProto(message: _98.BlockMeta): Uint8Array;
            toProtoMsg(message: _98.BlockMeta): _98.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _98.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _98.TxProof;
            fromPartial(object: Partial<_98.TxProof>): _98.TxProof;
            fromAmino(object: _98.TxProofAmino): _98.TxProof;
            toAmino(message: _98.TxProof): _98.TxProofAmino;
            fromAminoMsg(object: _98.TxProofAminoMsg): _98.TxProof;
            fromProtoMsg(message: _98.TxProofProtoMsg): _98.TxProof;
            toProto(message: _98.TxProof): Uint8Array;
            toProtoMsg(message: _98.TxProof): _98.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _97.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _97.ConsensusParams;
            fromPartial(object: Partial<_97.ConsensusParams>): _97.ConsensusParams;
            fromAmino(object: _97.ConsensusParamsAmino): _97.ConsensusParams;
            toAmino(message: _97.ConsensusParams): _97.ConsensusParamsAmino;
            fromAminoMsg(object: _97.ConsensusParamsAminoMsg): _97.ConsensusParams;
            fromProtoMsg(message: _97.ConsensusParamsProtoMsg): _97.ConsensusParams;
            toProto(message: _97.ConsensusParams): Uint8Array;
            toProtoMsg(message: _97.ConsensusParams): _97.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _97.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _97.BlockParams;
            fromPartial(object: Partial<_97.BlockParams>): _97.BlockParams;
            fromAmino(object: _97.BlockParamsAmino): _97.BlockParams;
            toAmino(message: _97.BlockParams): _97.BlockParamsAmino;
            fromAminoMsg(object: _97.BlockParamsAminoMsg): _97.BlockParams;
            fromProtoMsg(message: _97.BlockParamsProtoMsg): _97.BlockParams;
            toProto(message: _97.BlockParams): Uint8Array;
            toProtoMsg(message: _97.BlockParams): _97.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _97.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _97.EvidenceParams;
            fromPartial(object: Partial<_97.EvidenceParams>): _97.EvidenceParams;
            fromAmino(object: _97.EvidenceParamsAmino): _97.EvidenceParams;
            toAmino(message: _97.EvidenceParams): _97.EvidenceParamsAmino;
            fromAminoMsg(object: _97.EvidenceParamsAminoMsg): _97.EvidenceParams;
            fromProtoMsg(message: _97.EvidenceParamsProtoMsg): _97.EvidenceParams;
            toProto(message: _97.EvidenceParams): Uint8Array;
            toProtoMsg(message: _97.EvidenceParams): _97.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _97.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _97.ValidatorParams;
            fromPartial(object: Partial<_97.ValidatorParams>): _97.ValidatorParams;
            fromAmino(object: _97.ValidatorParamsAmino): _97.ValidatorParams;
            toAmino(message: _97.ValidatorParams): _97.ValidatorParamsAmino;
            fromAminoMsg(object: _97.ValidatorParamsAminoMsg): _97.ValidatorParams;
            fromProtoMsg(message: _97.ValidatorParamsProtoMsg): _97.ValidatorParams;
            toProto(message: _97.ValidatorParams): Uint8Array;
            toProtoMsg(message: _97.ValidatorParams): _97.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _97.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _97.VersionParams;
            fromPartial(object: Partial<_97.VersionParams>): _97.VersionParams;
            fromAmino(object: _97.VersionParamsAmino): _97.VersionParams;
            toAmino(message: _97.VersionParams): _97.VersionParamsAmino;
            fromAminoMsg(object: _97.VersionParamsAminoMsg): _97.VersionParams;
            fromProtoMsg(message: _97.VersionParamsProtoMsg): _97.VersionParams;
            toProto(message: _97.VersionParams): Uint8Array;
            toProtoMsg(message: _97.VersionParams): _97.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _97.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _97.HashedParams;
            fromPartial(object: Partial<_97.HashedParams>): _97.HashedParams;
            fromAmino(object: _97.HashedParamsAmino): _97.HashedParams;
            toAmino(message: _97.HashedParams): _97.HashedParamsAmino;
            fromAminoMsg(object: _97.HashedParamsAminoMsg): _97.HashedParams;
            fromProtoMsg(message: _97.HashedParamsProtoMsg): _97.HashedParams;
            toProto(message: _97.HashedParams): Uint8Array;
            toProtoMsg(message: _97.HashedParams): _97.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _96.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _96.Evidence;
            fromPartial(object: Partial<_96.Evidence>): _96.Evidence;
            fromAmino(object: _96.EvidenceAmino): _96.Evidence;
            toAmino(message: _96.Evidence): _96.EvidenceAmino;
            fromAminoMsg(object: _96.EvidenceAminoMsg): _96.Evidence;
            fromProtoMsg(message: _96.EvidenceProtoMsg): _96.Evidence;
            toProto(message: _96.Evidence): Uint8Array;
            toProtoMsg(message: _96.Evidence): _96.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _96.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _96.DuplicateVoteEvidence;
            fromPartial(object: Partial<_96.DuplicateVoteEvidence>): _96.DuplicateVoteEvidence;
            fromAmino(object: _96.DuplicateVoteEvidenceAmino): _96.DuplicateVoteEvidence;
            toAmino(message: _96.DuplicateVoteEvidence): _96.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _96.DuplicateVoteEvidenceAminoMsg): _96.DuplicateVoteEvidence;
            fromProtoMsg(message: _96.DuplicateVoteEvidenceProtoMsg): _96.DuplicateVoteEvidence;
            toProto(message: _96.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _96.DuplicateVoteEvidence): _96.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _96.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _96.LightClientAttackEvidence;
            fromPartial(object: Partial<_96.LightClientAttackEvidence>): _96.LightClientAttackEvidence;
            fromAmino(object: _96.LightClientAttackEvidenceAmino): _96.LightClientAttackEvidence;
            toAmino(message: _96.LightClientAttackEvidence): _96.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _96.LightClientAttackEvidenceAminoMsg): _96.LightClientAttackEvidence;
            fromProtoMsg(message: _96.LightClientAttackEvidenceProtoMsg): _96.LightClientAttackEvidence;
            toProto(message: _96.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _96.LightClientAttackEvidence): _96.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _96.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _96.EvidenceList;
            fromPartial(object: Partial<_96.EvidenceList>): _96.EvidenceList;
            fromAmino(object: _96.EvidenceListAmino): _96.EvidenceList;
            toAmino(message: _96.EvidenceList): _96.EvidenceListAmino;
            fromAminoMsg(object: _96.EvidenceListAminoMsg): _96.EvidenceList;
            fromProtoMsg(message: _96.EvidenceListProtoMsg): _96.EvidenceList;
            toProto(message: _96.EvidenceList): Uint8Array;
            toProtoMsg(message: _96.EvidenceList): _96.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _95.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _95.Block;
            fromPartial(object: Partial<_95.Block>): _95.Block;
            fromAmino(object: _95.BlockAmino): _95.Block;
            toAmino(message: _95.Block): _95.BlockAmino;
            fromAminoMsg(object: _95.BlockAminoMsg): _95.Block;
            fromProtoMsg(message: _95.BlockProtoMsg): _95.Block;
            toProto(message: _95.Block): Uint8Array;
            toProtoMsg(message: _95.Block): _95.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _100.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _100.App;
            fromPartial(object: Partial<_100.App>): _100.App;
            fromAmino(object: _100.AppAmino): _100.App;
            toAmino(message: _100.App): _100.AppAmino;
            fromAminoMsg(object: _100.AppAminoMsg): _100.App;
            fromProtoMsg(message: _100.AppProtoMsg): _100.App;
            toProto(message: _100.App): Uint8Array;
            toProtoMsg(message: _100.App): _100.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _100.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _100.Consensus;
            fromPartial(object: Partial<_100.Consensus>): _100.Consensus;
            fromAmino(object: _100.ConsensusAmino): _100.Consensus;
            toAmino(message: _100.Consensus): _100.ConsensusAmino;
            fromAminoMsg(object: _100.ConsensusAminoMsg): _100.Consensus;
            fromProtoMsg(message: _100.ConsensusProtoMsg): _100.Consensus;
            toProto(message: _100.Consensus): Uint8Array;
            toProtoMsg(message: _100.Consensus): _100.ConsensusProtoMsg;
        };
    };
}
