import * as _119 from "./abci/types";
import * as _120 from "./crypto/keys";
import * as _121 from "./crypto/proof";
import * as _122 from "./libs/bits/types";
import * as _123 from "./p2p/types";
import * as _124 from "./types/block";
import * as _125 from "./types/evidence";
import * as _126 from "./types/params";
import * as _127 from "./types/types";
import * as _128 from "./types/validator";
import * as _129 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _119.CheckTxType;
        checkTxTypeToJSON(object: _119.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _119.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _119.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _119.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _119.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _119.EvidenceType;
        evidenceTypeToJSON(object: _119.EvidenceType): string;
        CheckTxType: typeof _119.CheckTxType;
        CheckTxTypeSDKType: typeof _119.CheckTxType;
        CheckTxTypeAmino: typeof _119.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _119.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _119.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _119.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _119.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _119.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _119.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _119.EvidenceType;
        EvidenceTypeSDKType: typeof _119.EvidenceType;
        EvidenceTypeAmino: typeof _119.EvidenceType;
        Request: {
            typeUrl: string;
            encode(message: _119.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.Request;
            fromPartial(object: Partial<_119.Request>): _119.Request;
            fromAmino(object: _119.RequestAmino): _119.Request;
            toAmino(message: _119.Request): _119.RequestAmino;
            fromAminoMsg(object: _119.RequestAminoMsg): _119.Request;
            fromProtoMsg(message: _119.RequestProtoMsg): _119.Request;
            toProto(message: _119.Request): Uint8Array;
            toProtoMsg(message: _119.Request): _119.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _119.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.RequestEcho;
            fromPartial(object: Partial<_119.RequestEcho>): _119.RequestEcho;
            fromAmino(object: _119.RequestEchoAmino): _119.RequestEcho;
            toAmino(message: _119.RequestEcho): _119.RequestEchoAmino;
            fromAminoMsg(object: _119.RequestEchoAminoMsg): _119.RequestEcho;
            fromProtoMsg(message: _119.RequestEchoProtoMsg): _119.RequestEcho;
            toProto(message: _119.RequestEcho): Uint8Array;
            toProtoMsg(message: _119.RequestEcho): _119.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _119.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _119.RequestFlush;
            fromPartial(_: Partial<_119.RequestFlush>): _119.RequestFlush;
            fromAmino(_: _119.RequestFlushAmino): _119.RequestFlush;
            toAmino(_: _119.RequestFlush): _119.RequestFlushAmino;
            fromAminoMsg(object: _119.RequestFlushAminoMsg): _119.RequestFlush;
            fromProtoMsg(message: _119.RequestFlushProtoMsg): _119.RequestFlush;
            toProto(message: _119.RequestFlush): Uint8Array;
            toProtoMsg(message: _119.RequestFlush): _119.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _119.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.RequestInfo;
            fromPartial(object: Partial<_119.RequestInfo>): _119.RequestInfo;
            fromAmino(object: _119.RequestInfoAmino): _119.RequestInfo;
            toAmino(message: _119.RequestInfo): _119.RequestInfoAmino;
            fromAminoMsg(object: _119.RequestInfoAminoMsg): _119.RequestInfo;
            fromProtoMsg(message: _119.RequestInfoProtoMsg): _119.RequestInfo;
            toProto(message: _119.RequestInfo): Uint8Array;
            toProtoMsg(message: _119.RequestInfo): _119.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            typeUrl: string;
            encode(message: _119.RequestSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.RequestSetOption;
            fromPartial(object: Partial<_119.RequestSetOption>): _119.RequestSetOption;
            fromAmino(object: _119.RequestSetOptionAmino): _119.RequestSetOption;
            toAmino(message: _119.RequestSetOption): _119.RequestSetOptionAmino;
            fromAminoMsg(object: _119.RequestSetOptionAminoMsg): _119.RequestSetOption;
            fromProtoMsg(message: _119.RequestSetOptionProtoMsg): _119.RequestSetOption;
            toProto(message: _119.RequestSetOption): Uint8Array;
            toProtoMsg(message: _119.RequestSetOption): _119.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _119.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.RequestInitChain;
            fromPartial(object: Partial<_119.RequestInitChain>): _119.RequestInitChain;
            fromAmino(object: _119.RequestInitChainAmino): _119.RequestInitChain;
            toAmino(message: _119.RequestInitChain): _119.RequestInitChainAmino;
            fromAminoMsg(object: _119.RequestInitChainAminoMsg): _119.RequestInitChain;
            fromProtoMsg(message: _119.RequestInitChainProtoMsg): _119.RequestInitChain;
            toProto(message: _119.RequestInitChain): Uint8Array;
            toProtoMsg(message: _119.RequestInitChain): _119.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _119.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.RequestQuery;
            fromPartial(object: Partial<_119.RequestQuery>): _119.RequestQuery;
            fromAmino(object: _119.RequestQueryAmino): _119.RequestQuery;
            toAmino(message: _119.RequestQuery): _119.RequestQueryAmino;
            fromAminoMsg(object: _119.RequestQueryAminoMsg): _119.RequestQuery;
            fromProtoMsg(message: _119.RequestQueryProtoMsg): _119.RequestQuery;
            toProto(message: _119.RequestQuery): Uint8Array;
            toProtoMsg(message: _119.RequestQuery): _119.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _119.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.RequestBeginBlock;
            fromPartial(object: Partial<_119.RequestBeginBlock>): _119.RequestBeginBlock;
            fromAmino(object: _119.RequestBeginBlockAmino): _119.RequestBeginBlock;
            toAmino(message: _119.RequestBeginBlock): _119.RequestBeginBlockAmino;
            fromAminoMsg(object: _119.RequestBeginBlockAminoMsg): _119.RequestBeginBlock;
            fromProtoMsg(message: _119.RequestBeginBlockProtoMsg): _119.RequestBeginBlock;
            toProto(message: _119.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _119.RequestBeginBlock): _119.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _119.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.RequestCheckTx;
            fromPartial(object: Partial<_119.RequestCheckTx>): _119.RequestCheckTx;
            fromAmino(object: _119.RequestCheckTxAmino): _119.RequestCheckTx;
            toAmino(message: _119.RequestCheckTx): _119.RequestCheckTxAmino;
            fromAminoMsg(object: _119.RequestCheckTxAminoMsg): _119.RequestCheckTx;
            fromProtoMsg(message: _119.RequestCheckTxProtoMsg): _119.RequestCheckTx;
            toProto(message: _119.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _119.RequestCheckTx): _119.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _119.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.RequestDeliverTx;
            fromPartial(object: Partial<_119.RequestDeliverTx>): _119.RequestDeliverTx;
            fromAmino(object: _119.RequestDeliverTxAmino): _119.RequestDeliverTx;
            toAmino(message: _119.RequestDeliverTx): _119.RequestDeliverTxAmino;
            fromAminoMsg(object: _119.RequestDeliverTxAminoMsg): _119.RequestDeliverTx;
            fromProtoMsg(message: _119.RequestDeliverTxProtoMsg): _119.RequestDeliverTx;
            toProto(message: _119.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _119.RequestDeliverTx): _119.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _119.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.RequestEndBlock;
            fromPartial(object: Partial<_119.RequestEndBlock>): _119.RequestEndBlock;
            fromAmino(object: _119.RequestEndBlockAmino): _119.RequestEndBlock;
            toAmino(message: _119.RequestEndBlock): _119.RequestEndBlockAmino;
            fromAminoMsg(object: _119.RequestEndBlockAminoMsg): _119.RequestEndBlock;
            fromProtoMsg(message: _119.RequestEndBlockProtoMsg): _119.RequestEndBlock;
            toProto(message: _119.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _119.RequestEndBlock): _119.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _119.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _119.RequestCommit;
            fromPartial(_: Partial<_119.RequestCommit>): _119.RequestCommit;
            fromAmino(_: _119.RequestCommitAmino): _119.RequestCommit;
            toAmino(_: _119.RequestCommit): _119.RequestCommitAmino;
            fromAminoMsg(object: _119.RequestCommitAminoMsg): _119.RequestCommit;
            fromProtoMsg(message: _119.RequestCommitProtoMsg): _119.RequestCommit;
            toProto(message: _119.RequestCommit): Uint8Array;
            toProtoMsg(message: _119.RequestCommit): _119.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _119.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _119.RequestListSnapshots;
            fromPartial(_: Partial<_119.RequestListSnapshots>): _119.RequestListSnapshots;
            fromAmino(_: _119.RequestListSnapshotsAmino): _119.RequestListSnapshots;
            toAmino(_: _119.RequestListSnapshots): _119.RequestListSnapshotsAmino;
            fromAminoMsg(object: _119.RequestListSnapshotsAminoMsg): _119.RequestListSnapshots;
            fromProtoMsg(message: _119.RequestListSnapshotsProtoMsg): _119.RequestListSnapshots;
            toProto(message: _119.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _119.RequestListSnapshots): _119.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _119.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.RequestOfferSnapshot;
            fromPartial(object: Partial<_119.RequestOfferSnapshot>): _119.RequestOfferSnapshot;
            fromAmino(object: _119.RequestOfferSnapshotAmino): _119.RequestOfferSnapshot;
            toAmino(message: _119.RequestOfferSnapshot): _119.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _119.RequestOfferSnapshotAminoMsg): _119.RequestOfferSnapshot;
            fromProtoMsg(message: _119.RequestOfferSnapshotProtoMsg): _119.RequestOfferSnapshot;
            toProto(message: _119.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _119.RequestOfferSnapshot): _119.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _119.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_119.RequestLoadSnapshotChunk>): _119.RequestLoadSnapshotChunk;
            fromAmino(object: _119.RequestLoadSnapshotChunkAmino): _119.RequestLoadSnapshotChunk;
            toAmino(message: _119.RequestLoadSnapshotChunk): _119.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _119.RequestLoadSnapshotChunkAminoMsg): _119.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _119.RequestLoadSnapshotChunkProtoMsg): _119.RequestLoadSnapshotChunk;
            toProto(message: _119.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _119.RequestLoadSnapshotChunk): _119.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _119.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_119.RequestApplySnapshotChunk>): _119.RequestApplySnapshotChunk;
            fromAmino(object: _119.RequestApplySnapshotChunkAmino): _119.RequestApplySnapshotChunk;
            toAmino(message: _119.RequestApplySnapshotChunk): _119.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _119.RequestApplySnapshotChunkAminoMsg): _119.RequestApplySnapshotChunk;
            fromProtoMsg(message: _119.RequestApplySnapshotChunkProtoMsg): _119.RequestApplySnapshotChunk;
            toProto(message: _119.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _119.RequestApplySnapshotChunk): _119.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _119.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.Response;
            fromPartial(object: Partial<_119.Response>): _119.Response;
            fromAmino(object: _119.ResponseAmino): _119.Response;
            toAmino(message: _119.Response): _119.ResponseAmino;
            fromAminoMsg(object: _119.ResponseAminoMsg): _119.Response;
            fromProtoMsg(message: _119.ResponseProtoMsg): _119.Response;
            toProto(message: _119.Response): Uint8Array;
            toProtoMsg(message: _119.Response): _119.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _119.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseException;
            fromPartial(object: Partial<_119.ResponseException>): _119.ResponseException;
            fromAmino(object: _119.ResponseExceptionAmino): _119.ResponseException;
            toAmino(message: _119.ResponseException): _119.ResponseExceptionAmino;
            fromAminoMsg(object: _119.ResponseExceptionAminoMsg): _119.ResponseException;
            fromProtoMsg(message: _119.ResponseExceptionProtoMsg): _119.ResponseException;
            toProto(message: _119.ResponseException): Uint8Array;
            toProtoMsg(message: _119.ResponseException): _119.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _119.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseEcho;
            fromPartial(object: Partial<_119.ResponseEcho>): _119.ResponseEcho;
            fromAmino(object: _119.ResponseEchoAmino): _119.ResponseEcho;
            toAmino(message: _119.ResponseEcho): _119.ResponseEchoAmino;
            fromAminoMsg(object: _119.ResponseEchoAminoMsg): _119.ResponseEcho;
            fromProtoMsg(message: _119.ResponseEchoProtoMsg): _119.ResponseEcho;
            toProto(message: _119.ResponseEcho): Uint8Array;
            toProtoMsg(message: _119.ResponseEcho): _119.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _119.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _119.ResponseFlush;
            fromPartial(_: Partial<_119.ResponseFlush>): _119.ResponseFlush;
            fromAmino(_: _119.ResponseFlushAmino): _119.ResponseFlush;
            toAmino(_: _119.ResponseFlush): _119.ResponseFlushAmino;
            fromAminoMsg(object: _119.ResponseFlushAminoMsg): _119.ResponseFlush;
            fromProtoMsg(message: _119.ResponseFlushProtoMsg): _119.ResponseFlush;
            toProto(message: _119.ResponseFlush): Uint8Array;
            toProtoMsg(message: _119.ResponseFlush): _119.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _119.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseInfo;
            fromPartial(object: Partial<_119.ResponseInfo>): _119.ResponseInfo;
            fromAmino(object: _119.ResponseInfoAmino): _119.ResponseInfo;
            toAmino(message: _119.ResponseInfo): _119.ResponseInfoAmino;
            fromAminoMsg(object: _119.ResponseInfoAminoMsg): _119.ResponseInfo;
            fromProtoMsg(message: _119.ResponseInfoProtoMsg): _119.ResponseInfo;
            toProto(message: _119.ResponseInfo): Uint8Array;
            toProtoMsg(message: _119.ResponseInfo): _119.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            typeUrl: string;
            encode(message: _119.ResponseSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseSetOption;
            fromPartial(object: Partial<_119.ResponseSetOption>): _119.ResponseSetOption;
            fromAmino(object: _119.ResponseSetOptionAmino): _119.ResponseSetOption;
            toAmino(message: _119.ResponseSetOption): _119.ResponseSetOptionAmino;
            fromAminoMsg(object: _119.ResponseSetOptionAminoMsg): _119.ResponseSetOption;
            fromProtoMsg(message: _119.ResponseSetOptionProtoMsg): _119.ResponseSetOption;
            toProto(message: _119.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _119.ResponseSetOption): _119.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _119.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseInitChain;
            fromPartial(object: Partial<_119.ResponseInitChain>): _119.ResponseInitChain;
            fromAmino(object: _119.ResponseInitChainAmino): _119.ResponseInitChain;
            toAmino(message: _119.ResponseInitChain): _119.ResponseInitChainAmino;
            fromAminoMsg(object: _119.ResponseInitChainAminoMsg): _119.ResponseInitChain;
            fromProtoMsg(message: _119.ResponseInitChainProtoMsg): _119.ResponseInitChain;
            toProto(message: _119.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _119.ResponseInitChain): _119.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _119.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseQuery;
            fromPartial(object: Partial<_119.ResponseQuery>): _119.ResponseQuery;
            fromAmino(object: _119.ResponseQueryAmino): _119.ResponseQuery;
            toAmino(message: _119.ResponseQuery): _119.ResponseQueryAmino;
            fromAminoMsg(object: _119.ResponseQueryAminoMsg): _119.ResponseQuery;
            fromProtoMsg(message: _119.ResponseQueryProtoMsg): _119.ResponseQuery;
            toProto(message: _119.ResponseQuery): Uint8Array;
            toProtoMsg(message: _119.ResponseQuery): _119.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _119.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseBeginBlock;
            fromPartial(object: Partial<_119.ResponseBeginBlock>): _119.ResponseBeginBlock;
            fromAmino(object: _119.ResponseBeginBlockAmino): _119.ResponseBeginBlock;
            toAmino(message: _119.ResponseBeginBlock): _119.ResponseBeginBlockAmino;
            fromAminoMsg(object: _119.ResponseBeginBlockAminoMsg): _119.ResponseBeginBlock;
            fromProtoMsg(message: _119.ResponseBeginBlockProtoMsg): _119.ResponseBeginBlock;
            toProto(message: _119.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _119.ResponseBeginBlock): _119.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _119.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseCheckTx;
            fromPartial(object: Partial<_119.ResponseCheckTx>): _119.ResponseCheckTx;
            fromAmino(object: _119.ResponseCheckTxAmino): _119.ResponseCheckTx;
            toAmino(message: _119.ResponseCheckTx): _119.ResponseCheckTxAmino;
            fromAminoMsg(object: _119.ResponseCheckTxAminoMsg): _119.ResponseCheckTx;
            fromProtoMsg(message: _119.ResponseCheckTxProtoMsg): _119.ResponseCheckTx;
            toProto(message: _119.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _119.ResponseCheckTx): _119.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _119.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseDeliverTx;
            fromPartial(object: Partial<_119.ResponseDeliverTx>): _119.ResponseDeliverTx;
            fromAmino(object: _119.ResponseDeliverTxAmino): _119.ResponseDeliverTx;
            toAmino(message: _119.ResponseDeliverTx): _119.ResponseDeliverTxAmino;
            fromAminoMsg(object: _119.ResponseDeliverTxAminoMsg): _119.ResponseDeliverTx;
            fromProtoMsg(message: _119.ResponseDeliverTxProtoMsg): _119.ResponseDeliverTx;
            toProto(message: _119.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _119.ResponseDeliverTx): _119.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _119.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseEndBlock;
            fromPartial(object: Partial<_119.ResponseEndBlock>): _119.ResponseEndBlock;
            fromAmino(object: _119.ResponseEndBlockAmino): _119.ResponseEndBlock;
            toAmino(message: _119.ResponseEndBlock): _119.ResponseEndBlockAmino;
            fromAminoMsg(object: _119.ResponseEndBlockAminoMsg): _119.ResponseEndBlock;
            fromProtoMsg(message: _119.ResponseEndBlockProtoMsg): _119.ResponseEndBlock;
            toProto(message: _119.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _119.ResponseEndBlock): _119.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _119.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseCommit;
            fromPartial(object: Partial<_119.ResponseCommit>): _119.ResponseCommit;
            fromAmino(object: _119.ResponseCommitAmino): _119.ResponseCommit;
            toAmino(message: _119.ResponseCommit): _119.ResponseCommitAmino;
            fromAminoMsg(object: _119.ResponseCommitAminoMsg): _119.ResponseCommit;
            fromProtoMsg(message: _119.ResponseCommitProtoMsg): _119.ResponseCommit;
            toProto(message: _119.ResponseCommit): Uint8Array;
            toProtoMsg(message: _119.ResponseCommit): _119.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _119.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseListSnapshots;
            fromPartial(object: Partial<_119.ResponseListSnapshots>): _119.ResponseListSnapshots;
            fromAmino(object: _119.ResponseListSnapshotsAmino): _119.ResponseListSnapshots;
            toAmino(message: _119.ResponseListSnapshots): _119.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _119.ResponseListSnapshotsAminoMsg): _119.ResponseListSnapshots;
            fromProtoMsg(message: _119.ResponseListSnapshotsProtoMsg): _119.ResponseListSnapshots;
            toProto(message: _119.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _119.ResponseListSnapshots): _119.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _119.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseOfferSnapshot;
            fromPartial(object: Partial<_119.ResponseOfferSnapshot>): _119.ResponseOfferSnapshot;
            fromAmino(object: _119.ResponseOfferSnapshotAmino): _119.ResponseOfferSnapshot;
            toAmino(message: _119.ResponseOfferSnapshot): _119.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _119.ResponseOfferSnapshotAminoMsg): _119.ResponseOfferSnapshot;
            fromProtoMsg(message: _119.ResponseOfferSnapshotProtoMsg): _119.ResponseOfferSnapshot;
            toProto(message: _119.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _119.ResponseOfferSnapshot): _119.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _119.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_119.ResponseLoadSnapshotChunk>): _119.ResponseLoadSnapshotChunk;
            fromAmino(object: _119.ResponseLoadSnapshotChunkAmino): _119.ResponseLoadSnapshotChunk;
            toAmino(message: _119.ResponseLoadSnapshotChunk): _119.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _119.ResponseLoadSnapshotChunkAminoMsg): _119.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _119.ResponseLoadSnapshotChunkProtoMsg): _119.ResponseLoadSnapshotChunk;
            toProto(message: _119.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _119.ResponseLoadSnapshotChunk): _119.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _119.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_119.ResponseApplySnapshotChunk>): _119.ResponseApplySnapshotChunk;
            fromAmino(object: _119.ResponseApplySnapshotChunkAmino): _119.ResponseApplySnapshotChunk;
            toAmino(message: _119.ResponseApplySnapshotChunk): _119.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _119.ResponseApplySnapshotChunkAminoMsg): _119.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _119.ResponseApplySnapshotChunkProtoMsg): _119.ResponseApplySnapshotChunk;
            toProto(message: _119.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _119.ResponseApplySnapshotChunk): _119.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _119.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ConsensusParams;
            fromPartial(object: Partial<_119.ConsensusParams>): _119.ConsensusParams;
            fromAmino(object: _119.ConsensusParamsAmino): _119.ConsensusParams;
            toAmino(message: _119.ConsensusParams): _119.ConsensusParamsAmino;
            fromAminoMsg(object: _119.ConsensusParamsAminoMsg): _119.ConsensusParams;
            fromProtoMsg(message: _119.ConsensusParamsProtoMsg): _119.ConsensusParams;
            toProto(message: _119.ConsensusParams): Uint8Array;
            toProtoMsg(message: _119.ConsensusParams): _119.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _119.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.BlockParams;
            fromPartial(object: Partial<_119.BlockParams>): _119.BlockParams;
            fromAmino(object: _119.BlockParamsAmino): _119.BlockParams;
            toAmino(message: _119.BlockParams): _119.BlockParamsAmino;
            fromAminoMsg(object: _119.BlockParamsAminoMsg): _119.BlockParams;
            fromProtoMsg(message: _119.BlockParamsProtoMsg): _119.BlockParams;
            toProto(message: _119.BlockParams): Uint8Array;
            toProtoMsg(message: _119.BlockParams): _119.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            typeUrl: string;
            encode(message: _119.LastCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.LastCommitInfo;
            fromPartial(object: Partial<_119.LastCommitInfo>): _119.LastCommitInfo;
            fromAmino(object: _119.LastCommitInfoAmino): _119.LastCommitInfo;
            toAmino(message: _119.LastCommitInfo): _119.LastCommitInfoAmino;
            fromAminoMsg(object: _119.LastCommitInfoAminoMsg): _119.LastCommitInfo;
            fromProtoMsg(message: _119.LastCommitInfoProtoMsg): _119.LastCommitInfo;
            toProto(message: _119.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _119.LastCommitInfo): _119.LastCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _119.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.Event;
            fromPartial(object: Partial<_119.Event>): _119.Event;
            fromAmino(object: _119.EventAmino): _119.Event;
            toAmino(message: _119.Event): _119.EventAmino;
            fromAminoMsg(object: _119.EventAminoMsg): _119.Event;
            fromProtoMsg(message: _119.EventProtoMsg): _119.Event;
            toProto(message: _119.Event): Uint8Array;
            toProtoMsg(message: _119.Event): _119.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _119.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.EventAttribute;
            fromPartial(object: Partial<_119.EventAttribute>): _119.EventAttribute;
            fromAmino(object: _119.EventAttributeAmino): _119.EventAttribute;
            toAmino(message: _119.EventAttribute): _119.EventAttributeAmino;
            fromAminoMsg(object: _119.EventAttributeAminoMsg): _119.EventAttribute;
            fromProtoMsg(message: _119.EventAttributeProtoMsg): _119.EventAttribute;
            toProto(message: _119.EventAttribute): Uint8Array;
            toProtoMsg(message: _119.EventAttribute): _119.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _119.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.TxResult;
            fromPartial(object: Partial<_119.TxResult>): _119.TxResult;
            fromAmino(object: _119.TxResultAmino): _119.TxResult;
            toAmino(message: _119.TxResult): _119.TxResultAmino;
            fromAminoMsg(object: _119.TxResultAminoMsg): _119.TxResult;
            fromProtoMsg(message: _119.TxResultProtoMsg): _119.TxResult;
            toProto(message: _119.TxResult): Uint8Array;
            toProtoMsg(message: _119.TxResult): _119.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _119.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.Validator;
            fromPartial(object: Partial<_119.Validator>): _119.Validator;
            fromAmino(object: _119.ValidatorAmino): _119.Validator;
            toAmino(message: _119.Validator): _119.ValidatorAmino;
            fromAminoMsg(object: _119.ValidatorAminoMsg): _119.Validator;
            fromProtoMsg(message: _119.ValidatorProtoMsg): _119.Validator;
            toProto(message: _119.Validator): Uint8Array;
            toProtoMsg(message: _119.Validator): _119.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _119.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.ValidatorUpdate;
            fromPartial(object: Partial<_119.ValidatorUpdate>): _119.ValidatorUpdate;
            fromAmino(object: _119.ValidatorUpdateAmino): _119.ValidatorUpdate;
            toAmino(message: _119.ValidatorUpdate): _119.ValidatorUpdateAmino;
            fromAminoMsg(object: _119.ValidatorUpdateAminoMsg): _119.ValidatorUpdate;
            fromProtoMsg(message: _119.ValidatorUpdateProtoMsg): _119.ValidatorUpdate;
            toProto(message: _119.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _119.ValidatorUpdate): _119.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _119.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.VoteInfo;
            fromPartial(object: Partial<_119.VoteInfo>): _119.VoteInfo;
            fromAmino(object: _119.VoteInfoAmino): _119.VoteInfo;
            toAmino(message: _119.VoteInfo): _119.VoteInfoAmino;
            fromAminoMsg(object: _119.VoteInfoAminoMsg): _119.VoteInfo;
            fromProtoMsg(message: _119.VoteInfoProtoMsg): _119.VoteInfo;
            toProto(message: _119.VoteInfo): Uint8Array;
            toProtoMsg(message: _119.VoteInfo): _119.VoteInfoProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _119.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.Evidence;
            fromPartial(object: Partial<_119.Evidence>): _119.Evidence;
            fromAmino(object: _119.EvidenceAmino): _119.Evidence;
            toAmino(message: _119.Evidence): _119.EvidenceAmino;
            fromAminoMsg(object: _119.EvidenceAminoMsg): _119.Evidence;
            fromProtoMsg(message: _119.EvidenceProtoMsg): _119.Evidence;
            toProto(message: _119.Evidence): Uint8Array;
            toProtoMsg(message: _119.Evidence): _119.EvidenceProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _119.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.Snapshot;
            fromPartial(object: Partial<_119.Snapshot>): _119.Snapshot;
            fromAmino(object: _119.SnapshotAmino): _119.Snapshot;
            toAmino(message: _119.Snapshot): _119.SnapshotAmino;
            fromAminoMsg(object: _119.SnapshotAminoMsg): _119.Snapshot;
            fromProtoMsg(message: _119.SnapshotProtoMsg): _119.Snapshot;
            toProto(message: _119.Snapshot): Uint8Array;
            toProtoMsg(message: _119.Snapshot): _119.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _121.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _121.Proof;
            fromPartial(object: Partial<_121.Proof>): _121.Proof;
            fromAmino(object: _121.ProofAmino): _121.Proof;
            toAmino(message: _121.Proof): _121.ProofAmino;
            fromAminoMsg(object: _121.ProofAminoMsg): _121.Proof;
            fromProtoMsg(message: _121.ProofProtoMsg): _121.Proof;
            toProto(message: _121.Proof): Uint8Array;
            toProtoMsg(message: _121.Proof): _121.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _121.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _121.ValueOp;
            fromPartial(object: Partial<_121.ValueOp>): _121.ValueOp;
            fromAmino(object: _121.ValueOpAmino): _121.ValueOp;
            toAmino(message: _121.ValueOp): _121.ValueOpAmino;
            fromAminoMsg(object: _121.ValueOpAminoMsg): _121.ValueOp;
            fromProtoMsg(message: _121.ValueOpProtoMsg): _121.ValueOp;
            toProto(message: _121.ValueOp): Uint8Array;
            toProtoMsg(message: _121.ValueOp): _121.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _121.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _121.DominoOp;
            fromPartial(object: Partial<_121.DominoOp>): _121.DominoOp;
            fromAmino(object: _121.DominoOpAmino): _121.DominoOp;
            toAmino(message: _121.DominoOp): _121.DominoOpAmino;
            fromAminoMsg(object: _121.DominoOpAminoMsg): _121.DominoOp;
            fromProtoMsg(message: _121.DominoOpProtoMsg): _121.DominoOp;
            toProto(message: _121.DominoOp): Uint8Array;
            toProtoMsg(message: _121.DominoOp): _121.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _121.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _121.ProofOp;
            fromPartial(object: Partial<_121.ProofOp>): _121.ProofOp;
            fromAmino(object: _121.ProofOpAmino): _121.ProofOp;
            toAmino(message: _121.ProofOp): _121.ProofOpAmino;
            fromAminoMsg(object: _121.ProofOpAminoMsg): _121.ProofOp;
            fromProtoMsg(message: _121.ProofOpProtoMsg): _121.ProofOp;
            toProto(message: _121.ProofOp): Uint8Array;
            toProtoMsg(message: _121.ProofOp): _121.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _121.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _121.ProofOps;
            fromPartial(object: Partial<_121.ProofOps>): _121.ProofOps;
            fromAmino(object: _121.ProofOpsAmino): _121.ProofOps;
            toAmino(message: _121.ProofOps): _121.ProofOpsAmino;
            fromAminoMsg(object: _121.ProofOpsAminoMsg): _121.ProofOps;
            fromProtoMsg(message: _121.ProofOpsProtoMsg): _121.ProofOps;
            toProto(message: _121.ProofOps): Uint8Array;
            toProtoMsg(message: _121.ProofOps): _121.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _120.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _120.PublicKey;
            fromPartial(object: Partial<_120.PublicKey>): _120.PublicKey;
            fromAmino(object: _120.PublicKeyAmino): _120.PublicKey;
            toAmino(message: _120.PublicKey): _120.PublicKeyAmino;
            fromAminoMsg(object: _120.PublicKeyAminoMsg): _120.PublicKey;
            fromProtoMsg(message: _120.PublicKeyProtoMsg): _120.PublicKey;
            toProto(message: _120.PublicKey): Uint8Array;
            toProtoMsg(message: _120.PublicKey): _120.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _122.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                fromJSON(object: any): _122.BitArray;
                fromPartial(object: Partial<_122.BitArray>): _122.BitArray;
                fromAmino(object: _122.BitArrayAmino): _122.BitArray;
                toAmino(message: _122.BitArray): _122.BitArrayAmino;
                fromAminoMsg(object: _122.BitArrayAminoMsg): _122.BitArray;
                fromProtoMsg(message: _122.BitArrayProtoMsg): _122.BitArray;
                toProto(message: _122.BitArray): Uint8Array;
                toProtoMsg(message: _122.BitArray): _122.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _123.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _123.NetAddress;
            fromPartial(object: Partial<_123.NetAddress>): _123.NetAddress;
            fromAmino(object: _123.NetAddressAmino): _123.NetAddress;
            toAmino(message: _123.NetAddress): _123.NetAddressAmino;
            fromAminoMsg(object: _123.NetAddressAminoMsg): _123.NetAddress;
            fromProtoMsg(message: _123.NetAddressProtoMsg): _123.NetAddress;
            toProto(message: _123.NetAddress): Uint8Array;
            toProtoMsg(message: _123.NetAddress): _123.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _123.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _123.ProtocolVersion;
            fromPartial(object: Partial<_123.ProtocolVersion>): _123.ProtocolVersion;
            fromAmino(object: _123.ProtocolVersionAmino): _123.ProtocolVersion;
            toAmino(message: _123.ProtocolVersion): _123.ProtocolVersionAmino;
            fromAminoMsg(object: _123.ProtocolVersionAminoMsg): _123.ProtocolVersion;
            fromProtoMsg(message: _123.ProtocolVersionProtoMsg): _123.ProtocolVersion;
            toProto(message: _123.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _123.ProtocolVersion): _123.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _123.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _123.DefaultNodeInfo;
            fromPartial(object: Partial<_123.DefaultNodeInfo>): _123.DefaultNodeInfo;
            fromAmino(object: _123.DefaultNodeInfoAmino): _123.DefaultNodeInfo;
            toAmino(message: _123.DefaultNodeInfo): _123.DefaultNodeInfoAmino;
            fromAminoMsg(object: _123.DefaultNodeInfoAminoMsg): _123.DefaultNodeInfo;
            fromProtoMsg(message: _123.DefaultNodeInfoProtoMsg): _123.DefaultNodeInfo;
            toProto(message: _123.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _123.DefaultNodeInfo): _123.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _123.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _123.DefaultNodeInfoOther;
            fromPartial(object: Partial<_123.DefaultNodeInfoOther>): _123.DefaultNodeInfoOther;
            fromAmino(object: _123.DefaultNodeInfoOtherAmino): _123.DefaultNodeInfoOther;
            toAmino(message: _123.DefaultNodeInfoOther): _123.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _123.DefaultNodeInfoOtherAminoMsg): _123.DefaultNodeInfoOther;
            fromProtoMsg(message: _123.DefaultNodeInfoOtherProtoMsg): _123.DefaultNodeInfoOther;
            toProto(message: _123.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _123.DefaultNodeInfoOther): _123.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _128.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _128.ValidatorSet;
            fromPartial(object: Partial<_128.ValidatorSet>): _128.ValidatorSet;
            fromAmino(object: _128.ValidatorSetAmino): _128.ValidatorSet;
            toAmino(message: _128.ValidatorSet): _128.ValidatorSetAmino;
            fromAminoMsg(object: _128.ValidatorSetAminoMsg): _128.ValidatorSet;
            fromProtoMsg(message: _128.ValidatorSetProtoMsg): _128.ValidatorSet;
            toProto(message: _128.ValidatorSet): Uint8Array;
            toProtoMsg(message: _128.ValidatorSet): _128.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _128.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _128.Validator;
            fromPartial(object: Partial<_128.Validator>): _128.Validator;
            fromAmino(object: _128.ValidatorAmino): _128.Validator;
            toAmino(message: _128.Validator): _128.ValidatorAmino;
            fromAminoMsg(object: _128.ValidatorAminoMsg): _128.Validator;
            fromProtoMsg(message: _128.ValidatorProtoMsg): _128.Validator;
            toProto(message: _128.Validator): Uint8Array;
            toProtoMsg(message: _128.Validator): _128.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _128.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _128.SimpleValidator;
            fromPartial(object: Partial<_128.SimpleValidator>): _128.SimpleValidator;
            fromAmino(object: _128.SimpleValidatorAmino): _128.SimpleValidator;
            toAmino(message: _128.SimpleValidator): _128.SimpleValidatorAmino;
            fromAminoMsg(object: _128.SimpleValidatorAminoMsg): _128.SimpleValidator;
            fromProtoMsg(message: _128.SimpleValidatorProtoMsg): _128.SimpleValidator;
            toProto(message: _128.SimpleValidator): Uint8Array;
            toProtoMsg(message: _128.SimpleValidator): _128.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _127.BlockIDFlag;
        blockIDFlagToJSON(object: _127.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _127.SignedMsgType;
        signedMsgTypeToJSON(object: _127.SignedMsgType): string;
        BlockIDFlag: typeof _127.BlockIDFlag;
        BlockIDFlagSDKType: typeof _127.BlockIDFlag;
        BlockIDFlagAmino: typeof _127.BlockIDFlag;
        SignedMsgType: typeof _127.SignedMsgType;
        SignedMsgTypeSDKType: typeof _127.SignedMsgType;
        SignedMsgTypeAmino: typeof _127.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _127.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.PartSetHeader;
            fromPartial(object: Partial<_127.PartSetHeader>): _127.PartSetHeader;
            fromAmino(object: _127.PartSetHeaderAmino): _127.PartSetHeader;
            toAmino(message: _127.PartSetHeader): _127.PartSetHeaderAmino;
            fromAminoMsg(object: _127.PartSetHeaderAminoMsg): _127.PartSetHeader;
            fromProtoMsg(message: _127.PartSetHeaderProtoMsg): _127.PartSetHeader;
            toProto(message: _127.PartSetHeader): Uint8Array;
            toProtoMsg(message: _127.PartSetHeader): _127.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _127.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.Part;
            fromPartial(object: Partial<_127.Part>): _127.Part;
            fromAmino(object: _127.PartAmino): _127.Part;
            toAmino(message: _127.Part): _127.PartAmino;
            fromAminoMsg(object: _127.PartAminoMsg): _127.Part;
            fromProtoMsg(message: _127.PartProtoMsg): _127.Part;
            toProto(message: _127.Part): Uint8Array;
            toProtoMsg(message: _127.Part): _127.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _127.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.BlockID;
            fromPartial(object: Partial<_127.BlockID>): _127.BlockID;
            fromAmino(object: _127.BlockIDAmino): _127.BlockID;
            toAmino(message: _127.BlockID): _127.BlockIDAmino;
            fromAminoMsg(object: _127.BlockIDAminoMsg): _127.BlockID;
            fromProtoMsg(message: _127.BlockIDProtoMsg): _127.BlockID;
            toProto(message: _127.BlockID): Uint8Array;
            toProtoMsg(message: _127.BlockID): _127.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _127.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.Header;
            fromPartial(object: Partial<_127.Header>): _127.Header;
            fromAmino(object: _127.HeaderAmino): _127.Header;
            toAmino(message: _127.Header): _127.HeaderAmino;
            fromAminoMsg(object: _127.HeaderAminoMsg): _127.Header;
            fromProtoMsg(message: _127.HeaderProtoMsg): _127.Header;
            toProto(message: _127.Header): Uint8Array;
            toProtoMsg(message: _127.Header): _127.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _127.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.Data;
            fromPartial(object: Partial<_127.Data>): _127.Data;
            fromAmino(object: _127.DataAmino): _127.Data;
            toAmino(message: _127.Data): _127.DataAmino;
            fromAminoMsg(object: _127.DataAminoMsg): _127.Data;
            fromProtoMsg(message: _127.DataProtoMsg): _127.Data;
            toProto(message: _127.Data): Uint8Array;
            toProtoMsg(message: _127.Data): _127.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _127.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.Vote;
            fromPartial(object: Partial<_127.Vote>): _127.Vote;
            fromAmino(object: _127.VoteAmino): _127.Vote;
            toAmino(message: _127.Vote): _127.VoteAmino;
            fromAminoMsg(object: _127.VoteAminoMsg): _127.Vote;
            fromProtoMsg(message: _127.VoteProtoMsg): _127.Vote;
            toProto(message: _127.Vote): Uint8Array;
            toProtoMsg(message: _127.Vote): _127.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _127.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.Commit;
            fromPartial(object: Partial<_127.Commit>): _127.Commit;
            fromAmino(object: _127.CommitAmino): _127.Commit;
            toAmino(message: _127.Commit): _127.CommitAmino;
            fromAminoMsg(object: _127.CommitAminoMsg): _127.Commit;
            fromProtoMsg(message: _127.CommitProtoMsg): _127.Commit;
            toProto(message: _127.Commit): Uint8Array;
            toProtoMsg(message: _127.Commit): _127.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _127.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.CommitSig;
            fromPartial(object: Partial<_127.CommitSig>): _127.CommitSig;
            fromAmino(object: _127.CommitSigAmino): _127.CommitSig;
            toAmino(message: _127.CommitSig): _127.CommitSigAmino;
            fromAminoMsg(object: _127.CommitSigAminoMsg): _127.CommitSig;
            fromProtoMsg(message: _127.CommitSigProtoMsg): _127.CommitSig;
            toProto(message: _127.CommitSig): Uint8Array;
            toProtoMsg(message: _127.CommitSig): _127.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _127.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.Proposal;
            fromPartial(object: Partial<_127.Proposal>): _127.Proposal;
            fromAmino(object: _127.ProposalAmino): _127.Proposal;
            toAmino(message: _127.Proposal): _127.ProposalAmino;
            fromAminoMsg(object: _127.ProposalAminoMsg): _127.Proposal;
            fromProtoMsg(message: _127.ProposalProtoMsg): _127.Proposal;
            toProto(message: _127.Proposal): Uint8Array;
            toProtoMsg(message: _127.Proposal): _127.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _127.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.SignedHeader;
            fromPartial(object: Partial<_127.SignedHeader>): _127.SignedHeader;
            fromAmino(object: _127.SignedHeaderAmino): _127.SignedHeader;
            toAmino(message: _127.SignedHeader): _127.SignedHeaderAmino;
            fromAminoMsg(object: _127.SignedHeaderAminoMsg): _127.SignedHeader;
            fromProtoMsg(message: _127.SignedHeaderProtoMsg): _127.SignedHeader;
            toProto(message: _127.SignedHeader): Uint8Array;
            toProtoMsg(message: _127.SignedHeader): _127.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _127.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.LightBlock;
            fromPartial(object: Partial<_127.LightBlock>): _127.LightBlock;
            fromAmino(object: _127.LightBlockAmino): _127.LightBlock;
            toAmino(message: _127.LightBlock): _127.LightBlockAmino;
            fromAminoMsg(object: _127.LightBlockAminoMsg): _127.LightBlock;
            fromProtoMsg(message: _127.LightBlockProtoMsg): _127.LightBlock;
            toProto(message: _127.LightBlock): Uint8Array;
            toProtoMsg(message: _127.LightBlock): _127.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _127.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.BlockMeta;
            fromPartial(object: Partial<_127.BlockMeta>): _127.BlockMeta;
            fromAmino(object: _127.BlockMetaAmino): _127.BlockMeta;
            toAmino(message: _127.BlockMeta): _127.BlockMetaAmino;
            fromAminoMsg(object: _127.BlockMetaAminoMsg): _127.BlockMeta;
            fromProtoMsg(message: _127.BlockMetaProtoMsg): _127.BlockMeta;
            toProto(message: _127.BlockMeta): Uint8Array;
            toProtoMsg(message: _127.BlockMeta): _127.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _127.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.TxProof;
            fromPartial(object: Partial<_127.TxProof>): _127.TxProof;
            fromAmino(object: _127.TxProofAmino): _127.TxProof;
            toAmino(message: _127.TxProof): _127.TxProofAmino;
            fromAminoMsg(object: _127.TxProofAminoMsg): _127.TxProof;
            fromProtoMsg(message: _127.TxProofProtoMsg): _127.TxProof;
            toProto(message: _127.TxProof): Uint8Array;
            toProtoMsg(message: _127.TxProof): _127.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _126.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ConsensusParams;
            fromPartial(object: Partial<_126.ConsensusParams>): _126.ConsensusParams;
            fromAmino(object: _126.ConsensusParamsAmino): _126.ConsensusParams;
            toAmino(message: _126.ConsensusParams): _126.ConsensusParamsAmino;
            fromAminoMsg(object: _126.ConsensusParamsAminoMsg): _126.ConsensusParams;
            fromProtoMsg(message: _126.ConsensusParamsProtoMsg): _126.ConsensusParams;
            toProto(message: _126.ConsensusParams): Uint8Array;
            toProtoMsg(message: _126.ConsensusParams): _126.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _126.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.BlockParams;
            fromPartial(object: Partial<_126.BlockParams>): _126.BlockParams;
            fromAmino(object: _126.BlockParamsAmino): _126.BlockParams;
            toAmino(message: _126.BlockParams): _126.BlockParamsAmino;
            fromAminoMsg(object: _126.BlockParamsAminoMsg): _126.BlockParams;
            fromProtoMsg(message: _126.BlockParamsProtoMsg): _126.BlockParams;
            toProto(message: _126.BlockParams): Uint8Array;
            toProtoMsg(message: _126.BlockParams): _126.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _126.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.EvidenceParams;
            fromPartial(object: Partial<_126.EvidenceParams>): _126.EvidenceParams;
            fromAmino(object: _126.EvidenceParamsAmino): _126.EvidenceParams;
            toAmino(message: _126.EvidenceParams): _126.EvidenceParamsAmino;
            fromAminoMsg(object: _126.EvidenceParamsAminoMsg): _126.EvidenceParams;
            fromProtoMsg(message: _126.EvidenceParamsProtoMsg): _126.EvidenceParams;
            toProto(message: _126.EvidenceParams): Uint8Array;
            toProtoMsg(message: _126.EvidenceParams): _126.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _126.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.ValidatorParams;
            fromPartial(object: Partial<_126.ValidatorParams>): _126.ValidatorParams;
            fromAmino(object: _126.ValidatorParamsAmino): _126.ValidatorParams;
            toAmino(message: _126.ValidatorParams): _126.ValidatorParamsAmino;
            fromAminoMsg(object: _126.ValidatorParamsAminoMsg): _126.ValidatorParams;
            fromProtoMsg(message: _126.ValidatorParamsProtoMsg): _126.ValidatorParams;
            toProto(message: _126.ValidatorParams): Uint8Array;
            toProtoMsg(message: _126.ValidatorParams): _126.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _126.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.VersionParams;
            fromPartial(object: Partial<_126.VersionParams>): _126.VersionParams;
            fromAmino(object: _126.VersionParamsAmino): _126.VersionParams;
            toAmino(message: _126.VersionParams): _126.VersionParamsAmino;
            fromAminoMsg(object: _126.VersionParamsAminoMsg): _126.VersionParams;
            fromProtoMsg(message: _126.VersionParamsProtoMsg): _126.VersionParams;
            toProto(message: _126.VersionParams): Uint8Array;
            toProtoMsg(message: _126.VersionParams): _126.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _126.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.HashedParams;
            fromPartial(object: Partial<_126.HashedParams>): _126.HashedParams;
            fromAmino(object: _126.HashedParamsAmino): _126.HashedParams;
            toAmino(message: _126.HashedParams): _126.HashedParamsAmino;
            fromAminoMsg(object: _126.HashedParamsAminoMsg): _126.HashedParams;
            fromProtoMsg(message: _126.HashedParamsProtoMsg): _126.HashedParams;
            toProto(message: _126.HashedParams): Uint8Array;
            toProtoMsg(message: _126.HashedParams): _126.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _125.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _125.Evidence;
            fromPartial(object: Partial<_125.Evidence>): _125.Evidence;
            fromAmino(object: _125.EvidenceAmino): _125.Evidence;
            toAmino(message: _125.Evidence): _125.EvidenceAmino;
            fromAminoMsg(object: _125.EvidenceAminoMsg): _125.Evidence;
            fromProtoMsg(message: _125.EvidenceProtoMsg): _125.Evidence;
            toProto(message: _125.Evidence): Uint8Array;
            toProtoMsg(message: _125.Evidence): _125.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _125.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _125.DuplicateVoteEvidence;
            fromPartial(object: Partial<_125.DuplicateVoteEvidence>): _125.DuplicateVoteEvidence;
            fromAmino(object: _125.DuplicateVoteEvidenceAmino): _125.DuplicateVoteEvidence;
            toAmino(message: _125.DuplicateVoteEvidence): _125.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _125.DuplicateVoteEvidenceAminoMsg): _125.DuplicateVoteEvidence;
            fromProtoMsg(message: _125.DuplicateVoteEvidenceProtoMsg): _125.DuplicateVoteEvidence;
            toProto(message: _125.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _125.DuplicateVoteEvidence): _125.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _125.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _125.LightClientAttackEvidence;
            fromPartial(object: Partial<_125.LightClientAttackEvidence>): _125.LightClientAttackEvidence;
            fromAmino(object: _125.LightClientAttackEvidenceAmino): _125.LightClientAttackEvidence;
            toAmino(message: _125.LightClientAttackEvidence): _125.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _125.LightClientAttackEvidenceAminoMsg): _125.LightClientAttackEvidence;
            fromProtoMsg(message: _125.LightClientAttackEvidenceProtoMsg): _125.LightClientAttackEvidence;
            toProto(message: _125.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _125.LightClientAttackEvidence): _125.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _125.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _125.EvidenceList;
            fromPartial(object: Partial<_125.EvidenceList>): _125.EvidenceList;
            fromAmino(object: _125.EvidenceListAmino): _125.EvidenceList;
            toAmino(message: _125.EvidenceList): _125.EvidenceListAmino;
            fromAminoMsg(object: _125.EvidenceListAminoMsg): _125.EvidenceList;
            fromProtoMsg(message: _125.EvidenceListProtoMsg): _125.EvidenceList;
            toProto(message: _125.EvidenceList): Uint8Array;
            toProtoMsg(message: _125.EvidenceList): _125.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _124.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.Block;
            fromPartial(object: Partial<_124.Block>): _124.Block;
            fromAmino(object: _124.BlockAmino): _124.Block;
            toAmino(message: _124.Block): _124.BlockAmino;
            fromAminoMsg(object: _124.BlockAminoMsg): _124.Block;
            fromProtoMsg(message: _124.BlockProtoMsg): _124.Block;
            toProto(message: _124.Block): Uint8Array;
            toProtoMsg(message: _124.Block): _124.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _129.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _129.App;
            fromPartial(object: Partial<_129.App>): _129.App;
            fromAmino(object: _129.AppAmino): _129.App;
            toAmino(message: _129.App): _129.AppAmino;
            fromAminoMsg(object: _129.AppAminoMsg): _129.App;
            fromProtoMsg(message: _129.AppProtoMsg): _129.App;
            toProto(message: _129.App): Uint8Array;
            toProtoMsg(message: _129.App): _129.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _129.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _129.Consensus;
            fromPartial(object: Partial<_129.Consensus>): _129.Consensus;
            fromAmino(object: _129.ConsensusAmino): _129.Consensus;
            toAmino(message: _129.Consensus): _129.ConsensusAmino;
            fromAminoMsg(object: _129.ConsensusAminoMsg): _129.Consensus;
            fromProtoMsg(message: _129.ConsensusProtoMsg): _129.Consensus;
            toProto(message: _129.Consensus): Uint8Array;
            toProtoMsg(message: _129.Consensus): _129.ConsensusProtoMsg;
        };
    };
}
