import * as _208 from "./api/http";
import * as _209 from "./protobuf/timestamp";
import * as _210 from "./protobuf/any";
import * as _211 from "./protobuf/duration";
import * as _212 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _208.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _208.Http;
            fromPartial(object: Partial<_208.Http>): _208.Http;
            fromAmino(object: _208.HttpAmino): _208.Http;
            toAmino(message: _208.Http): _208.HttpAmino;
            fromAminoMsg(object: _208.HttpAminoMsg): _208.Http;
            fromProtoMsg(message: _208.HttpProtoMsg): _208.Http;
            toProto(message: _208.Http): Uint8Array;
            toProtoMsg(message: _208.Http): _208.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _208.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _208.HttpRule;
            fromPartial(object: Partial<_208.HttpRule>): _208.HttpRule;
            fromAmino(object: _208.HttpRuleAmino): _208.HttpRule;
            toAmino(message: _208.HttpRule): _208.HttpRuleAmino;
            fromAminoMsg(object: _208.HttpRuleAminoMsg): _208.HttpRule;
            fromProtoMsg(message: _208.HttpRuleProtoMsg): _208.HttpRule;
            toProto(message: _208.HttpRule): Uint8Array;
            toProtoMsg(message: _208.HttpRule): _208.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _208.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _208.CustomHttpPattern;
            fromPartial(object: Partial<_208.CustomHttpPattern>): _208.CustomHttpPattern;
            fromAmino(object: _208.CustomHttpPatternAmino): _208.CustomHttpPattern;
            toAmino(message: _208.CustomHttpPattern): _208.CustomHttpPatternAmino;
            fromAminoMsg(object: _208.CustomHttpPatternAminoMsg): _208.CustomHttpPattern;
            fromProtoMsg(message: _208.CustomHttpPatternProtoMsg): _208.CustomHttpPattern;
            toProto(message: _208.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _208.CustomHttpPattern): _208.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _212.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _212.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _212.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _212.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _212.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _212.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _212.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _212.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _212.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _212.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _212.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _212.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _212.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _212.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _212.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _212.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _212.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _212.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _212.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _212.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _212.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _212.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _212.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _212.FieldOptions_CType;
        FieldOptions_JSType: typeof _212.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _212.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _212.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _212.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _212.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _212.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _212.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.FileDescriptorSet;
            fromPartial(object: Partial<_212.FileDescriptorSet>): _212.FileDescriptorSet;
            fromAmino(object: _212.FileDescriptorSetAmino): _212.FileDescriptorSet;
            toAmino(message: _212.FileDescriptorSet): _212.FileDescriptorSetAmino;
            fromAminoMsg(object: _212.FileDescriptorSetAminoMsg): _212.FileDescriptorSet;
            fromProtoMsg(message: _212.FileDescriptorSetProtoMsg): _212.FileDescriptorSet;
            toProto(message: _212.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _212.FileDescriptorSet): _212.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _212.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.FileDescriptorProto;
            fromPartial(object: Partial<_212.FileDescriptorProto>): _212.FileDescriptorProto;
            fromAmino(object: _212.FileDescriptorProtoAmino): _212.FileDescriptorProto;
            toAmino(message: _212.FileDescriptorProto): _212.FileDescriptorProtoAmino;
            fromAminoMsg(object: _212.FileDescriptorProtoAminoMsg): _212.FileDescriptorProto;
            fromProtoMsg(message: _212.FileDescriptorProtoProtoMsg): _212.FileDescriptorProto;
            toProto(message: _212.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _212.FileDescriptorProto): _212.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _212.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.DescriptorProto;
            fromPartial(object: Partial<_212.DescriptorProto>): _212.DescriptorProto;
            fromAmino(object: _212.DescriptorProtoAmino): _212.DescriptorProto;
            toAmino(message: _212.DescriptorProto): _212.DescriptorProtoAmino;
            fromAminoMsg(object: _212.DescriptorProtoAminoMsg): _212.DescriptorProto;
            fromProtoMsg(message: _212.DescriptorProtoProtoMsg): _212.DescriptorProto;
            toProto(message: _212.DescriptorProto): Uint8Array;
            toProtoMsg(message: _212.DescriptorProto): _212.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _212.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_212.DescriptorProto_ExtensionRange>): _212.DescriptorProto_ExtensionRange;
            fromAmino(object: _212.DescriptorProto_ExtensionRangeAmino): _212.DescriptorProto_ExtensionRange;
            toAmino(message: _212.DescriptorProto_ExtensionRange): _212.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _212.DescriptorProto_ExtensionRangeAminoMsg): _212.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _212.DescriptorProto_ExtensionRangeProtoMsg): _212.DescriptorProto_ExtensionRange;
            toProto(message: _212.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _212.DescriptorProto_ExtensionRange): _212.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _212.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_212.DescriptorProto_ReservedRange>): _212.DescriptorProto_ReservedRange;
            fromAmino(object: _212.DescriptorProto_ReservedRangeAmino): _212.DescriptorProto_ReservedRange;
            toAmino(message: _212.DescriptorProto_ReservedRange): _212.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _212.DescriptorProto_ReservedRangeAminoMsg): _212.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _212.DescriptorProto_ReservedRangeProtoMsg): _212.DescriptorProto_ReservedRange;
            toProto(message: _212.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _212.DescriptorProto_ReservedRange): _212.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _212.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.ExtensionRangeOptions;
            fromPartial(object: Partial<_212.ExtensionRangeOptions>): _212.ExtensionRangeOptions;
            fromAmino(object: _212.ExtensionRangeOptionsAmino): _212.ExtensionRangeOptions;
            toAmino(message: _212.ExtensionRangeOptions): _212.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _212.ExtensionRangeOptionsAminoMsg): _212.ExtensionRangeOptions;
            fromProtoMsg(message: _212.ExtensionRangeOptionsProtoMsg): _212.ExtensionRangeOptions;
            toProto(message: _212.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _212.ExtensionRangeOptions): _212.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _212.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.FieldDescriptorProto;
            fromPartial(object: Partial<_212.FieldDescriptorProto>): _212.FieldDescriptorProto;
            fromAmino(object: _212.FieldDescriptorProtoAmino): _212.FieldDescriptorProto;
            toAmino(message: _212.FieldDescriptorProto): _212.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _212.FieldDescriptorProtoAminoMsg): _212.FieldDescriptorProto;
            fromProtoMsg(message: _212.FieldDescriptorProtoProtoMsg): _212.FieldDescriptorProto;
            toProto(message: _212.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _212.FieldDescriptorProto): _212.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _212.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.OneofDescriptorProto;
            fromPartial(object: Partial<_212.OneofDescriptorProto>): _212.OneofDescriptorProto;
            fromAmino(object: _212.OneofDescriptorProtoAmino): _212.OneofDescriptorProto;
            toAmino(message: _212.OneofDescriptorProto): _212.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _212.OneofDescriptorProtoAminoMsg): _212.OneofDescriptorProto;
            fromProtoMsg(message: _212.OneofDescriptorProtoProtoMsg): _212.OneofDescriptorProto;
            toProto(message: _212.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _212.OneofDescriptorProto): _212.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _212.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.EnumDescriptorProto;
            fromPartial(object: Partial<_212.EnumDescriptorProto>): _212.EnumDescriptorProto;
            fromAmino(object: _212.EnumDescriptorProtoAmino): _212.EnumDescriptorProto;
            toAmino(message: _212.EnumDescriptorProto): _212.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _212.EnumDescriptorProtoAminoMsg): _212.EnumDescriptorProto;
            fromProtoMsg(message: _212.EnumDescriptorProtoProtoMsg): _212.EnumDescriptorProto;
            toProto(message: _212.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _212.EnumDescriptorProto): _212.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _212.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_212.EnumDescriptorProto_EnumReservedRange>): _212.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _212.EnumDescriptorProto_EnumReservedRangeAmino): _212.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _212.EnumDescriptorProto_EnumReservedRange): _212.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _212.EnumDescriptorProto_EnumReservedRangeAminoMsg): _212.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _212.EnumDescriptorProto_EnumReservedRangeProtoMsg): _212.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _212.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _212.EnumDescriptorProto_EnumReservedRange): _212.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _212.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.EnumValueDescriptorProto;
            fromPartial(object: Partial<_212.EnumValueDescriptorProto>): _212.EnumValueDescriptorProto;
            fromAmino(object: _212.EnumValueDescriptorProtoAmino): _212.EnumValueDescriptorProto;
            toAmino(message: _212.EnumValueDescriptorProto): _212.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _212.EnumValueDescriptorProtoAminoMsg): _212.EnumValueDescriptorProto;
            fromProtoMsg(message: _212.EnumValueDescriptorProtoProtoMsg): _212.EnumValueDescriptorProto;
            toProto(message: _212.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _212.EnumValueDescriptorProto): _212.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _212.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.ServiceDescriptorProto;
            fromPartial(object: Partial<_212.ServiceDescriptorProto>): _212.ServiceDescriptorProto;
            fromAmino(object: _212.ServiceDescriptorProtoAmino): _212.ServiceDescriptorProto;
            toAmino(message: _212.ServiceDescriptorProto): _212.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _212.ServiceDescriptorProtoAminoMsg): _212.ServiceDescriptorProto;
            fromProtoMsg(message: _212.ServiceDescriptorProtoProtoMsg): _212.ServiceDescriptorProto;
            toProto(message: _212.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _212.ServiceDescriptorProto): _212.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _212.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.MethodDescriptorProto;
            fromPartial(object: Partial<_212.MethodDescriptorProto>): _212.MethodDescriptorProto;
            fromAmino(object: _212.MethodDescriptorProtoAmino): _212.MethodDescriptorProto;
            toAmino(message: _212.MethodDescriptorProto): _212.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _212.MethodDescriptorProtoAminoMsg): _212.MethodDescriptorProto;
            fromProtoMsg(message: _212.MethodDescriptorProtoProtoMsg): _212.MethodDescriptorProto;
            toProto(message: _212.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _212.MethodDescriptorProto): _212.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _212.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.FileOptions;
            fromPartial(object: Partial<_212.FileOptions>): _212.FileOptions;
            fromAmino(object: _212.FileOptionsAmino): _212.FileOptions;
            toAmino(message: _212.FileOptions): _212.FileOptionsAmino;
            fromAminoMsg(object: _212.FileOptionsAminoMsg): _212.FileOptions;
            fromProtoMsg(message: _212.FileOptionsProtoMsg): _212.FileOptions;
            toProto(message: _212.FileOptions): Uint8Array;
            toProtoMsg(message: _212.FileOptions): _212.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _212.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.MessageOptions;
            fromPartial(object: Partial<_212.MessageOptions>): _212.MessageOptions;
            fromAmino(object: _212.MessageOptionsAmino): _212.MessageOptions;
            toAmino(message: _212.MessageOptions): _212.MessageOptionsAmino;
            fromAminoMsg(object: _212.MessageOptionsAminoMsg): _212.MessageOptions;
            fromProtoMsg(message: _212.MessageOptionsProtoMsg): _212.MessageOptions;
            toProto(message: _212.MessageOptions): Uint8Array;
            toProtoMsg(message: _212.MessageOptions): _212.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _212.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.FieldOptions;
            fromPartial(object: Partial<_212.FieldOptions>): _212.FieldOptions;
            fromAmino(object: _212.FieldOptionsAmino): _212.FieldOptions;
            toAmino(message: _212.FieldOptions): _212.FieldOptionsAmino;
            fromAminoMsg(object: _212.FieldOptionsAminoMsg): _212.FieldOptions;
            fromProtoMsg(message: _212.FieldOptionsProtoMsg): _212.FieldOptions;
            toProto(message: _212.FieldOptions): Uint8Array;
            toProtoMsg(message: _212.FieldOptions): _212.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _212.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.OneofOptions;
            fromPartial(object: Partial<_212.OneofOptions>): _212.OneofOptions;
            fromAmino(object: _212.OneofOptionsAmino): _212.OneofOptions;
            toAmino(message: _212.OneofOptions): _212.OneofOptionsAmino;
            fromAminoMsg(object: _212.OneofOptionsAminoMsg): _212.OneofOptions;
            fromProtoMsg(message: _212.OneofOptionsProtoMsg): _212.OneofOptions;
            toProto(message: _212.OneofOptions): Uint8Array;
            toProtoMsg(message: _212.OneofOptions): _212.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _212.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.EnumOptions;
            fromPartial(object: Partial<_212.EnumOptions>): _212.EnumOptions;
            fromAmino(object: _212.EnumOptionsAmino): _212.EnumOptions;
            toAmino(message: _212.EnumOptions): _212.EnumOptionsAmino;
            fromAminoMsg(object: _212.EnumOptionsAminoMsg): _212.EnumOptions;
            fromProtoMsg(message: _212.EnumOptionsProtoMsg): _212.EnumOptions;
            toProto(message: _212.EnumOptions): Uint8Array;
            toProtoMsg(message: _212.EnumOptions): _212.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _212.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.EnumValueOptions;
            fromPartial(object: Partial<_212.EnumValueOptions>): _212.EnumValueOptions;
            fromAmino(object: _212.EnumValueOptionsAmino): _212.EnumValueOptions;
            toAmino(message: _212.EnumValueOptions): _212.EnumValueOptionsAmino;
            fromAminoMsg(object: _212.EnumValueOptionsAminoMsg): _212.EnumValueOptions;
            fromProtoMsg(message: _212.EnumValueOptionsProtoMsg): _212.EnumValueOptions;
            toProto(message: _212.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _212.EnumValueOptions): _212.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _212.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.ServiceOptions;
            fromPartial(object: Partial<_212.ServiceOptions>): _212.ServiceOptions;
            fromAmino(object: _212.ServiceOptionsAmino): _212.ServiceOptions;
            toAmino(message: _212.ServiceOptions): _212.ServiceOptionsAmino;
            fromAminoMsg(object: _212.ServiceOptionsAminoMsg): _212.ServiceOptions;
            fromProtoMsg(message: _212.ServiceOptionsProtoMsg): _212.ServiceOptions;
            toProto(message: _212.ServiceOptions): Uint8Array;
            toProtoMsg(message: _212.ServiceOptions): _212.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _212.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.MethodOptions;
            fromPartial(object: Partial<_212.MethodOptions>): _212.MethodOptions;
            fromAmino(object: _212.MethodOptionsAmino): _212.MethodOptions;
            toAmino(message: _212.MethodOptions): _212.MethodOptionsAmino;
            fromAminoMsg(object: _212.MethodOptionsAminoMsg): _212.MethodOptions;
            fromProtoMsg(message: _212.MethodOptionsProtoMsg): _212.MethodOptions;
            toProto(message: _212.MethodOptions): Uint8Array;
            toProtoMsg(message: _212.MethodOptions): _212.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _212.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.UninterpretedOption;
            fromPartial(object: Partial<_212.UninterpretedOption>): _212.UninterpretedOption;
            fromAmino(object: _212.UninterpretedOptionAmino): _212.UninterpretedOption;
            toAmino(message: _212.UninterpretedOption): _212.UninterpretedOptionAmino;
            fromAminoMsg(object: _212.UninterpretedOptionAminoMsg): _212.UninterpretedOption;
            fromProtoMsg(message: _212.UninterpretedOptionProtoMsg): _212.UninterpretedOption;
            toProto(message: _212.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _212.UninterpretedOption): _212.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _212.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_212.UninterpretedOption_NamePart>): _212.UninterpretedOption_NamePart;
            fromAmino(object: _212.UninterpretedOption_NamePartAmino): _212.UninterpretedOption_NamePart;
            toAmino(message: _212.UninterpretedOption_NamePart): _212.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _212.UninterpretedOption_NamePartAminoMsg): _212.UninterpretedOption_NamePart;
            fromProtoMsg(message: _212.UninterpretedOption_NamePartProtoMsg): _212.UninterpretedOption_NamePart;
            toProto(message: _212.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _212.UninterpretedOption_NamePart): _212.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _212.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.SourceCodeInfo;
            fromPartial(object: Partial<_212.SourceCodeInfo>): _212.SourceCodeInfo;
            fromAmino(object: _212.SourceCodeInfoAmino): _212.SourceCodeInfo;
            toAmino(message: _212.SourceCodeInfo): _212.SourceCodeInfoAmino;
            fromAminoMsg(object: _212.SourceCodeInfoAminoMsg): _212.SourceCodeInfo;
            fromProtoMsg(message: _212.SourceCodeInfoProtoMsg): _212.SourceCodeInfo;
            toProto(message: _212.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _212.SourceCodeInfo): _212.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _212.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.SourceCodeInfo_Location;
            fromPartial(object: Partial<_212.SourceCodeInfo_Location>): _212.SourceCodeInfo_Location;
            fromAmino(object: _212.SourceCodeInfo_LocationAmino): _212.SourceCodeInfo_Location;
            toAmino(message: _212.SourceCodeInfo_Location): _212.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _212.SourceCodeInfo_LocationAminoMsg): _212.SourceCodeInfo_Location;
            fromProtoMsg(message: _212.SourceCodeInfo_LocationProtoMsg): _212.SourceCodeInfo_Location;
            toProto(message: _212.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _212.SourceCodeInfo_Location): _212.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _212.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.GeneratedCodeInfo;
            fromPartial(object: Partial<_212.GeneratedCodeInfo>): _212.GeneratedCodeInfo;
            fromAmino(object: _212.GeneratedCodeInfoAmino): _212.GeneratedCodeInfo;
            toAmino(message: _212.GeneratedCodeInfo): _212.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _212.GeneratedCodeInfoAminoMsg): _212.GeneratedCodeInfo;
            fromProtoMsg(message: _212.GeneratedCodeInfoProtoMsg): _212.GeneratedCodeInfo;
            toProto(message: _212.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _212.GeneratedCodeInfo): _212.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _212.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _212.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_212.GeneratedCodeInfo_Annotation>): _212.GeneratedCodeInfo_Annotation;
            fromAmino(object: _212.GeneratedCodeInfo_AnnotationAmino): _212.GeneratedCodeInfo_Annotation;
            toAmino(message: _212.GeneratedCodeInfo_Annotation): _212.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _212.GeneratedCodeInfo_AnnotationAminoMsg): _212.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _212.GeneratedCodeInfo_AnnotationProtoMsg): _212.GeneratedCodeInfo_Annotation;
            toProto(message: _212.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _212.GeneratedCodeInfo_Annotation): _212.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _211.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _211.Duration;
            fromPartial(object: Partial<_211.Duration>): _211.Duration;
            fromAmino(object: string): _211.Duration;
            toAmino(message: _211.Duration): string;
            fromAminoMsg(object: _211.DurationAminoMsg): _211.Duration;
            fromProtoMsg(message: _211.DurationProtoMsg): _211.Duration;
            toProto(message: _211.Duration): Uint8Array;
            toProtoMsg(message: _211.Duration): _211.DurationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _210.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _210.Any;
            fromPartial(object: Partial<_210.Any>): _210.Any;
            fromAmino(object: _210.AnyAmino): _210.Any;
            toAmino(message: _210.Any): _210.AnyAmino;
            fromAminoMsg(object: _210.AnyAminoMsg): _210.Any;
            fromProtoMsg(message: _210.AnyProtoMsg): _210.Any;
            toProto(message: _210.Any): Uint8Array;
            toProtoMsg(message: _210.Any): _210.AnyProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _209.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _209.Timestamp;
            fromPartial(object: Partial<_209.Timestamp>): _209.Timestamp;
            fromAmino(object: string): _209.Timestamp;
            toAmino(message: _209.Timestamp): string;
            fromAminoMsg(object: _209.TimestampAminoMsg): _209.Timestamp;
            fromProtoMsg(message: _209.TimestampProtoMsg): _209.Timestamp;
            toProto(message: _209.Timestamp): Uint8Array;
            toProtoMsg(message: _209.Timestamp): _209.TimestampProtoMsg;
        };
    };
}
