import * as _124 from "./api/http";
import * as _125 from "./protobuf/timestamp";
import * as _126 from "./protobuf/any";
import * as _127 from "./protobuf/descriptor";
import * as _128 from "./protobuf/duration";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _124.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.Http;
            fromPartial(object: Partial<_124.Http>): _124.Http;
            fromAmino(object: _124.HttpAmino): _124.Http;
            toAmino(message: _124.Http): _124.HttpAmino;
            fromAminoMsg(object: _124.HttpAminoMsg): _124.Http;
            fromProtoMsg(message: _124.HttpProtoMsg): _124.Http;
            toProto(message: _124.Http): Uint8Array;
            toProtoMsg(message: _124.Http): _124.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _124.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.HttpRule;
            fromPartial(object: Partial<_124.HttpRule>): _124.HttpRule;
            fromAmino(object: _124.HttpRuleAmino): _124.HttpRule;
            toAmino(message: _124.HttpRule): _124.HttpRuleAmino;
            fromAminoMsg(object: _124.HttpRuleAminoMsg): _124.HttpRule;
            fromProtoMsg(message: _124.HttpRuleProtoMsg): _124.HttpRule;
            toProto(message: _124.HttpRule): Uint8Array;
            toProtoMsg(message: _124.HttpRule): _124.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _124.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _124.CustomHttpPattern;
            fromPartial(object: Partial<_124.CustomHttpPattern>): _124.CustomHttpPattern;
            fromAmino(object: _124.CustomHttpPatternAmino): _124.CustomHttpPattern;
            toAmino(message: _124.CustomHttpPattern): _124.CustomHttpPatternAmino;
            fromAminoMsg(object: _124.CustomHttpPatternAminoMsg): _124.CustomHttpPattern;
            fromProtoMsg(message: _124.CustomHttpPatternProtoMsg): _124.CustomHttpPattern;
            toProto(message: _124.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _124.CustomHttpPattern): _124.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Duration: {
            typeUrl: string;
            encode(message: _128.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _128.Duration;
            fromPartial(object: Partial<_128.Duration>): _128.Duration;
            fromAmino(object: string): _128.Duration;
            toAmino(message: _128.Duration): string;
            fromAminoMsg(object: _128.DurationAminoMsg): _128.Duration;
            fromProtoMsg(message: _128.DurationProtoMsg): _128.Duration;
            toProto(message: _128.Duration): Uint8Array;
            toProtoMsg(message: _128.Duration): _128.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _127.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _127.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _127.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _127.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _127.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _127.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _127.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _127.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _127.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _127.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _127.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _127.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _127.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _127.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _127.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _127.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _127.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _127.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _127.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _127.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _127.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _127.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _127.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _127.FieldOptions_CType;
        FieldOptions_JSType: typeof _127.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _127.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _127.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _127.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _127.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _127.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _127.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.FileDescriptorSet;
            fromPartial(object: Partial<_127.FileDescriptorSet>): _127.FileDescriptorSet;
            fromAmino(object: _127.FileDescriptorSetAmino): _127.FileDescriptorSet;
            toAmino(message: _127.FileDescriptorSet): _127.FileDescriptorSetAmino;
            fromAminoMsg(object: _127.FileDescriptorSetAminoMsg): _127.FileDescriptorSet;
            fromProtoMsg(message: _127.FileDescriptorSetProtoMsg): _127.FileDescriptorSet;
            toProto(message: _127.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _127.FileDescriptorSet): _127.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _127.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.FileDescriptorProto;
            fromPartial(object: Partial<_127.FileDescriptorProto>): _127.FileDescriptorProto;
            fromAmino(object: _127.FileDescriptorProtoAmino): _127.FileDescriptorProto;
            toAmino(message: _127.FileDescriptorProto): _127.FileDescriptorProtoAmino;
            fromAminoMsg(object: _127.FileDescriptorProtoAminoMsg): _127.FileDescriptorProto;
            fromProtoMsg(message: _127.FileDescriptorProtoProtoMsg): _127.FileDescriptorProto;
            toProto(message: _127.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _127.FileDescriptorProto): _127.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _127.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.DescriptorProto;
            fromPartial(object: Partial<_127.DescriptorProto>): _127.DescriptorProto;
            fromAmino(object: _127.DescriptorProtoAmino): _127.DescriptorProto;
            toAmino(message: _127.DescriptorProto): _127.DescriptorProtoAmino;
            fromAminoMsg(object: _127.DescriptorProtoAminoMsg): _127.DescriptorProto;
            fromProtoMsg(message: _127.DescriptorProtoProtoMsg): _127.DescriptorProto;
            toProto(message: _127.DescriptorProto): Uint8Array;
            toProtoMsg(message: _127.DescriptorProto): _127.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _127.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_127.DescriptorProto_ExtensionRange>): _127.DescriptorProto_ExtensionRange;
            fromAmino(object: _127.DescriptorProto_ExtensionRangeAmino): _127.DescriptorProto_ExtensionRange;
            toAmino(message: _127.DescriptorProto_ExtensionRange): _127.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _127.DescriptorProto_ExtensionRangeAminoMsg): _127.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _127.DescriptorProto_ExtensionRangeProtoMsg): _127.DescriptorProto_ExtensionRange;
            toProto(message: _127.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _127.DescriptorProto_ExtensionRange): _127.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _127.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_127.DescriptorProto_ReservedRange>): _127.DescriptorProto_ReservedRange;
            fromAmino(object: _127.DescriptorProto_ReservedRangeAmino): _127.DescriptorProto_ReservedRange;
            toAmino(message: _127.DescriptorProto_ReservedRange): _127.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _127.DescriptorProto_ReservedRangeAminoMsg): _127.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _127.DescriptorProto_ReservedRangeProtoMsg): _127.DescriptorProto_ReservedRange;
            toProto(message: _127.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _127.DescriptorProto_ReservedRange): _127.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _127.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.ExtensionRangeOptions;
            fromPartial(object: Partial<_127.ExtensionRangeOptions>): _127.ExtensionRangeOptions;
            fromAmino(object: _127.ExtensionRangeOptionsAmino): _127.ExtensionRangeOptions;
            toAmino(message: _127.ExtensionRangeOptions): _127.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _127.ExtensionRangeOptionsAminoMsg): _127.ExtensionRangeOptions;
            fromProtoMsg(message: _127.ExtensionRangeOptionsProtoMsg): _127.ExtensionRangeOptions;
            toProto(message: _127.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _127.ExtensionRangeOptions): _127.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _127.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.FieldDescriptorProto;
            fromPartial(object: Partial<_127.FieldDescriptorProto>): _127.FieldDescriptorProto;
            fromAmino(object: _127.FieldDescriptorProtoAmino): _127.FieldDescriptorProto;
            toAmino(message: _127.FieldDescriptorProto): _127.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _127.FieldDescriptorProtoAminoMsg): _127.FieldDescriptorProto;
            fromProtoMsg(message: _127.FieldDescriptorProtoProtoMsg): _127.FieldDescriptorProto;
            toProto(message: _127.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _127.FieldDescriptorProto): _127.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _127.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.OneofDescriptorProto;
            fromPartial(object: Partial<_127.OneofDescriptorProto>): _127.OneofDescriptorProto;
            fromAmino(object: _127.OneofDescriptorProtoAmino): _127.OneofDescriptorProto;
            toAmino(message: _127.OneofDescriptorProto): _127.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _127.OneofDescriptorProtoAminoMsg): _127.OneofDescriptorProto;
            fromProtoMsg(message: _127.OneofDescriptorProtoProtoMsg): _127.OneofDescriptorProto;
            toProto(message: _127.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _127.OneofDescriptorProto): _127.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _127.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.EnumDescriptorProto;
            fromPartial(object: Partial<_127.EnumDescriptorProto>): _127.EnumDescriptorProto;
            fromAmino(object: _127.EnumDescriptorProtoAmino): _127.EnumDescriptorProto;
            toAmino(message: _127.EnumDescriptorProto): _127.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _127.EnumDescriptorProtoAminoMsg): _127.EnumDescriptorProto;
            fromProtoMsg(message: _127.EnumDescriptorProtoProtoMsg): _127.EnumDescriptorProto;
            toProto(message: _127.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _127.EnumDescriptorProto): _127.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _127.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_127.EnumDescriptorProto_EnumReservedRange>): _127.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _127.EnumDescriptorProto_EnumReservedRangeAmino): _127.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _127.EnumDescriptorProto_EnumReservedRange): _127.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _127.EnumDescriptorProto_EnumReservedRangeAminoMsg): _127.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _127.EnumDescriptorProto_EnumReservedRangeProtoMsg): _127.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _127.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _127.EnumDescriptorProto_EnumReservedRange): _127.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _127.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.EnumValueDescriptorProto;
            fromPartial(object: Partial<_127.EnumValueDescriptorProto>): _127.EnumValueDescriptorProto;
            fromAmino(object: _127.EnumValueDescriptorProtoAmino): _127.EnumValueDescriptorProto;
            toAmino(message: _127.EnumValueDescriptorProto): _127.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _127.EnumValueDescriptorProtoAminoMsg): _127.EnumValueDescriptorProto;
            fromProtoMsg(message: _127.EnumValueDescriptorProtoProtoMsg): _127.EnumValueDescriptorProto;
            toProto(message: _127.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _127.EnumValueDescriptorProto): _127.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _127.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.ServiceDescriptorProto;
            fromPartial(object: Partial<_127.ServiceDescriptorProto>): _127.ServiceDescriptorProto;
            fromAmino(object: _127.ServiceDescriptorProtoAmino): _127.ServiceDescriptorProto;
            toAmino(message: _127.ServiceDescriptorProto): _127.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _127.ServiceDescriptorProtoAminoMsg): _127.ServiceDescriptorProto;
            fromProtoMsg(message: _127.ServiceDescriptorProtoProtoMsg): _127.ServiceDescriptorProto;
            toProto(message: _127.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _127.ServiceDescriptorProto): _127.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _127.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.MethodDescriptorProto;
            fromPartial(object: Partial<_127.MethodDescriptorProto>): _127.MethodDescriptorProto;
            fromAmino(object: _127.MethodDescriptorProtoAmino): _127.MethodDescriptorProto;
            toAmino(message: _127.MethodDescriptorProto): _127.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _127.MethodDescriptorProtoAminoMsg): _127.MethodDescriptorProto;
            fromProtoMsg(message: _127.MethodDescriptorProtoProtoMsg): _127.MethodDescriptorProto;
            toProto(message: _127.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _127.MethodDescriptorProto): _127.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _127.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.FileOptions;
            fromPartial(object: Partial<_127.FileOptions>): _127.FileOptions;
            fromAmino(object: _127.FileOptionsAmino): _127.FileOptions;
            toAmino(message: _127.FileOptions): _127.FileOptionsAmino;
            fromAminoMsg(object: _127.FileOptionsAminoMsg): _127.FileOptions;
            fromProtoMsg(message: _127.FileOptionsProtoMsg): _127.FileOptions;
            toProto(message: _127.FileOptions): Uint8Array;
            toProtoMsg(message: _127.FileOptions): _127.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _127.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.MessageOptions;
            fromPartial(object: Partial<_127.MessageOptions>): _127.MessageOptions;
            fromAmino(object: _127.MessageOptionsAmino): _127.MessageOptions;
            toAmino(message: _127.MessageOptions): _127.MessageOptionsAmino;
            fromAminoMsg(object: _127.MessageOptionsAminoMsg): _127.MessageOptions;
            fromProtoMsg(message: _127.MessageOptionsProtoMsg): _127.MessageOptions;
            toProto(message: _127.MessageOptions): Uint8Array;
            toProtoMsg(message: _127.MessageOptions): _127.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _127.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.FieldOptions;
            fromPartial(object: Partial<_127.FieldOptions>): _127.FieldOptions;
            fromAmino(object: _127.FieldOptionsAmino): _127.FieldOptions;
            toAmino(message: _127.FieldOptions): _127.FieldOptionsAmino;
            fromAminoMsg(object: _127.FieldOptionsAminoMsg): _127.FieldOptions;
            fromProtoMsg(message: _127.FieldOptionsProtoMsg): _127.FieldOptions;
            toProto(message: _127.FieldOptions): Uint8Array;
            toProtoMsg(message: _127.FieldOptions): _127.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _127.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.OneofOptions;
            fromPartial(object: Partial<_127.OneofOptions>): _127.OneofOptions;
            fromAmino(object: _127.OneofOptionsAmino): _127.OneofOptions;
            toAmino(message: _127.OneofOptions): _127.OneofOptionsAmino;
            fromAminoMsg(object: _127.OneofOptionsAminoMsg): _127.OneofOptions;
            fromProtoMsg(message: _127.OneofOptionsProtoMsg): _127.OneofOptions;
            toProto(message: _127.OneofOptions): Uint8Array;
            toProtoMsg(message: _127.OneofOptions): _127.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _127.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.EnumOptions;
            fromPartial(object: Partial<_127.EnumOptions>): _127.EnumOptions;
            fromAmino(object: _127.EnumOptionsAmino): _127.EnumOptions;
            toAmino(message: _127.EnumOptions): _127.EnumOptionsAmino;
            fromAminoMsg(object: _127.EnumOptionsAminoMsg): _127.EnumOptions;
            fromProtoMsg(message: _127.EnumOptionsProtoMsg): _127.EnumOptions;
            toProto(message: _127.EnumOptions): Uint8Array;
            toProtoMsg(message: _127.EnumOptions): _127.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _127.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.EnumValueOptions;
            fromPartial(object: Partial<_127.EnumValueOptions>): _127.EnumValueOptions;
            fromAmino(object: _127.EnumValueOptionsAmino): _127.EnumValueOptions;
            toAmino(message: _127.EnumValueOptions): _127.EnumValueOptionsAmino;
            fromAminoMsg(object: _127.EnumValueOptionsAminoMsg): _127.EnumValueOptions;
            fromProtoMsg(message: _127.EnumValueOptionsProtoMsg): _127.EnumValueOptions;
            toProto(message: _127.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _127.EnumValueOptions): _127.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _127.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.ServiceOptions;
            fromPartial(object: Partial<_127.ServiceOptions>): _127.ServiceOptions;
            fromAmino(object: _127.ServiceOptionsAmino): _127.ServiceOptions;
            toAmino(message: _127.ServiceOptions): _127.ServiceOptionsAmino;
            fromAminoMsg(object: _127.ServiceOptionsAminoMsg): _127.ServiceOptions;
            fromProtoMsg(message: _127.ServiceOptionsProtoMsg): _127.ServiceOptions;
            toProto(message: _127.ServiceOptions): Uint8Array;
            toProtoMsg(message: _127.ServiceOptions): _127.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _127.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.MethodOptions;
            fromPartial(object: Partial<_127.MethodOptions>): _127.MethodOptions;
            fromAmino(object: _127.MethodOptionsAmino): _127.MethodOptions;
            toAmino(message: _127.MethodOptions): _127.MethodOptionsAmino;
            fromAminoMsg(object: _127.MethodOptionsAminoMsg): _127.MethodOptions;
            fromProtoMsg(message: _127.MethodOptionsProtoMsg): _127.MethodOptions;
            toProto(message: _127.MethodOptions): Uint8Array;
            toProtoMsg(message: _127.MethodOptions): _127.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _127.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.UninterpretedOption;
            fromPartial(object: Partial<_127.UninterpretedOption>): _127.UninterpretedOption;
            fromAmino(object: _127.UninterpretedOptionAmino): _127.UninterpretedOption;
            toAmino(message: _127.UninterpretedOption): _127.UninterpretedOptionAmino;
            fromAminoMsg(object: _127.UninterpretedOptionAminoMsg): _127.UninterpretedOption;
            fromProtoMsg(message: _127.UninterpretedOptionProtoMsg): _127.UninterpretedOption;
            toProto(message: _127.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _127.UninterpretedOption): _127.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _127.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_127.UninterpretedOption_NamePart>): _127.UninterpretedOption_NamePart;
            fromAmino(object: _127.UninterpretedOption_NamePartAmino): _127.UninterpretedOption_NamePart;
            toAmino(message: _127.UninterpretedOption_NamePart): _127.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _127.UninterpretedOption_NamePartAminoMsg): _127.UninterpretedOption_NamePart;
            fromProtoMsg(message: _127.UninterpretedOption_NamePartProtoMsg): _127.UninterpretedOption_NamePart;
            toProto(message: _127.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _127.UninterpretedOption_NamePart): _127.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _127.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.SourceCodeInfo;
            fromPartial(object: Partial<_127.SourceCodeInfo>): _127.SourceCodeInfo;
            fromAmino(object: _127.SourceCodeInfoAmino): _127.SourceCodeInfo;
            toAmino(message: _127.SourceCodeInfo): _127.SourceCodeInfoAmino;
            fromAminoMsg(object: _127.SourceCodeInfoAminoMsg): _127.SourceCodeInfo;
            fromProtoMsg(message: _127.SourceCodeInfoProtoMsg): _127.SourceCodeInfo;
            toProto(message: _127.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _127.SourceCodeInfo): _127.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _127.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.SourceCodeInfo_Location;
            fromPartial(object: Partial<_127.SourceCodeInfo_Location>): _127.SourceCodeInfo_Location;
            fromAmino(object: _127.SourceCodeInfo_LocationAmino): _127.SourceCodeInfo_Location;
            toAmino(message: _127.SourceCodeInfo_Location): _127.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _127.SourceCodeInfo_LocationAminoMsg): _127.SourceCodeInfo_Location;
            fromProtoMsg(message: _127.SourceCodeInfo_LocationProtoMsg): _127.SourceCodeInfo_Location;
            toProto(message: _127.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _127.SourceCodeInfo_Location): _127.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _127.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.GeneratedCodeInfo;
            fromPartial(object: Partial<_127.GeneratedCodeInfo>): _127.GeneratedCodeInfo;
            fromAmino(object: _127.GeneratedCodeInfoAmino): _127.GeneratedCodeInfo;
            toAmino(message: _127.GeneratedCodeInfo): _127.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _127.GeneratedCodeInfoAminoMsg): _127.GeneratedCodeInfo;
            fromProtoMsg(message: _127.GeneratedCodeInfoProtoMsg): _127.GeneratedCodeInfo;
            toProto(message: _127.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _127.GeneratedCodeInfo): _127.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _127.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _127.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_127.GeneratedCodeInfo_Annotation>): _127.GeneratedCodeInfo_Annotation;
            fromAmino(object: _127.GeneratedCodeInfo_AnnotationAmino): _127.GeneratedCodeInfo_Annotation;
            toAmino(message: _127.GeneratedCodeInfo_Annotation): _127.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _127.GeneratedCodeInfo_AnnotationAminoMsg): _127.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _127.GeneratedCodeInfo_AnnotationProtoMsg): _127.GeneratedCodeInfo_Annotation;
            toProto(message: _127.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _127.GeneratedCodeInfo_Annotation): _127.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _126.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _126.Any;
            fromPartial(object: Partial<_126.Any>): _126.Any;
            fromAmino(object: _126.AnyAmino): _126.Any;
            toAmino(message: _126.Any): _126.AnyAmino;
            fromAminoMsg(object: _126.AnyAminoMsg): _126.Any;
            fromProtoMsg(message: _126.AnyProtoMsg): _126.Any;
            toProto(message: _126.Any): Uint8Array;
            toProtoMsg(message: _126.Any): _126.AnyProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _125.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _125.Timestamp;
            fromPartial(object: Partial<_125.Timestamp>): _125.Timestamp;
            fromAmino(object: string): _125.Timestamp;
            toAmino(message: _125.Timestamp): string;
            fromAminoMsg(object: _125.TimestampAminoMsg): _125.Timestamp;
            fromProtoMsg(message: _125.TimestampProtoMsg): _125.Timestamp;
            toProto(message: _125.Timestamp): Uint8Array;
            toProtoMsg(message: _125.Timestamp): _125.TimestampProtoMsg;
        };
    };
}
