import * as _184 from "./api/http";
import * as _185 from "./protobuf/duration";
import * as _186 from "./protobuf/timestamp";
import * as _187 from "./protobuf/descriptor";
import * as _188 from "./protobuf/any";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _184.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _184.Http;
            fromPartial(object: Partial<_184.Http>): _184.Http;
            fromAmino(object: _184.HttpAmino): _184.Http;
            toAmino(message: _184.Http): _184.HttpAmino;
            fromAminoMsg(object: _184.HttpAminoMsg): _184.Http;
            fromProtoMsg(message: _184.HttpProtoMsg): _184.Http;
            toProto(message: _184.Http): Uint8Array;
            toProtoMsg(message: _184.Http): _184.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _184.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _184.HttpRule;
            fromPartial(object: Partial<_184.HttpRule>): _184.HttpRule;
            fromAmino(object: _184.HttpRuleAmino): _184.HttpRule;
            toAmino(message: _184.HttpRule): _184.HttpRuleAmino;
            fromAminoMsg(object: _184.HttpRuleAminoMsg): _184.HttpRule;
            fromProtoMsg(message: _184.HttpRuleProtoMsg): _184.HttpRule;
            toProto(message: _184.HttpRule): Uint8Array;
            toProtoMsg(message: _184.HttpRule): _184.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _184.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _184.CustomHttpPattern;
            fromPartial(object: Partial<_184.CustomHttpPattern>): _184.CustomHttpPattern;
            fromAmino(object: _184.CustomHttpPatternAmino): _184.CustomHttpPattern;
            toAmino(message: _184.CustomHttpPattern): _184.CustomHttpPatternAmino;
            fromAminoMsg(object: _184.CustomHttpPatternAminoMsg): _184.CustomHttpPattern;
            fromProtoMsg(message: _184.CustomHttpPatternProtoMsg): _184.CustomHttpPattern;
            toProto(message: _184.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _184.CustomHttpPattern): _184.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Any: {
            typeUrl: string;
            encode(message: _188.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _188.Any;
            fromPartial(object: Partial<_188.Any>): _188.Any;
            fromAmino(object: _188.AnyAmino): _188.Any;
            toAmino(message: _188.Any): _188.AnyAmino;
            fromAminoMsg(object: _188.AnyAminoMsg): _188.Any;
            fromProtoMsg(message: _188.AnyProtoMsg): _188.Any;
            toProto(message: _188.Any): Uint8Array;
            toProtoMsg(message: _188.Any): _188.AnyProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _187.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _187.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _187.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _187.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _187.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _187.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _187.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _187.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _187.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _187.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _187.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _187.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _187.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _187.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _187.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _187.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _187.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _187.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _187.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _187.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _187.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _187.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _187.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _187.FieldOptions_CType;
        FieldOptions_JSType: typeof _187.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _187.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _187.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _187.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _187.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _187.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _187.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.FileDescriptorSet;
            fromPartial(object: Partial<_187.FileDescriptorSet>): _187.FileDescriptorSet;
            fromAmino(object: _187.FileDescriptorSetAmino): _187.FileDescriptorSet;
            toAmino(message: _187.FileDescriptorSet): _187.FileDescriptorSetAmino;
            fromAminoMsg(object: _187.FileDescriptorSetAminoMsg): _187.FileDescriptorSet;
            fromProtoMsg(message: _187.FileDescriptorSetProtoMsg): _187.FileDescriptorSet;
            toProto(message: _187.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _187.FileDescriptorSet): _187.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _187.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.FileDescriptorProto;
            fromPartial(object: Partial<_187.FileDescriptorProto>): _187.FileDescriptorProto;
            fromAmino(object: _187.FileDescriptorProtoAmino): _187.FileDescriptorProto;
            toAmino(message: _187.FileDescriptorProto): _187.FileDescriptorProtoAmino;
            fromAminoMsg(object: _187.FileDescriptorProtoAminoMsg): _187.FileDescriptorProto;
            fromProtoMsg(message: _187.FileDescriptorProtoProtoMsg): _187.FileDescriptorProto;
            toProto(message: _187.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _187.FileDescriptorProto): _187.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _187.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.DescriptorProto;
            fromPartial(object: Partial<_187.DescriptorProto>): _187.DescriptorProto;
            fromAmino(object: _187.DescriptorProtoAmino): _187.DescriptorProto;
            toAmino(message: _187.DescriptorProto): _187.DescriptorProtoAmino;
            fromAminoMsg(object: _187.DescriptorProtoAminoMsg): _187.DescriptorProto;
            fromProtoMsg(message: _187.DescriptorProtoProtoMsg): _187.DescriptorProto;
            toProto(message: _187.DescriptorProto): Uint8Array;
            toProtoMsg(message: _187.DescriptorProto): _187.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _187.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_187.DescriptorProto_ExtensionRange>): _187.DescriptorProto_ExtensionRange;
            fromAmino(object: _187.DescriptorProto_ExtensionRangeAmino): _187.DescriptorProto_ExtensionRange;
            toAmino(message: _187.DescriptorProto_ExtensionRange): _187.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _187.DescriptorProto_ExtensionRangeAminoMsg): _187.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _187.DescriptorProto_ExtensionRangeProtoMsg): _187.DescriptorProto_ExtensionRange;
            toProto(message: _187.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _187.DescriptorProto_ExtensionRange): _187.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _187.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_187.DescriptorProto_ReservedRange>): _187.DescriptorProto_ReservedRange;
            fromAmino(object: _187.DescriptorProto_ReservedRangeAmino): _187.DescriptorProto_ReservedRange;
            toAmino(message: _187.DescriptorProto_ReservedRange): _187.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _187.DescriptorProto_ReservedRangeAminoMsg): _187.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _187.DescriptorProto_ReservedRangeProtoMsg): _187.DescriptorProto_ReservedRange;
            toProto(message: _187.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _187.DescriptorProto_ReservedRange): _187.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _187.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.ExtensionRangeOptions;
            fromPartial(object: Partial<_187.ExtensionRangeOptions>): _187.ExtensionRangeOptions;
            fromAmino(object: _187.ExtensionRangeOptionsAmino): _187.ExtensionRangeOptions;
            toAmino(message: _187.ExtensionRangeOptions): _187.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _187.ExtensionRangeOptionsAminoMsg): _187.ExtensionRangeOptions;
            fromProtoMsg(message: _187.ExtensionRangeOptionsProtoMsg): _187.ExtensionRangeOptions;
            toProto(message: _187.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _187.ExtensionRangeOptions): _187.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _187.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.FieldDescriptorProto;
            fromPartial(object: Partial<_187.FieldDescriptorProto>): _187.FieldDescriptorProto;
            fromAmino(object: _187.FieldDescriptorProtoAmino): _187.FieldDescriptorProto;
            toAmino(message: _187.FieldDescriptorProto): _187.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _187.FieldDescriptorProtoAminoMsg): _187.FieldDescriptorProto;
            fromProtoMsg(message: _187.FieldDescriptorProtoProtoMsg): _187.FieldDescriptorProto;
            toProto(message: _187.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _187.FieldDescriptorProto): _187.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _187.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.OneofDescriptorProto;
            fromPartial(object: Partial<_187.OneofDescriptorProto>): _187.OneofDescriptorProto;
            fromAmino(object: _187.OneofDescriptorProtoAmino): _187.OneofDescriptorProto;
            toAmino(message: _187.OneofDescriptorProto): _187.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _187.OneofDescriptorProtoAminoMsg): _187.OneofDescriptorProto;
            fromProtoMsg(message: _187.OneofDescriptorProtoProtoMsg): _187.OneofDescriptorProto;
            toProto(message: _187.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _187.OneofDescriptorProto): _187.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _187.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.EnumDescriptorProto;
            fromPartial(object: Partial<_187.EnumDescriptorProto>): _187.EnumDescriptorProto;
            fromAmino(object: _187.EnumDescriptorProtoAmino): _187.EnumDescriptorProto;
            toAmino(message: _187.EnumDescriptorProto): _187.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _187.EnumDescriptorProtoAminoMsg): _187.EnumDescriptorProto;
            fromProtoMsg(message: _187.EnumDescriptorProtoProtoMsg): _187.EnumDescriptorProto;
            toProto(message: _187.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _187.EnumDescriptorProto): _187.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _187.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_187.EnumDescriptorProto_EnumReservedRange>): _187.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _187.EnumDescriptorProto_EnumReservedRangeAmino): _187.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _187.EnumDescriptorProto_EnumReservedRange): _187.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _187.EnumDescriptorProto_EnumReservedRangeAminoMsg): _187.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _187.EnumDescriptorProto_EnumReservedRangeProtoMsg): _187.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _187.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _187.EnumDescriptorProto_EnumReservedRange): _187.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _187.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.EnumValueDescriptorProto;
            fromPartial(object: Partial<_187.EnumValueDescriptorProto>): _187.EnumValueDescriptorProto;
            fromAmino(object: _187.EnumValueDescriptorProtoAmino): _187.EnumValueDescriptorProto;
            toAmino(message: _187.EnumValueDescriptorProto): _187.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _187.EnumValueDescriptorProtoAminoMsg): _187.EnumValueDescriptorProto;
            fromProtoMsg(message: _187.EnumValueDescriptorProtoProtoMsg): _187.EnumValueDescriptorProto;
            toProto(message: _187.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _187.EnumValueDescriptorProto): _187.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _187.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.ServiceDescriptorProto;
            fromPartial(object: Partial<_187.ServiceDescriptorProto>): _187.ServiceDescriptorProto;
            fromAmino(object: _187.ServiceDescriptorProtoAmino): _187.ServiceDescriptorProto;
            toAmino(message: _187.ServiceDescriptorProto): _187.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _187.ServiceDescriptorProtoAminoMsg): _187.ServiceDescriptorProto;
            fromProtoMsg(message: _187.ServiceDescriptorProtoProtoMsg): _187.ServiceDescriptorProto;
            toProto(message: _187.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _187.ServiceDescriptorProto): _187.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _187.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.MethodDescriptorProto;
            fromPartial(object: Partial<_187.MethodDescriptorProto>): _187.MethodDescriptorProto;
            fromAmino(object: _187.MethodDescriptorProtoAmino): _187.MethodDescriptorProto;
            toAmino(message: _187.MethodDescriptorProto): _187.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _187.MethodDescriptorProtoAminoMsg): _187.MethodDescriptorProto;
            fromProtoMsg(message: _187.MethodDescriptorProtoProtoMsg): _187.MethodDescriptorProto;
            toProto(message: _187.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _187.MethodDescriptorProto): _187.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _187.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.FileOptions;
            fromPartial(object: Partial<_187.FileOptions>): _187.FileOptions;
            fromAmino(object: _187.FileOptionsAmino): _187.FileOptions;
            toAmino(message: _187.FileOptions): _187.FileOptionsAmino;
            fromAminoMsg(object: _187.FileOptionsAminoMsg): _187.FileOptions;
            fromProtoMsg(message: _187.FileOptionsProtoMsg): _187.FileOptions;
            toProto(message: _187.FileOptions): Uint8Array;
            toProtoMsg(message: _187.FileOptions): _187.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _187.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.MessageOptions;
            fromPartial(object: Partial<_187.MessageOptions>): _187.MessageOptions;
            fromAmino(object: _187.MessageOptionsAmino): _187.MessageOptions;
            toAmino(message: _187.MessageOptions): _187.MessageOptionsAmino;
            fromAminoMsg(object: _187.MessageOptionsAminoMsg): _187.MessageOptions;
            fromProtoMsg(message: _187.MessageOptionsProtoMsg): _187.MessageOptions;
            toProto(message: _187.MessageOptions): Uint8Array;
            toProtoMsg(message: _187.MessageOptions): _187.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _187.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.FieldOptions;
            fromPartial(object: Partial<_187.FieldOptions>): _187.FieldOptions;
            fromAmino(object: _187.FieldOptionsAmino): _187.FieldOptions;
            toAmino(message: _187.FieldOptions): _187.FieldOptionsAmino;
            fromAminoMsg(object: _187.FieldOptionsAminoMsg): _187.FieldOptions;
            fromProtoMsg(message: _187.FieldOptionsProtoMsg): _187.FieldOptions;
            toProto(message: _187.FieldOptions): Uint8Array;
            toProtoMsg(message: _187.FieldOptions): _187.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _187.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.OneofOptions;
            fromPartial(object: Partial<_187.OneofOptions>): _187.OneofOptions;
            fromAmino(object: _187.OneofOptionsAmino): _187.OneofOptions;
            toAmino(message: _187.OneofOptions): _187.OneofOptionsAmino;
            fromAminoMsg(object: _187.OneofOptionsAminoMsg): _187.OneofOptions;
            fromProtoMsg(message: _187.OneofOptionsProtoMsg): _187.OneofOptions;
            toProto(message: _187.OneofOptions): Uint8Array;
            toProtoMsg(message: _187.OneofOptions): _187.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _187.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.EnumOptions;
            fromPartial(object: Partial<_187.EnumOptions>): _187.EnumOptions;
            fromAmino(object: _187.EnumOptionsAmino): _187.EnumOptions;
            toAmino(message: _187.EnumOptions): _187.EnumOptionsAmino;
            fromAminoMsg(object: _187.EnumOptionsAminoMsg): _187.EnumOptions;
            fromProtoMsg(message: _187.EnumOptionsProtoMsg): _187.EnumOptions;
            toProto(message: _187.EnumOptions): Uint8Array;
            toProtoMsg(message: _187.EnumOptions): _187.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _187.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.EnumValueOptions;
            fromPartial(object: Partial<_187.EnumValueOptions>): _187.EnumValueOptions;
            fromAmino(object: _187.EnumValueOptionsAmino): _187.EnumValueOptions;
            toAmino(message: _187.EnumValueOptions): _187.EnumValueOptionsAmino;
            fromAminoMsg(object: _187.EnumValueOptionsAminoMsg): _187.EnumValueOptions;
            fromProtoMsg(message: _187.EnumValueOptionsProtoMsg): _187.EnumValueOptions;
            toProto(message: _187.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _187.EnumValueOptions): _187.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _187.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.ServiceOptions;
            fromPartial(object: Partial<_187.ServiceOptions>): _187.ServiceOptions;
            fromAmino(object: _187.ServiceOptionsAmino): _187.ServiceOptions;
            toAmino(message: _187.ServiceOptions): _187.ServiceOptionsAmino;
            fromAminoMsg(object: _187.ServiceOptionsAminoMsg): _187.ServiceOptions;
            fromProtoMsg(message: _187.ServiceOptionsProtoMsg): _187.ServiceOptions;
            toProto(message: _187.ServiceOptions): Uint8Array;
            toProtoMsg(message: _187.ServiceOptions): _187.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _187.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.MethodOptions;
            fromPartial(object: Partial<_187.MethodOptions>): _187.MethodOptions;
            fromAmino(object: _187.MethodOptionsAmino): _187.MethodOptions;
            toAmino(message: _187.MethodOptions): _187.MethodOptionsAmino;
            fromAminoMsg(object: _187.MethodOptionsAminoMsg): _187.MethodOptions;
            fromProtoMsg(message: _187.MethodOptionsProtoMsg): _187.MethodOptions;
            toProto(message: _187.MethodOptions): Uint8Array;
            toProtoMsg(message: _187.MethodOptions): _187.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _187.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.UninterpretedOption;
            fromPartial(object: Partial<_187.UninterpretedOption>): _187.UninterpretedOption;
            fromAmino(object: _187.UninterpretedOptionAmino): _187.UninterpretedOption;
            toAmino(message: _187.UninterpretedOption): _187.UninterpretedOptionAmino;
            fromAminoMsg(object: _187.UninterpretedOptionAminoMsg): _187.UninterpretedOption;
            fromProtoMsg(message: _187.UninterpretedOptionProtoMsg): _187.UninterpretedOption;
            toProto(message: _187.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _187.UninterpretedOption): _187.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _187.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_187.UninterpretedOption_NamePart>): _187.UninterpretedOption_NamePart;
            fromAmino(object: _187.UninterpretedOption_NamePartAmino): _187.UninterpretedOption_NamePart;
            toAmino(message: _187.UninterpretedOption_NamePart): _187.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _187.UninterpretedOption_NamePartAminoMsg): _187.UninterpretedOption_NamePart;
            fromProtoMsg(message: _187.UninterpretedOption_NamePartProtoMsg): _187.UninterpretedOption_NamePart;
            toProto(message: _187.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _187.UninterpretedOption_NamePart): _187.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _187.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.SourceCodeInfo;
            fromPartial(object: Partial<_187.SourceCodeInfo>): _187.SourceCodeInfo;
            fromAmino(object: _187.SourceCodeInfoAmino): _187.SourceCodeInfo;
            toAmino(message: _187.SourceCodeInfo): _187.SourceCodeInfoAmino;
            fromAminoMsg(object: _187.SourceCodeInfoAminoMsg): _187.SourceCodeInfo;
            fromProtoMsg(message: _187.SourceCodeInfoProtoMsg): _187.SourceCodeInfo;
            toProto(message: _187.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _187.SourceCodeInfo): _187.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _187.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.SourceCodeInfo_Location;
            fromPartial(object: Partial<_187.SourceCodeInfo_Location>): _187.SourceCodeInfo_Location;
            fromAmino(object: _187.SourceCodeInfo_LocationAmino): _187.SourceCodeInfo_Location;
            toAmino(message: _187.SourceCodeInfo_Location): _187.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _187.SourceCodeInfo_LocationAminoMsg): _187.SourceCodeInfo_Location;
            fromProtoMsg(message: _187.SourceCodeInfo_LocationProtoMsg): _187.SourceCodeInfo_Location;
            toProto(message: _187.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _187.SourceCodeInfo_Location): _187.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _187.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.GeneratedCodeInfo;
            fromPartial(object: Partial<_187.GeneratedCodeInfo>): _187.GeneratedCodeInfo;
            fromAmino(object: _187.GeneratedCodeInfoAmino): _187.GeneratedCodeInfo;
            toAmino(message: _187.GeneratedCodeInfo): _187.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _187.GeneratedCodeInfoAminoMsg): _187.GeneratedCodeInfo;
            fromProtoMsg(message: _187.GeneratedCodeInfoProtoMsg): _187.GeneratedCodeInfo;
            toProto(message: _187.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _187.GeneratedCodeInfo): _187.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _187.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _187.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_187.GeneratedCodeInfo_Annotation>): _187.GeneratedCodeInfo_Annotation;
            fromAmino(object: _187.GeneratedCodeInfo_AnnotationAmino): _187.GeneratedCodeInfo_Annotation;
            toAmino(message: _187.GeneratedCodeInfo_Annotation): _187.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _187.GeneratedCodeInfo_AnnotationAminoMsg): _187.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _187.GeneratedCodeInfo_AnnotationProtoMsg): _187.GeneratedCodeInfo_Annotation;
            toProto(message: _187.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _187.GeneratedCodeInfo_Annotation): _187.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _186.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _186.Timestamp;
            fromPartial(object: Partial<_186.Timestamp>): _186.Timestamp;
            fromAmino(object: string): _186.Timestamp;
            toAmino(message: _186.Timestamp): string;
            fromAminoMsg(object: _186.TimestampAminoMsg): _186.Timestamp;
            fromProtoMsg(message: _186.TimestampProtoMsg): _186.Timestamp;
            toProto(message: _186.Timestamp): Uint8Array;
            toProtoMsg(message: _186.Timestamp): _186.TimestampProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _185.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _185.Duration;
            fromPartial(object: Partial<_185.Duration>): _185.Duration;
            fromAmino(object: string): _185.Duration;
            toAmino(message: _185.Duration): string;
            fromAminoMsg(object: _185.DurationAminoMsg): _185.Duration;
            fromProtoMsg(message: _185.DurationProtoMsg): _185.Duration;
            toProto(message: _185.Duration): Uint8Array;
            toProtoMsg(message: _185.Duration): _185.DurationProtoMsg;
        };
    };
}
