import * as _109 from "./abci/types";
import * as _110 from "./crypto/keys";
import * as _111 from "./crypto/proof";
import * as _112 from "./libs/bits/types";
import * as _113 from "./p2p/types";
import * as _114 from "./types/block";
import * as _115 from "./types/evidence";
import * as _116 from "./types/params";
import * as _117 from "./types/types";
import * as _118 from "./types/validator";
import * as _119 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _109.CheckTxType;
        checkTxTypeToJSON(object: _109.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _109.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _109.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _109.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _109.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _109.EvidenceType;
        evidenceTypeToJSON(object: _109.EvidenceType): string;
        CheckTxType: typeof _109.CheckTxType;
        CheckTxTypeSDKType: typeof _109.CheckTxType;
        CheckTxTypeAmino: typeof _109.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _109.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _109.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _109.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _109.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _109.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _109.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _109.EvidenceType;
        EvidenceTypeSDKType: typeof _109.EvidenceType;
        EvidenceTypeAmino: typeof _109.EvidenceType;
        Request: {
            typeUrl: string;
            encode(message: _109.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.Request;
            fromPartial(object: Partial<_109.Request>): _109.Request;
            fromAmino(object: _109.RequestAmino): _109.Request;
            toAmino(message: _109.Request): _109.RequestAmino;
            fromAminoMsg(object: _109.RequestAminoMsg): _109.Request;
            fromProtoMsg(message: _109.RequestProtoMsg): _109.Request;
            toProto(message: _109.Request): Uint8Array;
            toProtoMsg(message: _109.Request): _109.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _109.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.RequestEcho;
            fromPartial(object: Partial<_109.RequestEcho>): _109.RequestEcho;
            fromAmino(object: _109.RequestEchoAmino): _109.RequestEcho;
            toAmino(message: _109.RequestEcho): _109.RequestEchoAmino;
            fromAminoMsg(object: _109.RequestEchoAminoMsg): _109.RequestEcho;
            fromProtoMsg(message: _109.RequestEchoProtoMsg): _109.RequestEcho;
            toProto(message: _109.RequestEcho): Uint8Array;
            toProtoMsg(message: _109.RequestEcho): _109.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _109.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _109.RequestFlush;
            fromPartial(_: Partial<_109.RequestFlush>): _109.RequestFlush;
            fromAmino(_: _109.RequestFlushAmino): _109.RequestFlush;
            toAmino(_: _109.RequestFlush): _109.RequestFlushAmino;
            fromAminoMsg(object: _109.RequestFlushAminoMsg): _109.RequestFlush;
            fromProtoMsg(message: _109.RequestFlushProtoMsg): _109.RequestFlush;
            toProto(message: _109.RequestFlush): Uint8Array;
            toProtoMsg(message: _109.RequestFlush): _109.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _109.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.RequestInfo;
            fromPartial(object: Partial<_109.RequestInfo>): _109.RequestInfo;
            fromAmino(object: _109.RequestInfoAmino): _109.RequestInfo;
            toAmino(message: _109.RequestInfo): _109.RequestInfoAmino;
            fromAminoMsg(object: _109.RequestInfoAminoMsg): _109.RequestInfo;
            fromProtoMsg(message: _109.RequestInfoProtoMsg): _109.RequestInfo;
            toProto(message: _109.RequestInfo): Uint8Array;
            toProtoMsg(message: _109.RequestInfo): _109.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            typeUrl: string;
            encode(message: _109.RequestSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.RequestSetOption;
            fromPartial(object: Partial<_109.RequestSetOption>): _109.RequestSetOption;
            fromAmino(object: _109.RequestSetOptionAmino): _109.RequestSetOption;
            toAmino(message: _109.RequestSetOption): _109.RequestSetOptionAmino;
            fromAminoMsg(object: _109.RequestSetOptionAminoMsg): _109.RequestSetOption;
            fromProtoMsg(message: _109.RequestSetOptionProtoMsg): _109.RequestSetOption;
            toProto(message: _109.RequestSetOption): Uint8Array;
            toProtoMsg(message: _109.RequestSetOption): _109.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _109.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.RequestInitChain;
            fromPartial(object: Partial<_109.RequestInitChain>): _109.RequestInitChain;
            fromAmino(object: _109.RequestInitChainAmino): _109.RequestInitChain;
            toAmino(message: _109.RequestInitChain): _109.RequestInitChainAmino;
            fromAminoMsg(object: _109.RequestInitChainAminoMsg): _109.RequestInitChain;
            fromProtoMsg(message: _109.RequestInitChainProtoMsg): _109.RequestInitChain;
            toProto(message: _109.RequestInitChain): Uint8Array;
            toProtoMsg(message: _109.RequestInitChain): _109.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _109.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.RequestQuery;
            fromPartial(object: Partial<_109.RequestQuery>): _109.RequestQuery;
            fromAmino(object: _109.RequestQueryAmino): _109.RequestQuery;
            toAmino(message: _109.RequestQuery): _109.RequestQueryAmino;
            fromAminoMsg(object: _109.RequestQueryAminoMsg): _109.RequestQuery;
            fromProtoMsg(message: _109.RequestQueryProtoMsg): _109.RequestQuery;
            toProto(message: _109.RequestQuery): Uint8Array;
            toProtoMsg(message: _109.RequestQuery): _109.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _109.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.RequestBeginBlock;
            fromPartial(object: Partial<_109.RequestBeginBlock>): _109.RequestBeginBlock;
            fromAmino(object: _109.RequestBeginBlockAmino): _109.RequestBeginBlock;
            toAmino(message: _109.RequestBeginBlock): _109.RequestBeginBlockAmino;
            fromAminoMsg(object: _109.RequestBeginBlockAminoMsg): _109.RequestBeginBlock;
            fromProtoMsg(message: _109.RequestBeginBlockProtoMsg): _109.RequestBeginBlock;
            toProto(message: _109.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _109.RequestBeginBlock): _109.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _109.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.RequestCheckTx;
            fromPartial(object: Partial<_109.RequestCheckTx>): _109.RequestCheckTx;
            fromAmino(object: _109.RequestCheckTxAmino): _109.RequestCheckTx;
            toAmino(message: _109.RequestCheckTx): _109.RequestCheckTxAmino;
            fromAminoMsg(object: _109.RequestCheckTxAminoMsg): _109.RequestCheckTx;
            fromProtoMsg(message: _109.RequestCheckTxProtoMsg): _109.RequestCheckTx;
            toProto(message: _109.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _109.RequestCheckTx): _109.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _109.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.RequestDeliverTx;
            fromPartial(object: Partial<_109.RequestDeliverTx>): _109.RequestDeliverTx;
            fromAmino(object: _109.RequestDeliverTxAmino): _109.RequestDeliverTx;
            toAmino(message: _109.RequestDeliverTx): _109.RequestDeliverTxAmino;
            fromAminoMsg(object: _109.RequestDeliverTxAminoMsg): _109.RequestDeliverTx;
            fromProtoMsg(message: _109.RequestDeliverTxProtoMsg): _109.RequestDeliverTx;
            toProto(message: _109.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _109.RequestDeliverTx): _109.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _109.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.RequestEndBlock;
            fromPartial(object: Partial<_109.RequestEndBlock>): _109.RequestEndBlock;
            fromAmino(object: _109.RequestEndBlockAmino): _109.RequestEndBlock;
            toAmino(message: _109.RequestEndBlock): _109.RequestEndBlockAmino;
            fromAminoMsg(object: _109.RequestEndBlockAminoMsg): _109.RequestEndBlock;
            fromProtoMsg(message: _109.RequestEndBlockProtoMsg): _109.RequestEndBlock;
            toProto(message: _109.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _109.RequestEndBlock): _109.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _109.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _109.RequestCommit;
            fromPartial(_: Partial<_109.RequestCommit>): _109.RequestCommit;
            fromAmino(_: _109.RequestCommitAmino): _109.RequestCommit;
            toAmino(_: _109.RequestCommit): _109.RequestCommitAmino;
            fromAminoMsg(object: _109.RequestCommitAminoMsg): _109.RequestCommit;
            fromProtoMsg(message: _109.RequestCommitProtoMsg): _109.RequestCommit;
            toProto(message: _109.RequestCommit): Uint8Array;
            toProtoMsg(message: _109.RequestCommit): _109.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _109.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _109.RequestListSnapshots;
            fromPartial(_: Partial<_109.RequestListSnapshots>): _109.RequestListSnapshots;
            fromAmino(_: _109.RequestListSnapshotsAmino): _109.RequestListSnapshots;
            toAmino(_: _109.RequestListSnapshots): _109.RequestListSnapshotsAmino;
            fromAminoMsg(object: _109.RequestListSnapshotsAminoMsg): _109.RequestListSnapshots;
            fromProtoMsg(message: _109.RequestListSnapshotsProtoMsg): _109.RequestListSnapshots;
            toProto(message: _109.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _109.RequestListSnapshots): _109.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _109.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.RequestOfferSnapshot;
            fromPartial(object: Partial<_109.RequestOfferSnapshot>): _109.RequestOfferSnapshot;
            fromAmino(object: _109.RequestOfferSnapshotAmino): _109.RequestOfferSnapshot;
            toAmino(message: _109.RequestOfferSnapshot): _109.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _109.RequestOfferSnapshotAminoMsg): _109.RequestOfferSnapshot;
            fromProtoMsg(message: _109.RequestOfferSnapshotProtoMsg): _109.RequestOfferSnapshot;
            toProto(message: _109.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _109.RequestOfferSnapshot): _109.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _109.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_109.RequestLoadSnapshotChunk>): _109.RequestLoadSnapshotChunk;
            fromAmino(object: _109.RequestLoadSnapshotChunkAmino): _109.RequestLoadSnapshotChunk;
            toAmino(message: _109.RequestLoadSnapshotChunk): _109.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _109.RequestLoadSnapshotChunkAminoMsg): _109.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _109.RequestLoadSnapshotChunkProtoMsg): _109.RequestLoadSnapshotChunk;
            toProto(message: _109.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _109.RequestLoadSnapshotChunk): _109.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _109.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_109.RequestApplySnapshotChunk>): _109.RequestApplySnapshotChunk;
            fromAmino(object: _109.RequestApplySnapshotChunkAmino): _109.RequestApplySnapshotChunk;
            toAmino(message: _109.RequestApplySnapshotChunk): _109.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _109.RequestApplySnapshotChunkAminoMsg): _109.RequestApplySnapshotChunk;
            fromProtoMsg(message: _109.RequestApplySnapshotChunkProtoMsg): _109.RequestApplySnapshotChunk;
            toProto(message: _109.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _109.RequestApplySnapshotChunk): _109.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _109.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.Response;
            fromPartial(object: Partial<_109.Response>): _109.Response;
            fromAmino(object: _109.ResponseAmino): _109.Response;
            toAmino(message: _109.Response): _109.ResponseAmino;
            fromAminoMsg(object: _109.ResponseAminoMsg): _109.Response;
            fromProtoMsg(message: _109.ResponseProtoMsg): _109.Response;
            toProto(message: _109.Response): Uint8Array;
            toProtoMsg(message: _109.Response): _109.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _109.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseException;
            fromPartial(object: Partial<_109.ResponseException>): _109.ResponseException;
            fromAmino(object: _109.ResponseExceptionAmino): _109.ResponseException;
            toAmino(message: _109.ResponseException): _109.ResponseExceptionAmino;
            fromAminoMsg(object: _109.ResponseExceptionAminoMsg): _109.ResponseException;
            fromProtoMsg(message: _109.ResponseExceptionProtoMsg): _109.ResponseException;
            toProto(message: _109.ResponseException): Uint8Array;
            toProtoMsg(message: _109.ResponseException): _109.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _109.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseEcho;
            fromPartial(object: Partial<_109.ResponseEcho>): _109.ResponseEcho;
            fromAmino(object: _109.ResponseEchoAmino): _109.ResponseEcho;
            toAmino(message: _109.ResponseEcho): _109.ResponseEchoAmino;
            fromAminoMsg(object: _109.ResponseEchoAminoMsg): _109.ResponseEcho;
            fromProtoMsg(message: _109.ResponseEchoProtoMsg): _109.ResponseEcho;
            toProto(message: _109.ResponseEcho): Uint8Array;
            toProtoMsg(message: _109.ResponseEcho): _109.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _109.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _109.ResponseFlush;
            fromPartial(_: Partial<_109.ResponseFlush>): _109.ResponseFlush;
            fromAmino(_: _109.ResponseFlushAmino): _109.ResponseFlush;
            toAmino(_: _109.ResponseFlush): _109.ResponseFlushAmino;
            fromAminoMsg(object: _109.ResponseFlushAminoMsg): _109.ResponseFlush;
            fromProtoMsg(message: _109.ResponseFlushProtoMsg): _109.ResponseFlush;
            toProto(message: _109.ResponseFlush): Uint8Array;
            toProtoMsg(message: _109.ResponseFlush): _109.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _109.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseInfo;
            fromPartial(object: Partial<_109.ResponseInfo>): _109.ResponseInfo;
            fromAmino(object: _109.ResponseInfoAmino): _109.ResponseInfo;
            toAmino(message: _109.ResponseInfo): _109.ResponseInfoAmino;
            fromAminoMsg(object: _109.ResponseInfoAminoMsg): _109.ResponseInfo;
            fromProtoMsg(message: _109.ResponseInfoProtoMsg): _109.ResponseInfo;
            toProto(message: _109.ResponseInfo): Uint8Array;
            toProtoMsg(message: _109.ResponseInfo): _109.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            typeUrl: string;
            encode(message: _109.ResponseSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseSetOption;
            fromPartial(object: Partial<_109.ResponseSetOption>): _109.ResponseSetOption;
            fromAmino(object: _109.ResponseSetOptionAmino): _109.ResponseSetOption;
            toAmino(message: _109.ResponseSetOption): _109.ResponseSetOptionAmino;
            fromAminoMsg(object: _109.ResponseSetOptionAminoMsg): _109.ResponseSetOption;
            fromProtoMsg(message: _109.ResponseSetOptionProtoMsg): _109.ResponseSetOption;
            toProto(message: _109.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _109.ResponseSetOption): _109.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _109.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseInitChain;
            fromPartial(object: Partial<_109.ResponseInitChain>): _109.ResponseInitChain;
            fromAmino(object: _109.ResponseInitChainAmino): _109.ResponseInitChain;
            toAmino(message: _109.ResponseInitChain): _109.ResponseInitChainAmino;
            fromAminoMsg(object: _109.ResponseInitChainAminoMsg): _109.ResponseInitChain;
            fromProtoMsg(message: _109.ResponseInitChainProtoMsg): _109.ResponseInitChain;
            toProto(message: _109.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _109.ResponseInitChain): _109.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _109.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseQuery;
            fromPartial(object: Partial<_109.ResponseQuery>): _109.ResponseQuery;
            fromAmino(object: _109.ResponseQueryAmino): _109.ResponseQuery;
            toAmino(message: _109.ResponseQuery): _109.ResponseQueryAmino;
            fromAminoMsg(object: _109.ResponseQueryAminoMsg): _109.ResponseQuery;
            fromProtoMsg(message: _109.ResponseQueryProtoMsg): _109.ResponseQuery;
            toProto(message: _109.ResponseQuery): Uint8Array;
            toProtoMsg(message: _109.ResponseQuery): _109.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _109.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseBeginBlock;
            fromPartial(object: Partial<_109.ResponseBeginBlock>): _109.ResponseBeginBlock;
            fromAmino(object: _109.ResponseBeginBlockAmino): _109.ResponseBeginBlock;
            toAmino(message: _109.ResponseBeginBlock): _109.ResponseBeginBlockAmino;
            fromAminoMsg(object: _109.ResponseBeginBlockAminoMsg): _109.ResponseBeginBlock;
            fromProtoMsg(message: _109.ResponseBeginBlockProtoMsg): _109.ResponseBeginBlock;
            toProto(message: _109.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _109.ResponseBeginBlock): _109.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _109.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseCheckTx;
            fromPartial(object: Partial<_109.ResponseCheckTx>): _109.ResponseCheckTx;
            fromAmino(object: _109.ResponseCheckTxAmino): _109.ResponseCheckTx;
            toAmino(message: _109.ResponseCheckTx): _109.ResponseCheckTxAmino;
            fromAminoMsg(object: _109.ResponseCheckTxAminoMsg): _109.ResponseCheckTx;
            fromProtoMsg(message: _109.ResponseCheckTxProtoMsg): _109.ResponseCheckTx;
            toProto(message: _109.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _109.ResponseCheckTx): _109.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _109.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseDeliverTx;
            fromPartial(object: Partial<_109.ResponseDeliverTx>): _109.ResponseDeliverTx;
            fromAmino(object: _109.ResponseDeliverTxAmino): _109.ResponseDeliverTx;
            toAmino(message: _109.ResponseDeliverTx): _109.ResponseDeliverTxAmino;
            fromAminoMsg(object: _109.ResponseDeliverTxAminoMsg): _109.ResponseDeliverTx;
            fromProtoMsg(message: _109.ResponseDeliverTxProtoMsg): _109.ResponseDeliverTx;
            toProto(message: _109.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _109.ResponseDeliverTx): _109.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _109.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseEndBlock;
            fromPartial(object: Partial<_109.ResponseEndBlock>): _109.ResponseEndBlock;
            fromAmino(object: _109.ResponseEndBlockAmino): _109.ResponseEndBlock;
            toAmino(message: _109.ResponseEndBlock): _109.ResponseEndBlockAmino;
            fromAminoMsg(object: _109.ResponseEndBlockAminoMsg): _109.ResponseEndBlock;
            fromProtoMsg(message: _109.ResponseEndBlockProtoMsg): _109.ResponseEndBlock;
            toProto(message: _109.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _109.ResponseEndBlock): _109.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _109.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseCommit;
            fromPartial(object: Partial<_109.ResponseCommit>): _109.ResponseCommit;
            fromAmino(object: _109.ResponseCommitAmino): _109.ResponseCommit;
            toAmino(message: _109.ResponseCommit): _109.ResponseCommitAmino;
            fromAminoMsg(object: _109.ResponseCommitAminoMsg): _109.ResponseCommit;
            fromProtoMsg(message: _109.ResponseCommitProtoMsg): _109.ResponseCommit;
            toProto(message: _109.ResponseCommit): Uint8Array;
            toProtoMsg(message: _109.ResponseCommit): _109.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _109.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseListSnapshots;
            fromPartial(object: Partial<_109.ResponseListSnapshots>): _109.ResponseListSnapshots;
            fromAmino(object: _109.ResponseListSnapshotsAmino): _109.ResponseListSnapshots;
            toAmino(message: _109.ResponseListSnapshots): _109.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _109.ResponseListSnapshotsAminoMsg): _109.ResponseListSnapshots;
            fromProtoMsg(message: _109.ResponseListSnapshotsProtoMsg): _109.ResponseListSnapshots;
            toProto(message: _109.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _109.ResponseListSnapshots): _109.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _109.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseOfferSnapshot;
            fromPartial(object: Partial<_109.ResponseOfferSnapshot>): _109.ResponseOfferSnapshot;
            fromAmino(object: _109.ResponseOfferSnapshotAmino): _109.ResponseOfferSnapshot;
            toAmino(message: _109.ResponseOfferSnapshot): _109.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _109.ResponseOfferSnapshotAminoMsg): _109.ResponseOfferSnapshot;
            fromProtoMsg(message: _109.ResponseOfferSnapshotProtoMsg): _109.ResponseOfferSnapshot;
            toProto(message: _109.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _109.ResponseOfferSnapshot): _109.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _109.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_109.ResponseLoadSnapshotChunk>): _109.ResponseLoadSnapshotChunk;
            fromAmino(object: _109.ResponseLoadSnapshotChunkAmino): _109.ResponseLoadSnapshotChunk;
            toAmino(message: _109.ResponseLoadSnapshotChunk): _109.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _109.ResponseLoadSnapshotChunkAminoMsg): _109.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _109.ResponseLoadSnapshotChunkProtoMsg): _109.ResponseLoadSnapshotChunk;
            toProto(message: _109.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _109.ResponseLoadSnapshotChunk): _109.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _109.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_109.ResponseApplySnapshotChunk>): _109.ResponseApplySnapshotChunk;
            fromAmino(object: _109.ResponseApplySnapshotChunkAmino): _109.ResponseApplySnapshotChunk;
            toAmino(message: _109.ResponseApplySnapshotChunk): _109.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _109.ResponseApplySnapshotChunkAminoMsg): _109.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _109.ResponseApplySnapshotChunkProtoMsg): _109.ResponseApplySnapshotChunk;
            toProto(message: _109.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _109.ResponseApplySnapshotChunk): _109.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _109.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ConsensusParams;
            fromPartial(object: Partial<_109.ConsensusParams>): _109.ConsensusParams;
            fromAmino(object: _109.ConsensusParamsAmino): _109.ConsensusParams;
            toAmino(message: _109.ConsensusParams): _109.ConsensusParamsAmino;
            fromAminoMsg(object: _109.ConsensusParamsAminoMsg): _109.ConsensusParams;
            fromProtoMsg(message: _109.ConsensusParamsProtoMsg): _109.ConsensusParams;
            toProto(message: _109.ConsensusParams): Uint8Array;
            toProtoMsg(message: _109.ConsensusParams): _109.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _109.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.BlockParams;
            fromPartial(object: Partial<_109.BlockParams>): _109.BlockParams;
            fromAmino(object: _109.BlockParamsAmino): _109.BlockParams;
            toAmino(message: _109.BlockParams): _109.BlockParamsAmino;
            fromAminoMsg(object: _109.BlockParamsAminoMsg): _109.BlockParams;
            fromProtoMsg(message: _109.BlockParamsProtoMsg): _109.BlockParams;
            toProto(message: _109.BlockParams): Uint8Array;
            toProtoMsg(message: _109.BlockParams): _109.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            typeUrl: string;
            encode(message: _109.LastCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.LastCommitInfo;
            fromPartial(object: Partial<_109.LastCommitInfo>): _109.LastCommitInfo;
            fromAmino(object: _109.LastCommitInfoAmino): _109.LastCommitInfo;
            toAmino(message: _109.LastCommitInfo): _109.LastCommitInfoAmino;
            fromAminoMsg(object: _109.LastCommitInfoAminoMsg): _109.LastCommitInfo;
            fromProtoMsg(message: _109.LastCommitInfoProtoMsg): _109.LastCommitInfo;
            toProto(message: _109.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _109.LastCommitInfo): _109.LastCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _109.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.Event;
            fromPartial(object: Partial<_109.Event>): _109.Event;
            fromAmino(object: _109.EventAmino): _109.Event;
            toAmino(message: _109.Event): _109.EventAmino;
            fromAminoMsg(object: _109.EventAminoMsg): _109.Event;
            fromProtoMsg(message: _109.EventProtoMsg): _109.Event;
            toProto(message: _109.Event): Uint8Array;
            toProtoMsg(message: _109.Event): _109.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _109.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.EventAttribute;
            fromPartial(object: Partial<_109.EventAttribute>): _109.EventAttribute;
            fromAmino(object: _109.EventAttributeAmino): _109.EventAttribute;
            toAmino(message: _109.EventAttribute): _109.EventAttributeAmino;
            fromAminoMsg(object: _109.EventAttributeAminoMsg): _109.EventAttribute;
            fromProtoMsg(message: _109.EventAttributeProtoMsg): _109.EventAttribute;
            toProto(message: _109.EventAttribute): Uint8Array;
            toProtoMsg(message: _109.EventAttribute): _109.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _109.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.TxResult;
            fromPartial(object: Partial<_109.TxResult>): _109.TxResult;
            fromAmino(object: _109.TxResultAmino): _109.TxResult;
            toAmino(message: _109.TxResult): _109.TxResultAmino;
            fromAminoMsg(object: _109.TxResultAminoMsg): _109.TxResult;
            fromProtoMsg(message: _109.TxResultProtoMsg): _109.TxResult;
            toProto(message: _109.TxResult): Uint8Array;
            toProtoMsg(message: _109.TxResult): _109.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _109.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.Validator;
            fromPartial(object: Partial<_109.Validator>): _109.Validator;
            fromAmino(object: _109.ValidatorAmino): _109.Validator;
            toAmino(message: _109.Validator): _109.ValidatorAmino;
            fromAminoMsg(object: _109.ValidatorAminoMsg): _109.Validator;
            fromProtoMsg(message: _109.ValidatorProtoMsg): _109.Validator;
            toProto(message: _109.Validator): Uint8Array;
            toProtoMsg(message: _109.Validator): _109.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _109.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ValidatorUpdate;
            fromPartial(object: Partial<_109.ValidatorUpdate>): _109.ValidatorUpdate;
            fromAmino(object: _109.ValidatorUpdateAmino): _109.ValidatorUpdate;
            toAmino(message: _109.ValidatorUpdate): _109.ValidatorUpdateAmino;
            fromAminoMsg(object: _109.ValidatorUpdateAminoMsg): _109.ValidatorUpdate;
            fromProtoMsg(message: _109.ValidatorUpdateProtoMsg): _109.ValidatorUpdate;
            toProto(message: _109.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _109.ValidatorUpdate): _109.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _109.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.VoteInfo;
            fromPartial(object: Partial<_109.VoteInfo>): _109.VoteInfo;
            fromAmino(object: _109.VoteInfoAmino): _109.VoteInfo;
            toAmino(message: _109.VoteInfo): _109.VoteInfoAmino;
            fromAminoMsg(object: _109.VoteInfoAminoMsg): _109.VoteInfo;
            fromProtoMsg(message: _109.VoteInfoProtoMsg): _109.VoteInfo;
            toProto(message: _109.VoteInfo): Uint8Array;
            toProtoMsg(message: _109.VoteInfo): _109.VoteInfoProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _109.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.Evidence;
            fromPartial(object: Partial<_109.Evidence>): _109.Evidence;
            fromAmino(object: _109.EvidenceAmino): _109.Evidence;
            toAmino(message: _109.Evidence): _109.EvidenceAmino;
            fromAminoMsg(object: _109.EvidenceAminoMsg): _109.Evidence;
            fromProtoMsg(message: _109.EvidenceProtoMsg): _109.Evidence;
            toProto(message: _109.Evidence): Uint8Array;
            toProtoMsg(message: _109.Evidence): _109.EvidenceProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _109.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.Snapshot;
            fromPartial(object: Partial<_109.Snapshot>): _109.Snapshot;
            fromAmino(object: _109.SnapshotAmino): _109.Snapshot;
            toAmino(message: _109.Snapshot): _109.SnapshotAmino;
            fromAminoMsg(object: _109.SnapshotAminoMsg): _109.Snapshot;
            fromProtoMsg(message: _109.SnapshotProtoMsg): _109.Snapshot;
            toProto(message: _109.Snapshot): Uint8Array;
            toProtoMsg(message: _109.Snapshot): _109.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _111.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _111.Proof;
            fromPartial(object: Partial<_111.Proof>): _111.Proof;
            fromAmino(object: _111.ProofAmino): _111.Proof;
            toAmino(message: _111.Proof): _111.ProofAmino;
            fromAminoMsg(object: _111.ProofAminoMsg): _111.Proof;
            fromProtoMsg(message: _111.ProofProtoMsg): _111.Proof;
            toProto(message: _111.Proof): Uint8Array;
            toProtoMsg(message: _111.Proof): _111.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _111.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _111.ValueOp;
            fromPartial(object: Partial<_111.ValueOp>): _111.ValueOp;
            fromAmino(object: _111.ValueOpAmino): _111.ValueOp;
            toAmino(message: _111.ValueOp): _111.ValueOpAmino;
            fromAminoMsg(object: _111.ValueOpAminoMsg): _111.ValueOp;
            fromProtoMsg(message: _111.ValueOpProtoMsg): _111.ValueOp;
            toProto(message: _111.ValueOp): Uint8Array;
            toProtoMsg(message: _111.ValueOp): _111.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _111.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _111.DominoOp;
            fromPartial(object: Partial<_111.DominoOp>): _111.DominoOp;
            fromAmino(object: _111.DominoOpAmino): _111.DominoOp;
            toAmino(message: _111.DominoOp): _111.DominoOpAmino;
            fromAminoMsg(object: _111.DominoOpAminoMsg): _111.DominoOp;
            fromProtoMsg(message: _111.DominoOpProtoMsg): _111.DominoOp;
            toProto(message: _111.DominoOp): Uint8Array;
            toProtoMsg(message: _111.DominoOp): _111.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _111.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _111.ProofOp;
            fromPartial(object: Partial<_111.ProofOp>): _111.ProofOp;
            fromAmino(object: _111.ProofOpAmino): _111.ProofOp;
            toAmino(message: _111.ProofOp): _111.ProofOpAmino;
            fromAminoMsg(object: _111.ProofOpAminoMsg): _111.ProofOp;
            fromProtoMsg(message: _111.ProofOpProtoMsg): _111.ProofOp;
            toProto(message: _111.ProofOp): Uint8Array;
            toProtoMsg(message: _111.ProofOp): _111.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _111.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _111.ProofOps;
            fromPartial(object: Partial<_111.ProofOps>): _111.ProofOps;
            fromAmino(object: _111.ProofOpsAmino): _111.ProofOps;
            toAmino(message: _111.ProofOps): _111.ProofOpsAmino;
            fromAminoMsg(object: _111.ProofOpsAminoMsg): _111.ProofOps;
            fromProtoMsg(message: _111.ProofOpsProtoMsg): _111.ProofOps;
            toProto(message: _111.ProofOps): Uint8Array;
            toProtoMsg(message: _111.ProofOps): _111.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _110.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _110.PublicKey;
            fromPartial(object: Partial<_110.PublicKey>): _110.PublicKey;
            fromAmino(object: _110.PublicKeyAmino): _110.PublicKey;
            toAmino(message: _110.PublicKey): _110.PublicKeyAmino;
            fromAminoMsg(object: _110.PublicKeyAminoMsg): _110.PublicKey;
            fromProtoMsg(message: _110.PublicKeyProtoMsg): _110.PublicKey;
            toProto(message: _110.PublicKey): Uint8Array;
            toProtoMsg(message: _110.PublicKey): _110.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _112.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                fromJSON(object: any): _112.BitArray;
                fromPartial(object: Partial<_112.BitArray>): _112.BitArray;
                fromAmino(object: _112.BitArrayAmino): _112.BitArray;
                toAmino(message: _112.BitArray): _112.BitArrayAmino;
                fromAminoMsg(object: _112.BitArrayAminoMsg): _112.BitArray;
                fromProtoMsg(message: _112.BitArrayProtoMsg): _112.BitArray;
                toProto(message: _112.BitArray): Uint8Array;
                toProtoMsg(message: _112.BitArray): _112.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _113.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _113.NetAddress;
            fromPartial(object: Partial<_113.NetAddress>): _113.NetAddress;
            fromAmino(object: _113.NetAddressAmino): _113.NetAddress;
            toAmino(message: _113.NetAddress): _113.NetAddressAmino;
            fromAminoMsg(object: _113.NetAddressAminoMsg): _113.NetAddress;
            fromProtoMsg(message: _113.NetAddressProtoMsg): _113.NetAddress;
            toProto(message: _113.NetAddress): Uint8Array;
            toProtoMsg(message: _113.NetAddress): _113.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _113.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _113.ProtocolVersion;
            fromPartial(object: Partial<_113.ProtocolVersion>): _113.ProtocolVersion;
            fromAmino(object: _113.ProtocolVersionAmino): _113.ProtocolVersion;
            toAmino(message: _113.ProtocolVersion): _113.ProtocolVersionAmino;
            fromAminoMsg(object: _113.ProtocolVersionAminoMsg): _113.ProtocolVersion;
            fromProtoMsg(message: _113.ProtocolVersionProtoMsg): _113.ProtocolVersion;
            toProto(message: _113.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _113.ProtocolVersion): _113.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _113.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _113.DefaultNodeInfo;
            fromPartial(object: Partial<_113.DefaultNodeInfo>): _113.DefaultNodeInfo;
            fromAmino(object: _113.DefaultNodeInfoAmino): _113.DefaultNodeInfo;
            toAmino(message: _113.DefaultNodeInfo): _113.DefaultNodeInfoAmino;
            fromAminoMsg(object: _113.DefaultNodeInfoAminoMsg): _113.DefaultNodeInfo;
            fromProtoMsg(message: _113.DefaultNodeInfoProtoMsg): _113.DefaultNodeInfo;
            toProto(message: _113.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _113.DefaultNodeInfo): _113.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _113.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _113.DefaultNodeInfoOther;
            fromPartial(object: Partial<_113.DefaultNodeInfoOther>): _113.DefaultNodeInfoOther;
            fromAmino(object: _113.DefaultNodeInfoOtherAmino): _113.DefaultNodeInfoOther;
            toAmino(message: _113.DefaultNodeInfoOther): _113.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _113.DefaultNodeInfoOtherAminoMsg): _113.DefaultNodeInfoOther;
            fromProtoMsg(message: _113.DefaultNodeInfoOtherProtoMsg): _113.DefaultNodeInfoOther;
            toProto(message: _113.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _113.DefaultNodeInfoOther): _113.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _118.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _118.ValidatorSet;
            fromPartial(object: Partial<_118.ValidatorSet>): _118.ValidatorSet;
            fromAmino(object: _118.ValidatorSetAmino): _118.ValidatorSet;
            toAmino(message: _118.ValidatorSet): _118.ValidatorSetAmino;
            fromAminoMsg(object: _118.ValidatorSetAminoMsg): _118.ValidatorSet;
            fromProtoMsg(message: _118.ValidatorSetProtoMsg): _118.ValidatorSet;
            toProto(message: _118.ValidatorSet): Uint8Array;
            toProtoMsg(message: _118.ValidatorSet): _118.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _118.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _118.Validator;
            fromPartial(object: Partial<_118.Validator>): _118.Validator;
            fromAmino(object: _118.ValidatorAmino): _118.Validator;
            toAmino(message: _118.Validator): _118.ValidatorAmino;
            fromAminoMsg(object: _118.ValidatorAminoMsg): _118.Validator;
            fromProtoMsg(message: _118.ValidatorProtoMsg): _118.Validator;
            toProto(message: _118.Validator): Uint8Array;
            toProtoMsg(message: _118.Validator): _118.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _118.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _118.SimpleValidator;
            fromPartial(object: Partial<_118.SimpleValidator>): _118.SimpleValidator;
            fromAmino(object: _118.SimpleValidatorAmino): _118.SimpleValidator;
            toAmino(message: _118.SimpleValidator): _118.SimpleValidatorAmino;
            fromAminoMsg(object: _118.SimpleValidatorAminoMsg): _118.SimpleValidator;
            fromProtoMsg(message: _118.SimpleValidatorProtoMsg): _118.SimpleValidator;
            toProto(message: _118.SimpleValidator): Uint8Array;
            toProtoMsg(message: _118.SimpleValidator): _118.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _117.BlockIDFlag;
        blockIDFlagToJSON(object: _117.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _117.SignedMsgType;
        signedMsgTypeToJSON(object: _117.SignedMsgType): string;
        BlockIDFlag: typeof _117.BlockIDFlag;
        BlockIDFlagSDKType: typeof _117.BlockIDFlag;
        BlockIDFlagAmino: typeof _117.BlockIDFlag;
        SignedMsgType: typeof _117.SignedMsgType;
        SignedMsgTypeSDKType: typeof _117.SignedMsgType;
        SignedMsgTypeAmino: typeof _117.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _117.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.PartSetHeader;
            fromPartial(object: Partial<_117.PartSetHeader>): _117.PartSetHeader;
            fromAmino(object: _117.PartSetHeaderAmino): _117.PartSetHeader;
            toAmino(message: _117.PartSetHeader): _117.PartSetHeaderAmino;
            fromAminoMsg(object: _117.PartSetHeaderAminoMsg): _117.PartSetHeader;
            fromProtoMsg(message: _117.PartSetHeaderProtoMsg): _117.PartSetHeader;
            toProto(message: _117.PartSetHeader): Uint8Array;
            toProtoMsg(message: _117.PartSetHeader): _117.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _117.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.Part;
            fromPartial(object: Partial<_117.Part>): _117.Part;
            fromAmino(object: _117.PartAmino): _117.Part;
            toAmino(message: _117.Part): _117.PartAmino;
            fromAminoMsg(object: _117.PartAminoMsg): _117.Part;
            fromProtoMsg(message: _117.PartProtoMsg): _117.Part;
            toProto(message: _117.Part): Uint8Array;
            toProtoMsg(message: _117.Part): _117.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _117.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.BlockID;
            fromPartial(object: Partial<_117.BlockID>): _117.BlockID;
            fromAmino(object: _117.BlockIDAmino): _117.BlockID;
            toAmino(message: _117.BlockID): _117.BlockIDAmino;
            fromAminoMsg(object: _117.BlockIDAminoMsg): _117.BlockID;
            fromProtoMsg(message: _117.BlockIDProtoMsg): _117.BlockID;
            toProto(message: _117.BlockID): Uint8Array;
            toProtoMsg(message: _117.BlockID): _117.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _117.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.Header;
            fromPartial(object: Partial<_117.Header>): _117.Header;
            fromAmino(object: _117.HeaderAmino): _117.Header;
            toAmino(message: _117.Header): _117.HeaderAmino;
            fromAminoMsg(object: _117.HeaderAminoMsg): _117.Header;
            fromProtoMsg(message: _117.HeaderProtoMsg): _117.Header;
            toProto(message: _117.Header): Uint8Array;
            toProtoMsg(message: _117.Header): _117.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _117.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.Data;
            fromPartial(object: Partial<_117.Data>): _117.Data;
            fromAmino(object: _117.DataAmino): _117.Data;
            toAmino(message: _117.Data): _117.DataAmino;
            fromAminoMsg(object: _117.DataAminoMsg): _117.Data;
            fromProtoMsg(message: _117.DataProtoMsg): _117.Data;
            toProto(message: _117.Data): Uint8Array;
            toProtoMsg(message: _117.Data): _117.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _117.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.Vote;
            fromPartial(object: Partial<_117.Vote>): _117.Vote;
            fromAmino(object: _117.VoteAmino): _117.Vote;
            toAmino(message: _117.Vote): _117.VoteAmino;
            fromAminoMsg(object: _117.VoteAminoMsg): _117.Vote;
            fromProtoMsg(message: _117.VoteProtoMsg): _117.Vote;
            toProto(message: _117.Vote): Uint8Array;
            toProtoMsg(message: _117.Vote): _117.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _117.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.Commit;
            fromPartial(object: Partial<_117.Commit>): _117.Commit;
            fromAmino(object: _117.CommitAmino): _117.Commit;
            toAmino(message: _117.Commit): _117.CommitAmino;
            fromAminoMsg(object: _117.CommitAminoMsg): _117.Commit;
            fromProtoMsg(message: _117.CommitProtoMsg): _117.Commit;
            toProto(message: _117.Commit): Uint8Array;
            toProtoMsg(message: _117.Commit): _117.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _117.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.CommitSig;
            fromPartial(object: Partial<_117.CommitSig>): _117.CommitSig;
            fromAmino(object: _117.CommitSigAmino): _117.CommitSig;
            toAmino(message: _117.CommitSig): _117.CommitSigAmino;
            fromAminoMsg(object: _117.CommitSigAminoMsg): _117.CommitSig;
            fromProtoMsg(message: _117.CommitSigProtoMsg): _117.CommitSig;
            toProto(message: _117.CommitSig): Uint8Array;
            toProtoMsg(message: _117.CommitSig): _117.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _117.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.Proposal;
            fromPartial(object: Partial<_117.Proposal>): _117.Proposal;
            fromAmino(object: _117.ProposalAmino): _117.Proposal;
            toAmino(message: _117.Proposal): _117.ProposalAmino;
            fromAminoMsg(object: _117.ProposalAminoMsg): _117.Proposal;
            fromProtoMsg(message: _117.ProposalProtoMsg): _117.Proposal;
            toProto(message: _117.Proposal): Uint8Array;
            toProtoMsg(message: _117.Proposal): _117.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _117.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.SignedHeader;
            fromPartial(object: Partial<_117.SignedHeader>): _117.SignedHeader;
            fromAmino(object: _117.SignedHeaderAmino): _117.SignedHeader;
            toAmino(message: _117.SignedHeader): _117.SignedHeaderAmino;
            fromAminoMsg(object: _117.SignedHeaderAminoMsg): _117.SignedHeader;
            fromProtoMsg(message: _117.SignedHeaderProtoMsg): _117.SignedHeader;
            toProto(message: _117.SignedHeader): Uint8Array;
            toProtoMsg(message: _117.SignedHeader): _117.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _117.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.LightBlock;
            fromPartial(object: Partial<_117.LightBlock>): _117.LightBlock;
            fromAmino(object: _117.LightBlockAmino): _117.LightBlock;
            toAmino(message: _117.LightBlock): _117.LightBlockAmino;
            fromAminoMsg(object: _117.LightBlockAminoMsg): _117.LightBlock;
            fromProtoMsg(message: _117.LightBlockProtoMsg): _117.LightBlock;
            toProto(message: _117.LightBlock): Uint8Array;
            toProtoMsg(message: _117.LightBlock): _117.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _117.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.BlockMeta;
            fromPartial(object: Partial<_117.BlockMeta>): _117.BlockMeta;
            fromAmino(object: _117.BlockMetaAmino): _117.BlockMeta;
            toAmino(message: _117.BlockMeta): _117.BlockMetaAmino;
            fromAminoMsg(object: _117.BlockMetaAminoMsg): _117.BlockMeta;
            fromProtoMsg(message: _117.BlockMetaProtoMsg): _117.BlockMeta;
            toProto(message: _117.BlockMeta): Uint8Array;
            toProtoMsg(message: _117.BlockMeta): _117.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _117.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.TxProof;
            fromPartial(object: Partial<_117.TxProof>): _117.TxProof;
            fromAmino(object: _117.TxProofAmino): _117.TxProof;
            toAmino(message: _117.TxProof): _117.TxProofAmino;
            fromAminoMsg(object: _117.TxProofAminoMsg): _117.TxProof;
            fromProtoMsg(message: _117.TxProofProtoMsg): _117.TxProof;
            toProto(message: _117.TxProof): Uint8Array;
            toProtoMsg(message: _117.TxProof): _117.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _116.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _116.ConsensusParams;
            fromPartial(object: Partial<_116.ConsensusParams>): _116.ConsensusParams;
            fromAmino(object: _116.ConsensusParamsAmino): _116.ConsensusParams;
            toAmino(message: _116.ConsensusParams): _116.ConsensusParamsAmino;
            fromAminoMsg(object: _116.ConsensusParamsAminoMsg): _116.ConsensusParams;
            fromProtoMsg(message: _116.ConsensusParamsProtoMsg): _116.ConsensusParams;
            toProto(message: _116.ConsensusParams): Uint8Array;
            toProtoMsg(message: _116.ConsensusParams): _116.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _116.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _116.BlockParams;
            fromPartial(object: Partial<_116.BlockParams>): _116.BlockParams;
            fromAmino(object: _116.BlockParamsAmino): _116.BlockParams;
            toAmino(message: _116.BlockParams): _116.BlockParamsAmino;
            fromAminoMsg(object: _116.BlockParamsAminoMsg): _116.BlockParams;
            fromProtoMsg(message: _116.BlockParamsProtoMsg): _116.BlockParams;
            toProto(message: _116.BlockParams): Uint8Array;
            toProtoMsg(message: _116.BlockParams): _116.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _116.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _116.EvidenceParams;
            fromPartial(object: Partial<_116.EvidenceParams>): _116.EvidenceParams;
            fromAmino(object: _116.EvidenceParamsAmino): _116.EvidenceParams;
            toAmino(message: _116.EvidenceParams): _116.EvidenceParamsAmino;
            fromAminoMsg(object: _116.EvidenceParamsAminoMsg): _116.EvidenceParams;
            fromProtoMsg(message: _116.EvidenceParamsProtoMsg): _116.EvidenceParams;
            toProto(message: _116.EvidenceParams): Uint8Array;
            toProtoMsg(message: _116.EvidenceParams): _116.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _116.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _116.ValidatorParams;
            fromPartial(object: Partial<_116.ValidatorParams>): _116.ValidatorParams;
            fromAmino(object: _116.ValidatorParamsAmino): _116.ValidatorParams;
            toAmino(message: _116.ValidatorParams): _116.ValidatorParamsAmino;
            fromAminoMsg(object: _116.ValidatorParamsAminoMsg): _116.ValidatorParams;
            fromProtoMsg(message: _116.ValidatorParamsProtoMsg): _116.ValidatorParams;
            toProto(message: _116.ValidatorParams): Uint8Array;
            toProtoMsg(message: _116.ValidatorParams): _116.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _116.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _116.VersionParams;
            fromPartial(object: Partial<_116.VersionParams>): _116.VersionParams;
            fromAmino(object: _116.VersionParamsAmino): _116.VersionParams;
            toAmino(message: _116.VersionParams): _116.VersionParamsAmino;
            fromAminoMsg(object: _116.VersionParamsAminoMsg): _116.VersionParams;
            fromProtoMsg(message: _116.VersionParamsProtoMsg): _116.VersionParams;
            toProto(message: _116.VersionParams): Uint8Array;
            toProtoMsg(message: _116.VersionParams): _116.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _116.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _116.HashedParams;
            fromPartial(object: Partial<_116.HashedParams>): _116.HashedParams;
            fromAmino(object: _116.HashedParamsAmino): _116.HashedParams;
            toAmino(message: _116.HashedParams): _116.HashedParamsAmino;
            fromAminoMsg(object: _116.HashedParamsAminoMsg): _116.HashedParams;
            fromProtoMsg(message: _116.HashedParamsProtoMsg): _116.HashedParams;
            toProto(message: _116.HashedParams): Uint8Array;
            toProtoMsg(message: _116.HashedParams): _116.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _115.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.Evidence;
            fromPartial(object: Partial<_115.Evidence>): _115.Evidence;
            fromAmino(object: _115.EvidenceAmino): _115.Evidence;
            toAmino(message: _115.Evidence): _115.EvidenceAmino;
            fromAminoMsg(object: _115.EvidenceAminoMsg): _115.Evidence;
            fromProtoMsg(message: _115.EvidenceProtoMsg): _115.Evidence;
            toProto(message: _115.Evidence): Uint8Array;
            toProtoMsg(message: _115.Evidence): _115.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _115.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.DuplicateVoteEvidence;
            fromPartial(object: Partial<_115.DuplicateVoteEvidence>): _115.DuplicateVoteEvidence;
            fromAmino(object: _115.DuplicateVoteEvidenceAmino): _115.DuplicateVoteEvidence;
            toAmino(message: _115.DuplicateVoteEvidence): _115.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _115.DuplicateVoteEvidenceAminoMsg): _115.DuplicateVoteEvidence;
            fromProtoMsg(message: _115.DuplicateVoteEvidenceProtoMsg): _115.DuplicateVoteEvidence;
            toProto(message: _115.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _115.DuplicateVoteEvidence): _115.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _115.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.LightClientAttackEvidence;
            fromPartial(object: Partial<_115.LightClientAttackEvidence>): _115.LightClientAttackEvidence;
            fromAmino(object: _115.LightClientAttackEvidenceAmino): _115.LightClientAttackEvidence;
            toAmino(message: _115.LightClientAttackEvidence): _115.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _115.LightClientAttackEvidenceAminoMsg): _115.LightClientAttackEvidence;
            fromProtoMsg(message: _115.LightClientAttackEvidenceProtoMsg): _115.LightClientAttackEvidence;
            toProto(message: _115.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _115.LightClientAttackEvidence): _115.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _115.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.EvidenceList;
            fromPartial(object: Partial<_115.EvidenceList>): _115.EvidenceList;
            fromAmino(object: _115.EvidenceListAmino): _115.EvidenceList;
            toAmino(message: _115.EvidenceList): _115.EvidenceListAmino;
            fromAminoMsg(object: _115.EvidenceListAminoMsg): _115.EvidenceList;
            fromProtoMsg(message: _115.EvidenceListProtoMsg): _115.EvidenceList;
            toProto(message: _115.EvidenceList): Uint8Array;
            toProtoMsg(message: _115.EvidenceList): _115.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _114.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _114.Block;
            fromPartial(object: Partial<_114.Block>): _114.Block;
            fromAmino(object: _114.BlockAmino): _114.Block;
            toAmino(message: _114.Block): _114.BlockAmino;
            fromAminoMsg(object: _114.BlockAminoMsg): _114.Block;
            fromProtoMsg(message: _114.BlockProtoMsg): _114.Block;
            toProto(message: _114.Block): Uint8Array;
            toProtoMsg(message: _114.Block): _114.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _119.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.App;
            fromPartial(object: Partial<_119.App>): _119.App;
            fromAmino(object: _119.AppAmino): _119.App;
            toAmino(message: _119.App): _119.AppAmino;
            fromAminoMsg(object: _119.AppAminoMsg): _119.App;
            fromProtoMsg(message: _119.AppProtoMsg): _119.App;
            toProto(message: _119.App): Uint8Array;
            toProtoMsg(message: _119.App): _119.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _119.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _119.Consensus;
            fromPartial(object: Partial<_119.Consensus>): _119.Consensus;
            fromAmino(object: _119.ConsensusAmino): _119.Consensus;
            toAmino(message: _119.Consensus): _119.ConsensusAmino;
            fromAminoMsg(object: _119.ConsensusAminoMsg): _119.Consensus;
            fromProtoMsg(message: _119.ConsensusProtoMsg): _119.Consensus;
            toProto(message: _119.Consensus): Uint8Array;
            toProtoMsg(message: _119.Consensus): _119.ConsensusProtoMsg;
        };
    };
}
