import * as _194 from "./abci/types";
import * as _195 from "./crypto/keys";
import * as _196 from "./crypto/proof";
import * as _197 from "./libs/bits/types";
import * as _198 from "./p2p/types";
import * as _199 from "./types/block";
import * as _200 from "./types/evidence";
import * as _201 from "./types/params";
import * as _202 from "./types/types";
import * as _203 from "./types/validator";
import * as _204 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _194.CheckTxType;
        checkTxTypeToJSON(object: _194.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _194.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _194.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _194.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _194.ResponseApplySnapshotChunk_Result): string;
        responseProcessProposal_ProposalStatusFromJSON(object: any): _194.ResponseProcessProposal_ProposalStatus;
        responseProcessProposal_ProposalStatusToJSON(object: _194.ResponseProcessProposal_ProposalStatus): string;
        misbehaviorTypeFromJSON(object: any): _194.MisbehaviorType;
        misbehaviorTypeToJSON(object: _194.MisbehaviorType): string;
        CheckTxType: typeof _194.CheckTxType;
        CheckTxTypeSDKType: typeof _194.CheckTxType;
        CheckTxTypeAmino: typeof _194.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _194.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _194.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _194.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _194.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _194.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _194.ResponseApplySnapshotChunk_Result;
        ResponseProcessProposal_ProposalStatus: typeof _194.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusSDKType: typeof _194.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusAmino: typeof _194.ResponseProcessProposal_ProposalStatus;
        MisbehaviorType: typeof _194.MisbehaviorType;
        MisbehaviorTypeSDKType: typeof _194.MisbehaviorType;
        MisbehaviorTypeAmino: typeof _194.MisbehaviorType;
        Request: {
            typeUrl: string;
            encode(message: _194.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.Request;
            fromPartial(object: Partial<_194.Request>): _194.Request;
            fromAmino(object: _194.RequestAmino): _194.Request;
            toAmino(message: _194.Request): _194.RequestAmino;
            fromAminoMsg(object: _194.RequestAminoMsg): _194.Request;
            fromProtoMsg(message: _194.RequestProtoMsg): _194.Request;
            toProto(message: _194.Request): Uint8Array;
            toProtoMsg(message: _194.Request): _194.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _194.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestEcho;
            fromPartial(object: Partial<_194.RequestEcho>): _194.RequestEcho;
            fromAmino(object: _194.RequestEchoAmino): _194.RequestEcho;
            toAmino(message: _194.RequestEcho): _194.RequestEchoAmino;
            fromAminoMsg(object: _194.RequestEchoAminoMsg): _194.RequestEcho;
            fromProtoMsg(message: _194.RequestEchoProtoMsg): _194.RequestEcho;
            toProto(message: _194.RequestEcho): Uint8Array;
            toProtoMsg(message: _194.RequestEcho): _194.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _194.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _194.RequestFlush;
            fromPartial(_: Partial<_194.RequestFlush>): _194.RequestFlush;
            fromAmino(_: _194.RequestFlushAmino): _194.RequestFlush;
            toAmino(_: _194.RequestFlush): _194.RequestFlushAmino;
            fromAminoMsg(object: _194.RequestFlushAminoMsg): _194.RequestFlush;
            fromProtoMsg(message: _194.RequestFlushProtoMsg): _194.RequestFlush;
            toProto(message: _194.RequestFlush): Uint8Array;
            toProtoMsg(message: _194.RequestFlush): _194.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _194.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestInfo;
            fromPartial(object: Partial<_194.RequestInfo>): _194.RequestInfo;
            fromAmino(object: _194.RequestInfoAmino): _194.RequestInfo;
            toAmino(message: _194.RequestInfo): _194.RequestInfoAmino;
            fromAminoMsg(object: _194.RequestInfoAminoMsg): _194.RequestInfo;
            fromProtoMsg(message: _194.RequestInfoProtoMsg): _194.RequestInfo;
            toProto(message: _194.RequestInfo): Uint8Array;
            toProtoMsg(message: _194.RequestInfo): _194.RequestInfoProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _194.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestInitChain;
            fromPartial(object: Partial<_194.RequestInitChain>): _194.RequestInitChain;
            fromAmino(object: _194.RequestInitChainAmino): _194.RequestInitChain;
            toAmino(message: _194.RequestInitChain): _194.RequestInitChainAmino;
            fromAminoMsg(object: _194.RequestInitChainAminoMsg): _194.RequestInitChain;
            fromProtoMsg(message: _194.RequestInitChainProtoMsg): _194.RequestInitChain;
            toProto(message: _194.RequestInitChain): Uint8Array;
            toProtoMsg(message: _194.RequestInitChain): _194.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _194.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestQuery;
            fromPartial(object: Partial<_194.RequestQuery>): _194.RequestQuery;
            fromAmino(object: _194.RequestQueryAmino): _194.RequestQuery;
            toAmino(message: _194.RequestQuery): _194.RequestQueryAmino;
            fromAminoMsg(object: _194.RequestQueryAminoMsg): _194.RequestQuery;
            fromProtoMsg(message: _194.RequestQueryProtoMsg): _194.RequestQuery;
            toProto(message: _194.RequestQuery): Uint8Array;
            toProtoMsg(message: _194.RequestQuery): _194.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _194.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestBeginBlock;
            fromPartial(object: Partial<_194.RequestBeginBlock>): _194.RequestBeginBlock;
            fromAmino(object: _194.RequestBeginBlockAmino): _194.RequestBeginBlock;
            toAmino(message: _194.RequestBeginBlock): _194.RequestBeginBlockAmino;
            fromAminoMsg(object: _194.RequestBeginBlockAminoMsg): _194.RequestBeginBlock;
            fromProtoMsg(message: _194.RequestBeginBlockProtoMsg): _194.RequestBeginBlock;
            toProto(message: _194.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _194.RequestBeginBlock): _194.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _194.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestCheckTx;
            fromPartial(object: Partial<_194.RequestCheckTx>): _194.RequestCheckTx;
            fromAmino(object: _194.RequestCheckTxAmino): _194.RequestCheckTx;
            toAmino(message: _194.RequestCheckTx): _194.RequestCheckTxAmino;
            fromAminoMsg(object: _194.RequestCheckTxAminoMsg): _194.RequestCheckTx;
            fromProtoMsg(message: _194.RequestCheckTxProtoMsg): _194.RequestCheckTx;
            toProto(message: _194.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _194.RequestCheckTx): _194.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _194.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestDeliverTx;
            fromPartial(object: Partial<_194.RequestDeliverTx>): _194.RequestDeliverTx;
            fromAmino(object: _194.RequestDeliverTxAmino): _194.RequestDeliverTx;
            toAmino(message: _194.RequestDeliverTx): _194.RequestDeliverTxAmino;
            fromAminoMsg(object: _194.RequestDeliverTxAminoMsg): _194.RequestDeliverTx;
            fromProtoMsg(message: _194.RequestDeliverTxProtoMsg): _194.RequestDeliverTx;
            toProto(message: _194.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _194.RequestDeliverTx): _194.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _194.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestEndBlock;
            fromPartial(object: Partial<_194.RequestEndBlock>): _194.RequestEndBlock;
            fromAmino(object: _194.RequestEndBlockAmino): _194.RequestEndBlock;
            toAmino(message: _194.RequestEndBlock): _194.RequestEndBlockAmino;
            fromAminoMsg(object: _194.RequestEndBlockAminoMsg): _194.RequestEndBlock;
            fromProtoMsg(message: _194.RequestEndBlockProtoMsg): _194.RequestEndBlock;
            toProto(message: _194.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _194.RequestEndBlock): _194.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _194.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _194.RequestCommit;
            fromPartial(_: Partial<_194.RequestCommit>): _194.RequestCommit;
            fromAmino(_: _194.RequestCommitAmino): _194.RequestCommit;
            toAmino(_: _194.RequestCommit): _194.RequestCommitAmino;
            fromAminoMsg(object: _194.RequestCommitAminoMsg): _194.RequestCommit;
            fromProtoMsg(message: _194.RequestCommitProtoMsg): _194.RequestCommit;
            toProto(message: _194.RequestCommit): Uint8Array;
            toProtoMsg(message: _194.RequestCommit): _194.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _194.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _194.RequestListSnapshots;
            fromPartial(_: Partial<_194.RequestListSnapshots>): _194.RequestListSnapshots;
            fromAmino(_: _194.RequestListSnapshotsAmino): _194.RequestListSnapshots;
            toAmino(_: _194.RequestListSnapshots): _194.RequestListSnapshotsAmino;
            fromAminoMsg(object: _194.RequestListSnapshotsAminoMsg): _194.RequestListSnapshots;
            fromProtoMsg(message: _194.RequestListSnapshotsProtoMsg): _194.RequestListSnapshots;
            toProto(message: _194.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _194.RequestListSnapshots): _194.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _194.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestOfferSnapshot;
            fromPartial(object: Partial<_194.RequestOfferSnapshot>): _194.RequestOfferSnapshot;
            fromAmino(object: _194.RequestOfferSnapshotAmino): _194.RequestOfferSnapshot;
            toAmino(message: _194.RequestOfferSnapshot): _194.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _194.RequestOfferSnapshotAminoMsg): _194.RequestOfferSnapshot;
            fromProtoMsg(message: _194.RequestOfferSnapshotProtoMsg): _194.RequestOfferSnapshot;
            toProto(message: _194.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _194.RequestOfferSnapshot): _194.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _194.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_194.RequestLoadSnapshotChunk>): _194.RequestLoadSnapshotChunk;
            fromAmino(object: _194.RequestLoadSnapshotChunkAmino): _194.RequestLoadSnapshotChunk;
            toAmino(message: _194.RequestLoadSnapshotChunk): _194.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _194.RequestLoadSnapshotChunkAminoMsg): _194.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _194.RequestLoadSnapshotChunkProtoMsg): _194.RequestLoadSnapshotChunk;
            toProto(message: _194.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _194.RequestLoadSnapshotChunk): _194.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _194.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_194.RequestApplySnapshotChunk>): _194.RequestApplySnapshotChunk;
            fromAmino(object: _194.RequestApplySnapshotChunkAmino): _194.RequestApplySnapshotChunk;
            toAmino(message: _194.RequestApplySnapshotChunk): _194.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _194.RequestApplySnapshotChunkAminoMsg): _194.RequestApplySnapshotChunk;
            fromProtoMsg(message: _194.RequestApplySnapshotChunkProtoMsg): _194.RequestApplySnapshotChunk;
            toProto(message: _194.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _194.RequestApplySnapshotChunk): _194.RequestApplySnapshotChunkProtoMsg;
        };
        RequestPrepareProposal: {
            typeUrl: string;
            encode(message: _194.RequestPrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestPrepareProposal;
            fromPartial(object: Partial<_194.RequestPrepareProposal>): _194.RequestPrepareProposal;
            fromAmino(object: _194.RequestPrepareProposalAmino): _194.RequestPrepareProposal;
            toAmino(message: _194.RequestPrepareProposal): _194.RequestPrepareProposalAmino;
            fromAminoMsg(object: _194.RequestPrepareProposalAminoMsg): _194.RequestPrepareProposal;
            fromProtoMsg(message: _194.RequestPrepareProposalProtoMsg): _194.RequestPrepareProposal;
            toProto(message: _194.RequestPrepareProposal): Uint8Array;
            toProtoMsg(message: _194.RequestPrepareProposal): _194.RequestPrepareProposalProtoMsg;
        };
        RequestProcessProposal: {
            typeUrl: string;
            encode(message: _194.RequestProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.RequestProcessProposal;
            fromPartial(object: Partial<_194.RequestProcessProposal>): _194.RequestProcessProposal;
            fromAmino(object: _194.RequestProcessProposalAmino): _194.RequestProcessProposal;
            toAmino(message: _194.RequestProcessProposal): _194.RequestProcessProposalAmino;
            fromAminoMsg(object: _194.RequestProcessProposalAminoMsg): _194.RequestProcessProposal;
            fromProtoMsg(message: _194.RequestProcessProposalProtoMsg): _194.RequestProcessProposal;
            toProto(message: _194.RequestProcessProposal): Uint8Array;
            toProtoMsg(message: _194.RequestProcessProposal): _194.RequestProcessProposalProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _194.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.Response;
            fromPartial(object: Partial<_194.Response>): _194.Response;
            fromAmino(object: _194.ResponseAmino): _194.Response;
            toAmino(message: _194.Response): _194.ResponseAmino;
            fromAminoMsg(object: _194.ResponseAminoMsg): _194.Response;
            fromProtoMsg(message: _194.ResponseProtoMsg): _194.Response;
            toProto(message: _194.Response): Uint8Array;
            toProtoMsg(message: _194.Response): _194.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _194.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseException;
            fromPartial(object: Partial<_194.ResponseException>): _194.ResponseException;
            fromAmino(object: _194.ResponseExceptionAmino): _194.ResponseException;
            toAmino(message: _194.ResponseException): _194.ResponseExceptionAmino;
            fromAminoMsg(object: _194.ResponseExceptionAminoMsg): _194.ResponseException;
            fromProtoMsg(message: _194.ResponseExceptionProtoMsg): _194.ResponseException;
            toProto(message: _194.ResponseException): Uint8Array;
            toProtoMsg(message: _194.ResponseException): _194.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _194.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseEcho;
            fromPartial(object: Partial<_194.ResponseEcho>): _194.ResponseEcho;
            fromAmino(object: _194.ResponseEchoAmino): _194.ResponseEcho;
            toAmino(message: _194.ResponseEcho): _194.ResponseEchoAmino;
            fromAminoMsg(object: _194.ResponseEchoAminoMsg): _194.ResponseEcho;
            fromProtoMsg(message: _194.ResponseEchoProtoMsg): _194.ResponseEcho;
            toProto(message: _194.ResponseEcho): Uint8Array;
            toProtoMsg(message: _194.ResponseEcho): _194.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _194.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _194.ResponseFlush;
            fromPartial(_: Partial<_194.ResponseFlush>): _194.ResponseFlush;
            fromAmino(_: _194.ResponseFlushAmino): _194.ResponseFlush;
            toAmino(_: _194.ResponseFlush): _194.ResponseFlushAmino;
            fromAminoMsg(object: _194.ResponseFlushAminoMsg): _194.ResponseFlush;
            fromProtoMsg(message: _194.ResponseFlushProtoMsg): _194.ResponseFlush;
            toProto(message: _194.ResponseFlush): Uint8Array;
            toProtoMsg(message: _194.ResponseFlush): _194.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _194.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseInfo;
            fromPartial(object: Partial<_194.ResponseInfo>): _194.ResponseInfo;
            fromAmino(object: _194.ResponseInfoAmino): _194.ResponseInfo;
            toAmino(message: _194.ResponseInfo): _194.ResponseInfoAmino;
            fromAminoMsg(object: _194.ResponseInfoAminoMsg): _194.ResponseInfo;
            fromProtoMsg(message: _194.ResponseInfoProtoMsg): _194.ResponseInfo;
            toProto(message: _194.ResponseInfo): Uint8Array;
            toProtoMsg(message: _194.ResponseInfo): _194.ResponseInfoProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _194.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseInitChain;
            fromPartial(object: Partial<_194.ResponseInitChain>): _194.ResponseInitChain;
            fromAmino(object: _194.ResponseInitChainAmino): _194.ResponseInitChain;
            toAmino(message: _194.ResponseInitChain): _194.ResponseInitChainAmino;
            fromAminoMsg(object: _194.ResponseInitChainAminoMsg): _194.ResponseInitChain;
            fromProtoMsg(message: _194.ResponseInitChainProtoMsg): _194.ResponseInitChain;
            toProto(message: _194.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _194.ResponseInitChain): _194.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _194.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseQuery;
            fromPartial(object: Partial<_194.ResponseQuery>): _194.ResponseQuery;
            fromAmino(object: _194.ResponseQueryAmino): _194.ResponseQuery;
            toAmino(message: _194.ResponseQuery): _194.ResponseQueryAmino;
            fromAminoMsg(object: _194.ResponseQueryAminoMsg): _194.ResponseQuery;
            fromProtoMsg(message: _194.ResponseQueryProtoMsg): _194.ResponseQuery;
            toProto(message: _194.ResponseQuery): Uint8Array;
            toProtoMsg(message: _194.ResponseQuery): _194.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _194.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseBeginBlock;
            fromPartial(object: Partial<_194.ResponseBeginBlock>): _194.ResponseBeginBlock;
            fromAmino(object: _194.ResponseBeginBlockAmino): _194.ResponseBeginBlock;
            toAmino(message: _194.ResponseBeginBlock): _194.ResponseBeginBlockAmino;
            fromAminoMsg(object: _194.ResponseBeginBlockAminoMsg): _194.ResponseBeginBlock;
            fromProtoMsg(message: _194.ResponseBeginBlockProtoMsg): _194.ResponseBeginBlock;
            toProto(message: _194.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _194.ResponseBeginBlock): _194.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _194.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseCheckTx;
            fromPartial(object: Partial<_194.ResponseCheckTx>): _194.ResponseCheckTx;
            fromAmino(object: _194.ResponseCheckTxAmino): _194.ResponseCheckTx;
            toAmino(message: _194.ResponseCheckTx): _194.ResponseCheckTxAmino;
            fromAminoMsg(object: _194.ResponseCheckTxAminoMsg): _194.ResponseCheckTx;
            fromProtoMsg(message: _194.ResponseCheckTxProtoMsg): _194.ResponseCheckTx;
            toProto(message: _194.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _194.ResponseCheckTx): _194.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _194.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseDeliverTx;
            fromPartial(object: Partial<_194.ResponseDeliverTx>): _194.ResponseDeliverTx;
            fromAmino(object: _194.ResponseDeliverTxAmino): _194.ResponseDeliverTx;
            toAmino(message: _194.ResponseDeliverTx): _194.ResponseDeliverTxAmino;
            fromAminoMsg(object: _194.ResponseDeliverTxAminoMsg): _194.ResponseDeliverTx;
            fromProtoMsg(message: _194.ResponseDeliverTxProtoMsg): _194.ResponseDeliverTx;
            toProto(message: _194.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _194.ResponseDeliverTx): _194.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _194.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseEndBlock;
            fromPartial(object: Partial<_194.ResponseEndBlock>): _194.ResponseEndBlock;
            fromAmino(object: _194.ResponseEndBlockAmino): _194.ResponseEndBlock;
            toAmino(message: _194.ResponseEndBlock): _194.ResponseEndBlockAmino;
            fromAminoMsg(object: _194.ResponseEndBlockAminoMsg): _194.ResponseEndBlock;
            fromProtoMsg(message: _194.ResponseEndBlockProtoMsg): _194.ResponseEndBlock;
            toProto(message: _194.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _194.ResponseEndBlock): _194.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _194.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseCommit;
            fromPartial(object: Partial<_194.ResponseCommit>): _194.ResponseCommit;
            fromAmino(object: _194.ResponseCommitAmino): _194.ResponseCommit;
            toAmino(message: _194.ResponseCommit): _194.ResponseCommitAmino;
            fromAminoMsg(object: _194.ResponseCommitAminoMsg): _194.ResponseCommit;
            fromProtoMsg(message: _194.ResponseCommitProtoMsg): _194.ResponseCommit;
            toProto(message: _194.ResponseCommit): Uint8Array;
            toProtoMsg(message: _194.ResponseCommit): _194.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _194.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseListSnapshots;
            fromPartial(object: Partial<_194.ResponseListSnapshots>): _194.ResponseListSnapshots;
            fromAmino(object: _194.ResponseListSnapshotsAmino): _194.ResponseListSnapshots;
            toAmino(message: _194.ResponseListSnapshots): _194.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _194.ResponseListSnapshotsAminoMsg): _194.ResponseListSnapshots;
            fromProtoMsg(message: _194.ResponseListSnapshotsProtoMsg): _194.ResponseListSnapshots;
            toProto(message: _194.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _194.ResponseListSnapshots): _194.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _194.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseOfferSnapshot;
            fromPartial(object: Partial<_194.ResponseOfferSnapshot>): _194.ResponseOfferSnapshot;
            fromAmino(object: _194.ResponseOfferSnapshotAmino): _194.ResponseOfferSnapshot;
            toAmino(message: _194.ResponseOfferSnapshot): _194.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _194.ResponseOfferSnapshotAminoMsg): _194.ResponseOfferSnapshot;
            fromProtoMsg(message: _194.ResponseOfferSnapshotProtoMsg): _194.ResponseOfferSnapshot;
            toProto(message: _194.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _194.ResponseOfferSnapshot): _194.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _194.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_194.ResponseLoadSnapshotChunk>): _194.ResponseLoadSnapshotChunk;
            fromAmino(object: _194.ResponseLoadSnapshotChunkAmino): _194.ResponseLoadSnapshotChunk;
            toAmino(message: _194.ResponseLoadSnapshotChunk): _194.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _194.ResponseLoadSnapshotChunkAminoMsg): _194.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _194.ResponseLoadSnapshotChunkProtoMsg): _194.ResponseLoadSnapshotChunk;
            toProto(message: _194.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _194.ResponseLoadSnapshotChunk): _194.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _194.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_194.ResponseApplySnapshotChunk>): _194.ResponseApplySnapshotChunk;
            fromAmino(object: _194.ResponseApplySnapshotChunkAmino): _194.ResponseApplySnapshotChunk;
            toAmino(message: _194.ResponseApplySnapshotChunk): _194.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _194.ResponseApplySnapshotChunkAminoMsg): _194.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _194.ResponseApplySnapshotChunkProtoMsg): _194.ResponseApplySnapshotChunk;
            toProto(message: _194.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _194.ResponseApplySnapshotChunk): _194.ResponseApplySnapshotChunkProtoMsg;
        };
        ResponsePrepareProposal: {
            typeUrl: string;
            encode(message: _194.ResponsePrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponsePrepareProposal;
            fromPartial(object: Partial<_194.ResponsePrepareProposal>): _194.ResponsePrepareProposal;
            fromAmino(object: _194.ResponsePrepareProposalAmino): _194.ResponsePrepareProposal;
            toAmino(message: _194.ResponsePrepareProposal): _194.ResponsePrepareProposalAmino;
            fromAminoMsg(object: _194.ResponsePrepareProposalAminoMsg): _194.ResponsePrepareProposal;
            fromProtoMsg(message: _194.ResponsePrepareProposalProtoMsg): _194.ResponsePrepareProposal;
            toProto(message: _194.ResponsePrepareProposal): Uint8Array;
            toProtoMsg(message: _194.ResponsePrepareProposal): _194.ResponsePrepareProposalProtoMsg;
        };
        ResponseProcessProposal: {
            typeUrl: string;
            encode(message: _194.ResponseProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ResponseProcessProposal;
            fromPartial(object: Partial<_194.ResponseProcessProposal>): _194.ResponseProcessProposal;
            fromAmino(object: _194.ResponseProcessProposalAmino): _194.ResponseProcessProposal;
            toAmino(message: _194.ResponseProcessProposal): _194.ResponseProcessProposalAmino;
            fromAminoMsg(object: _194.ResponseProcessProposalAminoMsg): _194.ResponseProcessProposal;
            fromProtoMsg(message: _194.ResponseProcessProposalProtoMsg): _194.ResponseProcessProposal;
            toProto(message: _194.ResponseProcessProposal): Uint8Array;
            toProtoMsg(message: _194.ResponseProcessProposal): _194.ResponseProcessProposalProtoMsg;
        };
        CommitInfo: {
            typeUrl: string;
            encode(message: _194.CommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.CommitInfo;
            fromPartial(object: Partial<_194.CommitInfo>): _194.CommitInfo;
            fromAmino(object: _194.CommitInfoAmino): _194.CommitInfo;
            toAmino(message: _194.CommitInfo): _194.CommitInfoAmino;
            fromAminoMsg(object: _194.CommitInfoAminoMsg): _194.CommitInfo;
            fromProtoMsg(message: _194.CommitInfoProtoMsg): _194.CommitInfo;
            toProto(message: _194.CommitInfo): Uint8Array;
            toProtoMsg(message: _194.CommitInfo): _194.CommitInfoProtoMsg;
        };
        ExtendedCommitInfo: {
            typeUrl: string;
            encode(message: _194.ExtendedCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ExtendedCommitInfo;
            fromPartial(object: Partial<_194.ExtendedCommitInfo>): _194.ExtendedCommitInfo;
            fromAmino(object: _194.ExtendedCommitInfoAmino): _194.ExtendedCommitInfo;
            toAmino(message: _194.ExtendedCommitInfo): _194.ExtendedCommitInfoAmino;
            fromAminoMsg(object: _194.ExtendedCommitInfoAminoMsg): _194.ExtendedCommitInfo;
            fromProtoMsg(message: _194.ExtendedCommitInfoProtoMsg): _194.ExtendedCommitInfo;
            toProto(message: _194.ExtendedCommitInfo): Uint8Array;
            toProtoMsg(message: _194.ExtendedCommitInfo): _194.ExtendedCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _194.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.Event;
            fromPartial(object: Partial<_194.Event>): _194.Event;
            fromAmino(object: _194.EventAmino): _194.Event;
            toAmino(message: _194.Event): _194.EventAmino;
            fromAminoMsg(object: _194.EventAminoMsg): _194.Event;
            fromProtoMsg(message: _194.EventProtoMsg): _194.Event;
            toProto(message: _194.Event): Uint8Array;
            toProtoMsg(message: _194.Event): _194.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _194.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.EventAttribute;
            fromPartial(object: Partial<_194.EventAttribute>): _194.EventAttribute;
            fromAmino(object: _194.EventAttributeAmino): _194.EventAttribute;
            toAmino(message: _194.EventAttribute): _194.EventAttributeAmino;
            fromAminoMsg(object: _194.EventAttributeAminoMsg): _194.EventAttribute;
            fromProtoMsg(message: _194.EventAttributeProtoMsg): _194.EventAttribute;
            toProto(message: _194.EventAttribute): Uint8Array;
            toProtoMsg(message: _194.EventAttribute): _194.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _194.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.TxResult;
            fromPartial(object: Partial<_194.TxResult>): _194.TxResult;
            fromAmino(object: _194.TxResultAmino): _194.TxResult;
            toAmino(message: _194.TxResult): _194.TxResultAmino;
            fromAminoMsg(object: _194.TxResultAminoMsg): _194.TxResult;
            fromProtoMsg(message: _194.TxResultProtoMsg): _194.TxResult;
            toProto(message: _194.TxResult): Uint8Array;
            toProtoMsg(message: _194.TxResult): _194.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _194.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.Validator;
            fromPartial(object: Partial<_194.Validator>): _194.Validator;
            fromAmino(object: _194.ValidatorAmino): _194.Validator;
            toAmino(message: _194.Validator): _194.ValidatorAmino;
            fromAminoMsg(object: _194.ValidatorAminoMsg): _194.Validator;
            fromProtoMsg(message: _194.ValidatorProtoMsg): _194.Validator;
            toProto(message: _194.Validator): Uint8Array;
            toProtoMsg(message: _194.Validator): _194.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _194.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ValidatorUpdate;
            fromPartial(object: Partial<_194.ValidatorUpdate>): _194.ValidatorUpdate;
            fromAmino(object: _194.ValidatorUpdateAmino): _194.ValidatorUpdate;
            toAmino(message: _194.ValidatorUpdate): _194.ValidatorUpdateAmino;
            fromAminoMsg(object: _194.ValidatorUpdateAminoMsg): _194.ValidatorUpdate;
            fromProtoMsg(message: _194.ValidatorUpdateProtoMsg): _194.ValidatorUpdate;
            toProto(message: _194.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _194.ValidatorUpdate): _194.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _194.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.VoteInfo;
            fromPartial(object: Partial<_194.VoteInfo>): _194.VoteInfo;
            fromAmino(object: _194.VoteInfoAmino): _194.VoteInfo;
            toAmino(message: _194.VoteInfo): _194.VoteInfoAmino;
            fromAminoMsg(object: _194.VoteInfoAminoMsg): _194.VoteInfo;
            fromProtoMsg(message: _194.VoteInfoProtoMsg): _194.VoteInfo;
            toProto(message: _194.VoteInfo): Uint8Array;
            toProtoMsg(message: _194.VoteInfo): _194.VoteInfoProtoMsg;
        };
        ExtendedVoteInfo: {
            typeUrl: string;
            encode(message: _194.ExtendedVoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.ExtendedVoteInfo;
            fromPartial(object: Partial<_194.ExtendedVoteInfo>): _194.ExtendedVoteInfo;
            fromAmino(object: _194.ExtendedVoteInfoAmino): _194.ExtendedVoteInfo;
            toAmino(message: _194.ExtendedVoteInfo): _194.ExtendedVoteInfoAmino;
            fromAminoMsg(object: _194.ExtendedVoteInfoAminoMsg): _194.ExtendedVoteInfo;
            fromProtoMsg(message: _194.ExtendedVoteInfoProtoMsg): _194.ExtendedVoteInfo;
            toProto(message: _194.ExtendedVoteInfo): Uint8Array;
            toProtoMsg(message: _194.ExtendedVoteInfo): _194.ExtendedVoteInfoProtoMsg;
        };
        Misbehavior: {
            typeUrl: string;
            encode(message: _194.Misbehavior, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.Misbehavior;
            fromPartial(object: Partial<_194.Misbehavior>): _194.Misbehavior;
            fromAmino(object: _194.MisbehaviorAmino): _194.Misbehavior;
            toAmino(message: _194.Misbehavior): _194.MisbehaviorAmino;
            fromAminoMsg(object: _194.MisbehaviorAminoMsg): _194.Misbehavior;
            fromProtoMsg(message: _194.MisbehaviorProtoMsg): _194.Misbehavior;
            toProto(message: _194.Misbehavior): Uint8Array;
            toProtoMsg(message: _194.Misbehavior): _194.MisbehaviorProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _194.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _194.Snapshot;
            fromPartial(object: Partial<_194.Snapshot>): _194.Snapshot;
            fromAmino(object: _194.SnapshotAmino): _194.Snapshot;
            toAmino(message: _194.Snapshot): _194.SnapshotAmino;
            fromAminoMsg(object: _194.SnapshotAminoMsg): _194.Snapshot;
            fromProtoMsg(message: _194.SnapshotProtoMsg): _194.Snapshot;
            toProto(message: _194.Snapshot): Uint8Array;
            toProtoMsg(message: _194.Snapshot): _194.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _196.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _196.Proof;
            fromPartial(object: Partial<_196.Proof>): _196.Proof;
            fromAmino(object: _196.ProofAmino): _196.Proof;
            toAmino(message: _196.Proof): _196.ProofAmino;
            fromAminoMsg(object: _196.ProofAminoMsg): _196.Proof;
            fromProtoMsg(message: _196.ProofProtoMsg): _196.Proof;
            toProto(message: _196.Proof): Uint8Array;
            toProtoMsg(message: _196.Proof): _196.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _196.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _196.ValueOp;
            fromPartial(object: Partial<_196.ValueOp>): _196.ValueOp;
            fromAmino(object: _196.ValueOpAmino): _196.ValueOp;
            toAmino(message: _196.ValueOp): _196.ValueOpAmino;
            fromAminoMsg(object: _196.ValueOpAminoMsg): _196.ValueOp;
            fromProtoMsg(message: _196.ValueOpProtoMsg): _196.ValueOp;
            toProto(message: _196.ValueOp): Uint8Array;
            toProtoMsg(message: _196.ValueOp): _196.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _196.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _196.DominoOp;
            fromPartial(object: Partial<_196.DominoOp>): _196.DominoOp;
            fromAmino(object: _196.DominoOpAmino): _196.DominoOp;
            toAmino(message: _196.DominoOp): _196.DominoOpAmino;
            fromAminoMsg(object: _196.DominoOpAminoMsg): _196.DominoOp;
            fromProtoMsg(message: _196.DominoOpProtoMsg): _196.DominoOp;
            toProto(message: _196.DominoOp): Uint8Array;
            toProtoMsg(message: _196.DominoOp): _196.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _196.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _196.ProofOp;
            fromPartial(object: Partial<_196.ProofOp>): _196.ProofOp;
            fromAmino(object: _196.ProofOpAmino): _196.ProofOp;
            toAmino(message: _196.ProofOp): _196.ProofOpAmino;
            fromAminoMsg(object: _196.ProofOpAminoMsg): _196.ProofOp;
            fromProtoMsg(message: _196.ProofOpProtoMsg): _196.ProofOp;
            toProto(message: _196.ProofOp): Uint8Array;
            toProtoMsg(message: _196.ProofOp): _196.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _196.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _196.ProofOps;
            fromPartial(object: Partial<_196.ProofOps>): _196.ProofOps;
            fromAmino(object: _196.ProofOpsAmino): _196.ProofOps;
            toAmino(message: _196.ProofOps): _196.ProofOpsAmino;
            fromAminoMsg(object: _196.ProofOpsAminoMsg): _196.ProofOps;
            fromProtoMsg(message: _196.ProofOpsProtoMsg): _196.ProofOps;
            toProto(message: _196.ProofOps): Uint8Array;
            toProtoMsg(message: _196.ProofOps): _196.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _195.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _195.PublicKey;
            fromPartial(object: Partial<_195.PublicKey>): _195.PublicKey;
            fromAmino(object: _195.PublicKeyAmino): _195.PublicKey;
            toAmino(message: _195.PublicKey): _195.PublicKeyAmino;
            fromAminoMsg(object: _195.PublicKeyAminoMsg): _195.PublicKey;
            fromProtoMsg(message: _195.PublicKeyProtoMsg): _195.PublicKey;
            toProto(message: _195.PublicKey): Uint8Array;
            toProtoMsg(message: _195.PublicKey): _195.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _197.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                fromJSON(object: any): _197.BitArray;
                fromPartial(object: Partial<_197.BitArray>): _197.BitArray;
                fromAmino(object: _197.BitArrayAmino): _197.BitArray;
                toAmino(message: _197.BitArray): _197.BitArrayAmino;
                fromAminoMsg(object: _197.BitArrayAminoMsg): _197.BitArray;
                fromProtoMsg(message: _197.BitArrayProtoMsg): _197.BitArray;
                toProto(message: _197.BitArray): Uint8Array;
                toProtoMsg(message: _197.BitArray): _197.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _198.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _198.NetAddress;
            fromPartial(object: Partial<_198.NetAddress>): _198.NetAddress;
            fromAmino(object: _198.NetAddressAmino): _198.NetAddress;
            toAmino(message: _198.NetAddress): _198.NetAddressAmino;
            fromAminoMsg(object: _198.NetAddressAminoMsg): _198.NetAddress;
            fromProtoMsg(message: _198.NetAddressProtoMsg): _198.NetAddress;
            toProto(message: _198.NetAddress): Uint8Array;
            toProtoMsg(message: _198.NetAddress): _198.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _198.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _198.ProtocolVersion;
            fromPartial(object: Partial<_198.ProtocolVersion>): _198.ProtocolVersion;
            fromAmino(object: _198.ProtocolVersionAmino): _198.ProtocolVersion;
            toAmino(message: _198.ProtocolVersion): _198.ProtocolVersionAmino;
            fromAminoMsg(object: _198.ProtocolVersionAminoMsg): _198.ProtocolVersion;
            fromProtoMsg(message: _198.ProtocolVersionProtoMsg): _198.ProtocolVersion;
            toProto(message: _198.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _198.ProtocolVersion): _198.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _198.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _198.DefaultNodeInfo;
            fromPartial(object: Partial<_198.DefaultNodeInfo>): _198.DefaultNodeInfo;
            fromAmino(object: _198.DefaultNodeInfoAmino): _198.DefaultNodeInfo;
            toAmino(message: _198.DefaultNodeInfo): _198.DefaultNodeInfoAmino;
            fromAminoMsg(object: _198.DefaultNodeInfoAminoMsg): _198.DefaultNodeInfo;
            fromProtoMsg(message: _198.DefaultNodeInfoProtoMsg): _198.DefaultNodeInfo;
            toProto(message: _198.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _198.DefaultNodeInfo): _198.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _198.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _198.DefaultNodeInfoOther;
            fromPartial(object: Partial<_198.DefaultNodeInfoOther>): _198.DefaultNodeInfoOther;
            fromAmino(object: _198.DefaultNodeInfoOtherAmino): _198.DefaultNodeInfoOther;
            toAmino(message: _198.DefaultNodeInfoOther): _198.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _198.DefaultNodeInfoOtherAminoMsg): _198.DefaultNodeInfoOther;
            fromProtoMsg(message: _198.DefaultNodeInfoOtherProtoMsg): _198.DefaultNodeInfoOther;
            toProto(message: _198.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _198.DefaultNodeInfoOther): _198.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _203.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.ValidatorSet;
            fromPartial(object: Partial<_203.ValidatorSet>): _203.ValidatorSet;
            fromAmino(object: _203.ValidatorSetAmino): _203.ValidatorSet;
            toAmino(message: _203.ValidatorSet): _203.ValidatorSetAmino;
            fromAminoMsg(object: _203.ValidatorSetAminoMsg): _203.ValidatorSet;
            fromProtoMsg(message: _203.ValidatorSetProtoMsg): _203.ValidatorSet;
            toProto(message: _203.ValidatorSet): Uint8Array;
            toProtoMsg(message: _203.ValidatorSet): _203.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _203.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.Validator;
            fromPartial(object: Partial<_203.Validator>): _203.Validator;
            fromAmino(object: _203.ValidatorAmino): _203.Validator;
            toAmino(message: _203.Validator): _203.ValidatorAmino;
            fromAminoMsg(object: _203.ValidatorAminoMsg): _203.Validator;
            fromProtoMsg(message: _203.ValidatorProtoMsg): _203.Validator;
            toProto(message: _203.Validator): Uint8Array;
            toProtoMsg(message: _203.Validator): _203.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _203.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.SimpleValidator;
            fromPartial(object: Partial<_203.SimpleValidator>): _203.SimpleValidator;
            fromAmino(object: _203.SimpleValidatorAmino): _203.SimpleValidator;
            toAmino(message: _203.SimpleValidator): _203.SimpleValidatorAmino;
            fromAminoMsg(object: _203.SimpleValidatorAminoMsg): _203.SimpleValidator;
            fromProtoMsg(message: _203.SimpleValidatorProtoMsg): _203.SimpleValidator;
            toProto(message: _203.SimpleValidator): Uint8Array;
            toProtoMsg(message: _203.SimpleValidator): _203.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _202.BlockIDFlag;
        blockIDFlagToJSON(object: _202.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _202.SignedMsgType;
        signedMsgTypeToJSON(object: _202.SignedMsgType): string;
        BlockIDFlag: typeof _202.BlockIDFlag;
        BlockIDFlagSDKType: typeof _202.BlockIDFlag;
        BlockIDFlagAmino: typeof _202.BlockIDFlag;
        SignedMsgType: typeof _202.SignedMsgType;
        SignedMsgTypeSDKType: typeof _202.SignedMsgType;
        SignedMsgTypeAmino: typeof _202.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _202.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.PartSetHeader;
            fromPartial(object: Partial<_202.PartSetHeader>): _202.PartSetHeader;
            fromAmino(object: _202.PartSetHeaderAmino): _202.PartSetHeader;
            toAmino(message: _202.PartSetHeader): _202.PartSetHeaderAmino;
            fromAminoMsg(object: _202.PartSetHeaderAminoMsg): _202.PartSetHeader;
            fromProtoMsg(message: _202.PartSetHeaderProtoMsg): _202.PartSetHeader;
            toProto(message: _202.PartSetHeader): Uint8Array;
            toProtoMsg(message: _202.PartSetHeader): _202.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _202.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.Part;
            fromPartial(object: Partial<_202.Part>): _202.Part;
            fromAmino(object: _202.PartAmino): _202.Part;
            toAmino(message: _202.Part): _202.PartAmino;
            fromAminoMsg(object: _202.PartAminoMsg): _202.Part;
            fromProtoMsg(message: _202.PartProtoMsg): _202.Part;
            toProto(message: _202.Part): Uint8Array;
            toProtoMsg(message: _202.Part): _202.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _202.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.BlockID;
            fromPartial(object: Partial<_202.BlockID>): _202.BlockID;
            fromAmino(object: _202.BlockIDAmino): _202.BlockID;
            toAmino(message: _202.BlockID): _202.BlockIDAmino;
            fromAminoMsg(object: _202.BlockIDAminoMsg): _202.BlockID;
            fromProtoMsg(message: _202.BlockIDProtoMsg): _202.BlockID;
            toProto(message: _202.BlockID): Uint8Array;
            toProtoMsg(message: _202.BlockID): _202.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _202.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.Header;
            fromPartial(object: Partial<_202.Header>): _202.Header;
            fromAmino(object: _202.HeaderAmino): _202.Header;
            toAmino(message: _202.Header): _202.HeaderAmino;
            fromAminoMsg(object: _202.HeaderAminoMsg): _202.Header;
            fromProtoMsg(message: _202.HeaderProtoMsg): _202.Header;
            toProto(message: _202.Header): Uint8Array;
            toProtoMsg(message: _202.Header): _202.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _202.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.Data;
            fromPartial(object: Partial<_202.Data>): _202.Data;
            fromAmino(object: _202.DataAmino): _202.Data;
            toAmino(message: _202.Data): _202.DataAmino;
            fromAminoMsg(object: _202.DataAminoMsg): _202.Data;
            fromProtoMsg(message: _202.DataProtoMsg): _202.Data;
            toProto(message: _202.Data): Uint8Array;
            toProtoMsg(message: _202.Data): _202.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _202.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.Vote;
            fromPartial(object: Partial<_202.Vote>): _202.Vote;
            fromAmino(object: _202.VoteAmino): _202.Vote;
            toAmino(message: _202.Vote): _202.VoteAmino;
            fromAminoMsg(object: _202.VoteAminoMsg): _202.Vote;
            fromProtoMsg(message: _202.VoteProtoMsg): _202.Vote;
            toProto(message: _202.Vote): Uint8Array;
            toProtoMsg(message: _202.Vote): _202.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _202.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.Commit;
            fromPartial(object: Partial<_202.Commit>): _202.Commit;
            fromAmino(object: _202.CommitAmino): _202.Commit;
            toAmino(message: _202.Commit): _202.CommitAmino;
            fromAminoMsg(object: _202.CommitAminoMsg): _202.Commit;
            fromProtoMsg(message: _202.CommitProtoMsg): _202.Commit;
            toProto(message: _202.Commit): Uint8Array;
            toProtoMsg(message: _202.Commit): _202.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _202.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.CommitSig;
            fromPartial(object: Partial<_202.CommitSig>): _202.CommitSig;
            fromAmino(object: _202.CommitSigAmino): _202.CommitSig;
            toAmino(message: _202.CommitSig): _202.CommitSigAmino;
            fromAminoMsg(object: _202.CommitSigAminoMsg): _202.CommitSig;
            fromProtoMsg(message: _202.CommitSigProtoMsg): _202.CommitSig;
            toProto(message: _202.CommitSig): Uint8Array;
            toProtoMsg(message: _202.CommitSig): _202.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _202.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.Proposal;
            fromPartial(object: Partial<_202.Proposal>): _202.Proposal;
            fromAmino(object: _202.ProposalAmino): _202.Proposal;
            toAmino(message: _202.Proposal): _202.ProposalAmino;
            fromAminoMsg(object: _202.ProposalAminoMsg): _202.Proposal;
            fromProtoMsg(message: _202.ProposalProtoMsg): _202.Proposal;
            toProto(message: _202.Proposal): Uint8Array;
            toProtoMsg(message: _202.Proposal): _202.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _202.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.SignedHeader;
            fromPartial(object: Partial<_202.SignedHeader>): _202.SignedHeader;
            fromAmino(object: _202.SignedHeaderAmino): _202.SignedHeader;
            toAmino(message: _202.SignedHeader): _202.SignedHeaderAmino;
            fromAminoMsg(object: _202.SignedHeaderAminoMsg): _202.SignedHeader;
            fromProtoMsg(message: _202.SignedHeaderProtoMsg): _202.SignedHeader;
            toProto(message: _202.SignedHeader): Uint8Array;
            toProtoMsg(message: _202.SignedHeader): _202.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _202.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.LightBlock;
            fromPartial(object: Partial<_202.LightBlock>): _202.LightBlock;
            fromAmino(object: _202.LightBlockAmino): _202.LightBlock;
            toAmino(message: _202.LightBlock): _202.LightBlockAmino;
            fromAminoMsg(object: _202.LightBlockAminoMsg): _202.LightBlock;
            fromProtoMsg(message: _202.LightBlockProtoMsg): _202.LightBlock;
            toProto(message: _202.LightBlock): Uint8Array;
            toProtoMsg(message: _202.LightBlock): _202.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _202.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.BlockMeta;
            fromPartial(object: Partial<_202.BlockMeta>): _202.BlockMeta;
            fromAmino(object: _202.BlockMetaAmino): _202.BlockMeta;
            toAmino(message: _202.BlockMeta): _202.BlockMetaAmino;
            fromAminoMsg(object: _202.BlockMetaAminoMsg): _202.BlockMeta;
            fromProtoMsg(message: _202.BlockMetaProtoMsg): _202.BlockMeta;
            toProto(message: _202.BlockMeta): Uint8Array;
            toProtoMsg(message: _202.BlockMeta): _202.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _202.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.TxProof;
            fromPartial(object: Partial<_202.TxProof>): _202.TxProof;
            fromAmino(object: _202.TxProofAmino): _202.TxProof;
            toAmino(message: _202.TxProof): _202.TxProofAmino;
            fromAminoMsg(object: _202.TxProofAminoMsg): _202.TxProof;
            fromProtoMsg(message: _202.TxProofProtoMsg): _202.TxProof;
            toProto(message: _202.TxProof): Uint8Array;
            toProtoMsg(message: _202.TxProof): _202.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _201.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _201.ConsensusParams;
            fromPartial(object: Partial<_201.ConsensusParams>): _201.ConsensusParams;
            fromAmino(object: _201.ConsensusParamsAmino): _201.ConsensusParams;
            toAmino(message: _201.ConsensusParams): _201.ConsensusParamsAmino;
            fromAminoMsg(object: _201.ConsensusParamsAminoMsg): _201.ConsensusParams;
            fromProtoMsg(message: _201.ConsensusParamsProtoMsg): _201.ConsensusParams;
            toProto(message: _201.ConsensusParams): Uint8Array;
            toProtoMsg(message: _201.ConsensusParams): _201.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _201.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _201.BlockParams;
            fromPartial(object: Partial<_201.BlockParams>): _201.BlockParams;
            fromAmino(object: _201.BlockParamsAmino): _201.BlockParams;
            toAmino(message: _201.BlockParams): _201.BlockParamsAmino;
            fromAminoMsg(object: _201.BlockParamsAminoMsg): _201.BlockParams;
            fromProtoMsg(message: _201.BlockParamsProtoMsg): _201.BlockParams;
            toProto(message: _201.BlockParams): Uint8Array;
            toProtoMsg(message: _201.BlockParams): _201.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _201.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _201.EvidenceParams;
            fromPartial(object: Partial<_201.EvidenceParams>): _201.EvidenceParams;
            fromAmino(object: _201.EvidenceParamsAmino): _201.EvidenceParams;
            toAmino(message: _201.EvidenceParams): _201.EvidenceParamsAmino;
            fromAminoMsg(object: _201.EvidenceParamsAminoMsg): _201.EvidenceParams;
            fromProtoMsg(message: _201.EvidenceParamsProtoMsg): _201.EvidenceParams;
            toProto(message: _201.EvidenceParams): Uint8Array;
            toProtoMsg(message: _201.EvidenceParams): _201.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _201.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _201.ValidatorParams;
            fromPartial(object: Partial<_201.ValidatorParams>): _201.ValidatorParams;
            fromAmino(object: _201.ValidatorParamsAmino): _201.ValidatorParams;
            toAmino(message: _201.ValidatorParams): _201.ValidatorParamsAmino;
            fromAminoMsg(object: _201.ValidatorParamsAminoMsg): _201.ValidatorParams;
            fromProtoMsg(message: _201.ValidatorParamsProtoMsg): _201.ValidatorParams;
            toProto(message: _201.ValidatorParams): Uint8Array;
            toProtoMsg(message: _201.ValidatorParams): _201.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _201.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _201.VersionParams;
            fromPartial(object: Partial<_201.VersionParams>): _201.VersionParams;
            fromAmino(object: _201.VersionParamsAmino): _201.VersionParams;
            toAmino(message: _201.VersionParams): _201.VersionParamsAmino;
            fromAminoMsg(object: _201.VersionParamsAminoMsg): _201.VersionParams;
            fromProtoMsg(message: _201.VersionParamsProtoMsg): _201.VersionParams;
            toProto(message: _201.VersionParams): Uint8Array;
            toProtoMsg(message: _201.VersionParams): _201.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _201.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _201.HashedParams;
            fromPartial(object: Partial<_201.HashedParams>): _201.HashedParams;
            fromAmino(object: _201.HashedParamsAmino): _201.HashedParams;
            toAmino(message: _201.HashedParams): _201.HashedParamsAmino;
            fromAminoMsg(object: _201.HashedParamsAminoMsg): _201.HashedParams;
            fromProtoMsg(message: _201.HashedParamsProtoMsg): _201.HashedParams;
            toProto(message: _201.HashedParams): Uint8Array;
            toProtoMsg(message: _201.HashedParams): _201.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _200.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _200.Evidence;
            fromPartial(object: Partial<_200.Evidence>): _200.Evidence;
            fromAmino(object: _200.EvidenceAmino): _200.Evidence;
            toAmino(message: _200.Evidence): _200.EvidenceAmino;
            fromAminoMsg(object: _200.EvidenceAminoMsg): _200.Evidence;
            fromProtoMsg(message: _200.EvidenceProtoMsg): _200.Evidence;
            toProto(message: _200.Evidence): Uint8Array;
            toProtoMsg(message: _200.Evidence): _200.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _200.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _200.DuplicateVoteEvidence;
            fromPartial(object: Partial<_200.DuplicateVoteEvidence>): _200.DuplicateVoteEvidence;
            fromAmino(object: _200.DuplicateVoteEvidenceAmino): _200.DuplicateVoteEvidence;
            toAmino(message: _200.DuplicateVoteEvidence): _200.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _200.DuplicateVoteEvidenceAminoMsg): _200.DuplicateVoteEvidence;
            fromProtoMsg(message: _200.DuplicateVoteEvidenceProtoMsg): _200.DuplicateVoteEvidence;
            toProto(message: _200.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _200.DuplicateVoteEvidence): _200.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _200.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _200.LightClientAttackEvidence;
            fromPartial(object: Partial<_200.LightClientAttackEvidence>): _200.LightClientAttackEvidence;
            fromAmino(object: _200.LightClientAttackEvidenceAmino): _200.LightClientAttackEvidence;
            toAmino(message: _200.LightClientAttackEvidence): _200.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _200.LightClientAttackEvidenceAminoMsg): _200.LightClientAttackEvidence;
            fromProtoMsg(message: _200.LightClientAttackEvidenceProtoMsg): _200.LightClientAttackEvidence;
            toProto(message: _200.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _200.LightClientAttackEvidence): _200.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _200.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _200.EvidenceList;
            fromPartial(object: Partial<_200.EvidenceList>): _200.EvidenceList;
            fromAmino(object: _200.EvidenceListAmino): _200.EvidenceList;
            toAmino(message: _200.EvidenceList): _200.EvidenceListAmino;
            fromAminoMsg(object: _200.EvidenceListAminoMsg): _200.EvidenceList;
            fromProtoMsg(message: _200.EvidenceListProtoMsg): _200.EvidenceList;
            toProto(message: _200.EvidenceList): Uint8Array;
            toProtoMsg(message: _200.EvidenceList): _200.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _199.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _199.Block;
            fromPartial(object: Partial<_199.Block>): _199.Block;
            fromAmino(object: _199.BlockAmino): _199.Block;
            toAmino(message: _199.Block): _199.BlockAmino;
            fromAminoMsg(object: _199.BlockAminoMsg): _199.Block;
            fromProtoMsg(message: _199.BlockProtoMsg): _199.Block;
            toProto(message: _199.Block): Uint8Array;
            toProtoMsg(message: _199.Block): _199.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _204.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _204.App;
            fromPartial(object: Partial<_204.App>): _204.App;
            fromAmino(object: _204.AppAmino): _204.App;
            toAmino(message: _204.App): _204.AppAmino;
            fromAminoMsg(object: _204.AppAminoMsg): _204.App;
            fromProtoMsg(message: _204.AppProtoMsg): _204.App;
            toProto(message: _204.App): Uint8Array;
            toProtoMsg(message: _204.App): _204.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _204.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _204.Consensus;
            fromPartial(object: Partial<_204.Consensus>): _204.Consensus;
            fromAmino(object: _204.ConsensusAmino): _204.Consensus;
            toAmino(message: _204.Consensus): _204.ConsensusAmino;
            fromAminoMsg(object: _204.ConsensusAminoMsg): _204.Consensus;
            fromProtoMsg(message: _204.ConsensusProtoMsg): _204.Consensus;
            toProto(message: _204.Consensus): Uint8Array;
            toProtoMsg(message: _204.Consensus): _204.ConsensusProtoMsg;
        };
    };
}
