import * as _140 from "./api/http";
import * as _141 from "./api/httpbody";
import * as _142 from "./protobuf/any";
import * as _143 from "./protobuf/descriptor";
import * as _144 from "./protobuf/timestamp";
import * as _145 from "./protobuf/duration";
export declare namespace google {
    const api: {
        HttpBody: {
            typeUrl: string;
            encode(message: _141.HttpBody, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.HttpBody;
            fromPartial(object: Partial<_141.HttpBody>): _141.HttpBody;
            fromAmino(object: _141.HttpBodyAmino): _141.HttpBody;
            toAmino(message: _141.HttpBody): _141.HttpBodyAmino;
            fromAminoMsg(object: _141.HttpBodyAminoMsg): _141.HttpBody;
            fromProtoMsg(message: _141.HttpBodyProtoMsg): _141.HttpBody;
            toProto(message: _141.HttpBody): Uint8Array;
            toProtoMsg(message: _141.HttpBody): _141.HttpBodyProtoMsg;
        };
        Http: {
            typeUrl: string;
            encode(message: _140.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _140.Http;
            fromPartial(object: Partial<_140.Http>): _140.Http;
            fromAmino(object: _140.HttpAmino): _140.Http;
            toAmino(message: _140.Http): _140.HttpAmino;
            fromAminoMsg(object: _140.HttpAminoMsg): _140.Http;
            fromProtoMsg(message: _140.HttpProtoMsg): _140.Http;
            toProto(message: _140.Http): Uint8Array;
            toProtoMsg(message: _140.Http): _140.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _140.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _140.HttpRule;
            fromPartial(object: Partial<_140.HttpRule>): _140.HttpRule;
            fromAmino(object: _140.HttpRuleAmino): _140.HttpRule;
            toAmino(message: _140.HttpRule): _140.HttpRuleAmino;
            fromAminoMsg(object: _140.HttpRuleAminoMsg): _140.HttpRule;
            fromProtoMsg(message: _140.HttpRuleProtoMsg): _140.HttpRule;
            toProto(message: _140.HttpRule): Uint8Array;
            toProtoMsg(message: _140.HttpRule): _140.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _140.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _140.CustomHttpPattern;
            fromPartial(object: Partial<_140.CustomHttpPattern>): _140.CustomHttpPattern;
            fromAmino(object: _140.CustomHttpPatternAmino): _140.CustomHttpPattern;
            toAmino(message: _140.CustomHttpPattern): _140.CustomHttpPatternAmino;
            fromAminoMsg(object: _140.CustomHttpPatternAminoMsg): _140.CustomHttpPattern;
            fromProtoMsg(message: _140.CustomHttpPatternProtoMsg): _140.CustomHttpPattern;
            toProto(message: _140.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _140.CustomHttpPattern): _140.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Duration: {
            typeUrl: string;
            encode(message: _145.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.Duration;
            fromPartial(object: Partial<_145.Duration>): _145.Duration;
            fromAmino(object: string): _145.Duration;
            toAmino(message: _145.Duration): string;
            fromAminoMsg(object: _145.DurationAminoMsg): _145.Duration;
            fromProtoMsg(message: _145.DurationProtoMsg): _145.Duration;
            toProto(message: _145.Duration): Uint8Array;
            toProtoMsg(message: _145.Duration): _145.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _144.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _144.Timestamp;
            fromPartial(object: Partial<_144.Timestamp>): _144.Timestamp;
            fromAmino(object: string): _144.Timestamp;
            toAmino(message: _144.Timestamp): string;
            fromAminoMsg(object: _144.TimestampAminoMsg): _144.Timestamp;
            fromProtoMsg(message: _144.TimestampProtoMsg): _144.Timestamp;
            toProto(message: _144.Timestamp): Uint8Array;
            toProtoMsg(message: _144.Timestamp): _144.TimestampProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _143.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _143.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _143.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _143.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _143.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _143.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _143.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _143.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _143.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _143.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _143.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _143.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _143.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _143.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _143.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _143.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _143.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _143.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _143.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _143.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _143.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _143.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _143.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _143.FieldOptions_CType;
        FieldOptions_JSType: typeof _143.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _143.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _143.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _143.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _143.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _143.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _143.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.FileDescriptorSet;
            fromPartial(object: Partial<_143.FileDescriptorSet>): _143.FileDescriptorSet;
            fromAmino(object: _143.FileDescriptorSetAmino): _143.FileDescriptorSet;
            toAmino(message: _143.FileDescriptorSet): _143.FileDescriptorSetAmino;
            fromAminoMsg(object: _143.FileDescriptorSetAminoMsg): _143.FileDescriptorSet;
            fromProtoMsg(message: _143.FileDescriptorSetProtoMsg): _143.FileDescriptorSet;
            toProto(message: _143.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _143.FileDescriptorSet): _143.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _143.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.FileDescriptorProto;
            fromPartial(object: Partial<_143.FileDescriptorProto>): _143.FileDescriptorProto;
            fromAmino(object: _143.FileDescriptorProtoAmino): _143.FileDescriptorProto;
            toAmino(message: _143.FileDescriptorProto): _143.FileDescriptorProtoAmino;
            fromAminoMsg(object: _143.FileDescriptorProtoAminoMsg): _143.FileDescriptorProto;
            fromProtoMsg(message: _143.FileDescriptorProtoProtoMsg): _143.FileDescriptorProto;
            toProto(message: _143.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _143.FileDescriptorProto): _143.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _143.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.DescriptorProto;
            fromPartial(object: Partial<_143.DescriptorProto>): _143.DescriptorProto;
            fromAmino(object: _143.DescriptorProtoAmino): _143.DescriptorProto;
            toAmino(message: _143.DescriptorProto): _143.DescriptorProtoAmino;
            fromAminoMsg(object: _143.DescriptorProtoAminoMsg): _143.DescriptorProto;
            fromProtoMsg(message: _143.DescriptorProtoProtoMsg): _143.DescriptorProto;
            toProto(message: _143.DescriptorProto): Uint8Array;
            toProtoMsg(message: _143.DescriptorProto): _143.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _143.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_143.DescriptorProto_ExtensionRange>): _143.DescriptorProto_ExtensionRange;
            fromAmino(object: _143.DescriptorProto_ExtensionRangeAmino): _143.DescriptorProto_ExtensionRange;
            toAmino(message: _143.DescriptorProto_ExtensionRange): _143.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _143.DescriptorProto_ExtensionRangeAminoMsg): _143.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _143.DescriptorProto_ExtensionRangeProtoMsg): _143.DescriptorProto_ExtensionRange;
            toProto(message: _143.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _143.DescriptorProto_ExtensionRange): _143.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _143.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_143.DescriptorProto_ReservedRange>): _143.DescriptorProto_ReservedRange;
            fromAmino(object: _143.DescriptorProto_ReservedRangeAmino): _143.DescriptorProto_ReservedRange;
            toAmino(message: _143.DescriptorProto_ReservedRange): _143.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _143.DescriptorProto_ReservedRangeAminoMsg): _143.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _143.DescriptorProto_ReservedRangeProtoMsg): _143.DescriptorProto_ReservedRange;
            toProto(message: _143.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _143.DescriptorProto_ReservedRange): _143.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _143.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.ExtensionRangeOptions;
            fromPartial(object: Partial<_143.ExtensionRangeOptions>): _143.ExtensionRangeOptions;
            fromAmino(object: _143.ExtensionRangeOptionsAmino): _143.ExtensionRangeOptions;
            toAmino(message: _143.ExtensionRangeOptions): _143.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _143.ExtensionRangeOptionsAminoMsg): _143.ExtensionRangeOptions;
            fromProtoMsg(message: _143.ExtensionRangeOptionsProtoMsg): _143.ExtensionRangeOptions;
            toProto(message: _143.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _143.ExtensionRangeOptions): _143.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _143.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.FieldDescriptorProto;
            fromPartial(object: Partial<_143.FieldDescriptorProto>): _143.FieldDescriptorProto;
            fromAmino(object: _143.FieldDescriptorProtoAmino): _143.FieldDescriptorProto;
            toAmino(message: _143.FieldDescriptorProto): _143.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _143.FieldDescriptorProtoAminoMsg): _143.FieldDescriptorProto;
            fromProtoMsg(message: _143.FieldDescriptorProtoProtoMsg): _143.FieldDescriptorProto;
            toProto(message: _143.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _143.FieldDescriptorProto): _143.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _143.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.OneofDescriptorProto;
            fromPartial(object: Partial<_143.OneofDescriptorProto>): _143.OneofDescriptorProto;
            fromAmino(object: _143.OneofDescriptorProtoAmino): _143.OneofDescriptorProto;
            toAmino(message: _143.OneofDescriptorProto): _143.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _143.OneofDescriptorProtoAminoMsg): _143.OneofDescriptorProto;
            fromProtoMsg(message: _143.OneofDescriptorProtoProtoMsg): _143.OneofDescriptorProto;
            toProto(message: _143.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _143.OneofDescriptorProto): _143.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _143.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.EnumDescriptorProto;
            fromPartial(object: Partial<_143.EnumDescriptorProto>): _143.EnumDescriptorProto;
            fromAmino(object: _143.EnumDescriptorProtoAmino): _143.EnumDescriptorProto;
            toAmino(message: _143.EnumDescriptorProto): _143.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _143.EnumDescriptorProtoAminoMsg): _143.EnumDescriptorProto;
            fromProtoMsg(message: _143.EnumDescriptorProtoProtoMsg): _143.EnumDescriptorProto;
            toProto(message: _143.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _143.EnumDescriptorProto): _143.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _143.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_143.EnumDescriptorProto_EnumReservedRange>): _143.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _143.EnumDescriptorProto_EnumReservedRangeAmino): _143.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _143.EnumDescriptorProto_EnumReservedRange): _143.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _143.EnumDescriptorProto_EnumReservedRangeAminoMsg): _143.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _143.EnumDescriptorProto_EnumReservedRangeProtoMsg): _143.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _143.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _143.EnumDescriptorProto_EnumReservedRange): _143.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _143.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.EnumValueDescriptorProto;
            fromPartial(object: Partial<_143.EnumValueDescriptorProto>): _143.EnumValueDescriptorProto;
            fromAmino(object: _143.EnumValueDescriptorProtoAmino): _143.EnumValueDescriptorProto;
            toAmino(message: _143.EnumValueDescriptorProto): _143.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _143.EnumValueDescriptorProtoAminoMsg): _143.EnumValueDescriptorProto;
            fromProtoMsg(message: _143.EnumValueDescriptorProtoProtoMsg): _143.EnumValueDescriptorProto;
            toProto(message: _143.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _143.EnumValueDescriptorProto): _143.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _143.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.ServiceDescriptorProto;
            fromPartial(object: Partial<_143.ServiceDescriptorProto>): _143.ServiceDescriptorProto;
            fromAmino(object: _143.ServiceDescriptorProtoAmino): _143.ServiceDescriptorProto;
            toAmino(message: _143.ServiceDescriptorProto): _143.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _143.ServiceDescriptorProtoAminoMsg): _143.ServiceDescriptorProto;
            fromProtoMsg(message: _143.ServiceDescriptorProtoProtoMsg): _143.ServiceDescriptorProto;
            toProto(message: _143.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _143.ServiceDescriptorProto): _143.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _143.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.MethodDescriptorProto;
            fromPartial(object: Partial<_143.MethodDescriptorProto>): _143.MethodDescriptorProto;
            fromAmino(object: _143.MethodDescriptorProtoAmino): _143.MethodDescriptorProto;
            toAmino(message: _143.MethodDescriptorProto): _143.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _143.MethodDescriptorProtoAminoMsg): _143.MethodDescriptorProto;
            fromProtoMsg(message: _143.MethodDescriptorProtoProtoMsg): _143.MethodDescriptorProto;
            toProto(message: _143.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _143.MethodDescriptorProto): _143.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _143.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.FileOptions;
            fromPartial(object: Partial<_143.FileOptions>): _143.FileOptions;
            fromAmino(object: _143.FileOptionsAmino): _143.FileOptions;
            toAmino(message: _143.FileOptions): _143.FileOptionsAmino;
            fromAminoMsg(object: _143.FileOptionsAminoMsg): _143.FileOptions;
            fromProtoMsg(message: _143.FileOptionsProtoMsg): _143.FileOptions;
            toProto(message: _143.FileOptions): Uint8Array;
            toProtoMsg(message: _143.FileOptions): _143.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _143.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.MessageOptions;
            fromPartial(object: Partial<_143.MessageOptions>): _143.MessageOptions;
            fromAmino(object: _143.MessageOptionsAmino): _143.MessageOptions;
            toAmino(message: _143.MessageOptions): _143.MessageOptionsAmino;
            fromAminoMsg(object: _143.MessageOptionsAminoMsg): _143.MessageOptions;
            fromProtoMsg(message: _143.MessageOptionsProtoMsg): _143.MessageOptions;
            toProto(message: _143.MessageOptions): Uint8Array;
            toProtoMsg(message: _143.MessageOptions): _143.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _143.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.FieldOptions;
            fromPartial(object: Partial<_143.FieldOptions>): _143.FieldOptions;
            fromAmino(object: _143.FieldOptionsAmino): _143.FieldOptions;
            toAmino(message: _143.FieldOptions): _143.FieldOptionsAmino;
            fromAminoMsg(object: _143.FieldOptionsAminoMsg): _143.FieldOptions;
            fromProtoMsg(message: _143.FieldOptionsProtoMsg): _143.FieldOptions;
            toProto(message: _143.FieldOptions): Uint8Array;
            toProtoMsg(message: _143.FieldOptions): _143.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _143.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.OneofOptions;
            fromPartial(object: Partial<_143.OneofOptions>): _143.OneofOptions;
            fromAmino(object: _143.OneofOptionsAmino): _143.OneofOptions;
            toAmino(message: _143.OneofOptions): _143.OneofOptionsAmino;
            fromAminoMsg(object: _143.OneofOptionsAminoMsg): _143.OneofOptions;
            fromProtoMsg(message: _143.OneofOptionsProtoMsg): _143.OneofOptions;
            toProto(message: _143.OneofOptions): Uint8Array;
            toProtoMsg(message: _143.OneofOptions): _143.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _143.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.EnumOptions;
            fromPartial(object: Partial<_143.EnumOptions>): _143.EnumOptions;
            fromAmino(object: _143.EnumOptionsAmino): _143.EnumOptions;
            toAmino(message: _143.EnumOptions): _143.EnumOptionsAmino;
            fromAminoMsg(object: _143.EnumOptionsAminoMsg): _143.EnumOptions;
            fromProtoMsg(message: _143.EnumOptionsProtoMsg): _143.EnumOptions;
            toProto(message: _143.EnumOptions): Uint8Array;
            toProtoMsg(message: _143.EnumOptions): _143.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _143.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.EnumValueOptions;
            fromPartial(object: Partial<_143.EnumValueOptions>): _143.EnumValueOptions;
            fromAmino(object: _143.EnumValueOptionsAmino): _143.EnumValueOptions;
            toAmino(message: _143.EnumValueOptions): _143.EnumValueOptionsAmino;
            fromAminoMsg(object: _143.EnumValueOptionsAminoMsg): _143.EnumValueOptions;
            fromProtoMsg(message: _143.EnumValueOptionsProtoMsg): _143.EnumValueOptions;
            toProto(message: _143.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _143.EnumValueOptions): _143.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _143.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.ServiceOptions;
            fromPartial(object: Partial<_143.ServiceOptions>): _143.ServiceOptions;
            fromAmino(object: _143.ServiceOptionsAmino): _143.ServiceOptions;
            toAmino(message: _143.ServiceOptions): _143.ServiceOptionsAmino;
            fromAminoMsg(object: _143.ServiceOptionsAminoMsg): _143.ServiceOptions;
            fromProtoMsg(message: _143.ServiceOptionsProtoMsg): _143.ServiceOptions;
            toProto(message: _143.ServiceOptions): Uint8Array;
            toProtoMsg(message: _143.ServiceOptions): _143.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _143.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.MethodOptions;
            fromPartial(object: Partial<_143.MethodOptions>): _143.MethodOptions;
            fromAmino(object: _143.MethodOptionsAmino): _143.MethodOptions;
            toAmino(message: _143.MethodOptions): _143.MethodOptionsAmino;
            fromAminoMsg(object: _143.MethodOptionsAminoMsg): _143.MethodOptions;
            fromProtoMsg(message: _143.MethodOptionsProtoMsg): _143.MethodOptions;
            toProto(message: _143.MethodOptions): Uint8Array;
            toProtoMsg(message: _143.MethodOptions): _143.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _143.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.UninterpretedOption;
            fromPartial(object: Partial<_143.UninterpretedOption>): _143.UninterpretedOption;
            fromAmino(object: _143.UninterpretedOptionAmino): _143.UninterpretedOption;
            toAmino(message: _143.UninterpretedOption): _143.UninterpretedOptionAmino;
            fromAminoMsg(object: _143.UninterpretedOptionAminoMsg): _143.UninterpretedOption;
            fromProtoMsg(message: _143.UninterpretedOptionProtoMsg): _143.UninterpretedOption;
            toProto(message: _143.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _143.UninterpretedOption): _143.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _143.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_143.UninterpretedOption_NamePart>): _143.UninterpretedOption_NamePart;
            fromAmino(object: _143.UninterpretedOption_NamePartAmino): _143.UninterpretedOption_NamePart;
            toAmino(message: _143.UninterpretedOption_NamePart): _143.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _143.UninterpretedOption_NamePartAminoMsg): _143.UninterpretedOption_NamePart;
            fromProtoMsg(message: _143.UninterpretedOption_NamePartProtoMsg): _143.UninterpretedOption_NamePart;
            toProto(message: _143.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _143.UninterpretedOption_NamePart): _143.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _143.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.SourceCodeInfo;
            fromPartial(object: Partial<_143.SourceCodeInfo>): _143.SourceCodeInfo;
            fromAmino(object: _143.SourceCodeInfoAmino): _143.SourceCodeInfo;
            toAmino(message: _143.SourceCodeInfo): _143.SourceCodeInfoAmino;
            fromAminoMsg(object: _143.SourceCodeInfoAminoMsg): _143.SourceCodeInfo;
            fromProtoMsg(message: _143.SourceCodeInfoProtoMsg): _143.SourceCodeInfo;
            toProto(message: _143.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _143.SourceCodeInfo): _143.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _143.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.SourceCodeInfo_Location;
            fromPartial(object: Partial<_143.SourceCodeInfo_Location>): _143.SourceCodeInfo_Location;
            fromAmino(object: _143.SourceCodeInfo_LocationAmino): _143.SourceCodeInfo_Location;
            toAmino(message: _143.SourceCodeInfo_Location): _143.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _143.SourceCodeInfo_LocationAminoMsg): _143.SourceCodeInfo_Location;
            fromProtoMsg(message: _143.SourceCodeInfo_LocationProtoMsg): _143.SourceCodeInfo_Location;
            toProto(message: _143.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _143.SourceCodeInfo_Location): _143.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _143.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.GeneratedCodeInfo;
            fromPartial(object: Partial<_143.GeneratedCodeInfo>): _143.GeneratedCodeInfo;
            fromAmino(object: _143.GeneratedCodeInfoAmino): _143.GeneratedCodeInfo;
            toAmino(message: _143.GeneratedCodeInfo): _143.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _143.GeneratedCodeInfoAminoMsg): _143.GeneratedCodeInfo;
            fromProtoMsg(message: _143.GeneratedCodeInfoProtoMsg): _143.GeneratedCodeInfo;
            toProto(message: _143.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _143.GeneratedCodeInfo): _143.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _143.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_143.GeneratedCodeInfo_Annotation>): _143.GeneratedCodeInfo_Annotation;
            fromAmino(object: _143.GeneratedCodeInfo_AnnotationAmino): _143.GeneratedCodeInfo_Annotation;
            toAmino(message: _143.GeneratedCodeInfo_Annotation): _143.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _143.GeneratedCodeInfo_AnnotationAminoMsg): _143.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _143.GeneratedCodeInfo_AnnotationProtoMsg): _143.GeneratedCodeInfo_Annotation;
            toProto(message: _143.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _143.GeneratedCodeInfo_Annotation): _143.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _142.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _142.Any;
            fromPartial(object: Partial<_142.Any>): _142.Any;
            fromAmino(object: _142.AnyAmino): _142.Any;
            toAmino(message: _142.Any): _142.AnyAmino;
            fromAminoMsg(object: _142.AnyAminoMsg): _142.Any;
            fromProtoMsg(message: _142.AnyProtoMsg): _142.Any;
            toProto(message: _142.Any): Uint8Array;
            toProtoMsg(message: _142.Any): _142.AnyProtoMsg;
        };
    };
}
