import * as _177 from "./api/http";
import * as _178 from "./protobuf/descriptor";
import * as _179 from "./protobuf/any";
import * as _180 from "./protobuf/timestamp";
import * as _181 from "./protobuf/duration";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _177.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _177.Http;
            fromPartial(object: Partial<_177.Http>): _177.Http;
            fromAmino(object: _177.HttpAmino): _177.Http;
            toAmino(message: _177.Http): _177.HttpAmino;
            fromAminoMsg(object: _177.HttpAminoMsg): _177.Http;
            fromProtoMsg(message: _177.HttpProtoMsg): _177.Http;
            toProto(message: _177.Http): Uint8Array;
            toProtoMsg(message: _177.Http): _177.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _177.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _177.HttpRule;
            fromPartial(object: Partial<_177.HttpRule>): _177.HttpRule;
            fromAmino(object: _177.HttpRuleAmino): _177.HttpRule;
            toAmino(message: _177.HttpRule): _177.HttpRuleAmino;
            fromAminoMsg(object: _177.HttpRuleAminoMsg): _177.HttpRule;
            fromProtoMsg(message: _177.HttpRuleProtoMsg): _177.HttpRule;
            toProto(message: _177.HttpRule): Uint8Array;
            toProtoMsg(message: _177.HttpRule): _177.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _177.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _177.CustomHttpPattern;
            fromPartial(object: Partial<_177.CustomHttpPattern>): _177.CustomHttpPattern;
            fromAmino(object: _177.CustomHttpPatternAmino): _177.CustomHttpPattern;
            toAmino(message: _177.CustomHttpPattern): _177.CustomHttpPatternAmino;
            fromAminoMsg(object: _177.CustomHttpPatternAminoMsg): _177.CustomHttpPattern;
            fromProtoMsg(message: _177.CustomHttpPatternProtoMsg): _177.CustomHttpPattern;
            toProto(message: _177.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _177.CustomHttpPattern): _177.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Duration: {
            typeUrl: string;
            encode(message: _181.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _181.Duration;
            fromPartial(object: Partial<_181.Duration>): _181.Duration;
            fromAmino(object: string): _181.Duration;
            toAmino(message: _181.Duration): string;
            fromAminoMsg(object: _181.DurationAminoMsg): _181.Duration;
            fromProtoMsg(message: _181.DurationProtoMsg): _181.Duration;
            toProto(message: _181.Duration): Uint8Array;
            toProtoMsg(message: _181.Duration): _181.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _180.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.Timestamp;
            fromPartial(object: Partial<_180.Timestamp>): _180.Timestamp;
            fromAmino(object: string): _180.Timestamp;
            toAmino(message: _180.Timestamp): string;
            fromAminoMsg(object: _180.TimestampAminoMsg): _180.Timestamp;
            fromProtoMsg(message: _180.TimestampProtoMsg): _180.Timestamp;
            toProto(message: _180.Timestamp): Uint8Array;
            toProtoMsg(message: _180.Timestamp): _180.TimestampProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _179.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _179.Any;
            fromPartial(object: Partial<_179.Any>): _179.Any;
            fromAmino(object: _179.AnyAmino): _179.Any;
            toAmino(message: _179.Any): _179.AnyAmino;
            fromAminoMsg(object: _179.AnyAminoMsg): _179.Any;
            fromProtoMsg(message: _179.AnyProtoMsg): _179.Any;
            toProto(message: _179.Any): Uint8Array;
            toProtoMsg(message: _179.Any): _179.AnyProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _178.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _178.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _178.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _178.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _178.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _178.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _178.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _178.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _178.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _178.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _178.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _178.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _178.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _178.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _178.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _178.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _178.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _178.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _178.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _178.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _178.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _178.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _178.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _178.FieldOptions_CType;
        FieldOptions_JSType: typeof _178.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _178.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _178.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _178.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _178.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _178.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _178.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.FileDescriptorSet;
            fromPartial(object: Partial<_178.FileDescriptorSet>): _178.FileDescriptorSet;
            fromAmino(object: _178.FileDescriptorSetAmino): _178.FileDescriptorSet;
            toAmino(message: _178.FileDescriptorSet): _178.FileDescriptorSetAmino;
            fromAminoMsg(object: _178.FileDescriptorSetAminoMsg): _178.FileDescriptorSet;
            fromProtoMsg(message: _178.FileDescriptorSetProtoMsg): _178.FileDescriptorSet;
            toProto(message: _178.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _178.FileDescriptorSet): _178.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _178.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.FileDescriptorProto;
            fromPartial(object: Partial<_178.FileDescriptorProto>): _178.FileDescriptorProto;
            fromAmino(object: _178.FileDescriptorProtoAmino): _178.FileDescriptorProto;
            toAmino(message: _178.FileDescriptorProto): _178.FileDescriptorProtoAmino;
            fromAminoMsg(object: _178.FileDescriptorProtoAminoMsg): _178.FileDescriptorProto;
            fromProtoMsg(message: _178.FileDescriptorProtoProtoMsg): _178.FileDescriptorProto;
            toProto(message: _178.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _178.FileDescriptorProto): _178.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _178.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.DescriptorProto;
            fromPartial(object: Partial<_178.DescriptorProto>): _178.DescriptorProto;
            fromAmino(object: _178.DescriptorProtoAmino): _178.DescriptorProto;
            toAmino(message: _178.DescriptorProto): _178.DescriptorProtoAmino;
            fromAminoMsg(object: _178.DescriptorProtoAminoMsg): _178.DescriptorProto;
            fromProtoMsg(message: _178.DescriptorProtoProtoMsg): _178.DescriptorProto;
            toProto(message: _178.DescriptorProto): Uint8Array;
            toProtoMsg(message: _178.DescriptorProto): _178.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _178.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_178.DescriptorProto_ExtensionRange>): _178.DescriptorProto_ExtensionRange;
            fromAmino(object: _178.DescriptorProto_ExtensionRangeAmino): _178.DescriptorProto_ExtensionRange;
            toAmino(message: _178.DescriptorProto_ExtensionRange): _178.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _178.DescriptorProto_ExtensionRangeAminoMsg): _178.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _178.DescriptorProto_ExtensionRangeProtoMsg): _178.DescriptorProto_ExtensionRange;
            toProto(message: _178.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _178.DescriptorProto_ExtensionRange): _178.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _178.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_178.DescriptorProto_ReservedRange>): _178.DescriptorProto_ReservedRange;
            fromAmino(object: _178.DescriptorProto_ReservedRangeAmino): _178.DescriptorProto_ReservedRange;
            toAmino(message: _178.DescriptorProto_ReservedRange): _178.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _178.DescriptorProto_ReservedRangeAminoMsg): _178.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _178.DescriptorProto_ReservedRangeProtoMsg): _178.DescriptorProto_ReservedRange;
            toProto(message: _178.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _178.DescriptorProto_ReservedRange): _178.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _178.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.ExtensionRangeOptions;
            fromPartial(object: Partial<_178.ExtensionRangeOptions>): _178.ExtensionRangeOptions;
            fromAmino(object: _178.ExtensionRangeOptionsAmino): _178.ExtensionRangeOptions;
            toAmino(message: _178.ExtensionRangeOptions): _178.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _178.ExtensionRangeOptionsAminoMsg): _178.ExtensionRangeOptions;
            fromProtoMsg(message: _178.ExtensionRangeOptionsProtoMsg): _178.ExtensionRangeOptions;
            toProto(message: _178.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _178.ExtensionRangeOptions): _178.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _178.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.FieldDescriptorProto;
            fromPartial(object: Partial<_178.FieldDescriptorProto>): _178.FieldDescriptorProto;
            fromAmino(object: _178.FieldDescriptorProtoAmino): _178.FieldDescriptorProto;
            toAmino(message: _178.FieldDescriptorProto): _178.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _178.FieldDescriptorProtoAminoMsg): _178.FieldDescriptorProto;
            fromProtoMsg(message: _178.FieldDescriptorProtoProtoMsg): _178.FieldDescriptorProto;
            toProto(message: _178.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _178.FieldDescriptorProto): _178.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _178.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.OneofDescriptorProto;
            fromPartial(object: Partial<_178.OneofDescriptorProto>): _178.OneofDescriptorProto;
            fromAmino(object: _178.OneofDescriptorProtoAmino): _178.OneofDescriptorProto;
            toAmino(message: _178.OneofDescriptorProto): _178.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _178.OneofDescriptorProtoAminoMsg): _178.OneofDescriptorProto;
            fromProtoMsg(message: _178.OneofDescriptorProtoProtoMsg): _178.OneofDescriptorProto;
            toProto(message: _178.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _178.OneofDescriptorProto): _178.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _178.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.EnumDescriptorProto;
            fromPartial(object: Partial<_178.EnumDescriptorProto>): _178.EnumDescriptorProto;
            fromAmino(object: _178.EnumDescriptorProtoAmino): _178.EnumDescriptorProto;
            toAmino(message: _178.EnumDescriptorProto): _178.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _178.EnumDescriptorProtoAminoMsg): _178.EnumDescriptorProto;
            fromProtoMsg(message: _178.EnumDescriptorProtoProtoMsg): _178.EnumDescriptorProto;
            toProto(message: _178.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _178.EnumDescriptorProto): _178.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _178.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_178.EnumDescriptorProto_EnumReservedRange>): _178.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _178.EnumDescriptorProto_EnumReservedRangeAmino): _178.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _178.EnumDescriptorProto_EnumReservedRange): _178.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _178.EnumDescriptorProto_EnumReservedRangeAminoMsg): _178.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _178.EnumDescriptorProto_EnumReservedRangeProtoMsg): _178.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _178.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _178.EnumDescriptorProto_EnumReservedRange): _178.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _178.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.EnumValueDescriptorProto;
            fromPartial(object: Partial<_178.EnumValueDescriptorProto>): _178.EnumValueDescriptorProto;
            fromAmino(object: _178.EnumValueDescriptorProtoAmino): _178.EnumValueDescriptorProto;
            toAmino(message: _178.EnumValueDescriptorProto): _178.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _178.EnumValueDescriptorProtoAminoMsg): _178.EnumValueDescriptorProto;
            fromProtoMsg(message: _178.EnumValueDescriptorProtoProtoMsg): _178.EnumValueDescriptorProto;
            toProto(message: _178.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _178.EnumValueDescriptorProto): _178.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _178.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.ServiceDescriptorProto;
            fromPartial(object: Partial<_178.ServiceDescriptorProto>): _178.ServiceDescriptorProto;
            fromAmino(object: _178.ServiceDescriptorProtoAmino): _178.ServiceDescriptorProto;
            toAmino(message: _178.ServiceDescriptorProto): _178.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _178.ServiceDescriptorProtoAminoMsg): _178.ServiceDescriptorProto;
            fromProtoMsg(message: _178.ServiceDescriptorProtoProtoMsg): _178.ServiceDescriptorProto;
            toProto(message: _178.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _178.ServiceDescriptorProto): _178.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _178.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.MethodDescriptorProto;
            fromPartial(object: Partial<_178.MethodDescriptorProto>): _178.MethodDescriptorProto;
            fromAmino(object: _178.MethodDescriptorProtoAmino): _178.MethodDescriptorProto;
            toAmino(message: _178.MethodDescriptorProto): _178.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _178.MethodDescriptorProtoAminoMsg): _178.MethodDescriptorProto;
            fromProtoMsg(message: _178.MethodDescriptorProtoProtoMsg): _178.MethodDescriptorProto;
            toProto(message: _178.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _178.MethodDescriptorProto): _178.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _178.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.FileOptions;
            fromPartial(object: Partial<_178.FileOptions>): _178.FileOptions;
            fromAmino(object: _178.FileOptionsAmino): _178.FileOptions;
            toAmino(message: _178.FileOptions): _178.FileOptionsAmino;
            fromAminoMsg(object: _178.FileOptionsAminoMsg): _178.FileOptions;
            fromProtoMsg(message: _178.FileOptionsProtoMsg): _178.FileOptions;
            toProto(message: _178.FileOptions): Uint8Array;
            toProtoMsg(message: _178.FileOptions): _178.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _178.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.MessageOptions;
            fromPartial(object: Partial<_178.MessageOptions>): _178.MessageOptions;
            fromAmino(object: _178.MessageOptionsAmino): _178.MessageOptions;
            toAmino(message: _178.MessageOptions): _178.MessageOptionsAmino;
            fromAminoMsg(object: _178.MessageOptionsAminoMsg): _178.MessageOptions;
            fromProtoMsg(message: _178.MessageOptionsProtoMsg): _178.MessageOptions;
            toProto(message: _178.MessageOptions): Uint8Array;
            toProtoMsg(message: _178.MessageOptions): _178.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _178.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.FieldOptions;
            fromPartial(object: Partial<_178.FieldOptions>): _178.FieldOptions;
            fromAmino(object: _178.FieldOptionsAmino): _178.FieldOptions;
            toAmino(message: _178.FieldOptions): _178.FieldOptionsAmino;
            fromAminoMsg(object: _178.FieldOptionsAminoMsg): _178.FieldOptions;
            fromProtoMsg(message: _178.FieldOptionsProtoMsg): _178.FieldOptions;
            toProto(message: _178.FieldOptions): Uint8Array;
            toProtoMsg(message: _178.FieldOptions): _178.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _178.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.OneofOptions;
            fromPartial(object: Partial<_178.OneofOptions>): _178.OneofOptions;
            fromAmino(object: _178.OneofOptionsAmino): _178.OneofOptions;
            toAmino(message: _178.OneofOptions): _178.OneofOptionsAmino;
            fromAminoMsg(object: _178.OneofOptionsAminoMsg): _178.OneofOptions;
            fromProtoMsg(message: _178.OneofOptionsProtoMsg): _178.OneofOptions;
            toProto(message: _178.OneofOptions): Uint8Array;
            toProtoMsg(message: _178.OneofOptions): _178.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _178.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.EnumOptions;
            fromPartial(object: Partial<_178.EnumOptions>): _178.EnumOptions;
            fromAmino(object: _178.EnumOptionsAmino): _178.EnumOptions;
            toAmino(message: _178.EnumOptions): _178.EnumOptionsAmino;
            fromAminoMsg(object: _178.EnumOptionsAminoMsg): _178.EnumOptions;
            fromProtoMsg(message: _178.EnumOptionsProtoMsg): _178.EnumOptions;
            toProto(message: _178.EnumOptions): Uint8Array;
            toProtoMsg(message: _178.EnumOptions): _178.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _178.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.EnumValueOptions;
            fromPartial(object: Partial<_178.EnumValueOptions>): _178.EnumValueOptions;
            fromAmino(object: _178.EnumValueOptionsAmino): _178.EnumValueOptions;
            toAmino(message: _178.EnumValueOptions): _178.EnumValueOptionsAmino;
            fromAminoMsg(object: _178.EnumValueOptionsAminoMsg): _178.EnumValueOptions;
            fromProtoMsg(message: _178.EnumValueOptionsProtoMsg): _178.EnumValueOptions;
            toProto(message: _178.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _178.EnumValueOptions): _178.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _178.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.ServiceOptions;
            fromPartial(object: Partial<_178.ServiceOptions>): _178.ServiceOptions;
            fromAmino(object: _178.ServiceOptionsAmino): _178.ServiceOptions;
            toAmino(message: _178.ServiceOptions): _178.ServiceOptionsAmino;
            fromAminoMsg(object: _178.ServiceOptionsAminoMsg): _178.ServiceOptions;
            fromProtoMsg(message: _178.ServiceOptionsProtoMsg): _178.ServiceOptions;
            toProto(message: _178.ServiceOptions): Uint8Array;
            toProtoMsg(message: _178.ServiceOptions): _178.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _178.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.MethodOptions;
            fromPartial(object: Partial<_178.MethodOptions>): _178.MethodOptions;
            fromAmino(object: _178.MethodOptionsAmino): _178.MethodOptions;
            toAmino(message: _178.MethodOptions): _178.MethodOptionsAmino;
            fromAminoMsg(object: _178.MethodOptionsAminoMsg): _178.MethodOptions;
            fromProtoMsg(message: _178.MethodOptionsProtoMsg): _178.MethodOptions;
            toProto(message: _178.MethodOptions): Uint8Array;
            toProtoMsg(message: _178.MethodOptions): _178.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _178.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.UninterpretedOption;
            fromPartial(object: Partial<_178.UninterpretedOption>): _178.UninterpretedOption;
            fromAmino(object: _178.UninterpretedOptionAmino): _178.UninterpretedOption;
            toAmino(message: _178.UninterpretedOption): _178.UninterpretedOptionAmino;
            fromAminoMsg(object: _178.UninterpretedOptionAminoMsg): _178.UninterpretedOption;
            fromProtoMsg(message: _178.UninterpretedOptionProtoMsg): _178.UninterpretedOption;
            toProto(message: _178.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _178.UninterpretedOption): _178.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _178.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_178.UninterpretedOption_NamePart>): _178.UninterpretedOption_NamePart;
            fromAmino(object: _178.UninterpretedOption_NamePartAmino): _178.UninterpretedOption_NamePart;
            toAmino(message: _178.UninterpretedOption_NamePart): _178.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _178.UninterpretedOption_NamePartAminoMsg): _178.UninterpretedOption_NamePart;
            fromProtoMsg(message: _178.UninterpretedOption_NamePartProtoMsg): _178.UninterpretedOption_NamePart;
            toProto(message: _178.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _178.UninterpretedOption_NamePart): _178.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _178.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.SourceCodeInfo;
            fromPartial(object: Partial<_178.SourceCodeInfo>): _178.SourceCodeInfo;
            fromAmino(object: _178.SourceCodeInfoAmino): _178.SourceCodeInfo;
            toAmino(message: _178.SourceCodeInfo): _178.SourceCodeInfoAmino;
            fromAminoMsg(object: _178.SourceCodeInfoAminoMsg): _178.SourceCodeInfo;
            fromProtoMsg(message: _178.SourceCodeInfoProtoMsg): _178.SourceCodeInfo;
            toProto(message: _178.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _178.SourceCodeInfo): _178.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _178.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.SourceCodeInfo_Location;
            fromPartial(object: Partial<_178.SourceCodeInfo_Location>): _178.SourceCodeInfo_Location;
            fromAmino(object: _178.SourceCodeInfo_LocationAmino): _178.SourceCodeInfo_Location;
            toAmino(message: _178.SourceCodeInfo_Location): _178.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _178.SourceCodeInfo_LocationAminoMsg): _178.SourceCodeInfo_Location;
            fromProtoMsg(message: _178.SourceCodeInfo_LocationProtoMsg): _178.SourceCodeInfo_Location;
            toProto(message: _178.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _178.SourceCodeInfo_Location): _178.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _178.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.GeneratedCodeInfo;
            fromPartial(object: Partial<_178.GeneratedCodeInfo>): _178.GeneratedCodeInfo;
            fromAmino(object: _178.GeneratedCodeInfoAmino): _178.GeneratedCodeInfo;
            toAmino(message: _178.GeneratedCodeInfo): _178.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _178.GeneratedCodeInfoAminoMsg): _178.GeneratedCodeInfo;
            fromProtoMsg(message: _178.GeneratedCodeInfoProtoMsg): _178.GeneratedCodeInfo;
            toProto(message: _178.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _178.GeneratedCodeInfo): _178.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _178.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_178.GeneratedCodeInfo_Annotation>): _178.GeneratedCodeInfo_Annotation;
            fromAmino(object: _178.GeneratedCodeInfo_AnnotationAmino): _178.GeneratedCodeInfo_Annotation;
            toAmino(message: _178.GeneratedCodeInfo_Annotation): _178.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _178.GeneratedCodeInfo_AnnotationAminoMsg): _178.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _178.GeneratedCodeInfo_AnnotationProtoMsg): _178.GeneratedCodeInfo_Annotation;
            toProto(message: _178.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _178.GeneratedCodeInfo_Annotation): _178.GeneratedCodeInfo_AnnotationProtoMsg;
        };
    };
}
