import * as _152 from "./abci/types";
import * as _153 from "./crypto/keys";
import * as _154 from "./crypto/proof";
import * as _155 from "./libs/bits/types";
import * as _156 from "./p2p/types";
import * as _157 from "./types/block";
import * as _158 from "./types/evidence";
import * as _159 from "./types/params";
import * as _160 from "./types/types";
import * as _161 from "./types/validator";
import * as _162 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _152.CheckTxType;
        checkTxTypeToJSON(object: _152.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _152.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _152.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _152.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _152.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _152.EvidenceType;
        evidenceTypeToJSON(object: _152.EvidenceType): string;
        CheckTxType: typeof _152.CheckTxType;
        CheckTxTypeSDKType: typeof _152.CheckTxType;
        CheckTxTypeAmino: typeof _152.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _152.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _152.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _152.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _152.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _152.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _152.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _152.EvidenceType;
        EvidenceTypeSDKType: typeof _152.EvidenceType;
        EvidenceTypeAmino: typeof _152.EvidenceType;
        Request: {
            typeUrl: string;
            encode(message: _152.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.Request;
            fromPartial(object: Partial<_152.Request>): _152.Request;
            fromAmino(object: _152.RequestAmino): _152.Request;
            toAmino(message: _152.Request): _152.RequestAmino;
            fromAminoMsg(object: _152.RequestAminoMsg): _152.Request;
            fromProtoMsg(message: _152.RequestProtoMsg): _152.Request;
            toProto(message: _152.Request): Uint8Array;
            toProtoMsg(message: _152.Request): _152.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _152.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.RequestEcho;
            fromPartial(object: Partial<_152.RequestEcho>): _152.RequestEcho;
            fromAmino(object: _152.RequestEchoAmino): _152.RequestEcho;
            toAmino(message: _152.RequestEcho): _152.RequestEchoAmino;
            fromAminoMsg(object: _152.RequestEchoAminoMsg): _152.RequestEcho;
            fromProtoMsg(message: _152.RequestEchoProtoMsg): _152.RequestEcho;
            toProto(message: _152.RequestEcho): Uint8Array;
            toProtoMsg(message: _152.RequestEcho): _152.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _152.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _152.RequestFlush;
            fromPartial(_: Partial<_152.RequestFlush>): _152.RequestFlush;
            fromAmino(_: _152.RequestFlushAmino): _152.RequestFlush;
            toAmino(_: _152.RequestFlush): _152.RequestFlushAmino;
            fromAminoMsg(object: _152.RequestFlushAminoMsg): _152.RequestFlush;
            fromProtoMsg(message: _152.RequestFlushProtoMsg): _152.RequestFlush;
            toProto(message: _152.RequestFlush): Uint8Array;
            toProtoMsg(message: _152.RequestFlush): _152.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _152.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.RequestInfo;
            fromPartial(object: Partial<_152.RequestInfo>): _152.RequestInfo;
            fromAmino(object: _152.RequestInfoAmino): _152.RequestInfo;
            toAmino(message: _152.RequestInfo): _152.RequestInfoAmino;
            fromAminoMsg(object: _152.RequestInfoAminoMsg): _152.RequestInfo;
            fromProtoMsg(message: _152.RequestInfoProtoMsg): _152.RequestInfo;
            toProto(message: _152.RequestInfo): Uint8Array;
            toProtoMsg(message: _152.RequestInfo): _152.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            typeUrl: string;
            encode(message: _152.RequestSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.RequestSetOption;
            fromPartial(object: Partial<_152.RequestSetOption>): _152.RequestSetOption;
            fromAmino(object: _152.RequestSetOptionAmino): _152.RequestSetOption;
            toAmino(message: _152.RequestSetOption): _152.RequestSetOptionAmino;
            fromAminoMsg(object: _152.RequestSetOptionAminoMsg): _152.RequestSetOption;
            fromProtoMsg(message: _152.RequestSetOptionProtoMsg): _152.RequestSetOption;
            toProto(message: _152.RequestSetOption): Uint8Array;
            toProtoMsg(message: _152.RequestSetOption): _152.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _152.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.RequestInitChain;
            fromPartial(object: Partial<_152.RequestInitChain>): _152.RequestInitChain;
            fromAmino(object: _152.RequestInitChainAmino): _152.RequestInitChain;
            toAmino(message: _152.RequestInitChain): _152.RequestInitChainAmino;
            fromAminoMsg(object: _152.RequestInitChainAminoMsg): _152.RequestInitChain;
            fromProtoMsg(message: _152.RequestInitChainProtoMsg): _152.RequestInitChain;
            toProto(message: _152.RequestInitChain): Uint8Array;
            toProtoMsg(message: _152.RequestInitChain): _152.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _152.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.RequestQuery;
            fromPartial(object: Partial<_152.RequestQuery>): _152.RequestQuery;
            fromAmino(object: _152.RequestQueryAmino): _152.RequestQuery;
            toAmino(message: _152.RequestQuery): _152.RequestQueryAmino;
            fromAminoMsg(object: _152.RequestQueryAminoMsg): _152.RequestQuery;
            fromProtoMsg(message: _152.RequestQueryProtoMsg): _152.RequestQuery;
            toProto(message: _152.RequestQuery): Uint8Array;
            toProtoMsg(message: _152.RequestQuery): _152.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _152.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.RequestBeginBlock;
            fromPartial(object: Partial<_152.RequestBeginBlock>): _152.RequestBeginBlock;
            fromAmino(object: _152.RequestBeginBlockAmino): _152.RequestBeginBlock;
            toAmino(message: _152.RequestBeginBlock): _152.RequestBeginBlockAmino;
            fromAminoMsg(object: _152.RequestBeginBlockAminoMsg): _152.RequestBeginBlock;
            fromProtoMsg(message: _152.RequestBeginBlockProtoMsg): _152.RequestBeginBlock;
            toProto(message: _152.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _152.RequestBeginBlock): _152.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _152.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.RequestCheckTx;
            fromPartial(object: Partial<_152.RequestCheckTx>): _152.RequestCheckTx;
            fromAmino(object: _152.RequestCheckTxAmino): _152.RequestCheckTx;
            toAmino(message: _152.RequestCheckTx): _152.RequestCheckTxAmino;
            fromAminoMsg(object: _152.RequestCheckTxAminoMsg): _152.RequestCheckTx;
            fromProtoMsg(message: _152.RequestCheckTxProtoMsg): _152.RequestCheckTx;
            toProto(message: _152.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _152.RequestCheckTx): _152.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _152.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.RequestDeliverTx;
            fromPartial(object: Partial<_152.RequestDeliverTx>): _152.RequestDeliverTx;
            fromAmino(object: _152.RequestDeliverTxAmino): _152.RequestDeliverTx;
            toAmino(message: _152.RequestDeliverTx): _152.RequestDeliverTxAmino;
            fromAminoMsg(object: _152.RequestDeliverTxAminoMsg): _152.RequestDeliverTx;
            fromProtoMsg(message: _152.RequestDeliverTxProtoMsg): _152.RequestDeliverTx;
            toProto(message: _152.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _152.RequestDeliverTx): _152.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _152.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.RequestEndBlock;
            fromPartial(object: Partial<_152.RequestEndBlock>): _152.RequestEndBlock;
            fromAmino(object: _152.RequestEndBlockAmino): _152.RequestEndBlock;
            toAmino(message: _152.RequestEndBlock): _152.RequestEndBlockAmino;
            fromAminoMsg(object: _152.RequestEndBlockAminoMsg): _152.RequestEndBlock;
            fromProtoMsg(message: _152.RequestEndBlockProtoMsg): _152.RequestEndBlock;
            toProto(message: _152.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _152.RequestEndBlock): _152.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _152.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _152.RequestCommit;
            fromPartial(_: Partial<_152.RequestCommit>): _152.RequestCommit;
            fromAmino(_: _152.RequestCommitAmino): _152.RequestCommit;
            toAmino(_: _152.RequestCommit): _152.RequestCommitAmino;
            fromAminoMsg(object: _152.RequestCommitAminoMsg): _152.RequestCommit;
            fromProtoMsg(message: _152.RequestCommitProtoMsg): _152.RequestCommit;
            toProto(message: _152.RequestCommit): Uint8Array;
            toProtoMsg(message: _152.RequestCommit): _152.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _152.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _152.RequestListSnapshots;
            fromPartial(_: Partial<_152.RequestListSnapshots>): _152.RequestListSnapshots;
            fromAmino(_: _152.RequestListSnapshotsAmino): _152.RequestListSnapshots;
            toAmino(_: _152.RequestListSnapshots): _152.RequestListSnapshotsAmino;
            fromAminoMsg(object: _152.RequestListSnapshotsAminoMsg): _152.RequestListSnapshots;
            fromProtoMsg(message: _152.RequestListSnapshotsProtoMsg): _152.RequestListSnapshots;
            toProto(message: _152.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _152.RequestListSnapshots): _152.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _152.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.RequestOfferSnapshot;
            fromPartial(object: Partial<_152.RequestOfferSnapshot>): _152.RequestOfferSnapshot;
            fromAmino(object: _152.RequestOfferSnapshotAmino): _152.RequestOfferSnapshot;
            toAmino(message: _152.RequestOfferSnapshot): _152.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _152.RequestOfferSnapshotAminoMsg): _152.RequestOfferSnapshot;
            fromProtoMsg(message: _152.RequestOfferSnapshotProtoMsg): _152.RequestOfferSnapshot;
            toProto(message: _152.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _152.RequestOfferSnapshot): _152.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _152.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_152.RequestLoadSnapshotChunk>): _152.RequestLoadSnapshotChunk;
            fromAmino(object: _152.RequestLoadSnapshotChunkAmino): _152.RequestLoadSnapshotChunk;
            toAmino(message: _152.RequestLoadSnapshotChunk): _152.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _152.RequestLoadSnapshotChunkAminoMsg): _152.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _152.RequestLoadSnapshotChunkProtoMsg): _152.RequestLoadSnapshotChunk;
            toProto(message: _152.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _152.RequestLoadSnapshotChunk): _152.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _152.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_152.RequestApplySnapshotChunk>): _152.RequestApplySnapshotChunk;
            fromAmino(object: _152.RequestApplySnapshotChunkAmino): _152.RequestApplySnapshotChunk;
            toAmino(message: _152.RequestApplySnapshotChunk): _152.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _152.RequestApplySnapshotChunkAminoMsg): _152.RequestApplySnapshotChunk;
            fromProtoMsg(message: _152.RequestApplySnapshotChunkProtoMsg): _152.RequestApplySnapshotChunk;
            toProto(message: _152.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _152.RequestApplySnapshotChunk): _152.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _152.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.Response;
            fromPartial(object: Partial<_152.Response>): _152.Response;
            fromAmino(object: _152.ResponseAmino): _152.Response;
            toAmino(message: _152.Response): _152.ResponseAmino;
            fromAminoMsg(object: _152.ResponseAminoMsg): _152.Response;
            fromProtoMsg(message: _152.ResponseProtoMsg): _152.Response;
            toProto(message: _152.Response): Uint8Array;
            toProtoMsg(message: _152.Response): _152.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _152.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseException;
            fromPartial(object: Partial<_152.ResponseException>): _152.ResponseException;
            fromAmino(object: _152.ResponseExceptionAmino): _152.ResponseException;
            toAmino(message: _152.ResponseException): _152.ResponseExceptionAmino;
            fromAminoMsg(object: _152.ResponseExceptionAminoMsg): _152.ResponseException;
            fromProtoMsg(message: _152.ResponseExceptionProtoMsg): _152.ResponseException;
            toProto(message: _152.ResponseException): Uint8Array;
            toProtoMsg(message: _152.ResponseException): _152.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _152.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseEcho;
            fromPartial(object: Partial<_152.ResponseEcho>): _152.ResponseEcho;
            fromAmino(object: _152.ResponseEchoAmino): _152.ResponseEcho;
            toAmino(message: _152.ResponseEcho): _152.ResponseEchoAmino;
            fromAminoMsg(object: _152.ResponseEchoAminoMsg): _152.ResponseEcho;
            fromProtoMsg(message: _152.ResponseEchoProtoMsg): _152.ResponseEcho;
            toProto(message: _152.ResponseEcho): Uint8Array;
            toProtoMsg(message: _152.ResponseEcho): _152.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _152.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _152.ResponseFlush;
            fromPartial(_: Partial<_152.ResponseFlush>): _152.ResponseFlush;
            fromAmino(_: _152.ResponseFlushAmino): _152.ResponseFlush;
            toAmino(_: _152.ResponseFlush): _152.ResponseFlushAmino;
            fromAminoMsg(object: _152.ResponseFlushAminoMsg): _152.ResponseFlush;
            fromProtoMsg(message: _152.ResponseFlushProtoMsg): _152.ResponseFlush;
            toProto(message: _152.ResponseFlush): Uint8Array;
            toProtoMsg(message: _152.ResponseFlush): _152.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _152.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseInfo;
            fromPartial(object: Partial<_152.ResponseInfo>): _152.ResponseInfo;
            fromAmino(object: _152.ResponseInfoAmino): _152.ResponseInfo;
            toAmino(message: _152.ResponseInfo): _152.ResponseInfoAmino;
            fromAminoMsg(object: _152.ResponseInfoAminoMsg): _152.ResponseInfo;
            fromProtoMsg(message: _152.ResponseInfoProtoMsg): _152.ResponseInfo;
            toProto(message: _152.ResponseInfo): Uint8Array;
            toProtoMsg(message: _152.ResponseInfo): _152.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            typeUrl: string;
            encode(message: _152.ResponseSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseSetOption;
            fromPartial(object: Partial<_152.ResponseSetOption>): _152.ResponseSetOption;
            fromAmino(object: _152.ResponseSetOptionAmino): _152.ResponseSetOption;
            toAmino(message: _152.ResponseSetOption): _152.ResponseSetOptionAmino;
            fromAminoMsg(object: _152.ResponseSetOptionAminoMsg): _152.ResponseSetOption;
            fromProtoMsg(message: _152.ResponseSetOptionProtoMsg): _152.ResponseSetOption;
            toProto(message: _152.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _152.ResponseSetOption): _152.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _152.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseInitChain;
            fromPartial(object: Partial<_152.ResponseInitChain>): _152.ResponseInitChain;
            fromAmino(object: _152.ResponseInitChainAmino): _152.ResponseInitChain;
            toAmino(message: _152.ResponseInitChain): _152.ResponseInitChainAmino;
            fromAminoMsg(object: _152.ResponseInitChainAminoMsg): _152.ResponseInitChain;
            fromProtoMsg(message: _152.ResponseInitChainProtoMsg): _152.ResponseInitChain;
            toProto(message: _152.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _152.ResponseInitChain): _152.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _152.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseQuery;
            fromPartial(object: Partial<_152.ResponseQuery>): _152.ResponseQuery;
            fromAmino(object: _152.ResponseQueryAmino): _152.ResponseQuery;
            toAmino(message: _152.ResponseQuery): _152.ResponseQueryAmino;
            fromAminoMsg(object: _152.ResponseQueryAminoMsg): _152.ResponseQuery;
            fromProtoMsg(message: _152.ResponseQueryProtoMsg): _152.ResponseQuery;
            toProto(message: _152.ResponseQuery): Uint8Array;
            toProtoMsg(message: _152.ResponseQuery): _152.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _152.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseBeginBlock;
            fromPartial(object: Partial<_152.ResponseBeginBlock>): _152.ResponseBeginBlock;
            fromAmino(object: _152.ResponseBeginBlockAmino): _152.ResponseBeginBlock;
            toAmino(message: _152.ResponseBeginBlock): _152.ResponseBeginBlockAmino;
            fromAminoMsg(object: _152.ResponseBeginBlockAminoMsg): _152.ResponseBeginBlock;
            fromProtoMsg(message: _152.ResponseBeginBlockProtoMsg): _152.ResponseBeginBlock;
            toProto(message: _152.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _152.ResponseBeginBlock): _152.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _152.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseCheckTx;
            fromPartial(object: Partial<_152.ResponseCheckTx>): _152.ResponseCheckTx;
            fromAmino(object: _152.ResponseCheckTxAmino): _152.ResponseCheckTx;
            toAmino(message: _152.ResponseCheckTx): _152.ResponseCheckTxAmino;
            fromAminoMsg(object: _152.ResponseCheckTxAminoMsg): _152.ResponseCheckTx;
            fromProtoMsg(message: _152.ResponseCheckTxProtoMsg): _152.ResponseCheckTx;
            toProto(message: _152.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _152.ResponseCheckTx): _152.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _152.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseDeliverTx;
            fromPartial(object: Partial<_152.ResponseDeliverTx>): _152.ResponseDeliverTx;
            fromAmino(object: _152.ResponseDeliverTxAmino): _152.ResponseDeliverTx;
            toAmino(message: _152.ResponseDeliverTx): _152.ResponseDeliverTxAmino;
            fromAminoMsg(object: _152.ResponseDeliverTxAminoMsg): _152.ResponseDeliverTx;
            fromProtoMsg(message: _152.ResponseDeliverTxProtoMsg): _152.ResponseDeliverTx;
            toProto(message: _152.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _152.ResponseDeliverTx): _152.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _152.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseEndBlock;
            fromPartial(object: Partial<_152.ResponseEndBlock>): _152.ResponseEndBlock;
            fromAmino(object: _152.ResponseEndBlockAmino): _152.ResponseEndBlock;
            toAmino(message: _152.ResponseEndBlock): _152.ResponseEndBlockAmino;
            fromAminoMsg(object: _152.ResponseEndBlockAminoMsg): _152.ResponseEndBlock;
            fromProtoMsg(message: _152.ResponseEndBlockProtoMsg): _152.ResponseEndBlock;
            toProto(message: _152.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _152.ResponseEndBlock): _152.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _152.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseCommit;
            fromPartial(object: Partial<_152.ResponseCommit>): _152.ResponseCommit;
            fromAmino(object: _152.ResponseCommitAmino): _152.ResponseCommit;
            toAmino(message: _152.ResponseCommit): _152.ResponseCommitAmino;
            fromAminoMsg(object: _152.ResponseCommitAminoMsg): _152.ResponseCommit;
            fromProtoMsg(message: _152.ResponseCommitProtoMsg): _152.ResponseCommit;
            toProto(message: _152.ResponseCommit): Uint8Array;
            toProtoMsg(message: _152.ResponseCommit): _152.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _152.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseListSnapshots;
            fromPartial(object: Partial<_152.ResponseListSnapshots>): _152.ResponseListSnapshots;
            fromAmino(object: _152.ResponseListSnapshotsAmino): _152.ResponseListSnapshots;
            toAmino(message: _152.ResponseListSnapshots): _152.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _152.ResponseListSnapshotsAminoMsg): _152.ResponseListSnapshots;
            fromProtoMsg(message: _152.ResponseListSnapshotsProtoMsg): _152.ResponseListSnapshots;
            toProto(message: _152.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _152.ResponseListSnapshots): _152.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _152.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseOfferSnapshot;
            fromPartial(object: Partial<_152.ResponseOfferSnapshot>): _152.ResponseOfferSnapshot;
            fromAmino(object: _152.ResponseOfferSnapshotAmino): _152.ResponseOfferSnapshot;
            toAmino(message: _152.ResponseOfferSnapshot): _152.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _152.ResponseOfferSnapshotAminoMsg): _152.ResponseOfferSnapshot;
            fromProtoMsg(message: _152.ResponseOfferSnapshotProtoMsg): _152.ResponseOfferSnapshot;
            toProto(message: _152.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _152.ResponseOfferSnapshot): _152.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _152.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_152.ResponseLoadSnapshotChunk>): _152.ResponseLoadSnapshotChunk;
            fromAmino(object: _152.ResponseLoadSnapshotChunkAmino): _152.ResponseLoadSnapshotChunk;
            toAmino(message: _152.ResponseLoadSnapshotChunk): _152.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _152.ResponseLoadSnapshotChunkAminoMsg): _152.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _152.ResponseLoadSnapshotChunkProtoMsg): _152.ResponseLoadSnapshotChunk;
            toProto(message: _152.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _152.ResponseLoadSnapshotChunk): _152.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _152.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_152.ResponseApplySnapshotChunk>): _152.ResponseApplySnapshotChunk;
            fromAmino(object: _152.ResponseApplySnapshotChunkAmino): _152.ResponseApplySnapshotChunk;
            toAmino(message: _152.ResponseApplySnapshotChunk): _152.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _152.ResponseApplySnapshotChunkAminoMsg): _152.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _152.ResponseApplySnapshotChunkProtoMsg): _152.ResponseApplySnapshotChunk;
            toProto(message: _152.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _152.ResponseApplySnapshotChunk): _152.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _152.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ConsensusParams;
            fromPartial(object: Partial<_152.ConsensusParams>): _152.ConsensusParams;
            fromAmino(object: _152.ConsensusParamsAmino): _152.ConsensusParams;
            toAmino(message: _152.ConsensusParams): _152.ConsensusParamsAmino;
            fromAminoMsg(object: _152.ConsensusParamsAminoMsg): _152.ConsensusParams;
            fromProtoMsg(message: _152.ConsensusParamsProtoMsg): _152.ConsensusParams;
            toProto(message: _152.ConsensusParams): Uint8Array;
            toProtoMsg(message: _152.ConsensusParams): _152.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _152.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.BlockParams;
            fromPartial(object: Partial<_152.BlockParams>): _152.BlockParams;
            fromAmino(object: _152.BlockParamsAmino): _152.BlockParams;
            toAmino(message: _152.BlockParams): _152.BlockParamsAmino;
            fromAminoMsg(object: _152.BlockParamsAminoMsg): _152.BlockParams;
            fromProtoMsg(message: _152.BlockParamsProtoMsg): _152.BlockParams;
            toProto(message: _152.BlockParams): Uint8Array;
            toProtoMsg(message: _152.BlockParams): _152.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            typeUrl: string;
            encode(message: _152.LastCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.LastCommitInfo;
            fromPartial(object: Partial<_152.LastCommitInfo>): _152.LastCommitInfo;
            fromAmino(object: _152.LastCommitInfoAmino): _152.LastCommitInfo;
            toAmino(message: _152.LastCommitInfo): _152.LastCommitInfoAmino;
            fromAminoMsg(object: _152.LastCommitInfoAminoMsg): _152.LastCommitInfo;
            fromProtoMsg(message: _152.LastCommitInfoProtoMsg): _152.LastCommitInfo;
            toProto(message: _152.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _152.LastCommitInfo): _152.LastCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _152.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.Event;
            fromPartial(object: Partial<_152.Event>): _152.Event;
            fromAmino(object: _152.EventAmino): _152.Event;
            toAmino(message: _152.Event): _152.EventAmino;
            fromAminoMsg(object: _152.EventAminoMsg): _152.Event;
            fromProtoMsg(message: _152.EventProtoMsg): _152.Event;
            toProto(message: _152.Event): Uint8Array;
            toProtoMsg(message: _152.Event): _152.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _152.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.EventAttribute;
            fromPartial(object: Partial<_152.EventAttribute>): _152.EventAttribute;
            fromAmino(object: _152.EventAttributeAmino): _152.EventAttribute;
            toAmino(message: _152.EventAttribute): _152.EventAttributeAmino;
            fromAminoMsg(object: _152.EventAttributeAminoMsg): _152.EventAttribute;
            fromProtoMsg(message: _152.EventAttributeProtoMsg): _152.EventAttribute;
            toProto(message: _152.EventAttribute): Uint8Array;
            toProtoMsg(message: _152.EventAttribute): _152.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _152.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.TxResult;
            fromPartial(object: Partial<_152.TxResult>): _152.TxResult;
            fromAmino(object: _152.TxResultAmino): _152.TxResult;
            toAmino(message: _152.TxResult): _152.TxResultAmino;
            fromAminoMsg(object: _152.TxResultAminoMsg): _152.TxResult;
            fromProtoMsg(message: _152.TxResultProtoMsg): _152.TxResult;
            toProto(message: _152.TxResult): Uint8Array;
            toProtoMsg(message: _152.TxResult): _152.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _152.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.Validator;
            fromPartial(object: Partial<_152.Validator>): _152.Validator;
            fromAmino(object: _152.ValidatorAmino): _152.Validator;
            toAmino(message: _152.Validator): _152.ValidatorAmino;
            fromAminoMsg(object: _152.ValidatorAminoMsg): _152.Validator;
            fromProtoMsg(message: _152.ValidatorProtoMsg): _152.Validator;
            toProto(message: _152.Validator): Uint8Array;
            toProtoMsg(message: _152.Validator): _152.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _152.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.ValidatorUpdate;
            fromPartial(object: Partial<_152.ValidatorUpdate>): _152.ValidatorUpdate;
            fromAmino(object: _152.ValidatorUpdateAmino): _152.ValidatorUpdate;
            toAmino(message: _152.ValidatorUpdate): _152.ValidatorUpdateAmino;
            fromAminoMsg(object: _152.ValidatorUpdateAminoMsg): _152.ValidatorUpdate;
            fromProtoMsg(message: _152.ValidatorUpdateProtoMsg): _152.ValidatorUpdate;
            toProto(message: _152.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _152.ValidatorUpdate): _152.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _152.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.VoteInfo;
            fromPartial(object: Partial<_152.VoteInfo>): _152.VoteInfo;
            fromAmino(object: _152.VoteInfoAmino): _152.VoteInfo;
            toAmino(message: _152.VoteInfo): _152.VoteInfoAmino;
            fromAminoMsg(object: _152.VoteInfoAminoMsg): _152.VoteInfo;
            fromProtoMsg(message: _152.VoteInfoProtoMsg): _152.VoteInfo;
            toProto(message: _152.VoteInfo): Uint8Array;
            toProtoMsg(message: _152.VoteInfo): _152.VoteInfoProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _152.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.Evidence;
            fromPartial(object: Partial<_152.Evidence>): _152.Evidence;
            fromAmino(object: _152.EvidenceAmino): _152.Evidence;
            toAmino(message: _152.Evidence): _152.EvidenceAmino;
            fromAminoMsg(object: _152.EvidenceAminoMsg): _152.Evidence;
            fromProtoMsg(message: _152.EvidenceProtoMsg): _152.Evidence;
            toProto(message: _152.Evidence): Uint8Array;
            toProtoMsg(message: _152.Evidence): _152.EvidenceProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _152.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _152.Snapshot;
            fromPartial(object: Partial<_152.Snapshot>): _152.Snapshot;
            fromAmino(object: _152.SnapshotAmino): _152.Snapshot;
            toAmino(message: _152.Snapshot): _152.SnapshotAmino;
            fromAminoMsg(object: _152.SnapshotAminoMsg): _152.Snapshot;
            fromProtoMsg(message: _152.SnapshotProtoMsg): _152.Snapshot;
            toProto(message: _152.Snapshot): Uint8Array;
            toProtoMsg(message: _152.Snapshot): _152.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _154.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _154.Proof;
            fromPartial(object: Partial<_154.Proof>): _154.Proof;
            fromAmino(object: _154.ProofAmino): _154.Proof;
            toAmino(message: _154.Proof): _154.ProofAmino;
            fromAminoMsg(object: _154.ProofAminoMsg): _154.Proof;
            fromProtoMsg(message: _154.ProofProtoMsg): _154.Proof;
            toProto(message: _154.Proof): Uint8Array;
            toProtoMsg(message: _154.Proof): _154.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _154.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _154.ValueOp;
            fromPartial(object: Partial<_154.ValueOp>): _154.ValueOp;
            fromAmino(object: _154.ValueOpAmino): _154.ValueOp;
            toAmino(message: _154.ValueOp): _154.ValueOpAmino;
            fromAminoMsg(object: _154.ValueOpAminoMsg): _154.ValueOp;
            fromProtoMsg(message: _154.ValueOpProtoMsg): _154.ValueOp;
            toProto(message: _154.ValueOp): Uint8Array;
            toProtoMsg(message: _154.ValueOp): _154.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _154.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _154.DominoOp;
            fromPartial(object: Partial<_154.DominoOp>): _154.DominoOp;
            fromAmino(object: _154.DominoOpAmino): _154.DominoOp;
            toAmino(message: _154.DominoOp): _154.DominoOpAmino;
            fromAminoMsg(object: _154.DominoOpAminoMsg): _154.DominoOp;
            fromProtoMsg(message: _154.DominoOpProtoMsg): _154.DominoOp;
            toProto(message: _154.DominoOp): Uint8Array;
            toProtoMsg(message: _154.DominoOp): _154.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _154.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _154.ProofOp;
            fromPartial(object: Partial<_154.ProofOp>): _154.ProofOp;
            fromAmino(object: _154.ProofOpAmino): _154.ProofOp;
            toAmino(message: _154.ProofOp): _154.ProofOpAmino;
            fromAminoMsg(object: _154.ProofOpAminoMsg): _154.ProofOp;
            fromProtoMsg(message: _154.ProofOpProtoMsg): _154.ProofOp;
            toProto(message: _154.ProofOp): Uint8Array;
            toProtoMsg(message: _154.ProofOp): _154.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _154.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _154.ProofOps;
            fromPartial(object: Partial<_154.ProofOps>): _154.ProofOps;
            fromAmino(object: _154.ProofOpsAmino): _154.ProofOps;
            toAmino(message: _154.ProofOps): _154.ProofOpsAmino;
            fromAminoMsg(object: _154.ProofOpsAminoMsg): _154.ProofOps;
            fromProtoMsg(message: _154.ProofOpsProtoMsg): _154.ProofOps;
            toProto(message: _154.ProofOps): Uint8Array;
            toProtoMsg(message: _154.ProofOps): _154.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _153.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _153.PublicKey;
            fromPartial(object: Partial<_153.PublicKey>): _153.PublicKey;
            fromAmino(object: _153.PublicKeyAmino): _153.PublicKey;
            toAmino(message: _153.PublicKey): _153.PublicKeyAmino;
            fromAminoMsg(object: _153.PublicKeyAminoMsg): _153.PublicKey;
            fromProtoMsg(message: _153.PublicKeyProtoMsg): _153.PublicKey;
            toProto(message: _153.PublicKey): Uint8Array;
            toProtoMsg(message: _153.PublicKey): _153.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _155.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                fromJSON(object: any): _155.BitArray;
                fromPartial(object: Partial<_155.BitArray>): _155.BitArray;
                fromAmino(object: _155.BitArrayAmino): _155.BitArray;
                toAmino(message: _155.BitArray): _155.BitArrayAmino;
                fromAminoMsg(object: _155.BitArrayAminoMsg): _155.BitArray;
                fromProtoMsg(message: _155.BitArrayProtoMsg): _155.BitArray;
                toProto(message: _155.BitArray): Uint8Array;
                toProtoMsg(message: _155.BitArray): _155.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _156.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.NetAddress;
            fromPartial(object: Partial<_156.NetAddress>): _156.NetAddress;
            fromAmino(object: _156.NetAddressAmino): _156.NetAddress;
            toAmino(message: _156.NetAddress): _156.NetAddressAmino;
            fromAminoMsg(object: _156.NetAddressAminoMsg): _156.NetAddress;
            fromProtoMsg(message: _156.NetAddressProtoMsg): _156.NetAddress;
            toProto(message: _156.NetAddress): Uint8Array;
            toProtoMsg(message: _156.NetAddress): _156.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _156.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.ProtocolVersion;
            fromPartial(object: Partial<_156.ProtocolVersion>): _156.ProtocolVersion;
            fromAmino(object: _156.ProtocolVersionAmino): _156.ProtocolVersion;
            toAmino(message: _156.ProtocolVersion): _156.ProtocolVersionAmino;
            fromAminoMsg(object: _156.ProtocolVersionAminoMsg): _156.ProtocolVersion;
            fromProtoMsg(message: _156.ProtocolVersionProtoMsg): _156.ProtocolVersion;
            toProto(message: _156.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _156.ProtocolVersion): _156.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _156.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.DefaultNodeInfo;
            fromPartial(object: Partial<_156.DefaultNodeInfo>): _156.DefaultNodeInfo;
            fromAmino(object: _156.DefaultNodeInfoAmino): _156.DefaultNodeInfo;
            toAmino(message: _156.DefaultNodeInfo): _156.DefaultNodeInfoAmino;
            fromAminoMsg(object: _156.DefaultNodeInfoAminoMsg): _156.DefaultNodeInfo;
            fromProtoMsg(message: _156.DefaultNodeInfoProtoMsg): _156.DefaultNodeInfo;
            toProto(message: _156.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _156.DefaultNodeInfo): _156.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _156.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _156.DefaultNodeInfoOther;
            fromPartial(object: Partial<_156.DefaultNodeInfoOther>): _156.DefaultNodeInfoOther;
            fromAmino(object: _156.DefaultNodeInfoOtherAmino): _156.DefaultNodeInfoOther;
            toAmino(message: _156.DefaultNodeInfoOther): _156.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _156.DefaultNodeInfoOtherAminoMsg): _156.DefaultNodeInfoOther;
            fromProtoMsg(message: _156.DefaultNodeInfoOtherProtoMsg): _156.DefaultNodeInfoOther;
            toProto(message: _156.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _156.DefaultNodeInfoOther): _156.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _161.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.ValidatorSet;
            fromPartial(object: Partial<_161.ValidatorSet>): _161.ValidatorSet;
            fromAmino(object: _161.ValidatorSetAmino): _161.ValidatorSet;
            toAmino(message: _161.ValidatorSet): _161.ValidatorSetAmino;
            fromAminoMsg(object: _161.ValidatorSetAminoMsg): _161.ValidatorSet;
            fromProtoMsg(message: _161.ValidatorSetProtoMsg): _161.ValidatorSet;
            toProto(message: _161.ValidatorSet): Uint8Array;
            toProtoMsg(message: _161.ValidatorSet): _161.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _161.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.Validator;
            fromPartial(object: Partial<_161.Validator>): _161.Validator;
            fromAmino(object: _161.ValidatorAmino): _161.Validator;
            toAmino(message: _161.Validator): _161.ValidatorAmino;
            fromAminoMsg(object: _161.ValidatorAminoMsg): _161.Validator;
            fromProtoMsg(message: _161.ValidatorProtoMsg): _161.Validator;
            toProto(message: _161.Validator): Uint8Array;
            toProtoMsg(message: _161.Validator): _161.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _161.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.SimpleValidator;
            fromPartial(object: Partial<_161.SimpleValidator>): _161.SimpleValidator;
            fromAmino(object: _161.SimpleValidatorAmino): _161.SimpleValidator;
            toAmino(message: _161.SimpleValidator): _161.SimpleValidatorAmino;
            fromAminoMsg(object: _161.SimpleValidatorAminoMsg): _161.SimpleValidator;
            fromProtoMsg(message: _161.SimpleValidatorProtoMsg): _161.SimpleValidator;
            toProto(message: _161.SimpleValidator): Uint8Array;
            toProtoMsg(message: _161.SimpleValidator): _161.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _160.BlockIDFlag;
        blockIDFlagToJSON(object: _160.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _160.SignedMsgType;
        signedMsgTypeToJSON(object: _160.SignedMsgType): string;
        BlockIDFlag: typeof _160.BlockIDFlag;
        BlockIDFlagSDKType: typeof _160.BlockIDFlag;
        BlockIDFlagAmino: typeof _160.BlockIDFlag;
        SignedMsgType: typeof _160.SignedMsgType;
        SignedMsgTypeSDKType: typeof _160.SignedMsgType;
        SignedMsgTypeAmino: typeof _160.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _160.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.PartSetHeader;
            fromPartial(object: Partial<_160.PartSetHeader>): _160.PartSetHeader;
            fromAmino(object: _160.PartSetHeaderAmino): _160.PartSetHeader;
            toAmino(message: _160.PartSetHeader): _160.PartSetHeaderAmino;
            fromAminoMsg(object: _160.PartSetHeaderAminoMsg): _160.PartSetHeader;
            fromProtoMsg(message: _160.PartSetHeaderProtoMsg): _160.PartSetHeader;
            toProto(message: _160.PartSetHeader): Uint8Array;
            toProtoMsg(message: _160.PartSetHeader): _160.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _160.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.Part;
            fromPartial(object: Partial<_160.Part>): _160.Part;
            fromAmino(object: _160.PartAmino): _160.Part;
            toAmino(message: _160.Part): _160.PartAmino;
            fromAminoMsg(object: _160.PartAminoMsg): _160.Part;
            fromProtoMsg(message: _160.PartProtoMsg): _160.Part;
            toProto(message: _160.Part): Uint8Array;
            toProtoMsg(message: _160.Part): _160.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _160.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.BlockID;
            fromPartial(object: Partial<_160.BlockID>): _160.BlockID;
            fromAmino(object: _160.BlockIDAmino): _160.BlockID;
            toAmino(message: _160.BlockID): _160.BlockIDAmino;
            fromAminoMsg(object: _160.BlockIDAminoMsg): _160.BlockID;
            fromProtoMsg(message: _160.BlockIDProtoMsg): _160.BlockID;
            toProto(message: _160.BlockID): Uint8Array;
            toProtoMsg(message: _160.BlockID): _160.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _160.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.Header;
            fromPartial(object: Partial<_160.Header>): _160.Header;
            fromAmino(object: _160.HeaderAmino): _160.Header;
            toAmino(message: _160.Header): _160.HeaderAmino;
            fromAminoMsg(object: _160.HeaderAminoMsg): _160.Header;
            fromProtoMsg(message: _160.HeaderProtoMsg): _160.Header;
            toProto(message: _160.Header): Uint8Array;
            toProtoMsg(message: _160.Header): _160.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _160.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.Data;
            fromPartial(object: Partial<_160.Data>): _160.Data;
            fromAmino(object: _160.DataAmino): _160.Data;
            toAmino(message: _160.Data): _160.DataAmino;
            fromAminoMsg(object: _160.DataAminoMsg): _160.Data;
            fromProtoMsg(message: _160.DataProtoMsg): _160.Data;
            toProto(message: _160.Data): Uint8Array;
            toProtoMsg(message: _160.Data): _160.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _160.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.Vote;
            fromPartial(object: Partial<_160.Vote>): _160.Vote;
            fromAmino(object: _160.VoteAmino): _160.Vote;
            toAmino(message: _160.Vote): _160.VoteAmino;
            fromAminoMsg(object: _160.VoteAminoMsg): _160.Vote;
            fromProtoMsg(message: _160.VoteProtoMsg): _160.Vote;
            toProto(message: _160.Vote): Uint8Array;
            toProtoMsg(message: _160.Vote): _160.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _160.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.Commit;
            fromPartial(object: Partial<_160.Commit>): _160.Commit;
            fromAmino(object: _160.CommitAmino): _160.Commit;
            toAmino(message: _160.Commit): _160.CommitAmino;
            fromAminoMsg(object: _160.CommitAminoMsg): _160.Commit;
            fromProtoMsg(message: _160.CommitProtoMsg): _160.Commit;
            toProto(message: _160.Commit): Uint8Array;
            toProtoMsg(message: _160.Commit): _160.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _160.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.CommitSig;
            fromPartial(object: Partial<_160.CommitSig>): _160.CommitSig;
            fromAmino(object: _160.CommitSigAmino): _160.CommitSig;
            toAmino(message: _160.CommitSig): _160.CommitSigAmino;
            fromAminoMsg(object: _160.CommitSigAminoMsg): _160.CommitSig;
            fromProtoMsg(message: _160.CommitSigProtoMsg): _160.CommitSig;
            toProto(message: _160.CommitSig): Uint8Array;
            toProtoMsg(message: _160.CommitSig): _160.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _160.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.Proposal;
            fromPartial(object: Partial<_160.Proposal>): _160.Proposal;
            fromAmino(object: _160.ProposalAmino): _160.Proposal;
            toAmino(message: _160.Proposal): _160.ProposalAmino;
            fromAminoMsg(object: _160.ProposalAminoMsg): _160.Proposal;
            fromProtoMsg(message: _160.ProposalProtoMsg): _160.Proposal;
            toProto(message: _160.Proposal): Uint8Array;
            toProtoMsg(message: _160.Proposal): _160.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _160.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.SignedHeader;
            fromPartial(object: Partial<_160.SignedHeader>): _160.SignedHeader;
            fromAmino(object: _160.SignedHeaderAmino): _160.SignedHeader;
            toAmino(message: _160.SignedHeader): _160.SignedHeaderAmino;
            fromAminoMsg(object: _160.SignedHeaderAminoMsg): _160.SignedHeader;
            fromProtoMsg(message: _160.SignedHeaderProtoMsg): _160.SignedHeader;
            toProto(message: _160.SignedHeader): Uint8Array;
            toProtoMsg(message: _160.SignedHeader): _160.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _160.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.LightBlock;
            fromPartial(object: Partial<_160.LightBlock>): _160.LightBlock;
            fromAmino(object: _160.LightBlockAmino): _160.LightBlock;
            toAmino(message: _160.LightBlock): _160.LightBlockAmino;
            fromAminoMsg(object: _160.LightBlockAminoMsg): _160.LightBlock;
            fromProtoMsg(message: _160.LightBlockProtoMsg): _160.LightBlock;
            toProto(message: _160.LightBlock): Uint8Array;
            toProtoMsg(message: _160.LightBlock): _160.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _160.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.BlockMeta;
            fromPartial(object: Partial<_160.BlockMeta>): _160.BlockMeta;
            fromAmino(object: _160.BlockMetaAmino): _160.BlockMeta;
            toAmino(message: _160.BlockMeta): _160.BlockMetaAmino;
            fromAminoMsg(object: _160.BlockMetaAminoMsg): _160.BlockMeta;
            fromProtoMsg(message: _160.BlockMetaProtoMsg): _160.BlockMeta;
            toProto(message: _160.BlockMeta): Uint8Array;
            toProtoMsg(message: _160.BlockMeta): _160.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _160.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.TxProof;
            fromPartial(object: Partial<_160.TxProof>): _160.TxProof;
            fromAmino(object: _160.TxProofAmino): _160.TxProof;
            toAmino(message: _160.TxProof): _160.TxProofAmino;
            fromAminoMsg(object: _160.TxProofAminoMsg): _160.TxProof;
            fromProtoMsg(message: _160.TxProofProtoMsg): _160.TxProof;
            toProto(message: _160.TxProof): Uint8Array;
            toProtoMsg(message: _160.TxProof): _160.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _159.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _159.ConsensusParams;
            fromPartial(object: Partial<_159.ConsensusParams>): _159.ConsensusParams;
            fromAmino(object: _159.ConsensusParamsAmino): _159.ConsensusParams;
            toAmino(message: _159.ConsensusParams): _159.ConsensusParamsAmino;
            fromAminoMsg(object: _159.ConsensusParamsAminoMsg): _159.ConsensusParams;
            fromProtoMsg(message: _159.ConsensusParamsProtoMsg): _159.ConsensusParams;
            toProto(message: _159.ConsensusParams): Uint8Array;
            toProtoMsg(message: _159.ConsensusParams): _159.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _159.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _159.BlockParams;
            fromPartial(object: Partial<_159.BlockParams>): _159.BlockParams;
            fromAmino(object: _159.BlockParamsAmino): _159.BlockParams;
            toAmino(message: _159.BlockParams): _159.BlockParamsAmino;
            fromAminoMsg(object: _159.BlockParamsAminoMsg): _159.BlockParams;
            fromProtoMsg(message: _159.BlockParamsProtoMsg): _159.BlockParams;
            toProto(message: _159.BlockParams): Uint8Array;
            toProtoMsg(message: _159.BlockParams): _159.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _159.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _159.EvidenceParams;
            fromPartial(object: Partial<_159.EvidenceParams>): _159.EvidenceParams;
            fromAmino(object: _159.EvidenceParamsAmino): _159.EvidenceParams;
            toAmino(message: _159.EvidenceParams): _159.EvidenceParamsAmino;
            fromAminoMsg(object: _159.EvidenceParamsAminoMsg): _159.EvidenceParams;
            fromProtoMsg(message: _159.EvidenceParamsProtoMsg): _159.EvidenceParams;
            toProto(message: _159.EvidenceParams): Uint8Array;
            toProtoMsg(message: _159.EvidenceParams): _159.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _159.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _159.ValidatorParams;
            fromPartial(object: Partial<_159.ValidatorParams>): _159.ValidatorParams;
            fromAmino(object: _159.ValidatorParamsAmino): _159.ValidatorParams;
            toAmino(message: _159.ValidatorParams): _159.ValidatorParamsAmino;
            fromAminoMsg(object: _159.ValidatorParamsAminoMsg): _159.ValidatorParams;
            fromProtoMsg(message: _159.ValidatorParamsProtoMsg): _159.ValidatorParams;
            toProto(message: _159.ValidatorParams): Uint8Array;
            toProtoMsg(message: _159.ValidatorParams): _159.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _159.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _159.VersionParams;
            fromPartial(object: Partial<_159.VersionParams>): _159.VersionParams;
            fromAmino(object: _159.VersionParamsAmino): _159.VersionParams;
            toAmino(message: _159.VersionParams): _159.VersionParamsAmino;
            fromAminoMsg(object: _159.VersionParamsAminoMsg): _159.VersionParams;
            fromProtoMsg(message: _159.VersionParamsProtoMsg): _159.VersionParams;
            toProto(message: _159.VersionParams): Uint8Array;
            toProtoMsg(message: _159.VersionParams): _159.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _159.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _159.HashedParams;
            fromPartial(object: Partial<_159.HashedParams>): _159.HashedParams;
            fromAmino(object: _159.HashedParamsAmino): _159.HashedParams;
            toAmino(message: _159.HashedParams): _159.HashedParamsAmino;
            fromAminoMsg(object: _159.HashedParamsAminoMsg): _159.HashedParams;
            fromProtoMsg(message: _159.HashedParamsProtoMsg): _159.HashedParams;
            toProto(message: _159.HashedParams): Uint8Array;
            toProtoMsg(message: _159.HashedParams): _159.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _158.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _158.Evidence;
            fromPartial(object: Partial<_158.Evidence>): _158.Evidence;
            fromAmino(object: _158.EvidenceAmino): _158.Evidence;
            toAmino(message: _158.Evidence): _158.EvidenceAmino;
            fromAminoMsg(object: _158.EvidenceAminoMsg): _158.Evidence;
            fromProtoMsg(message: _158.EvidenceProtoMsg): _158.Evidence;
            toProto(message: _158.Evidence): Uint8Array;
            toProtoMsg(message: _158.Evidence): _158.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _158.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _158.DuplicateVoteEvidence;
            fromPartial(object: Partial<_158.DuplicateVoteEvidence>): _158.DuplicateVoteEvidence;
            fromAmino(object: _158.DuplicateVoteEvidenceAmino): _158.DuplicateVoteEvidence;
            toAmino(message: _158.DuplicateVoteEvidence): _158.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _158.DuplicateVoteEvidenceAminoMsg): _158.DuplicateVoteEvidence;
            fromProtoMsg(message: _158.DuplicateVoteEvidenceProtoMsg): _158.DuplicateVoteEvidence;
            toProto(message: _158.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _158.DuplicateVoteEvidence): _158.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _158.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _158.LightClientAttackEvidence;
            fromPartial(object: Partial<_158.LightClientAttackEvidence>): _158.LightClientAttackEvidence;
            fromAmino(object: _158.LightClientAttackEvidenceAmino): _158.LightClientAttackEvidence;
            toAmino(message: _158.LightClientAttackEvidence): _158.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _158.LightClientAttackEvidenceAminoMsg): _158.LightClientAttackEvidence;
            fromProtoMsg(message: _158.LightClientAttackEvidenceProtoMsg): _158.LightClientAttackEvidence;
            toProto(message: _158.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _158.LightClientAttackEvidence): _158.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _158.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _158.EvidenceList;
            fromPartial(object: Partial<_158.EvidenceList>): _158.EvidenceList;
            fromAmino(object: _158.EvidenceListAmino): _158.EvidenceList;
            toAmino(message: _158.EvidenceList): _158.EvidenceListAmino;
            fromAminoMsg(object: _158.EvidenceListAminoMsg): _158.EvidenceList;
            fromProtoMsg(message: _158.EvidenceListProtoMsg): _158.EvidenceList;
            toProto(message: _158.EvidenceList): Uint8Array;
            toProtoMsg(message: _158.EvidenceList): _158.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _157.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _157.Block;
            fromPartial(object: Partial<_157.Block>): _157.Block;
            fromAmino(object: _157.BlockAmino): _157.Block;
            toAmino(message: _157.Block): _157.BlockAmino;
            fromAminoMsg(object: _157.BlockAminoMsg): _157.Block;
            fromProtoMsg(message: _157.BlockProtoMsg): _157.Block;
            toProto(message: _157.Block): Uint8Array;
            toProtoMsg(message: _157.Block): _157.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _162.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _162.App;
            fromPartial(object: Partial<_162.App>): _162.App;
            fromAmino(object: _162.AppAmino): _162.App;
            toAmino(message: _162.App): _162.AppAmino;
            fromAminoMsg(object: _162.AppAminoMsg): _162.App;
            fromProtoMsg(message: _162.AppProtoMsg): _162.App;
            toProto(message: _162.App): Uint8Array;
            toProtoMsg(message: _162.App): _162.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _162.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _162.Consensus;
            fromPartial(object: Partial<_162.Consensus>): _162.Consensus;
            fromAmino(object: _162.ConsensusAmino): _162.Consensus;
            toAmino(message: _162.Consensus): _162.ConsensusAmino;
            fromAminoMsg(object: _162.ConsensusAminoMsg): _162.Consensus;
            fromProtoMsg(message: _162.ConsensusProtoMsg): _162.Consensus;
            toProto(message: _162.Consensus): Uint8Array;
            toProtoMsg(message: _162.Consensus): _162.ConsensusProtoMsg;
        };
    };
}
