import * as _169 from "../proofs";
export declare const ics23: {
    hashOpFromJSON(object: any): _169.HashOp;
    hashOpToJSON(object: _169.HashOp): string;
    lengthOpFromJSON(object: any): _169.LengthOp;
    lengthOpToJSON(object: _169.LengthOp): string;
    HashOp: typeof _169.HashOp;
    HashOpSDKType: typeof _169.HashOp;
    HashOpAmino: typeof _169.HashOp;
    LengthOp: typeof _169.LengthOp;
    LengthOpSDKType: typeof _169.LengthOp;
    LengthOpAmino: typeof _169.LengthOp;
    ExistenceProof: {
        typeUrl: string;
        encode(message: _169.ExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.ExistenceProof;
        fromPartial(object: Partial<_169.ExistenceProof>): _169.ExistenceProof;
        fromAmino(object: _169.ExistenceProofAmino): _169.ExistenceProof;
        toAmino(message: _169.ExistenceProof): _169.ExistenceProofAmino;
        fromAminoMsg(object: _169.ExistenceProofAminoMsg): _169.ExistenceProof;
        fromProtoMsg(message: _169.ExistenceProofProtoMsg): _169.ExistenceProof;
        toProto(message: _169.ExistenceProof): Uint8Array;
        toProtoMsg(message: _169.ExistenceProof): _169.ExistenceProofProtoMsg;
    };
    NonExistenceProof: {
        typeUrl: string;
        encode(message: _169.NonExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.NonExistenceProof;
        fromPartial(object: Partial<_169.NonExistenceProof>): _169.NonExistenceProof;
        fromAmino(object: _169.NonExistenceProofAmino): _169.NonExistenceProof;
        toAmino(message: _169.NonExistenceProof): _169.NonExistenceProofAmino;
        fromAminoMsg(object: _169.NonExistenceProofAminoMsg): _169.NonExistenceProof;
        fromProtoMsg(message: _169.NonExistenceProofProtoMsg): _169.NonExistenceProof;
        toProto(message: _169.NonExistenceProof): Uint8Array;
        toProtoMsg(message: _169.NonExistenceProof): _169.NonExistenceProofProtoMsg;
    };
    CommitmentProof: {
        typeUrl: string;
        encode(message: _169.CommitmentProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.CommitmentProof;
        fromPartial(object: Partial<_169.CommitmentProof>): _169.CommitmentProof;
        fromAmino(object: _169.CommitmentProofAmino): _169.CommitmentProof;
        toAmino(message: _169.CommitmentProof): _169.CommitmentProofAmino;
        fromAminoMsg(object: _169.CommitmentProofAminoMsg): _169.CommitmentProof;
        fromProtoMsg(message: _169.CommitmentProofProtoMsg): _169.CommitmentProof;
        toProto(message: _169.CommitmentProof): Uint8Array;
        toProtoMsg(message: _169.CommitmentProof): _169.CommitmentProofProtoMsg;
    };
    LeafOp: {
        typeUrl: string;
        encode(message: _169.LeafOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.LeafOp;
        fromPartial(object: Partial<_169.LeafOp>): _169.LeafOp;
        fromAmino(object: _169.LeafOpAmino): _169.LeafOp;
        toAmino(message: _169.LeafOp): _169.LeafOpAmino;
        fromAminoMsg(object: _169.LeafOpAminoMsg): _169.LeafOp;
        fromProtoMsg(message: _169.LeafOpProtoMsg): _169.LeafOp;
        toProto(message: _169.LeafOp): Uint8Array;
        toProtoMsg(message: _169.LeafOp): _169.LeafOpProtoMsg;
    };
    InnerOp: {
        typeUrl: string;
        encode(message: _169.InnerOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.InnerOp;
        fromPartial(object: Partial<_169.InnerOp>): _169.InnerOp;
        fromAmino(object: _169.InnerOpAmino): _169.InnerOp;
        toAmino(message: _169.InnerOp): _169.InnerOpAmino;
        fromAminoMsg(object: _169.InnerOpAminoMsg): _169.InnerOp;
        fromProtoMsg(message: _169.InnerOpProtoMsg): _169.InnerOp;
        toProto(message: _169.InnerOp): Uint8Array;
        toProtoMsg(message: _169.InnerOp): _169.InnerOpProtoMsg;
    };
    ProofSpec: {
        typeUrl: string;
        encode(message: _169.ProofSpec, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.ProofSpec;
        fromPartial(object: Partial<_169.ProofSpec>): _169.ProofSpec;
        fromAmino(object: _169.ProofSpecAmino): _169.ProofSpec;
        toAmino(message: _169.ProofSpec): _169.ProofSpecAmino;
        fromAminoMsg(object: _169.ProofSpecAminoMsg): _169.ProofSpec;
        fromProtoMsg(message: _169.ProofSpecProtoMsg): _169.ProofSpec;
        toProto(message: _169.ProofSpec): Uint8Array;
        toProtoMsg(message: _169.ProofSpec): _169.ProofSpecProtoMsg;
    };
    InnerSpec: {
        typeUrl: string;
        encode(message: _169.InnerSpec, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.InnerSpec;
        fromPartial(object: Partial<_169.InnerSpec>): _169.InnerSpec;
        fromAmino(object: _169.InnerSpecAmino): _169.InnerSpec;
        toAmino(message: _169.InnerSpec): _169.InnerSpecAmino;
        fromAminoMsg(object: _169.InnerSpecAminoMsg): _169.InnerSpec;
        fromProtoMsg(message: _169.InnerSpecProtoMsg): _169.InnerSpec;
        toProto(message: _169.InnerSpec): Uint8Array;
        toProtoMsg(message: _169.InnerSpec): _169.InnerSpecProtoMsg;
    };
    BatchProof: {
        typeUrl: string;
        encode(message: _169.BatchProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.BatchProof;
        fromPartial(object: Partial<_169.BatchProof>): _169.BatchProof;
        fromAmino(object: _169.BatchProofAmino): _169.BatchProof;
        toAmino(message: _169.BatchProof): _169.BatchProofAmino;
        fromAminoMsg(object: _169.BatchProofAminoMsg): _169.BatchProof;
        fromProtoMsg(message: _169.BatchProofProtoMsg): _169.BatchProof;
        toProto(message: _169.BatchProof): Uint8Array;
        toProtoMsg(message: _169.BatchProof): _169.BatchProofProtoMsg;
    };
    BatchEntry: {
        typeUrl: string;
        encode(message: _169.BatchEntry, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.BatchEntry;
        fromPartial(object: Partial<_169.BatchEntry>): _169.BatchEntry;
        fromAmino(object: _169.BatchEntryAmino): _169.BatchEntry;
        toAmino(message: _169.BatchEntry): _169.BatchEntryAmino;
        fromAminoMsg(object: _169.BatchEntryAminoMsg): _169.BatchEntry;
        fromProtoMsg(message: _169.BatchEntryProtoMsg): _169.BatchEntry;
        toProto(message: _169.BatchEntry): Uint8Array;
        toProtoMsg(message: _169.BatchEntry): _169.BatchEntryProtoMsg;
    };
    CompressedBatchProof: {
        typeUrl: string;
        encode(message: _169.CompressedBatchProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.CompressedBatchProof;
        fromPartial(object: Partial<_169.CompressedBatchProof>): _169.CompressedBatchProof;
        fromAmino(object: _169.CompressedBatchProofAmino): _169.CompressedBatchProof;
        toAmino(message: _169.CompressedBatchProof): _169.CompressedBatchProofAmino;
        fromAminoMsg(object: _169.CompressedBatchProofAminoMsg): _169.CompressedBatchProof;
        fromProtoMsg(message: _169.CompressedBatchProofProtoMsg): _169.CompressedBatchProof;
        toProto(message: _169.CompressedBatchProof): Uint8Array;
        toProtoMsg(message: _169.CompressedBatchProof): _169.CompressedBatchProofProtoMsg;
    };
    CompressedBatchEntry: {
        typeUrl: string;
        encode(message: _169.CompressedBatchEntry, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.CompressedBatchEntry;
        fromPartial(object: Partial<_169.CompressedBatchEntry>): _169.CompressedBatchEntry;
        fromAmino(object: _169.CompressedBatchEntryAmino): _169.CompressedBatchEntry;
        toAmino(message: _169.CompressedBatchEntry): _169.CompressedBatchEntryAmino;
        fromAminoMsg(object: _169.CompressedBatchEntryAminoMsg): _169.CompressedBatchEntry;
        fromProtoMsg(message: _169.CompressedBatchEntryProtoMsg): _169.CompressedBatchEntry;
        toProto(message: _169.CompressedBatchEntry): Uint8Array;
        toProtoMsg(message: _169.CompressedBatchEntry): _169.CompressedBatchEntryProtoMsg;
    };
    CompressedExistenceProof: {
        typeUrl: string;
        encode(message: _169.CompressedExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.CompressedExistenceProof;
        fromPartial(object: Partial<_169.CompressedExistenceProof>): _169.CompressedExistenceProof;
        fromAmino(object: _169.CompressedExistenceProofAmino): _169.CompressedExistenceProof;
        toAmino(message: _169.CompressedExistenceProof): _169.CompressedExistenceProofAmino;
        fromAminoMsg(object: _169.CompressedExistenceProofAminoMsg): _169.CompressedExistenceProof;
        fromProtoMsg(message: _169.CompressedExistenceProofProtoMsg): _169.CompressedExistenceProof;
        toProto(message: _169.CompressedExistenceProof): Uint8Array;
        toProtoMsg(message: _169.CompressedExistenceProof): _169.CompressedExistenceProofProtoMsg;
    };
    CompressedNonExistenceProof: {
        typeUrl: string;
        encode(message: _169.CompressedNonExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _169.CompressedNonExistenceProof;
        fromPartial(object: Partial<_169.CompressedNonExistenceProof>): _169.CompressedNonExistenceProof;
        fromAmino(object: _169.CompressedNonExistenceProofAmino): _169.CompressedNonExistenceProof;
        toAmino(message: _169.CompressedNonExistenceProof): _169.CompressedNonExistenceProofAmino;
        fromAminoMsg(object: _169.CompressedNonExistenceProofAminoMsg): _169.CompressedNonExistenceProof;
        fromProtoMsg(message: _169.CompressedNonExistenceProofProtoMsg): _169.CompressedNonExistenceProof;
        toProto(message: _169.CompressedNonExistenceProof): Uint8Array;
        toProtoMsg(message: _169.CompressedNonExistenceProof): _169.CompressedNonExistenceProofProtoMsg;
    };
};
