import * as _176 from "./api/http";
import * as _177 from "./protobuf/timestamp";
import * as _178 from "./protobuf/duration";
import * as _179 from "./protobuf/any";
import * as _180 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _176.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _176.Http;
            fromPartial(object: Partial<_176.Http>): _176.Http;
            fromAmino(object: _176.HttpAmino): _176.Http;
            toAmino(message: _176.Http): _176.HttpAmino;
            fromAminoMsg(object: _176.HttpAminoMsg): _176.Http;
            fromProtoMsg(message: _176.HttpProtoMsg): _176.Http;
            toProto(message: _176.Http): Uint8Array;
            toProtoMsg(message: _176.Http): _176.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _176.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _176.HttpRule;
            fromPartial(object: Partial<_176.HttpRule>): _176.HttpRule;
            fromAmino(object: _176.HttpRuleAmino): _176.HttpRule;
            toAmino(message: _176.HttpRule): _176.HttpRuleAmino;
            fromAminoMsg(object: _176.HttpRuleAminoMsg): _176.HttpRule;
            fromProtoMsg(message: _176.HttpRuleProtoMsg): _176.HttpRule;
            toProto(message: _176.HttpRule): Uint8Array;
            toProtoMsg(message: _176.HttpRule): _176.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _176.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _176.CustomHttpPattern;
            fromPartial(object: Partial<_176.CustomHttpPattern>): _176.CustomHttpPattern;
            fromAmino(object: _176.CustomHttpPatternAmino): _176.CustomHttpPattern;
            toAmino(message: _176.CustomHttpPattern): _176.CustomHttpPatternAmino;
            fromAminoMsg(object: _176.CustomHttpPatternAminoMsg): _176.CustomHttpPattern;
            fromProtoMsg(message: _176.CustomHttpPatternProtoMsg): _176.CustomHttpPattern;
            toProto(message: _176.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _176.CustomHttpPattern): _176.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _180.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _180.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _180.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _180.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _180.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _180.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _180.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _180.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _180.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _180.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _180.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _180.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _180.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _180.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _180.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _180.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _180.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _180.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _180.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _180.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _180.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _180.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _180.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _180.FieldOptions_CType;
        FieldOptions_JSType: typeof _180.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _180.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _180.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _180.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _180.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _180.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _180.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.FileDescriptorSet;
            fromPartial(object: Partial<_180.FileDescriptorSet>): _180.FileDescriptorSet;
            fromAmino(object: _180.FileDescriptorSetAmino): _180.FileDescriptorSet;
            toAmino(message: _180.FileDescriptorSet): _180.FileDescriptorSetAmino;
            fromAminoMsg(object: _180.FileDescriptorSetAminoMsg): _180.FileDescriptorSet;
            fromProtoMsg(message: _180.FileDescriptorSetProtoMsg): _180.FileDescriptorSet;
            toProto(message: _180.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _180.FileDescriptorSet): _180.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _180.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.FileDescriptorProto;
            fromPartial(object: Partial<_180.FileDescriptorProto>): _180.FileDescriptorProto;
            fromAmino(object: _180.FileDescriptorProtoAmino): _180.FileDescriptorProto;
            toAmino(message: _180.FileDescriptorProto): _180.FileDescriptorProtoAmino;
            fromAminoMsg(object: _180.FileDescriptorProtoAminoMsg): _180.FileDescriptorProto;
            fromProtoMsg(message: _180.FileDescriptorProtoProtoMsg): _180.FileDescriptorProto;
            toProto(message: _180.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _180.FileDescriptorProto): _180.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _180.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.DescriptorProto;
            fromPartial(object: Partial<_180.DescriptorProto>): _180.DescriptorProto;
            fromAmino(object: _180.DescriptorProtoAmino): _180.DescriptorProto;
            toAmino(message: _180.DescriptorProto): _180.DescriptorProtoAmino;
            fromAminoMsg(object: _180.DescriptorProtoAminoMsg): _180.DescriptorProto;
            fromProtoMsg(message: _180.DescriptorProtoProtoMsg): _180.DescriptorProto;
            toProto(message: _180.DescriptorProto): Uint8Array;
            toProtoMsg(message: _180.DescriptorProto): _180.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _180.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_180.DescriptorProto_ExtensionRange>): _180.DescriptorProto_ExtensionRange;
            fromAmino(object: _180.DescriptorProto_ExtensionRangeAmino): _180.DescriptorProto_ExtensionRange;
            toAmino(message: _180.DescriptorProto_ExtensionRange): _180.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _180.DescriptorProto_ExtensionRangeAminoMsg): _180.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _180.DescriptorProto_ExtensionRangeProtoMsg): _180.DescriptorProto_ExtensionRange;
            toProto(message: _180.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _180.DescriptorProto_ExtensionRange): _180.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _180.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_180.DescriptorProto_ReservedRange>): _180.DescriptorProto_ReservedRange;
            fromAmino(object: _180.DescriptorProto_ReservedRangeAmino): _180.DescriptorProto_ReservedRange;
            toAmino(message: _180.DescriptorProto_ReservedRange): _180.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _180.DescriptorProto_ReservedRangeAminoMsg): _180.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _180.DescriptorProto_ReservedRangeProtoMsg): _180.DescriptorProto_ReservedRange;
            toProto(message: _180.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _180.DescriptorProto_ReservedRange): _180.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _180.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.ExtensionRangeOptions;
            fromPartial(object: Partial<_180.ExtensionRangeOptions>): _180.ExtensionRangeOptions;
            fromAmino(object: _180.ExtensionRangeOptionsAmino): _180.ExtensionRangeOptions;
            toAmino(message: _180.ExtensionRangeOptions): _180.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _180.ExtensionRangeOptionsAminoMsg): _180.ExtensionRangeOptions;
            fromProtoMsg(message: _180.ExtensionRangeOptionsProtoMsg): _180.ExtensionRangeOptions;
            toProto(message: _180.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _180.ExtensionRangeOptions): _180.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _180.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.FieldDescriptorProto;
            fromPartial(object: Partial<_180.FieldDescriptorProto>): _180.FieldDescriptorProto;
            fromAmino(object: _180.FieldDescriptorProtoAmino): _180.FieldDescriptorProto;
            toAmino(message: _180.FieldDescriptorProto): _180.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _180.FieldDescriptorProtoAminoMsg): _180.FieldDescriptorProto;
            fromProtoMsg(message: _180.FieldDescriptorProtoProtoMsg): _180.FieldDescriptorProto;
            toProto(message: _180.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _180.FieldDescriptorProto): _180.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _180.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.OneofDescriptorProto;
            fromPartial(object: Partial<_180.OneofDescriptorProto>): _180.OneofDescriptorProto;
            fromAmino(object: _180.OneofDescriptorProtoAmino): _180.OneofDescriptorProto;
            toAmino(message: _180.OneofDescriptorProto): _180.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _180.OneofDescriptorProtoAminoMsg): _180.OneofDescriptorProto;
            fromProtoMsg(message: _180.OneofDescriptorProtoProtoMsg): _180.OneofDescriptorProto;
            toProto(message: _180.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _180.OneofDescriptorProto): _180.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _180.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.EnumDescriptorProto;
            fromPartial(object: Partial<_180.EnumDescriptorProto>): _180.EnumDescriptorProto;
            fromAmino(object: _180.EnumDescriptorProtoAmino): _180.EnumDescriptorProto;
            toAmino(message: _180.EnumDescriptorProto): _180.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _180.EnumDescriptorProtoAminoMsg): _180.EnumDescriptorProto;
            fromProtoMsg(message: _180.EnumDescriptorProtoProtoMsg): _180.EnumDescriptorProto;
            toProto(message: _180.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _180.EnumDescriptorProto): _180.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _180.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_180.EnumDescriptorProto_EnumReservedRange>): _180.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _180.EnumDescriptorProto_EnumReservedRangeAmino): _180.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _180.EnumDescriptorProto_EnumReservedRange): _180.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _180.EnumDescriptorProto_EnumReservedRangeAminoMsg): _180.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _180.EnumDescriptorProto_EnumReservedRangeProtoMsg): _180.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _180.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _180.EnumDescriptorProto_EnumReservedRange): _180.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _180.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.EnumValueDescriptorProto;
            fromPartial(object: Partial<_180.EnumValueDescriptorProto>): _180.EnumValueDescriptorProto;
            fromAmino(object: _180.EnumValueDescriptorProtoAmino): _180.EnumValueDescriptorProto;
            toAmino(message: _180.EnumValueDescriptorProto): _180.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _180.EnumValueDescriptorProtoAminoMsg): _180.EnumValueDescriptorProto;
            fromProtoMsg(message: _180.EnumValueDescriptorProtoProtoMsg): _180.EnumValueDescriptorProto;
            toProto(message: _180.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _180.EnumValueDescriptorProto): _180.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _180.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.ServiceDescriptorProto;
            fromPartial(object: Partial<_180.ServiceDescriptorProto>): _180.ServiceDescriptorProto;
            fromAmino(object: _180.ServiceDescriptorProtoAmino): _180.ServiceDescriptorProto;
            toAmino(message: _180.ServiceDescriptorProto): _180.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _180.ServiceDescriptorProtoAminoMsg): _180.ServiceDescriptorProto;
            fromProtoMsg(message: _180.ServiceDescriptorProtoProtoMsg): _180.ServiceDescriptorProto;
            toProto(message: _180.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _180.ServiceDescriptorProto): _180.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _180.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.MethodDescriptorProto;
            fromPartial(object: Partial<_180.MethodDescriptorProto>): _180.MethodDescriptorProto;
            fromAmino(object: _180.MethodDescriptorProtoAmino): _180.MethodDescriptorProto;
            toAmino(message: _180.MethodDescriptorProto): _180.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _180.MethodDescriptorProtoAminoMsg): _180.MethodDescriptorProto;
            fromProtoMsg(message: _180.MethodDescriptorProtoProtoMsg): _180.MethodDescriptorProto;
            toProto(message: _180.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _180.MethodDescriptorProto): _180.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _180.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.FileOptions;
            fromPartial(object: Partial<_180.FileOptions>): _180.FileOptions;
            fromAmino(object: _180.FileOptionsAmino): _180.FileOptions;
            toAmino(message: _180.FileOptions): _180.FileOptionsAmino;
            fromAminoMsg(object: _180.FileOptionsAminoMsg): _180.FileOptions;
            fromProtoMsg(message: _180.FileOptionsProtoMsg): _180.FileOptions;
            toProto(message: _180.FileOptions): Uint8Array;
            toProtoMsg(message: _180.FileOptions): _180.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _180.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.MessageOptions;
            fromPartial(object: Partial<_180.MessageOptions>): _180.MessageOptions;
            fromAmino(object: _180.MessageOptionsAmino): _180.MessageOptions;
            toAmino(message: _180.MessageOptions): _180.MessageOptionsAmino;
            fromAminoMsg(object: _180.MessageOptionsAminoMsg): _180.MessageOptions;
            fromProtoMsg(message: _180.MessageOptionsProtoMsg): _180.MessageOptions;
            toProto(message: _180.MessageOptions): Uint8Array;
            toProtoMsg(message: _180.MessageOptions): _180.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _180.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.FieldOptions;
            fromPartial(object: Partial<_180.FieldOptions>): _180.FieldOptions;
            fromAmino(object: _180.FieldOptionsAmino): _180.FieldOptions;
            toAmino(message: _180.FieldOptions): _180.FieldOptionsAmino;
            fromAminoMsg(object: _180.FieldOptionsAminoMsg): _180.FieldOptions;
            fromProtoMsg(message: _180.FieldOptionsProtoMsg): _180.FieldOptions;
            toProto(message: _180.FieldOptions): Uint8Array;
            toProtoMsg(message: _180.FieldOptions): _180.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _180.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.OneofOptions;
            fromPartial(object: Partial<_180.OneofOptions>): _180.OneofOptions;
            fromAmino(object: _180.OneofOptionsAmino): _180.OneofOptions;
            toAmino(message: _180.OneofOptions): _180.OneofOptionsAmino;
            fromAminoMsg(object: _180.OneofOptionsAminoMsg): _180.OneofOptions;
            fromProtoMsg(message: _180.OneofOptionsProtoMsg): _180.OneofOptions;
            toProto(message: _180.OneofOptions): Uint8Array;
            toProtoMsg(message: _180.OneofOptions): _180.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _180.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.EnumOptions;
            fromPartial(object: Partial<_180.EnumOptions>): _180.EnumOptions;
            fromAmino(object: _180.EnumOptionsAmino): _180.EnumOptions;
            toAmino(message: _180.EnumOptions): _180.EnumOptionsAmino;
            fromAminoMsg(object: _180.EnumOptionsAminoMsg): _180.EnumOptions;
            fromProtoMsg(message: _180.EnumOptionsProtoMsg): _180.EnumOptions;
            toProto(message: _180.EnumOptions): Uint8Array;
            toProtoMsg(message: _180.EnumOptions): _180.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _180.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.EnumValueOptions;
            fromPartial(object: Partial<_180.EnumValueOptions>): _180.EnumValueOptions;
            fromAmino(object: _180.EnumValueOptionsAmino): _180.EnumValueOptions;
            toAmino(message: _180.EnumValueOptions): _180.EnumValueOptionsAmino;
            fromAminoMsg(object: _180.EnumValueOptionsAminoMsg): _180.EnumValueOptions;
            fromProtoMsg(message: _180.EnumValueOptionsProtoMsg): _180.EnumValueOptions;
            toProto(message: _180.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _180.EnumValueOptions): _180.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _180.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.ServiceOptions;
            fromPartial(object: Partial<_180.ServiceOptions>): _180.ServiceOptions;
            fromAmino(object: _180.ServiceOptionsAmino): _180.ServiceOptions;
            toAmino(message: _180.ServiceOptions): _180.ServiceOptionsAmino;
            fromAminoMsg(object: _180.ServiceOptionsAminoMsg): _180.ServiceOptions;
            fromProtoMsg(message: _180.ServiceOptionsProtoMsg): _180.ServiceOptions;
            toProto(message: _180.ServiceOptions): Uint8Array;
            toProtoMsg(message: _180.ServiceOptions): _180.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _180.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.MethodOptions;
            fromPartial(object: Partial<_180.MethodOptions>): _180.MethodOptions;
            fromAmino(object: _180.MethodOptionsAmino): _180.MethodOptions;
            toAmino(message: _180.MethodOptions): _180.MethodOptionsAmino;
            fromAminoMsg(object: _180.MethodOptionsAminoMsg): _180.MethodOptions;
            fromProtoMsg(message: _180.MethodOptionsProtoMsg): _180.MethodOptions;
            toProto(message: _180.MethodOptions): Uint8Array;
            toProtoMsg(message: _180.MethodOptions): _180.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _180.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.UninterpretedOption;
            fromPartial(object: Partial<_180.UninterpretedOption>): _180.UninterpretedOption;
            fromAmino(object: _180.UninterpretedOptionAmino): _180.UninterpretedOption;
            toAmino(message: _180.UninterpretedOption): _180.UninterpretedOptionAmino;
            fromAminoMsg(object: _180.UninterpretedOptionAminoMsg): _180.UninterpretedOption;
            fromProtoMsg(message: _180.UninterpretedOptionProtoMsg): _180.UninterpretedOption;
            toProto(message: _180.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _180.UninterpretedOption): _180.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _180.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_180.UninterpretedOption_NamePart>): _180.UninterpretedOption_NamePart;
            fromAmino(object: _180.UninterpretedOption_NamePartAmino): _180.UninterpretedOption_NamePart;
            toAmino(message: _180.UninterpretedOption_NamePart): _180.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _180.UninterpretedOption_NamePartAminoMsg): _180.UninterpretedOption_NamePart;
            fromProtoMsg(message: _180.UninterpretedOption_NamePartProtoMsg): _180.UninterpretedOption_NamePart;
            toProto(message: _180.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _180.UninterpretedOption_NamePart): _180.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _180.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.SourceCodeInfo;
            fromPartial(object: Partial<_180.SourceCodeInfo>): _180.SourceCodeInfo;
            fromAmino(object: _180.SourceCodeInfoAmino): _180.SourceCodeInfo;
            toAmino(message: _180.SourceCodeInfo): _180.SourceCodeInfoAmino;
            fromAminoMsg(object: _180.SourceCodeInfoAminoMsg): _180.SourceCodeInfo;
            fromProtoMsg(message: _180.SourceCodeInfoProtoMsg): _180.SourceCodeInfo;
            toProto(message: _180.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _180.SourceCodeInfo): _180.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _180.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.SourceCodeInfo_Location;
            fromPartial(object: Partial<_180.SourceCodeInfo_Location>): _180.SourceCodeInfo_Location;
            fromAmino(object: _180.SourceCodeInfo_LocationAmino): _180.SourceCodeInfo_Location;
            toAmino(message: _180.SourceCodeInfo_Location): _180.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _180.SourceCodeInfo_LocationAminoMsg): _180.SourceCodeInfo_Location;
            fromProtoMsg(message: _180.SourceCodeInfo_LocationProtoMsg): _180.SourceCodeInfo_Location;
            toProto(message: _180.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _180.SourceCodeInfo_Location): _180.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _180.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.GeneratedCodeInfo;
            fromPartial(object: Partial<_180.GeneratedCodeInfo>): _180.GeneratedCodeInfo;
            fromAmino(object: _180.GeneratedCodeInfoAmino): _180.GeneratedCodeInfo;
            toAmino(message: _180.GeneratedCodeInfo): _180.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _180.GeneratedCodeInfoAminoMsg): _180.GeneratedCodeInfo;
            fromProtoMsg(message: _180.GeneratedCodeInfoProtoMsg): _180.GeneratedCodeInfo;
            toProto(message: _180.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _180.GeneratedCodeInfo): _180.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _180.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_180.GeneratedCodeInfo_Annotation>): _180.GeneratedCodeInfo_Annotation;
            fromAmino(object: _180.GeneratedCodeInfo_AnnotationAmino): _180.GeneratedCodeInfo_Annotation;
            toAmino(message: _180.GeneratedCodeInfo_Annotation): _180.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _180.GeneratedCodeInfo_AnnotationAminoMsg): _180.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _180.GeneratedCodeInfo_AnnotationProtoMsg): _180.GeneratedCodeInfo_Annotation;
            toProto(message: _180.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _180.GeneratedCodeInfo_Annotation): _180.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _179.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _179.Any;
            fromPartial(object: Partial<_179.Any>): _179.Any;
            fromAmino(object: _179.AnyAmino): _179.Any;
            toAmino(message: _179.Any): _179.AnyAmino;
            fromAminoMsg(object: _179.AnyAminoMsg): _179.Any;
            fromProtoMsg(message: _179.AnyProtoMsg): _179.Any;
            toProto(message: _179.Any): Uint8Array;
            toProtoMsg(message: _179.Any): _179.AnyProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _178.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.Duration;
            fromPartial(object: Partial<_178.Duration>): _178.Duration;
            fromAmino(object: string): _178.Duration;
            toAmino(message: _178.Duration): string;
            fromAminoMsg(object: _178.DurationAminoMsg): _178.Duration;
            fromProtoMsg(message: _178.DurationProtoMsg): _178.Duration;
            toProto(message: _178.Duration): Uint8Array;
            toProtoMsg(message: _178.Duration): _178.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _177.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _177.Timestamp;
            fromPartial(object: Partial<_177.Timestamp>): _177.Timestamp;
            fromAmino(object: string): _177.Timestamp;
            toAmino(message: _177.Timestamp): string;
            fromAminoMsg(object: _177.TimestampAminoMsg): _177.Timestamp;
            fromProtoMsg(message: _177.TimestampProtoMsg): _177.Timestamp;
            toProto(message: _177.Timestamp): Uint8Array;
            toProtoMsg(message: _177.Timestamp): _177.TimestampProtoMsg;
        };
    };
}
