import * as _21 from "../confio/proofs";
export declare const ics23: {
    hashOpFromJSON(object: any): _21.HashOp;
    hashOpToJSON(object: _21.HashOp): string;
    lengthOpFromJSON(object: any): _21.LengthOp;
    lengthOpToJSON(object: _21.LengthOp): string;
    HashOp: typeof _21.HashOp;
    HashOpSDKType: typeof _21.HashOp;
    HashOpAmino: typeof _21.HashOp;
    LengthOp: typeof _21.LengthOp;
    LengthOpSDKType: typeof _21.LengthOp;
    LengthOpAmino: typeof _21.LengthOp;
    ExistenceProof: {
        typeUrl: string;
        encode(message: _21.ExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.ExistenceProof;
        fromPartial(object: Partial<_21.ExistenceProof>): _21.ExistenceProof;
        fromAmino(object: _21.ExistenceProofAmino): _21.ExistenceProof;
        toAmino(message: _21.ExistenceProof): _21.ExistenceProofAmino;
        fromAminoMsg(object: _21.ExistenceProofAminoMsg): _21.ExistenceProof;
        fromProtoMsg(message: _21.ExistenceProofProtoMsg): _21.ExistenceProof;
        toProto(message: _21.ExistenceProof): Uint8Array;
        toProtoMsg(message: _21.ExistenceProof): _21.ExistenceProofProtoMsg;
    };
    NonExistenceProof: {
        typeUrl: string;
        encode(message: _21.NonExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.NonExistenceProof;
        fromPartial(object: Partial<_21.NonExistenceProof>): _21.NonExistenceProof;
        fromAmino(object: _21.NonExistenceProofAmino): _21.NonExistenceProof;
        toAmino(message: _21.NonExistenceProof): _21.NonExistenceProofAmino;
        fromAminoMsg(object: _21.NonExistenceProofAminoMsg): _21.NonExistenceProof;
        fromProtoMsg(message: _21.NonExistenceProofProtoMsg): _21.NonExistenceProof;
        toProto(message: _21.NonExistenceProof): Uint8Array;
        toProtoMsg(message: _21.NonExistenceProof): _21.NonExistenceProofProtoMsg;
    };
    CommitmentProof: {
        typeUrl: string;
        encode(message: _21.CommitmentProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.CommitmentProof;
        fromPartial(object: Partial<_21.CommitmentProof>): _21.CommitmentProof;
        fromAmino(object: _21.CommitmentProofAmino): _21.CommitmentProof;
        toAmino(message: _21.CommitmentProof): _21.CommitmentProofAmino;
        fromAminoMsg(object: _21.CommitmentProofAminoMsg): _21.CommitmentProof;
        fromProtoMsg(message: _21.CommitmentProofProtoMsg): _21.CommitmentProof;
        toProto(message: _21.CommitmentProof): Uint8Array;
        toProtoMsg(message: _21.CommitmentProof): _21.CommitmentProofProtoMsg;
    };
    LeafOp: {
        typeUrl: string;
        encode(message: _21.LeafOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.LeafOp;
        fromPartial(object: Partial<_21.LeafOp>): _21.LeafOp;
        fromAmino(object: _21.LeafOpAmino): _21.LeafOp;
        toAmino(message: _21.LeafOp): _21.LeafOpAmino;
        fromAminoMsg(object: _21.LeafOpAminoMsg): _21.LeafOp;
        fromProtoMsg(message: _21.LeafOpProtoMsg): _21.LeafOp;
        toProto(message: _21.LeafOp): Uint8Array;
        toProtoMsg(message: _21.LeafOp): _21.LeafOpProtoMsg;
    };
    InnerOp: {
        typeUrl: string;
        encode(message: _21.InnerOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.InnerOp;
        fromPartial(object: Partial<_21.InnerOp>): _21.InnerOp;
        fromAmino(object: _21.InnerOpAmino): _21.InnerOp;
        toAmino(message: _21.InnerOp): _21.InnerOpAmino;
        fromAminoMsg(object: _21.InnerOpAminoMsg): _21.InnerOp;
        fromProtoMsg(message: _21.InnerOpProtoMsg): _21.InnerOp;
        toProto(message: _21.InnerOp): Uint8Array;
        toProtoMsg(message: _21.InnerOp): _21.InnerOpProtoMsg;
    };
    ProofSpec: {
        typeUrl: string;
        encode(message: _21.ProofSpec, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.ProofSpec;
        fromPartial(object: Partial<_21.ProofSpec>): _21.ProofSpec;
        fromAmino(object: _21.ProofSpecAmino): _21.ProofSpec;
        toAmino(message: _21.ProofSpec): _21.ProofSpecAmino;
        fromAminoMsg(object: _21.ProofSpecAminoMsg): _21.ProofSpec;
        fromProtoMsg(message: _21.ProofSpecProtoMsg): _21.ProofSpec;
        toProto(message: _21.ProofSpec): Uint8Array;
        toProtoMsg(message: _21.ProofSpec): _21.ProofSpecProtoMsg;
    };
    InnerSpec: {
        typeUrl: string;
        encode(message: _21.InnerSpec, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.InnerSpec;
        fromPartial(object: Partial<_21.InnerSpec>): _21.InnerSpec;
        fromAmino(object: _21.InnerSpecAmino): _21.InnerSpec;
        toAmino(message: _21.InnerSpec): _21.InnerSpecAmino;
        fromAminoMsg(object: _21.InnerSpecAminoMsg): _21.InnerSpec;
        fromProtoMsg(message: _21.InnerSpecProtoMsg): _21.InnerSpec;
        toProto(message: _21.InnerSpec): Uint8Array;
        toProtoMsg(message: _21.InnerSpec): _21.InnerSpecProtoMsg;
    };
    BatchProof: {
        typeUrl: string;
        encode(message: _21.BatchProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.BatchProof;
        fromPartial(object: Partial<_21.BatchProof>): _21.BatchProof;
        fromAmino(object: _21.BatchProofAmino): _21.BatchProof;
        toAmino(message: _21.BatchProof): _21.BatchProofAmino;
        fromAminoMsg(object: _21.BatchProofAminoMsg): _21.BatchProof;
        fromProtoMsg(message: _21.BatchProofProtoMsg): _21.BatchProof;
        toProto(message: _21.BatchProof): Uint8Array;
        toProtoMsg(message: _21.BatchProof): _21.BatchProofProtoMsg;
    };
    BatchEntry: {
        typeUrl: string;
        encode(message: _21.BatchEntry, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.BatchEntry;
        fromPartial(object: Partial<_21.BatchEntry>): _21.BatchEntry;
        fromAmino(object: _21.BatchEntryAmino): _21.BatchEntry;
        toAmino(message: _21.BatchEntry): _21.BatchEntryAmino;
        fromAminoMsg(object: _21.BatchEntryAminoMsg): _21.BatchEntry;
        fromProtoMsg(message: _21.BatchEntryProtoMsg): _21.BatchEntry;
        toProto(message: _21.BatchEntry): Uint8Array;
        toProtoMsg(message: _21.BatchEntry): _21.BatchEntryProtoMsg;
    };
    CompressedBatchProof: {
        typeUrl: string;
        encode(message: _21.CompressedBatchProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.CompressedBatchProof;
        fromPartial(object: Partial<_21.CompressedBatchProof>): _21.CompressedBatchProof;
        fromAmino(object: _21.CompressedBatchProofAmino): _21.CompressedBatchProof;
        toAmino(message: _21.CompressedBatchProof): _21.CompressedBatchProofAmino;
        fromAminoMsg(object: _21.CompressedBatchProofAminoMsg): _21.CompressedBatchProof;
        fromProtoMsg(message: _21.CompressedBatchProofProtoMsg): _21.CompressedBatchProof;
        toProto(message: _21.CompressedBatchProof): Uint8Array;
        toProtoMsg(message: _21.CompressedBatchProof): _21.CompressedBatchProofProtoMsg;
    };
    CompressedBatchEntry: {
        typeUrl: string;
        encode(message: _21.CompressedBatchEntry, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.CompressedBatchEntry;
        fromPartial(object: Partial<_21.CompressedBatchEntry>): _21.CompressedBatchEntry;
        fromAmino(object: _21.CompressedBatchEntryAmino): _21.CompressedBatchEntry;
        toAmino(message: _21.CompressedBatchEntry): _21.CompressedBatchEntryAmino;
        fromAminoMsg(object: _21.CompressedBatchEntryAminoMsg): _21.CompressedBatchEntry;
        fromProtoMsg(message: _21.CompressedBatchEntryProtoMsg): _21.CompressedBatchEntry;
        toProto(message: _21.CompressedBatchEntry): Uint8Array;
        toProtoMsg(message: _21.CompressedBatchEntry): _21.CompressedBatchEntryProtoMsg;
    };
    CompressedExistenceProof: {
        typeUrl: string;
        encode(message: _21.CompressedExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.CompressedExistenceProof;
        fromPartial(object: Partial<_21.CompressedExistenceProof>): _21.CompressedExistenceProof;
        fromAmino(object: _21.CompressedExistenceProofAmino): _21.CompressedExistenceProof;
        toAmino(message: _21.CompressedExistenceProof): _21.CompressedExistenceProofAmino;
        fromAminoMsg(object: _21.CompressedExistenceProofAminoMsg): _21.CompressedExistenceProof;
        fromProtoMsg(message: _21.CompressedExistenceProofProtoMsg): _21.CompressedExistenceProof;
        toProto(message: _21.CompressedExistenceProof): Uint8Array;
        toProtoMsg(message: _21.CompressedExistenceProof): _21.CompressedExistenceProofProtoMsg;
    };
    CompressedNonExistenceProof: {
        typeUrl: string;
        encode(message: _21.CompressedNonExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        fromJSON(object: any): _21.CompressedNonExistenceProof;
        fromPartial(object: Partial<_21.CompressedNonExistenceProof>): _21.CompressedNonExistenceProof;
        fromAmino(object: _21.CompressedNonExistenceProofAmino): _21.CompressedNonExistenceProof;
        toAmino(message: _21.CompressedNonExistenceProof): _21.CompressedNonExistenceProofAmino;
        fromAminoMsg(object: _21.CompressedNonExistenceProofAminoMsg): _21.CompressedNonExistenceProof;
        fromProtoMsg(message: _21.CompressedNonExistenceProofProtoMsg): _21.CompressedNonExistenceProof;
        toProto(message: _21.CompressedNonExistenceProof): Uint8Array;
        toProtoMsg(message: _21.CompressedNonExistenceProof): _21.CompressedNonExistenceProofProtoMsg;
    };
};
