import * as _199 from "./api/http";
import * as _200 from "./protobuf/duration";
import * as _201 from "./protobuf/timestamp";
import * as _202 from "./protobuf/any";
import * as _203 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _199.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _199.Http;
            fromPartial(object: Partial<_199.Http>): _199.Http;
            fromAmino(object: _199.HttpAmino): _199.Http;
            toAmino(message: _199.Http): _199.HttpAmino;
            fromAminoMsg(object: _199.HttpAminoMsg): _199.Http;
            fromProtoMsg(message: _199.HttpProtoMsg): _199.Http;
            toProto(message: _199.Http): Uint8Array;
            toProtoMsg(message: _199.Http): _199.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _199.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _199.HttpRule;
            fromPartial(object: Partial<_199.HttpRule>): _199.HttpRule;
            fromAmino(object: _199.HttpRuleAmino): _199.HttpRule;
            toAmino(message: _199.HttpRule): _199.HttpRuleAmino;
            fromAminoMsg(object: _199.HttpRuleAminoMsg): _199.HttpRule;
            fromProtoMsg(message: _199.HttpRuleProtoMsg): _199.HttpRule;
            toProto(message: _199.HttpRule): Uint8Array;
            toProtoMsg(message: _199.HttpRule): _199.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _199.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _199.CustomHttpPattern;
            fromPartial(object: Partial<_199.CustomHttpPattern>): _199.CustomHttpPattern;
            fromAmino(object: _199.CustomHttpPatternAmino): _199.CustomHttpPattern;
            toAmino(message: _199.CustomHttpPattern): _199.CustomHttpPatternAmino;
            fromAminoMsg(object: _199.CustomHttpPatternAminoMsg): _199.CustomHttpPattern;
            fromProtoMsg(message: _199.CustomHttpPatternProtoMsg): _199.CustomHttpPattern;
            toProto(message: _199.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _199.CustomHttpPattern): _199.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _203.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _203.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _203.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _203.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _203.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _203.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _203.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _203.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _203.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _203.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _203.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _203.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _203.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _203.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _203.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _203.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _203.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _203.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _203.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _203.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _203.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _203.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _203.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _203.FieldOptions_CType;
        FieldOptions_JSType: typeof _203.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _203.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _203.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _203.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _203.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _203.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _203.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.FileDescriptorSet;
            fromPartial(object: Partial<_203.FileDescriptorSet>): _203.FileDescriptorSet;
            fromAmino(object: _203.FileDescriptorSetAmino): _203.FileDescriptorSet;
            toAmino(message: _203.FileDescriptorSet): _203.FileDescriptorSetAmino;
            fromAminoMsg(object: _203.FileDescriptorSetAminoMsg): _203.FileDescriptorSet;
            fromProtoMsg(message: _203.FileDescriptorSetProtoMsg): _203.FileDescriptorSet;
            toProto(message: _203.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _203.FileDescriptorSet): _203.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _203.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.FileDescriptorProto;
            fromPartial(object: Partial<_203.FileDescriptorProto>): _203.FileDescriptorProto;
            fromAmino(object: _203.FileDescriptorProtoAmino): _203.FileDescriptorProto;
            toAmino(message: _203.FileDescriptorProto): _203.FileDescriptorProtoAmino;
            fromAminoMsg(object: _203.FileDescriptorProtoAminoMsg): _203.FileDescriptorProto;
            fromProtoMsg(message: _203.FileDescriptorProtoProtoMsg): _203.FileDescriptorProto;
            toProto(message: _203.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _203.FileDescriptorProto): _203.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _203.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.DescriptorProto;
            fromPartial(object: Partial<_203.DescriptorProto>): _203.DescriptorProto;
            fromAmino(object: _203.DescriptorProtoAmino): _203.DescriptorProto;
            toAmino(message: _203.DescriptorProto): _203.DescriptorProtoAmino;
            fromAminoMsg(object: _203.DescriptorProtoAminoMsg): _203.DescriptorProto;
            fromProtoMsg(message: _203.DescriptorProtoProtoMsg): _203.DescriptorProto;
            toProto(message: _203.DescriptorProto): Uint8Array;
            toProtoMsg(message: _203.DescriptorProto): _203.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _203.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_203.DescriptorProto_ExtensionRange>): _203.DescriptorProto_ExtensionRange;
            fromAmino(object: _203.DescriptorProto_ExtensionRangeAmino): _203.DescriptorProto_ExtensionRange;
            toAmino(message: _203.DescriptorProto_ExtensionRange): _203.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _203.DescriptorProto_ExtensionRangeAminoMsg): _203.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _203.DescriptorProto_ExtensionRangeProtoMsg): _203.DescriptorProto_ExtensionRange;
            toProto(message: _203.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _203.DescriptorProto_ExtensionRange): _203.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _203.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_203.DescriptorProto_ReservedRange>): _203.DescriptorProto_ReservedRange;
            fromAmino(object: _203.DescriptorProto_ReservedRangeAmino): _203.DescriptorProto_ReservedRange;
            toAmino(message: _203.DescriptorProto_ReservedRange): _203.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _203.DescriptorProto_ReservedRangeAminoMsg): _203.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _203.DescriptorProto_ReservedRangeProtoMsg): _203.DescriptorProto_ReservedRange;
            toProto(message: _203.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _203.DescriptorProto_ReservedRange): _203.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _203.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.ExtensionRangeOptions;
            fromPartial(object: Partial<_203.ExtensionRangeOptions>): _203.ExtensionRangeOptions;
            fromAmino(object: _203.ExtensionRangeOptionsAmino): _203.ExtensionRangeOptions;
            toAmino(message: _203.ExtensionRangeOptions): _203.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _203.ExtensionRangeOptionsAminoMsg): _203.ExtensionRangeOptions;
            fromProtoMsg(message: _203.ExtensionRangeOptionsProtoMsg): _203.ExtensionRangeOptions;
            toProto(message: _203.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _203.ExtensionRangeOptions): _203.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _203.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.FieldDescriptorProto;
            fromPartial(object: Partial<_203.FieldDescriptorProto>): _203.FieldDescriptorProto;
            fromAmino(object: _203.FieldDescriptorProtoAmino): _203.FieldDescriptorProto;
            toAmino(message: _203.FieldDescriptorProto): _203.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _203.FieldDescriptorProtoAminoMsg): _203.FieldDescriptorProto;
            fromProtoMsg(message: _203.FieldDescriptorProtoProtoMsg): _203.FieldDescriptorProto;
            toProto(message: _203.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _203.FieldDescriptorProto): _203.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _203.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.OneofDescriptorProto;
            fromPartial(object: Partial<_203.OneofDescriptorProto>): _203.OneofDescriptorProto;
            fromAmino(object: _203.OneofDescriptorProtoAmino): _203.OneofDescriptorProto;
            toAmino(message: _203.OneofDescriptorProto): _203.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _203.OneofDescriptorProtoAminoMsg): _203.OneofDescriptorProto;
            fromProtoMsg(message: _203.OneofDescriptorProtoProtoMsg): _203.OneofDescriptorProto;
            toProto(message: _203.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _203.OneofDescriptorProto): _203.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _203.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.EnumDescriptorProto;
            fromPartial(object: Partial<_203.EnumDescriptorProto>): _203.EnumDescriptorProto;
            fromAmino(object: _203.EnumDescriptorProtoAmino): _203.EnumDescriptorProto;
            toAmino(message: _203.EnumDescriptorProto): _203.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _203.EnumDescriptorProtoAminoMsg): _203.EnumDescriptorProto;
            fromProtoMsg(message: _203.EnumDescriptorProtoProtoMsg): _203.EnumDescriptorProto;
            toProto(message: _203.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _203.EnumDescriptorProto): _203.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _203.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_203.EnumDescriptorProto_EnumReservedRange>): _203.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _203.EnumDescriptorProto_EnumReservedRangeAmino): _203.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _203.EnumDescriptorProto_EnumReservedRange): _203.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _203.EnumDescriptorProto_EnumReservedRangeAminoMsg): _203.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _203.EnumDescriptorProto_EnumReservedRangeProtoMsg): _203.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _203.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _203.EnumDescriptorProto_EnumReservedRange): _203.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _203.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.EnumValueDescriptorProto;
            fromPartial(object: Partial<_203.EnumValueDescriptorProto>): _203.EnumValueDescriptorProto;
            fromAmino(object: _203.EnumValueDescriptorProtoAmino): _203.EnumValueDescriptorProto;
            toAmino(message: _203.EnumValueDescriptorProto): _203.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _203.EnumValueDescriptorProtoAminoMsg): _203.EnumValueDescriptorProto;
            fromProtoMsg(message: _203.EnumValueDescriptorProtoProtoMsg): _203.EnumValueDescriptorProto;
            toProto(message: _203.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _203.EnumValueDescriptorProto): _203.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _203.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.ServiceDescriptorProto;
            fromPartial(object: Partial<_203.ServiceDescriptorProto>): _203.ServiceDescriptorProto;
            fromAmino(object: _203.ServiceDescriptorProtoAmino): _203.ServiceDescriptorProto;
            toAmino(message: _203.ServiceDescriptorProto): _203.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _203.ServiceDescriptorProtoAminoMsg): _203.ServiceDescriptorProto;
            fromProtoMsg(message: _203.ServiceDescriptorProtoProtoMsg): _203.ServiceDescriptorProto;
            toProto(message: _203.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _203.ServiceDescriptorProto): _203.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _203.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.MethodDescriptorProto;
            fromPartial(object: Partial<_203.MethodDescriptorProto>): _203.MethodDescriptorProto;
            fromAmino(object: _203.MethodDescriptorProtoAmino): _203.MethodDescriptorProto;
            toAmino(message: _203.MethodDescriptorProto): _203.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _203.MethodDescriptorProtoAminoMsg): _203.MethodDescriptorProto;
            fromProtoMsg(message: _203.MethodDescriptorProtoProtoMsg): _203.MethodDescriptorProto;
            toProto(message: _203.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _203.MethodDescriptorProto): _203.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _203.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.FileOptions;
            fromPartial(object: Partial<_203.FileOptions>): _203.FileOptions;
            fromAmino(object: _203.FileOptionsAmino): _203.FileOptions;
            toAmino(message: _203.FileOptions): _203.FileOptionsAmino;
            fromAminoMsg(object: _203.FileOptionsAminoMsg): _203.FileOptions;
            fromProtoMsg(message: _203.FileOptionsProtoMsg): _203.FileOptions;
            toProto(message: _203.FileOptions): Uint8Array;
            toProtoMsg(message: _203.FileOptions): _203.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _203.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.MessageOptions;
            fromPartial(object: Partial<_203.MessageOptions>): _203.MessageOptions;
            fromAmino(object: _203.MessageOptionsAmino): _203.MessageOptions;
            toAmino(message: _203.MessageOptions): _203.MessageOptionsAmino;
            fromAminoMsg(object: _203.MessageOptionsAminoMsg): _203.MessageOptions;
            fromProtoMsg(message: _203.MessageOptionsProtoMsg): _203.MessageOptions;
            toProto(message: _203.MessageOptions): Uint8Array;
            toProtoMsg(message: _203.MessageOptions): _203.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _203.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.FieldOptions;
            fromPartial(object: Partial<_203.FieldOptions>): _203.FieldOptions;
            fromAmino(object: _203.FieldOptionsAmino): _203.FieldOptions;
            toAmino(message: _203.FieldOptions): _203.FieldOptionsAmino;
            fromAminoMsg(object: _203.FieldOptionsAminoMsg): _203.FieldOptions;
            fromProtoMsg(message: _203.FieldOptionsProtoMsg): _203.FieldOptions;
            toProto(message: _203.FieldOptions): Uint8Array;
            toProtoMsg(message: _203.FieldOptions): _203.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _203.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.OneofOptions;
            fromPartial(object: Partial<_203.OneofOptions>): _203.OneofOptions;
            fromAmino(object: _203.OneofOptionsAmino): _203.OneofOptions;
            toAmino(message: _203.OneofOptions): _203.OneofOptionsAmino;
            fromAminoMsg(object: _203.OneofOptionsAminoMsg): _203.OneofOptions;
            fromProtoMsg(message: _203.OneofOptionsProtoMsg): _203.OneofOptions;
            toProto(message: _203.OneofOptions): Uint8Array;
            toProtoMsg(message: _203.OneofOptions): _203.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _203.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.EnumOptions;
            fromPartial(object: Partial<_203.EnumOptions>): _203.EnumOptions;
            fromAmino(object: _203.EnumOptionsAmino): _203.EnumOptions;
            toAmino(message: _203.EnumOptions): _203.EnumOptionsAmino;
            fromAminoMsg(object: _203.EnumOptionsAminoMsg): _203.EnumOptions;
            fromProtoMsg(message: _203.EnumOptionsProtoMsg): _203.EnumOptions;
            toProto(message: _203.EnumOptions): Uint8Array;
            toProtoMsg(message: _203.EnumOptions): _203.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _203.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.EnumValueOptions;
            fromPartial(object: Partial<_203.EnumValueOptions>): _203.EnumValueOptions;
            fromAmino(object: _203.EnumValueOptionsAmino): _203.EnumValueOptions;
            toAmino(message: _203.EnumValueOptions): _203.EnumValueOptionsAmino;
            fromAminoMsg(object: _203.EnumValueOptionsAminoMsg): _203.EnumValueOptions;
            fromProtoMsg(message: _203.EnumValueOptionsProtoMsg): _203.EnumValueOptions;
            toProto(message: _203.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _203.EnumValueOptions): _203.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _203.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.ServiceOptions;
            fromPartial(object: Partial<_203.ServiceOptions>): _203.ServiceOptions;
            fromAmino(object: _203.ServiceOptionsAmino): _203.ServiceOptions;
            toAmino(message: _203.ServiceOptions): _203.ServiceOptionsAmino;
            fromAminoMsg(object: _203.ServiceOptionsAminoMsg): _203.ServiceOptions;
            fromProtoMsg(message: _203.ServiceOptionsProtoMsg): _203.ServiceOptions;
            toProto(message: _203.ServiceOptions): Uint8Array;
            toProtoMsg(message: _203.ServiceOptions): _203.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _203.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.MethodOptions;
            fromPartial(object: Partial<_203.MethodOptions>): _203.MethodOptions;
            fromAmino(object: _203.MethodOptionsAmino): _203.MethodOptions;
            toAmino(message: _203.MethodOptions): _203.MethodOptionsAmino;
            fromAminoMsg(object: _203.MethodOptionsAminoMsg): _203.MethodOptions;
            fromProtoMsg(message: _203.MethodOptionsProtoMsg): _203.MethodOptions;
            toProto(message: _203.MethodOptions): Uint8Array;
            toProtoMsg(message: _203.MethodOptions): _203.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _203.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.UninterpretedOption;
            fromPartial(object: Partial<_203.UninterpretedOption>): _203.UninterpretedOption;
            fromAmino(object: _203.UninterpretedOptionAmino): _203.UninterpretedOption;
            toAmino(message: _203.UninterpretedOption): _203.UninterpretedOptionAmino;
            fromAminoMsg(object: _203.UninterpretedOptionAminoMsg): _203.UninterpretedOption;
            fromProtoMsg(message: _203.UninterpretedOptionProtoMsg): _203.UninterpretedOption;
            toProto(message: _203.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _203.UninterpretedOption): _203.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _203.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_203.UninterpretedOption_NamePart>): _203.UninterpretedOption_NamePart;
            fromAmino(object: _203.UninterpretedOption_NamePartAmino): _203.UninterpretedOption_NamePart;
            toAmino(message: _203.UninterpretedOption_NamePart): _203.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _203.UninterpretedOption_NamePartAminoMsg): _203.UninterpretedOption_NamePart;
            fromProtoMsg(message: _203.UninterpretedOption_NamePartProtoMsg): _203.UninterpretedOption_NamePart;
            toProto(message: _203.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _203.UninterpretedOption_NamePart): _203.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _203.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.SourceCodeInfo;
            fromPartial(object: Partial<_203.SourceCodeInfo>): _203.SourceCodeInfo;
            fromAmino(object: _203.SourceCodeInfoAmino): _203.SourceCodeInfo;
            toAmino(message: _203.SourceCodeInfo): _203.SourceCodeInfoAmino;
            fromAminoMsg(object: _203.SourceCodeInfoAminoMsg): _203.SourceCodeInfo;
            fromProtoMsg(message: _203.SourceCodeInfoProtoMsg): _203.SourceCodeInfo;
            toProto(message: _203.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _203.SourceCodeInfo): _203.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _203.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.SourceCodeInfo_Location;
            fromPartial(object: Partial<_203.SourceCodeInfo_Location>): _203.SourceCodeInfo_Location;
            fromAmino(object: _203.SourceCodeInfo_LocationAmino): _203.SourceCodeInfo_Location;
            toAmino(message: _203.SourceCodeInfo_Location): _203.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _203.SourceCodeInfo_LocationAminoMsg): _203.SourceCodeInfo_Location;
            fromProtoMsg(message: _203.SourceCodeInfo_LocationProtoMsg): _203.SourceCodeInfo_Location;
            toProto(message: _203.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _203.SourceCodeInfo_Location): _203.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _203.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.GeneratedCodeInfo;
            fromPartial(object: Partial<_203.GeneratedCodeInfo>): _203.GeneratedCodeInfo;
            fromAmino(object: _203.GeneratedCodeInfoAmino): _203.GeneratedCodeInfo;
            toAmino(message: _203.GeneratedCodeInfo): _203.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _203.GeneratedCodeInfoAminoMsg): _203.GeneratedCodeInfo;
            fromProtoMsg(message: _203.GeneratedCodeInfoProtoMsg): _203.GeneratedCodeInfo;
            toProto(message: _203.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _203.GeneratedCodeInfo): _203.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _203.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _203.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_203.GeneratedCodeInfo_Annotation>): _203.GeneratedCodeInfo_Annotation;
            fromAmino(object: _203.GeneratedCodeInfo_AnnotationAmino): _203.GeneratedCodeInfo_Annotation;
            toAmino(message: _203.GeneratedCodeInfo_Annotation): _203.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _203.GeneratedCodeInfo_AnnotationAminoMsg): _203.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _203.GeneratedCodeInfo_AnnotationProtoMsg): _203.GeneratedCodeInfo_Annotation;
            toProto(message: _203.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _203.GeneratedCodeInfo_Annotation): _203.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _202.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _202.Any;
            fromPartial(object: Partial<_202.Any>): _202.Any;
            fromAmino(object: _202.AnyAmino): _202.Any;
            toAmino(message: _202.Any): _202.AnyAmino;
            fromAminoMsg(object: _202.AnyAminoMsg): _202.Any;
            fromProtoMsg(message: _202.AnyProtoMsg): _202.Any;
            toProto(message: _202.Any): Uint8Array;
            toProtoMsg(message: _202.Any): _202.AnyProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _201.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _201.Timestamp;
            fromPartial(object: Partial<_201.Timestamp>): _201.Timestamp;
            fromAmino(object: string): _201.Timestamp;
            toAmino(message: _201.Timestamp): string;
            fromAminoMsg(object: _201.TimestampAminoMsg): _201.Timestamp;
            fromProtoMsg(message: _201.TimestampProtoMsg): _201.Timestamp;
            toProto(message: _201.Timestamp): Uint8Array;
            toProtoMsg(message: _201.Timestamp): _201.TimestampProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _200.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _200.Duration;
            fromPartial(object: Partial<_200.Duration>): _200.Duration;
            fromAmino(object: string): _200.Duration;
            toAmino(message: _200.Duration): string;
            fromAminoMsg(object: _200.DurationAminoMsg): _200.Duration;
            fromProtoMsg(message: _200.DurationProtoMsg): _200.Duration;
            toProto(message: _200.Duration): Uint8Array;
            toProtoMsg(message: _200.Duration): _200.DurationProtoMsg;
        };
    };
}
