import * as _130 from "./api/http";
import * as _131 from "./protobuf/timestamp";
import * as _132 from "./protobuf/any";
import * as _133 from "./protobuf/descriptor";
import * as _134 from "./protobuf/duration";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _130.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _130.Http;
            fromPartial(object: Partial<_130.Http>): _130.Http;
            fromAmino(object: _130.HttpAmino): _130.Http;
            toAmino(message: _130.Http): _130.HttpAmino;
            fromAminoMsg(object: _130.HttpAminoMsg): _130.Http;
            fromProtoMsg(message: _130.HttpProtoMsg): _130.Http;
            toProto(message: _130.Http): Uint8Array;
            toProtoMsg(message: _130.Http): _130.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _130.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _130.HttpRule;
            fromPartial(object: Partial<_130.HttpRule>): _130.HttpRule;
            fromAmino(object: _130.HttpRuleAmino): _130.HttpRule;
            toAmino(message: _130.HttpRule): _130.HttpRuleAmino;
            fromAminoMsg(object: _130.HttpRuleAminoMsg): _130.HttpRule;
            fromProtoMsg(message: _130.HttpRuleProtoMsg): _130.HttpRule;
            toProto(message: _130.HttpRule): Uint8Array;
            toProtoMsg(message: _130.HttpRule): _130.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _130.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _130.CustomHttpPattern;
            fromPartial(object: Partial<_130.CustomHttpPattern>): _130.CustomHttpPattern;
            fromAmino(object: _130.CustomHttpPatternAmino): _130.CustomHttpPattern;
            toAmino(message: _130.CustomHttpPattern): _130.CustomHttpPatternAmino;
            fromAminoMsg(object: _130.CustomHttpPatternAminoMsg): _130.CustomHttpPattern;
            fromProtoMsg(message: _130.CustomHttpPatternProtoMsg): _130.CustomHttpPattern;
            toProto(message: _130.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _130.CustomHttpPattern): _130.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Duration: {
            typeUrl: string;
            encode(message: _134.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _134.Duration;
            fromPartial(object: Partial<_134.Duration>): _134.Duration;
            fromAmino(object: string): _134.Duration;
            toAmino(message: _134.Duration): string;
            fromAminoMsg(object: _134.DurationAminoMsg): _134.Duration;
            fromProtoMsg(message: _134.DurationProtoMsg): _134.Duration;
            toProto(message: _134.Duration): Uint8Array;
            toProtoMsg(message: _134.Duration): _134.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _133.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _133.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _133.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _133.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _133.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _133.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _133.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _133.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _133.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _133.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _133.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _133.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _133.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _133.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _133.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _133.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _133.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _133.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _133.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _133.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _133.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _133.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _133.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _133.FieldOptions_CType;
        FieldOptions_JSType: typeof _133.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _133.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _133.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _133.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _133.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _133.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _133.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.FileDescriptorSet;
            fromPartial(object: Partial<_133.FileDescriptorSet>): _133.FileDescriptorSet;
            fromAmino(object: _133.FileDescriptorSetAmino): _133.FileDescriptorSet;
            toAmino(message: _133.FileDescriptorSet): _133.FileDescriptorSetAmino;
            fromAminoMsg(object: _133.FileDescriptorSetAminoMsg): _133.FileDescriptorSet;
            fromProtoMsg(message: _133.FileDescriptorSetProtoMsg): _133.FileDescriptorSet;
            toProto(message: _133.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _133.FileDescriptorSet): _133.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _133.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.FileDescriptorProto;
            fromPartial(object: Partial<_133.FileDescriptorProto>): _133.FileDescriptorProto;
            fromAmino(object: _133.FileDescriptorProtoAmino): _133.FileDescriptorProto;
            toAmino(message: _133.FileDescriptorProto): _133.FileDescriptorProtoAmino;
            fromAminoMsg(object: _133.FileDescriptorProtoAminoMsg): _133.FileDescriptorProto;
            fromProtoMsg(message: _133.FileDescriptorProtoProtoMsg): _133.FileDescriptorProto;
            toProto(message: _133.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _133.FileDescriptorProto): _133.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _133.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.DescriptorProto;
            fromPartial(object: Partial<_133.DescriptorProto>): _133.DescriptorProto;
            fromAmino(object: _133.DescriptorProtoAmino): _133.DescriptorProto;
            toAmino(message: _133.DescriptorProto): _133.DescriptorProtoAmino;
            fromAminoMsg(object: _133.DescriptorProtoAminoMsg): _133.DescriptorProto;
            fromProtoMsg(message: _133.DescriptorProtoProtoMsg): _133.DescriptorProto;
            toProto(message: _133.DescriptorProto): Uint8Array;
            toProtoMsg(message: _133.DescriptorProto): _133.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _133.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_133.DescriptorProto_ExtensionRange>): _133.DescriptorProto_ExtensionRange;
            fromAmino(object: _133.DescriptorProto_ExtensionRangeAmino): _133.DescriptorProto_ExtensionRange;
            toAmino(message: _133.DescriptorProto_ExtensionRange): _133.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _133.DescriptorProto_ExtensionRangeAminoMsg): _133.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _133.DescriptorProto_ExtensionRangeProtoMsg): _133.DescriptorProto_ExtensionRange;
            toProto(message: _133.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _133.DescriptorProto_ExtensionRange): _133.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _133.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_133.DescriptorProto_ReservedRange>): _133.DescriptorProto_ReservedRange;
            fromAmino(object: _133.DescriptorProto_ReservedRangeAmino): _133.DescriptorProto_ReservedRange;
            toAmino(message: _133.DescriptorProto_ReservedRange): _133.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _133.DescriptorProto_ReservedRangeAminoMsg): _133.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _133.DescriptorProto_ReservedRangeProtoMsg): _133.DescriptorProto_ReservedRange;
            toProto(message: _133.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _133.DescriptorProto_ReservedRange): _133.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _133.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ExtensionRangeOptions;
            fromPartial(object: Partial<_133.ExtensionRangeOptions>): _133.ExtensionRangeOptions;
            fromAmino(object: _133.ExtensionRangeOptionsAmino): _133.ExtensionRangeOptions;
            toAmino(message: _133.ExtensionRangeOptions): _133.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _133.ExtensionRangeOptionsAminoMsg): _133.ExtensionRangeOptions;
            fromProtoMsg(message: _133.ExtensionRangeOptionsProtoMsg): _133.ExtensionRangeOptions;
            toProto(message: _133.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _133.ExtensionRangeOptions): _133.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _133.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.FieldDescriptorProto;
            fromPartial(object: Partial<_133.FieldDescriptorProto>): _133.FieldDescriptorProto;
            fromAmino(object: _133.FieldDescriptorProtoAmino): _133.FieldDescriptorProto;
            toAmino(message: _133.FieldDescriptorProto): _133.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _133.FieldDescriptorProtoAminoMsg): _133.FieldDescriptorProto;
            fromProtoMsg(message: _133.FieldDescriptorProtoProtoMsg): _133.FieldDescriptorProto;
            toProto(message: _133.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _133.FieldDescriptorProto): _133.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _133.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.OneofDescriptorProto;
            fromPartial(object: Partial<_133.OneofDescriptorProto>): _133.OneofDescriptorProto;
            fromAmino(object: _133.OneofDescriptorProtoAmino): _133.OneofDescriptorProto;
            toAmino(message: _133.OneofDescriptorProto): _133.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _133.OneofDescriptorProtoAminoMsg): _133.OneofDescriptorProto;
            fromProtoMsg(message: _133.OneofDescriptorProtoProtoMsg): _133.OneofDescriptorProto;
            toProto(message: _133.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _133.OneofDescriptorProto): _133.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _133.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.EnumDescriptorProto;
            fromPartial(object: Partial<_133.EnumDescriptorProto>): _133.EnumDescriptorProto;
            fromAmino(object: _133.EnumDescriptorProtoAmino): _133.EnumDescriptorProto;
            toAmino(message: _133.EnumDescriptorProto): _133.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _133.EnumDescriptorProtoAminoMsg): _133.EnumDescriptorProto;
            fromProtoMsg(message: _133.EnumDescriptorProtoProtoMsg): _133.EnumDescriptorProto;
            toProto(message: _133.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _133.EnumDescriptorProto): _133.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _133.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_133.EnumDescriptorProto_EnumReservedRange>): _133.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _133.EnumDescriptorProto_EnumReservedRangeAmino): _133.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _133.EnumDescriptorProto_EnumReservedRange): _133.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _133.EnumDescriptorProto_EnumReservedRangeAminoMsg): _133.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _133.EnumDescriptorProto_EnumReservedRangeProtoMsg): _133.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _133.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _133.EnumDescriptorProto_EnumReservedRange): _133.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _133.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.EnumValueDescriptorProto;
            fromPartial(object: Partial<_133.EnumValueDescriptorProto>): _133.EnumValueDescriptorProto;
            fromAmino(object: _133.EnumValueDescriptorProtoAmino): _133.EnumValueDescriptorProto;
            toAmino(message: _133.EnumValueDescriptorProto): _133.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _133.EnumValueDescriptorProtoAminoMsg): _133.EnumValueDescriptorProto;
            fromProtoMsg(message: _133.EnumValueDescriptorProtoProtoMsg): _133.EnumValueDescriptorProto;
            toProto(message: _133.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _133.EnumValueDescriptorProto): _133.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _133.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ServiceDescriptorProto;
            fromPartial(object: Partial<_133.ServiceDescriptorProto>): _133.ServiceDescriptorProto;
            fromAmino(object: _133.ServiceDescriptorProtoAmino): _133.ServiceDescriptorProto;
            toAmino(message: _133.ServiceDescriptorProto): _133.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _133.ServiceDescriptorProtoAminoMsg): _133.ServiceDescriptorProto;
            fromProtoMsg(message: _133.ServiceDescriptorProtoProtoMsg): _133.ServiceDescriptorProto;
            toProto(message: _133.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _133.ServiceDescriptorProto): _133.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _133.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.MethodDescriptorProto;
            fromPartial(object: Partial<_133.MethodDescriptorProto>): _133.MethodDescriptorProto;
            fromAmino(object: _133.MethodDescriptorProtoAmino): _133.MethodDescriptorProto;
            toAmino(message: _133.MethodDescriptorProto): _133.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _133.MethodDescriptorProtoAminoMsg): _133.MethodDescriptorProto;
            fromProtoMsg(message: _133.MethodDescriptorProtoProtoMsg): _133.MethodDescriptorProto;
            toProto(message: _133.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _133.MethodDescriptorProto): _133.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _133.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.FileOptions;
            fromPartial(object: Partial<_133.FileOptions>): _133.FileOptions;
            fromAmino(object: _133.FileOptionsAmino): _133.FileOptions;
            toAmino(message: _133.FileOptions): _133.FileOptionsAmino;
            fromAminoMsg(object: _133.FileOptionsAminoMsg): _133.FileOptions;
            fromProtoMsg(message: _133.FileOptionsProtoMsg): _133.FileOptions;
            toProto(message: _133.FileOptions): Uint8Array;
            toProtoMsg(message: _133.FileOptions): _133.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _133.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.MessageOptions;
            fromPartial(object: Partial<_133.MessageOptions>): _133.MessageOptions;
            fromAmino(object: _133.MessageOptionsAmino): _133.MessageOptions;
            toAmino(message: _133.MessageOptions): _133.MessageOptionsAmino;
            fromAminoMsg(object: _133.MessageOptionsAminoMsg): _133.MessageOptions;
            fromProtoMsg(message: _133.MessageOptionsProtoMsg): _133.MessageOptions;
            toProto(message: _133.MessageOptions): Uint8Array;
            toProtoMsg(message: _133.MessageOptions): _133.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _133.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.FieldOptions;
            fromPartial(object: Partial<_133.FieldOptions>): _133.FieldOptions;
            fromAmino(object: _133.FieldOptionsAmino): _133.FieldOptions;
            toAmino(message: _133.FieldOptions): _133.FieldOptionsAmino;
            fromAminoMsg(object: _133.FieldOptionsAminoMsg): _133.FieldOptions;
            fromProtoMsg(message: _133.FieldOptionsProtoMsg): _133.FieldOptions;
            toProto(message: _133.FieldOptions): Uint8Array;
            toProtoMsg(message: _133.FieldOptions): _133.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _133.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.OneofOptions;
            fromPartial(object: Partial<_133.OneofOptions>): _133.OneofOptions;
            fromAmino(object: _133.OneofOptionsAmino): _133.OneofOptions;
            toAmino(message: _133.OneofOptions): _133.OneofOptionsAmino;
            fromAminoMsg(object: _133.OneofOptionsAminoMsg): _133.OneofOptions;
            fromProtoMsg(message: _133.OneofOptionsProtoMsg): _133.OneofOptions;
            toProto(message: _133.OneofOptions): Uint8Array;
            toProtoMsg(message: _133.OneofOptions): _133.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _133.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.EnumOptions;
            fromPartial(object: Partial<_133.EnumOptions>): _133.EnumOptions;
            fromAmino(object: _133.EnumOptionsAmino): _133.EnumOptions;
            toAmino(message: _133.EnumOptions): _133.EnumOptionsAmino;
            fromAminoMsg(object: _133.EnumOptionsAminoMsg): _133.EnumOptions;
            fromProtoMsg(message: _133.EnumOptionsProtoMsg): _133.EnumOptions;
            toProto(message: _133.EnumOptions): Uint8Array;
            toProtoMsg(message: _133.EnumOptions): _133.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _133.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.EnumValueOptions;
            fromPartial(object: Partial<_133.EnumValueOptions>): _133.EnumValueOptions;
            fromAmino(object: _133.EnumValueOptionsAmino): _133.EnumValueOptions;
            toAmino(message: _133.EnumValueOptions): _133.EnumValueOptionsAmino;
            fromAminoMsg(object: _133.EnumValueOptionsAminoMsg): _133.EnumValueOptions;
            fromProtoMsg(message: _133.EnumValueOptionsProtoMsg): _133.EnumValueOptions;
            toProto(message: _133.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _133.EnumValueOptions): _133.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _133.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.ServiceOptions;
            fromPartial(object: Partial<_133.ServiceOptions>): _133.ServiceOptions;
            fromAmino(object: _133.ServiceOptionsAmino): _133.ServiceOptions;
            toAmino(message: _133.ServiceOptions): _133.ServiceOptionsAmino;
            fromAminoMsg(object: _133.ServiceOptionsAminoMsg): _133.ServiceOptions;
            fromProtoMsg(message: _133.ServiceOptionsProtoMsg): _133.ServiceOptions;
            toProto(message: _133.ServiceOptions): Uint8Array;
            toProtoMsg(message: _133.ServiceOptions): _133.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _133.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.MethodOptions;
            fromPartial(object: Partial<_133.MethodOptions>): _133.MethodOptions;
            fromAmino(object: _133.MethodOptionsAmino): _133.MethodOptions;
            toAmino(message: _133.MethodOptions): _133.MethodOptionsAmino;
            fromAminoMsg(object: _133.MethodOptionsAminoMsg): _133.MethodOptions;
            fromProtoMsg(message: _133.MethodOptionsProtoMsg): _133.MethodOptions;
            toProto(message: _133.MethodOptions): Uint8Array;
            toProtoMsg(message: _133.MethodOptions): _133.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _133.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.UninterpretedOption;
            fromPartial(object: Partial<_133.UninterpretedOption>): _133.UninterpretedOption;
            fromAmino(object: _133.UninterpretedOptionAmino): _133.UninterpretedOption;
            toAmino(message: _133.UninterpretedOption): _133.UninterpretedOptionAmino;
            fromAminoMsg(object: _133.UninterpretedOptionAminoMsg): _133.UninterpretedOption;
            fromProtoMsg(message: _133.UninterpretedOptionProtoMsg): _133.UninterpretedOption;
            toProto(message: _133.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _133.UninterpretedOption): _133.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _133.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_133.UninterpretedOption_NamePart>): _133.UninterpretedOption_NamePart;
            fromAmino(object: _133.UninterpretedOption_NamePartAmino): _133.UninterpretedOption_NamePart;
            toAmino(message: _133.UninterpretedOption_NamePart): _133.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _133.UninterpretedOption_NamePartAminoMsg): _133.UninterpretedOption_NamePart;
            fromProtoMsg(message: _133.UninterpretedOption_NamePartProtoMsg): _133.UninterpretedOption_NamePart;
            toProto(message: _133.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _133.UninterpretedOption_NamePart): _133.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _133.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.SourceCodeInfo;
            fromPartial(object: Partial<_133.SourceCodeInfo>): _133.SourceCodeInfo;
            fromAmino(object: _133.SourceCodeInfoAmino): _133.SourceCodeInfo;
            toAmino(message: _133.SourceCodeInfo): _133.SourceCodeInfoAmino;
            fromAminoMsg(object: _133.SourceCodeInfoAminoMsg): _133.SourceCodeInfo;
            fromProtoMsg(message: _133.SourceCodeInfoProtoMsg): _133.SourceCodeInfo;
            toProto(message: _133.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _133.SourceCodeInfo): _133.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _133.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.SourceCodeInfo_Location;
            fromPartial(object: Partial<_133.SourceCodeInfo_Location>): _133.SourceCodeInfo_Location;
            fromAmino(object: _133.SourceCodeInfo_LocationAmino): _133.SourceCodeInfo_Location;
            toAmino(message: _133.SourceCodeInfo_Location): _133.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _133.SourceCodeInfo_LocationAminoMsg): _133.SourceCodeInfo_Location;
            fromProtoMsg(message: _133.SourceCodeInfo_LocationProtoMsg): _133.SourceCodeInfo_Location;
            toProto(message: _133.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _133.SourceCodeInfo_Location): _133.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _133.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.GeneratedCodeInfo;
            fromPartial(object: Partial<_133.GeneratedCodeInfo>): _133.GeneratedCodeInfo;
            fromAmino(object: _133.GeneratedCodeInfoAmino): _133.GeneratedCodeInfo;
            toAmino(message: _133.GeneratedCodeInfo): _133.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _133.GeneratedCodeInfoAminoMsg): _133.GeneratedCodeInfo;
            fromProtoMsg(message: _133.GeneratedCodeInfoProtoMsg): _133.GeneratedCodeInfo;
            toProto(message: _133.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _133.GeneratedCodeInfo): _133.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _133.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _133.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_133.GeneratedCodeInfo_Annotation>): _133.GeneratedCodeInfo_Annotation;
            fromAmino(object: _133.GeneratedCodeInfo_AnnotationAmino): _133.GeneratedCodeInfo_Annotation;
            toAmino(message: _133.GeneratedCodeInfo_Annotation): _133.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _133.GeneratedCodeInfo_AnnotationAminoMsg): _133.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _133.GeneratedCodeInfo_AnnotationProtoMsg): _133.GeneratedCodeInfo_Annotation;
            toProto(message: _133.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _133.GeneratedCodeInfo_Annotation): _133.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _132.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _132.Any;
            fromPartial(object: Partial<_132.Any>): _132.Any;
            fromAmino(object: _132.AnyAmino): _132.Any;
            toAmino(message: _132.Any): _132.AnyAmino;
            fromAminoMsg(object: _132.AnyAminoMsg): _132.Any;
            fromProtoMsg(message: _132.AnyProtoMsg): _132.Any;
            toProto(message: _132.Any): Uint8Array;
            toProtoMsg(message: _132.Any): _132.AnyProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _131.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _131.Timestamp;
            fromPartial(object: Partial<_131.Timestamp>): _131.Timestamp;
            fromAmino(object: string): _131.Timestamp;
            toAmino(message: _131.Timestamp): string;
            fromAminoMsg(object: _131.TimestampAminoMsg): _131.Timestamp;
            fromProtoMsg(message: _131.TimestampProtoMsg): _131.Timestamp;
            toProto(message: _131.Timestamp): Uint8Array;
            toProtoMsg(message: _131.Timestamp): _131.TimestampProtoMsg;
        };
    };
}
