import * as _107 from "./abci/types";
import * as _108 from "./crypto/keys";
import * as _109 from "./crypto/proof";
import * as _110 from "./libs/bits/types";
import * as _111 from "./p2p/types";
import * as _112 from "./types/block";
import * as _113 from "./types/evidence";
import * as _114 from "./types/params";
import * as _115 from "./types/types";
import * as _116 from "./types/validator";
import * as _117 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _107.CheckTxType;
        checkTxTypeToJSON(object: _107.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _107.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _107.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _107.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _107.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _107.EvidenceType;
        evidenceTypeToJSON(object: _107.EvidenceType): string;
        CheckTxType: typeof _107.CheckTxType;
        CheckTxTypeSDKType: typeof _107.CheckTxType;
        CheckTxTypeAmino: typeof _107.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _107.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _107.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _107.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _107.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _107.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _107.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _107.EvidenceType;
        EvidenceTypeSDKType: typeof _107.EvidenceType;
        EvidenceTypeAmino: typeof _107.EvidenceType;
        Request: {
            typeUrl: string;
            encode(message: _107.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.Request;
            fromPartial(object: Partial<_107.Request>): _107.Request;
            fromAmino(object: _107.RequestAmino): _107.Request;
            toAmino(message: _107.Request): _107.RequestAmino;
            fromAminoMsg(object: _107.RequestAminoMsg): _107.Request;
            fromProtoMsg(message: _107.RequestProtoMsg): _107.Request;
            toProto(message: _107.Request): Uint8Array;
            toProtoMsg(message: _107.Request): _107.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _107.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.RequestEcho;
            fromPartial(object: Partial<_107.RequestEcho>): _107.RequestEcho;
            fromAmino(object: _107.RequestEchoAmino): _107.RequestEcho;
            toAmino(message: _107.RequestEcho): _107.RequestEchoAmino;
            fromAminoMsg(object: _107.RequestEchoAminoMsg): _107.RequestEcho;
            fromProtoMsg(message: _107.RequestEchoProtoMsg): _107.RequestEcho;
            toProto(message: _107.RequestEcho): Uint8Array;
            toProtoMsg(message: _107.RequestEcho): _107.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _107.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _107.RequestFlush;
            fromPartial(_: Partial<_107.RequestFlush>): _107.RequestFlush;
            fromAmino(_: _107.RequestFlushAmino): _107.RequestFlush;
            toAmino(_: _107.RequestFlush): _107.RequestFlushAmino;
            fromAminoMsg(object: _107.RequestFlushAminoMsg): _107.RequestFlush;
            fromProtoMsg(message: _107.RequestFlushProtoMsg): _107.RequestFlush;
            toProto(message: _107.RequestFlush): Uint8Array;
            toProtoMsg(message: _107.RequestFlush): _107.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _107.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.RequestInfo;
            fromPartial(object: Partial<_107.RequestInfo>): _107.RequestInfo;
            fromAmino(object: _107.RequestInfoAmino): _107.RequestInfo;
            toAmino(message: _107.RequestInfo): _107.RequestInfoAmino;
            fromAminoMsg(object: _107.RequestInfoAminoMsg): _107.RequestInfo;
            fromProtoMsg(message: _107.RequestInfoProtoMsg): _107.RequestInfo;
            toProto(message: _107.RequestInfo): Uint8Array;
            toProtoMsg(message: _107.RequestInfo): _107.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            typeUrl: string;
            encode(message: _107.RequestSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.RequestSetOption;
            fromPartial(object: Partial<_107.RequestSetOption>): _107.RequestSetOption;
            fromAmino(object: _107.RequestSetOptionAmino): _107.RequestSetOption;
            toAmino(message: _107.RequestSetOption): _107.RequestSetOptionAmino;
            fromAminoMsg(object: _107.RequestSetOptionAminoMsg): _107.RequestSetOption;
            fromProtoMsg(message: _107.RequestSetOptionProtoMsg): _107.RequestSetOption;
            toProto(message: _107.RequestSetOption): Uint8Array;
            toProtoMsg(message: _107.RequestSetOption): _107.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _107.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.RequestInitChain;
            fromPartial(object: Partial<_107.RequestInitChain>): _107.RequestInitChain;
            fromAmino(object: _107.RequestInitChainAmino): _107.RequestInitChain;
            toAmino(message: _107.RequestInitChain): _107.RequestInitChainAmino;
            fromAminoMsg(object: _107.RequestInitChainAminoMsg): _107.RequestInitChain;
            fromProtoMsg(message: _107.RequestInitChainProtoMsg): _107.RequestInitChain;
            toProto(message: _107.RequestInitChain): Uint8Array;
            toProtoMsg(message: _107.RequestInitChain): _107.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _107.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.RequestQuery;
            fromPartial(object: Partial<_107.RequestQuery>): _107.RequestQuery;
            fromAmino(object: _107.RequestQueryAmino): _107.RequestQuery;
            toAmino(message: _107.RequestQuery): _107.RequestQueryAmino;
            fromAminoMsg(object: _107.RequestQueryAminoMsg): _107.RequestQuery;
            fromProtoMsg(message: _107.RequestQueryProtoMsg): _107.RequestQuery;
            toProto(message: _107.RequestQuery): Uint8Array;
            toProtoMsg(message: _107.RequestQuery): _107.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _107.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.RequestBeginBlock;
            fromPartial(object: Partial<_107.RequestBeginBlock>): _107.RequestBeginBlock;
            fromAmino(object: _107.RequestBeginBlockAmino): _107.RequestBeginBlock;
            toAmino(message: _107.RequestBeginBlock): _107.RequestBeginBlockAmino;
            fromAminoMsg(object: _107.RequestBeginBlockAminoMsg): _107.RequestBeginBlock;
            fromProtoMsg(message: _107.RequestBeginBlockProtoMsg): _107.RequestBeginBlock;
            toProto(message: _107.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _107.RequestBeginBlock): _107.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _107.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.RequestCheckTx;
            fromPartial(object: Partial<_107.RequestCheckTx>): _107.RequestCheckTx;
            fromAmino(object: _107.RequestCheckTxAmino): _107.RequestCheckTx;
            toAmino(message: _107.RequestCheckTx): _107.RequestCheckTxAmino;
            fromAminoMsg(object: _107.RequestCheckTxAminoMsg): _107.RequestCheckTx;
            fromProtoMsg(message: _107.RequestCheckTxProtoMsg): _107.RequestCheckTx;
            toProto(message: _107.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _107.RequestCheckTx): _107.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _107.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.RequestDeliverTx;
            fromPartial(object: Partial<_107.RequestDeliverTx>): _107.RequestDeliverTx;
            fromAmino(object: _107.RequestDeliverTxAmino): _107.RequestDeliverTx;
            toAmino(message: _107.RequestDeliverTx): _107.RequestDeliverTxAmino;
            fromAminoMsg(object: _107.RequestDeliverTxAminoMsg): _107.RequestDeliverTx;
            fromProtoMsg(message: _107.RequestDeliverTxProtoMsg): _107.RequestDeliverTx;
            toProto(message: _107.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _107.RequestDeliverTx): _107.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _107.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.RequestEndBlock;
            fromPartial(object: Partial<_107.RequestEndBlock>): _107.RequestEndBlock;
            fromAmino(object: _107.RequestEndBlockAmino): _107.RequestEndBlock;
            toAmino(message: _107.RequestEndBlock): _107.RequestEndBlockAmino;
            fromAminoMsg(object: _107.RequestEndBlockAminoMsg): _107.RequestEndBlock;
            fromProtoMsg(message: _107.RequestEndBlockProtoMsg): _107.RequestEndBlock;
            toProto(message: _107.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _107.RequestEndBlock): _107.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _107.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _107.RequestCommit;
            fromPartial(_: Partial<_107.RequestCommit>): _107.RequestCommit;
            fromAmino(_: _107.RequestCommitAmino): _107.RequestCommit;
            toAmino(_: _107.RequestCommit): _107.RequestCommitAmino;
            fromAminoMsg(object: _107.RequestCommitAminoMsg): _107.RequestCommit;
            fromProtoMsg(message: _107.RequestCommitProtoMsg): _107.RequestCommit;
            toProto(message: _107.RequestCommit): Uint8Array;
            toProtoMsg(message: _107.RequestCommit): _107.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _107.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _107.RequestListSnapshots;
            fromPartial(_: Partial<_107.RequestListSnapshots>): _107.RequestListSnapshots;
            fromAmino(_: _107.RequestListSnapshotsAmino): _107.RequestListSnapshots;
            toAmino(_: _107.RequestListSnapshots): _107.RequestListSnapshotsAmino;
            fromAminoMsg(object: _107.RequestListSnapshotsAminoMsg): _107.RequestListSnapshots;
            fromProtoMsg(message: _107.RequestListSnapshotsProtoMsg): _107.RequestListSnapshots;
            toProto(message: _107.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _107.RequestListSnapshots): _107.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _107.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.RequestOfferSnapshot;
            fromPartial(object: Partial<_107.RequestOfferSnapshot>): _107.RequestOfferSnapshot;
            fromAmino(object: _107.RequestOfferSnapshotAmino): _107.RequestOfferSnapshot;
            toAmino(message: _107.RequestOfferSnapshot): _107.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _107.RequestOfferSnapshotAminoMsg): _107.RequestOfferSnapshot;
            fromProtoMsg(message: _107.RequestOfferSnapshotProtoMsg): _107.RequestOfferSnapshot;
            toProto(message: _107.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _107.RequestOfferSnapshot): _107.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _107.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_107.RequestLoadSnapshotChunk>): _107.RequestLoadSnapshotChunk;
            fromAmino(object: _107.RequestLoadSnapshotChunkAmino): _107.RequestLoadSnapshotChunk;
            toAmino(message: _107.RequestLoadSnapshotChunk): _107.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _107.RequestLoadSnapshotChunkAminoMsg): _107.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _107.RequestLoadSnapshotChunkProtoMsg): _107.RequestLoadSnapshotChunk;
            toProto(message: _107.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _107.RequestLoadSnapshotChunk): _107.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _107.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_107.RequestApplySnapshotChunk>): _107.RequestApplySnapshotChunk;
            fromAmino(object: _107.RequestApplySnapshotChunkAmino): _107.RequestApplySnapshotChunk;
            toAmino(message: _107.RequestApplySnapshotChunk): _107.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _107.RequestApplySnapshotChunkAminoMsg): _107.RequestApplySnapshotChunk;
            fromProtoMsg(message: _107.RequestApplySnapshotChunkProtoMsg): _107.RequestApplySnapshotChunk;
            toProto(message: _107.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _107.RequestApplySnapshotChunk): _107.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _107.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.Response;
            fromPartial(object: Partial<_107.Response>): _107.Response;
            fromAmino(object: _107.ResponseAmino): _107.Response;
            toAmino(message: _107.Response): _107.ResponseAmino;
            fromAminoMsg(object: _107.ResponseAminoMsg): _107.Response;
            fromProtoMsg(message: _107.ResponseProtoMsg): _107.Response;
            toProto(message: _107.Response): Uint8Array;
            toProtoMsg(message: _107.Response): _107.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _107.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseException;
            fromPartial(object: Partial<_107.ResponseException>): _107.ResponseException;
            fromAmino(object: _107.ResponseExceptionAmino): _107.ResponseException;
            toAmino(message: _107.ResponseException): _107.ResponseExceptionAmino;
            fromAminoMsg(object: _107.ResponseExceptionAminoMsg): _107.ResponseException;
            fromProtoMsg(message: _107.ResponseExceptionProtoMsg): _107.ResponseException;
            toProto(message: _107.ResponseException): Uint8Array;
            toProtoMsg(message: _107.ResponseException): _107.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _107.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseEcho;
            fromPartial(object: Partial<_107.ResponseEcho>): _107.ResponseEcho;
            fromAmino(object: _107.ResponseEchoAmino): _107.ResponseEcho;
            toAmino(message: _107.ResponseEcho): _107.ResponseEchoAmino;
            fromAminoMsg(object: _107.ResponseEchoAminoMsg): _107.ResponseEcho;
            fromProtoMsg(message: _107.ResponseEchoProtoMsg): _107.ResponseEcho;
            toProto(message: _107.ResponseEcho): Uint8Array;
            toProtoMsg(message: _107.ResponseEcho): _107.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _107.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _107.ResponseFlush;
            fromPartial(_: Partial<_107.ResponseFlush>): _107.ResponseFlush;
            fromAmino(_: _107.ResponseFlushAmino): _107.ResponseFlush;
            toAmino(_: _107.ResponseFlush): _107.ResponseFlushAmino;
            fromAminoMsg(object: _107.ResponseFlushAminoMsg): _107.ResponseFlush;
            fromProtoMsg(message: _107.ResponseFlushProtoMsg): _107.ResponseFlush;
            toProto(message: _107.ResponseFlush): Uint8Array;
            toProtoMsg(message: _107.ResponseFlush): _107.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _107.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseInfo;
            fromPartial(object: Partial<_107.ResponseInfo>): _107.ResponseInfo;
            fromAmino(object: _107.ResponseInfoAmino): _107.ResponseInfo;
            toAmino(message: _107.ResponseInfo): _107.ResponseInfoAmino;
            fromAminoMsg(object: _107.ResponseInfoAminoMsg): _107.ResponseInfo;
            fromProtoMsg(message: _107.ResponseInfoProtoMsg): _107.ResponseInfo;
            toProto(message: _107.ResponseInfo): Uint8Array;
            toProtoMsg(message: _107.ResponseInfo): _107.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            typeUrl: string;
            encode(message: _107.ResponseSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseSetOption;
            fromPartial(object: Partial<_107.ResponseSetOption>): _107.ResponseSetOption;
            fromAmino(object: _107.ResponseSetOptionAmino): _107.ResponseSetOption;
            toAmino(message: _107.ResponseSetOption): _107.ResponseSetOptionAmino;
            fromAminoMsg(object: _107.ResponseSetOptionAminoMsg): _107.ResponseSetOption;
            fromProtoMsg(message: _107.ResponseSetOptionProtoMsg): _107.ResponseSetOption;
            toProto(message: _107.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _107.ResponseSetOption): _107.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _107.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseInitChain;
            fromPartial(object: Partial<_107.ResponseInitChain>): _107.ResponseInitChain;
            fromAmino(object: _107.ResponseInitChainAmino): _107.ResponseInitChain;
            toAmino(message: _107.ResponseInitChain): _107.ResponseInitChainAmino;
            fromAminoMsg(object: _107.ResponseInitChainAminoMsg): _107.ResponseInitChain;
            fromProtoMsg(message: _107.ResponseInitChainProtoMsg): _107.ResponseInitChain;
            toProto(message: _107.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _107.ResponseInitChain): _107.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _107.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseQuery;
            fromPartial(object: Partial<_107.ResponseQuery>): _107.ResponseQuery;
            fromAmino(object: _107.ResponseQueryAmino): _107.ResponseQuery;
            toAmino(message: _107.ResponseQuery): _107.ResponseQueryAmino;
            fromAminoMsg(object: _107.ResponseQueryAminoMsg): _107.ResponseQuery;
            fromProtoMsg(message: _107.ResponseQueryProtoMsg): _107.ResponseQuery;
            toProto(message: _107.ResponseQuery): Uint8Array;
            toProtoMsg(message: _107.ResponseQuery): _107.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _107.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseBeginBlock;
            fromPartial(object: Partial<_107.ResponseBeginBlock>): _107.ResponseBeginBlock;
            fromAmino(object: _107.ResponseBeginBlockAmino): _107.ResponseBeginBlock;
            toAmino(message: _107.ResponseBeginBlock): _107.ResponseBeginBlockAmino;
            fromAminoMsg(object: _107.ResponseBeginBlockAminoMsg): _107.ResponseBeginBlock;
            fromProtoMsg(message: _107.ResponseBeginBlockProtoMsg): _107.ResponseBeginBlock;
            toProto(message: _107.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _107.ResponseBeginBlock): _107.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _107.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseCheckTx;
            fromPartial(object: Partial<_107.ResponseCheckTx>): _107.ResponseCheckTx;
            fromAmino(object: _107.ResponseCheckTxAmino): _107.ResponseCheckTx;
            toAmino(message: _107.ResponseCheckTx): _107.ResponseCheckTxAmino;
            fromAminoMsg(object: _107.ResponseCheckTxAminoMsg): _107.ResponseCheckTx;
            fromProtoMsg(message: _107.ResponseCheckTxProtoMsg): _107.ResponseCheckTx;
            toProto(message: _107.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _107.ResponseCheckTx): _107.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _107.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseDeliverTx;
            fromPartial(object: Partial<_107.ResponseDeliverTx>): _107.ResponseDeliverTx;
            fromAmino(object: _107.ResponseDeliverTxAmino): _107.ResponseDeliverTx;
            toAmino(message: _107.ResponseDeliverTx): _107.ResponseDeliverTxAmino;
            fromAminoMsg(object: _107.ResponseDeliverTxAminoMsg): _107.ResponseDeliverTx;
            fromProtoMsg(message: _107.ResponseDeliverTxProtoMsg): _107.ResponseDeliverTx;
            toProto(message: _107.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _107.ResponseDeliverTx): _107.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _107.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseEndBlock;
            fromPartial(object: Partial<_107.ResponseEndBlock>): _107.ResponseEndBlock;
            fromAmino(object: _107.ResponseEndBlockAmino): _107.ResponseEndBlock;
            toAmino(message: _107.ResponseEndBlock): _107.ResponseEndBlockAmino;
            fromAminoMsg(object: _107.ResponseEndBlockAminoMsg): _107.ResponseEndBlock;
            fromProtoMsg(message: _107.ResponseEndBlockProtoMsg): _107.ResponseEndBlock;
            toProto(message: _107.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _107.ResponseEndBlock): _107.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _107.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseCommit;
            fromPartial(object: Partial<_107.ResponseCommit>): _107.ResponseCommit;
            fromAmino(object: _107.ResponseCommitAmino): _107.ResponseCommit;
            toAmino(message: _107.ResponseCommit): _107.ResponseCommitAmino;
            fromAminoMsg(object: _107.ResponseCommitAminoMsg): _107.ResponseCommit;
            fromProtoMsg(message: _107.ResponseCommitProtoMsg): _107.ResponseCommit;
            toProto(message: _107.ResponseCommit): Uint8Array;
            toProtoMsg(message: _107.ResponseCommit): _107.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _107.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseListSnapshots;
            fromPartial(object: Partial<_107.ResponseListSnapshots>): _107.ResponseListSnapshots;
            fromAmino(object: _107.ResponseListSnapshotsAmino): _107.ResponseListSnapshots;
            toAmino(message: _107.ResponseListSnapshots): _107.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _107.ResponseListSnapshotsAminoMsg): _107.ResponseListSnapshots;
            fromProtoMsg(message: _107.ResponseListSnapshotsProtoMsg): _107.ResponseListSnapshots;
            toProto(message: _107.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _107.ResponseListSnapshots): _107.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _107.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseOfferSnapshot;
            fromPartial(object: Partial<_107.ResponseOfferSnapshot>): _107.ResponseOfferSnapshot;
            fromAmino(object: _107.ResponseOfferSnapshotAmino): _107.ResponseOfferSnapshot;
            toAmino(message: _107.ResponseOfferSnapshot): _107.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _107.ResponseOfferSnapshotAminoMsg): _107.ResponseOfferSnapshot;
            fromProtoMsg(message: _107.ResponseOfferSnapshotProtoMsg): _107.ResponseOfferSnapshot;
            toProto(message: _107.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _107.ResponseOfferSnapshot): _107.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _107.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_107.ResponseLoadSnapshotChunk>): _107.ResponseLoadSnapshotChunk;
            fromAmino(object: _107.ResponseLoadSnapshotChunkAmino): _107.ResponseLoadSnapshotChunk;
            toAmino(message: _107.ResponseLoadSnapshotChunk): _107.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _107.ResponseLoadSnapshotChunkAminoMsg): _107.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _107.ResponseLoadSnapshotChunkProtoMsg): _107.ResponseLoadSnapshotChunk;
            toProto(message: _107.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _107.ResponseLoadSnapshotChunk): _107.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _107.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_107.ResponseApplySnapshotChunk>): _107.ResponseApplySnapshotChunk;
            fromAmino(object: _107.ResponseApplySnapshotChunkAmino): _107.ResponseApplySnapshotChunk;
            toAmino(message: _107.ResponseApplySnapshotChunk): _107.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _107.ResponseApplySnapshotChunkAminoMsg): _107.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _107.ResponseApplySnapshotChunkProtoMsg): _107.ResponseApplySnapshotChunk;
            toProto(message: _107.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _107.ResponseApplySnapshotChunk): _107.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _107.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ConsensusParams;
            fromPartial(object: Partial<_107.ConsensusParams>): _107.ConsensusParams;
            fromAmino(object: _107.ConsensusParamsAmino): _107.ConsensusParams;
            toAmino(message: _107.ConsensusParams): _107.ConsensusParamsAmino;
            fromAminoMsg(object: _107.ConsensusParamsAminoMsg): _107.ConsensusParams;
            fromProtoMsg(message: _107.ConsensusParamsProtoMsg): _107.ConsensusParams;
            toProto(message: _107.ConsensusParams): Uint8Array;
            toProtoMsg(message: _107.ConsensusParams): _107.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _107.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.BlockParams;
            fromPartial(object: Partial<_107.BlockParams>): _107.BlockParams;
            fromAmino(object: _107.BlockParamsAmino): _107.BlockParams;
            toAmino(message: _107.BlockParams): _107.BlockParamsAmino;
            fromAminoMsg(object: _107.BlockParamsAminoMsg): _107.BlockParams;
            fromProtoMsg(message: _107.BlockParamsProtoMsg): _107.BlockParams;
            toProto(message: _107.BlockParams): Uint8Array;
            toProtoMsg(message: _107.BlockParams): _107.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            typeUrl: string;
            encode(message: _107.LastCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.LastCommitInfo;
            fromPartial(object: Partial<_107.LastCommitInfo>): _107.LastCommitInfo;
            fromAmino(object: _107.LastCommitInfoAmino): _107.LastCommitInfo;
            toAmino(message: _107.LastCommitInfo): _107.LastCommitInfoAmino;
            fromAminoMsg(object: _107.LastCommitInfoAminoMsg): _107.LastCommitInfo;
            fromProtoMsg(message: _107.LastCommitInfoProtoMsg): _107.LastCommitInfo;
            toProto(message: _107.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _107.LastCommitInfo): _107.LastCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _107.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.Event;
            fromPartial(object: Partial<_107.Event>): _107.Event;
            fromAmino(object: _107.EventAmino): _107.Event;
            toAmino(message: _107.Event): _107.EventAmino;
            fromAminoMsg(object: _107.EventAminoMsg): _107.Event;
            fromProtoMsg(message: _107.EventProtoMsg): _107.Event;
            toProto(message: _107.Event): Uint8Array;
            toProtoMsg(message: _107.Event): _107.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _107.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.EventAttribute;
            fromPartial(object: Partial<_107.EventAttribute>): _107.EventAttribute;
            fromAmino(object: _107.EventAttributeAmino): _107.EventAttribute;
            toAmino(message: _107.EventAttribute): _107.EventAttributeAmino;
            fromAminoMsg(object: _107.EventAttributeAminoMsg): _107.EventAttribute;
            fromProtoMsg(message: _107.EventAttributeProtoMsg): _107.EventAttribute;
            toProto(message: _107.EventAttribute): Uint8Array;
            toProtoMsg(message: _107.EventAttribute): _107.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _107.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.TxResult;
            fromPartial(object: Partial<_107.TxResult>): _107.TxResult;
            fromAmino(object: _107.TxResultAmino): _107.TxResult;
            toAmino(message: _107.TxResult): _107.TxResultAmino;
            fromAminoMsg(object: _107.TxResultAminoMsg): _107.TxResult;
            fromProtoMsg(message: _107.TxResultProtoMsg): _107.TxResult;
            toProto(message: _107.TxResult): Uint8Array;
            toProtoMsg(message: _107.TxResult): _107.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _107.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.Validator;
            fromPartial(object: Partial<_107.Validator>): _107.Validator;
            fromAmino(object: _107.ValidatorAmino): _107.Validator;
            toAmino(message: _107.Validator): _107.ValidatorAmino;
            fromAminoMsg(object: _107.ValidatorAminoMsg): _107.Validator;
            fromProtoMsg(message: _107.ValidatorProtoMsg): _107.Validator;
            toProto(message: _107.Validator): Uint8Array;
            toProtoMsg(message: _107.Validator): _107.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _107.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.ValidatorUpdate;
            fromPartial(object: Partial<_107.ValidatorUpdate>): _107.ValidatorUpdate;
            fromAmino(object: _107.ValidatorUpdateAmino): _107.ValidatorUpdate;
            toAmino(message: _107.ValidatorUpdate): _107.ValidatorUpdateAmino;
            fromAminoMsg(object: _107.ValidatorUpdateAminoMsg): _107.ValidatorUpdate;
            fromProtoMsg(message: _107.ValidatorUpdateProtoMsg): _107.ValidatorUpdate;
            toProto(message: _107.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _107.ValidatorUpdate): _107.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _107.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.VoteInfo;
            fromPartial(object: Partial<_107.VoteInfo>): _107.VoteInfo;
            fromAmino(object: _107.VoteInfoAmino): _107.VoteInfo;
            toAmino(message: _107.VoteInfo): _107.VoteInfoAmino;
            fromAminoMsg(object: _107.VoteInfoAminoMsg): _107.VoteInfo;
            fromProtoMsg(message: _107.VoteInfoProtoMsg): _107.VoteInfo;
            toProto(message: _107.VoteInfo): Uint8Array;
            toProtoMsg(message: _107.VoteInfo): _107.VoteInfoProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _107.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.Evidence;
            fromPartial(object: Partial<_107.Evidence>): _107.Evidence;
            fromAmino(object: _107.EvidenceAmino): _107.Evidence;
            toAmino(message: _107.Evidence): _107.EvidenceAmino;
            fromAminoMsg(object: _107.EvidenceAminoMsg): _107.Evidence;
            fromProtoMsg(message: _107.EvidenceProtoMsg): _107.Evidence;
            toProto(message: _107.Evidence): Uint8Array;
            toProtoMsg(message: _107.Evidence): _107.EvidenceProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _107.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _107.Snapshot;
            fromPartial(object: Partial<_107.Snapshot>): _107.Snapshot;
            fromAmino(object: _107.SnapshotAmino): _107.Snapshot;
            toAmino(message: _107.Snapshot): _107.SnapshotAmino;
            fromAminoMsg(object: _107.SnapshotAminoMsg): _107.Snapshot;
            fromProtoMsg(message: _107.SnapshotProtoMsg): _107.Snapshot;
            toProto(message: _107.Snapshot): Uint8Array;
            toProtoMsg(message: _107.Snapshot): _107.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _109.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.Proof;
            fromPartial(object: Partial<_109.Proof>): _109.Proof;
            fromAmino(object: _109.ProofAmino): _109.Proof;
            toAmino(message: _109.Proof): _109.ProofAmino;
            fromAminoMsg(object: _109.ProofAminoMsg): _109.Proof;
            fromProtoMsg(message: _109.ProofProtoMsg): _109.Proof;
            toProto(message: _109.Proof): Uint8Array;
            toProtoMsg(message: _109.Proof): _109.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _109.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ValueOp;
            fromPartial(object: Partial<_109.ValueOp>): _109.ValueOp;
            fromAmino(object: _109.ValueOpAmino): _109.ValueOp;
            toAmino(message: _109.ValueOp): _109.ValueOpAmino;
            fromAminoMsg(object: _109.ValueOpAminoMsg): _109.ValueOp;
            fromProtoMsg(message: _109.ValueOpProtoMsg): _109.ValueOp;
            toProto(message: _109.ValueOp): Uint8Array;
            toProtoMsg(message: _109.ValueOp): _109.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _109.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.DominoOp;
            fromPartial(object: Partial<_109.DominoOp>): _109.DominoOp;
            fromAmino(object: _109.DominoOpAmino): _109.DominoOp;
            toAmino(message: _109.DominoOp): _109.DominoOpAmino;
            fromAminoMsg(object: _109.DominoOpAminoMsg): _109.DominoOp;
            fromProtoMsg(message: _109.DominoOpProtoMsg): _109.DominoOp;
            toProto(message: _109.DominoOp): Uint8Array;
            toProtoMsg(message: _109.DominoOp): _109.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _109.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ProofOp;
            fromPartial(object: Partial<_109.ProofOp>): _109.ProofOp;
            fromAmino(object: _109.ProofOpAmino): _109.ProofOp;
            toAmino(message: _109.ProofOp): _109.ProofOpAmino;
            fromAminoMsg(object: _109.ProofOpAminoMsg): _109.ProofOp;
            fromProtoMsg(message: _109.ProofOpProtoMsg): _109.ProofOp;
            toProto(message: _109.ProofOp): Uint8Array;
            toProtoMsg(message: _109.ProofOp): _109.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _109.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _109.ProofOps;
            fromPartial(object: Partial<_109.ProofOps>): _109.ProofOps;
            fromAmino(object: _109.ProofOpsAmino): _109.ProofOps;
            toAmino(message: _109.ProofOps): _109.ProofOpsAmino;
            fromAminoMsg(object: _109.ProofOpsAminoMsg): _109.ProofOps;
            fromProtoMsg(message: _109.ProofOpsProtoMsg): _109.ProofOps;
            toProto(message: _109.ProofOps): Uint8Array;
            toProtoMsg(message: _109.ProofOps): _109.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _108.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _108.PublicKey;
            fromPartial(object: Partial<_108.PublicKey>): _108.PublicKey;
            fromAmino(object: _108.PublicKeyAmino): _108.PublicKey;
            toAmino(message: _108.PublicKey): _108.PublicKeyAmino;
            fromAminoMsg(object: _108.PublicKeyAminoMsg): _108.PublicKey;
            fromProtoMsg(message: _108.PublicKeyProtoMsg): _108.PublicKey;
            toProto(message: _108.PublicKey): Uint8Array;
            toProtoMsg(message: _108.PublicKey): _108.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _110.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                fromJSON(object: any): _110.BitArray;
                fromPartial(object: Partial<_110.BitArray>): _110.BitArray;
                fromAmino(object: _110.BitArrayAmino): _110.BitArray;
                toAmino(message: _110.BitArray): _110.BitArrayAmino;
                fromAminoMsg(object: _110.BitArrayAminoMsg): _110.BitArray;
                fromProtoMsg(message: _110.BitArrayProtoMsg): _110.BitArray;
                toProto(message: _110.BitArray): Uint8Array;
                toProtoMsg(message: _110.BitArray): _110.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _111.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _111.NetAddress;
            fromPartial(object: Partial<_111.NetAddress>): _111.NetAddress;
            fromAmino(object: _111.NetAddressAmino): _111.NetAddress;
            toAmino(message: _111.NetAddress): _111.NetAddressAmino;
            fromAminoMsg(object: _111.NetAddressAminoMsg): _111.NetAddress;
            fromProtoMsg(message: _111.NetAddressProtoMsg): _111.NetAddress;
            toProto(message: _111.NetAddress): Uint8Array;
            toProtoMsg(message: _111.NetAddress): _111.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _111.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _111.ProtocolVersion;
            fromPartial(object: Partial<_111.ProtocolVersion>): _111.ProtocolVersion;
            fromAmino(object: _111.ProtocolVersionAmino): _111.ProtocolVersion;
            toAmino(message: _111.ProtocolVersion): _111.ProtocolVersionAmino;
            fromAminoMsg(object: _111.ProtocolVersionAminoMsg): _111.ProtocolVersion;
            fromProtoMsg(message: _111.ProtocolVersionProtoMsg): _111.ProtocolVersion;
            toProto(message: _111.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _111.ProtocolVersion): _111.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _111.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _111.DefaultNodeInfo;
            fromPartial(object: Partial<_111.DefaultNodeInfo>): _111.DefaultNodeInfo;
            fromAmino(object: _111.DefaultNodeInfoAmino): _111.DefaultNodeInfo;
            toAmino(message: _111.DefaultNodeInfo): _111.DefaultNodeInfoAmino;
            fromAminoMsg(object: _111.DefaultNodeInfoAminoMsg): _111.DefaultNodeInfo;
            fromProtoMsg(message: _111.DefaultNodeInfoProtoMsg): _111.DefaultNodeInfo;
            toProto(message: _111.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _111.DefaultNodeInfo): _111.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _111.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _111.DefaultNodeInfoOther;
            fromPartial(object: Partial<_111.DefaultNodeInfoOther>): _111.DefaultNodeInfoOther;
            fromAmino(object: _111.DefaultNodeInfoOtherAmino): _111.DefaultNodeInfoOther;
            toAmino(message: _111.DefaultNodeInfoOther): _111.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _111.DefaultNodeInfoOtherAminoMsg): _111.DefaultNodeInfoOther;
            fromProtoMsg(message: _111.DefaultNodeInfoOtherProtoMsg): _111.DefaultNodeInfoOther;
            toProto(message: _111.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _111.DefaultNodeInfoOther): _111.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _116.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _116.ValidatorSet;
            fromPartial(object: Partial<_116.ValidatorSet>): _116.ValidatorSet;
            fromAmino(object: _116.ValidatorSetAmino): _116.ValidatorSet;
            toAmino(message: _116.ValidatorSet): _116.ValidatorSetAmino;
            fromAminoMsg(object: _116.ValidatorSetAminoMsg): _116.ValidatorSet;
            fromProtoMsg(message: _116.ValidatorSetProtoMsg): _116.ValidatorSet;
            toProto(message: _116.ValidatorSet): Uint8Array;
            toProtoMsg(message: _116.ValidatorSet): _116.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _116.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _116.Validator;
            fromPartial(object: Partial<_116.Validator>): _116.Validator;
            fromAmino(object: _116.ValidatorAmino): _116.Validator;
            toAmino(message: _116.Validator): _116.ValidatorAmino;
            fromAminoMsg(object: _116.ValidatorAminoMsg): _116.Validator;
            fromProtoMsg(message: _116.ValidatorProtoMsg): _116.Validator;
            toProto(message: _116.Validator): Uint8Array;
            toProtoMsg(message: _116.Validator): _116.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _116.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _116.SimpleValidator;
            fromPartial(object: Partial<_116.SimpleValidator>): _116.SimpleValidator;
            fromAmino(object: _116.SimpleValidatorAmino): _116.SimpleValidator;
            toAmino(message: _116.SimpleValidator): _116.SimpleValidatorAmino;
            fromAminoMsg(object: _116.SimpleValidatorAminoMsg): _116.SimpleValidator;
            fromProtoMsg(message: _116.SimpleValidatorProtoMsg): _116.SimpleValidator;
            toProto(message: _116.SimpleValidator): Uint8Array;
            toProtoMsg(message: _116.SimpleValidator): _116.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _115.BlockIDFlag;
        blockIDFlagToJSON(object: _115.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _115.SignedMsgType;
        signedMsgTypeToJSON(object: _115.SignedMsgType): string;
        BlockIDFlag: typeof _115.BlockIDFlag;
        BlockIDFlagSDKType: typeof _115.BlockIDFlag;
        BlockIDFlagAmino: typeof _115.BlockIDFlag;
        SignedMsgType: typeof _115.SignedMsgType;
        SignedMsgTypeSDKType: typeof _115.SignedMsgType;
        SignedMsgTypeAmino: typeof _115.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _115.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.PartSetHeader;
            fromPartial(object: Partial<_115.PartSetHeader>): _115.PartSetHeader;
            fromAmino(object: _115.PartSetHeaderAmino): _115.PartSetHeader;
            toAmino(message: _115.PartSetHeader): _115.PartSetHeaderAmino;
            fromAminoMsg(object: _115.PartSetHeaderAminoMsg): _115.PartSetHeader;
            fromProtoMsg(message: _115.PartSetHeaderProtoMsg): _115.PartSetHeader;
            toProto(message: _115.PartSetHeader): Uint8Array;
            toProtoMsg(message: _115.PartSetHeader): _115.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _115.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.Part;
            fromPartial(object: Partial<_115.Part>): _115.Part;
            fromAmino(object: _115.PartAmino): _115.Part;
            toAmino(message: _115.Part): _115.PartAmino;
            fromAminoMsg(object: _115.PartAminoMsg): _115.Part;
            fromProtoMsg(message: _115.PartProtoMsg): _115.Part;
            toProto(message: _115.Part): Uint8Array;
            toProtoMsg(message: _115.Part): _115.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _115.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.BlockID;
            fromPartial(object: Partial<_115.BlockID>): _115.BlockID;
            fromAmino(object: _115.BlockIDAmino): _115.BlockID;
            toAmino(message: _115.BlockID): _115.BlockIDAmino;
            fromAminoMsg(object: _115.BlockIDAminoMsg): _115.BlockID;
            fromProtoMsg(message: _115.BlockIDProtoMsg): _115.BlockID;
            toProto(message: _115.BlockID): Uint8Array;
            toProtoMsg(message: _115.BlockID): _115.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _115.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.Header;
            fromPartial(object: Partial<_115.Header>): _115.Header;
            fromAmino(object: _115.HeaderAmino): _115.Header;
            toAmino(message: _115.Header): _115.HeaderAmino;
            fromAminoMsg(object: _115.HeaderAminoMsg): _115.Header;
            fromProtoMsg(message: _115.HeaderProtoMsg): _115.Header;
            toProto(message: _115.Header): Uint8Array;
            toProtoMsg(message: _115.Header): _115.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _115.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.Data;
            fromPartial(object: Partial<_115.Data>): _115.Data;
            fromAmino(object: _115.DataAmino): _115.Data;
            toAmino(message: _115.Data): _115.DataAmino;
            fromAminoMsg(object: _115.DataAminoMsg): _115.Data;
            fromProtoMsg(message: _115.DataProtoMsg): _115.Data;
            toProto(message: _115.Data): Uint8Array;
            toProtoMsg(message: _115.Data): _115.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _115.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.Vote;
            fromPartial(object: Partial<_115.Vote>): _115.Vote;
            fromAmino(object: _115.VoteAmino): _115.Vote;
            toAmino(message: _115.Vote): _115.VoteAmino;
            fromAminoMsg(object: _115.VoteAminoMsg): _115.Vote;
            fromProtoMsg(message: _115.VoteProtoMsg): _115.Vote;
            toProto(message: _115.Vote): Uint8Array;
            toProtoMsg(message: _115.Vote): _115.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _115.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.Commit;
            fromPartial(object: Partial<_115.Commit>): _115.Commit;
            fromAmino(object: _115.CommitAmino): _115.Commit;
            toAmino(message: _115.Commit): _115.CommitAmino;
            fromAminoMsg(object: _115.CommitAminoMsg): _115.Commit;
            fromProtoMsg(message: _115.CommitProtoMsg): _115.Commit;
            toProto(message: _115.Commit): Uint8Array;
            toProtoMsg(message: _115.Commit): _115.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _115.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.CommitSig;
            fromPartial(object: Partial<_115.CommitSig>): _115.CommitSig;
            fromAmino(object: _115.CommitSigAmino): _115.CommitSig;
            toAmino(message: _115.CommitSig): _115.CommitSigAmino;
            fromAminoMsg(object: _115.CommitSigAminoMsg): _115.CommitSig;
            fromProtoMsg(message: _115.CommitSigProtoMsg): _115.CommitSig;
            toProto(message: _115.CommitSig): Uint8Array;
            toProtoMsg(message: _115.CommitSig): _115.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _115.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.Proposal;
            fromPartial(object: Partial<_115.Proposal>): _115.Proposal;
            fromAmino(object: _115.ProposalAmino): _115.Proposal;
            toAmino(message: _115.Proposal): _115.ProposalAmino;
            fromAminoMsg(object: _115.ProposalAminoMsg): _115.Proposal;
            fromProtoMsg(message: _115.ProposalProtoMsg): _115.Proposal;
            toProto(message: _115.Proposal): Uint8Array;
            toProtoMsg(message: _115.Proposal): _115.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _115.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.SignedHeader;
            fromPartial(object: Partial<_115.SignedHeader>): _115.SignedHeader;
            fromAmino(object: _115.SignedHeaderAmino): _115.SignedHeader;
            toAmino(message: _115.SignedHeader): _115.SignedHeaderAmino;
            fromAminoMsg(object: _115.SignedHeaderAminoMsg): _115.SignedHeader;
            fromProtoMsg(message: _115.SignedHeaderProtoMsg): _115.SignedHeader;
            toProto(message: _115.SignedHeader): Uint8Array;
            toProtoMsg(message: _115.SignedHeader): _115.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _115.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.LightBlock;
            fromPartial(object: Partial<_115.LightBlock>): _115.LightBlock;
            fromAmino(object: _115.LightBlockAmino): _115.LightBlock;
            toAmino(message: _115.LightBlock): _115.LightBlockAmino;
            fromAminoMsg(object: _115.LightBlockAminoMsg): _115.LightBlock;
            fromProtoMsg(message: _115.LightBlockProtoMsg): _115.LightBlock;
            toProto(message: _115.LightBlock): Uint8Array;
            toProtoMsg(message: _115.LightBlock): _115.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _115.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.BlockMeta;
            fromPartial(object: Partial<_115.BlockMeta>): _115.BlockMeta;
            fromAmino(object: _115.BlockMetaAmino): _115.BlockMeta;
            toAmino(message: _115.BlockMeta): _115.BlockMetaAmino;
            fromAminoMsg(object: _115.BlockMetaAminoMsg): _115.BlockMeta;
            fromProtoMsg(message: _115.BlockMetaProtoMsg): _115.BlockMeta;
            toProto(message: _115.BlockMeta): Uint8Array;
            toProtoMsg(message: _115.BlockMeta): _115.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _115.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _115.TxProof;
            fromPartial(object: Partial<_115.TxProof>): _115.TxProof;
            fromAmino(object: _115.TxProofAmino): _115.TxProof;
            toAmino(message: _115.TxProof): _115.TxProofAmino;
            fromAminoMsg(object: _115.TxProofAminoMsg): _115.TxProof;
            fromProtoMsg(message: _115.TxProofProtoMsg): _115.TxProof;
            toProto(message: _115.TxProof): Uint8Array;
            toProtoMsg(message: _115.TxProof): _115.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _114.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _114.ConsensusParams;
            fromPartial(object: Partial<_114.ConsensusParams>): _114.ConsensusParams;
            fromAmino(object: _114.ConsensusParamsAmino): _114.ConsensusParams;
            toAmino(message: _114.ConsensusParams): _114.ConsensusParamsAmino;
            fromAminoMsg(object: _114.ConsensusParamsAminoMsg): _114.ConsensusParams;
            fromProtoMsg(message: _114.ConsensusParamsProtoMsg): _114.ConsensusParams;
            toProto(message: _114.ConsensusParams): Uint8Array;
            toProtoMsg(message: _114.ConsensusParams): _114.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _114.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _114.BlockParams;
            fromPartial(object: Partial<_114.BlockParams>): _114.BlockParams;
            fromAmino(object: _114.BlockParamsAmino): _114.BlockParams;
            toAmino(message: _114.BlockParams): _114.BlockParamsAmino;
            fromAminoMsg(object: _114.BlockParamsAminoMsg): _114.BlockParams;
            fromProtoMsg(message: _114.BlockParamsProtoMsg): _114.BlockParams;
            toProto(message: _114.BlockParams): Uint8Array;
            toProtoMsg(message: _114.BlockParams): _114.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _114.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _114.EvidenceParams;
            fromPartial(object: Partial<_114.EvidenceParams>): _114.EvidenceParams;
            fromAmino(object: _114.EvidenceParamsAmino): _114.EvidenceParams;
            toAmino(message: _114.EvidenceParams): _114.EvidenceParamsAmino;
            fromAminoMsg(object: _114.EvidenceParamsAminoMsg): _114.EvidenceParams;
            fromProtoMsg(message: _114.EvidenceParamsProtoMsg): _114.EvidenceParams;
            toProto(message: _114.EvidenceParams): Uint8Array;
            toProtoMsg(message: _114.EvidenceParams): _114.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _114.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _114.ValidatorParams;
            fromPartial(object: Partial<_114.ValidatorParams>): _114.ValidatorParams;
            fromAmino(object: _114.ValidatorParamsAmino): _114.ValidatorParams;
            toAmino(message: _114.ValidatorParams): _114.ValidatorParamsAmino;
            fromAminoMsg(object: _114.ValidatorParamsAminoMsg): _114.ValidatorParams;
            fromProtoMsg(message: _114.ValidatorParamsProtoMsg): _114.ValidatorParams;
            toProto(message: _114.ValidatorParams): Uint8Array;
            toProtoMsg(message: _114.ValidatorParams): _114.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _114.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _114.VersionParams;
            fromPartial(object: Partial<_114.VersionParams>): _114.VersionParams;
            fromAmino(object: _114.VersionParamsAmino): _114.VersionParams;
            toAmino(message: _114.VersionParams): _114.VersionParamsAmino;
            fromAminoMsg(object: _114.VersionParamsAminoMsg): _114.VersionParams;
            fromProtoMsg(message: _114.VersionParamsProtoMsg): _114.VersionParams;
            toProto(message: _114.VersionParams): Uint8Array;
            toProtoMsg(message: _114.VersionParams): _114.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _114.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _114.HashedParams;
            fromPartial(object: Partial<_114.HashedParams>): _114.HashedParams;
            fromAmino(object: _114.HashedParamsAmino): _114.HashedParams;
            toAmino(message: _114.HashedParams): _114.HashedParamsAmino;
            fromAminoMsg(object: _114.HashedParamsAminoMsg): _114.HashedParams;
            fromProtoMsg(message: _114.HashedParamsProtoMsg): _114.HashedParams;
            toProto(message: _114.HashedParams): Uint8Array;
            toProtoMsg(message: _114.HashedParams): _114.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _113.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _113.Evidence;
            fromPartial(object: Partial<_113.Evidence>): _113.Evidence;
            fromAmino(object: _113.EvidenceAmino): _113.Evidence;
            toAmino(message: _113.Evidence): _113.EvidenceAmino;
            fromAminoMsg(object: _113.EvidenceAminoMsg): _113.Evidence;
            fromProtoMsg(message: _113.EvidenceProtoMsg): _113.Evidence;
            toProto(message: _113.Evidence): Uint8Array;
            toProtoMsg(message: _113.Evidence): _113.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _113.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _113.DuplicateVoteEvidence;
            fromPartial(object: Partial<_113.DuplicateVoteEvidence>): _113.DuplicateVoteEvidence;
            fromAmino(object: _113.DuplicateVoteEvidenceAmino): _113.DuplicateVoteEvidence;
            toAmino(message: _113.DuplicateVoteEvidence): _113.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _113.DuplicateVoteEvidenceAminoMsg): _113.DuplicateVoteEvidence;
            fromProtoMsg(message: _113.DuplicateVoteEvidenceProtoMsg): _113.DuplicateVoteEvidence;
            toProto(message: _113.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _113.DuplicateVoteEvidence): _113.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _113.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _113.LightClientAttackEvidence;
            fromPartial(object: Partial<_113.LightClientAttackEvidence>): _113.LightClientAttackEvidence;
            fromAmino(object: _113.LightClientAttackEvidenceAmino): _113.LightClientAttackEvidence;
            toAmino(message: _113.LightClientAttackEvidence): _113.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _113.LightClientAttackEvidenceAminoMsg): _113.LightClientAttackEvidence;
            fromProtoMsg(message: _113.LightClientAttackEvidenceProtoMsg): _113.LightClientAttackEvidence;
            toProto(message: _113.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _113.LightClientAttackEvidence): _113.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _113.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _113.EvidenceList;
            fromPartial(object: Partial<_113.EvidenceList>): _113.EvidenceList;
            fromAmino(object: _113.EvidenceListAmino): _113.EvidenceList;
            toAmino(message: _113.EvidenceList): _113.EvidenceListAmino;
            fromAminoMsg(object: _113.EvidenceListAminoMsg): _113.EvidenceList;
            fromProtoMsg(message: _113.EvidenceListProtoMsg): _113.EvidenceList;
            toProto(message: _113.EvidenceList): Uint8Array;
            toProtoMsg(message: _113.EvidenceList): _113.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _112.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _112.Block;
            fromPartial(object: Partial<_112.Block>): _112.Block;
            fromAmino(object: _112.BlockAmino): _112.Block;
            toAmino(message: _112.Block): _112.BlockAmino;
            fromAminoMsg(object: _112.BlockAminoMsg): _112.Block;
            fromProtoMsg(message: _112.BlockProtoMsg): _112.Block;
            toProto(message: _112.Block): Uint8Array;
            toProtoMsg(message: _112.Block): _112.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _117.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.App;
            fromPartial(object: Partial<_117.App>): _117.App;
            fromAmino(object: _117.AppAmino): _117.App;
            toAmino(message: _117.App): _117.AppAmino;
            fromAminoMsg(object: _117.AppAminoMsg): _117.App;
            fromProtoMsg(message: _117.AppProtoMsg): _117.App;
            toProto(message: _117.App): Uint8Array;
            toProtoMsg(message: _117.App): _117.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _117.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _117.Consensus;
            fromPartial(object: Partial<_117.Consensus>): _117.Consensus;
            fromAmino(object: _117.ConsensusAmino): _117.Consensus;
            toAmino(message: _117.Consensus): _117.ConsensusAmino;
            fromAminoMsg(object: _117.ConsensusAminoMsg): _117.Consensus;
            fromProtoMsg(message: _117.ConsensusProtoMsg): _117.Consensus;
            toProto(message: _117.Consensus): Uint8Array;
            toProtoMsg(message: _117.Consensus): _117.ConsensusProtoMsg;
        };
    };
}
