import * as _236 from "./api/http";
import * as _237 from "./protobuf/timestamp";
import * as _238 from "./protobuf/any";
import * as _239 from "./protobuf/descriptor";
import * as _240 from "./protobuf/duration";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _236.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _236.Http;
            fromPartial(object: Partial<_236.Http>): _236.Http;
            fromAmino(object: _236.HttpAmino): _236.Http;
            toAmino(message: _236.Http): _236.HttpAmino;
            fromAminoMsg(object: _236.HttpAminoMsg): _236.Http;
            fromProtoMsg(message: _236.HttpProtoMsg): _236.Http;
            toProto(message: _236.Http): Uint8Array;
            toProtoMsg(message: _236.Http): _236.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _236.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _236.HttpRule;
            fromPartial(object: Partial<_236.HttpRule>): _236.HttpRule;
            fromAmino(object: _236.HttpRuleAmino): _236.HttpRule;
            toAmino(message: _236.HttpRule): _236.HttpRuleAmino;
            fromAminoMsg(object: _236.HttpRuleAminoMsg): _236.HttpRule;
            fromProtoMsg(message: _236.HttpRuleProtoMsg): _236.HttpRule;
            toProto(message: _236.HttpRule): Uint8Array;
            toProtoMsg(message: _236.HttpRule): _236.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _236.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _236.CustomHttpPattern;
            fromPartial(object: Partial<_236.CustomHttpPattern>): _236.CustomHttpPattern;
            fromAmino(object: _236.CustomHttpPatternAmino): _236.CustomHttpPattern;
            toAmino(message: _236.CustomHttpPattern): _236.CustomHttpPatternAmino;
            fromAminoMsg(object: _236.CustomHttpPatternAminoMsg): _236.CustomHttpPattern;
            fromProtoMsg(message: _236.CustomHttpPatternProtoMsg): _236.CustomHttpPattern;
            toProto(message: _236.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _236.CustomHttpPattern): _236.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Duration: {
            typeUrl: string;
            encode(message: _240.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _240.Duration;
            fromPartial(object: Partial<_240.Duration>): _240.Duration;
            fromAmino(object: string): _240.Duration;
            toAmino(message: _240.Duration): string;
            fromAminoMsg(object: _240.DurationAminoMsg): _240.Duration;
            fromProtoMsg(message: _240.DurationProtoMsg): _240.Duration;
            toProto(message: _240.Duration): Uint8Array;
            toProtoMsg(message: _240.Duration): _240.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _239.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _239.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _239.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _239.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _239.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _239.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _239.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _239.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _239.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _239.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _239.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _239.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _239.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _239.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _239.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _239.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _239.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _239.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _239.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _239.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _239.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _239.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _239.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _239.FieldOptions_CType;
        FieldOptions_JSType: typeof _239.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _239.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _239.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _239.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _239.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _239.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _239.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.FileDescriptorSet;
            fromPartial(object: Partial<_239.FileDescriptorSet>): _239.FileDescriptorSet;
            fromAmino(object: _239.FileDescriptorSetAmino): _239.FileDescriptorSet;
            toAmino(message: _239.FileDescriptorSet): _239.FileDescriptorSetAmino;
            fromAminoMsg(object: _239.FileDescriptorSetAminoMsg): _239.FileDescriptorSet;
            fromProtoMsg(message: _239.FileDescriptorSetProtoMsg): _239.FileDescriptorSet;
            toProto(message: _239.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _239.FileDescriptorSet): _239.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _239.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.FileDescriptorProto;
            fromPartial(object: Partial<_239.FileDescriptorProto>): _239.FileDescriptorProto;
            fromAmino(object: _239.FileDescriptorProtoAmino): _239.FileDescriptorProto;
            toAmino(message: _239.FileDescriptorProto): _239.FileDescriptorProtoAmino;
            fromAminoMsg(object: _239.FileDescriptorProtoAminoMsg): _239.FileDescriptorProto;
            fromProtoMsg(message: _239.FileDescriptorProtoProtoMsg): _239.FileDescriptorProto;
            toProto(message: _239.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _239.FileDescriptorProto): _239.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _239.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.DescriptorProto;
            fromPartial(object: Partial<_239.DescriptorProto>): _239.DescriptorProto;
            fromAmino(object: _239.DescriptorProtoAmino): _239.DescriptorProto;
            toAmino(message: _239.DescriptorProto): _239.DescriptorProtoAmino;
            fromAminoMsg(object: _239.DescriptorProtoAminoMsg): _239.DescriptorProto;
            fromProtoMsg(message: _239.DescriptorProtoProtoMsg): _239.DescriptorProto;
            toProto(message: _239.DescriptorProto): Uint8Array;
            toProtoMsg(message: _239.DescriptorProto): _239.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _239.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_239.DescriptorProto_ExtensionRange>): _239.DescriptorProto_ExtensionRange;
            fromAmino(object: _239.DescriptorProto_ExtensionRangeAmino): _239.DescriptorProto_ExtensionRange;
            toAmino(message: _239.DescriptorProto_ExtensionRange): _239.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _239.DescriptorProto_ExtensionRangeAminoMsg): _239.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _239.DescriptorProto_ExtensionRangeProtoMsg): _239.DescriptorProto_ExtensionRange;
            toProto(message: _239.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _239.DescriptorProto_ExtensionRange): _239.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _239.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_239.DescriptorProto_ReservedRange>): _239.DescriptorProto_ReservedRange;
            fromAmino(object: _239.DescriptorProto_ReservedRangeAmino): _239.DescriptorProto_ReservedRange;
            toAmino(message: _239.DescriptorProto_ReservedRange): _239.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _239.DescriptorProto_ReservedRangeAminoMsg): _239.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _239.DescriptorProto_ReservedRangeProtoMsg): _239.DescriptorProto_ReservedRange;
            toProto(message: _239.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _239.DescriptorProto_ReservedRange): _239.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _239.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.ExtensionRangeOptions;
            fromPartial(object: Partial<_239.ExtensionRangeOptions>): _239.ExtensionRangeOptions;
            fromAmino(object: _239.ExtensionRangeOptionsAmino): _239.ExtensionRangeOptions;
            toAmino(message: _239.ExtensionRangeOptions): _239.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _239.ExtensionRangeOptionsAminoMsg): _239.ExtensionRangeOptions;
            fromProtoMsg(message: _239.ExtensionRangeOptionsProtoMsg): _239.ExtensionRangeOptions;
            toProto(message: _239.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _239.ExtensionRangeOptions): _239.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _239.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.FieldDescriptorProto;
            fromPartial(object: Partial<_239.FieldDescriptorProto>): _239.FieldDescriptorProto;
            fromAmino(object: _239.FieldDescriptorProtoAmino): _239.FieldDescriptorProto;
            toAmino(message: _239.FieldDescriptorProto): _239.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _239.FieldDescriptorProtoAminoMsg): _239.FieldDescriptorProto;
            fromProtoMsg(message: _239.FieldDescriptorProtoProtoMsg): _239.FieldDescriptorProto;
            toProto(message: _239.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _239.FieldDescriptorProto): _239.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _239.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.OneofDescriptorProto;
            fromPartial(object: Partial<_239.OneofDescriptorProto>): _239.OneofDescriptorProto;
            fromAmino(object: _239.OneofDescriptorProtoAmino): _239.OneofDescriptorProto;
            toAmino(message: _239.OneofDescriptorProto): _239.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _239.OneofDescriptorProtoAminoMsg): _239.OneofDescriptorProto;
            fromProtoMsg(message: _239.OneofDescriptorProtoProtoMsg): _239.OneofDescriptorProto;
            toProto(message: _239.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _239.OneofDescriptorProto): _239.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _239.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.EnumDescriptorProto;
            fromPartial(object: Partial<_239.EnumDescriptorProto>): _239.EnumDescriptorProto;
            fromAmino(object: _239.EnumDescriptorProtoAmino): _239.EnumDescriptorProto;
            toAmino(message: _239.EnumDescriptorProto): _239.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _239.EnumDescriptorProtoAminoMsg): _239.EnumDescriptorProto;
            fromProtoMsg(message: _239.EnumDescriptorProtoProtoMsg): _239.EnumDescriptorProto;
            toProto(message: _239.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _239.EnumDescriptorProto): _239.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _239.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_239.EnumDescriptorProto_EnumReservedRange>): _239.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _239.EnumDescriptorProto_EnumReservedRangeAmino): _239.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _239.EnumDescriptorProto_EnumReservedRange): _239.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _239.EnumDescriptorProto_EnumReservedRangeAminoMsg): _239.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _239.EnumDescriptorProto_EnumReservedRangeProtoMsg): _239.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _239.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _239.EnumDescriptorProto_EnumReservedRange): _239.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _239.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.EnumValueDescriptorProto;
            fromPartial(object: Partial<_239.EnumValueDescriptorProto>): _239.EnumValueDescriptorProto;
            fromAmino(object: _239.EnumValueDescriptorProtoAmino): _239.EnumValueDescriptorProto;
            toAmino(message: _239.EnumValueDescriptorProto): _239.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _239.EnumValueDescriptorProtoAminoMsg): _239.EnumValueDescriptorProto;
            fromProtoMsg(message: _239.EnumValueDescriptorProtoProtoMsg): _239.EnumValueDescriptorProto;
            toProto(message: _239.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _239.EnumValueDescriptorProto): _239.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _239.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.ServiceDescriptorProto;
            fromPartial(object: Partial<_239.ServiceDescriptorProto>): _239.ServiceDescriptorProto;
            fromAmino(object: _239.ServiceDescriptorProtoAmino): _239.ServiceDescriptorProto;
            toAmino(message: _239.ServiceDescriptorProto): _239.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _239.ServiceDescriptorProtoAminoMsg): _239.ServiceDescriptorProto;
            fromProtoMsg(message: _239.ServiceDescriptorProtoProtoMsg): _239.ServiceDescriptorProto;
            toProto(message: _239.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _239.ServiceDescriptorProto): _239.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _239.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.MethodDescriptorProto;
            fromPartial(object: Partial<_239.MethodDescriptorProto>): _239.MethodDescriptorProto;
            fromAmino(object: _239.MethodDescriptorProtoAmino): _239.MethodDescriptorProto;
            toAmino(message: _239.MethodDescriptorProto): _239.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _239.MethodDescriptorProtoAminoMsg): _239.MethodDescriptorProto;
            fromProtoMsg(message: _239.MethodDescriptorProtoProtoMsg): _239.MethodDescriptorProto;
            toProto(message: _239.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _239.MethodDescriptorProto): _239.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _239.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.FileOptions;
            fromPartial(object: Partial<_239.FileOptions>): _239.FileOptions;
            fromAmino(object: _239.FileOptionsAmino): _239.FileOptions;
            toAmino(message: _239.FileOptions): _239.FileOptionsAmino;
            fromAminoMsg(object: _239.FileOptionsAminoMsg): _239.FileOptions;
            fromProtoMsg(message: _239.FileOptionsProtoMsg): _239.FileOptions;
            toProto(message: _239.FileOptions): Uint8Array;
            toProtoMsg(message: _239.FileOptions): _239.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _239.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.MessageOptions;
            fromPartial(object: Partial<_239.MessageOptions>): _239.MessageOptions;
            fromAmino(object: _239.MessageOptionsAmino): _239.MessageOptions;
            toAmino(message: _239.MessageOptions): _239.MessageOptionsAmino;
            fromAminoMsg(object: _239.MessageOptionsAminoMsg): _239.MessageOptions;
            fromProtoMsg(message: _239.MessageOptionsProtoMsg): _239.MessageOptions;
            toProto(message: _239.MessageOptions): Uint8Array;
            toProtoMsg(message: _239.MessageOptions): _239.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _239.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.FieldOptions;
            fromPartial(object: Partial<_239.FieldOptions>): _239.FieldOptions;
            fromAmino(object: _239.FieldOptionsAmino): _239.FieldOptions;
            toAmino(message: _239.FieldOptions): _239.FieldOptionsAmino;
            fromAminoMsg(object: _239.FieldOptionsAminoMsg): _239.FieldOptions;
            fromProtoMsg(message: _239.FieldOptionsProtoMsg): _239.FieldOptions;
            toProto(message: _239.FieldOptions): Uint8Array;
            toProtoMsg(message: _239.FieldOptions): _239.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _239.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.OneofOptions;
            fromPartial(object: Partial<_239.OneofOptions>): _239.OneofOptions;
            fromAmino(object: _239.OneofOptionsAmino): _239.OneofOptions;
            toAmino(message: _239.OneofOptions): _239.OneofOptionsAmino;
            fromAminoMsg(object: _239.OneofOptionsAminoMsg): _239.OneofOptions;
            fromProtoMsg(message: _239.OneofOptionsProtoMsg): _239.OneofOptions;
            toProto(message: _239.OneofOptions): Uint8Array;
            toProtoMsg(message: _239.OneofOptions): _239.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _239.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.EnumOptions;
            fromPartial(object: Partial<_239.EnumOptions>): _239.EnumOptions;
            fromAmino(object: _239.EnumOptionsAmino): _239.EnumOptions;
            toAmino(message: _239.EnumOptions): _239.EnumOptionsAmino;
            fromAminoMsg(object: _239.EnumOptionsAminoMsg): _239.EnumOptions;
            fromProtoMsg(message: _239.EnumOptionsProtoMsg): _239.EnumOptions;
            toProto(message: _239.EnumOptions): Uint8Array;
            toProtoMsg(message: _239.EnumOptions): _239.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _239.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.EnumValueOptions;
            fromPartial(object: Partial<_239.EnumValueOptions>): _239.EnumValueOptions;
            fromAmino(object: _239.EnumValueOptionsAmino): _239.EnumValueOptions;
            toAmino(message: _239.EnumValueOptions): _239.EnumValueOptionsAmino;
            fromAminoMsg(object: _239.EnumValueOptionsAminoMsg): _239.EnumValueOptions;
            fromProtoMsg(message: _239.EnumValueOptionsProtoMsg): _239.EnumValueOptions;
            toProto(message: _239.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _239.EnumValueOptions): _239.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _239.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.ServiceOptions;
            fromPartial(object: Partial<_239.ServiceOptions>): _239.ServiceOptions;
            fromAmino(object: _239.ServiceOptionsAmino): _239.ServiceOptions;
            toAmino(message: _239.ServiceOptions): _239.ServiceOptionsAmino;
            fromAminoMsg(object: _239.ServiceOptionsAminoMsg): _239.ServiceOptions;
            fromProtoMsg(message: _239.ServiceOptionsProtoMsg): _239.ServiceOptions;
            toProto(message: _239.ServiceOptions): Uint8Array;
            toProtoMsg(message: _239.ServiceOptions): _239.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _239.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.MethodOptions;
            fromPartial(object: Partial<_239.MethodOptions>): _239.MethodOptions;
            fromAmino(object: _239.MethodOptionsAmino): _239.MethodOptions;
            toAmino(message: _239.MethodOptions): _239.MethodOptionsAmino;
            fromAminoMsg(object: _239.MethodOptionsAminoMsg): _239.MethodOptions;
            fromProtoMsg(message: _239.MethodOptionsProtoMsg): _239.MethodOptions;
            toProto(message: _239.MethodOptions): Uint8Array;
            toProtoMsg(message: _239.MethodOptions): _239.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _239.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.UninterpretedOption;
            fromPartial(object: Partial<_239.UninterpretedOption>): _239.UninterpretedOption;
            fromAmino(object: _239.UninterpretedOptionAmino): _239.UninterpretedOption;
            toAmino(message: _239.UninterpretedOption): _239.UninterpretedOptionAmino;
            fromAminoMsg(object: _239.UninterpretedOptionAminoMsg): _239.UninterpretedOption;
            fromProtoMsg(message: _239.UninterpretedOptionProtoMsg): _239.UninterpretedOption;
            toProto(message: _239.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _239.UninterpretedOption): _239.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _239.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_239.UninterpretedOption_NamePart>): _239.UninterpretedOption_NamePart;
            fromAmino(object: _239.UninterpretedOption_NamePartAmino): _239.UninterpretedOption_NamePart;
            toAmino(message: _239.UninterpretedOption_NamePart): _239.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _239.UninterpretedOption_NamePartAminoMsg): _239.UninterpretedOption_NamePart;
            fromProtoMsg(message: _239.UninterpretedOption_NamePartProtoMsg): _239.UninterpretedOption_NamePart;
            toProto(message: _239.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _239.UninterpretedOption_NamePart): _239.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _239.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.SourceCodeInfo;
            fromPartial(object: Partial<_239.SourceCodeInfo>): _239.SourceCodeInfo;
            fromAmino(object: _239.SourceCodeInfoAmino): _239.SourceCodeInfo;
            toAmino(message: _239.SourceCodeInfo): _239.SourceCodeInfoAmino;
            fromAminoMsg(object: _239.SourceCodeInfoAminoMsg): _239.SourceCodeInfo;
            fromProtoMsg(message: _239.SourceCodeInfoProtoMsg): _239.SourceCodeInfo;
            toProto(message: _239.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _239.SourceCodeInfo): _239.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _239.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.SourceCodeInfo_Location;
            fromPartial(object: Partial<_239.SourceCodeInfo_Location>): _239.SourceCodeInfo_Location;
            fromAmino(object: _239.SourceCodeInfo_LocationAmino): _239.SourceCodeInfo_Location;
            toAmino(message: _239.SourceCodeInfo_Location): _239.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _239.SourceCodeInfo_LocationAminoMsg): _239.SourceCodeInfo_Location;
            fromProtoMsg(message: _239.SourceCodeInfo_LocationProtoMsg): _239.SourceCodeInfo_Location;
            toProto(message: _239.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _239.SourceCodeInfo_Location): _239.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _239.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.GeneratedCodeInfo;
            fromPartial(object: Partial<_239.GeneratedCodeInfo>): _239.GeneratedCodeInfo;
            fromAmino(object: _239.GeneratedCodeInfoAmino): _239.GeneratedCodeInfo;
            toAmino(message: _239.GeneratedCodeInfo): _239.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _239.GeneratedCodeInfoAminoMsg): _239.GeneratedCodeInfo;
            fromProtoMsg(message: _239.GeneratedCodeInfoProtoMsg): _239.GeneratedCodeInfo;
            toProto(message: _239.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _239.GeneratedCodeInfo): _239.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _239.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _239.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_239.GeneratedCodeInfo_Annotation>): _239.GeneratedCodeInfo_Annotation;
            fromAmino(object: _239.GeneratedCodeInfo_AnnotationAmino): _239.GeneratedCodeInfo_Annotation;
            toAmino(message: _239.GeneratedCodeInfo_Annotation): _239.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _239.GeneratedCodeInfo_AnnotationAminoMsg): _239.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _239.GeneratedCodeInfo_AnnotationProtoMsg): _239.GeneratedCodeInfo_Annotation;
            toProto(message: _239.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _239.GeneratedCodeInfo_Annotation): _239.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _238.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _238.Any;
            fromPartial(object: Partial<_238.Any>): _238.Any;
            fromAmino(object: _238.AnyAmino): _238.Any;
            toAmino(message: _238.Any): _238.AnyAmino;
            fromAminoMsg(object: _238.AnyAminoMsg): _238.Any;
            fromProtoMsg(message: _238.AnyProtoMsg): _238.Any;
            toProto(message: _238.Any): Uint8Array;
            toProtoMsg(message: _238.Any): _238.AnyProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _237.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _237.Timestamp;
            fromPartial(object: Partial<_237.Timestamp>): _237.Timestamp;
            fromAmino(object: string): _237.Timestamp;
            toAmino(message: _237.Timestamp): string;
            fromAminoMsg(object: _237.TimestampAminoMsg): _237.Timestamp;
            fromProtoMsg(message: _237.TimestampProtoMsg): _237.Timestamp;
            toProto(message: _237.Timestamp): Uint8Array;
            toProtoMsg(message: _237.Timestamp): _237.TimestampProtoMsg;
        };
    };
}
