import * as _157 from "./api/http";
import * as _158 from "./protobuf/timestamp";
import * as _159 from "./protobuf/any";
import * as _160 from "./protobuf/duration";
import * as _161 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _157.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _157.Http;
            fromPartial(object: Partial<_157.Http>): _157.Http;
            fromAmino(object: _157.HttpAmino): _157.Http;
            toAmino(message: _157.Http): _157.HttpAmino;
            fromAminoMsg(object: _157.HttpAminoMsg): _157.Http;
            fromProtoMsg(message: _157.HttpProtoMsg): _157.Http;
            toProto(message: _157.Http): Uint8Array;
            toProtoMsg(message: _157.Http): _157.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _157.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _157.HttpRule;
            fromPartial(object: Partial<_157.HttpRule>): _157.HttpRule;
            fromAmino(object: _157.HttpRuleAmino): _157.HttpRule;
            toAmino(message: _157.HttpRule): _157.HttpRuleAmino;
            fromAminoMsg(object: _157.HttpRuleAminoMsg): _157.HttpRule;
            fromProtoMsg(message: _157.HttpRuleProtoMsg): _157.HttpRule;
            toProto(message: _157.HttpRule): Uint8Array;
            toProtoMsg(message: _157.HttpRule): _157.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _157.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _157.CustomHttpPattern;
            fromPartial(object: Partial<_157.CustomHttpPattern>): _157.CustomHttpPattern;
            fromAmino(object: _157.CustomHttpPatternAmino): _157.CustomHttpPattern;
            toAmino(message: _157.CustomHttpPattern): _157.CustomHttpPatternAmino;
            fromAminoMsg(object: _157.CustomHttpPatternAminoMsg): _157.CustomHttpPattern;
            fromProtoMsg(message: _157.CustomHttpPatternProtoMsg): _157.CustomHttpPattern;
            toProto(message: _157.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _157.CustomHttpPattern): _157.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _161.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _161.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _161.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _161.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _161.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _161.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _161.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _161.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _161.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _161.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _161.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _161.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _161.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _161.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _161.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _161.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _161.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _161.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _161.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _161.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _161.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _161.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _161.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _161.FieldOptions_CType;
        FieldOptions_JSType: typeof _161.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _161.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _161.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _161.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _161.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _161.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _161.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.FileDescriptorSet;
            fromPartial(object: Partial<_161.FileDescriptorSet>): _161.FileDescriptorSet;
            fromAmino(object: _161.FileDescriptorSetAmino): _161.FileDescriptorSet;
            toAmino(message: _161.FileDescriptorSet): _161.FileDescriptorSetAmino;
            fromAminoMsg(object: _161.FileDescriptorSetAminoMsg): _161.FileDescriptorSet;
            fromProtoMsg(message: _161.FileDescriptorSetProtoMsg): _161.FileDescriptorSet;
            toProto(message: _161.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _161.FileDescriptorSet): _161.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _161.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.FileDescriptorProto;
            fromPartial(object: Partial<_161.FileDescriptorProto>): _161.FileDescriptorProto;
            fromAmino(object: _161.FileDescriptorProtoAmino): _161.FileDescriptorProto;
            toAmino(message: _161.FileDescriptorProto): _161.FileDescriptorProtoAmino;
            fromAminoMsg(object: _161.FileDescriptorProtoAminoMsg): _161.FileDescriptorProto;
            fromProtoMsg(message: _161.FileDescriptorProtoProtoMsg): _161.FileDescriptorProto;
            toProto(message: _161.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _161.FileDescriptorProto): _161.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _161.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.DescriptorProto;
            fromPartial(object: Partial<_161.DescriptorProto>): _161.DescriptorProto;
            fromAmino(object: _161.DescriptorProtoAmino): _161.DescriptorProto;
            toAmino(message: _161.DescriptorProto): _161.DescriptorProtoAmino;
            fromAminoMsg(object: _161.DescriptorProtoAminoMsg): _161.DescriptorProto;
            fromProtoMsg(message: _161.DescriptorProtoProtoMsg): _161.DescriptorProto;
            toProto(message: _161.DescriptorProto): Uint8Array;
            toProtoMsg(message: _161.DescriptorProto): _161.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _161.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_161.DescriptorProto_ExtensionRange>): _161.DescriptorProto_ExtensionRange;
            fromAmino(object: _161.DescriptorProto_ExtensionRangeAmino): _161.DescriptorProto_ExtensionRange;
            toAmino(message: _161.DescriptorProto_ExtensionRange): _161.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _161.DescriptorProto_ExtensionRangeAminoMsg): _161.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _161.DescriptorProto_ExtensionRangeProtoMsg): _161.DescriptorProto_ExtensionRange;
            toProto(message: _161.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _161.DescriptorProto_ExtensionRange): _161.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _161.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_161.DescriptorProto_ReservedRange>): _161.DescriptorProto_ReservedRange;
            fromAmino(object: _161.DescriptorProto_ReservedRangeAmino): _161.DescriptorProto_ReservedRange;
            toAmino(message: _161.DescriptorProto_ReservedRange): _161.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _161.DescriptorProto_ReservedRangeAminoMsg): _161.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _161.DescriptorProto_ReservedRangeProtoMsg): _161.DescriptorProto_ReservedRange;
            toProto(message: _161.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _161.DescriptorProto_ReservedRange): _161.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _161.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.ExtensionRangeOptions;
            fromPartial(object: Partial<_161.ExtensionRangeOptions>): _161.ExtensionRangeOptions;
            fromAmino(object: _161.ExtensionRangeOptionsAmino): _161.ExtensionRangeOptions;
            toAmino(message: _161.ExtensionRangeOptions): _161.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _161.ExtensionRangeOptionsAminoMsg): _161.ExtensionRangeOptions;
            fromProtoMsg(message: _161.ExtensionRangeOptionsProtoMsg): _161.ExtensionRangeOptions;
            toProto(message: _161.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _161.ExtensionRangeOptions): _161.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _161.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.FieldDescriptorProto;
            fromPartial(object: Partial<_161.FieldDescriptorProto>): _161.FieldDescriptorProto;
            fromAmino(object: _161.FieldDescriptorProtoAmino): _161.FieldDescriptorProto;
            toAmino(message: _161.FieldDescriptorProto): _161.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _161.FieldDescriptorProtoAminoMsg): _161.FieldDescriptorProto;
            fromProtoMsg(message: _161.FieldDescriptorProtoProtoMsg): _161.FieldDescriptorProto;
            toProto(message: _161.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _161.FieldDescriptorProto): _161.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _161.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.OneofDescriptorProto;
            fromPartial(object: Partial<_161.OneofDescriptorProto>): _161.OneofDescriptorProto;
            fromAmino(object: _161.OneofDescriptorProtoAmino): _161.OneofDescriptorProto;
            toAmino(message: _161.OneofDescriptorProto): _161.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _161.OneofDescriptorProtoAminoMsg): _161.OneofDescriptorProto;
            fromProtoMsg(message: _161.OneofDescriptorProtoProtoMsg): _161.OneofDescriptorProto;
            toProto(message: _161.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _161.OneofDescriptorProto): _161.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _161.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.EnumDescriptorProto;
            fromPartial(object: Partial<_161.EnumDescriptorProto>): _161.EnumDescriptorProto;
            fromAmino(object: _161.EnumDescriptorProtoAmino): _161.EnumDescriptorProto;
            toAmino(message: _161.EnumDescriptorProto): _161.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _161.EnumDescriptorProtoAminoMsg): _161.EnumDescriptorProto;
            fromProtoMsg(message: _161.EnumDescriptorProtoProtoMsg): _161.EnumDescriptorProto;
            toProto(message: _161.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _161.EnumDescriptorProto): _161.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _161.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_161.EnumDescriptorProto_EnumReservedRange>): _161.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _161.EnumDescriptorProto_EnumReservedRangeAmino): _161.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _161.EnumDescriptorProto_EnumReservedRange): _161.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _161.EnumDescriptorProto_EnumReservedRangeAminoMsg): _161.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _161.EnumDescriptorProto_EnumReservedRangeProtoMsg): _161.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _161.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _161.EnumDescriptorProto_EnumReservedRange): _161.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _161.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.EnumValueDescriptorProto;
            fromPartial(object: Partial<_161.EnumValueDescriptorProto>): _161.EnumValueDescriptorProto;
            fromAmino(object: _161.EnumValueDescriptorProtoAmino): _161.EnumValueDescriptorProto;
            toAmino(message: _161.EnumValueDescriptorProto): _161.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _161.EnumValueDescriptorProtoAminoMsg): _161.EnumValueDescriptorProto;
            fromProtoMsg(message: _161.EnumValueDescriptorProtoProtoMsg): _161.EnumValueDescriptorProto;
            toProto(message: _161.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _161.EnumValueDescriptorProto): _161.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _161.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.ServiceDescriptorProto;
            fromPartial(object: Partial<_161.ServiceDescriptorProto>): _161.ServiceDescriptorProto;
            fromAmino(object: _161.ServiceDescriptorProtoAmino): _161.ServiceDescriptorProto;
            toAmino(message: _161.ServiceDescriptorProto): _161.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _161.ServiceDescriptorProtoAminoMsg): _161.ServiceDescriptorProto;
            fromProtoMsg(message: _161.ServiceDescriptorProtoProtoMsg): _161.ServiceDescriptorProto;
            toProto(message: _161.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _161.ServiceDescriptorProto): _161.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _161.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.MethodDescriptorProto;
            fromPartial(object: Partial<_161.MethodDescriptorProto>): _161.MethodDescriptorProto;
            fromAmino(object: _161.MethodDescriptorProtoAmino): _161.MethodDescriptorProto;
            toAmino(message: _161.MethodDescriptorProto): _161.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _161.MethodDescriptorProtoAminoMsg): _161.MethodDescriptorProto;
            fromProtoMsg(message: _161.MethodDescriptorProtoProtoMsg): _161.MethodDescriptorProto;
            toProto(message: _161.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _161.MethodDescriptorProto): _161.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _161.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.FileOptions;
            fromPartial(object: Partial<_161.FileOptions>): _161.FileOptions;
            fromAmino(object: _161.FileOptionsAmino): _161.FileOptions;
            toAmino(message: _161.FileOptions): _161.FileOptionsAmino;
            fromAminoMsg(object: _161.FileOptionsAminoMsg): _161.FileOptions;
            fromProtoMsg(message: _161.FileOptionsProtoMsg): _161.FileOptions;
            toProto(message: _161.FileOptions): Uint8Array;
            toProtoMsg(message: _161.FileOptions): _161.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _161.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.MessageOptions;
            fromPartial(object: Partial<_161.MessageOptions>): _161.MessageOptions;
            fromAmino(object: _161.MessageOptionsAmino): _161.MessageOptions;
            toAmino(message: _161.MessageOptions): _161.MessageOptionsAmino;
            fromAminoMsg(object: _161.MessageOptionsAminoMsg): _161.MessageOptions;
            fromProtoMsg(message: _161.MessageOptionsProtoMsg): _161.MessageOptions;
            toProto(message: _161.MessageOptions): Uint8Array;
            toProtoMsg(message: _161.MessageOptions): _161.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _161.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.FieldOptions;
            fromPartial(object: Partial<_161.FieldOptions>): _161.FieldOptions;
            fromAmino(object: _161.FieldOptionsAmino): _161.FieldOptions;
            toAmino(message: _161.FieldOptions): _161.FieldOptionsAmino;
            fromAminoMsg(object: _161.FieldOptionsAminoMsg): _161.FieldOptions;
            fromProtoMsg(message: _161.FieldOptionsProtoMsg): _161.FieldOptions;
            toProto(message: _161.FieldOptions): Uint8Array;
            toProtoMsg(message: _161.FieldOptions): _161.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _161.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.OneofOptions;
            fromPartial(object: Partial<_161.OneofOptions>): _161.OneofOptions;
            fromAmino(object: _161.OneofOptionsAmino): _161.OneofOptions;
            toAmino(message: _161.OneofOptions): _161.OneofOptionsAmino;
            fromAminoMsg(object: _161.OneofOptionsAminoMsg): _161.OneofOptions;
            fromProtoMsg(message: _161.OneofOptionsProtoMsg): _161.OneofOptions;
            toProto(message: _161.OneofOptions): Uint8Array;
            toProtoMsg(message: _161.OneofOptions): _161.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _161.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.EnumOptions;
            fromPartial(object: Partial<_161.EnumOptions>): _161.EnumOptions;
            fromAmino(object: _161.EnumOptionsAmino): _161.EnumOptions;
            toAmino(message: _161.EnumOptions): _161.EnumOptionsAmino;
            fromAminoMsg(object: _161.EnumOptionsAminoMsg): _161.EnumOptions;
            fromProtoMsg(message: _161.EnumOptionsProtoMsg): _161.EnumOptions;
            toProto(message: _161.EnumOptions): Uint8Array;
            toProtoMsg(message: _161.EnumOptions): _161.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _161.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.EnumValueOptions;
            fromPartial(object: Partial<_161.EnumValueOptions>): _161.EnumValueOptions;
            fromAmino(object: _161.EnumValueOptionsAmino): _161.EnumValueOptions;
            toAmino(message: _161.EnumValueOptions): _161.EnumValueOptionsAmino;
            fromAminoMsg(object: _161.EnumValueOptionsAminoMsg): _161.EnumValueOptions;
            fromProtoMsg(message: _161.EnumValueOptionsProtoMsg): _161.EnumValueOptions;
            toProto(message: _161.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _161.EnumValueOptions): _161.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _161.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.ServiceOptions;
            fromPartial(object: Partial<_161.ServiceOptions>): _161.ServiceOptions;
            fromAmino(object: _161.ServiceOptionsAmino): _161.ServiceOptions;
            toAmino(message: _161.ServiceOptions): _161.ServiceOptionsAmino;
            fromAminoMsg(object: _161.ServiceOptionsAminoMsg): _161.ServiceOptions;
            fromProtoMsg(message: _161.ServiceOptionsProtoMsg): _161.ServiceOptions;
            toProto(message: _161.ServiceOptions): Uint8Array;
            toProtoMsg(message: _161.ServiceOptions): _161.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _161.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.MethodOptions;
            fromPartial(object: Partial<_161.MethodOptions>): _161.MethodOptions;
            fromAmino(object: _161.MethodOptionsAmino): _161.MethodOptions;
            toAmino(message: _161.MethodOptions): _161.MethodOptionsAmino;
            fromAminoMsg(object: _161.MethodOptionsAminoMsg): _161.MethodOptions;
            fromProtoMsg(message: _161.MethodOptionsProtoMsg): _161.MethodOptions;
            toProto(message: _161.MethodOptions): Uint8Array;
            toProtoMsg(message: _161.MethodOptions): _161.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _161.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.UninterpretedOption;
            fromPartial(object: Partial<_161.UninterpretedOption>): _161.UninterpretedOption;
            fromAmino(object: _161.UninterpretedOptionAmino): _161.UninterpretedOption;
            toAmino(message: _161.UninterpretedOption): _161.UninterpretedOptionAmino;
            fromAminoMsg(object: _161.UninterpretedOptionAminoMsg): _161.UninterpretedOption;
            fromProtoMsg(message: _161.UninterpretedOptionProtoMsg): _161.UninterpretedOption;
            toProto(message: _161.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _161.UninterpretedOption): _161.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _161.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_161.UninterpretedOption_NamePart>): _161.UninterpretedOption_NamePart;
            fromAmino(object: _161.UninterpretedOption_NamePartAmino): _161.UninterpretedOption_NamePart;
            toAmino(message: _161.UninterpretedOption_NamePart): _161.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _161.UninterpretedOption_NamePartAminoMsg): _161.UninterpretedOption_NamePart;
            fromProtoMsg(message: _161.UninterpretedOption_NamePartProtoMsg): _161.UninterpretedOption_NamePart;
            toProto(message: _161.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _161.UninterpretedOption_NamePart): _161.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _161.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.SourceCodeInfo;
            fromPartial(object: Partial<_161.SourceCodeInfo>): _161.SourceCodeInfo;
            fromAmino(object: _161.SourceCodeInfoAmino): _161.SourceCodeInfo;
            toAmino(message: _161.SourceCodeInfo): _161.SourceCodeInfoAmino;
            fromAminoMsg(object: _161.SourceCodeInfoAminoMsg): _161.SourceCodeInfo;
            fromProtoMsg(message: _161.SourceCodeInfoProtoMsg): _161.SourceCodeInfo;
            toProto(message: _161.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _161.SourceCodeInfo): _161.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _161.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.SourceCodeInfo_Location;
            fromPartial(object: Partial<_161.SourceCodeInfo_Location>): _161.SourceCodeInfo_Location;
            fromAmino(object: _161.SourceCodeInfo_LocationAmino): _161.SourceCodeInfo_Location;
            toAmino(message: _161.SourceCodeInfo_Location): _161.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _161.SourceCodeInfo_LocationAminoMsg): _161.SourceCodeInfo_Location;
            fromProtoMsg(message: _161.SourceCodeInfo_LocationProtoMsg): _161.SourceCodeInfo_Location;
            toProto(message: _161.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _161.SourceCodeInfo_Location): _161.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _161.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.GeneratedCodeInfo;
            fromPartial(object: Partial<_161.GeneratedCodeInfo>): _161.GeneratedCodeInfo;
            fromAmino(object: _161.GeneratedCodeInfoAmino): _161.GeneratedCodeInfo;
            toAmino(message: _161.GeneratedCodeInfo): _161.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _161.GeneratedCodeInfoAminoMsg): _161.GeneratedCodeInfo;
            fromProtoMsg(message: _161.GeneratedCodeInfoProtoMsg): _161.GeneratedCodeInfo;
            toProto(message: _161.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _161.GeneratedCodeInfo): _161.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _161.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _161.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_161.GeneratedCodeInfo_Annotation>): _161.GeneratedCodeInfo_Annotation;
            fromAmino(object: _161.GeneratedCodeInfo_AnnotationAmino): _161.GeneratedCodeInfo_Annotation;
            toAmino(message: _161.GeneratedCodeInfo_Annotation): _161.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _161.GeneratedCodeInfo_AnnotationAminoMsg): _161.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _161.GeneratedCodeInfo_AnnotationProtoMsg): _161.GeneratedCodeInfo_Annotation;
            toProto(message: _161.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _161.GeneratedCodeInfo_Annotation): _161.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _160.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _160.Duration;
            fromPartial(object: Partial<_160.Duration>): _160.Duration;
            fromAmino(object: string): _160.Duration;
            toAmino(message: _160.Duration): string;
            fromAminoMsg(object: _160.DurationAminoMsg): _160.Duration;
            fromProtoMsg(message: _160.DurationProtoMsg): _160.Duration;
            toProto(message: _160.Duration): Uint8Array;
            toProtoMsg(message: _160.Duration): _160.DurationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _159.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _159.Any;
            fromPartial(object: Partial<_159.Any>): _159.Any;
            fromAmino(object: _159.AnyAmino): _159.Any;
            toAmino(message: _159.Any): _159.AnyAmino;
            fromAminoMsg(object: _159.AnyAminoMsg): _159.Any;
            fromProtoMsg(message: _159.AnyProtoMsg): _159.Any;
            toProto(message: _159.Any): Uint8Array;
            toProtoMsg(message: _159.Any): _159.AnyProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _158.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _158.Timestamp;
            fromPartial(object: Partial<_158.Timestamp>): _158.Timestamp;
            fromAmino(object: string): _158.Timestamp;
            toAmino(message: _158.Timestamp): string;
            fromAminoMsg(object: _158.TimestampAminoMsg): _158.Timestamp;
            fromProtoMsg(message: _158.TimestampProtoMsg): _158.Timestamp;
            toProto(message: _158.Timestamp): Uint8Array;
            toProtoMsg(message: _158.Timestamp): _158.TimestampProtoMsg;
        };
    };
}
