import * as _188 from "./api/http";
import * as _189 from "./protobuf/descriptor";
import * as _190 from "./protobuf/any";
import * as _191 from "./protobuf/timestamp";
import * as _192 from "./protobuf/duration";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _188.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _188.Http;
            fromPartial(object: Partial<_188.Http>): _188.Http;
            fromAmino(object: _188.HttpAmino): _188.Http;
            toAmino(message: _188.Http): _188.HttpAmino;
            fromAminoMsg(object: _188.HttpAminoMsg): _188.Http;
            fromProtoMsg(message: _188.HttpProtoMsg): _188.Http;
            toProto(message: _188.Http): Uint8Array;
            toProtoMsg(message: _188.Http): _188.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _188.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _188.HttpRule;
            fromPartial(object: Partial<_188.HttpRule>): _188.HttpRule;
            fromAmino(object: _188.HttpRuleAmino): _188.HttpRule;
            toAmino(message: _188.HttpRule): _188.HttpRuleAmino;
            fromAminoMsg(object: _188.HttpRuleAminoMsg): _188.HttpRule;
            fromProtoMsg(message: _188.HttpRuleProtoMsg): _188.HttpRule;
            toProto(message: _188.HttpRule): Uint8Array;
            toProtoMsg(message: _188.HttpRule): _188.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _188.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _188.CustomHttpPattern;
            fromPartial(object: Partial<_188.CustomHttpPattern>): _188.CustomHttpPattern;
            fromAmino(object: _188.CustomHttpPatternAmino): _188.CustomHttpPattern;
            toAmino(message: _188.CustomHttpPattern): _188.CustomHttpPatternAmino;
            fromAminoMsg(object: _188.CustomHttpPatternAminoMsg): _188.CustomHttpPattern;
            fromProtoMsg(message: _188.CustomHttpPatternProtoMsg): _188.CustomHttpPattern;
            toProto(message: _188.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _188.CustomHttpPattern): _188.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Duration: {
            typeUrl: string;
            encode(message: _192.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _192.Duration;
            fromPartial(object: Partial<_192.Duration>): _192.Duration;
            fromAmino(object: string): _192.Duration;
            toAmino(message: _192.Duration): string;
            fromAminoMsg(object: _192.DurationAminoMsg): _192.Duration;
            fromProtoMsg(message: _192.DurationProtoMsg): _192.Duration;
            toProto(message: _192.Duration): Uint8Array;
            toProtoMsg(message: _192.Duration): _192.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _191.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _191.Timestamp;
            fromPartial(object: Partial<_191.Timestamp>): _191.Timestamp;
            fromAmino(object: string): _191.Timestamp;
            toAmino(message: _191.Timestamp): string;
            fromAminoMsg(object: _191.TimestampAminoMsg): _191.Timestamp;
            fromProtoMsg(message: _191.TimestampProtoMsg): _191.Timestamp;
            toProto(message: _191.Timestamp): Uint8Array;
            toProtoMsg(message: _191.Timestamp): _191.TimestampProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _190.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _190.Any;
            fromPartial(object: Partial<_190.Any>): _190.Any;
            fromAmino(object: _190.AnyAmino): _190.Any;
            toAmino(message: _190.Any): _190.AnyAmino;
            fromAminoMsg(object: _190.AnyAminoMsg): _190.Any;
            fromProtoMsg(message: _190.AnyProtoMsg): _190.Any;
            toProto(message: _190.Any): Uint8Array;
            toProtoMsg(message: _190.Any): _190.AnyProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _189.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _189.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _189.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _189.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _189.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _189.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _189.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _189.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _189.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _189.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _189.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _189.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _189.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _189.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _189.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _189.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _189.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _189.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _189.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _189.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _189.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _189.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _189.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _189.FieldOptions_CType;
        FieldOptions_JSType: typeof _189.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _189.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _189.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _189.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _189.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _189.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _189.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.FileDescriptorSet;
            fromPartial(object: Partial<_189.FileDescriptorSet>): _189.FileDescriptorSet;
            fromAmino(object: _189.FileDescriptorSetAmino): _189.FileDescriptorSet;
            toAmino(message: _189.FileDescriptorSet): _189.FileDescriptorSetAmino;
            fromAminoMsg(object: _189.FileDescriptorSetAminoMsg): _189.FileDescriptorSet;
            fromProtoMsg(message: _189.FileDescriptorSetProtoMsg): _189.FileDescriptorSet;
            toProto(message: _189.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _189.FileDescriptorSet): _189.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _189.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.FileDescriptorProto;
            fromPartial(object: Partial<_189.FileDescriptorProto>): _189.FileDescriptorProto;
            fromAmino(object: _189.FileDescriptorProtoAmino): _189.FileDescriptorProto;
            toAmino(message: _189.FileDescriptorProto): _189.FileDescriptorProtoAmino;
            fromAminoMsg(object: _189.FileDescriptorProtoAminoMsg): _189.FileDescriptorProto;
            fromProtoMsg(message: _189.FileDescriptorProtoProtoMsg): _189.FileDescriptorProto;
            toProto(message: _189.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _189.FileDescriptorProto): _189.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _189.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.DescriptorProto;
            fromPartial(object: Partial<_189.DescriptorProto>): _189.DescriptorProto;
            fromAmino(object: _189.DescriptorProtoAmino): _189.DescriptorProto;
            toAmino(message: _189.DescriptorProto): _189.DescriptorProtoAmino;
            fromAminoMsg(object: _189.DescriptorProtoAminoMsg): _189.DescriptorProto;
            fromProtoMsg(message: _189.DescriptorProtoProtoMsg): _189.DescriptorProto;
            toProto(message: _189.DescriptorProto): Uint8Array;
            toProtoMsg(message: _189.DescriptorProto): _189.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _189.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_189.DescriptorProto_ExtensionRange>): _189.DescriptorProto_ExtensionRange;
            fromAmino(object: _189.DescriptorProto_ExtensionRangeAmino): _189.DescriptorProto_ExtensionRange;
            toAmino(message: _189.DescriptorProto_ExtensionRange): _189.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _189.DescriptorProto_ExtensionRangeAminoMsg): _189.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _189.DescriptorProto_ExtensionRangeProtoMsg): _189.DescriptorProto_ExtensionRange;
            toProto(message: _189.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _189.DescriptorProto_ExtensionRange): _189.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _189.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_189.DescriptorProto_ReservedRange>): _189.DescriptorProto_ReservedRange;
            fromAmino(object: _189.DescriptorProto_ReservedRangeAmino): _189.DescriptorProto_ReservedRange;
            toAmino(message: _189.DescriptorProto_ReservedRange): _189.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _189.DescriptorProto_ReservedRangeAminoMsg): _189.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _189.DescriptorProto_ReservedRangeProtoMsg): _189.DescriptorProto_ReservedRange;
            toProto(message: _189.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _189.DescriptorProto_ReservedRange): _189.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _189.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.ExtensionRangeOptions;
            fromPartial(object: Partial<_189.ExtensionRangeOptions>): _189.ExtensionRangeOptions;
            fromAmino(object: _189.ExtensionRangeOptionsAmino): _189.ExtensionRangeOptions;
            toAmino(message: _189.ExtensionRangeOptions): _189.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _189.ExtensionRangeOptionsAminoMsg): _189.ExtensionRangeOptions;
            fromProtoMsg(message: _189.ExtensionRangeOptionsProtoMsg): _189.ExtensionRangeOptions;
            toProto(message: _189.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _189.ExtensionRangeOptions): _189.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _189.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.FieldDescriptorProto;
            fromPartial(object: Partial<_189.FieldDescriptorProto>): _189.FieldDescriptorProto;
            fromAmino(object: _189.FieldDescriptorProtoAmino): _189.FieldDescriptorProto;
            toAmino(message: _189.FieldDescriptorProto): _189.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _189.FieldDescriptorProtoAminoMsg): _189.FieldDescriptorProto;
            fromProtoMsg(message: _189.FieldDescriptorProtoProtoMsg): _189.FieldDescriptorProto;
            toProto(message: _189.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _189.FieldDescriptorProto): _189.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _189.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.OneofDescriptorProto;
            fromPartial(object: Partial<_189.OneofDescriptorProto>): _189.OneofDescriptorProto;
            fromAmino(object: _189.OneofDescriptorProtoAmino): _189.OneofDescriptorProto;
            toAmino(message: _189.OneofDescriptorProto): _189.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _189.OneofDescriptorProtoAminoMsg): _189.OneofDescriptorProto;
            fromProtoMsg(message: _189.OneofDescriptorProtoProtoMsg): _189.OneofDescriptorProto;
            toProto(message: _189.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _189.OneofDescriptorProto): _189.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _189.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.EnumDescriptorProto;
            fromPartial(object: Partial<_189.EnumDescriptorProto>): _189.EnumDescriptorProto;
            fromAmino(object: _189.EnumDescriptorProtoAmino): _189.EnumDescriptorProto;
            toAmino(message: _189.EnumDescriptorProto): _189.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _189.EnumDescriptorProtoAminoMsg): _189.EnumDescriptorProto;
            fromProtoMsg(message: _189.EnumDescriptorProtoProtoMsg): _189.EnumDescriptorProto;
            toProto(message: _189.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _189.EnumDescriptorProto): _189.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _189.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_189.EnumDescriptorProto_EnumReservedRange>): _189.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _189.EnumDescriptorProto_EnumReservedRangeAmino): _189.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _189.EnumDescriptorProto_EnumReservedRange): _189.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _189.EnumDescriptorProto_EnumReservedRangeAminoMsg): _189.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _189.EnumDescriptorProto_EnumReservedRangeProtoMsg): _189.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _189.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _189.EnumDescriptorProto_EnumReservedRange): _189.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _189.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.EnumValueDescriptorProto;
            fromPartial(object: Partial<_189.EnumValueDescriptorProto>): _189.EnumValueDescriptorProto;
            fromAmino(object: _189.EnumValueDescriptorProtoAmino): _189.EnumValueDescriptorProto;
            toAmino(message: _189.EnumValueDescriptorProto): _189.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _189.EnumValueDescriptorProtoAminoMsg): _189.EnumValueDescriptorProto;
            fromProtoMsg(message: _189.EnumValueDescriptorProtoProtoMsg): _189.EnumValueDescriptorProto;
            toProto(message: _189.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _189.EnumValueDescriptorProto): _189.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _189.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.ServiceDescriptorProto;
            fromPartial(object: Partial<_189.ServiceDescriptorProto>): _189.ServiceDescriptorProto;
            fromAmino(object: _189.ServiceDescriptorProtoAmino): _189.ServiceDescriptorProto;
            toAmino(message: _189.ServiceDescriptorProto): _189.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _189.ServiceDescriptorProtoAminoMsg): _189.ServiceDescriptorProto;
            fromProtoMsg(message: _189.ServiceDescriptorProtoProtoMsg): _189.ServiceDescriptorProto;
            toProto(message: _189.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _189.ServiceDescriptorProto): _189.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _189.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.MethodDescriptorProto;
            fromPartial(object: Partial<_189.MethodDescriptorProto>): _189.MethodDescriptorProto;
            fromAmino(object: _189.MethodDescriptorProtoAmino): _189.MethodDescriptorProto;
            toAmino(message: _189.MethodDescriptorProto): _189.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _189.MethodDescriptorProtoAminoMsg): _189.MethodDescriptorProto;
            fromProtoMsg(message: _189.MethodDescriptorProtoProtoMsg): _189.MethodDescriptorProto;
            toProto(message: _189.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _189.MethodDescriptorProto): _189.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _189.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.FileOptions;
            fromPartial(object: Partial<_189.FileOptions>): _189.FileOptions;
            fromAmino(object: _189.FileOptionsAmino): _189.FileOptions;
            toAmino(message: _189.FileOptions): _189.FileOptionsAmino;
            fromAminoMsg(object: _189.FileOptionsAminoMsg): _189.FileOptions;
            fromProtoMsg(message: _189.FileOptionsProtoMsg): _189.FileOptions;
            toProto(message: _189.FileOptions): Uint8Array;
            toProtoMsg(message: _189.FileOptions): _189.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _189.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.MessageOptions;
            fromPartial(object: Partial<_189.MessageOptions>): _189.MessageOptions;
            fromAmino(object: _189.MessageOptionsAmino): _189.MessageOptions;
            toAmino(message: _189.MessageOptions): _189.MessageOptionsAmino;
            fromAminoMsg(object: _189.MessageOptionsAminoMsg): _189.MessageOptions;
            fromProtoMsg(message: _189.MessageOptionsProtoMsg): _189.MessageOptions;
            toProto(message: _189.MessageOptions): Uint8Array;
            toProtoMsg(message: _189.MessageOptions): _189.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _189.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.FieldOptions;
            fromPartial(object: Partial<_189.FieldOptions>): _189.FieldOptions;
            fromAmino(object: _189.FieldOptionsAmino): _189.FieldOptions;
            toAmino(message: _189.FieldOptions): _189.FieldOptionsAmino;
            fromAminoMsg(object: _189.FieldOptionsAminoMsg): _189.FieldOptions;
            fromProtoMsg(message: _189.FieldOptionsProtoMsg): _189.FieldOptions;
            toProto(message: _189.FieldOptions): Uint8Array;
            toProtoMsg(message: _189.FieldOptions): _189.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _189.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.OneofOptions;
            fromPartial(object: Partial<_189.OneofOptions>): _189.OneofOptions;
            fromAmino(object: _189.OneofOptionsAmino): _189.OneofOptions;
            toAmino(message: _189.OneofOptions): _189.OneofOptionsAmino;
            fromAminoMsg(object: _189.OneofOptionsAminoMsg): _189.OneofOptions;
            fromProtoMsg(message: _189.OneofOptionsProtoMsg): _189.OneofOptions;
            toProto(message: _189.OneofOptions): Uint8Array;
            toProtoMsg(message: _189.OneofOptions): _189.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _189.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.EnumOptions;
            fromPartial(object: Partial<_189.EnumOptions>): _189.EnumOptions;
            fromAmino(object: _189.EnumOptionsAmino): _189.EnumOptions;
            toAmino(message: _189.EnumOptions): _189.EnumOptionsAmino;
            fromAminoMsg(object: _189.EnumOptionsAminoMsg): _189.EnumOptions;
            fromProtoMsg(message: _189.EnumOptionsProtoMsg): _189.EnumOptions;
            toProto(message: _189.EnumOptions): Uint8Array;
            toProtoMsg(message: _189.EnumOptions): _189.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _189.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.EnumValueOptions;
            fromPartial(object: Partial<_189.EnumValueOptions>): _189.EnumValueOptions;
            fromAmino(object: _189.EnumValueOptionsAmino): _189.EnumValueOptions;
            toAmino(message: _189.EnumValueOptions): _189.EnumValueOptionsAmino;
            fromAminoMsg(object: _189.EnumValueOptionsAminoMsg): _189.EnumValueOptions;
            fromProtoMsg(message: _189.EnumValueOptionsProtoMsg): _189.EnumValueOptions;
            toProto(message: _189.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _189.EnumValueOptions): _189.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _189.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.ServiceOptions;
            fromPartial(object: Partial<_189.ServiceOptions>): _189.ServiceOptions;
            fromAmino(object: _189.ServiceOptionsAmino): _189.ServiceOptions;
            toAmino(message: _189.ServiceOptions): _189.ServiceOptionsAmino;
            fromAminoMsg(object: _189.ServiceOptionsAminoMsg): _189.ServiceOptions;
            fromProtoMsg(message: _189.ServiceOptionsProtoMsg): _189.ServiceOptions;
            toProto(message: _189.ServiceOptions): Uint8Array;
            toProtoMsg(message: _189.ServiceOptions): _189.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _189.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.MethodOptions;
            fromPartial(object: Partial<_189.MethodOptions>): _189.MethodOptions;
            fromAmino(object: _189.MethodOptionsAmino): _189.MethodOptions;
            toAmino(message: _189.MethodOptions): _189.MethodOptionsAmino;
            fromAminoMsg(object: _189.MethodOptionsAminoMsg): _189.MethodOptions;
            fromProtoMsg(message: _189.MethodOptionsProtoMsg): _189.MethodOptions;
            toProto(message: _189.MethodOptions): Uint8Array;
            toProtoMsg(message: _189.MethodOptions): _189.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _189.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.UninterpretedOption;
            fromPartial(object: Partial<_189.UninterpretedOption>): _189.UninterpretedOption;
            fromAmino(object: _189.UninterpretedOptionAmino): _189.UninterpretedOption;
            toAmino(message: _189.UninterpretedOption): _189.UninterpretedOptionAmino;
            fromAminoMsg(object: _189.UninterpretedOptionAminoMsg): _189.UninterpretedOption;
            fromProtoMsg(message: _189.UninterpretedOptionProtoMsg): _189.UninterpretedOption;
            toProto(message: _189.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _189.UninterpretedOption): _189.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _189.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_189.UninterpretedOption_NamePart>): _189.UninterpretedOption_NamePart;
            fromAmino(object: _189.UninterpretedOption_NamePartAmino): _189.UninterpretedOption_NamePart;
            toAmino(message: _189.UninterpretedOption_NamePart): _189.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _189.UninterpretedOption_NamePartAminoMsg): _189.UninterpretedOption_NamePart;
            fromProtoMsg(message: _189.UninterpretedOption_NamePartProtoMsg): _189.UninterpretedOption_NamePart;
            toProto(message: _189.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _189.UninterpretedOption_NamePart): _189.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _189.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.SourceCodeInfo;
            fromPartial(object: Partial<_189.SourceCodeInfo>): _189.SourceCodeInfo;
            fromAmino(object: _189.SourceCodeInfoAmino): _189.SourceCodeInfo;
            toAmino(message: _189.SourceCodeInfo): _189.SourceCodeInfoAmino;
            fromAminoMsg(object: _189.SourceCodeInfoAminoMsg): _189.SourceCodeInfo;
            fromProtoMsg(message: _189.SourceCodeInfoProtoMsg): _189.SourceCodeInfo;
            toProto(message: _189.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _189.SourceCodeInfo): _189.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _189.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.SourceCodeInfo_Location;
            fromPartial(object: Partial<_189.SourceCodeInfo_Location>): _189.SourceCodeInfo_Location;
            fromAmino(object: _189.SourceCodeInfo_LocationAmino): _189.SourceCodeInfo_Location;
            toAmino(message: _189.SourceCodeInfo_Location): _189.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _189.SourceCodeInfo_LocationAminoMsg): _189.SourceCodeInfo_Location;
            fromProtoMsg(message: _189.SourceCodeInfo_LocationProtoMsg): _189.SourceCodeInfo_Location;
            toProto(message: _189.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _189.SourceCodeInfo_Location): _189.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _189.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.GeneratedCodeInfo;
            fromPartial(object: Partial<_189.GeneratedCodeInfo>): _189.GeneratedCodeInfo;
            fromAmino(object: _189.GeneratedCodeInfoAmino): _189.GeneratedCodeInfo;
            toAmino(message: _189.GeneratedCodeInfo): _189.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _189.GeneratedCodeInfoAminoMsg): _189.GeneratedCodeInfo;
            fromProtoMsg(message: _189.GeneratedCodeInfoProtoMsg): _189.GeneratedCodeInfo;
            toProto(message: _189.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _189.GeneratedCodeInfo): _189.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _189.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _189.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_189.GeneratedCodeInfo_Annotation>): _189.GeneratedCodeInfo_Annotation;
            fromAmino(object: _189.GeneratedCodeInfo_AnnotationAmino): _189.GeneratedCodeInfo_Annotation;
            toAmino(message: _189.GeneratedCodeInfo_Annotation): _189.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _189.GeneratedCodeInfo_AnnotationAminoMsg): _189.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _189.GeneratedCodeInfo_AnnotationProtoMsg): _189.GeneratedCodeInfo_Annotation;
            toProto(message: _189.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _189.GeneratedCodeInfo_Annotation): _189.GeneratedCodeInfo_AnnotationProtoMsg;
        };
    };
}
