import * as _81 from "./api/http";
import * as _82 from "./api/httpbody";
import * as _83 from "./protobuf/any";
import * as _84 from "./protobuf/timestamp";
import * as _85 from "./protobuf/descriptor";
import * as _86 from "./protobuf/duration";
export declare namespace google {
    const api: {
        HttpBody: {
            typeUrl: string;
            encode(message: _82.HttpBody, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _82.HttpBody;
            fromPartial(object: Partial<_82.HttpBody>): _82.HttpBody;
            fromAmino(object: _82.HttpBodyAmino): _82.HttpBody;
            toAmino(message: _82.HttpBody): _82.HttpBodyAmino;
            fromAminoMsg(object: _82.HttpBodyAminoMsg): _82.HttpBody;
            fromProtoMsg(message: _82.HttpBodyProtoMsg): _82.HttpBody;
            toProto(message: _82.HttpBody): Uint8Array;
            toProtoMsg(message: _82.HttpBody): _82.HttpBodyProtoMsg;
        };
        Http: {
            typeUrl: string;
            encode(message: _81.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _81.Http;
            fromPartial(object: Partial<_81.Http>): _81.Http;
            fromAmino(object: _81.HttpAmino): _81.Http;
            toAmino(message: _81.Http): _81.HttpAmino;
            fromAminoMsg(object: _81.HttpAminoMsg): _81.Http;
            fromProtoMsg(message: _81.HttpProtoMsg): _81.Http;
            toProto(message: _81.Http): Uint8Array;
            toProtoMsg(message: _81.Http): _81.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _81.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _81.HttpRule;
            fromPartial(object: Partial<_81.HttpRule>): _81.HttpRule;
            fromAmino(object: _81.HttpRuleAmino): _81.HttpRule;
            toAmino(message: _81.HttpRule): _81.HttpRuleAmino;
            fromAminoMsg(object: _81.HttpRuleAminoMsg): _81.HttpRule;
            fromProtoMsg(message: _81.HttpRuleProtoMsg): _81.HttpRule;
            toProto(message: _81.HttpRule): Uint8Array;
            toProtoMsg(message: _81.HttpRule): _81.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _81.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _81.CustomHttpPattern;
            fromPartial(object: Partial<_81.CustomHttpPattern>): _81.CustomHttpPattern;
            fromAmino(object: _81.CustomHttpPatternAmino): _81.CustomHttpPattern;
            toAmino(message: _81.CustomHttpPattern): _81.CustomHttpPatternAmino;
            fromAminoMsg(object: _81.CustomHttpPatternAminoMsg): _81.CustomHttpPattern;
            fromProtoMsg(message: _81.CustomHttpPatternProtoMsg): _81.CustomHttpPattern;
            toProto(message: _81.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _81.CustomHttpPattern): _81.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Duration: {
            typeUrl: string;
            encode(message: _86.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _86.Duration;
            fromPartial(object: Partial<_86.Duration>): _86.Duration;
            fromAmino(object: string): _86.Duration;
            toAmino(message: _86.Duration): string;
            fromAminoMsg(object: _86.DurationAminoMsg): _86.Duration;
            fromProtoMsg(message: _86.DurationProtoMsg): _86.Duration;
            toProto(message: _86.Duration): Uint8Array;
            toProtoMsg(message: _86.Duration): _86.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _85.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _85.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _85.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _85.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _85.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _85.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _85.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _85.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _85.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _85.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _85.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _85.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _85.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _85.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _85.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _85.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _85.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _85.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _85.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _85.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _85.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _85.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _85.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _85.FieldOptions_CType;
        FieldOptions_JSType: typeof _85.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _85.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _85.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _85.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _85.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _85.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _85.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.FileDescriptorSet;
            fromPartial(object: Partial<_85.FileDescriptorSet>): _85.FileDescriptorSet;
            fromAmino(object: _85.FileDescriptorSetAmino): _85.FileDescriptorSet;
            toAmino(message: _85.FileDescriptorSet): _85.FileDescriptorSetAmino;
            fromAminoMsg(object: _85.FileDescriptorSetAminoMsg): _85.FileDescriptorSet;
            fromProtoMsg(message: _85.FileDescriptorSetProtoMsg): _85.FileDescriptorSet;
            toProto(message: _85.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _85.FileDescriptorSet): _85.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _85.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.FileDescriptorProto;
            fromPartial(object: Partial<_85.FileDescriptorProto>): _85.FileDescriptorProto;
            fromAmino(object: _85.FileDescriptorProtoAmino): _85.FileDescriptorProto;
            toAmino(message: _85.FileDescriptorProto): _85.FileDescriptorProtoAmino;
            fromAminoMsg(object: _85.FileDescriptorProtoAminoMsg): _85.FileDescriptorProto;
            fromProtoMsg(message: _85.FileDescriptorProtoProtoMsg): _85.FileDescriptorProto;
            toProto(message: _85.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _85.FileDescriptorProto): _85.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _85.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.DescriptorProto;
            fromPartial(object: Partial<_85.DescriptorProto>): _85.DescriptorProto;
            fromAmino(object: _85.DescriptorProtoAmino): _85.DescriptorProto;
            toAmino(message: _85.DescriptorProto): _85.DescriptorProtoAmino;
            fromAminoMsg(object: _85.DescriptorProtoAminoMsg): _85.DescriptorProto;
            fromProtoMsg(message: _85.DescriptorProtoProtoMsg): _85.DescriptorProto;
            toProto(message: _85.DescriptorProto): Uint8Array;
            toProtoMsg(message: _85.DescriptorProto): _85.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _85.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_85.DescriptorProto_ExtensionRange>): _85.DescriptorProto_ExtensionRange;
            fromAmino(object: _85.DescriptorProto_ExtensionRangeAmino): _85.DescriptorProto_ExtensionRange;
            toAmino(message: _85.DescriptorProto_ExtensionRange): _85.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _85.DescriptorProto_ExtensionRangeAminoMsg): _85.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _85.DescriptorProto_ExtensionRangeProtoMsg): _85.DescriptorProto_ExtensionRange;
            toProto(message: _85.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _85.DescriptorProto_ExtensionRange): _85.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _85.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_85.DescriptorProto_ReservedRange>): _85.DescriptorProto_ReservedRange;
            fromAmino(object: _85.DescriptorProto_ReservedRangeAmino): _85.DescriptorProto_ReservedRange;
            toAmino(message: _85.DescriptorProto_ReservedRange): _85.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _85.DescriptorProto_ReservedRangeAminoMsg): _85.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _85.DescriptorProto_ReservedRangeProtoMsg): _85.DescriptorProto_ReservedRange;
            toProto(message: _85.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _85.DescriptorProto_ReservedRange): _85.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _85.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.ExtensionRangeOptions;
            fromPartial(object: Partial<_85.ExtensionRangeOptions>): _85.ExtensionRangeOptions;
            fromAmino(object: _85.ExtensionRangeOptionsAmino): _85.ExtensionRangeOptions;
            toAmino(message: _85.ExtensionRangeOptions): _85.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _85.ExtensionRangeOptionsAminoMsg): _85.ExtensionRangeOptions;
            fromProtoMsg(message: _85.ExtensionRangeOptionsProtoMsg): _85.ExtensionRangeOptions;
            toProto(message: _85.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _85.ExtensionRangeOptions): _85.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _85.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.FieldDescriptorProto;
            fromPartial(object: Partial<_85.FieldDescriptorProto>): _85.FieldDescriptorProto;
            fromAmino(object: _85.FieldDescriptorProtoAmino): _85.FieldDescriptorProto;
            toAmino(message: _85.FieldDescriptorProto): _85.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _85.FieldDescriptorProtoAminoMsg): _85.FieldDescriptorProto;
            fromProtoMsg(message: _85.FieldDescriptorProtoProtoMsg): _85.FieldDescriptorProto;
            toProto(message: _85.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _85.FieldDescriptorProto): _85.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _85.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.OneofDescriptorProto;
            fromPartial(object: Partial<_85.OneofDescriptorProto>): _85.OneofDescriptorProto;
            fromAmino(object: _85.OneofDescriptorProtoAmino): _85.OneofDescriptorProto;
            toAmino(message: _85.OneofDescriptorProto): _85.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _85.OneofDescriptorProtoAminoMsg): _85.OneofDescriptorProto;
            fromProtoMsg(message: _85.OneofDescriptorProtoProtoMsg): _85.OneofDescriptorProto;
            toProto(message: _85.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _85.OneofDescriptorProto): _85.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _85.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.EnumDescriptorProto;
            fromPartial(object: Partial<_85.EnumDescriptorProto>): _85.EnumDescriptorProto;
            fromAmino(object: _85.EnumDescriptorProtoAmino): _85.EnumDescriptorProto;
            toAmino(message: _85.EnumDescriptorProto): _85.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _85.EnumDescriptorProtoAminoMsg): _85.EnumDescriptorProto;
            fromProtoMsg(message: _85.EnumDescriptorProtoProtoMsg): _85.EnumDescriptorProto;
            toProto(message: _85.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _85.EnumDescriptorProto): _85.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _85.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_85.EnumDescriptorProto_EnumReservedRange>): _85.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _85.EnumDescriptorProto_EnumReservedRangeAmino): _85.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _85.EnumDescriptorProto_EnumReservedRange): _85.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _85.EnumDescriptorProto_EnumReservedRangeAminoMsg): _85.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _85.EnumDescriptorProto_EnumReservedRangeProtoMsg): _85.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _85.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _85.EnumDescriptorProto_EnumReservedRange): _85.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _85.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.EnumValueDescriptorProto;
            fromPartial(object: Partial<_85.EnumValueDescriptorProto>): _85.EnumValueDescriptorProto;
            fromAmino(object: _85.EnumValueDescriptorProtoAmino): _85.EnumValueDescriptorProto;
            toAmino(message: _85.EnumValueDescriptorProto): _85.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _85.EnumValueDescriptorProtoAminoMsg): _85.EnumValueDescriptorProto;
            fromProtoMsg(message: _85.EnumValueDescriptorProtoProtoMsg): _85.EnumValueDescriptorProto;
            toProto(message: _85.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _85.EnumValueDescriptorProto): _85.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _85.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.ServiceDescriptorProto;
            fromPartial(object: Partial<_85.ServiceDescriptorProto>): _85.ServiceDescriptorProto;
            fromAmino(object: _85.ServiceDescriptorProtoAmino): _85.ServiceDescriptorProto;
            toAmino(message: _85.ServiceDescriptorProto): _85.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _85.ServiceDescriptorProtoAminoMsg): _85.ServiceDescriptorProto;
            fromProtoMsg(message: _85.ServiceDescriptorProtoProtoMsg): _85.ServiceDescriptorProto;
            toProto(message: _85.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _85.ServiceDescriptorProto): _85.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _85.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.MethodDescriptorProto;
            fromPartial(object: Partial<_85.MethodDescriptorProto>): _85.MethodDescriptorProto;
            fromAmino(object: _85.MethodDescriptorProtoAmino): _85.MethodDescriptorProto;
            toAmino(message: _85.MethodDescriptorProto): _85.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _85.MethodDescriptorProtoAminoMsg): _85.MethodDescriptorProto;
            fromProtoMsg(message: _85.MethodDescriptorProtoProtoMsg): _85.MethodDescriptorProto;
            toProto(message: _85.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _85.MethodDescriptorProto): _85.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _85.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.FileOptions;
            fromPartial(object: Partial<_85.FileOptions>): _85.FileOptions;
            fromAmino(object: _85.FileOptionsAmino): _85.FileOptions;
            toAmino(message: _85.FileOptions): _85.FileOptionsAmino;
            fromAminoMsg(object: _85.FileOptionsAminoMsg): _85.FileOptions;
            fromProtoMsg(message: _85.FileOptionsProtoMsg): _85.FileOptions;
            toProto(message: _85.FileOptions): Uint8Array;
            toProtoMsg(message: _85.FileOptions): _85.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _85.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.MessageOptions;
            fromPartial(object: Partial<_85.MessageOptions>): _85.MessageOptions;
            fromAmino(object: _85.MessageOptionsAmino): _85.MessageOptions;
            toAmino(message: _85.MessageOptions): _85.MessageOptionsAmino;
            fromAminoMsg(object: _85.MessageOptionsAminoMsg): _85.MessageOptions;
            fromProtoMsg(message: _85.MessageOptionsProtoMsg): _85.MessageOptions;
            toProto(message: _85.MessageOptions): Uint8Array;
            toProtoMsg(message: _85.MessageOptions): _85.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _85.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.FieldOptions;
            fromPartial(object: Partial<_85.FieldOptions>): _85.FieldOptions;
            fromAmino(object: _85.FieldOptionsAmino): _85.FieldOptions;
            toAmino(message: _85.FieldOptions): _85.FieldOptionsAmino;
            fromAminoMsg(object: _85.FieldOptionsAminoMsg): _85.FieldOptions;
            fromProtoMsg(message: _85.FieldOptionsProtoMsg): _85.FieldOptions;
            toProto(message: _85.FieldOptions): Uint8Array;
            toProtoMsg(message: _85.FieldOptions): _85.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _85.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.OneofOptions;
            fromPartial(object: Partial<_85.OneofOptions>): _85.OneofOptions;
            fromAmino(object: _85.OneofOptionsAmino): _85.OneofOptions;
            toAmino(message: _85.OneofOptions): _85.OneofOptionsAmino;
            fromAminoMsg(object: _85.OneofOptionsAminoMsg): _85.OneofOptions;
            fromProtoMsg(message: _85.OneofOptionsProtoMsg): _85.OneofOptions;
            toProto(message: _85.OneofOptions): Uint8Array;
            toProtoMsg(message: _85.OneofOptions): _85.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _85.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.EnumOptions;
            fromPartial(object: Partial<_85.EnumOptions>): _85.EnumOptions;
            fromAmino(object: _85.EnumOptionsAmino): _85.EnumOptions;
            toAmino(message: _85.EnumOptions): _85.EnumOptionsAmino;
            fromAminoMsg(object: _85.EnumOptionsAminoMsg): _85.EnumOptions;
            fromProtoMsg(message: _85.EnumOptionsProtoMsg): _85.EnumOptions;
            toProto(message: _85.EnumOptions): Uint8Array;
            toProtoMsg(message: _85.EnumOptions): _85.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _85.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.EnumValueOptions;
            fromPartial(object: Partial<_85.EnumValueOptions>): _85.EnumValueOptions;
            fromAmino(object: _85.EnumValueOptionsAmino): _85.EnumValueOptions;
            toAmino(message: _85.EnumValueOptions): _85.EnumValueOptionsAmino;
            fromAminoMsg(object: _85.EnumValueOptionsAminoMsg): _85.EnumValueOptions;
            fromProtoMsg(message: _85.EnumValueOptionsProtoMsg): _85.EnumValueOptions;
            toProto(message: _85.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _85.EnumValueOptions): _85.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _85.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.ServiceOptions;
            fromPartial(object: Partial<_85.ServiceOptions>): _85.ServiceOptions;
            fromAmino(object: _85.ServiceOptionsAmino): _85.ServiceOptions;
            toAmino(message: _85.ServiceOptions): _85.ServiceOptionsAmino;
            fromAminoMsg(object: _85.ServiceOptionsAminoMsg): _85.ServiceOptions;
            fromProtoMsg(message: _85.ServiceOptionsProtoMsg): _85.ServiceOptions;
            toProto(message: _85.ServiceOptions): Uint8Array;
            toProtoMsg(message: _85.ServiceOptions): _85.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _85.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.MethodOptions;
            fromPartial(object: Partial<_85.MethodOptions>): _85.MethodOptions;
            fromAmino(object: _85.MethodOptionsAmino): _85.MethodOptions;
            toAmino(message: _85.MethodOptions): _85.MethodOptionsAmino;
            fromAminoMsg(object: _85.MethodOptionsAminoMsg): _85.MethodOptions;
            fromProtoMsg(message: _85.MethodOptionsProtoMsg): _85.MethodOptions;
            toProto(message: _85.MethodOptions): Uint8Array;
            toProtoMsg(message: _85.MethodOptions): _85.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _85.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.UninterpretedOption;
            fromPartial(object: Partial<_85.UninterpretedOption>): _85.UninterpretedOption;
            fromAmino(object: _85.UninterpretedOptionAmino): _85.UninterpretedOption;
            toAmino(message: _85.UninterpretedOption): _85.UninterpretedOptionAmino;
            fromAminoMsg(object: _85.UninterpretedOptionAminoMsg): _85.UninterpretedOption;
            fromProtoMsg(message: _85.UninterpretedOptionProtoMsg): _85.UninterpretedOption;
            toProto(message: _85.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _85.UninterpretedOption): _85.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _85.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_85.UninterpretedOption_NamePart>): _85.UninterpretedOption_NamePart;
            fromAmino(object: _85.UninterpretedOption_NamePartAmino): _85.UninterpretedOption_NamePart;
            toAmino(message: _85.UninterpretedOption_NamePart): _85.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _85.UninterpretedOption_NamePartAminoMsg): _85.UninterpretedOption_NamePart;
            fromProtoMsg(message: _85.UninterpretedOption_NamePartProtoMsg): _85.UninterpretedOption_NamePart;
            toProto(message: _85.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _85.UninterpretedOption_NamePart): _85.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _85.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.SourceCodeInfo;
            fromPartial(object: Partial<_85.SourceCodeInfo>): _85.SourceCodeInfo;
            fromAmino(object: _85.SourceCodeInfoAmino): _85.SourceCodeInfo;
            toAmino(message: _85.SourceCodeInfo): _85.SourceCodeInfoAmino;
            fromAminoMsg(object: _85.SourceCodeInfoAminoMsg): _85.SourceCodeInfo;
            fromProtoMsg(message: _85.SourceCodeInfoProtoMsg): _85.SourceCodeInfo;
            toProto(message: _85.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _85.SourceCodeInfo): _85.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _85.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.SourceCodeInfo_Location;
            fromPartial(object: Partial<_85.SourceCodeInfo_Location>): _85.SourceCodeInfo_Location;
            fromAmino(object: _85.SourceCodeInfo_LocationAmino): _85.SourceCodeInfo_Location;
            toAmino(message: _85.SourceCodeInfo_Location): _85.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _85.SourceCodeInfo_LocationAminoMsg): _85.SourceCodeInfo_Location;
            fromProtoMsg(message: _85.SourceCodeInfo_LocationProtoMsg): _85.SourceCodeInfo_Location;
            toProto(message: _85.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _85.SourceCodeInfo_Location): _85.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _85.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.GeneratedCodeInfo;
            fromPartial(object: Partial<_85.GeneratedCodeInfo>): _85.GeneratedCodeInfo;
            fromAmino(object: _85.GeneratedCodeInfoAmino): _85.GeneratedCodeInfo;
            toAmino(message: _85.GeneratedCodeInfo): _85.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _85.GeneratedCodeInfoAminoMsg): _85.GeneratedCodeInfo;
            fromProtoMsg(message: _85.GeneratedCodeInfoProtoMsg): _85.GeneratedCodeInfo;
            toProto(message: _85.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _85.GeneratedCodeInfo): _85.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _85.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_85.GeneratedCodeInfo_Annotation>): _85.GeneratedCodeInfo_Annotation;
            fromAmino(object: _85.GeneratedCodeInfo_AnnotationAmino): _85.GeneratedCodeInfo_Annotation;
            toAmino(message: _85.GeneratedCodeInfo_Annotation): _85.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _85.GeneratedCodeInfo_AnnotationAminoMsg): _85.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _85.GeneratedCodeInfo_AnnotationProtoMsg): _85.GeneratedCodeInfo_Annotation;
            toProto(message: _85.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _85.GeneratedCodeInfo_Annotation): _85.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _84.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _84.Timestamp;
            fromPartial(object: Partial<_84.Timestamp>): _84.Timestamp;
            fromAmino(object: string): _84.Timestamp;
            toAmino(message: _84.Timestamp): string;
            fromAminoMsg(object: _84.TimestampAminoMsg): _84.Timestamp;
            fromProtoMsg(message: _84.TimestampProtoMsg): _84.Timestamp;
            toProto(message: _84.Timestamp): Uint8Array;
            toProtoMsg(message: _84.Timestamp): _84.TimestampProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _83.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _83.Any;
            fromPartial(object: Partial<_83.Any>): _83.Any;
            fromAmino(object: _83.AnyAmino): _83.Any;
            toAmino(message: _83.Any): _83.AnyAmino;
            fromAminoMsg(object: _83.AnyAminoMsg): _83.Any;
            fromProtoMsg(message: _83.AnyProtoMsg): _83.Any;
            toProto(message: _83.Any): Uint8Array;
            toProtoMsg(message: _83.Any): _83.AnyProtoMsg;
        };
    };
}
