import * as _145 from "./api/http";
import * as _146 from "./api/httpbody";
import * as _147 from "./protobuf/any";
import * as _148 from "./protobuf/duration";
import * as _149 from "./protobuf/timestamp";
import * as _150 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        HttpBody: {
            typeUrl: string;
            encode(message: _146.HttpBody, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _146.HttpBody;
            fromPartial(object: Partial<_146.HttpBody>): _146.HttpBody;
            fromAmino(object: _146.HttpBodyAmino): _146.HttpBody;
            toAmino(message: _146.HttpBody): _146.HttpBodyAmino;
            fromAminoMsg(object: _146.HttpBodyAminoMsg): _146.HttpBody;
            fromProtoMsg(message: _146.HttpBodyProtoMsg): _146.HttpBody;
            toProto(message: _146.HttpBody): Uint8Array;
            toProtoMsg(message: _146.HttpBody): _146.HttpBodyProtoMsg;
        };
        Http: {
            typeUrl: string;
            encode(message: _145.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.Http;
            fromPartial(object: Partial<_145.Http>): _145.Http;
            fromAmino(object: _145.HttpAmino): _145.Http;
            toAmino(message: _145.Http): _145.HttpAmino;
            fromAminoMsg(object: _145.HttpAminoMsg): _145.Http;
            fromProtoMsg(message: _145.HttpProtoMsg): _145.Http;
            toProto(message: _145.Http): Uint8Array;
            toProtoMsg(message: _145.Http): _145.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _145.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.HttpRule;
            fromPartial(object: Partial<_145.HttpRule>): _145.HttpRule;
            fromAmino(object: _145.HttpRuleAmino): _145.HttpRule;
            toAmino(message: _145.HttpRule): _145.HttpRuleAmino;
            fromAminoMsg(object: _145.HttpRuleAminoMsg): _145.HttpRule;
            fromProtoMsg(message: _145.HttpRuleProtoMsg): _145.HttpRule;
            toProto(message: _145.HttpRule): Uint8Array;
            toProtoMsg(message: _145.HttpRule): _145.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _145.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.CustomHttpPattern;
            fromPartial(object: Partial<_145.CustomHttpPattern>): _145.CustomHttpPattern;
            fromAmino(object: _145.CustomHttpPatternAmino): _145.CustomHttpPattern;
            toAmino(message: _145.CustomHttpPattern): _145.CustomHttpPatternAmino;
            fromAminoMsg(object: _145.CustomHttpPatternAminoMsg): _145.CustomHttpPattern;
            fromProtoMsg(message: _145.CustomHttpPatternProtoMsg): _145.CustomHttpPattern;
            toProto(message: _145.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _145.CustomHttpPattern): _145.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _150.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _150.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _150.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _150.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _150.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _150.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _150.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _150.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _150.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _150.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _150.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _150.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _150.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _150.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _150.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _150.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _150.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _150.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _150.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _150.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _150.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _150.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _150.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _150.FieldOptions_CType;
        FieldOptions_JSType: typeof _150.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _150.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _150.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _150.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _150.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _150.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _150.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.FileDescriptorSet;
            fromPartial(object: Partial<_150.FileDescriptorSet>): _150.FileDescriptorSet;
            fromAmino(object: _150.FileDescriptorSetAmino): _150.FileDescriptorSet;
            toAmino(message: _150.FileDescriptorSet): _150.FileDescriptorSetAmino;
            fromAminoMsg(object: _150.FileDescriptorSetAminoMsg): _150.FileDescriptorSet;
            fromProtoMsg(message: _150.FileDescriptorSetProtoMsg): _150.FileDescriptorSet;
            toProto(message: _150.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _150.FileDescriptorSet): _150.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _150.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.FileDescriptorProto;
            fromPartial(object: Partial<_150.FileDescriptorProto>): _150.FileDescriptorProto;
            fromAmino(object: _150.FileDescriptorProtoAmino): _150.FileDescriptorProto;
            toAmino(message: _150.FileDescriptorProto): _150.FileDescriptorProtoAmino;
            fromAminoMsg(object: _150.FileDescriptorProtoAminoMsg): _150.FileDescriptorProto;
            fromProtoMsg(message: _150.FileDescriptorProtoProtoMsg): _150.FileDescriptorProto;
            toProto(message: _150.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _150.FileDescriptorProto): _150.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _150.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.DescriptorProto;
            fromPartial(object: Partial<_150.DescriptorProto>): _150.DescriptorProto;
            fromAmino(object: _150.DescriptorProtoAmino): _150.DescriptorProto;
            toAmino(message: _150.DescriptorProto): _150.DescriptorProtoAmino;
            fromAminoMsg(object: _150.DescriptorProtoAminoMsg): _150.DescriptorProto;
            fromProtoMsg(message: _150.DescriptorProtoProtoMsg): _150.DescriptorProto;
            toProto(message: _150.DescriptorProto): Uint8Array;
            toProtoMsg(message: _150.DescriptorProto): _150.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _150.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_150.DescriptorProto_ExtensionRange>): _150.DescriptorProto_ExtensionRange;
            fromAmino(object: _150.DescriptorProto_ExtensionRangeAmino): _150.DescriptorProto_ExtensionRange;
            toAmino(message: _150.DescriptorProto_ExtensionRange): _150.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _150.DescriptorProto_ExtensionRangeAminoMsg): _150.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _150.DescriptorProto_ExtensionRangeProtoMsg): _150.DescriptorProto_ExtensionRange;
            toProto(message: _150.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _150.DescriptorProto_ExtensionRange): _150.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _150.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_150.DescriptorProto_ReservedRange>): _150.DescriptorProto_ReservedRange;
            fromAmino(object: _150.DescriptorProto_ReservedRangeAmino): _150.DescriptorProto_ReservedRange;
            toAmino(message: _150.DescriptorProto_ReservedRange): _150.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _150.DescriptorProto_ReservedRangeAminoMsg): _150.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _150.DescriptorProto_ReservedRangeProtoMsg): _150.DescriptorProto_ReservedRange;
            toProto(message: _150.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _150.DescriptorProto_ReservedRange): _150.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _150.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.ExtensionRangeOptions;
            fromPartial(object: Partial<_150.ExtensionRangeOptions>): _150.ExtensionRangeOptions;
            fromAmino(object: _150.ExtensionRangeOptionsAmino): _150.ExtensionRangeOptions;
            toAmino(message: _150.ExtensionRangeOptions): _150.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _150.ExtensionRangeOptionsAminoMsg): _150.ExtensionRangeOptions;
            fromProtoMsg(message: _150.ExtensionRangeOptionsProtoMsg): _150.ExtensionRangeOptions;
            toProto(message: _150.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _150.ExtensionRangeOptions): _150.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _150.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.FieldDescriptorProto;
            fromPartial(object: Partial<_150.FieldDescriptorProto>): _150.FieldDescriptorProto;
            fromAmino(object: _150.FieldDescriptorProtoAmino): _150.FieldDescriptorProto;
            toAmino(message: _150.FieldDescriptorProto): _150.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _150.FieldDescriptorProtoAminoMsg): _150.FieldDescriptorProto;
            fromProtoMsg(message: _150.FieldDescriptorProtoProtoMsg): _150.FieldDescriptorProto;
            toProto(message: _150.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _150.FieldDescriptorProto): _150.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _150.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.OneofDescriptorProto;
            fromPartial(object: Partial<_150.OneofDescriptorProto>): _150.OneofDescriptorProto;
            fromAmino(object: _150.OneofDescriptorProtoAmino): _150.OneofDescriptorProto;
            toAmino(message: _150.OneofDescriptorProto): _150.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _150.OneofDescriptorProtoAminoMsg): _150.OneofDescriptorProto;
            fromProtoMsg(message: _150.OneofDescriptorProtoProtoMsg): _150.OneofDescriptorProto;
            toProto(message: _150.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _150.OneofDescriptorProto): _150.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _150.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.EnumDescriptorProto;
            fromPartial(object: Partial<_150.EnumDescriptorProto>): _150.EnumDescriptorProto;
            fromAmino(object: _150.EnumDescriptorProtoAmino): _150.EnumDescriptorProto;
            toAmino(message: _150.EnumDescriptorProto): _150.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _150.EnumDescriptorProtoAminoMsg): _150.EnumDescriptorProto;
            fromProtoMsg(message: _150.EnumDescriptorProtoProtoMsg): _150.EnumDescriptorProto;
            toProto(message: _150.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _150.EnumDescriptorProto): _150.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _150.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_150.EnumDescriptorProto_EnumReservedRange>): _150.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _150.EnumDescriptorProto_EnumReservedRangeAmino): _150.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _150.EnumDescriptorProto_EnumReservedRange): _150.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _150.EnumDescriptorProto_EnumReservedRangeAminoMsg): _150.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _150.EnumDescriptorProto_EnumReservedRangeProtoMsg): _150.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _150.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _150.EnumDescriptorProto_EnumReservedRange): _150.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _150.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.EnumValueDescriptorProto;
            fromPartial(object: Partial<_150.EnumValueDescriptorProto>): _150.EnumValueDescriptorProto;
            fromAmino(object: _150.EnumValueDescriptorProtoAmino): _150.EnumValueDescriptorProto;
            toAmino(message: _150.EnumValueDescriptorProto): _150.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _150.EnumValueDescriptorProtoAminoMsg): _150.EnumValueDescriptorProto;
            fromProtoMsg(message: _150.EnumValueDescriptorProtoProtoMsg): _150.EnumValueDescriptorProto;
            toProto(message: _150.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _150.EnumValueDescriptorProto): _150.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _150.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.ServiceDescriptorProto;
            fromPartial(object: Partial<_150.ServiceDescriptorProto>): _150.ServiceDescriptorProto;
            fromAmino(object: _150.ServiceDescriptorProtoAmino): _150.ServiceDescriptorProto;
            toAmino(message: _150.ServiceDescriptorProto): _150.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _150.ServiceDescriptorProtoAminoMsg): _150.ServiceDescriptorProto;
            fromProtoMsg(message: _150.ServiceDescriptorProtoProtoMsg): _150.ServiceDescriptorProto;
            toProto(message: _150.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _150.ServiceDescriptorProto): _150.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _150.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.MethodDescriptorProto;
            fromPartial(object: Partial<_150.MethodDescriptorProto>): _150.MethodDescriptorProto;
            fromAmino(object: _150.MethodDescriptorProtoAmino): _150.MethodDescriptorProto;
            toAmino(message: _150.MethodDescriptorProto): _150.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _150.MethodDescriptorProtoAminoMsg): _150.MethodDescriptorProto;
            fromProtoMsg(message: _150.MethodDescriptorProtoProtoMsg): _150.MethodDescriptorProto;
            toProto(message: _150.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _150.MethodDescriptorProto): _150.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _150.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.FileOptions;
            fromPartial(object: Partial<_150.FileOptions>): _150.FileOptions;
            fromAmino(object: _150.FileOptionsAmino): _150.FileOptions;
            toAmino(message: _150.FileOptions): _150.FileOptionsAmino;
            fromAminoMsg(object: _150.FileOptionsAminoMsg): _150.FileOptions;
            fromProtoMsg(message: _150.FileOptionsProtoMsg): _150.FileOptions;
            toProto(message: _150.FileOptions): Uint8Array;
            toProtoMsg(message: _150.FileOptions): _150.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _150.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.MessageOptions;
            fromPartial(object: Partial<_150.MessageOptions>): _150.MessageOptions;
            fromAmino(object: _150.MessageOptionsAmino): _150.MessageOptions;
            toAmino(message: _150.MessageOptions): _150.MessageOptionsAmino;
            fromAminoMsg(object: _150.MessageOptionsAminoMsg): _150.MessageOptions;
            fromProtoMsg(message: _150.MessageOptionsProtoMsg): _150.MessageOptions;
            toProto(message: _150.MessageOptions): Uint8Array;
            toProtoMsg(message: _150.MessageOptions): _150.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _150.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.FieldOptions;
            fromPartial(object: Partial<_150.FieldOptions>): _150.FieldOptions;
            fromAmino(object: _150.FieldOptionsAmino): _150.FieldOptions;
            toAmino(message: _150.FieldOptions): _150.FieldOptionsAmino;
            fromAminoMsg(object: _150.FieldOptionsAminoMsg): _150.FieldOptions;
            fromProtoMsg(message: _150.FieldOptionsProtoMsg): _150.FieldOptions;
            toProto(message: _150.FieldOptions): Uint8Array;
            toProtoMsg(message: _150.FieldOptions): _150.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _150.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.OneofOptions;
            fromPartial(object: Partial<_150.OneofOptions>): _150.OneofOptions;
            fromAmino(object: _150.OneofOptionsAmino): _150.OneofOptions;
            toAmino(message: _150.OneofOptions): _150.OneofOptionsAmino;
            fromAminoMsg(object: _150.OneofOptionsAminoMsg): _150.OneofOptions;
            fromProtoMsg(message: _150.OneofOptionsProtoMsg): _150.OneofOptions;
            toProto(message: _150.OneofOptions): Uint8Array;
            toProtoMsg(message: _150.OneofOptions): _150.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _150.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.EnumOptions;
            fromPartial(object: Partial<_150.EnumOptions>): _150.EnumOptions;
            fromAmino(object: _150.EnumOptionsAmino): _150.EnumOptions;
            toAmino(message: _150.EnumOptions): _150.EnumOptionsAmino;
            fromAminoMsg(object: _150.EnumOptionsAminoMsg): _150.EnumOptions;
            fromProtoMsg(message: _150.EnumOptionsProtoMsg): _150.EnumOptions;
            toProto(message: _150.EnumOptions): Uint8Array;
            toProtoMsg(message: _150.EnumOptions): _150.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _150.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.EnumValueOptions;
            fromPartial(object: Partial<_150.EnumValueOptions>): _150.EnumValueOptions;
            fromAmino(object: _150.EnumValueOptionsAmino): _150.EnumValueOptions;
            toAmino(message: _150.EnumValueOptions): _150.EnumValueOptionsAmino;
            fromAminoMsg(object: _150.EnumValueOptionsAminoMsg): _150.EnumValueOptions;
            fromProtoMsg(message: _150.EnumValueOptionsProtoMsg): _150.EnumValueOptions;
            toProto(message: _150.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _150.EnumValueOptions): _150.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _150.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.ServiceOptions;
            fromPartial(object: Partial<_150.ServiceOptions>): _150.ServiceOptions;
            fromAmino(object: _150.ServiceOptionsAmino): _150.ServiceOptions;
            toAmino(message: _150.ServiceOptions): _150.ServiceOptionsAmino;
            fromAminoMsg(object: _150.ServiceOptionsAminoMsg): _150.ServiceOptions;
            fromProtoMsg(message: _150.ServiceOptionsProtoMsg): _150.ServiceOptions;
            toProto(message: _150.ServiceOptions): Uint8Array;
            toProtoMsg(message: _150.ServiceOptions): _150.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _150.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.MethodOptions;
            fromPartial(object: Partial<_150.MethodOptions>): _150.MethodOptions;
            fromAmino(object: _150.MethodOptionsAmino): _150.MethodOptions;
            toAmino(message: _150.MethodOptions): _150.MethodOptionsAmino;
            fromAminoMsg(object: _150.MethodOptionsAminoMsg): _150.MethodOptions;
            fromProtoMsg(message: _150.MethodOptionsProtoMsg): _150.MethodOptions;
            toProto(message: _150.MethodOptions): Uint8Array;
            toProtoMsg(message: _150.MethodOptions): _150.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _150.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.UninterpretedOption;
            fromPartial(object: Partial<_150.UninterpretedOption>): _150.UninterpretedOption;
            fromAmino(object: _150.UninterpretedOptionAmino): _150.UninterpretedOption;
            toAmino(message: _150.UninterpretedOption): _150.UninterpretedOptionAmino;
            fromAminoMsg(object: _150.UninterpretedOptionAminoMsg): _150.UninterpretedOption;
            fromProtoMsg(message: _150.UninterpretedOptionProtoMsg): _150.UninterpretedOption;
            toProto(message: _150.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _150.UninterpretedOption): _150.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _150.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_150.UninterpretedOption_NamePart>): _150.UninterpretedOption_NamePart;
            fromAmino(object: _150.UninterpretedOption_NamePartAmino): _150.UninterpretedOption_NamePart;
            toAmino(message: _150.UninterpretedOption_NamePart): _150.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _150.UninterpretedOption_NamePartAminoMsg): _150.UninterpretedOption_NamePart;
            fromProtoMsg(message: _150.UninterpretedOption_NamePartProtoMsg): _150.UninterpretedOption_NamePart;
            toProto(message: _150.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _150.UninterpretedOption_NamePart): _150.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _150.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.SourceCodeInfo;
            fromPartial(object: Partial<_150.SourceCodeInfo>): _150.SourceCodeInfo;
            fromAmino(object: _150.SourceCodeInfoAmino): _150.SourceCodeInfo;
            toAmino(message: _150.SourceCodeInfo): _150.SourceCodeInfoAmino;
            fromAminoMsg(object: _150.SourceCodeInfoAminoMsg): _150.SourceCodeInfo;
            fromProtoMsg(message: _150.SourceCodeInfoProtoMsg): _150.SourceCodeInfo;
            toProto(message: _150.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _150.SourceCodeInfo): _150.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _150.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.SourceCodeInfo_Location;
            fromPartial(object: Partial<_150.SourceCodeInfo_Location>): _150.SourceCodeInfo_Location;
            fromAmino(object: _150.SourceCodeInfo_LocationAmino): _150.SourceCodeInfo_Location;
            toAmino(message: _150.SourceCodeInfo_Location): _150.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _150.SourceCodeInfo_LocationAminoMsg): _150.SourceCodeInfo_Location;
            fromProtoMsg(message: _150.SourceCodeInfo_LocationProtoMsg): _150.SourceCodeInfo_Location;
            toProto(message: _150.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _150.SourceCodeInfo_Location): _150.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _150.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.GeneratedCodeInfo;
            fromPartial(object: Partial<_150.GeneratedCodeInfo>): _150.GeneratedCodeInfo;
            fromAmino(object: _150.GeneratedCodeInfoAmino): _150.GeneratedCodeInfo;
            toAmino(message: _150.GeneratedCodeInfo): _150.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _150.GeneratedCodeInfoAminoMsg): _150.GeneratedCodeInfo;
            fromProtoMsg(message: _150.GeneratedCodeInfoProtoMsg): _150.GeneratedCodeInfo;
            toProto(message: _150.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _150.GeneratedCodeInfo): _150.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _150.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _150.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_150.GeneratedCodeInfo_Annotation>): _150.GeneratedCodeInfo_Annotation;
            fromAmino(object: _150.GeneratedCodeInfo_AnnotationAmino): _150.GeneratedCodeInfo_Annotation;
            toAmino(message: _150.GeneratedCodeInfo_Annotation): _150.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _150.GeneratedCodeInfo_AnnotationAminoMsg): _150.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _150.GeneratedCodeInfo_AnnotationProtoMsg): _150.GeneratedCodeInfo_Annotation;
            toProto(message: _150.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _150.GeneratedCodeInfo_Annotation): _150.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _149.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _149.Timestamp;
            fromPartial(object: Partial<_149.Timestamp>): _149.Timestamp;
            fromAmino(object: string): _149.Timestamp;
            toAmino(message: _149.Timestamp): string;
            fromAminoMsg(object: _149.TimestampAminoMsg): _149.Timestamp;
            fromProtoMsg(message: _149.TimestampProtoMsg): _149.Timestamp;
            toProto(message: _149.Timestamp): Uint8Array;
            toProtoMsg(message: _149.Timestamp): _149.TimestampProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _148.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _148.Duration;
            fromPartial(object: Partial<_148.Duration>): _148.Duration;
            fromAmino(object: string): _148.Duration;
            toAmino(message: _148.Duration): string;
            fromAminoMsg(object: _148.DurationAminoMsg): _148.Duration;
            fromProtoMsg(message: _148.DurationProtoMsg): _148.Duration;
            toProto(message: _148.Duration): Uint8Array;
            toProtoMsg(message: _148.Duration): _148.DurationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _147.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _147.Any;
            fromPartial(object: Partial<_147.Any>): _147.Any;
            fromAmino(object: _147.AnyAmino): _147.Any;
            toAmino(message: _147.Any): _147.AnyAmino;
            fromAminoMsg(object: _147.AnyAminoMsg): _147.Any;
            fromProtoMsg(message: _147.AnyProtoMsg): _147.Any;
            toProto(message: _147.Any): Uint8Array;
            toProtoMsg(message: _147.Any): _147.AnyProtoMsg;
        };
    };
}
