import * as _85 from "./api/http";
import * as _86 from "./protobuf/timestamp";
import * as _87 from "./protobuf/duration";
import * as _88 from "./protobuf/any";
import * as _89 from "./protobuf/descriptor";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _85.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.Http;
            fromPartial(object: Partial<_85.Http>): _85.Http;
            fromAmino(object: _85.HttpAmino): _85.Http;
            toAmino(message: _85.Http): _85.HttpAmino;
            fromAminoMsg(object: _85.HttpAminoMsg): _85.Http;
            fromProtoMsg(message: _85.HttpProtoMsg): _85.Http;
            toProto(message: _85.Http): Uint8Array;
            toProtoMsg(message: _85.Http): _85.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _85.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.HttpRule;
            fromPartial(object: Partial<_85.HttpRule>): _85.HttpRule;
            fromAmino(object: _85.HttpRuleAmino): _85.HttpRule;
            toAmino(message: _85.HttpRule): _85.HttpRuleAmino;
            fromAminoMsg(object: _85.HttpRuleAminoMsg): _85.HttpRule;
            fromProtoMsg(message: _85.HttpRuleProtoMsg): _85.HttpRule;
            toProto(message: _85.HttpRule): Uint8Array;
            toProtoMsg(message: _85.HttpRule): _85.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _85.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _85.CustomHttpPattern;
            fromPartial(object: Partial<_85.CustomHttpPattern>): _85.CustomHttpPattern;
            fromAmino(object: _85.CustomHttpPatternAmino): _85.CustomHttpPattern;
            toAmino(message: _85.CustomHttpPattern): _85.CustomHttpPatternAmino;
            fromAminoMsg(object: _85.CustomHttpPatternAminoMsg): _85.CustomHttpPattern;
            fromProtoMsg(message: _85.CustomHttpPatternProtoMsg): _85.CustomHttpPattern;
            toProto(message: _85.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _85.CustomHttpPattern): _85.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        fieldDescriptorProto_TypeFromJSON(object: any): _89.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _89.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _89.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _89.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _89.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _89.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _89.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _89.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _89.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _89.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _89.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _89.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _89.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _89.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _89.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _89.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _89.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _89.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _89.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _89.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _89.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _89.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _89.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _89.FieldOptions_CType;
        FieldOptions_JSType: typeof _89.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _89.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _89.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _89.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _89.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _89.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _89.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.FileDescriptorSet;
            fromPartial(object: Partial<_89.FileDescriptorSet>): _89.FileDescriptorSet;
            fromAmino(object: _89.FileDescriptorSetAmino): _89.FileDescriptorSet;
            toAmino(message: _89.FileDescriptorSet): _89.FileDescriptorSetAmino;
            fromAminoMsg(object: _89.FileDescriptorSetAminoMsg): _89.FileDescriptorSet;
            fromProtoMsg(message: _89.FileDescriptorSetProtoMsg): _89.FileDescriptorSet;
            toProto(message: _89.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _89.FileDescriptorSet): _89.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _89.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.FileDescriptorProto;
            fromPartial(object: Partial<_89.FileDescriptorProto>): _89.FileDescriptorProto;
            fromAmino(object: _89.FileDescriptorProtoAmino): _89.FileDescriptorProto;
            toAmino(message: _89.FileDescriptorProto): _89.FileDescriptorProtoAmino;
            fromAminoMsg(object: _89.FileDescriptorProtoAminoMsg): _89.FileDescriptorProto;
            fromProtoMsg(message: _89.FileDescriptorProtoProtoMsg): _89.FileDescriptorProto;
            toProto(message: _89.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _89.FileDescriptorProto): _89.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _89.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.DescriptorProto;
            fromPartial(object: Partial<_89.DescriptorProto>): _89.DescriptorProto;
            fromAmino(object: _89.DescriptorProtoAmino): _89.DescriptorProto;
            toAmino(message: _89.DescriptorProto): _89.DescriptorProtoAmino;
            fromAminoMsg(object: _89.DescriptorProtoAminoMsg): _89.DescriptorProto;
            fromProtoMsg(message: _89.DescriptorProtoProtoMsg): _89.DescriptorProto;
            toProto(message: _89.DescriptorProto): Uint8Array;
            toProtoMsg(message: _89.DescriptorProto): _89.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _89.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_89.DescriptorProto_ExtensionRange>): _89.DescriptorProto_ExtensionRange;
            fromAmino(object: _89.DescriptorProto_ExtensionRangeAmino): _89.DescriptorProto_ExtensionRange;
            toAmino(message: _89.DescriptorProto_ExtensionRange): _89.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _89.DescriptorProto_ExtensionRangeAminoMsg): _89.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _89.DescriptorProto_ExtensionRangeProtoMsg): _89.DescriptorProto_ExtensionRange;
            toProto(message: _89.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _89.DescriptorProto_ExtensionRange): _89.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _89.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_89.DescriptorProto_ReservedRange>): _89.DescriptorProto_ReservedRange;
            fromAmino(object: _89.DescriptorProto_ReservedRangeAmino): _89.DescriptorProto_ReservedRange;
            toAmino(message: _89.DescriptorProto_ReservedRange): _89.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _89.DescriptorProto_ReservedRangeAminoMsg): _89.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _89.DescriptorProto_ReservedRangeProtoMsg): _89.DescriptorProto_ReservedRange;
            toProto(message: _89.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _89.DescriptorProto_ReservedRange): _89.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _89.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.ExtensionRangeOptions;
            fromPartial(object: Partial<_89.ExtensionRangeOptions>): _89.ExtensionRangeOptions;
            fromAmino(object: _89.ExtensionRangeOptionsAmino): _89.ExtensionRangeOptions;
            toAmino(message: _89.ExtensionRangeOptions): _89.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _89.ExtensionRangeOptionsAminoMsg): _89.ExtensionRangeOptions;
            fromProtoMsg(message: _89.ExtensionRangeOptionsProtoMsg): _89.ExtensionRangeOptions;
            toProto(message: _89.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _89.ExtensionRangeOptions): _89.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _89.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.FieldDescriptorProto;
            fromPartial(object: Partial<_89.FieldDescriptorProto>): _89.FieldDescriptorProto;
            fromAmino(object: _89.FieldDescriptorProtoAmino): _89.FieldDescriptorProto;
            toAmino(message: _89.FieldDescriptorProto): _89.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _89.FieldDescriptorProtoAminoMsg): _89.FieldDescriptorProto;
            fromProtoMsg(message: _89.FieldDescriptorProtoProtoMsg): _89.FieldDescriptorProto;
            toProto(message: _89.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _89.FieldDescriptorProto): _89.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _89.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.OneofDescriptorProto;
            fromPartial(object: Partial<_89.OneofDescriptorProto>): _89.OneofDescriptorProto;
            fromAmino(object: _89.OneofDescriptorProtoAmino): _89.OneofDescriptorProto;
            toAmino(message: _89.OneofDescriptorProto): _89.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _89.OneofDescriptorProtoAminoMsg): _89.OneofDescriptorProto;
            fromProtoMsg(message: _89.OneofDescriptorProtoProtoMsg): _89.OneofDescriptorProto;
            toProto(message: _89.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _89.OneofDescriptorProto): _89.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _89.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.EnumDescriptorProto;
            fromPartial(object: Partial<_89.EnumDescriptorProto>): _89.EnumDescriptorProto;
            fromAmino(object: _89.EnumDescriptorProtoAmino): _89.EnumDescriptorProto;
            toAmino(message: _89.EnumDescriptorProto): _89.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _89.EnumDescriptorProtoAminoMsg): _89.EnumDescriptorProto;
            fromProtoMsg(message: _89.EnumDescriptorProtoProtoMsg): _89.EnumDescriptorProto;
            toProto(message: _89.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _89.EnumDescriptorProto): _89.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _89.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_89.EnumDescriptorProto_EnumReservedRange>): _89.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _89.EnumDescriptorProto_EnumReservedRangeAmino): _89.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _89.EnumDescriptorProto_EnumReservedRange): _89.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _89.EnumDescriptorProto_EnumReservedRangeAminoMsg): _89.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _89.EnumDescriptorProto_EnumReservedRangeProtoMsg): _89.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _89.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _89.EnumDescriptorProto_EnumReservedRange): _89.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _89.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.EnumValueDescriptorProto;
            fromPartial(object: Partial<_89.EnumValueDescriptorProto>): _89.EnumValueDescriptorProto;
            fromAmino(object: _89.EnumValueDescriptorProtoAmino): _89.EnumValueDescriptorProto;
            toAmino(message: _89.EnumValueDescriptorProto): _89.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _89.EnumValueDescriptorProtoAminoMsg): _89.EnumValueDescriptorProto;
            fromProtoMsg(message: _89.EnumValueDescriptorProtoProtoMsg): _89.EnumValueDescriptorProto;
            toProto(message: _89.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _89.EnumValueDescriptorProto): _89.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _89.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.ServiceDescriptorProto;
            fromPartial(object: Partial<_89.ServiceDescriptorProto>): _89.ServiceDescriptorProto;
            fromAmino(object: _89.ServiceDescriptorProtoAmino): _89.ServiceDescriptorProto;
            toAmino(message: _89.ServiceDescriptorProto): _89.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _89.ServiceDescriptorProtoAminoMsg): _89.ServiceDescriptorProto;
            fromProtoMsg(message: _89.ServiceDescriptorProtoProtoMsg): _89.ServiceDescriptorProto;
            toProto(message: _89.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _89.ServiceDescriptorProto): _89.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _89.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.MethodDescriptorProto;
            fromPartial(object: Partial<_89.MethodDescriptorProto>): _89.MethodDescriptorProto;
            fromAmino(object: _89.MethodDescriptorProtoAmino): _89.MethodDescriptorProto;
            toAmino(message: _89.MethodDescriptorProto): _89.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _89.MethodDescriptorProtoAminoMsg): _89.MethodDescriptorProto;
            fromProtoMsg(message: _89.MethodDescriptorProtoProtoMsg): _89.MethodDescriptorProto;
            toProto(message: _89.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _89.MethodDescriptorProto): _89.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _89.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.FileOptions;
            fromPartial(object: Partial<_89.FileOptions>): _89.FileOptions;
            fromAmino(object: _89.FileOptionsAmino): _89.FileOptions;
            toAmino(message: _89.FileOptions): _89.FileOptionsAmino;
            fromAminoMsg(object: _89.FileOptionsAminoMsg): _89.FileOptions;
            fromProtoMsg(message: _89.FileOptionsProtoMsg): _89.FileOptions;
            toProto(message: _89.FileOptions): Uint8Array;
            toProtoMsg(message: _89.FileOptions): _89.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _89.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.MessageOptions;
            fromPartial(object: Partial<_89.MessageOptions>): _89.MessageOptions;
            fromAmino(object: _89.MessageOptionsAmino): _89.MessageOptions;
            toAmino(message: _89.MessageOptions): _89.MessageOptionsAmino;
            fromAminoMsg(object: _89.MessageOptionsAminoMsg): _89.MessageOptions;
            fromProtoMsg(message: _89.MessageOptionsProtoMsg): _89.MessageOptions;
            toProto(message: _89.MessageOptions): Uint8Array;
            toProtoMsg(message: _89.MessageOptions): _89.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _89.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.FieldOptions;
            fromPartial(object: Partial<_89.FieldOptions>): _89.FieldOptions;
            fromAmino(object: _89.FieldOptionsAmino): _89.FieldOptions;
            toAmino(message: _89.FieldOptions): _89.FieldOptionsAmino;
            fromAminoMsg(object: _89.FieldOptionsAminoMsg): _89.FieldOptions;
            fromProtoMsg(message: _89.FieldOptionsProtoMsg): _89.FieldOptions;
            toProto(message: _89.FieldOptions): Uint8Array;
            toProtoMsg(message: _89.FieldOptions): _89.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _89.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.OneofOptions;
            fromPartial(object: Partial<_89.OneofOptions>): _89.OneofOptions;
            fromAmino(object: _89.OneofOptionsAmino): _89.OneofOptions;
            toAmino(message: _89.OneofOptions): _89.OneofOptionsAmino;
            fromAminoMsg(object: _89.OneofOptionsAminoMsg): _89.OneofOptions;
            fromProtoMsg(message: _89.OneofOptionsProtoMsg): _89.OneofOptions;
            toProto(message: _89.OneofOptions): Uint8Array;
            toProtoMsg(message: _89.OneofOptions): _89.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _89.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.EnumOptions;
            fromPartial(object: Partial<_89.EnumOptions>): _89.EnumOptions;
            fromAmino(object: _89.EnumOptionsAmino): _89.EnumOptions;
            toAmino(message: _89.EnumOptions): _89.EnumOptionsAmino;
            fromAminoMsg(object: _89.EnumOptionsAminoMsg): _89.EnumOptions;
            fromProtoMsg(message: _89.EnumOptionsProtoMsg): _89.EnumOptions;
            toProto(message: _89.EnumOptions): Uint8Array;
            toProtoMsg(message: _89.EnumOptions): _89.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _89.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.EnumValueOptions;
            fromPartial(object: Partial<_89.EnumValueOptions>): _89.EnumValueOptions;
            fromAmino(object: _89.EnumValueOptionsAmino): _89.EnumValueOptions;
            toAmino(message: _89.EnumValueOptions): _89.EnumValueOptionsAmino;
            fromAminoMsg(object: _89.EnumValueOptionsAminoMsg): _89.EnumValueOptions;
            fromProtoMsg(message: _89.EnumValueOptionsProtoMsg): _89.EnumValueOptions;
            toProto(message: _89.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _89.EnumValueOptions): _89.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _89.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.ServiceOptions;
            fromPartial(object: Partial<_89.ServiceOptions>): _89.ServiceOptions;
            fromAmino(object: _89.ServiceOptionsAmino): _89.ServiceOptions;
            toAmino(message: _89.ServiceOptions): _89.ServiceOptionsAmino;
            fromAminoMsg(object: _89.ServiceOptionsAminoMsg): _89.ServiceOptions;
            fromProtoMsg(message: _89.ServiceOptionsProtoMsg): _89.ServiceOptions;
            toProto(message: _89.ServiceOptions): Uint8Array;
            toProtoMsg(message: _89.ServiceOptions): _89.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _89.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.MethodOptions;
            fromPartial(object: Partial<_89.MethodOptions>): _89.MethodOptions;
            fromAmino(object: _89.MethodOptionsAmino): _89.MethodOptions;
            toAmino(message: _89.MethodOptions): _89.MethodOptionsAmino;
            fromAminoMsg(object: _89.MethodOptionsAminoMsg): _89.MethodOptions;
            fromProtoMsg(message: _89.MethodOptionsProtoMsg): _89.MethodOptions;
            toProto(message: _89.MethodOptions): Uint8Array;
            toProtoMsg(message: _89.MethodOptions): _89.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _89.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.UninterpretedOption;
            fromPartial(object: Partial<_89.UninterpretedOption>): _89.UninterpretedOption;
            fromAmino(object: _89.UninterpretedOptionAmino): _89.UninterpretedOption;
            toAmino(message: _89.UninterpretedOption): _89.UninterpretedOptionAmino;
            fromAminoMsg(object: _89.UninterpretedOptionAminoMsg): _89.UninterpretedOption;
            fromProtoMsg(message: _89.UninterpretedOptionProtoMsg): _89.UninterpretedOption;
            toProto(message: _89.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _89.UninterpretedOption): _89.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _89.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_89.UninterpretedOption_NamePart>): _89.UninterpretedOption_NamePart;
            fromAmino(object: _89.UninterpretedOption_NamePartAmino): _89.UninterpretedOption_NamePart;
            toAmino(message: _89.UninterpretedOption_NamePart): _89.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _89.UninterpretedOption_NamePartAminoMsg): _89.UninterpretedOption_NamePart;
            fromProtoMsg(message: _89.UninterpretedOption_NamePartProtoMsg): _89.UninterpretedOption_NamePart;
            toProto(message: _89.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _89.UninterpretedOption_NamePart): _89.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _89.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.SourceCodeInfo;
            fromPartial(object: Partial<_89.SourceCodeInfo>): _89.SourceCodeInfo;
            fromAmino(object: _89.SourceCodeInfoAmino): _89.SourceCodeInfo;
            toAmino(message: _89.SourceCodeInfo): _89.SourceCodeInfoAmino;
            fromAminoMsg(object: _89.SourceCodeInfoAminoMsg): _89.SourceCodeInfo;
            fromProtoMsg(message: _89.SourceCodeInfoProtoMsg): _89.SourceCodeInfo;
            toProto(message: _89.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _89.SourceCodeInfo): _89.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _89.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.SourceCodeInfo_Location;
            fromPartial(object: Partial<_89.SourceCodeInfo_Location>): _89.SourceCodeInfo_Location;
            fromAmino(object: _89.SourceCodeInfo_LocationAmino): _89.SourceCodeInfo_Location;
            toAmino(message: _89.SourceCodeInfo_Location): _89.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _89.SourceCodeInfo_LocationAminoMsg): _89.SourceCodeInfo_Location;
            fromProtoMsg(message: _89.SourceCodeInfo_LocationProtoMsg): _89.SourceCodeInfo_Location;
            toProto(message: _89.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _89.SourceCodeInfo_Location): _89.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _89.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.GeneratedCodeInfo;
            fromPartial(object: Partial<_89.GeneratedCodeInfo>): _89.GeneratedCodeInfo;
            fromAmino(object: _89.GeneratedCodeInfoAmino): _89.GeneratedCodeInfo;
            toAmino(message: _89.GeneratedCodeInfo): _89.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _89.GeneratedCodeInfoAminoMsg): _89.GeneratedCodeInfo;
            fromProtoMsg(message: _89.GeneratedCodeInfoProtoMsg): _89.GeneratedCodeInfo;
            toProto(message: _89.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _89.GeneratedCodeInfo): _89.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _89.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _89.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_89.GeneratedCodeInfo_Annotation>): _89.GeneratedCodeInfo_Annotation;
            fromAmino(object: _89.GeneratedCodeInfo_AnnotationAmino): _89.GeneratedCodeInfo_Annotation;
            toAmino(message: _89.GeneratedCodeInfo_Annotation): _89.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _89.GeneratedCodeInfo_AnnotationAminoMsg): _89.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _89.GeneratedCodeInfo_AnnotationProtoMsg): _89.GeneratedCodeInfo_Annotation;
            toProto(message: _89.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _89.GeneratedCodeInfo_Annotation): _89.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _88.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _88.Any;
            fromPartial(object: Partial<_88.Any>): _88.Any;
            fromAmino(object: _88.AnyAmino): _88.Any;
            toAmino(message: _88.Any): _88.AnyAmino;
            fromAminoMsg(object: _88.AnyAminoMsg): _88.Any;
            fromProtoMsg(message: _88.AnyProtoMsg): _88.Any;
            toProto(message: _88.Any): Uint8Array;
            toProtoMsg(message: _88.Any): _88.AnyProtoMsg;
        };
        Duration: {
            typeUrl: string;
            encode(message: _87.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _87.Duration;
            fromPartial(object: Partial<_87.Duration>): _87.Duration;
            fromAmino(object: string): _87.Duration;
            toAmino(message: _87.Duration): string;
            fromAminoMsg(object: _87.DurationAminoMsg): _87.Duration;
            fromProtoMsg(message: _87.DurationProtoMsg): _87.Duration;
            toProto(message: _87.Duration): Uint8Array;
            toProtoMsg(message: _87.Duration): _87.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _86.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _86.Timestamp;
            fromPartial(object: Partial<_86.Timestamp>): _86.Timestamp;
            fromAmino(object: string): _86.Timestamp;
            toAmino(message: _86.Timestamp): string;
            fromAminoMsg(object: _86.TimestampAminoMsg): _86.Timestamp;
            fromProtoMsg(message: _86.TimestampProtoMsg): _86.Timestamp;
            toProto(message: _86.Timestamp): Uint8Array;
            toProtoMsg(message: _86.Timestamp): _86.TimestampProtoMsg;
        };
    };
}
