import * as _137 from "./abci/types";
import * as _138 from "./crypto/keys";
import * as _139 from "./crypto/proof";
import * as _140 from "./libs/bits/types";
import * as _141 from "./p2p/types";
import * as _142 from "./types/block";
import * as _143 from "./types/evidence";
import * as _144 from "./types/params";
import * as _145 from "./types/types";
import * as _146 from "./types/validator";
import * as _147 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _137.CheckTxType;
        checkTxTypeToJSON(object: _137.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _137.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _137.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _137.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _137.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _137.EvidenceType;
        evidenceTypeToJSON(object: _137.EvidenceType): string;
        CheckTxType: typeof _137.CheckTxType;
        CheckTxTypeSDKType: typeof _137.CheckTxType;
        CheckTxTypeAmino: typeof _137.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _137.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _137.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _137.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _137.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _137.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _137.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _137.EvidenceType;
        EvidenceTypeSDKType: typeof _137.EvidenceType;
        EvidenceTypeAmino: typeof _137.EvidenceType;
        Request: {
            typeUrl: string;
            encode(message: _137.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.Request;
            fromPartial(object: Partial<_137.Request>): _137.Request;
            fromAmino(object: _137.RequestAmino): _137.Request;
            toAmino(message: _137.Request): _137.RequestAmino;
            fromAminoMsg(object: _137.RequestAminoMsg): _137.Request;
            fromProtoMsg(message: _137.RequestProtoMsg): _137.Request;
            toProto(message: _137.Request): Uint8Array;
            toProtoMsg(message: _137.Request): _137.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _137.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.RequestEcho;
            fromPartial(object: Partial<_137.RequestEcho>): _137.RequestEcho;
            fromAmino(object: _137.RequestEchoAmino): _137.RequestEcho;
            toAmino(message: _137.RequestEcho): _137.RequestEchoAmino;
            fromAminoMsg(object: _137.RequestEchoAminoMsg): _137.RequestEcho;
            fromProtoMsg(message: _137.RequestEchoProtoMsg): _137.RequestEcho;
            toProto(message: _137.RequestEcho): Uint8Array;
            toProtoMsg(message: _137.RequestEcho): _137.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _137.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _137.RequestFlush;
            fromPartial(_: Partial<_137.RequestFlush>): _137.RequestFlush;
            fromAmino(_: _137.RequestFlushAmino): _137.RequestFlush;
            toAmino(_: _137.RequestFlush): _137.RequestFlushAmino;
            fromAminoMsg(object: _137.RequestFlushAminoMsg): _137.RequestFlush;
            fromProtoMsg(message: _137.RequestFlushProtoMsg): _137.RequestFlush;
            toProto(message: _137.RequestFlush): Uint8Array;
            toProtoMsg(message: _137.RequestFlush): _137.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _137.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.RequestInfo;
            fromPartial(object: Partial<_137.RequestInfo>): _137.RequestInfo;
            fromAmino(object: _137.RequestInfoAmino): _137.RequestInfo;
            toAmino(message: _137.RequestInfo): _137.RequestInfoAmino;
            fromAminoMsg(object: _137.RequestInfoAminoMsg): _137.RequestInfo;
            fromProtoMsg(message: _137.RequestInfoProtoMsg): _137.RequestInfo;
            toProto(message: _137.RequestInfo): Uint8Array;
            toProtoMsg(message: _137.RequestInfo): _137.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            typeUrl: string;
            encode(message: _137.RequestSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.RequestSetOption;
            fromPartial(object: Partial<_137.RequestSetOption>): _137.RequestSetOption;
            fromAmino(object: _137.RequestSetOptionAmino): _137.RequestSetOption;
            toAmino(message: _137.RequestSetOption): _137.RequestSetOptionAmino;
            fromAminoMsg(object: _137.RequestSetOptionAminoMsg): _137.RequestSetOption;
            fromProtoMsg(message: _137.RequestSetOptionProtoMsg): _137.RequestSetOption;
            toProto(message: _137.RequestSetOption): Uint8Array;
            toProtoMsg(message: _137.RequestSetOption): _137.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _137.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.RequestInitChain;
            fromPartial(object: Partial<_137.RequestInitChain>): _137.RequestInitChain;
            fromAmino(object: _137.RequestInitChainAmino): _137.RequestInitChain;
            toAmino(message: _137.RequestInitChain): _137.RequestInitChainAmino;
            fromAminoMsg(object: _137.RequestInitChainAminoMsg): _137.RequestInitChain;
            fromProtoMsg(message: _137.RequestInitChainProtoMsg): _137.RequestInitChain;
            toProto(message: _137.RequestInitChain): Uint8Array;
            toProtoMsg(message: _137.RequestInitChain): _137.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _137.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.RequestQuery;
            fromPartial(object: Partial<_137.RequestQuery>): _137.RequestQuery;
            fromAmino(object: _137.RequestQueryAmino): _137.RequestQuery;
            toAmino(message: _137.RequestQuery): _137.RequestQueryAmino;
            fromAminoMsg(object: _137.RequestQueryAminoMsg): _137.RequestQuery;
            fromProtoMsg(message: _137.RequestQueryProtoMsg): _137.RequestQuery;
            toProto(message: _137.RequestQuery): Uint8Array;
            toProtoMsg(message: _137.RequestQuery): _137.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _137.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.RequestBeginBlock;
            fromPartial(object: Partial<_137.RequestBeginBlock>): _137.RequestBeginBlock;
            fromAmino(object: _137.RequestBeginBlockAmino): _137.RequestBeginBlock;
            toAmino(message: _137.RequestBeginBlock): _137.RequestBeginBlockAmino;
            fromAminoMsg(object: _137.RequestBeginBlockAminoMsg): _137.RequestBeginBlock;
            fromProtoMsg(message: _137.RequestBeginBlockProtoMsg): _137.RequestBeginBlock;
            toProto(message: _137.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _137.RequestBeginBlock): _137.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _137.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.RequestCheckTx;
            fromPartial(object: Partial<_137.RequestCheckTx>): _137.RequestCheckTx;
            fromAmino(object: _137.RequestCheckTxAmino): _137.RequestCheckTx;
            toAmino(message: _137.RequestCheckTx): _137.RequestCheckTxAmino;
            fromAminoMsg(object: _137.RequestCheckTxAminoMsg): _137.RequestCheckTx;
            fromProtoMsg(message: _137.RequestCheckTxProtoMsg): _137.RequestCheckTx;
            toProto(message: _137.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _137.RequestCheckTx): _137.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _137.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.RequestDeliverTx;
            fromPartial(object: Partial<_137.RequestDeliverTx>): _137.RequestDeliverTx;
            fromAmino(object: _137.RequestDeliverTxAmino): _137.RequestDeliverTx;
            toAmino(message: _137.RequestDeliverTx): _137.RequestDeliverTxAmino;
            fromAminoMsg(object: _137.RequestDeliverTxAminoMsg): _137.RequestDeliverTx;
            fromProtoMsg(message: _137.RequestDeliverTxProtoMsg): _137.RequestDeliverTx;
            toProto(message: _137.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _137.RequestDeliverTx): _137.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _137.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.RequestEndBlock;
            fromPartial(object: Partial<_137.RequestEndBlock>): _137.RequestEndBlock;
            fromAmino(object: _137.RequestEndBlockAmino): _137.RequestEndBlock;
            toAmino(message: _137.RequestEndBlock): _137.RequestEndBlockAmino;
            fromAminoMsg(object: _137.RequestEndBlockAminoMsg): _137.RequestEndBlock;
            fromProtoMsg(message: _137.RequestEndBlockProtoMsg): _137.RequestEndBlock;
            toProto(message: _137.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _137.RequestEndBlock): _137.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _137.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _137.RequestCommit;
            fromPartial(_: Partial<_137.RequestCommit>): _137.RequestCommit;
            fromAmino(_: _137.RequestCommitAmino): _137.RequestCommit;
            toAmino(_: _137.RequestCommit): _137.RequestCommitAmino;
            fromAminoMsg(object: _137.RequestCommitAminoMsg): _137.RequestCommit;
            fromProtoMsg(message: _137.RequestCommitProtoMsg): _137.RequestCommit;
            toProto(message: _137.RequestCommit): Uint8Array;
            toProtoMsg(message: _137.RequestCommit): _137.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _137.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _137.RequestListSnapshots;
            fromPartial(_: Partial<_137.RequestListSnapshots>): _137.RequestListSnapshots;
            fromAmino(_: _137.RequestListSnapshotsAmino): _137.RequestListSnapshots;
            toAmino(_: _137.RequestListSnapshots): _137.RequestListSnapshotsAmino;
            fromAminoMsg(object: _137.RequestListSnapshotsAminoMsg): _137.RequestListSnapshots;
            fromProtoMsg(message: _137.RequestListSnapshotsProtoMsg): _137.RequestListSnapshots;
            toProto(message: _137.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _137.RequestListSnapshots): _137.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _137.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.RequestOfferSnapshot;
            fromPartial(object: Partial<_137.RequestOfferSnapshot>): _137.RequestOfferSnapshot;
            fromAmino(object: _137.RequestOfferSnapshotAmino): _137.RequestOfferSnapshot;
            toAmino(message: _137.RequestOfferSnapshot): _137.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _137.RequestOfferSnapshotAminoMsg): _137.RequestOfferSnapshot;
            fromProtoMsg(message: _137.RequestOfferSnapshotProtoMsg): _137.RequestOfferSnapshot;
            toProto(message: _137.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _137.RequestOfferSnapshot): _137.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _137.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_137.RequestLoadSnapshotChunk>): _137.RequestLoadSnapshotChunk;
            fromAmino(object: _137.RequestLoadSnapshotChunkAmino): _137.RequestLoadSnapshotChunk;
            toAmino(message: _137.RequestLoadSnapshotChunk): _137.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _137.RequestLoadSnapshotChunkAminoMsg): _137.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _137.RequestLoadSnapshotChunkProtoMsg): _137.RequestLoadSnapshotChunk;
            toProto(message: _137.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _137.RequestLoadSnapshotChunk): _137.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _137.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_137.RequestApplySnapshotChunk>): _137.RequestApplySnapshotChunk;
            fromAmino(object: _137.RequestApplySnapshotChunkAmino): _137.RequestApplySnapshotChunk;
            toAmino(message: _137.RequestApplySnapshotChunk): _137.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _137.RequestApplySnapshotChunkAminoMsg): _137.RequestApplySnapshotChunk;
            fromProtoMsg(message: _137.RequestApplySnapshotChunkProtoMsg): _137.RequestApplySnapshotChunk;
            toProto(message: _137.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _137.RequestApplySnapshotChunk): _137.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _137.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.Response;
            fromPartial(object: Partial<_137.Response>): _137.Response;
            fromAmino(object: _137.ResponseAmino): _137.Response;
            toAmino(message: _137.Response): _137.ResponseAmino;
            fromAminoMsg(object: _137.ResponseAminoMsg): _137.Response;
            fromProtoMsg(message: _137.ResponseProtoMsg): _137.Response;
            toProto(message: _137.Response): Uint8Array;
            toProtoMsg(message: _137.Response): _137.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _137.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseException;
            fromPartial(object: Partial<_137.ResponseException>): _137.ResponseException;
            fromAmino(object: _137.ResponseExceptionAmino): _137.ResponseException;
            toAmino(message: _137.ResponseException): _137.ResponseExceptionAmino;
            fromAminoMsg(object: _137.ResponseExceptionAminoMsg): _137.ResponseException;
            fromProtoMsg(message: _137.ResponseExceptionProtoMsg): _137.ResponseException;
            toProto(message: _137.ResponseException): Uint8Array;
            toProtoMsg(message: _137.ResponseException): _137.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _137.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseEcho;
            fromPartial(object: Partial<_137.ResponseEcho>): _137.ResponseEcho;
            fromAmino(object: _137.ResponseEchoAmino): _137.ResponseEcho;
            toAmino(message: _137.ResponseEcho): _137.ResponseEchoAmino;
            fromAminoMsg(object: _137.ResponseEchoAminoMsg): _137.ResponseEcho;
            fromProtoMsg(message: _137.ResponseEchoProtoMsg): _137.ResponseEcho;
            toProto(message: _137.ResponseEcho): Uint8Array;
            toProtoMsg(message: _137.ResponseEcho): _137.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _137.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _137.ResponseFlush;
            fromPartial(_: Partial<_137.ResponseFlush>): _137.ResponseFlush;
            fromAmino(_: _137.ResponseFlushAmino): _137.ResponseFlush;
            toAmino(_: _137.ResponseFlush): _137.ResponseFlushAmino;
            fromAminoMsg(object: _137.ResponseFlushAminoMsg): _137.ResponseFlush;
            fromProtoMsg(message: _137.ResponseFlushProtoMsg): _137.ResponseFlush;
            toProto(message: _137.ResponseFlush): Uint8Array;
            toProtoMsg(message: _137.ResponseFlush): _137.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _137.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseInfo;
            fromPartial(object: Partial<_137.ResponseInfo>): _137.ResponseInfo;
            fromAmino(object: _137.ResponseInfoAmino): _137.ResponseInfo;
            toAmino(message: _137.ResponseInfo): _137.ResponseInfoAmino;
            fromAminoMsg(object: _137.ResponseInfoAminoMsg): _137.ResponseInfo;
            fromProtoMsg(message: _137.ResponseInfoProtoMsg): _137.ResponseInfo;
            toProto(message: _137.ResponseInfo): Uint8Array;
            toProtoMsg(message: _137.ResponseInfo): _137.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            typeUrl: string;
            encode(message: _137.ResponseSetOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseSetOption;
            fromPartial(object: Partial<_137.ResponseSetOption>): _137.ResponseSetOption;
            fromAmino(object: _137.ResponseSetOptionAmino): _137.ResponseSetOption;
            toAmino(message: _137.ResponseSetOption): _137.ResponseSetOptionAmino;
            fromAminoMsg(object: _137.ResponseSetOptionAminoMsg): _137.ResponseSetOption;
            fromProtoMsg(message: _137.ResponseSetOptionProtoMsg): _137.ResponseSetOption;
            toProto(message: _137.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _137.ResponseSetOption): _137.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _137.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseInitChain;
            fromPartial(object: Partial<_137.ResponseInitChain>): _137.ResponseInitChain;
            fromAmino(object: _137.ResponseInitChainAmino): _137.ResponseInitChain;
            toAmino(message: _137.ResponseInitChain): _137.ResponseInitChainAmino;
            fromAminoMsg(object: _137.ResponseInitChainAminoMsg): _137.ResponseInitChain;
            fromProtoMsg(message: _137.ResponseInitChainProtoMsg): _137.ResponseInitChain;
            toProto(message: _137.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _137.ResponseInitChain): _137.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _137.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseQuery;
            fromPartial(object: Partial<_137.ResponseQuery>): _137.ResponseQuery;
            fromAmino(object: _137.ResponseQueryAmino): _137.ResponseQuery;
            toAmino(message: _137.ResponseQuery): _137.ResponseQueryAmino;
            fromAminoMsg(object: _137.ResponseQueryAminoMsg): _137.ResponseQuery;
            fromProtoMsg(message: _137.ResponseQueryProtoMsg): _137.ResponseQuery;
            toProto(message: _137.ResponseQuery): Uint8Array;
            toProtoMsg(message: _137.ResponseQuery): _137.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _137.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseBeginBlock;
            fromPartial(object: Partial<_137.ResponseBeginBlock>): _137.ResponseBeginBlock;
            fromAmino(object: _137.ResponseBeginBlockAmino): _137.ResponseBeginBlock;
            toAmino(message: _137.ResponseBeginBlock): _137.ResponseBeginBlockAmino;
            fromAminoMsg(object: _137.ResponseBeginBlockAminoMsg): _137.ResponseBeginBlock;
            fromProtoMsg(message: _137.ResponseBeginBlockProtoMsg): _137.ResponseBeginBlock;
            toProto(message: _137.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _137.ResponseBeginBlock): _137.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _137.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseCheckTx;
            fromPartial(object: Partial<_137.ResponseCheckTx>): _137.ResponseCheckTx;
            fromAmino(object: _137.ResponseCheckTxAmino): _137.ResponseCheckTx;
            toAmino(message: _137.ResponseCheckTx): _137.ResponseCheckTxAmino;
            fromAminoMsg(object: _137.ResponseCheckTxAminoMsg): _137.ResponseCheckTx;
            fromProtoMsg(message: _137.ResponseCheckTxProtoMsg): _137.ResponseCheckTx;
            toProto(message: _137.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _137.ResponseCheckTx): _137.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _137.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseDeliverTx;
            fromPartial(object: Partial<_137.ResponseDeliverTx>): _137.ResponseDeliverTx;
            fromAmino(object: _137.ResponseDeliverTxAmino): _137.ResponseDeliverTx;
            toAmino(message: _137.ResponseDeliverTx): _137.ResponseDeliverTxAmino;
            fromAminoMsg(object: _137.ResponseDeliverTxAminoMsg): _137.ResponseDeliverTx;
            fromProtoMsg(message: _137.ResponseDeliverTxProtoMsg): _137.ResponseDeliverTx;
            toProto(message: _137.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _137.ResponseDeliverTx): _137.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _137.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseEndBlock;
            fromPartial(object: Partial<_137.ResponseEndBlock>): _137.ResponseEndBlock;
            fromAmino(object: _137.ResponseEndBlockAmino): _137.ResponseEndBlock;
            toAmino(message: _137.ResponseEndBlock): _137.ResponseEndBlockAmino;
            fromAminoMsg(object: _137.ResponseEndBlockAminoMsg): _137.ResponseEndBlock;
            fromProtoMsg(message: _137.ResponseEndBlockProtoMsg): _137.ResponseEndBlock;
            toProto(message: _137.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _137.ResponseEndBlock): _137.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _137.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseCommit;
            fromPartial(object: Partial<_137.ResponseCommit>): _137.ResponseCommit;
            fromAmino(object: _137.ResponseCommitAmino): _137.ResponseCommit;
            toAmino(message: _137.ResponseCommit): _137.ResponseCommitAmino;
            fromAminoMsg(object: _137.ResponseCommitAminoMsg): _137.ResponseCommit;
            fromProtoMsg(message: _137.ResponseCommitProtoMsg): _137.ResponseCommit;
            toProto(message: _137.ResponseCommit): Uint8Array;
            toProtoMsg(message: _137.ResponseCommit): _137.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _137.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseListSnapshots;
            fromPartial(object: Partial<_137.ResponseListSnapshots>): _137.ResponseListSnapshots;
            fromAmino(object: _137.ResponseListSnapshotsAmino): _137.ResponseListSnapshots;
            toAmino(message: _137.ResponseListSnapshots): _137.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _137.ResponseListSnapshotsAminoMsg): _137.ResponseListSnapshots;
            fromProtoMsg(message: _137.ResponseListSnapshotsProtoMsg): _137.ResponseListSnapshots;
            toProto(message: _137.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _137.ResponseListSnapshots): _137.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _137.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseOfferSnapshot;
            fromPartial(object: Partial<_137.ResponseOfferSnapshot>): _137.ResponseOfferSnapshot;
            fromAmino(object: _137.ResponseOfferSnapshotAmino): _137.ResponseOfferSnapshot;
            toAmino(message: _137.ResponseOfferSnapshot): _137.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _137.ResponseOfferSnapshotAminoMsg): _137.ResponseOfferSnapshot;
            fromProtoMsg(message: _137.ResponseOfferSnapshotProtoMsg): _137.ResponseOfferSnapshot;
            toProto(message: _137.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _137.ResponseOfferSnapshot): _137.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _137.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_137.ResponseLoadSnapshotChunk>): _137.ResponseLoadSnapshotChunk;
            fromAmino(object: _137.ResponseLoadSnapshotChunkAmino): _137.ResponseLoadSnapshotChunk;
            toAmino(message: _137.ResponseLoadSnapshotChunk): _137.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _137.ResponseLoadSnapshotChunkAminoMsg): _137.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _137.ResponseLoadSnapshotChunkProtoMsg): _137.ResponseLoadSnapshotChunk;
            toProto(message: _137.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _137.ResponseLoadSnapshotChunk): _137.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _137.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_137.ResponseApplySnapshotChunk>): _137.ResponseApplySnapshotChunk;
            fromAmino(object: _137.ResponseApplySnapshotChunkAmino): _137.ResponseApplySnapshotChunk;
            toAmino(message: _137.ResponseApplySnapshotChunk): _137.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _137.ResponseApplySnapshotChunkAminoMsg): _137.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _137.ResponseApplySnapshotChunkProtoMsg): _137.ResponseApplySnapshotChunk;
            toProto(message: _137.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _137.ResponseApplySnapshotChunk): _137.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _137.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ConsensusParams;
            fromPartial(object: Partial<_137.ConsensusParams>): _137.ConsensusParams;
            fromAmino(object: _137.ConsensusParamsAmino): _137.ConsensusParams;
            toAmino(message: _137.ConsensusParams): _137.ConsensusParamsAmino;
            fromAminoMsg(object: _137.ConsensusParamsAminoMsg): _137.ConsensusParams;
            fromProtoMsg(message: _137.ConsensusParamsProtoMsg): _137.ConsensusParams;
            toProto(message: _137.ConsensusParams): Uint8Array;
            toProtoMsg(message: _137.ConsensusParams): _137.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _137.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.BlockParams;
            fromPartial(object: Partial<_137.BlockParams>): _137.BlockParams;
            fromAmino(object: _137.BlockParamsAmino): _137.BlockParams;
            toAmino(message: _137.BlockParams): _137.BlockParamsAmino;
            fromAminoMsg(object: _137.BlockParamsAminoMsg): _137.BlockParams;
            fromProtoMsg(message: _137.BlockParamsProtoMsg): _137.BlockParams;
            toProto(message: _137.BlockParams): Uint8Array;
            toProtoMsg(message: _137.BlockParams): _137.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            typeUrl: string;
            encode(message: _137.LastCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.LastCommitInfo;
            fromPartial(object: Partial<_137.LastCommitInfo>): _137.LastCommitInfo;
            fromAmino(object: _137.LastCommitInfoAmino): _137.LastCommitInfo;
            toAmino(message: _137.LastCommitInfo): _137.LastCommitInfoAmino;
            fromAminoMsg(object: _137.LastCommitInfoAminoMsg): _137.LastCommitInfo;
            fromProtoMsg(message: _137.LastCommitInfoProtoMsg): _137.LastCommitInfo;
            toProto(message: _137.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _137.LastCommitInfo): _137.LastCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _137.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.Event;
            fromPartial(object: Partial<_137.Event>): _137.Event;
            fromAmino(object: _137.EventAmino): _137.Event;
            toAmino(message: _137.Event): _137.EventAmino;
            fromAminoMsg(object: _137.EventAminoMsg): _137.Event;
            fromProtoMsg(message: _137.EventProtoMsg): _137.Event;
            toProto(message: _137.Event): Uint8Array;
            toProtoMsg(message: _137.Event): _137.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _137.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.EventAttribute;
            fromPartial(object: Partial<_137.EventAttribute>): _137.EventAttribute;
            fromAmino(object: _137.EventAttributeAmino): _137.EventAttribute;
            toAmino(message: _137.EventAttribute): _137.EventAttributeAmino;
            fromAminoMsg(object: _137.EventAttributeAminoMsg): _137.EventAttribute;
            fromProtoMsg(message: _137.EventAttributeProtoMsg): _137.EventAttribute;
            toProto(message: _137.EventAttribute): Uint8Array;
            toProtoMsg(message: _137.EventAttribute): _137.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _137.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.TxResult;
            fromPartial(object: Partial<_137.TxResult>): _137.TxResult;
            fromAmino(object: _137.TxResultAmino): _137.TxResult;
            toAmino(message: _137.TxResult): _137.TxResultAmino;
            fromAminoMsg(object: _137.TxResultAminoMsg): _137.TxResult;
            fromProtoMsg(message: _137.TxResultProtoMsg): _137.TxResult;
            toProto(message: _137.TxResult): Uint8Array;
            toProtoMsg(message: _137.TxResult): _137.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _137.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.Validator;
            fromPartial(object: Partial<_137.Validator>): _137.Validator;
            fromAmino(object: _137.ValidatorAmino): _137.Validator;
            toAmino(message: _137.Validator): _137.ValidatorAmino;
            fromAminoMsg(object: _137.ValidatorAminoMsg): _137.Validator;
            fromProtoMsg(message: _137.ValidatorProtoMsg): _137.Validator;
            toProto(message: _137.Validator): Uint8Array;
            toProtoMsg(message: _137.Validator): _137.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _137.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.ValidatorUpdate;
            fromPartial(object: Partial<_137.ValidatorUpdate>): _137.ValidatorUpdate;
            fromAmino(object: _137.ValidatorUpdateAmino): _137.ValidatorUpdate;
            toAmino(message: _137.ValidatorUpdate): _137.ValidatorUpdateAmino;
            fromAminoMsg(object: _137.ValidatorUpdateAminoMsg): _137.ValidatorUpdate;
            fromProtoMsg(message: _137.ValidatorUpdateProtoMsg): _137.ValidatorUpdate;
            toProto(message: _137.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _137.ValidatorUpdate): _137.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _137.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.VoteInfo;
            fromPartial(object: Partial<_137.VoteInfo>): _137.VoteInfo;
            fromAmino(object: _137.VoteInfoAmino): _137.VoteInfo;
            toAmino(message: _137.VoteInfo): _137.VoteInfoAmino;
            fromAminoMsg(object: _137.VoteInfoAminoMsg): _137.VoteInfo;
            fromProtoMsg(message: _137.VoteInfoProtoMsg): _137.VoteInfo;
            toProto(message: _137.VoteInfo): Uint8Array;
            toProtoMsg(message: _137.VoteInfo): _137.VoteInfoProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _137.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.Evidence;
            fromPartial(object: Partial<_137.Evidence>): _137.Evidence;
            fromAmino(object: _137.EvidenceAmino): _137.Evidence;
            toAmino(message: _137.Evidence): _137.EvidenceAmino;
            fromAminoMsg(object: _137.EvidenceAminoMsg): _137.Evidence;
            fromProtoMsg(message: _137.EvidenceProtoMsg): _137.Evidence;
            toProto(message: _137.Evidence): Uint8Array;
            toProtoMsg(message: _137.Evidence): _137.EvidenceProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _137.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _137.Snapshot;
            fromPartial(object: Partial<_137.Snapshot>): _137.Snapshot;
            fromAmino(object: _137.SnapshotAmino): _137.Snapshot;
            toAmino(message: _137.Snapshot): _137.SnapshotAmino;
            fromAminoMsg(object: _137.SnapshotAminoMsg): _137.Snapshot;
            fromProtoMsg(message: _137.SnapshotProtoMsg): _137.Snapshot;
            toProto(message: _137.Snapshot): Uint8Array;
            toProtoMsg(message: _137.Snapshot): _137.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _139.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _139.Proof;
            fromPartial(object: Partial<_139.Proof>): _139.Proof;
            fromAmino(object: _139.ProofAmino): _139.Proof;
            toAmino(message: _139.Proof): _139.ProofAmino;
            fromAminoMsg(object: _139.ProofAminoMsg): _139.Proof;
            fromProtoMsg(message: _139.ProofProtoMsg): _139.Proof;
            toProto(message: _139.Proof): Uint8Array;
            toProtoMsg(message: _139.Proof): _139.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _139.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _139.ValueOp;
            fromPartial(object: Partial<_139.ValueOp>): _139.ValueOp;
            fromAmino(object: _139.ValueOpAmino): _139.ValueOp;
            toAmino(message: _139.ValueOp): _139.ValueOpAmino;
            fromAminoMsg(object: _139.ValueOpAminoMsg): _139.ValueOp;
            fromProtoMsg(message: _139.ValueOpProtoMsg): _139.ValueOp;
            toProto(message: _139.ValueOp): Uint8Array;
            toProtoMsg(message: _139.ValueOp): _139.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _139.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _139.DominoOp;
            fromPartial(object: Partial<_139.DominoOp>): _139.DominoOp;
            fromAmino(object: _139.DominoOpAmino): _139.DominoOp;
            toAmino(message: _139.DominoOp): _139.DominoOpAmino;
            fromAminoMsg(object: _139.DominoOpAminoMsg): _139.DominoOp;
            fromProtoMsg(message: _139.DominoOpProtoMsg): _139.DominoOp;
            toProto(message: _139.DominoOp): Uint8Array;
            toProtoMsg(message: _139.DominoOp): _139.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _139.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _139.ProofOp;
            fromPartial(object: Partial<_139.ProofOp>): _139.ProofOp;
            fromAmino(object: _139.ProofOpAmino): _139.ProofOp;
            toAmino(message: _139.ProofOp): _139.ProofOpAmino;
            fromAminoMsg(object: _139.ProofOpAminoMsg): _139.ProofOp;
            fromProtoMsg(message: _139.ProofOpProtoMsg): _139.ProofOp;
            toProto(message: _139.ProofOp): Uint8Array;
            toProtoMsg(message: _139.ProofOp): _139.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _139.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _139.ProofOps;
            fromPartial(object: Partial<_139.ProofOps>): _139.ProofOps;
            fromAmino(object: _139.ProofOpsAmino): _139.ProofOps;
            toAmino(message: _139.ProofOps): _139.ProofOpsAmino;
            fromAminoMsg(object: _139.ProofOpsAminoMsg): _139.ProofOps;
            fromProtoMsg(message: _139.ProofOpsProtoMsg): _139.ProofOps;
            toProto(message: _139.ProofOps): Uint8Array;
            toProtoMsg(message: _139.ProofOps): _139.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _138.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _138.PublicKey;
            fromPartial(object: Partial<_138.PublicKey>): _138.PublicKey;
            fromAmino(object: _138.PublicKeyAmino): _138.PublicKey;
            toAmino(message: _138.PublicKey): _138.PublicKeyAmino;
            fromAminoMsg(object: _138.PublicKeyAminoMsg): _138.PublicKey;
            fromProtoMsg(message: _138.PublicKeyProtoMsg): _138.PublicKey;
            toProto(message: _138.PublicKey): Uint8Array;
            toProtoMsg(message: _138.PublicKey): _138.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _140.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                fromJSON(object: any): _140.BitArray;
                fromPartial(object: Partial<_140.BitArray>): _140.BitArray;
                fromAmino(object: _140.BitArrayAmino): _140.BitArray;
                toAmino(message: _140.BitArray): _140.BitArrayAmino;
                fromAminoMsg(object: _140.BitArrayAminoMsg): _140.BitArray;
                fromProtoMsg(message: _140.BitArrayProtoMsg): _140.BitArray;
                toProto(message: _140.BitArray): Uint8Array;
                toProtoMsg(message: _140.BitArray): _140.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _141.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.NetAddress;
            fromPartial(object: Partial<_141.NetAddress>): _141.NetAddress;
            fromAmino(object: _141.NetAddressAmino): _141.NetAddress;
            toAmino(message: _141.NetAddress): _141.NetAddressAmino;
            fromAminoMsg(object: _141.NetAddressAminoMsg): _141.NetAddress;
            fromProtoMsg(message: _141.NetAddressProtoMsg): _141.NetAddress;
            toProto(message: _141.NetAddress): Uint8Array;
            toProtoMsg(message: _141.NetAddress): _141.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _141.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.ProtocolVersion;
            fromPartial(object: Partial<_141.ProtocolVersion>): _141.ProtocolVersion;
            fromAmino(object: _141.ProtocolVersionAmino): _141.ProtocolVersion;
            toAmino(message: _141.ProtocolVersion): _141.ProtocolVersionAmino;
            fromAminoMsg(object: _141.ProtocolVersionAminoMsg): _141.ProtocolVersion;
            fromProtoMsg(message: _141.ProtocolVersionProtoMsg): _141.ProtocolVersion;
            toProto(message: _141.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _141.ProtocolVersion): _141.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _141.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.DefaultNodeInfo;
            fromPartial(object: Partial<_141.DefaultNodeInfo>): _141.DefaultNodeInfo;
            fromAmino(object: _141.DefaultNodeInfoAmino): _141.DefaultNodeInfo;
            toAmino(message: _141.DefaultNodeInfo): _141.DefaultNodeInfoAmino;
            fromAminoMsg(object: _141.DefaultNodeInfoAminoMsg): _141.DefaultNodeInfo;
            fromProtoMsg(message: _141.DefaultNodeInfoProtoMsg): _141.DefaultNodeInfo;
            toProto(message: _141.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _141.DefaultNodeInfo): _141.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _141.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _141.DefaultNodeInfoOther;
            fromPartial(object: Partial<_141.DefaultNodeInfoOther>): _141.DefaultNodeInfoOther;
            fromAmino(object: _141.DefaultNodeInfoOtherAmino): _141.DefaultNodeInfoOther;
            toAmino(message: _141.DefaultNodeInfoOther): _141.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _141.DefaultNodeInfoOtherAminoMsg): _141.DefaultNodeInfoOther;
            fromProtoMsg(message: _141.DefaultNodeInfoOtherProtoMsg): _141.DefaultNodeInfoOther;
            toProto(message: _141.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _141.DefaultNodeInfoOther): _141.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _146.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _146.ValidatorSet;
            fromPartial(object: Partial<_146.ValidatorSet>): _146.ValidatorSet;
            fromAmino(object: _146.ValidatorSetAmino): _146.ValidatorSet;
            toAmino(message: _146.ValidatorSet): _146.ValidatorSetAmino;
            fromAminoMsg(object: _146.ValidatorSetAminoMsg): _146.ValidatorSet;
            fromProtoMsg(message: _146.ValidatorSetProtoMsg): _146.ValidatorSet;
            toProto(message: _146.ValidatorSet): Uint8Array;
            toProtoMsg(message: _146.ValidatorSet): _146.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _146.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _146.Validator;
            fromPartial(object: Partial<_146.Validator>): _146.Validator;
            fromAmino(object: _146.ValidatorAmino): _146.Validator;
            toAmino(message: _146.Validator): _146.ValidatorAmino;
            fromAminoMsg(object: _146.ValidatorAminoMsg): _146.Validator;
            fromProtoMsg(message: _146.ValidatorProtoMsg): _146.Validator;
            toProto(message: _146.Validator): Uint8Array;
            toProtoMsg(message: _146.Validator): _146.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _146.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _146.SimpleValidator;
            fromPartial(object: Partial<_146.SimpleValidator>): _146.SimpleValidator;
            fromAmino(object: _146.SimpleValidatorAmino): _146.SimpleValidator;
            toAmino(message: _146.SimpleValidator): _146.SimpleValidatorAmino;
            fromAminoMsg(object: _146.SimpleValidatorAminoMsg): _146.SimpleValidator;
            fromProtoMsg(message: _146.SimpleValidatorProtoMsg): _146.SimpleValidator;
            toProto(message: _146.SimpleValidator): Uint8Array;
            toProtoMsg(message: _146.SimpleValidator): _146.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _145.BlockIDFlag;
        blockIDFlagToJSON(object: _145.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _145.SignedMsgType;
        signedMsgTypeToJSON(object: _145.SignedMsgType): string;
        BlockIDFlag: typeof _145.BlockIDFlag;
        BlockIDFlagSDKType: typeof _145.BlockIDFlag;
        BlockIDFlagAmino: typeof _145.BlockIDFlag;
        SignedMsgType: typeof _145.SignedMsgType;
        SignedMsgTypeSDKType: typeof _145.SignedMsgType;
        SignedMsgTypeAmino: typeof _145.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _145.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.PartSetHeader;
            fromPartial(object: Partial<_145.PartSetHeader>): _145.PartSetHeader;
            fromAmino(object: _145.PartSetHeaderAmino): _145.PartSetHeader;
            toAmino(message: _145.PartSetHeader): _145.PartSetHeaderAmino;
            fromAminoMsg(object: _145.PartSetHeaderAminoMsg): _145.PartSetHeader;
            fromProtoMsg(message: _145.PartSetHeaderProtoMsg): _145.PartSetHeader;
            toProto(message: _145.PartSetHeader): Uint8Array;
            toProtoMsg(message: _145.PartSetHeader): _145.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _145.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.Part;
            fromPartial(object: Partial<_145.Part>): _145.Part;
            fromAmino(object: _145.PartAmino): _145.Part;
            toAmino(message: _145.Part): _145.PartAmino;
            fromAminoMsg(object: _145.PartAminoMsg): _145.Part;
            fromProtoMsg(message: _145.PartProtoMsg): _145.Part;
            toProto(message: _145.Part): Uint8Array;
            toProtoMsg(message: _145.Part): _145.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _145.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.BlockID;
            fromPartial(object: Partial<_145.BlockID>): _145.BlockID;
            fromAmino(object: _145.BlockIDAmino): _145.BlockID;
            toAmino(message: _145.BlockID): _145.BlockIDAmino;
            fromAminoMsg(object: _145.BlockIDAminoMsg): _145.BlockID;
            fromProtoMsg(message: _145.BlockIDProtoMsg): _145.BlockID;
            toProto(message: _145.BlockID): Uint8Array;
            toProtoMsg(message: _145.BlockID): _145.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _145.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.Header;
            fromPartial(object: Partial<_145.Header>): _145.Header;
            fromAmino(object: _145.HeaderAmino): _145.Header;
            toAmino(message: _145.Header): _145.HeaderAmino;
            fromAminoMsg(object: _145.HeaderAminoMsg): _145.Header;
            fromProtoMsg(message: _145.HeaderProtoMsg): _145.Header;
            toProto(message: _145.Header): Uint8Array;
            toProtoMsg(message: _145.Header): _145.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _145.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.Data;
            fromPartial(object: Partial<_145.Data>): _145.Data;
            fromAmino(object: _145.DataAmino): _145.Data;
            toAmino(message: _145.Data): _145.DataAmino;
            fromAminoMsg(object: _145.DataAminoMsg): _145.Data;
            fromProtoMsg(message: _145.DataProtoMsg): _145.Data;
            toProto(message: _145.Data): Uint8Array;
            toProtoMsg(message: _145.Data): _145.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _145.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.Vote;
            fromPartial(object: Partial<_145.Vote>): _145.Vote;
            fromAmino(object: _145.VoteAmino): _145.Vote;
            toAmino(message: _145.Vote): _145.VoteAmino;
            fromAminoMsg(object: _145.VoteAminoMsg): _145.Vote;
            fromProtoMsg(message: _145.VoteProtoMsg): _145.Vote;
            toProto(message: _145.Vote): Uint8Array;
            toProtoMsg(message: _145.Vote): _145.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _145.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.Commit;
            fromPartial(object: Partial<_145.Commit>): _145.Commit;
            fromAmino(object: _145.CommitAmino): _145.Commit;
            toAmino(message: _145.Commit): _145.CommitAmino;
            fromAminoMsg(object: _145.CommitAminoMsg): _145.Commit;
            fromProtoMsg(message: _145.CommitProtoMsg): _145.Commit;
            toProto(message: _145.Commit): Uint8Array;
            toProtoMsg(message: _145.Commit): _145.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _145.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.CommitSig;
            fromPartial(object: Partial<_145.CommitSig>): _145.CommitSig;
            fromAmino(object: _145.CommitSigAmino): _145.CommitSig;
            toAmino(message: _145.CommitSig): _145.CommitSigAmino;
            fromAminoMsg(object: _145.CommitSigAminoMsg): _145.CommitSig;
            fromProtoMsg(message: _145.CommitSigProtoMsg): _145.CommitSig;
            toProto(message: _145.CommitSig): Uint8Array;
            toProtoMsg(message: _145.CommitSig): _145.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _145.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.Proposal;
            fromPartial(object: Partial<_145.Proposal>): _145.Proposal;
            fromAmino(object: _145.ProposalAmino): _145.Proposal;
            toAmino(message: _145.Proposal): _145.ProposalAmino;
            fromAminoMsg(object: _145.ProposalAminoMsg): _145.Proposal;
            fromProtoMsg(message: _145.ProposalProtoMsg): _145.Proposal;
            toProto(message: _145.Proposal): Uint8Array;
            toProtoMsg(message: _145.Proposal): _145.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _145.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.SignedHeader;
            fromPartial(object: Partial<_145.SignedHeader>): _145.SignedHeader;
            fromAmino(object: _145.SignedHeaderAmino): _145.SignedHeader;
            toAmino(message: _145.SignedHeader): _145.SignedHeaderAmino;
            fromAminoMsg(object: _145.SignedHeaderAminoMsg): _145.SignedHeader;
            fromProtoMsg(message: _145.SignedHeaderProtoMsg): _145.SignedHeader;
            toProto(message: _145.SignedHeader): Uint8Array;
            toProtoMsg(message: _145.SignedHeader): _145.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _145.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.LightBlock;
            fromPartial(object: Partial<_145.LightBlock>): _145.LightBlock;
            fromAmino(object: _145.LightBlockAmino): _145.LightBlock;
            toAmino(message: _145.LightBlock): _145.LightBlockAmino;
            fromAminoMsg(object: _145.LightBlockAminoMsg): _145.LightBlock;
            fromProtoMsg(message: _145.LightBlockProtoMsg): _145.LightBlock;
            toProto(message: _145.LightBlock): Uint8Array;
            toProtoMsg(message: _145.LightBlock): _145.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _145.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.BlockMeta;
            fromPartial(object: Partial<_145.BlockMeta>): _145.BlockMeta;
            fromAmino(object: _145.BlockMetaAmino): _145.BlockMeta;
            toAmino(message: _145.BlockMeta): _145.BlockMetaAmino;
            fromAminoMsg(object: _145.BlockMetaAminoMsg): _145.BlockMeta;
            fromProtoMsg(message: _145.BlockMetaProtoMsg): _145.BlockMeta;
            toProto(message: _145.BlockMeta): Uint8Array;
            toProtoMsg(message: _145.BlockMeta): _145.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _145.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _145.TxProof;
            fromPartial(object: Partial<_145.TxProof>): _145.TxProof;
            fromAmino(object: _145.TxProofAmino): _145.TxProof;
            toAmino(message: _145.TxProof): _145.TxProofAmino;
            fromAminoMsg(object: _145.TxProofAminoMsg): _145.TxProof;
            fromProtoMsg(message: _145.TxProofProtoMsg): _145.TxProof;
            toProto(message: _145.TxProof): Uint8Array;
            toProtoMsg(message: _145.TxProof): _145.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _144.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _144.ConsensusParams;
            fromPartial(object: Partial<_144.ConsensusParams>): _144.ConsensusParams;
            fromAmino(object: _144.ConsensusParamsAmino): _144.ConsensusParams;
            toAmino(message: _144.ConsensusParams): _144.ConsensusParamsAmino;
            fromAminoMsg(object: _144.ConsensusParamsAminoMsg): _144.ConsensusParams;
            fromProtoMsg(message: _144.ConsensusParamsProtoMsg): _144.ConsensusParams;
            toProto(message: _144.ConsensusParams): Uint8Array;
            toProtoMsg(message: _144.ConsensusParams): _144.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _144.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _144.BlockParams;
            fromPartial(object: Partial<_144.BlockParams>): _144.BlockParams;
            fromAmino(object: _144.BlockParamsAmino): _144.BlockParams;
            toAmino(message: _144.BlockParams): _144.BlockParamsAmino;
            fromAminoMsg(object: _144.BlockParamsAminoMsg): _144.BlockParams;
            fromProtoMsg(message: _144.BlockParamsProtoMsg): _144.BlockParams;
            toProto(message: _144.BlockParams): Uint8Array;
            toProtoMsg(message: _144.BlockParams): _144.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _144.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _144.EvidenceParams;
            fromPartial(object: Partial<_144.EvidenceParams>): _144.EvidenceParams;
            fromAmino(object: _144.EvidenceParamsAmino): _144.EvidenceParams;
            toAmino(message: _144.EvidenceParams): _144.EvidenceParamsAmino;
            fromAminoMsg(object: _144.EvidenceParamsAminoMsg): _144.EvidenceParams;
            fromProtoMsg(message: _144.EvidenceParamsProtoMsg): _144.EvidenceParams;
            toProto(message: _144.EvidenceParams): Uint8Array;
            toProtoMsg(message: _144.EvidenceParams): _144.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _144.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _144.ValidatorParams;
            fromPartial(object: Partial<_144.ValidatorParams>): _144.ValidatorParams;
            fromAmino(object: _144.ValidatorParamsAmino): _144.ValidatorParams;
            toAmino(message: _144.ValidatorParams): _144.ValidatorParamsAmino;
            fromAminoMsg(object: _144.ValidatorParamsAminoMsg): _144.ValidatorParams;
            fromProtoMsg(message: _144.ValidatorParamsProtoMsg): _144.ValidatorParams;
            toProto(message: _144.ValidatorParams): Uint8Array;
            toProtoMsg(message: _144.ValidatorParams): _144.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _144.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _144.VersionParams;
            fromPartial(object: Partial<_144.VersionParams>): _144.VersionParams;
            fromAmino(object: _144.VersionParamsAmino): _144.VersionParams;
            toAmino(message: _144.VersionParams): _144.VersionParamsAmino;
            fromAminoMsg(object: _144.VersionParamsAminoMsg): _144.VersionParams;
            fromProtoMsg(message: _144.VersionParamsProtoMsg): _144.VersionParams;
            toProto(message: _144.VersionParams): Uint8Array;
            toProtoMsg(message: _144.VersionParams): _144.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _144.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _144.HashedParams;
            fromPartial(object: Partial<_144.HashedParams>): _144.HashedParams;
            fromAmino(object: _144.HashedParamsAmino): _144.HashedParams;
            toAmino(message: _144.HashedParams): _144.HashedParamsAmino;
            fromAminoMsg(object: _144.HashedParamsAminoMsg): _144.HashedParams;
            fromProtoMsg(message: _144.HashedParamsProtoMsg): _144.HashedParams;
            toProto(message: _144.HashedParams): Uint8Array;
            toProtoMsg(message: _144.HashedParams): _144.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _143.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.Evidence;
            fromPartial(object: Partial<_143.Evidence>): _143.Evidence;
            fromAmino(object: _143.EvidenceAmino): _143.Evidence;
            toAmino(message: _143.Evidence): _143.EvidenceAmino;
            fromAminoMsg(object: _143.EvidenceAminoMsg): _143.Evidence;
            fromProtoMsg(message: _143.EvidenceProtoMsg): _143.Evidence;
            toProto(message: _143.Evidence): Uint8Array;
            toProtoMsg(message: _143.Evidence): _143.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _143.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.DuplicateVoteEvidence;
            fromPartial(object: Partial<_143.DuplicateVoteEvidence>): _143.DuplicateVoteEvidence;
            fromAmino(object: _143.DuplicateVoteEvidenceAmino): _143.DuplicateVoteEvidence;
            toAmino(message: _143.DuplicateVoteEvidence): _143.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _143.DuplicateVoteEvidenceAminoMsg): _143.DuplicateVoteEvidence;
            fromProtoMsg(message: _143.DuplicateVoteEvidenceProtoMsg): _143.DuplicateVoteEvidence;
            toProto(message: _143.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _143.DuplicateVoteEvidence): _143.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _143.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.LightClientAttackEvidence;
            fromPartial(object: Partial<_143.LightClientAttackEvidence>): _143.LightClientAttackEvidence;
            fromAmino(object: _143.LightClientAttackEvidenceAmino): _143.LightClientAttackEvidence;
            toAmino(message: _143.LightClientAttackEvidence): _143.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _143.LightClientAttackEvidenceAminoMsg): _143.LightClientAttackEvidence;
            fromProtoMsg(message: _143.LightClientAttackEvidenceProtoMsg): _143.LightClientAttackEvidence;
            toProto(message: _143.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _143.LightClientAttackEvidence): _143.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _143.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _143.EvidenceList;
            fromPartial(object: Partial<_143.EvidenceList>): _143.EvidenceList;
            fromAmino(object: _143.EvidenceListAmino): _143.EvidenceList;
            toAmino(message: _143.EvidenceList): _143.EvidenceListAmino;
            fromAminoMsg(object: _143.EvidenceListAminoMsg): _143.EvidenceList;
            fromProtoMsg(message: _143.EvidenceListProtoMsg): _143.EvidenceList;
            toProto(message: _143.EvidenceList): Uint8Array;
            toProtoMsg(message: _143.EvidenceList): _143.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _142.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _142.Block;
            fromPartial(object: Partial<_142.Block>): _142.Block;
            fromAmino(object: _142.BlockAmino): _142.Block;
            toAmino(message: _142.Block): _142.BlockAmino;
            fromAminoMsg(object: _142.BlockAminoMsg): _142.Block;
            fromProtoMsg(message: _142.BlockProtoMsg): _142.Block;
            toProto(message: _142.Block): Uint8Array;
            toProtoMsg(message: _142.Block): _142.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _147.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _147.App;
            fromPartial(object: Partial<_147.App>): _147.App;
            fromAmino(object: _147.AppAmino): _147.App;
            toAmino(message: _147.App): _147.AppAmino;
            fromAminoMsg(object: _147.AppAminoMsg): _147.App;
            fromProtoMsg(message: _147.AppProtoMsg): _147.App;
            toProto(message: _147.App): Uint8Array;
            toProtoMsg(message: _147.App): _147.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _147.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _147.Consensus;
            fromPartial(object: Partial<_147.Consensus>): _147.Consensus;
            fromAmino(object: _147.ConsensusAmino): _147.Consensus;
            toAmino(message: _147.Consensus): _147.ConsensusAmino;
            fromAminoMsg(object: _147.ConsensusAminoMsg): _147.Consensus;
            fromProtoMsg(message: _147.ConsensusProtoMsg): _147.Consensus;
            toProto(message: _147.Consensus): Uint8Array;
            toProtoMsg(message: _147.Consensus): _147.ConsensusProtoMsg;
        };
    };
}
