import * as _174 from "./abci/types";
import * as _175 from "./crypto/keys";
import * as _176 from "./crypto/proof";
import * as _177 from "./libs/bits/types";
import * as _178 from "./p2p/types";
import * as _179 from "./types/block";
import * as _180 from "./types/evidence";
import * as _181 from "./types/params";
import * as _182 from "./types/types";
import * as _183 from "./types/validator";
import * as _184 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _174.CheckTxType;
        checkTxTypeToJSON(object: _174.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _174.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _174.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _174.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _174.ResponseApplySnapshotChunk_Result): string;
        responseProcessProposal_ProposalStatusFromJSON(object: any): _174.ResponseProcessProposal_ProposalStatus;
        responseProcessProposal_ProposalStatusToJSON(object: _174.ResponseProcessProposal_ProposalStatus): string;
        misbehaviorTypeFromJSON(object: any): _174.MisbehaviorType;
        misbehaviorTypeToJSON(object: _174.MisbehaviorType): string;
        CheckTxType: typeof _174.CheckTxType;
        CheckTxTypeSDKType: typeof _174.CheckTxType;
        CheckTxTypeAmino: typeof _174.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _174.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _174.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _174.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _174.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _174.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _174.ResponseApplySnapshotChunk_Result;
        ResponseProcessProposal_ProposalStatus: typeof _174.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusSDKType: typeof _174.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusAmino: typeof _174.ResponseProcessProposal_ProposalStatus;
        MisbehaviorType: typeof _174.MisbehaviorType;
        MisbehaviorTypeSDKType: typeof _174.MisbehaviorType;
        MisbehaviorTypeAmino: typeof _174.MisbehaviorType;
        Request: {
            typeUrl: string;
            encode(message: _174.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.Request;
            fromPartial(object: Partial<_174.Request>): _174.Request;
            fromAmino(object: _174.RequestAmino): _174.Request;
            toAmino(message: _174.Request): _174.RequestAmino;
            fromAminoMsg(object: _174.RequestAminoMsg): _174.Request;
            fromProtoMsg(message: _174.RequestProtoMsg): _174.Request;
            toProto(message: _174.Request): Uint8Array;
            toProtoMsg(message: _174.Request): _174.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _174.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestEcho;
            fromPartial(object: Partial<_174.RequestEcho>): _174.RequestEcho;
            fromAmino(object: _174.RequestEchoAmino): _174.RequestEcho;
            toAmino(message: _174.RequestEcho): _174.RequestEchoAmino;
            fromAminoMsg(object: _174.RequestEchoAminoMsg): _174.RequestEcho;
            fromProtoMsg(message: _174.RequestEchoProtoMsg): _174.RequestEcho;
            toProto(message: _174.RequestEcho): Uint8Array;
            toProtoMsg(message: _174.RequestEcho): _174.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _174.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _174.RequestFlush;
            fromPartial(_: Partial<_174.RequestFlush>): _174.RequestFlush;
            fromAmino(_: _174.RequestFlushAmino): _174.RequestFlush;
            toAmino(_: _174.RequestFlush): _174.RequestFlushAmino;
            fromAminoMsg(object: _174.RequestFlushAminoMsg): _174.RequestFlush;
            fromProtoMsg(message: _174.RequestFlushProtoMsg): _174.RequestFlush;
            toProto(message: _174.RequestFlush): Uint8Array;
            toProtoMsg(message: _174.RequestFlush): _174.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _174.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestInfo;
            fromPartial(object: Partial<_174.RequestInfo>): _174.RequestInfo;
            fromAmino(object: _174.RequestInfoAmino): _174.RequestInfo;
            toAmino(message: _174.RequestInfo): _174.RequestInfoAmino;
            fromAminoMsg(object: _174.RequestInfoAminoMsg): _174.RequestInfo;
            fromProtoMsg(message: _174.RequestInfoProtoMsg): _174.RequestInfo;
            toProto(message: _174.RequestInfo): Uint8Array;
            toProtoMsg(message: _174.RequestInfo): _174.RequestInfoProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _174.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestInitChain;
            fromPartial(object: Partial<_174.RequestInitChain>): _174.RequestInitChain;
            fromAmino(object: _174.RequestInitChainAmino): _174.RequestInitChain;
            toAmino(message: _174.RequestInitChain): _174.RequestInitChainAmino;
            fromAminoMsg(object: _174.RequestInitChainAminoMsg): _174.RequestInitChain;
            fromProtoMsg(message: _174.RequestInitChainProtoMsg): _174.RequestInitChain;
            toProto(message: _174.RequestInitChain): Uint8Array;
            toProtoMsg(message: _174.RequestInitChain): _174.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _174.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestQuery;
            fromPartial(object: Partial<_174.RequestQuery>): _174.RequestQuery;
            fromAmino(object: _174.RequestQueryAmino): _174.RequestQuery;
            toAmino(message: _174.RequestQuery): _174.RequestQueryAmino;
            fromAminoMsg(object: _174.RequestQueryAminoMsg): _174.RequestQuery;
            fromProtoMsg(message: _174.RequestQueryProtoMsg): _174.RequestQuery;
            toProto(message: _174.RequestQuery): Uint8Array;
            toProtoMsg(message: _174.RequestQuery): _174.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _174.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestBeginBlock;
            fromPartial(object: Partial<_174.RequestBeginBlock>): _174.RequestBeginBlock;
            fromAmino(object: _174.RequestBeginBlockAmino): _174.RequestBeginBlock;
            toAmino(message: _174.RequestBeginBlock): _174.RequestBeginBlockAmino;
            fromAminoMsg(object: _174.RequestBeginBlockAminoMsg): _174.RequestBeginBlock;
            fromProtoMsg(message: _174.RequestBeginBlockProtoMsg): _174.RequestBeginBlock;
            toProto(message: _174.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _174.RequestBeginBlock): _174.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _174.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestCheckTx;
            fromPartial(object: Partial<_174.RequestCheckTx>): _174.RequestCheckTx;
            fromAmino(object: _174.RequestCheckTxAmino): _174.RequestCheckTx;
            toAmino(message: _174.RequestCheckTx): _174.RequestCheckTxAmino;
            fromAminoMsg(object: _174.RequestCheckTxAminoMsg): _174.RequestCheckTx;
            fromProtoMsg(message: _174.RequestCheckTxProtoMsg): _174.RequestCheckTx;
            toProto(message: _174.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _174.RequestCheckTx): _174.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _174.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestDeliverTx;
            fromPartial(object: Partial<_174.RequestDeliverTx>): _174.RequestDeliverTx;
            fromAmino(object: _174.RequestDeliverTxAmino): _174.RequestDeliverTx;
            toAmino(message: _174.RequestDeliverTx): _174.RequestDeliverTxAmino;
            fromAminoMsg(object: _174.RequestDeliverTxAminoMsg): _174.RequestDeliverTx;
            fromProtoMsg(message: _174.RequestDeliverTxProtoMsg): _174.RequestDeliverTx;
            toProto(message: _174.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _174.RequestDeliverTx): _174.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _174.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestEndBlock;
            fromPartial(object: Partial<_174.RequestEndBlock>): _174.RequestEndBlock;
            fromAmino(object: _174.RequestEndBlockAmino): _174.RequestEndBlock;
            toAmino(message: _174.RequestEndBlock): _174.RequestEndBlockAmino;
            fromAminoMsg(object: _174.RequestEndBlockAminoMsg): _174.RequestEndBlock;
            fromProtoMsg(message: _174.RequestEndBlockProtoMsg): _174.RequestEndBlock;
            toProto(message: _174.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _174.RequestEndBlock): _174.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _174.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _174.RequestCommit;
            fromPartial(_: Partial<_174.RequestCommit>): _174.RequestCommit;
            fromAmino(_: _174.RequestCommitAmino): _174.RequestCommit;
            toAmino(_: _174.RequestCommit): _174.RequestCommitAmino;
            fromAminoMsg(object: _174.RequestCommitAminoMsg): _174.RequestCommit;
            fromProtoMsg(message: _174.RequestCommitProtoMsg): _174.RequestCommit;
            toProto(message: _174.RequestCommit): Uint8Array;
            toProtoMsg(message: _174.RequestCommit): _174.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _174.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _174.RequestListSnapshots;
            fromPartial(_: Partial<_174.RequestListSnapshots>): _174.RequestListSnapshots;
            fromAmino(_: _174.RequestListSnapshotsAmino): _174.RequestListSnapshots;
            toAmino(_: _174.RequestListSnapshots): _174.RequestListSnapshotsAmino;
            fromAminoMsg(object: _174.RequestListSnapshotsAminoMsg): _174.RequestListSnapshots;
            fromProtoMsg(message: _174.RequestListSnapshotsProtoMsg): _174.RequestListSnapshots;
            toProto(message: _174.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _174.RequestListSnapshots): _174.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _174.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestOfferSnapshot;
            fromPartial(object: Partial<_174.RequestOfferSnapshot>): _174.RequestOfferSnapshot;
            fromAmino(object: _174.RequestOfferSnapshotAmino): _174.RequestOfferSnapshot;
            toAmino(message: _174.RequestOfferSnapshot): _174.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _174.RequestOfferSnapshotAminoMsg): _174.RequestOfferSnapshot;
            fromProtoMsg(message: _174.RequestOfferSnapshotProtoMsg): _174.RequestOfferSnapshot;
            toProto(message: _174.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _174.RequestOfferSnapshot): _174.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _174.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestLoadSnapshotChunk;
            fromPartial(object: Partial<_174.RequestLoadSnapshotChunk>): _174.RequestLoadSnapshotChunk;
            fromAmino(object: _174.RequestLoadSnapshotChunkAmino): _174.RequestLoadSnapshotChunk;
            toAmino(message: _174.RequestLoadSnapshotChunk): _174.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _174.RequestLoadSnapshotChunkAminoMsg): _174.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _174.RequestLoadSnapshotChunkProtoMsg): _174.RequestLoadSnapshotChunk;
            toProto(message: _174.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _174.RequestLoadSnapshotChunk): _174.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _174.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestApplySnapshotChunk;
            fromPartial(object: Partial<_174.RequestApplySnapshotChunk>): _174.RequestApplySnapshotChunk;
            fromAmino(object: _174.RequestApplySnapshotChunkAmino): _174.RequestApplySnapshotChunk;
            toAmino(message: _174.RequestApplySnapshotChunk): _174.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _174.RequestApplySnapshotChunkAminoMsg): _174.RequestApplySnapshotChunk;
            fromProtoMsg(message: _174.RequestApplySnapshotChunkProtoMsg): _174.RequestApplySnapshotChunk;
            toProto(message: _174.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _174.RequestApplySnapshotChunk): _174.RequestApplySnapshotChunkProtoMsg;
        };
        RequestPrepareProposal: {
            typeUrl: string;
            encode(message: _174.RequestPrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestPrepareProposal;
            fromPartial(object: Partial<_174.RequestPrepareProposal>): _174.RequestPrepareProposal;
            fromAmino(object: _174.RequestPrepareProposalAmino): _174.RequestPrepareProposal;
            toAmino(message: _174.RequestPrepareProposal): _174.RequestPrepareProposalAmino;
            fromAminoMsg(object: _174.RequestPrepareProposalAminoMsg): _174.RequestPrepareProposal;
            fromProtoMsg(message: _174.RequestPrepareProposalProtoMsg): _174.RequestPrepareProposal;
            toProto(message: _174.RequestPrepareProposal): Uint8Array;
            toProtoMsg(message: _174.RequestPrepareProposal): _174.RequestPrepareProposalProtoMsg;
        };
        RequestProcessProposal: {
            typeUrl: string;
            encode(message: _174.RequestProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.RequestProcessProposal;
            fromPartial(object: Partial<_174.RequestProcessProposal>): _174.RequestProcessProposal;
            fromAmino(object: _174.RequestProcessProposalAmino): _174.RequestProcessProposal;
            toAmino(message: _174.RequestProcessProposal): _174.RequestProcessProposalAmino;
            fromAminoMsg(object: _174.RequestProcessProposalAminoMsg): _174.RequestProcessProposal;
            fromProtoMsg(message: _174.RequestProcessProposalProtoMsg): _174.RequestProcessProposal;
            toProto(message: _174.RequestProcessProposal): Uint8Array;
            toProtoMsg(message: _174.RequestProcessProposal): _174.RequestProcessProposalProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _174.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.Response;
            fromPartial(object: Partial<_174.Response>): _174.Response;
            fromAmino(object: _174.ResponseAmino): _174.Response;
            toAmino(message: _174.Response): _174.ResponseAmino;
            fromAminoMsg(object: _174.ResponseAminoMsg): _174.Response;
            fromProtoMsg(message: _174.ResponseProtoMsg): _174.Response;
            toProto(message: _174.Response): Uint8Array;
            toProtoMsg(message: _174.Response): _174.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _174.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseException;
            fromPartial(object: Partial<_174.ResponseException>): _174.ResponseException;
            fromAmino(object: _174.ResponseExceptionAmino): _174.ResponseException;
            toAmino(message: _174.ResponseException): _174.ResponseExceptionAmino;
            fromAminoMsg(object: _174.ResponseExceptionAminoMsg): _174.ResponseException;
            fromProtoMsg(message: _174.ResponseExceptionProtoMsg): _174.ResponseException;
            toProto(message: _174.ResponseException): Uint8Array;
            toProtoMsg(message: _174.ResponseException): _174.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _174.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseEcho;
            fromPartial(object: Partial<_174.ResponseEcho>): _174.ResponseEcho;
            fromAmino(object: _174.ResponseEchoAmino): _174.ResponseEcho;
            toAmino(message: _174.ResponseEcho): _174.ResponseEchoAmino;
            fromAminoMsg(object: _174.ResponseEchoAminoMsg): _174.ResponseEcho;
            fromProtoMsg(message: _174.ResponseEchoProtoMsg): _174.ResponseEcho;
            toProto(message: _174.ResponseEcho): Uint8Array;
            toProtoMsg(message: _174.ResponseEcho): _174.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _174.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(_: any): _174.ResponseFlush;
            fromPartial(_: Partial<_174.ResponseFlush>): _174.ResponseFlush;
            fromAmino(_: _174.ResponseFlushAmino): _174.ResponseFlush;
            toAmino(_: _174.ResponseFlush): _174.ResponseFlushAmino;
            fromAminoMsg(object: _174.ResponseFlushAminoMsg): _174.ResponseFlush;
            fromProtoMsg(message: _174.ResponseFlushProtoMsg): _174.ResponseFlush;
            toProto(message: _174.ResponseFlush): Uint8Array;
            toProtoMsg(message: _174.ResponseFlush): _174.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _174.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseInfo;
            fromPartial(object: Partial<_174.ResponseInfo>): _174.ResponseInfo;
            fromAmino(object: _174.ResponseInfoAmino): _174.ResponseInfo;
            toAmino(message: _174.ResponseInfo): _174.ResponseInfoAmino;
            fromAminoMsg(object: _174.ResponseInfoAminoMsg): _174.ResponseInfo;
            fromProtoMsg(message: _174.ResponseInfoProtoMsg): _174.ResponseInfo;
            toProto(message: _174.ResponseInfo): Uint8Array;
            toProtoMsg(message: _174.ResponseInfo): _174.ResponseInfoProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _174.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseInitChain;
            fromPartial(object: Partial<_174.ResponseInitChain>): _174.ResponseInitChain;
            fromAmino(object: _174.ResponseInitChainAmino): _174.ResponseInitChain;
            toAmino(message: _174.ResponseInitChain): _174.ResponseInitChainAmino;
            fromAminoMsg(object: _174.ResponseInitChainAminoMsg): _174.ResponseInitChain;
            fromProtoMsg(message: _174.ResponseInitChainProtoMsg): _174.ResponseInitChain;
            toProto(message: _174.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _174.ResponseInitChain): _174.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _174.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseQuery;
            fromPartial(object: Partial<_174.ResponseQuery>): _174.ResponseQuery;
            fromAmino(object: _174.ResponseQueryAmino): _174.ResponseQuery;
            toAmino(message: _174.ResponseQuery): _174.ResponseQueryAmino;
            fromAminoMsg(object: _174.ResponseQueryAminoMsg): _174.ResponseQuery;
            fromProtoMsg(message: _174.ResponseQueryProtoMsg): _174.ResponseQuery;
            toProto(message: _174.ResponseQuery): Uint8Array;
            toProtoMsg(message: _174.ResponseQuery): _174.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _174.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseBeginBlock;
            fromPartial(object: Partial<_174.ResponseBeginBlock>): _174.ResponseBeginBlock;
            fromAmino(object: _174.ResponseBeginBlockAmino): _174.ResponseBeginBlock;
            toAmino(message: _174.ResponseBeginBlock): _174.ResponseBeginBlockAmino;
            fromAminoMsg(object: _174.ResponseBeginBlockAminoMsg): _174.ResponseBeginBlock;
            fromProtoMsg(message: _174.ResponseBeginBlockProtoMsg): _174.ResponseBeginBlock;
            toProto(message: _174.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _174.ResponseBeginBlock): _174.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _174.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseCheckTx;
            fromPartial(object: Partial<_174.ResponseCheckTx>): _174.ResponseCheckTx;
            fromAmino(object: _174.ResponseCheckTxAmino): _174.ResponseCheckTx;
            toAmino(message: _174.ResponseCheckTx): _174.ResponseCheckTxAmino;
            fromAminoMsg(object: _174.ResponseCheckTxAminoMsg): _174.ResponseCheckTx;
            fromProtoMsg(message: _174.ResponseCheckTxProtoMsg): _174.ResponseCheckTx;
            toProto(message: _174.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _174.ResponseCheckTx): _174.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _174.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseDeliverTx;
            fromPartial(object: Partial<_174.ResponseDeliverTx>): _174.ResponseDeliverTx;
            fromAmino(object: _174.ResponseDeliverTxAmino): _174.ResponseDeliverTx;
            toAmino(message: _174.ResponseDeliverTx): _174.ResponseDeliverTxAmino;
            fromAminoMsg(object: _174.ResponseDeliverTxAminoMsg): _174.ResponseDeliverTx;
            fromProtoMsg(message: _174.ResponseDeliverTxProtoMsg): _174.ResponseDeliverTx;
            toProto(message: _174.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _174.ResponseDeliverTx): _174.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _174.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseEndBlock;
            fromPartial(object: Partial<_174.ResponseEndBlock>): _174.ResponseEndBlock;
            fromAmino(object: _174.ResponseEndBlockAmino): _174.ResponseEndBlock;
            toAmino(message: _174.ResponseEndBlock): _174.ResponseEndBlockAmino;
            fromAminoMsg(object: _174.ResponseEndBlockAminoMsg): _174.ResponseEndBlock;
            fromProtoMsg(message: _174.ResponseEndBlockProtoMsg): _174.ResponseEndBlock;
            toProto(message: _174.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _174.ResponseEndBlock): _174.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _174.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseCommit;
            fromPartial(object: Partial<_174.ResponseCommit>): _174.ResponseCommit;
            fromAmino(object: _174.ResponseCommitAmino): _174.ResponseCommit;
            toAmino(message: _174.ResponseCommit): _174.ResponseCommitAmino;
            fromAminoMsg(object: _174.ResponseCommitAminoMsg): _174.ResponseCommit;
            fromProtoMsg(message: _174.ResponseCommitProtoMsg): _174.ResponseCommit;
            toProto(message: _174.ResponseCommit): Uint8Array;
            toProtoMsg(message: _174.ResponseCommit): _174.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _174.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseListSnapshots;
            fromPartial(object: Partial<_174.ResponseListSnapshots>): _174.ResponseListSnapshots;
            fromAmino(object: _174.ResponseListSnapshotsAmino): _174.ResponseListSnapshots;
            toAmino(message: _174.ResponseListSnapshots): _174.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _174.ResponseListSnapshotsAminoMsg): _174.ResponseListSnapshots;
            fromProtoMsg(message: _174.ResponseListSnapshotsProtoMsg): _174.ResponseListSnapshots;
            toProto(message: _174.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _174.ResponseListSnapshots): _174.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _174.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseOfferSnapshot;
            fromPartial(object: Partial<_174.ResponseOfferSnapshot>): _174.ResponseOfferSnapshot;
            fromAmino(object: _174.ResponseOfferSnapshotAmino): _174.ResponseOfferSnapshot;
            toAmino(message: _174.ResponseOfferSnapshot): _174.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _174.ResponseOfferSnapshotAminoMsg): _174.ResponseOfferSnapshot;
            fromProtoMsg(message: _174.ResponseOfferSnapshotProtoMsg): _174.ResponseOfferSnapshot;
            toProto(message: _174.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _174.ResponseOfferSnapshot): _174.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _174.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseLoadSnapshotChunk;
            fromPartial(object: Partial<_174.ResponseLoadSnapshotChunk>): _174.ResponseLoadSnapshotChunk;
            fromAmino(object: _174.ResponseLoadSnapshotChunkAmino): _174.ResponseLoadSnapshotChunk;
            toAmino(message: _174.ResponseLoadSnapshotChunk): _174.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _174.ResponseLoadSnapshotChunkAminoMsg): _174.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _174.ResponseLoadSnapshotChunkProtoMsg): _174.ResponseLoadSnapshotChunk;
            toProto(message: _174.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _174.ResponseLoadSnapshotChunk): _174.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _174.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseApplySnapshotChunk;
            fromPartial(object: Partial<_174.ResponseApplySnapshotChunk>): _174.ResponseApplySnapshotChunk;
            fromAmino(object: _174.ResponseApplySnapshotChunkAmino): _174.ResponseApplySnapshotChunk;
            toAmino(message: _174.ResponseApplySnapshotChunk): _174.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _174.ResponseApplySnapshotChunkAminoMsg): _174.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _174.ResponseApplySnapshotChunkProtoMsg): _174.ResponseApplySnapshotChunk;
            toProto(message: _174.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _174.ResponseApplySnapshotChunk): _174.ResponseApplySnapshotChunkProtoMsg;
        };
        ResponsePrepareProposal: {
            typeUrl: string;
            encode(message: _174.ResponsePrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponsePrepareProposal;
            fromPartial(object: Partial<_174.ResponsePrepareProposal>): _174.ResponsePrepareProposal;
            fromAmino(object: _174.ResponsePrepareProposalAmino): _174.ResponsePrepareProposal;
            toAmino(message: _174.ResponsePrepareProposal): _174.ResponsePrepareProposalAmino;
            fromAminoMsg(object: _174.ResponsePrepareProposalAminoMsg): _174.ResponsePrepareProposal;
            fromProtoMsg(message: _174.ResponsePrepareProposalProtoMsg): _174.ResponsePrepareProposal;
            toProto(message: _174.ResponsePrepareProposal): Uint8Array;
            toProtoMsg(message: _174.ResponsePrepareProposal): _174.ResponsePrepareProposalProtoMsg;
        };
        ResponseProcessProposal: {
            typeUrl: string;
            encode(message: _174.ResponseProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ResponseProcessProposal;
            fromPartial(object: Partial<_174.ResponseProcessProposal>): _174.ResponseProcessProposal;
            fromAmino(object: _174.ResponseProcessProposalAmino): _174.ResponseProcessProposal;
            toAmino(message: _174.ResponseProcessProposal): _174.ResponseProcessProposalAmino;
            fromAminoMsg(object: _174.ResponseProcessProposalAminoMsg): _174.ResponseProcessProposal;
            fromProtoMsg(message: _174.ResponseProcessProposalProtoMsg): _174.ResponseProcessProposal;
            toProto(message: _174.ResponseProcessProposal): Uint8Array;
            toProtoMsg(message: _174.ResponseProcessProposal): _174.ResponseProcessProposalProtoMsg;
        };
        CommitInfo: {
            typeUrl: string;
            encode(message: _174.CommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.CommitInfo;
            fromPartial(object: Partial<_174.CommitInfo>): _174.CommitInfo;
            fromAmino(object: _174.CommitInfoAmino): _174.CommitInfo;
            toAmino(message: _174.CommitInfo): _174.CommitInfoAmino;
            fromAminoMsg(object: _174.CommitInfoAminoMsg): _174.CommitInfo;
            fromProtoMsg(message: _174.CommitInfoProtoMsg): _174.CommitInfo;
            toProto(message: _174.CommitInfo): Uint8Array;
            toProtoMsg(message: _174.CommitInfo): _174.CommitInfoProtoMsg;
        };
        ExtendedCommitInfo: {
            typeUrl: string;
            encode(message: _174.ExtendedCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ExtendedCommitInfo;
            fromPartial(object: Partial<_174.ExtendedCommitInfo>): _174.ExtendedCommitInfo;
            fromAmino(object: _174.ExtendedCommitInfoAmino): _174.ExtendedCommitInfo;
            toAmino(message: _174.ExtendedCommitInfo): _174.ExtendedCommitInfoAmino;
            fromAminoMsg(object: _174.ExtendedCommitInfoAminoMsg): _174.ExtendedCommitInfo;
            fromProtoMsg(message: _174.ExtendedCommitInfoProtoMsg): _174.ExtendedCommitInfo;
            toProto(message: _174.ExtendedCommitInfo): Uint8Array;
            toProtoMsg(message: _174.ExtendedCommitInfo): _174.ExtendedCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _174.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.Event;
            fromPartial(object: Partial<_174.Event>): _174.Event;
            fromAmino(object: _174.EventAmino): _174.Event;
            toAmino(message: _174.Event): _174.EventAmino;
            fromAminoMsg(object: _174.EventAminoMsg): _174.Event;
            fromProtoMsg(message: _174.EventProtoMsg): _174.Event;
            toProto(message: _174.Event): Uint8Array;
            toProtoMsg(message: _174.Event): _174.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _174.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.EventAttribute;
            fromPartial(object: Partial<_174.EventAttribute>): _174.EventAttribute;
            fromAmino(object: _174.EventAttributeAmino): _174.EventAttribute;
            toAmino(message: _174.EventAttribute): _174.EventAttributeAmino;
            fromAminoMsg(object: _174.EventAttributeAminoMsg): _174.EventAttribute;
            fromProtoMsg(message: _174.EventAttributeProtoMsg): _174.EventAttribute;
            toProto(message: _174.EventAttribute): Uint8Array;
            toProtoMsg(message: _174.EventAttribute): _174.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _174.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.TxResult;
            fromPartial(object: Partial<_174.TxResult>): _174.TxResult;
            fromAmino(object: _174.TxResultAmino): _174.TxResult;
            toAmino(message: _174.TxResult): _174.TxResultAmino;
            fromAminoMsg(object: _174.TxResultAminoMsg): _174.TxResult;
            fromProtoMsg(message: _174.TxResultProtoMsg): _174.TxResult;
            toProto(message: _174.TxResult): Uint8Array;
            toProtoMsg(message: _174.TxResult): _174.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _174.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.Validator;
            fromPartial(object: Partial<_174.Validator>): _174.Validator;
            fromAmino(object: _174.ValidatorAmino): _174.Validator;
            toAmino(message: _174.Validator): _174.ValidatorAmino;
            fromAminoMsg(object: _174.ValidatorAminoMsg): _174.Validator;
            fromProtoMsg(message: _174.ValidatorProtoMsg): _174.Validator;
            toProto(message: _174.Validator): Uint8Array;
            toProtoMsg(message: _174.Validator): _174.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _174.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ValidatorUpdate;
            fromPartial(object: Partial<_174.ValidatorUpdate>): _174.ValidatorUpdate;
            fromAmino(object: _174.ValidatorUpdateAmino): _174.ValidatorUpdate;
            toAmino(message: _174.ValidatorUpdate): _174.ValidatorUpdateAmino;
            fromAminoMsg(object: _174.ValidatorUpdateAminoMsg): _174.ValidatorUpdate;
            fromProtoMsg(message: _174.ValidatorUpdateProtoMsg): _174.ValidatorUpdate;
            toProto(message: _174.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _174.ValidatorUpdate): _174.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _174.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.VoteInfo;
            fromPartial(object: Partial<_174.VoteInfo>): _174.VoteInfo;
            fromAmino(object: _174.VoteInfoAmino): _174.VoteInfo;
            toAmino(message: _174.VoteInfo): _174.VoteInfoAmino;
            fromAminoMsg(object: _174.VoteInfoAminoMsg): _174.VoteInfo;
            fromProtoMsg(message: _174.VoteInfoProtoMsg): _174.VoteInfo;
            toProto(message: _174.VoteInfo): Uint8Array;
            toProtoMsg(message: _174.VoteInfo): _174.VoteInfoProtoMsg;
        };
        ExtendedVoteInfo: {
            typeUrl: string;
            encode(message: _174.ExtendedVoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.ExtendedVoteInfo;
            fromPartial(object: Partial<_174.ExtendedVoteInfo>): _174.ExtendedVoteInfo;
            fromAmino(object: _174.ExtendedVoteInfoAmino): _174.ExtendedVoteInfo;
            toAmino(message: _174.ExtendedVoteInfo): _174.ExtendedVoteInfoAmino;
            fromAminoMsg(object: _174.ExtendedVoteInfoAminoMsg): _174.ExtendedVoteInfo;
            fromProtoMsg(message: _174.ExtendedVoteInfoProtoMsg): _174.ExtendedVoteInfo;
            toProto(message: _174.ExtendedVoteInfo): Uint8Array;
            toProtoMsg(message: _174.ExtendedVoteInfo): _174.ExtendedVoteInfoProtoMsg;
        };
        Misbehavior: {
            typeUrl: string;
            encode(message: _174.Misbehavior, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.Misbehavior;
            fromPartial(object: Partial<_174.Misbehavior>): _174.Misbehavior;
            fromAmino(object: _174.MisbehaviorAmino): _174.Misbehavior;
            toAmino(message: _174.Misbehavior): _174.MisbehaviorAmino;
            fromAminoMsg(object: _174.MisbehaviorAminoMsg): _174.Misbehavior;
            fromProtoMsg(message: _174.MisbehaviorProtoMsg): _174.Misbehavior;
            toProto(message: _174.Misbehavior): Uint8Array;
            toProtoMsg(message: _174.Misbehavior): _174.MisbehaviorProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _174.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _174.Snapshot;
            fromPartial(object: Partial<_174.Snapshot>): _174.Snapshot;
            fromAmino(object: _174.SnapshotAmino): _174.Snapshot;
            toAmino(message: _174.Snapshot): _174.SnapshotAmino;
            fromAminoMsg(object: _174.SnapshotAminoMsg): _174.Snapshot;
            fromProtoMsg(message: _174.SnapshotProtoMsg): _174.Snapshot;
            toProto(message: _174.Snapshot): Uint8Array;
            toProtoMsg(message: _174.Snapshot): _174.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _176.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _176.Proof;
            fromPartial(object: Partial<_176.Proof>): _176.Proof;
            fromAmino(object: _176.ProofAmino): _176.Proof;
            toAmino(message: _176.Proof): _176.ProofAmino;
            fromAminoMsg(object: _176.ProofAminoMsg): _176.Proof;
            fromProtoMsg(message: _176.ProofProtoMsg): _176.Proof;
            toProto(message: _176.Proof): Uint8Array;
            toProtoMsg(message: _176.Proof): _176.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _176.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _176.ValueOp;
            fromPartial(object: Partial<_176.ValueOp>): _176.ValueOp;
            fromAmino(object: _176.ValueOpAmino): _176.ValueOp;
            toAmino(message: _176.ValueOp): _176.ValueOpAmino;
            fromAminoMsg(object: _176.ValueOpAminoMsg): _176.ValueOp;
            fromProtoMsg(message: _176.ValueOpProtoMsg): _176.ValueOp;
            toProto(message: _176.ValueOp): Uint8Array;
            toProtoMsg(message: _176.ValueOp): _176.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _176.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _176.DominoOp;
            fromPartial(object: Partial<_176.DominoOp>): _176.DominoOp;
            fromAmino(object: _176.DominoOpAmino): _176.DominoOp;
            toAmino(message: _176.DominoOp): _176.DominoOpAmino;
            fromAminoMsg(object: _176.DominoOpAminoMsg): _176.DominoOp;
            fromProtoMsg(message: _176.DominoOpProtoMsg): _176.DominoOp;
            toProto(message: _176.DominoOp): Uint8Array;
            toProtoMsg(message: _176.DominoOp): _176.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _176.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _176.ProofOp;
            fromPartial(object: Partial<_176.ProofOp>): _176.ProofOp;
            fromAmino(object: _176.ProofOpAmino): _176.ProofOp;
            toAmino(message: _176.ProofOp): _176.ProofOpAmino;
            fromAminoMsg(object: _176.ProofOpAminoMsg): _176.ProofOp;
            fromProtoMsg(message: _176.ProofOpProtoMsg): _176.ProofOp;
            toProto(message: _176.ProofOp): Uint8Array;
            toProtoMsg(message: _176.ProofOp): _176.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _176.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _176.ProofOps;
            fromPartial(object: Partial<_176.ProofOps>): _176.ProofOps;
            fromAmino(object: _176.ProofOpsAmino): _176.ProofOps;
            toAmino(message: _176.ProofOps): _176.ProofOpsAmino;
            fromAminoMsg(object: _176.ProofOpsAminoMsg): _176.ProofOps;
            fromProtoMsg(message: _176.ProofOpsProtoMsg): _176.ProofOps;
            toProto(message: _176.ProofOps): Uint8Array;
            toProtoMsg(message: _176.ProofOps): _176.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _175.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _175.PublicKey;
            fromPartial(object: Partial<_175.PublicKey>): _175.PublicKey;
            fromAmino(object: _175.PublicKeyAmino): _175.PublicKey;
            toAmino(message: _175.PublicKey): _175.PublicKeyAmino;
            fromAminoMsg(object: _175.PublicKeyAminoMsg): _175.PublicKey;
            fromProtoMsg(message: _175.PublicKeyProtoMsg): _175.PublicKey;
            toProto(message: _175.PublicKey): Uint8Array;
            toProtoMsg(message: _175.PublicKey): _175.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _177.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                fromJSON(object: any): _177.BitArray;
                fromPartial(object: Partial<_177.BitArray>): _177.BitArray;
                fromAmino(object: _177.BitArrayAmino): _177.BitArray;
                toAmino(message: _177.BitArray): _177.BitArrayAmino;
                fromAminoMsg(object: _177.BitArrayAminoMsg): _177.BitArray;
                fromProtoMsg(message: _177.BitArrayProtoMsg): _177.BitArray;
                toProto(message: _177.BitArray): Uint8Array;
                toProtoMsg(message: _177.BitArray): _177.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _178.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.NetAddress;
            fromPartial(object: Partial<_178.NetAddress>): _178.NetAddress;
            fromAmino(object: _178.NetAddressAmino): _178.NetAddress;
            toAmino(message: _178.NetAddress): _178.NetAddressAmino;
            fromAminoMsg(object: _178.NetAddressAminoMsg): _178.NetAddress;
            fromProtoMsg(message: _178.NetAddressProtoMsg): _178.NetAddress;
            toProto(message: _178.NetAddress): Uint8Array;
            toProtoMsg(message: _178.NetAddress): _178.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _178.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.ProtocolVersion;
            fromPartial(object: Partial<_178.ProtocolVersion>): _178.ProtocolVersion;
            fromAmino(object: _178.ProtocolVersionAmino): _178.ProtocolVersion;
            toAmino(message: _178.ProtocolVersion): _178.ProtocolVersionAmino;
            fromAminoMsg(object: _178.ProtocolVersionAminoMsg): _178.ProtocolVersion;
            fromProtoMsg(message: _178.ProtocolVersionProtoMsg): _178.ProtocolVersion;
            toProto(message: _178.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _178.ProtocolVersion): _178.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _178.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.DefaultNodeInfo;
            fromPartial(object: Partial<_178.DefaultNodeInfo>): _178.DefaultNodeInfo;
            fromAmino(object: _178.DefaultNodeInfoAmino): _178.DefaultNodeInfo;
            toAmino(message: _178.DefaultNodeInfo): _178.DefaultNodeInfoAmino;
            fromAminoMsg(object: _178.DefaultNodeInfoAminoMsg): _178.DefaultNodeInfo;
            fromProtoMsg(message: _178.DefaultNodeInfoProtoMsg): _178.DefaultNodeInfo;
            toProto(message: _178.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _178.DefaultNodeInfo): _178.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _178.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _178.DefaultNodeInfoOther;
            fromPartial(object: Partial<_178.DefaultNodeInfoOther>): _178.DefaultNodeInfoOther;
            fromAmino(object: _178.DefaultNodeInfoOtherAmino): _178.DefaultNodeInfoOther;
            toAmino(message: _178.DefaultNodeInfoOther): _178.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _178.DefaultNodeInfoOtherAminoMsg): _178.DefaultNodeInfoOther;
            fromProtoMsg(message: _178.DefaultNodeInfoOtherProtoMsg): _178.DefaultNodeInfoOther;
            toProto(message: _178.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _178.DefaultNodeInfoOther): _178.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _183.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _183.ValidatorSet;
            fromPartial(object: Partial<_183.ValidatorSet>): _183.ValidatorSet;
            fromAmino(object: _183.ValidatorSetAmino): _183.ValidatorSet;
            toAmino(message: _183.ValidatorSet): _183.ValidatorSetAmino;
            fromAminoMsg(object: _183.ValidatorSetAminoMsg): _183.ValidatorSet;
            fromProtoMsg(message: _183.ValidatorSetProtoMsg): _183.ValidatorSet;
            toProto(message: _183.ValidatorSet): Uint8Array;
            toProtoMsg(message: _183.ValidatorSet): _183.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _183.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _183.Validator;
            fromPartial(object: Partial<_183.Validator>): _183.Validator;
            fromAmino(object: _183.ValidatorAmino): _183.Validator;
            toAmino(message: _183.Validator): _183.ValidatorAmino;
            fromAminoMsg(object: _183.ValidatorAminoMsg): _183.Validator;
            fromProtoMsg(message: _183.ValidatorProtoMsg): _183.Validator;
            toProto(message: _183.Validator): Uint8Array;
            toProtoMsg(message: _183.Validator): _183.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _183.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _183.SimpleValidator;
            fromPartial(object: Partial<_183.SimpleValidator>): _183.SimpleValidator;
            fromAmino(object: _183.SimpleValidatorAmino): _183.SimpleValidator;
            toAmino(message: _183.SimpleValidator): _183.SimpleValidatorAmino;
            fromAminoMsg(object: _183.SimpleValidatorAminoMsg): _183.SimpleValidator;
            fromProtoMsg(message: _183.SimpleValidatorProtoMsg): _183.SimpleValidator;
            toProto(message: _183.SimpleValidator): Uint8Array;
            toProtoMsg(message: _183.SimpleValidator): _183.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _182.BlockIDFlag;
        blockIDFlagToJSON(object: _182.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _182.SignedMsgType;
        signedMsgTypeToJSON(object: _182.SignedMsgType): string;
        BlockIDFlag: typeof _182.BlockIDFlag;
        BlockIDFlagSDKType: typeof _182.BlockIDFlag;
        BlockIDFlagAmino: typeof _182.BlockIDFlag;
        SignedMsgType: typeof _182.SignedMsgType;
        SignedMsgTypeSDKType: typeof _182.SignedMsgType;
        SignedMsgTypeAmino: typeof _182.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _182.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.PartSetHeader;
            fromPartial(object: Partial<_182.PartSetHeader>): _182.PartSetHeader;
            fromAmino(object: _182.PartSetHeaderAmino): _182.PartSetHeader;
            toAmino(message: _182.PartSetHeader): _182.PartSetHeaderAmino;
            fromAminoMsg(object: _182.PartSetHeaderAminoMsg): _182.PartSetHeader;
            fromProtoMsg(message: _182.PartSetHeaderProtoMsg): _182.PartSetHeader;
            toProto(message: _182.PartSetHeader): Uint8Array;
            toProtoMsg(message: _182.PartSetHeader): _182.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _182.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.Part;
            fromPartial(object: Partial<_182.Part>): _182.Part;
            fromAmino(object: _182.PartAmino): _182.Part;
            toAmino(message: _182.Part): _182.PartAmino;
            fromAminoMsg(object: _182.PartAminoMsg): _182.Part;
            fromProtoMsg(message: _182.PartProtoMsg): _182.Part;
            toProto(message: _182.Part): Uint8Array;
            toProtoMsg(message: _182.Part): _182.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _182.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.BlockID;
            fromPartial(object: Partial<_182.BlockID>): _182.BlockID;
            fromAmino(object: _182.BlockIDAmino): _182.BlockID;
            toAmino(message: _182.BlockID): _182.BlockIDAmino;
            fromAminoMsg(object: _182.BlockIDAminoMsg): _182.BlockID;
            fromProtoMsg(message: _182.BlockIDProtoMsg): _182.BlockID;
            toProto(message: _182.BlockID): Uint8Array;
            toProtoMsg(message: _182.BlockID): _182.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _182.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.Header;
            fromPartial(object: Partial<_182.Header>): _182.Header;
            fromAmino(object: _182.HeaderAmino): _182.Header;
            toAmino(message: _182.Header): _182.HeaderAmino;
            fromAminoMsg(object: _182.HeaderAminoMsg): _182.Header;
            fromProtoMsg(message: _182.HeaderProtoMsg): _182.Header;
            toProto(message: _182.Header): Uint8Array;
            toProtoMsg(message: _182.Header): _182.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _182.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.Data;
            fromPartial(object: Partial<_182.Data>): _182.Data;
            fromAmino(object: _182.DataAmino): _182.Data;
            toAmino(message: _182.Data): _182.DataAmino;
            fromAminoMsg(object: _182.DataAminoMsg): _182.Data;
            fromProtoMsg(message: _182.DataProtoMsg): _182.Data;
            toProto(message: _182.Data): Uint8Array;
            toProtoMsg(message: _182.Data): _182.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _182.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.Vote;
            fromPartial(object: Partial<_182.Vote>): _182.Vote;
            fromAmino(object: _182.VoteAmino): _182.Vote;
            toAmino(message: _182.Vote): _182.VoteAmino;
            fromAminoMsg(object: _182.VoteAminoMsg): _182.Vote;
            fromProtoMsg(message: _182.VoteProtoMsg): _182.Vote;
            toProto(message: _182.Vote): Uint8Array;
            toProtoMsg(message: _182.Vote): _182.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _182.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.Commit;
            fromPartial(object: Partial<_182.Commit>): _182.Commit;
            fromAmino(object: _182.CommitAmino): _182.Commit;
            toAmino(message: _182.Commit): _182.CommitAmino;
            fromAminoMsg(object: _182.CommitAminoMsg): _182.Commit;
            fromProtoMsg(message: _182.CommitProtoMsg): _182.Commit;
            toProto(message: _182.Commit): Uint8Array;
            toProtoMsg(message: _182.Commit): _182.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _182.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.CommitSig;
            fromPartial(object: Partial<_182.CommitSig>): _182.CommitSig;
            fromAmino(object: _182.CommitSigAmino): _182.CommitSig;
            toAmino(message: _182.CommitSig): _182.CommitSigAmino;
            fromAminoMsg(object: _182.CommitSigAminoMsg): _182.CommitSig;
            fromProtoMsg(message: _182.CommitSigProtoMsg): _182.CommitSig;
            toProto(message: _182.CommitSig): Uint8Array;
            toProtoMsg(message: _182.CommitSig): _182.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _182.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.Proposal;
            fromPartial(object: Partial<_182.Proposal>): _182.Proposal;
            fromAmino(object: _182.ProposalAmino): _182.Proposal;
            toAmino(message: _182.Proposal): _182.ProposalAmino;
            fromAminoMsg(object: _182.ProposalAminoMsg): _182.Proposal;
            fromProtoMsg(message: _182.ProposalProtoMsg): _182.Proposal;
            toProto(message: _182.Proposal): Uint8Array;
            toProtoMsg(message: _182.Proposal): _182.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _182.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.SignedHeader;
            fromPartial(object: Partial<_182.SignedHeader>): _182.SignedHeader;
            fromAmino(object: _182.SignedHeaderAmino): _182.SignedHeader;
            toAmino(message: _182.SignedHeader): _182.SignedHeaderAmino;
            fromAminoMsg(object: _182.SignedHeaderAminoMsg): _182.SignedHeader;
            fromProtoMsg(message: _182.SignedHeaderProtoMsg): _182.SignedHeader;
            toProto(message: _182.SignedHeader): Uint8Array;
            toProtoMsg(message: _182.SignedHeader): _182.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _182.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.LightBlock;
            fromPartial(object: Partial<_182.LightBlock>): _182.LightBlock;
            fromAmino(object: _182.LightBlockAmino): _182.LightBlock;
            toAmino(message: _182.LightBlock): _182.LightBlockAmino;
            fromAminoMsg(object: _182.LightBlockAminoMsg): _182.LightBlock;
            fromProtoMsg(message: _182.LightBlockProtoMsg): _182.LightBlock;
            toProto(message: _182.LightBlock): Uint8Array;
            toProtoMsg(message: _182.LightBlock): _182.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _182.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.BlockMeta;
            fromPartial(object: Partial<_182.BlockMeta>): _182.BlockMeta;
            fromAmino(object: _182.BlockMetaAmino): _182.BlockMeta;
            toAmino(message: _182.BlockMeta): _182.BlockMetaAmino;
            fromAminoMsg(object: _182.BlockMetaAminoMsg): _182.BlockMeta;
            fromProtoMsg(message: _182.BlockMetaProtoMsg): _182.BlockMeta;
            toProto(message: _182.BlockMeta): Uint8Array;
            toProtoMsg(message: _182.BlockMeta): _182.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _182.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _182.TxProof;
            fromPartial(object: Partial<_182.TxProof>): _182.TxProof;
            fromAmino(object: _182.TxProofAmino): _182.TxProof;
            toAmino(message: _182.TxProof): _182.TxProofAmino;
            fromAminoMsg(object: _182.TxProofAminoMsg): _182.TxProof;
            fromProtoMsg(message: _182.TxProofProtoMsg): _182.TxProof;
            toProto(message: _182.TxProof): Uint8Array;
            toProtoMsg(message: _182.TxProof): _182.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _181.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _181.ConsensusParams;
            fromPartial(object: Partial<_181.ConsensusParams>): _181.ConsensusParams;
            fromAmino(object: _181.ConsensusParamsAmino): _181.ConsensusParams;
            toAmino(message: _181.ConsensusParams): _181.ConsensusParamsAmino;
            fromAminoMsg(object: _181.ConsensusParamsAminoMsg): _181.ConsensusParams;
            fromProtoMsg(message: _181.ConsensusParamsProtoMsg): _181.ConsensusParams;
            toProto(message: _181.ConsensusParams): Uint8Array;
            toProtoMsg(message: _181.ConsensusParams): _181.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _181.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _181.BlockParams;
            fromPartial(object: Partial<_181.BlockParams>): _181.BlockParams;
            fromAmino(object: _181.BlockParamsAmino): _181.BlockParams;
            toAmino(message: _181.BlockParams): _181.BlockParamsAmino;
            fromAminoMsg(object: _181.BlockParamsAminoMsg): _181.BlockParams;
            fromProtoMsg(message: _181.BlockParamsProtoMsg): _181.BlockParams;
            toProto(message: _181.BlockParams): Uint8Array;
            toProtoMsg(message: _181.BlockParams): _181.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _181.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _181.EvidenceParams;
            fromPartial(object: Partial<_181.EvidenceParams>): _181.EvidenceParams;
            fromAmino(object: _181.EvidenceParamsAmino): _181.EvidenceParams;
            toAmino(message: _181.EvidenceParams): _181.EvidenceParamsAmino;
            fromAminoMsg(object: _181.EvidenceParamsAminoMsg): _181.EvidenceParams;
            fromProtoMsg(message: _181.EvidenceParamsProtoMsg): _181.EvidenceParams;
            toProto(message: _181.EvidenceParams): Uint8Array;
            toProtoMsg(message: _181.EvidenceParams): _181.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _181.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _181.ValidatorParams;
            fromPartial(object: Partial<_181.ValidatorParams>): _181.ValidatorParams;
            fromAmino(object: _181.ValidatorParamsAmino): _181.ValidatorParams;
            toAmino(message: _181.ValidatorParams): _181.ValidatorParamsAmino;
            fromAminoMsg(object: _181.ValidatorParamsAminoMsg): _181.ValidatorParams;
            fromProtoMsg(message: _181.ValidatorParamsProtoMsg): _181.ValidatorParams;
            toProto(message: _181.ValidatorParams): Uint8Array;
            toProtoMsg(message: _181.ValidatorParams): _181.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _181.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _181.VersionParams;
            fromPartial(object: Partial<_181.VersionParams>): _181.VersionParams;
            fromAmino(object: _181.VersionParamsAmino): _181.VersionParams;
            toAmino(message: _181.VersionParams): _181.VersionParamsAmino;
            fromAminoMsg(object: _181.VersionParamsAminoMsg): _181.VersionParams;
            fromProtoMsg(message: _181.VersionParamsProtoMsg): _181.VersionParams;
            toProto(message: _181.VersionParams): Uint8Array;
            toProtoMsg(message: _181.VersionParams): _181.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _181.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _181.HashedParams;
            fromPartial(object: Partial<_181.HashedParams>): _181.HashedParams;
            fromAmino(object: _181.HashedParamsAmino): _181.HashedParams;
            toAmino(message: _181.HashedParams): _181.HashedParamsAmino;
            fromAminoMsg(object: _181.HashedParamsAminoMsg): _181.HashedParams;
            fromProtoMsg(message: _181.HashedParamsProtoMsg): _181.HashedParams;
            toProto(message: _181.HashedParams): Uint8Array;
            toProtoMsg(message: _181.HashedParams): _181.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _180.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.Evidence;
            fromPartial(object: Partial<_180.Evidence>): _180.Evidence;
            fromAmino(object: _180.EvidenceAmino): _180.Evidence;
            toAmino(message: _180.Evidence): _180.EvidenceAmino;
            fromAminoMsg(object: _180.EvidenceAminoMsg): _180.Evidence;
            fromProtoMsg(message: _180.EvidenceProtoMsg): _180.Evidence;
            toProto(message: _180.Evidence): Uint8Array;
            toProtoMsg(message: _180.Evidence): _180.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _180.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.DuplicateVoteEvidence;
            fromPartial(object: Partial<_180.DuplicateVoteEvidence>): _180.DuplicateVoteEvidence;
            fromAmino(object: _180.DuplicateVoteEvidenceAmino): _180.DuplicateVoteEvidence;
            toAmino(message: _180.DuplicateVoteEvidence): _180.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _180.DuplicateVoteEvidenceAminoMsg): _180.DuplicateVoteEvidence;
            fromProtoMsg(message: _180.DuplicateVoteEvidenceProtoMsg): _180.DuplicateVoteEvidence;
            toProto(message: _180.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _180.DuplicateVoteEvidence): _180.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _180.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.LightClientAttackEvidence;
            fromPartial(object: Partial<_180.LightClientAttackEvidence>): _180.LightClientAttackEvidence;
            fromAmino(object: _180.LightClientAttackEvidenceAmino): _180.LightClientAttackEvidence;
            toAmino(message: _180.LightClientAttackEvidence): _180.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _180.LightClientAttackEvidenceAminoMsg): _180.LightClientAttackEvidence;
            fromProtoMsg(message: _180.LightClientAttackEvidenceProtoMsg): _180.LightClientAttackEvidence;
            toProto(message: _180.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _180.LightClientAttackEvidence): _180.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _180.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _180.EvidenceList;
            fromPartial(object: Partial<_180.EvidenceList>): _180.EvidenceList;
            fromAmino(object: _180.EvidenceListAmino): _180.EvidenceList;
            toAmino(message: _180.EvidenceList): _180.EvidenceListAmino;
            fromAminoMsg(object: _180.EvidenceListAminoMsg): _180.EvidenceList;
            fromProtoMsg(message: _180.EvidenceListProtoMsg): _180.EvidenceList;
            toProto(message: _180.EvidenceList): Uint8Array;
            toProtoMsg(message: _180.EvidenceList): _180.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _179.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _179.Block;
            fromPartial(object: Partial<_179.Block>): _179.Block;
            fromAmino(object: _179.BlockAmino): _179.Block;
            toAmino(message: _179.Block): _179.BlockAmino;
            fromAminoMsg(object: _179.BlockAminoMsg): _179.Block;
            fromProtoMsg(message: _179.BlockProtoMsg): _179.Block;
            toProto(message: _179.Block): Uint8Array;
            toProtoMsg(message: _179.Block): _179.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _184.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _184.App;
            fromPartial(object: Partial<_184.App>): _184.App;
            fromAmino(object: _184.AppAmino): _184.App;
            toAmino(message: _184.App): _184.AppAmino;
            fromAminoMsg(object: _184.AppAminoMsg): _184.App;
            fromProtoMsg(message: _184.AppProtoMsg): _184.App;
            toProto(message: _184.App): Uint8Array;
            toProtoMsg(message: _184.App): _184.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _184.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            fromJSON(object: any): _184.Consensus;
            fromPartial(object: Partial<_184.Consensus>): _184.Consensus;
            fromAmino(object: _184.ConsensusAmino): _184.Consensus;
            toAmino(message: _184.Consensus): _184.ConsensusAmino;
            fromAminoMsg(object: _184.ConsensusAminoMsg): _184.Consensus;
            fromProtoMsg(message: _184.ConsensusProtoMsg): _184.Consensus;
            toProto(message: _184.Consensus): Uint8Array;
            toProtoMsg(message: _184.Consensus): _184.ConsensusProtoMsg;
        };
    };
}
